### ISSUE TITLE
SAPT0 for He atoms fails

### ISSUE THREAD

**Issue by PeterKraus** [psi4/psi4#1018]
Using version 1.2-rc2 from conda psi4/label/dev (and also several previous versions):

The following input crashes with a `RuntimeError: Fatal Error: Not enough memory` (logfile [attached](https://github.com/psi4/psi4/files/2000688/sapt0.txt)):

```
molecule dimer {
 0 1
    HE          -3.175580423325    -0.517569032036     0.000000000000
 --
 0 1
    C           -0.047607579372     0.489078465367     0.000000000000
    O           -0.621270272014     1.491611955637     0.000000000000
    S            0.726228977971    -0.864990071157     0.000000000000

 no_reorient
 no_com
}

memory 20 Gb

dimer.update_geometry()
energy("sapt0/jun-cc-pvdz", molecule=dimer)
``` 

When the He atom in the above is changed to, say, Ne, the calculation runs fine.

**Comment by dgasmith** [comment]
Probably bad logic for extremely small computations. Thanks for the report.

**Comment by loriab** [comment]
With 20 GB & helium, available memory overflowed `int`. `long int` seems to be working, but the C++ devs should probably look over my fix.
