### ISSUE TITLE
SCF_TYPE global namespace

### ISSUE THREAD

**Issue by dgasmith** [psi4/psi4#1019]
As mentioned [here](http://forum.psicode.org/t/manual-update-dfocc-requires-scf-type-disk-df/904/3), users can set `scf_type` in the SCF local namespace which will really mess with a great deal of our logic. I think this should be extracted and placed in globals only similar to `CC_TYPE` and the like. @loriab any thoughts?

```
set scf {
 scf_type df
}
energy('ccsd(t)/aug-cc-pvtz')
```

**Comment by loriab** [comment]
I approve of the extraction to globals, as every other *_type is such. Cphf is the only other module using scf_type.
