### ISSUE TITLE
Restart from previous rhf calculation

### ISSUE THREAD

**Issue by wpoely86** [psi4/psi4#102]
It's not clear to me if it's possible to start from a previous calculated rhf result to do for example ccsd(t). Can this be done? If I keep the scratch dir, and use the `-r` parameters with `guess read`, it will start from the rhf solution of the previous run, but it will still do the rhf calculation and integral transformations. I would like it to directly start with the ccsd(t) calculation, and not redo the rhf calculation. Is this currently possible?

**Comment by loriab** [comment]
There's a bypass_scf=True argument to energy() that may help. Look in proc.py if I don't have the syntax quite right.

**Comment by wpoely86** [comment]
Unfortunately, that causes a crash. The `transqt2` starts but fails:
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000012fd9df in psi::transqt2::get_moinfo (options=...) at /home/ward/tmp/psi4release/src/bin/transqt2/get_moinfo.cc:114
114	     moinfo.frdocc[h] = Process::environment.wavefunction()->frzcpi()[h];
```

Seems like some things are not properly initialized when bypassing scf?

**Comment by dgasmith** [comment]
@wpoely86 `transqt` has been deprecated. Can you please try this again.

**Comment by dgasmith** [comment]
Closing as `transqt2` has been deprecated. Please let us know if this issue pops up again.
