### ISSUE TITLE
Problems with ADC(2) in Psi4?

### ISSUE THREAD

**Issue by ssh2** [psi4/psi4#1033]
Hi everyone,

I was testing the ADC(2) code in Psi4 on small molecules and noticed that the results I obtained were significantly different from Q-Chem. The SCF and MP2 energies match very well.

For N2 (r = 1.2 A) with cc-pVDZ basis, here's a summary of the energies for the 8 lowest-lying singlet states from Q-Chem 4.4.1 compared to Psi4 1.1:

Q-Chem 4.4.1:
MP2 ground-state energy: -109.2579498247
  Excitation energy:                                               8.385211 eV
  Excitation energy:                                               8.385211 eV
  Excitation energy:                                               8.832813 eV
  Excitation energy:                                               9.441957 eV
  Excitation energy:                                               9.441957 eV
  Excitation energy:                                              13.868446 eV
  Excitation energy:                                              13.868446 eV
  Excitation energy:                                              14.791430 eV

Psi4 1.1: 
MP2 ground-state energy: -109.25794982519506
->	1  A state   :  0.3113289 (a.u.),  8.4716885 (eV)
->	2  A state   :  0.3113289 (a.u.),  8.4716885 (eV)
->	3  A state   :  0.3343892 (a.u.),  9.0991916 (eV)
->	4  A state   :  0.3565394 (a.u.),  9.7019279 (eV)
->	5  A state   :  0.3565394 (a.u.),  9.7019279 (eV)
->	6  A state   :  0.5069575 (a.u.), 13.7950140 (eV)
->	7  A state   :  0.5069575 (a.u.), 13.7950140 (eV)
->	8  A state   :  0.5127312 (a.u.), 13.9521243 (eV)

The Q-Chem energies agree with my standalone code. For N2 with STO-3G basis I simply get zero excitation energies with Psi4:

    ==> ADC(2) Computation <==                       
                                                     
->  1  A state   :  0.0000000 (a.u.),  0.0000000 (eV)
    Non-iterative:  0.3864160 (a.u.), 10.5149136 (eV)
       ┆   ┆ Occ Vir        Coefficient              
    ---------------------------------------------    
                                                     
    Converged in   2 iteration.                      
    Squared norm of the S component:  1.0000000      
    The S vector is rotated up to 90.000 (deg.)      
    #WARNING: Strongly rotated from the CIS state!   
                                                     
->  2  A state   :  0.0000000 (a.u.),  0.0000000 (eV)
    Non-iterative:  0.4145495 (a.u.), 11.2804653 (eV)
       ┆   ┆ Occ Vir        Coefficient              
    ---------------------------------------------    
                                                     
    Converged in   2 iteration.                      
    Squared norm of the S component:  1.0000000      
    The S vector is rotated up to 90.000 (deg.)      
    #WARNING: Strongly rotated from the CIS state!   

Any idea about what's going on? 

My input files for cc-pvdz:

**Psi4:**
molecule {                                
0 1                                       
N     0.000000      0.000000      0.000000
N     0.000000      0.000000      1.200000
symmetry c1                               
}                                         
                                          
set {                                     
basis cc-pvdz                             
guess sad                                 
reference rhf                             
scf_type pk                               
roots_per_irrep [8]                       
}                                         
                                          
set_num_threads(12)                       
energy('adc')                             

**Q-Chem:**
$molecule                  
0 1                        
N 0.0 0.0 0.0              
N 0.0 0.0 1.2              
$end                       
                           
$rem                       
jobtype             sp     
method              adc(2) 
basis               cc-pvdz
mem_total           4000   
mem_static          100    
cc_symmetry         false  
ee_singlets           8    
$end

**Comment by CDSherrill** [comment]
I think the ADC(2) code has some special corrections it can apply, but I
would have thought that those were turned off by default...

**Comment by ssh2** [comment]
It looks like one of the corrections could be the "partial renormalization scheme", but according to the manual it is turned off by default...

I tried using partial renormalization (set pr true) and it is indeed giving different ADC(2) energies:
->	1  A state   :  0.3074681 (a.u.),  8.3666314 (eV)
->	2  A state   :  0.3074681 (a.u.),  8.3666314 (eV)
->	3  A state   :  0.3282148 (a.u.),  8.9311786 (eV)
->	4  A state   :  0.3502345 (a.u.),  9.5303635 (eV)
->	5  A state   :  0.3502345 (a.u.),  9.5303635 (eV)
->	6  A state   :  0.5040061 (a.u.), 13.7147013 (eV)
->	7  A state   :  0.5040061 (a.u.), 13.7147013 (eV)
->	8  A state   :  0.5127427 (a.u.), 13.9524352 (eV)

I wonder if the original problem is related to convergence issues when starting with CIS guess vectors. For all states in N2 the ADC(2) code in Psi4 gives the following warning:
"#WARNING: Strongly rotated from the CIS state!"

**Comment by iliamazin** [comment]
Hello,

I am a graduate student from Dr. Sokolov's lab at The Ohio State University. Over the last week or so, I have run some calculations with both Psi4 (version 1.3.2) and QChem (5.1.1) to hopefully get some information regarding the origin of this problem. All relevant input/output files are attached, in full, to this post.

First, I ran the ADC(1) and ADC(2) tests provided in the test suite of Psi4 in both programs.

The ADC(1) excitation energies match between the two programs:

### **Psi4 1.3.2 energies output**
```
	1  A state:  0.3529478 (a.u.),  9.6041997 (eV)
	2  A state:  0.4215815 (a.u.), 11.4718175 (eV)
	3  A state:  0.4538994 (a.u.), 12.3512305 (eV)
	4  A state:  0.5246003 (a.u.), 14.2751021 (eV)
	5  A state:  0.5709848 (a.u.), 15.5372886 (eV)
	6  A state:  0.7050389 (a.u.), 19.1850862 (eV)
	7  A state:  1.0543763 (a.u.), 28.6910395 (eV)
	8  A state:  1.0720010 (a.u.), 29.1706341 (eV)
	9  A state:  1.1388267 (a.u.), 30.9890538 (eV)
	10  A state:  1.1821020 (a.u.), 32.1666340 (eV)
	11  A state:  1.1875445 (a.u.), 32.3147310 (eV)
	12  A state:  1.1982557 (a.u.), 32.6061991 (eV)
	13  A state:  1.1992474 (a.u.), 32.6331833 (eV)
	14  A state:  1.2585194 (a.u.), 34.2460572 (eV)
	15  A state:  1.2767037 (a.u.), 34.7408785 (eV)
	16  A state:  1.2815731 (a.u.), 34.8733809 (eV)
	17  A state:  1.3132971 (a.u.), 35.7366340 (eV)
	18  A state:  1.3296420 (a.u.), 36.1814011 (eV)
	19  A state:  1.3540510 (a.u.), 36.8456048 (eV)
	20  A state:  1.3585131 (a.u.), 36.9670246 (eV)
```

### **QChem 5.1.1 energies output**
```
  Excitation energy:                                               9.604199 eV
  Excitation energy:                                              11.471817 eV
  Excitation energy:                                              12.351230 eV
  Excitation energy:                                              14.275101 eV
  Excitation energy:                                              15.537288 eV
  Excitation energy:                                              19.185085 eV
  Excitation energy:                                              28.691037 eV
  Excitation energy:                                              29.170632 eV
  Excitation energy:                                              30.989051 eV
  Excitation energy:                                              32.166632 eV
  Excitation energy:                                              32.314728 eV
  Excitation energy:                                              32.606197 eV
  Excitation energy:                                              32.633181 eV
  Excitation energy:                                              34.246055 eV
  Excitation energy:                                              34.740876 eV
  Excitation energy:                                              34.873378 eV
  Excitation energy:                                              35.736631 eV
  Excitation energy:                                              36.181398 eV
  Excitation energy:                                              36.845602 eV
  Excitation energy:                                              36.967022 eV
```

Running the ADC(2) test in both programs showed some slight deviation in energies, but nothing alarming.
### **QChem 5.1.1 - adc(2) test energies**
```
Excitation energy:                                               6.951866 eV
Excitation energy:                                               6.951866 eV
```

### **Psi4 1.3.2 -- adc(2) test energies**
```
->	1  A state   :  0.2557608 (a.u.),  6.9596066 (eV)
      Non-iterative:  0.2559128 (a.u.),  6.9637417 (eV)
->	2  A state   :  0.2557608 (a.u.),  6.9596066 (eV)
      Non-iterative:  0.2559128 (a.u.),  6.9637417 (eV)
```


Further, we set up calculations for the systems in [this work](https://aip.scitation.org/doi/10.1063/1.1504708). Please find the calculations for HF and N2 below; I am happy to provide data on the other systems if needed.
Basis set & geometry information for HF and N2 were found in [this work](https://aip.scitation.org/doi/abs/10.1063/1.1386415).

### **HF**
For ADC(1) results, we continue to see no remarkable error. In the ADC(2) results, the HF system's excitation energies calculated by QChem reproduce the results provided in the Trofimov, Stelter, Schirmer paper. However, the energies provided by Psi4 seem to have an inconsistent deviation from the values: for some states, the energies reported are near exact:
```
Lit:           9.63 eV
Psi4:        9.6455240 eV
QChem:  9.631168 eV
```
for others, the excitation energy deviates as much as 0.08 eV:
```
Lit:          15.33 eV
Psi4:       15.2573251 eV
QChem:  15.318842 eV
```

### **N2**
In the case of the N2 system, we again saw no errors in the ADC(1) results. QChem continues to be able to reproduce excitation energies for ADC(2) calculations, but in Psi4, for several states in the ADC(2) calculation, we see warnings about a strongly rotated CIS state and zero eigenvalues.


### **Psi4 1.3.2 -- N2 ADC(2) excitation energies**
```
1 Ag state   :  0.9479767 (a.u.), 25.7957601 (eV)
2 Ag state   :  1.0193053 (a.u.), 27.7367101 (eV)
#WARNING: Strongly rotated from the CIS state!
3 Ag state   :  1.0706909 (a.u.), 29.1349838 (eV)
#WARNING: Strongly rotated from the CIS state!
4 Ag state   :  1.1395201 (a.u.), 31.0079202 (eV)

1B1g state   :  0.0000000 (a.u.),  0.0000000 (eV)
#WARNING: Strongly rotated from the CIS state!
2B1g state   :  0.0000000 (a.u.),  0.0000000 (eV)
#WARNING: Strongly rotated from the CIS state!
3B1g state   :  0.0000000 (a.u.),  0.0000000 (eV)
#WARNING: Strongly rotated from the CIS state!
4B1g state   :  0.0000000 (a.u.),  0.0000000 (eV)
#WARNING: Strongly rotated from the CIS state!

1B2g state   :  0.3603525 (a.u.),  9.8056918 (eV)
2B2g state   :  0.8939572 (a.u.), 24.3258137 (eV)
3B2g state   :  1.0911018 (a.u.), 29.6903924 (eV)
4B2g state   :  1.1499070 (a.u.), 31.2905619 (eV)

1B3g state   :  0.3603525 (a.u.),  9.8056918 (eV)
2B3g state   :  0.8939572 (a.u.), 24.3258137 (eV)
3B3g state   :  1.0911018 (a.u.), 29.6903924 (eV)
4B3g state   :  1.1499070 (a.u.), 31.2905619 (eV)

1 Au state   :  0.3979835 (a.u.), 10.8296837 (eV)
2 Au state   :  0.4181288 (a.u.), 11.3778645 (eV)
3 Au state   :  1.2424474 (a.u.), 33.8087156 (eV)
4 Au state   :  1.2463377 (a.u.), 33.9145774 (eV)

1B1u state   :  0.4181288 (a.u.), 11.3778645 (eV)
2B1u state   :  0.5947679 (a.u.), 16.1844579 (eV)
3B1u state   :  0.8225723 (a.u.), 22.3833328 (eV)
4B1u state   :  1.1369059 (a.u.), 30.9367845 (eV)

1B2u state   :  0.5317879 (a.u.), 14.4706869 (eV)
2B2u state   :  1.0161418 (a.u.), 27.6506260 (eV)
3B2u state   :  1.0847614 (a.u.), 29.5178612 (eV)
4B2u state   :  1.2061345 (a.u.), 32.8205905 (eV)

1B3u state   :  0.5317879 (a.u.), 14.4706869 (eV)
2B3u state   :  1.0161418 (a.u.), 27.6506260 (eV)
3B3u state   :  1.0847614 (a.u.), 29.5178611 (eV)
4B3u state   :  1.2061345 (a.u.), 32.8205905 (eV)
```

These N2 results lead us to believe that there appears to be a bug in the Psi4 ADC(2) code, as the appearance of zero eigenvalues in the results should not be happening. Further, it is concerning to see non-negligible deviations in ADC(2) energies between the two programs when geometries, basis sets, and ADC(1) energies match.

Best,
Ilia
[psi4_test_adc1_in.txt](https://github.com/psi4/psi4/files/3383908/psi4_test_adc1_in.txt)[ps4_test_adc1_out.txt](https://github.com/psi4/psi4/files/3383907/ps4_test_adc1_out.txt)
[qchem_test_adc1_in.txt](https://github.com/psi4/psi4/files/3383919/qchem_test_adc1_in.txt)
[qchem_test_adc1_out.txt](https://github.com/psi4/psi4/files/3383920/qchem_test_adc1_out.txt)
[psi4_test_adc2_in.txt](https://github.com/psi4/psi4/files/3383926/psi4_test_adc2_in.txt)
[psi4_test_adc2_out.txt](https://github.com/psi4/psi4/files/3383927/psi4_test_adc2_out.txt)
[qchem_test_adc2_in.txt](https://github.com/psi4/psi4/files/3383928/qchem_test_adc2_in.txt)
[qchem_test_adc2_out.txt](https://github.com/psi4/psi4/files/3383929/qchem_test_adc2_out.txt)
[psi4_hf_in.txt](https://github.com/psi4/psi4/files/3383932/psi4_hf_in.txt)
[psi4_hf_out.txt](https://github.com/psi4/psi4/files/3383934/psi4_hf_out.txt)
[qchem_hf_adc1_in.txt](https://github.com/psi4/psi4/files/3383940/qchem_hf_adc1_in.txt)
[qchem_hf_adc1_out.txt](https://github.com/psi4/psi4/files/3383941/qchem_hf_adc1_out.txt)
[qchem_hf_adc2_in.txt](https://github.com/psi4/psi4/files/3383942/qchem_hf_adc2_in.txt)
[qchem_hf_adc2_out.txt](https://github.com/psi4/psi4/files/3383943/qchem_hf_adc2_out.txt)
[psi4_n2_in.txt](https://github.com/psi4/psi4/files/3383945/psi4_n2_in.txt)
[psi4_n2_out.txt](https://github.com/psi4/psi4/files/3383946/psi4_n2_out.txt)
[qchem_n2_adc1_in.txt](https://github.com/psi4/psi4/files/3383967/qchem_n2_adc1_in.txt)
[qchem_n2_adc1_out.txt](https://github.com/psi4/psi4/files/3383968/qchem_n2_adc1_out.txt)
[qchem_n2_adc2_in.txt](https://github.com/psi4/psi4/files/3383969/qchem_n2_adc2_in.txt)
[qchem_n2_adc2_out.txt](https://github.com/psi4/psi4/files/3383970/qchem_n2_adc2_out.txt)

**Comment by dgasmith** [comment]
I am not sure we have anyone currently that is "responsible" for the ADC code. Without someone to step in and attempt to fix this, I am inclined to simply disable the ability to run ADC(2) until we have someone to delve into it.

**Comment by loriab** [comment]
Pinging @msaitow in case he has time to help.

**Comment by loriab** [comment]
Hi @msaitow, I don't believe we ever corresponded directly back when you were adding ADC to Psi4, but I did want to thank you on behalf of all the Psi4 developers for the longstanding functionality. I think your contribution of the ADC module was one of the first prompts to this community that we could develop software in a delocalized fashion and that the early Psi4 codebase could be understood and be a good development platform. There have been a few issues detected with ADC and a capable replacement in ADCC, so I wanted to let you know that we're removing the ADC module with #2737. The code will still be available in https://github.com/psi4/psi4attic and in any version of Psi4 through v1.6.1 . Thanks again!
