### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by ChayaSt** [psi4/psi4#1036]
I installed the latest version of psi4 via conda using the following command: 
```conda install psi4=1.2rc2 psi4-rt python=3.6 -c psi4/label/dev```

When I try to import psi4, I get the following error:
```
In [1]: import psi4
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/anaconda3/lib/python3.6/site-packages/psi4/__init__.py in <module>()
     53 try:
---> 54     from . import core
     55 except ImportError as err:

ImportError: /home/chayas/anaconda3/lib/python3.6/site-packages/psi4/core.so: undefined symbol: __svml_sincos4_l9

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-becb93fbd2ca> in <module>()
----> 1 import psi4

~/anaconda3/lib/python3.6/site-packages/psi4/__init__.py in <module>()
     57         raise ImportError("{0}\nLikely cause: GCC >= 4.9 not in [DY]LD_LIBRARY_PATH".format(err))
     58     else:
---> 59         raise ImportError("{0}".format(err))
     60 
     61 from psi4.core import set_output_file, get_variable, set_variable, get_num_threads, set_num_threads

ImportError: /home/chayas/anaconda3/lib/python3.6/site-packages/psi4/core.so: undefined symbol: __svml_sincos4_l9
```

**Comment by ChayaSt** [comment]
@loriab, it works in a clean environment. 

Thanks!

**Comment by loriab** [comment]
Ok, good. Now that psi4 is up-to-date with cb3 and defaults libraries, it's possible to install it into the base env (that was a bad idea when psi4 was distributing gcc52 alongside), but there's still enough turbulence among the big channels that own env is a safer bet.

Btw, if your base env is longstanding and contains `gcc-5-mp`, that's a non-modern-psi artifact that can be gotten rid of.

**Comment by loriab** [comment]
extra note: `svml` error seems to pop up when switching Intel versions — not pinned down to compiler/mkl/etc.

**Comment by BradenDKelly** [comment]
@loriab did you have an easy fix for the svml error? psi4 was working until I installed rdkit and ambertools, and during the process it seems to have over-rode something. now I have the 

```
Traceback (most recent call last):
  File "/home/user/psi4conda/bin/psi4", line 183, in <module>
    import psi4  # isort:skip
  File "/home/user/psi4conda/lib//python3.8/site-packages/psi4/__init__.py", line 60, in <module>
    raise ImportError("{0}".format(err))
ImportError: /home/user/psi4conda/lib//python3.8/site-packages/psi4/core.cpython-38-x86_64-linux-gnu.so: undefined symbol: __svml_exp4_mask_e9
```
error.

Thanks

**Comment by BradenDKelly** [comment]
@loriab Nevermind, I wanted to reinstall psi4 into `/apps/` anyways, so I did that, put that at the start of `PATH` and it all works now. Not really a solution, but, my kind of solution :)
