### ISSUE TITLE
[solved] DFT convergens fail for XC functionals

### ISSUE THREAD

**Issue by TermeHansen** [psi4/psi4#1054]
For  a simple S2 molecule I get a failure to converge (in the default 100 iterations at least) when using XC functionals (tested with PBE and BP86), but not with hybrid (tested with PBE0)

[S2_PBE.log](https://github.com/psi4/psi4/files/2131171/S2_PBE.log)

sample input file:
```
molecule mol {
 0 1
S       0.0000000000    0.0000000000    -0.9555689065
S       0.0000000000    0.0000000000    0.9555689065
 }

mol.update_geometry()
mol.symmetrize(0.01)

set scf_type df
set basis pcsseg-1

set DYNAMIC_LEVEL 1
#E, wfn = optimize('PBE0',return_wfn=True) # works
E, wfn = optimize('PBE',return_wfn=True) # fails
```
Any ideas to why this happens, and what I can do to help avoid this problem?

(also tested on v1.2-rc3, same issue)

**Comment by susilehtola** [comment]
I'm pretty sure S2 has a triplet ground state. Are you sure you want the singlet excited state?

**Comment by TermeHansen** [comment]
HA! I new there was an obvious answer...

**Comment by loriab** [comment]
Glad it was easy and @susilehtola recognized the trouble.
