### ISSUE TITLE
OEProp direct call printing

### ISSUE THREAD

**Issue by dgasmith** [psi4/psi4#1055]
I have seen folks try the following several times:

```
e, wfn = energy('MP2', return_wfn=True)
oeprop(wfn)
```

which will return the HF properties as MP2 densities are costly to compute, the same is true with CCSD and others. To help alleviate confusion I would add a few lines [here](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libmints/oeprop.cc#L866) in the OEProp compute call that would highlight the name of the density matrix. A line like the following could be appropriate:

```
if (title_ == ""){
    outfile->Printf("OEProp: No title given, name of density matrix used for the following properties is %s\n", Da_so_->name().c_str());
}
```

This should give folks some hint that things may not be as they appear.

**Comment by CDSherrill** [comment]
Something like this is an excellent idea.

**Comment by loriab** [comment]
(ditto from Slack) It'd be very good to get a PR for this today.
