### ISSUE TITLE
check Pople basis sets against EMSL

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#1058]
It's been noticed that a coefficient has changed in EMSL (a polarization D 6-311G(2d,p) for Fluorine from 2.396 to 3.5) since the psi basis library was formed. It would be good to know if there are others.

1) go to https://bse.pnl.gov/bse/portal and filter on "polarization"
2) for the 7 partial basis set starting "6-31" or "Pople", download them in Gaussian94 format (if their "Last Modified" date is after August 2010).
3) For files in https://github.com/psi4/psi4/tree/master/psi4/share/psi4/basis/primitives starting with "polarization-631", find the analogous polarization pattern (e.g., EMSL "6-311G* Polarization" matches https://github.com/psi4/psi4/blob/master/psi4/share/psi4/basis/primitives/polarization-6311g-_d_.gbs) and through `diff` or the script `diff_gbs.py`, check if there are any changes Psi4 needs to make.
    - Note: there's more files in basis/primitives than from EMSL. Don't worry about the cross-terms like (3df, p).
    - Note: because of how the files are structures, there may be differences of H/He present or absent. So long as exponents/coefficients aren't changing, don't worry about it.
4) Report changed coeff/exp back here.

**Comment by mdav2** [comment]
On it

**Comment by mdav2** [comment]
polarization-6-31g-_d_.gbs: Ga-Kr in Psi4 but not EMSL (new basis attributed to 6-31G* EMSL 8/22/17)
polarization-6-31g-_d_p_.gbs: Ga-Kr in Psi4 but not EMSL (new basis attributed to 6-31G* EMSL 8/22/17)
polarization-6311g-_d_p_.gbs: Iodine basis in EMSL; want to add (EMSL updated 2007?)?
polarization-6311g-_d_p_.gbs: Iodine basis in EMSL; want to add (EMSL updated 2007?)?
polarization-6311g-_2d_2p_.gbs: Fluorine D function 1 changed from 2.396 -> 3.5 (updated 2013)
polarization-6311g-_2df_2pd_.gbs: Flurine D function 1 changed from 2.396 -> 3.5 (updated 2013)
polarization-6311g-_3df_3pd_.gbs: No unaccounted difference

**Comment by loriab** [comment]
Perfect, thanks much. I’m out of town but will make the necessary adjustments in psi on Monday. Historically we stopped at Kr (except for a couple edu basis sets ), because no ECP so I’ll think about whether there’s a reason to change.

**Comment by loriab** [comment]
Ok, the 6311g_2d* fluorine was patched in psi4/psi4#1066.

The Iodine 6311g_d, I looked up the paper and confirmed it's all-electron, not ecp. However, the paper also lists a _f_ exp for 6-311G(df) for iodine that doesn't match the existing pattern (other elements are _2df_). Since I hope to abandon this for Ben's project, I'm skipping the complication. 

The Ga-Kr in Psi4 but not in EMSL a byproduct of EMSL's inconsistency is storing basis set precursors. They only define these elements in the full "6-31G*" basis.
