### ISSUE TITLE
Add SCFConvergenceError exception with wfn or geometry parameter

### ISSUE THREAD

**Issue by bgobbi** [psi4/psi4#1062]
Could you implement a specific SCFConvergenceErrors similar to OptimizationConvergenceError such that the exception provides access to the wfn or the geometry of the input?

This would allow users to catch the exception and retry the SCF with different options.
Something like this:
try:
    optE, optWfn = optimize(optMethod, return_wfn=True)
except SCFConvergenceError as e:
    optWfn = e.wfn
    # let try again:
    optE, optWfn = optimize(optMethod, return_wfn=True)
    print("SCF did not converge")

**Comment by loriab** [comment]
Yes! It’s in the plans but will only really work with py-side scf iterations. They’re waiting in the wings to be merged as soon as 1.2 is out (next week)

**Comment by dgasmith** [comment]
Should be handled with #888 as well.

**Comment by loriab** [comment]
Ticket claimed for cdsgroup programming exercise, now that scfitertopy is merged.
