### ISSUE TITLE
df-mp2 testing non-closed-shell

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#107]
for df-mp2, these are the cases:
uhf energy: good, this is is Rob's code (we're pretty sure; test)
rohf energy: we think this may be in Rob's code, but not verified vs other codes 
uhf grad: we think this may be in Rob's code, but not verified vs other codes 
rohf grad: no good. Ugur doesn't support rohf scf being fed into his omp2 w/o subsequent opt

ticket task: verify the above with the code and with the authors. if needed, re-route in driver (see mp2_type as example in ``proc.py``. If anything looks to hard or want to defer, create a new ticket for it, and do all you can to close out this one.

After discussion below, consolidated tasks:
- [x] re-route uhf grad through Ugur's code
- [x] make rohf grad fail gracefully
- [x] test all four cases
- [x] for uhf, make sure findif of Rob == Ugur
- [ ] comment ``dfmp2/corr_grad.cc`` stubs according to below

**Comment by robparrish** [comment]
No UHF-MP2 gradients in my code. Sorry.

-Rob

**Comment by psi4** [comment]
We saw some ``!restricted`` in src/bin/dfmp2/corr_grad.cc and were hopeful. Were we mistaken or was it not finished or not tested, or what’s the status.

Anyway ok, can re-route through Ugur’s code.

Lori

**Comment by robparrish** [comment]
That was just stubs in case I ever got around to it. No significant code
along those lines was completed.

-Rob

**Comment by loriab** [comment]
Ok, thanks for the clarification! I'll add to this ticket that the fixer should comment that bit of code according to Rob's pronouncements.

**Comment by loriab** [comment]
Consolidated tasks:
- [ ] re-route uhf grad through Ugur's code
- [ ] make rohf grad fail gracefully
- [ ] test all four cases
- [ ] for uhf, make sure findif of Rob == Ugur

**Comment by bwb314** [comment]
A PSIEXCEPTION is now thrown if ROHF gradients are requested.
