### ISSUE TITLE
test case coverage

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#108]
Does every major feature have a corresponding test case? For every reference on that capabilities table (http://psicode.org/psi4manual/master/introduction.html#capabilities)?

To approach this ticket, you can either:
- Go through the process above and notate here missing test case combinations.
- Or, find missing test case combinations in the course of other work
- Or, take a block of missing test case combinations, make another ticket of them, remove them from this list, and actually make the test cases and close the new ticket.

**Comment by dgasmith** [comment]
You can also use: https://codecov.io/gh/psi4/psi4 as a guide to find code that is not covered.

**Comment by dgasmith** [comment]
This seems a bit generic to have an issue on. Should be a general principle when adding new features. Closing.
