### ISSUE TITLE
Optking assign Mn to P in Writting optimization data to binary file step

### ISSUE THREAD

**Issue by pistack** [psi4/psi4#1082]
When I use ECP correction basis set like lanl2dz, Optking assign Mn to P in Writting optimization data to binary file step.

[Mn2-dzvp.txt](https://github.com/psi4/psi4/files/2177450/Mn2-dzvp.txt)
[Mn2-lanl2dz.txt](https://github.com/psi4/psi4/files/2177451/Mn2-lanl2dz.txt)

**Comment by loriab** [comment]
Thanks. Easier to track bugs here.

**Comment by loriab** [comment]
Also fixed by #1109
