### ISSUE TITLE
scratch handling documentation

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#109]
* [x] At the end of the detailed build directions in https://github.com/psi4/psi4/wiki/3_Building, add a step `7. Configure Runtime` directing user to set scratch and otherwise configure environment (e.g., add to path).

* [x] In docs/sphinxman/source/external.rst, break up "scratch files and the ~/.psi4rc file" into separate sections so that we're not suggesting psi4rc is the best way to set your scratch (pretty much, PSI_SCRATCH envvar is). Use ``make sphinxmini`` if you need to test the docs build.

* [ ] In docs, show example csh/bash in the PSI_SCRATCH envvar section. Can probably steal some text/code from conda.rst.

* [ ] In docs, show an example of a threaded pbs job file. Here's one to work from. See @loriab about any parts that are obscure.

```
#!/bin/tcsh
## this file auto-generated by submit4 ...
#PBS -j oe 
#PBS -l walltime=80:00:00:00
#PBS -l pmem=2120mb
#PBS -N SSI-084TYR-095LEU-1-dimer
#PBS -V


setenv OMP_NUM_THREADS 4
setenv MKL_NUM_THREADS 4
cd $PBS_O_WORKDIR
setenv myscratch /scratch/loriab/psi4.$PBS_JOBID

cat $PBS_NODEFILE
foreach i (`sort $PBS_NODEFILE | uniq`)
    echo "Creating scratch directory " $myscratch " on " $i
    ssh $i rm -rf $myscratch
    ssh $i mkdir -p $myscratch
end
unsetenv PSI4DATADIR
unsetenv PSIDATADIR
if ! ( $?PYTHONPATH ) setenv PYTHONPATH ""
setenv PYTHONPATH /theoryfs2/ds/cdsgroup/psi4aux:$PYTHONPATH
setenv PSI_SCRATCH $myscratch
setenv PATH /theoryfs2/ds/cdsgroup/miniconda/bin:${PATH}
setenv PATH /theoryfs2/ds/cdsgroup/scripts/bin:${PATH}
setenv PATH /theoryfs2/ds/loriab/chem/psi4_trials/c4/c4v2/cfour_v2.00beta/bin:${PATH}
setenv PATH /theoryfs2/ds/cdsgroup/psi4-compile/mrcc:${PATH}
setenv PSIDATADIR /theoryfs2/ds/cdsgroup/psi4-install/psi3930/share/psi4
source /theoryfs2/common/software/intel2016/bin/compilervars.csh intel64
/theoryfs2/ds/cdsgroup/scripts/bin/runpsi.py -i SSI-084TYR-095LEU-1-dimer.in -o SSI-084TYR-095LEU-1-dimer.out

foreach i (`sort $PBS_NODEFILE | uniq`)
    echo "Removing scratch directory " $myscratch " on " $i
    ssh $i rm -rf $myscratch
end
```

* [ ] On wiki, create FAQ on https://github.com/psi4/psi4/wiki/8_FAQ_Contents about how do i set scratch, how do i use psi4 in a pbs queue, etc. Questions go in the 8_FAQ_Contents page, answers can link back to the sphinx docs themselves, then index the questions in the https://github.com/psi4/psi4/wiki/0_FAQ.

* [ ] Edit the link on page https://github.com/psi4/psi4/blob/master/doc/sphinxman/source/tutorial.rst in sentence "For your convenience" to point to something you created.

**Comment by loriab** [comment]
I think you meant to close psi4/issues/109 but ended up closing psi4public/issues/109. Perhaps just switch things around via GitHub.

**Comment by jgonthier** [comment]
Two first checkboxes done. Is there any way I can check them myself ?

**Comment by jgonthier** [comment]
The last wiki point (FAQ) is done.

**Comment by loriab** [comment]
Thanks for the FYI. I was just reading your PBS section, so I'll read the wiki next.
