### ISSUE TITLE
psi4 1.1 and Psi4 1.2 give very different results with [18]Annulene

### ISSUE THREAD

**Issue by pistack** [psi4/psi4#1094]
This is my input file.

memory 2000 mb

set {
basis  6-31+G**
reference uks
print_trajectory_xyz_file True
dynamic_level 3
geom_maxiter 2 # for banch mark
}
molecule {
0 1
            C    -0.9912206086   2.8131856160  -0.0573611577
            C    -0.0065361040   3.8004573879  -0.0899945316
            C     1.3798808082   3.5407045556  -0.1041053058
            C     1.9410978806   2.2641950692  -0.0799579740
            C     3.2886025195   1.9047050299  -0.0932225800
            C     3.7573004262   0.5746382727  -0.0668232062
            C     2.9322291027  -0.5491503715  -0.0253808964
            C     3.2949719214  -1.8954547342   0.0021456089
            C     2.3774158668  -2.9661063312   0.0421948956
            C     0.9910962887  -2.8134295526   0.0516412719
            C     0.0065004625  -3.8005717170   0.0933574064
            C    -1.3797668642  -3.5408136100   0.1034400320
            C    -1.9409778357  -2.2639998084   0.0835635290
            C    -3.2884679268  -1.9048573146   0.0867443596
            C    -3.7572441300  -0.5746153801   0.0624966242
            C    -2.9322699356   0.5491764124   0.0248765082
            C    -3.2951262899   1.8957129852   0.0016465100
            C    -2.3775183237   2.9662393715  -0.0357709805
            H     0.6306894251  -1.7913750813   0.0208596131
            H     2.7841508221  -3.9758109969   0.0667744946
            H     4.3553844319  -2.1428427854  -0.0063594220
            H     1.8668978587  -0.3494271067  -0.0121498700
            H     0.3228373264  -4.8420256607   0.1188602273
            H    -2.0511468159  -4.3975325285   0.1300589689
            H    -1.2357730759  -1.4410348629   0.0655215046
            H     4.8351452690   0.4211590359  -0.0805349766
            H     4.0326489552   2.6988346470  -0.1263761210
            H     1.2360000160   1.4415822577  -0.0454433027
            H     2.0511633898   4.3973662877  -0.1345195235
            H    -0.3226761608   4.8421262640  -0.1059899081
            H    -0.6312244278   1.7907842456  -0.0464818848
            H    -2.7838455263   3.9761404520  -0.0477059840
            H    -4.3553303919   2.1429676321   0.0149903516
            H    -1.8669715938   0.3495233958   0.0124287296
            H    -4.8350335200  -0.4213578612   0.0728297413
            H    -4.0325261304  -2.6992664259   0.1093084921
}
E,wfn = optimize('b3lyp5',return_wfn=True)

When I run this file with psi4 1.1 the results of first geometry is

   Step     Total Energy     Delta E     MAX Force     RMS Force      MAX Disp      RMS Disp   

    Convergence Criteria    1.00e-06 *    3.00e-04 *             o    1.20e-03 *             o  

      1    -696.23196743   -6.96e+02      6.60e-04      2.45e-04 o    3.67e-03      1.31e-03 o  ~

But I run this file with psi4 1.2 the results of first geometry is

   Step     Total Energy     Delta E     MAX Force     RMS Force      MAX Disp      RMS Disp    ~

    Convergence Criteria    1.00e-06 *    3.00e-04 *             o    1.20e-03 *             o  ~

      1    -696.23196742   -6.96e+02      6.43e-02      1.88e-02 o    2.04e-02      6.09e-03 o  ~

And psi4 1.2 failed to optimize geometry but psi4 1.1 successfully optimize geometry.

**Comment by pistack** [comment]
results of psi4 1.1 is this
  --------------------------------------------------------------------------------------------- ~
   Step     Total Energy     Delta E     MAX Force     RMS Force      MAX Disp      RMS Disp    ~
  --------------------------------------------------------------------------------------------- ~
    Convergence Criteria    1.00e-06 *    3.00e-04 *             o    1.20e-03 *             o  ~
  --------------------------------------------------------------------------------------------- ~
      1    -696.23196743   -6.96e+02      6.60e-04      2.45e-04 o    3.67e-03      1.31e-03 o  ~
      2    -696.23202825   -6.08e-05      2.89e-04 *    9.64e-05 o    3.98e-03      1.27e-03 o  ~
      3    -696.23204984   -2.16e-05      1.78e-04 *    5.02e-05 o    2.05e-03      7.01e-04 o  ~
      4    -696.23205372   -3.88e-06      1.35e-04 *    3.92e-05 o    4.27e-03      1.33e-03 o  ~
      5    -696.23205950   -5.79e-06      6.65e-05 *    1.71e-05 o    9.47e-04 *    2.94e-04 o  ~
And
results of psi4 1.2 is this
 --------------------------------------------------------------------------------------------- ~
   Step     Total Energy     Delta E     MAX Force     RMS Force      MAX Disp      RMS Disp    ~
  --------------------------------------------------------------------------------------------- ~
    Convergence Criteria    1.00e-06 *    3.00e-04 *             o    1.20e-03 *             o  ~
  --------------------------------------------------------------------------------------------- ~
      1    -696.23196742   -6.96e+02      6.43e-02      1.88e-02 o    2.04e-02      6.09e-03 o  ~
      2    -696.23181077    1.57e-04      6.10e-02      1.83e-02 o    1.93e-02      6.09e-03 o  ~
      3    -696.23126151    5.49e-04      5.77e-02      1.78e-02 o    1.93e-02      6.09e-03 o  ~
      4    -696.23034152    9.20e-04      5.45e-02      1.73e-02 o    1.93e-02      6.09e-03 o  ~
	Raising dynamic level to 4. ~
  --------------------------------------------------------------------------------------------- ~
   Step     Total Energy     Delta E     MAX Force     RMS Force      MAX Disp      RMS Disp    ~
  --------------------------------------------------------------------------------------------- ~
    Convergence Criteria    1.00e-06 *    3.00e-04 *             o    1.20e-03 *             o  ~
  --------------------------------------------------------------------------------------------- ~
      1    -696.23034152   -6.96e+02      1.45e-01      4.37e-02 o    5.20e-02      1.59e-02 o  ~

Thank you.

**Comment by dgasmith** [comment]
Thanks for the report. This one is on me, we should have a fix in and will back port to the conda version soon.

**Comment by loriab** [comment]
#1096 fixes the gradients. optimization should follow.

**Comment by pistack** [comment]
Thank you very much!
