### ISSUE TITLE
problematic geometry optimization with DF-SCF

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#1095]
I want to optimize base-pairs in Cs symmetry and DFT, but the optimization fails/produces a wrong minimum. Moreoever, the optimization goes a bit crazy.

DF-B3LYP-D3/def2-QZVP gives some form of this with most options (including cart.) for the optimizer:
```
    Convergence Criteria    1.00e-06 *    3.00e-04 *             o    1.20e-03 *             o  ~
  --------------------------------------------------------------------------------------------- ~
      1   -1089.49118380   -1.09e+03      9.40e-02      1.22e-02 o    1.04e-01      1.41e-02 o  ~
      2   -1089.49529350   -4.11e-03      5.45e-02      7.48e-03 o    9.20e-02      1.41e-02 o  ~
      3   -1089.49300118    2.29e-03      4.10e-02      5.60e-03 o    8.58e-02      1.41e-02 o  ~
      4   -1089.48886131    4.14e-03      3.02e-02      4.05e-03 o    8.07e-02      1.41e-02 o  ~

```

The default optimizer keeps increasing the energy and ends up in a wrong minimum. The option `DYNAMIC_LEVEL 2` tries to fix things, but it goes nowhere in the end. See output for further details:  [dynamic.txt](https://github.com/psi4/psi4/files/2196749/dynamic.txt) 

While at first I thought the optimizer just has weird troubles, from the below notes it seems the gradient might be faulty. And computing the numerical gradient shows some values a bit too far off. 
[grad.txt](https://github.com/psi4/psi4/files/2197616/grad.txt) (both next to each other at the bottom)
E.g. compare the row for Atom 38.

Additional notes/remarks
* Turbomole (RI-JK) and Gaussian converge smoothly. No increase in energy.
* smaller basis sets (def2-TZVP) converge as they should
* DFT grid increase does not change anything to the better
* same convergence issue with other (similar) structures
* revPBE0/def2-QZVP shows the same incorrect behavior
* `scf_type direct` seems to converge as it should (slow, still running)
* DF-B3LYP gradient vs. FD gradients for water seems okay
* Not a symmetry problem
* Same with DF-HF
* Psi4 1.2 release; Git: Rev {HEAD} 9d4a61c (conda install)

**Comment by dgasmith** [comment]
What happens if you use `scf_type disk_df`? It might be an issues that the normal stationary points that SCF is assumed under fail when two different types of screening are used.

**Comment by hokru** [comment]
* reducing memory in input to  8Gb to have true disk-based DF does not help
* GGA (BLYP) calculations seems to converge normally.

**Comment by hokru** [comment]
I finally managed to get a small test case: 
[small2_in.txt](https://github.com/psi4/psi4/files/2199056/small2_in.txt)
[small2_out.txt](https://github.com/psi4/psi4/files/2199057/small2_out.txt)

```
        DF-SCF gradient test: computed value (-0.25836946643405045) does not match (-0.11351758729533379).
        DF-SCF gradient test: computed value (0.020545640137366858) does not match (0.012569715618282922).
        DF-SCF gradient test: computed value (-0.020205828245199342) does not match (-0.014701497891262322).
     etc.
```

* Increasing memory to 2.5 Gb passes the test (MEM_DF and DISK_DF)


Oddly, perhaps, using 0.5 Gb memory I get (both DISK_DF):
```
    Memory (MB):               357
    Algorithm:                Core
```
and with 2.5 Gb:
```
    Memory (MB):              1788
    Algorithm:                Core

```
