### ISSUE TITLE
refresh Python 3 compatibility

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#110]
Once upon a time, Psi4 was made python3 compatible. I haven't heard of it being tested since. Make it so once more.

potentially helpful tools:
- `conda create -n pyconv python=3.4` if you need a python3 environment
- http://python-modernize.readthedocs.org/en/latest/ looks like a helpful project. `pip install modernize` then run on each file.

Driver is a sad mix of `print vari` and `print(vari)`. Feel free to import latter from future and standardize. But leave qcdb alone. It has its own ticket and repository.

**Comment by dgasmith** [comment]
This has been completed through several PR. Conda package coming shortly.
