### ISSUE TITLE
ECPs, freeze_core and ghosted atoms do not get along

### ISSUE THREAD

**Issue by PeterKraus** [psi4/psi4#1102]
When trying to compute counterpoise-corrected energies of complexes with atoms including ECPs, and frozen core applied, the results are incorrect. I believe it is due to incorrect assignment of frozen core orbitals (yet again). See attached input and output files. The relevant part is quoted below

```
$: grep frozen bug.out 
        Use frozen natural orbitals?           no
        Number of frozen core orbitals:         4 (Kr + OCS ghost)
        Number of frozen virtual orbitals:      0
        Use frozen natural orbitals?           no
        Number of frozen core orbitals:         4
        Number of frozen virtual orbitals:      0
        Use frozen natural orbitals?           no
        Number of frozen core orbitals:         3 (Kr ghost + OCS)
        Number of frozen virtual orbitals:      0
        Use frozen natural orbitals?           no
        Number of frozen core orbitals:         3
        Number of frozen virtual orbitals:      0
        Use frozen natural orbitals?           no
        Number of frozen core orbitals:        11 (Kr + OCS)
        Number of frozen virtual orbitals:      0
        Use frozen natural orbitals?           no
        Number of frozen core orbitals:        11
        Number of frozen virtual orbitals:      0
```

For the Kr + OCS(Gh) combination, we want to freeze the [Ar] shell, ie 18 electrons. Part of them is frozen using the ECP (10e-), and the remaining 4 pairs are frozen correctly.

For the Kr(Gh) + OCS combination, we want to freeze the [He] electrons on O and C, and the [Ne] electrons on S, ie. 14 electrons. But we freeze only 3 orbitals, we are 8 electrons short.

For Kr + OCS, we want to freeze 2x[He], 1x[Ne] and 1x[Ar] shells, ie. 32 electrons. As above, 10 are in Kr's ECP, and the additional 22 are correctly ghosted by the 11 frozen orbitals.

The problem seems to be happening when an ECP-containing atom is ghosted. I think it happened both with explicit ghosting using `(Gh)` and with `extract_subsets`; I didn't keep the other logfile.

[bug_inp.txt](https://github.com/psi4/psi4/files/2219016/bug_inp.txt)
[bug_out.txt](https://github.com/psi4/psi4/files/2219017/bug_out.txt)

**Comment by loriab** [comment]
fixed by #1109
