### ISSUE TITLE
Fragment Multiplicities Don't Add

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#1106]
If you supply two fragments to Psi4, it will assume the multiplicity of the combined system is the multiplicity of the first fragment, not the multiplicity of the high spin combination. For instance, Psi will attempt to treat the following molecule as a singlet rather than a triplet. Switching the order of the fragments will make Psi look for the triplet. Switching both to be triplets, where the high spin combination is a quintet, will have Psi look for triplets. I haven't tested how it handles more than two fragments.

```
molecule {
   0 1 
   H         -0.7589216703        0.0000000000        3.1082565820
   H          0.7589216703        0.0000000000        3.1082565820
   O          0.0000000000        0.0000000000        2.5216012101
   --  
   0 3 
   S          0.0000000000        0.0000000000       -0.4748174225
   O          0.0000000000        0.0000000000       -1.9641940526
     symmetry c1
     no_reorient
     no_com
}

set {
reference   uhf 
scf_type    direct
basis       cc-pVDZ
}

energy('scf')
```
Attempted on `Git: Rev {master} 9994682`.

**Comment by loriab** [comment]
This has bitten a lot of people (including the devs who programmed it), esp. when you start ghosting fragments. I'm pleased to say that the new mol parsing in #953 should fix this. In particular, you can add an extra `0 3\n--` at the top to specify overall chgmult.

**Comment by JonathonMisiewicz** [comment]
Tests confirm that #953 fixes the issue. Many thanks to @loriab.
