### ISSUE TITLE
python3 conda package

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#111]
After https://github.com/psi4/psi4/issues/86 and https://github.com/psi4/psi4public/issues/110 settled, 
- [ ] create conda package with python 3.4. Should be as simple as changing the `conda-recipe/psi4/meta.yaml` dependencies.
- [ ] add to Psinet's duties by modifying/copying stuff in nightly folder so package built nightly and results sent to testboard

**Comment by dgasmith** [comment]
Apparently conda only compiles boost against python2.
https://github.com/ContinuumIO/anaconda-issues/issues/316


Compiling boost against conda's python3 may be a challenge due to the header changes.

**Comment by loriab** [comment]
I've got it partially compiled against 3. We'll have to compare notes.

**Comment by rmcgibbo** [comment]
If you like, we have conda boost packages for py3 in the omnia suite https://github.com/omnia-md/conda-recipes, https://anaconda.org/omnia/boost/files. Feel free to copy / take. Note that if yoy use boost 1.58.0, there is a bug in the py3 support that you need to patch.

**Comment by dgasmith** [comment]
Collapsing to just issue #466, Python 3 package coming soon!
