### ISSUE TITLE
BVWN5 Functional

### ISSUE THREAD

**Issue by dgasmith** [psi4/psi4#1111]
As noted [here](http://forum.psicode.org/t/looking-for-basis-set-bvwn5/1012/5), we seem to be missing a functional that GAMMES has. It would be great to add to our functional library. The functional is below, all that is need is to find the original paper that this came from.

```python
bvwn5_func = {
    "name": "BVWN5",
    "x_functionals": {
        "GGA_X_B88": {}
    },
    "c_functionals": {
        "LDA_C_VWN": {}
    }
}
```

**Comment by PeterKraus** [comment]
Could I have a "reference" value for BVWN5 and ideally also for BVWN3 (ideally for the `dft-bench-ionization` and `dft-bench-interaction`) from GAMESS?

**Comment by susilehtola** [comment]
This doesn't really even seem to be a functional...

**Comment by dgasmith** [comment]
Found in the docs here: http://classic.chem.msu.su/gran/gamess/dft.html

**Comment by JonathonMisiewicz** [comment]
The reference you're looking for is: S. H. Vosko, L. Wilk, and M. Nusair, “Accurate spin-dependent electron liquid correlation energies for local spin density calculations: A critical analysis,” Can. J. Phys., 58 (1980) 1200-11.

I just wasn't sure if there needed to be a reference for the specific x/c combination.

**Comment by susilehtola** [comment]
That's for the correlation, not the xc combination.

It seems stupid to have this in, since this is really nothing but a combination of two published exchange and correlation functionals.

Instead, the parser should be developed to have a shorthand for exchange and correlation functionals. Like "S" for LDA exchange, "B" for Becke88 and so on. And then go through all the possible combinations to figure out what was specified.

**Comment by PeterKraus** [comment]
> Instead, the parser should be developed to have a shorthand for exchange and correlation functionals. 

Not sure I agree on this one. While such parsers are common in other codes, personally I think it's a wasted effort when one uses libxc - most folks who want "non-standard" combinations of exchanges and correlations know what they're doing, and they will be comfortable with the `dict`-based interface (if they aren't, it's a failure of the docs more than anything). Obviously, it doesn't hurt to have the common options (such as BLYP, SVWN, PW91, PBE...) pre-defined and checked for regressions.

**Comment by dgasmith** [comment]
Took a vote, BVWN5 declared not a real functional until documentation can be provided. Happy to reopen if we can find more literature on the subject.
