### ISSUE TITLE
wrong atom in cube file

### ISSUE THREAD

**Issue by TermeHansen** [psi4/psi4#1113]
If I have Iodine in a molecule I get wrong atom (from I[53] to Mn[25]) in header in cube file:

example:
```
molecule mol {
 0 1
I          1.05590        0.00000        0.00000
C         -1.05590        0.00000        0.00000
H         -1.44970       -1.02090        0.00000
H         -1.44980        0.51040        0.88420
H         -1.44970        0.51050       -0.88410
 }

set scf_type df
set basis def2-SVP

E, wfn = energy('pbe',return_wfn=True)
set cubeprop_tasks ['density']
set CUBIC_GRID_OVERAGE [8.0, 8.0, 8.0]
set CUBIC_GRID_SPACING [0.17, 0.17, 0.17]
cubeprop(wfn)

```

cube header:
```

Psi4 Gaussian Cube File.
Property: Dt [e/a0^3]. Isocontour range for 85% of the density: (0.0575417,0)
     5 -12.299260 -10.002258  -9.689907
   123   0.170000   0.000000   0.000000
   113   0.000000   0.170000   0.000000
   115   0.000000   0.000000   0.170000
 25   0.000000   0.438284  -0.000000  -0.000001
  6   0.000000  -3.552440  -0.000000  -0.000001
  1   0.000000  -4.296614  -1.929221  -0.000001
  1   0.000000  -4.296803   0.964516   1.670895
  1   0.000000  -4.296614   0.964705  -1.670708
```
[CH3I.log](https://github.com/psi4/psi4/files/2245612/CH3I.log)

**Comment by loriab** [comment]
fixed by #1109

**Comment by TermeHansen** [comment]
will this fix be merged into v1.2 and v1.2.1 ?

**Comment by loriab** [comment]
Hadn't planned to, but it wouldn't be a problem. I suppose that's a request for v1.2.2?

**Comment by TermeHansen** [comment]
Yes, that would be nice. I try to use psi4 for sort of production use, so stay on these tag-releases in a hope that they have less of these kind of development bugs :)

**Comment by TermeHansen** [comment]
I'm sorry, but the issue does not seem to be fully solved... Yes not the atom nr in the header of the cube file is correct:
```
Psi4 Gaussian Cube File.
Property: Dt [e/a0^3]. Isocontour range for 85% of the density: (0.0571983,0)
     5 -12.329260 -10.002258  -9.679907
   131   0.160000   0.000000   0.000000
   120   0.000000   0.160000   0.000000
   122   0.000000   0.000000   0.160000
 53   0.000000   0.438284  -0.000000  -0.000001
  6   0.000000  -3.552440  -0.000000  -0.000001
  1   0.000000  -4.296614  -1.929221  -0.000001
  1   0.000000  -4.296803   0.964516   1.670895
  1   0.000000  -4.296614   0.964705  -1.670708

```
But the integrated electrons in the cube file still misses alot of electrons. I use the cube file as input for the Chargemol code, and it works perfect for all other than molecules with Iodine as in this example.

```
 Starting DDEC program
 2018/08/14  12:53:41
 Copyright (c) 2014, 2015, 2016 by Thomas A. Manz and Nidia Gabaldon Limas. Rights reserved.
  
 **************** THREAD INFORMATION ******************
 Job running using OpenMP.
 The number of parallel threads is:            4
  
 ******************************************************
  
 /home/termo/chargemol_09_26_2017/atomic_densities/                                                                                                                                                    
  
 ******************** TIME CONTROL ********************
 Starting format_total_cube_density
 ******************************************************
  
 inputfile = "total_density.cube"
 parameters
   5.0000000000000000       -12.329260000000000       -10.002257999999999       -9.6799070000000000     
   131.00000000000000       0.16000000000000000        0.0000000000000000        0.0000000000000000     
   120.00000000000000        0.0000000000000000       0.16000000000000000        0.0000000000000000     
   122.00000000000000        0.0000000000000000        0.0000000000000000       0.16000000000000000     
 sum_negative_density=    0.0000000000000000     
 center_nabc =
          80          63          60
          55          63          60
          50          50          60
          50          69          71
          50          69          50
 delta_na=     61
 delta_nb=     61
 delta_nc=     61
  
 ******************** TIME CONTROL ********************
 Starting check_grid_spacing
 ******************************************************
  
 The grid spacing in your electron density input file is adequate.
  
 ******************** TIME CONTROL ********************
 Finished check_grid_spacing in   0.11500000208616257      seconds
 ******************************************************
  
  
 ******************** TIME CONTROL ********************
 Finished format_total_cube_density in    1.1610000133514404      seconds
 ******************************************************
  
 ncore =        0.0000
 nvalence =       62.0000
 pixelvolume =    4.0960E-03
 numerically integrated valence density =    3.3967E+01
 sum_valence_occupancy_correction =    0.0000E+00
 checkme =    2.8033E+01
 The electrons are not properly accounted for.

```

So here 28 electrons short in the cube of the 62 expected....

**Comment by andysim** [comment]
I'm not familiar with Chargemol, but it must have some mechanism for providing information about core electrons (the `ncore` that is listed as zero in your provided output); to my knowledge there is no place in the cube file format for this information.  The problem you are experiencing is almost certainly because the 28 'missing' electrons are accounted for by an ECP for the iodine atom, so we need some way to tell Chargemol about those.

**Comment by TermeHansen** [comment]
I am on the other up until this bug, unfamiliar wuth ECP. So if som electrons are accounted for by ECP, they will and should not be part of the total density cube file? For aroms without ECP they are all part of the total density cube file...

**Comment by andysim** [comment]
For very heavy atoms, the innermost electrons experience a very high charge from the nucleus and have enough kinetic energy that relativistic effects are significant.  They're also so tightly bound that they don't matter in most chemical applications, so it's better to treat them using a term that can properly handle these 'core' electrons, and remove them from the calculation.   Therefore, only the valence electrons contribute to the density when ECPs are present so there must be some way to tell Chargemol that this is the case.

**Comment by PeterKraus** [comment]
From the manual for Chargemol, eg on page 12 for CP2K input:
```
<number of core electrons>
36 28 <-- First number is the element number and second number is num_core
47 30 <-- First number is the element number and second number is num_core
</number of core electrons>
```

**Comment by TermeHansen** [comment]
Yes there is. Can you help in where in the code the number of ECP core electrons for the different atoms are found? Next question out of interest is why 28 core and not 36 for atom nr 53?

**Comment by TermeHansen** [comment]
Yes there is. Can you help in where in the code the number of ECP core electrons for the different atoms are found? Next question out of interest is why 28 core and not 36 for atom nr 53?

**Comment by TermeHansen** [comment]
Yes Peter, and then use density cube as valence_density.cube input - AND set non ECP using atoms to 0

**Comment by andysim** [comment]
The number of core electrons is determined [by the basis set](https://github.com/psi4/psi4/blob/master/psi4/share/psi4/basis/def2-sv_p_.gbs#L2729), as the core is designed to model a specific number of electrons.

**Comment by PeterKraus** [comment]
Ideally, you should know what kind of basis set you're using, as you're presumably going to cite it in your work; the details about the number of core `e-`'s treated as effective potentials will be included there. There are also all-electron basis sets available for almost any element; some of them are shipped with Psi4 (eg. 3-21g). Psi4 tells you the basis has an ECP in the `=> Loading Basis Set <=` section, and the details are printed later on under `==> Primary Basis <==`.

As for the question of 28 vs 36 electrons: the first 28 electrons are the 1s2 + 2s2, 2p6 + 3s2, 3p6, 3d10 shells - ie. full 1st, 2nd and 3rd shell. The additional 8 electrons you're thinking about are from the 4th period shells, where the 4d10 part is in your 5th valence shell - so you don't really want to replace any of those with a potential. (At least that's my rather limited understanding.)

**Comment by CDSherrill** [comment]
If we don't print the number of implied core electrons in the output
somewhere when using an ECP basis, it wouldn't be a bad idea to do so.

**Comment by TermeHansen** [comment]
It is printed... I know which basis set I use, but would just like upfront
to make my chargemol job-control file ready for my basis set choise. Thank
you all!

**Comment by andysim** [comment]
Peter's right - the info can be found [in the output](https://github.com/psi4/psi4/blob/master/tests/scf-ecp/output.ref#L133) already.   Different basis sets have different numbers of explicit/implicit electrons for a given atom, so this will have to be evaluated for each basis set / molecule combination you're interested in.

**Comment by loriab** [comment]
There's a comment line in the cube file that we use for units and property. It wouldn't be standard among all cube-reading software, but we can put the No. core electrons there, so downstream has a chance.

**Comment by andysim** [comment]
That's a great idea
