### ISSUE TITLE
Implementation of I/O less OEProps in-memory

### ISSUE THREAD

**Issue by timostrunk** [psi4/psi4#1116]
I would like to implement a faster way to do ESP fits than what is found here:
https://github.com/psi4/psi4numpy/tree/master/One-Electron-Property/Restrained-Electrostatic-Potential

The solution above is writing multiple grids on disk, yet the strength of the python and C++ APIs of Psi4 should be to have these in memory and allow for fast multithreaded evaluations.

My development proposal would be a little more involved, but also give the Psi4 API a lot more power. I would split the whole OEProp class into:

OEPropCalc
This class will get all currently existing logic to calculate the requested properties. Most properties are already calculated as SharedMatrix. This class will not be allowed to have any kind of output, unless a bulk property is requested (such as a grid).
OEProp
This class gets all output handling, it will only call the respective OEPropCalc functions and then use the existing code for output. Data will be passed between OEPropCalc and OEProp as SharedPointer and therefore not cost overhead. Exception to this rule would be the functions writing grids, which will get an in-memory and a direct write solution.
Reason:
Currently OEProp sometimes exposes data in memory (such as Mulliken charges using wfn.set_array) and sometimes not (such as Multipoles only via stdout or outfile). The approach above would allow internal code use of SharedMatrices directly (OEPropCalc would get a public python API) and keep existing functionality untouched.

Once the split is done, I would also split the GridEvaluation routines to either write a grid-XXX.dat (the existing functionality) or to keep the grids in memory (new functionality) and generate them with a grid taken from memory using the existing GridIterator interface.

Are there any objections or is somebody else currently working on this?

**Comment by dgasmith** [comment]
Thanks for the suggestion. As a first pass this sounds great and I don’t think anyone else is working on it currently. I agree that OEProp should be a bit more straightforward about the output. Let me think on this a bit and perhaps source some other feedback. 

Thanks for delving into this!

**Comment by loriab** [comment]
libcubeprop will also be getting some I/O refactoring soon, so feel free to chime in if there's anything relevant you see going wrong or right with your planned uses.

**Comment by timostrunk** [comment]
This issue is adressed in https://github.com/psi4/psi4/pull/1133
I did not use the GridIterator interface as the memory overhead of passing the complete grid from python is currently neglibible. 
Also only one of the Grid functions is converted. Converting the others after the split will be trivial.
Therefore closing the issue.
