### ISSUE TITLE
MathOpenMP detection

### ISSUE THREAD

**Issue by jgonthier** [psi4/psi4#1118]
I'm building Psi4 updated with the most recent trunk from Github on a cluster with the following:
 vim/7.4        ;      python/2.7   ;        mkl/2016.4.072  ;     hdf5/1.8.20-gcc-s
  emacs/25.1       ;    gcc/6.3.0        ;    cmake/3.7.2      ;    perl/5.20.0

During the configure step, MathOpenMP is not found with the following message:
```
-- Math lib search order is MKL;OPENBLAS;ESSL;ATLAS;ACML;SYSTEM_NATIVE
-- You can select a specific type by defining for instance -D BLAS_TYPE=ATLAS or -D LAPACK_TYPE=ACML
-- or by redefining MATH_LIB_SEARCH_ORDER
-- BLAS will be searched for based on MKLROOT=/global/software/sl-7.x86_64/modules/langs/intel/2016.4.072/mkl
-- Found BLAS: MKL (/global/software/sl-7.x86_64/modules/langs/intel/2016.4.072/mkl/lib/intel64/libmkl_rt.so)
-- LAPACK will be searched for based on MKLROOT=/global/software/sl-7.x86_64/modules/langs/intel/2016.4.072/mkl
-- Found LAPACK: MKL (/global/software/sl-7.x86_64/modules/langs/intel/2016.4.072/mkl/lib/intel64/libmkl_rt.so)
-- Could NOT find MathOpenMP (missing:  MathOpenMP_MESSAGE) 
-- Found LAPACK MKL: /global/software/sl-7.x86_64/modules/langs/intel/2016.4.072/mkl/lib/intel64/libmkl_rt.so;...
```

and then cmake ends without errors. Proceeding with building, it of course fails since it can't find MathOpenMP. I found the solution in issue #1041 : hint at the location of libiomp5 using `-DOpenMP_LIBRARY_DIRS`

However, the fact that cmake terminates without any error message seems suboptimal, since less experienced users might spend a long time recompiling to track down an error that could actually be diagnosed at configure time.
Also, I did not look into extreme detail but I could not find this CMake hint in the `installation from source` part of the manual.

**Comment by edeustua** [comment]
I'm having the same problem. I've tracked the problem down to the path of the library not being passed to

`external/common/lapack/FindMathOpenMP.cmake`

Setting `-DOpenMP_LIBRARY_DIRS` solves the issue, but I believe this is not the intended behavior.

**Comment by loriab** [comment]
Reproach well deserved, @jgonthier. Info has been in [CMakeLists.txt](https://github.com/psi4/psi4/blob/master/CMakeLists.txt#L71), but that admittedly is an awful error message. I've figured out how to hit it locally (conda directory structure bypasses it all), and a fix will appear soon to a PR near you. Thanks for the report.

@edeustua, `-DOpenMP_LIBRARY-DIRS` probably _is_ the intended solution. The usual case where this issue appears is you're building Psi with GCC compilers and MKL LAPACK. For a usual from-intel (as opposed to from-conda) MKL installation, libraries mkl_rt and iomp5 are in different locations. With GCC+MKL, Psi needs to explicitly use iomp5 to suppress the tenacious gomp. But unless the location of iomp5 is already known to CMake through another detection sequence, it can't find the library, hence the (poor) error message you got. `OpenMP_LIBRARY_DIRS` is the intended solution. If I'm misunderstanding your circumstance, please let me know.

**Comment by edeustua** [comment]
@loriab. I think `-DOpenMP_LIBRARY_DIRS` is a good solution. I just think that if the detection is not going to be truly automatic (i.e. combinations such as gcc + MKL, which is a very common free combination of software,  is not properly detected) it probably should be more obvious to the user that such options _have_ to be passed to CMake.

With that in mind, improving the error message suggesting to use `-DOpenMP_LIBRARY_DIRS` would be awesome.

And thank you for your time by the way.

**Comment by BJWiley233** [comment]
on MacOS I am using `-DOpenMP_LIBRARY_DIRS=/usr/local/Cellar/libomp/12.0.1/lib` where I have brew installation `libomp.a` and `libomp.dylib1 but still getting:

```
ld: library not found for -lMathOpenMP_LIBRARIES-NOTFOUND
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
