### ISSUE TITLE
Add ECP info to cube files

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#1136]
Following the discussion https://github.com/psi4/psi4/issues/1113, it'd be useful to add to the comment line of cube files (found in [libcubeprop](https://github.com/psi4/psi4/tree/master/psi4/src/psi4/libcubeprop)) info about the number of core electrons treated by ECP and _not_ to be found in the electron density of the cube file.

* Note that not all types of cubes will need this (e.g., not HOMO/LUMO cubes)
* Since the Chargemol input needs number of electrons and number of core electrons _per atom_, should identify which atom(s) cores belong to. (e.g., `Total core: 10 [e] from atom 4 (6) and 8 (4)`. I'm not sure where the 0-/1-indexing notice should go.)

**Comment by andysim** [comment]
[This](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libmints/basisset.cc#L228) is where the information is printed to the regular output file.

**Comment by PeterKraus** [comment]
I've got a working prototype. There were another few things I wanted to add to cubeprop, so expect the review-ready PR around the end of the week.
