### ISSUE TITLE
stuck in analytic frequency computation with HF (tags/v1.2.1)

### ISSUE THREAD

**Issue by TermeHansen** [psi4/psi4#1145]
If I do analytic frequency calculation with HF it seems eternally stuck (with full cpu load) - for this particular molecule at least.

attached log with optimization and frequency calculation that is stuck when using analytical and full successful log with dertype="gradient"

```
E, wfn = optimize('HF',return_wfn=True)
#E, wfn = frequencies('HF',return_wfn=True, dertype='gradient')
E, wfn = frequencies('HF',return_wfn=True)

```
[2202-HF-analytic.log](https://github.com/psi4/psi4/files/2307871/2202-HF-low-analytic.log)
[2202-HF-gradient.log](https://github.com/psi4/psi4/files/2307873/2202-HF-low.log)

**Comment by loriab** [comment]
Is "eternally stuck" about 3 hrs or 3 days?

I was going to say that's a large-ish molecule (the dev groups don't run many SCF freq). But if findif H by G only took half an hour, surely analytic should be manageable. Sound suspect, @andysim?

**Comment by TermeHansen** [comment]
Left it overnight and still same place with full cpu load. Started H by G and yes finished soon after...

**Comment by JonathonMisiewicz** [comment]
I think I've stumbled across this problem when trying to get hessians for comparison with finite difference code. The below input completes on our cluster in under a minute, operating on dev199. It took about 1.8 hours for jobs to finish when I didn't change the scf_type. Curiously, this is the same amount of time it took when I forgot to include the memory line. Could the bug be the DF code not using all the memory it has available? If so, then the bug OP saw wasn't the computation getting eternally stuck, but that trying to get an analytic hessian with around 1500 basis functions and only 500 MiB feels like an eternity.

```
#! SCF DZ finite difference frequencies by energies for C4NH4
memory 30gb

molecule c4nh4 {
  units angstrom
  -1 1
    C         0.000000000000     0.000000000000     1.119905811674
    N         0.000000000000     0.000000000000     2.310087277449
    C         0.000000000000     0.000000000000    -0.231085072523
    C        -0.781617287494     0.000000000000    -1.483869398827
    C         0.781617287494     0.000000000000    -1.483869398827
    H        -1.274488047821    -0.899961499592    -1.835960153318
    H        -1.274488047821     0.899961499592    -1.835960153318
    H         1.274488047821     0.899961499592    -1.835960153318
    H         1.274488047821    -0.899961499592    -1.835960153318
}

# *** Test all frequencies by 3-pt formula.
set {
  basis dz
  d_convergence 13
  scf_type pk
}

scf_e, scf_wfn = frequencies('scf', dertype=2,  return_wfn=True)
fd_freqs = scf_wfn.frequencies()
clean()
```

**Comment by JonathonMisiewicz** [comment]
Confirming this bug still exists on up-to-date Psi. RHF hessians run faster with conventional integrals than with DF integrals.

**Comment by JonathonMisiewicz** [comment]
Another user is reporting this bug [on forums](http://forum.psicode.org/t/frequency-calculation-stalls-in-jupyternotebook-python-interpreter/1497).
