### ISSUE TITLE
Have energy derivatives intercept missing analytic methods on auto

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#1149]
If the user doesn't specify how a gradient or hessian is to be computed (difference of energies, difference of gradients, or analytically), Psi will choose to compute it by the most analytic method available to the general method. This leads to annoying crashes when that method isn't available for the more particular variant of the method requested. For instance, the following input file will crash:
```
molecule {
 O 
 H 1 1.0 
 H 1 1.0 2 105 
}

set {
    reference     rks 
    basis sto-3g
}

gradient('wb97x-v')
```

The error is that:
```
Fatal Error: V: RKS cannot compute VV10 gradient contribution.
```

But in that case, Psi shouldn't have tried to do an analytic gradient computation at all but just done finite difference of energies.

I'm not familiar with how the method selection works, but I have a bad feeling that writing this would be rather painful.

**Comment by dgasmith** [comment]
In general, we do catch these but missed the `vv10` edge case. A single line [here](https://github.com/psi4/psi4/blob/master/psi4/driver/procrouting/proc_table.py#L223) will prevent analytic gradients for `vv10` methods.

**Comment by JonathonMisiewicz** [comment]
Oh, thanks for the quick response and the link! I'll want to test to make sure I'm making the right edit first, but I can get this easily.
