### ISSUE TITLE
separate reference from method in energy arguments

### ISSUE THREAD

**Issue by psi4** [psi4/psi4#117]
From discussion today, the following tasks to wrap up https://github.com/psi4/psi4public/issues/103

- [x] In driver.py, delete reference-bearing methods from procedures table (multiple places). Delete table:energy_scf rst table and its analogies. Salvage 'hf' from them and move it into the main rst table.
- [x] In proc.py, remove much of parse_scf_cases, maybe drop that fn and move it back into the run_scf* as it was early this year.
- [x] Inspect test cases for removed functionality and adapt them. Check that the uhf that originally prompted this post is still working. Check that every energy/gradient rhf/uhf/rohf/cuhf/etc scf/hf/b3lyp does something sensible or exits gracefully.
- [x] Check the docs to see if they reference this functionality and adapt them.

**Comment by amjames** [comment]
I'd be happy to pick this one up if no one else is working on it. I just want to clarify is the desired behavior of something like this:
   
   set dft_functional b3lyp
   energy('scf')

Should this run the dft or HF calculation? (amusing the user or the solution to #118 has set the reference properly) Currently this would do the the HF.

**Comment by loriab** [comment]
It'd be great if you wanted to work on this. I'm fine with the current behavior, that the ``set dft_functional b3lyp\n energy('scf')`` runs scf. It's the ``energy('b3lyp')`` notation that we want to be user friendly, and that's already satisfied. Ok to keep the ``set dft_functional b3lyp`` notation straightforward and less user-friendly.

**Comment by amjames** [comment]
I just pushed these changes to the private master

**Comment by dgasmith** [comment]
Looking through the code, it appears that these changes are complete.

Everyone: Has anyone had experiences contrary to the above?
@amjames Can you confirm?

**Comment by amjames** [comment]
@dgasmith, confirmed. I haven't seen/heard of any problems with the changes I added back in July.

**Comment by dgasmith** [comment]
@amjames Excellent, I have received very positive feedback from other folks so I think I will go ahead and close this. We can always open a new issue if we run into problems, but its been about 6 months of everything working well so I think we are fine.
