### ISSUE TITLE
implement adaptable reference for closed/open-shell

### ISSUE THREAD

**Issue by psi4** [psi4/psi4#118]
Follows from discussion in https://github.com/psi4/psi4public/issues/103 and a bit in https://github.com/psi4/psi4private/issues/101

We'd like reference `rhf`, `rohf`, etc. to behave exactly as they do at present, that is cry foul if inappropriate for active molecule or unavailable for the method at hand. But we'd like a new value `auto` for `reference` keyword that is the default and switches between rhf and uhf>rohf as appropriate, depending solely on the molecule. 

Exactly how to this this is up for discussion. It's most appropriately done at activate-molecule-time, but don't have the machinery to track and undo that setting in the activalte molecule code. Maybe a generic function that's called in each run_\* in proc.py with inputs of the most restrictive reference setting among the called modules (e.g., rhf/rohf for run_detci that traverses scf _and_ detci modules). Then the generic function sets the reference to something legit (e.g., `rhf`) for the scope of the energy/grad/etc call. And the optstash object in each of the proc.py routines can be used to undo the driver-level reference setting and return to the user or default setting.
- [ ] implement above. break this into smaller bullets as needed.
- [ ] also, warn in output that reference changing

**Comment by CDSherrill** [comment]
AJ made this comment:

My implementation involved handling cases where the user sets a hf reference and calls a dft method. For example if the input is,

set reference rhf

energy('b3lyp)

the reference option will be set to rks. The goal there was to keep the energy('method') interface user friendly.

If/when psi4public/118 is implemented the smart-reference should be able to handle those conflicts and my checks for these conflicts can probably be removed.

**Comment by dgasmith** [comment]
In some ways this is completed (via AJ's changes). For the fully `auto` feature I have appended this to the wish list; however, from recent discussion here and raised issues this may be more theoretically problematic than we really want to get into.
