### ISSUE TITLE
doc: The manual is hiding the good stuff from us.

### ISSUE THREAD

**Issue by PeterKraus** [psi4/psi4#1218]
As discussed on slack today (5th Sept 2018, 12:00 UTC), there are a few points where the docs are inaccurate:

1) SOSCF with DFT *is* supported; as @dgasmith said, the feature is not thoroughly checked - eg. DAMP and SOSCF should be exclusive.:
https://github.com/psi4/psi4/blob/master/doc/sphinxman/source/scf.rst#second-order-convergence

2) Gradients with LRC and DF integrals *are* supported, as reported by @hokru and confirmed by @dgasmith:
https://github.com/psi4/psi4/blob/b0b8cd19f5a360871277cbcc00193c88c00ec3e9/doc/sphinxman/source/dft.rst#eri-algorithms

Please add more issues below. I currently (Autumn 2018) don't plan to make a PR to fix these.

**Comment by loriab** [comment]
- [ ] Also, molecule input parsing has changed (you can use XYZ files or give overall chgmult now) without benefit of documentation. On me, obviously. Almost entirely backwards compatible (exception is unphysical fragments to signal the code like in isapt1).
