### ISSUE TITLE
Question: Is mp2 relaxed density avilable for double hybird funcitonals?

### ISSUE THREAD

**Issue by tzyii** [psi4/psi4#1236]

**Comment by hokru** [comment]
The DHDF analytic gradients are not implemented and thus the relaxed density is not readily available.
A scaled MP2 density from kohn-sham orbitals could perhaps be constructed through `psi4numpy` means, as an approximation. The contributions from the additional xc-coupling terms arising in DHDF gradient theory should be very small.

**Comment by tzyii** [comment]
@hokru Okay, I see. Thank you for your help.
