### ISSUE TITLE
Range separations not handled properly in libxc interface for range separated functionals

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#1258]
I was just looking through the code in the libxc interface, and I noticed the following in LibXCfunctional.cc
```
        if (xc_functional_->info->flags & XC_FLAGS_HYB_CAM) rangesep++;
        if (xc_functional_->info->flags & XC_FLAGS_HYB_CAMY) rangesep++;
        if (xc_functional_->info->flags & XC_FLAGS_HYB_LC) rangesep++;
        if (xc_functional_->info->flags & XC_FLAGS_HYB_LCY) rangesep++;
```

While this is correct, per se, the thing is that the four cases refer to different kinds of range separation kernels. The case ```XC_FLAGS_HYB_CAM``` is the most common one, and appears to be the only one supported by Psi4.

The other cases should crash, as they will give an incorrect result.

**Comment by dgasmith** [comment]
Interesting, I had believed the other cases were handled by LibXC and the only component we were interested in is if they needed wK or not. As a note this was directly copied out of the wiki at one stage. What needs to be done to add Yukawa screening and what exactly is LC then?

**Comment by susilehtola** [comment]
I'm also still wondering about the code snippet
```
           // SR      = LibXC_ALPHA + LibXC_BETA = psi4.set_x_alpha
            // LR      = LibXC_ALPHA              = psi4.set_x_alpha + psi4.set_x_beta
            // LR - SR =             - LibXC_BETA =                    psi4.set_x_beta
```
in the same file. I have a vague recollection of discussing this here, but I don't remember the end result. Namely, ```src/export_functional.cc``` states
```
        .def("set_x_alpha", &SuperFunctional::set_x_alpha, "Sets the amount of exact global HF exchange.")
        .def("set_x_beta", &SuperFunctional::set_x_beta, "Sets the amount of exact HF exchange at long range.")
```
which doesn't agree with the code. Namely, in libxc the ```alpha``` parameter is the coefficient for global exact exchange, whereas ```beta``` is the coefficient for short-range-only exact exchange. The description should be improved at the very least....

**Comment by susilehtola** [comment]
> Interesting, I had believed the other cases were handled by LibXC and the only component we were interested in is if they needed wK or not. As a note this was directly copied out of the wiki at one stage. What needs to be done to add Yukawa screening and what exactly is LC then?

They are handled in libxc in the same way CAM is. Namely, if you use a range-separated hybrid, libxc only computes the local component. It is the responsibility of the downstream code to do the range-separated exact exchange.

I have a vague recollection of seeing a paper (I think the authors were Japanese) that discussed how the Yukawa exchange can be calculated in Gaussian basis sets. I never implemented it in ERKALE since basically all functionals just use the error function method which is trivial to implement in Gaussian programs.

**Comment by dgasmith** [comment]
@susilehtola Sure good point, `set_x_beta` is the amount of additional `wK` exchange for us. We can edit that at some point in the future.

So Yukawa is out, what is the difference between LC and CAM then and why does our case not handle those.

**Comment by susilehtola** [comment]
> @susilehtola Sure good point, `set_x_beta` is the amount of additional `wK` exchange for us. We can edit that at some point in the future.

... and by `wK` you mean **long-range** exchange defined with the wrong sign? :laughing: 

> So Yukawa is out, what is the difference between LC and CAM then and why does our case not handle those.

OK, I can see now you have probably copied the code from ```xc-info.c```, which does not care about the difference between the different kinds of range separation kernels.

I found the reference which describes the integrals
https://www.sciencedirect.com/science/article/pii/S0009261408010609?via%3Dihub
which is just a modification of the Boys functions.

However, there are only *two* functionals in libxc that use the Yukawa LCY scheme (`hyb_gga_xc_lcy_pbe` and `hyb_gga_xc_lcy_blyp`), and another two that use the CAMY scheme (`hyb_gga_xc_camy_blyp` and `hyb_gga_xc_camy_b3lyp`). On a quick glance I don't know what the difference between the LCY and CAMY approaches is....

**Comment by dgasmith** [comment]
Happy to nix the LCY and CAMY functionals on the initializer. Mostly curious what to do about the straight LC functionals. Looking at the source code shows the flag `XC_FLAGS_HYB_LC` is not used, `XC_FLAGS_HYB_LCY` is used however. Perhaps a bit of legacy code there to differentiate between "true" long-range functionals and CAM functionals.

Oh sign wars are great fun. CI/MCSCF is especially bad at that.

**Comment by PeterKraus** [comment]
I think part of the problem with signs was my rather careless implementation of `dict_funcs` - I really didn't want to touch the C++ part. If I left those inconsistencies in, my apologies. it's good that somebody found the time to review both the C++ and python parts of this.

As long as `dft-bench-interaction` and `dft-bench-ionization` pass, I'm happy...

**Comment by susilehtola** [comment]
Since #1260 has been merged, should this bug and #1259 be closed or is there something else that still needs to be done?

**Comment by loriab** [comment]
Your issues and PR, so I think if you're satisfied, close them. I don't know of any complicating factors.

**Comment by susilehtola** [comment]
OK, I was just wondering why github is showing 2 of 6 tasks complete, but I see that's because of the checkboxes in the issue template.
