### ISSUE TITLE
Missing DFT Test coverage

### ISSUE THREAD

**Issue by dgasmith** [psi4/psi4#1266]
As @PeterKraus points out we have the following missing tests:

```
missing = ['B1WC', 'B2GPPLYP', 'B2PLYP', 'B3LYPs', 'B86B95', 'B86BPBE', 
           'B96B95', 'B97-1p', 'B97-GGA1', 'BHandH', 'BHandHLYP', 'CAMY-B3LYP', 
           'CAMY-BLYP', 'CAP0', 'CORE-DSD-BLYP', 'DSD-BLYP', 'DSD-PBEB95', 'DSD-PBEP86', 
           'DSD-PBEPBE', 'HCTH407P', 'HCTHP14', 'HF', 'HJS-B97X', 'HJS-PBE', 'HJS-PBE-SOL',
           'HPBEINT', 'HSE03', 'HSE06', 'KSDT', 'KT2', 'LCY-BLYP', 'LCY-PBE', 'LRC-WPBE', 
           'MB3LYP-RC04', 'MN15', 'MOHLYP', 'MOHLYP2', 'OP-PBE', 'PBE0-13', 'PBE0-2', 
           'PBE0-DH', 'PBE1W', 'PBELYP1W', 'PTPSS', 'PW86B95', 'PW86PBE', 'PWPB95', 
           'RPBE', 'SB98-1a', 'SB98-1b', 'SB98-1c', 'SB98-2a', 'SB98-2b', 'SB98-2c', 'SVWN', 
           'TETER93', 'TH-FC', 'TH-FCFO', 'TH-FCO', 'TH-FL', 'TH1', 'TH2', 'TH3', 'TH4', 
           'TPSSLYP1W', 'TUNED-CAM-B3LYP', 'XLYP', 'ZLP', 
           'mPW1PW', 'mPW3LYP', 'mPW3PW', 'mPWLYP1', 'mPWLYP1M', 
           'mPWLYP1W', 'mPWPW', 'revB3LYP', 'wPBE', 'wPBE0', "X1B95", "XB1K"]

skip = ["HCTHP76", # scf fail
        "HJS-B88", # C_DSYEV failed
        "FT97",    # C_DSYEV failed
        ]
```

Several functionals like B2PLYP are tested outside `dft-bench-*` tests and are covered. In general, we have good coverage of the different runs of functionals at this point and we should rely somewhat that LibXC tests individual functionals well. So functionals purely defined by LibXC should be fine in general.

The primary concerning points above are the `*wPBE*` series and `SVWN` are not well tested and are curated by us. This issue will be closed by hunting down references and adding tests for the above.

FT97 and co have historically been problematic for us. I would be curious if this is due to instabilities in FT97 or something on our end.

**Comment by susilehtola** [comment]
Unfortunately, historically the reliability of the libxc testing hasn't been very good, the main reason being that the main developers aren't quantum chemists and haven't had access to a Gaussian basis program. Because most functionals have been trained with a Gaussian basis set, reference values are usually given. Unfortunately, very few paper actually give raw datapoints, and running e.g. G2 atomization energies to validate a single functional might not really make sense....

**Comment by dgasmith** [comment]
This has largely been resolved, thanks to everyone who helped out building the DFT testing infrastructure.
