### ISSUE TITLE
Calcium Basis Set Error?

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#1271]
Reposted from forum with modification.

The following attempt at open-shell SAPT fails with segfault `forrtl: severe (174): SIGSEGV, segmentation fault occurred`. Original reporter concluded it was a problem with Calcium, as modifying it to Chlorine (along with the charges) resulted in a successful computation. The example molecule is reduced from the original report, for ease of reproduction. 40 GB is (hopefully) enough to indicate this is not a problem of needing more memory.

```memory 40 gb
molecule {
0 1
H -0.803001 1.098737 0.000360
H -0.919454 -1.089722 0.000521
O -0.035537 -0.067631 0.000218
--
2 1
Ca 2.281447 -0.004247 -0.000154
units angstrom
no_reorient
symmetry c1
}

set globals {
scf_type df
FREEZE_CORE true
}

basis {
assign aug-cc-pVTZ
assign Ca def2-TZVPP
}

df_basis_scf {
assign aug-cc-pVTZ-jkfit
assign Ca def2-TZVPP-jkfit
}

df_basis_sapt {
assign aug-cc-pVTZ-RI
assign Ca def2-TZVPP-ri
}

energy('sapt0')```

**Comment by jgonthier** [comment]
Maybe I am missing something, but are you sure this is open-shell SAPT? It seems these are two closed-shell singlet systems, I would then expect the default treatment to be restricted.

**Comment by JonathonMisiewicz** [comment]
My mistake - the HF computations are all closed-shell. Nothing is printed to the output file to clarify which SAPT0 is running.

**Comment by PeterKraus** [comment]
The problem is that with `freeze_core True`, the second monomer (Ca2+) has no unfrozen electrons. I'm not sure what the proper fix would be: probably `freeze_core $n` support (where `$n` is n-th previous period).

**Comment by JonathonMisiewicz** [comment]
Good detective work!

Fixing this issue wouldn't require `freeze_core $n` support, only changing the default behavior when the core level isn't the same as in the neutral species. I'll suggest this as a possible new developer issue at the conference today.

_That said_, it would also be really nice to be able to set the core level for individual atoms, rather than going through the clunky and somewhat obscure `num_frozen_docc` and `frozen_docc`. We have a project in my research group that requires correlating an extra level of electrons just for neutral calcium.
