### ISSUE TITLE
DETCI yields different energies with different diag_methods

### ISSUE THREAD

**Issue by bozkaya** [psi4/psi4#1281]
Hi everyone,

When I run the following input I get different energies depending on the diag_method. While RSP gives the correct zeroth root of H0 as the ground state energy, the default one gives the first root energy as the ground state energy. With RSP Total CI energy =    -149.601664883615285; with the default one Total CI energy =    -149.577513236489096.

İnput:
```
molecule {
0 1
O
O 1 1.2156
symmetry c1
}

set {
  basis 6-311++G(d)
  reference rohf
  frozen_docc [7]
  frozen_uocc [35]
  diag_method rsp
}
energy('detci')
```
@dgasmith @CDSherrill

**Comment by dgasmith** [comment]
Looks like a bad starting guess, adjusting `H0_BLOCKSIZE 2000` will probably get you on track.

**Comment by dgasmith** [comment]
Closing this down, this seems more of an initial guess issue than an error in default SEM algorithm and one that I don't think we can fix in a wholistic manner.
