### ISSUE TITLE
full_hess_every N with N > 0 does not work as expected

### ISSUE THREAD

**Issue by tgaillard** [psi4/psi4#1282]
Dear Psi4 developers,

The 'full_hess_every N' functionality, used to compute the full Hessian
every N steps in an optimization, does not work as expected for N > 0:
the Hessian is always recalculated on the initial structure instead of
the current one.

This can be tested as follows.

First, we only calculate the Hessian initially (full_hess_every 0). The
minimization converges in 7 steps to an R=0.95, B=104.6 geometry. The
frequencies obtained are 1776, 4112, 4211.

#input: hess0.in
molecule h2o {
  symmetry c1
  O
  H 1 R
  H 1 R 2 B
  R = 1.2
  B = 120
}
set basis cc-pVDZ
set full_hess_every 0
optimize('scf', dertype='gradient')
freq('scf', dertype='gradient')

#grep '~' hess0.out
      1     -75.93350508   -7.59e+01      1.35e-01      1.14e-01 o    3.44e-01      2.89e-01 o  ~
      2     -76.01434847   -8.08e-02      6.88e-02      5.91e-02 o    2.89e-01      2.51e-01 o  ~
      3     -76.00936003    4.99e-03      1.27e-01      1.04e-01 o    1.83e-01      1.51e-01 o  ~
      4     -76.02647334   -1.71e-02      1.62e-02      1.35e-02 o    4.78e-02      4.32e-02 o  ~
      5     -76.02694403   -4.71e-04      6.79e-03      5.64e-03 o    1.47e-02      1.11e-02 o  ~
      6     -76.02702784   -8.38e-05      1.73e-03      1.43e-03 o    2.89e-03      2.48e-03 o  ~
      7     -76.02703276   -4.93e-06      1.05e-04 *    8.74e-05 o    1.63e-04 *    1.45e-04 o  ~

#grep -A1 'post-proj  all' hess0.out
  post-proj  all modes:['0.0000i' '0.0000i' '0.0000i' '1103.2728' '1246.1842' '1310.1099'
 '1334.3071' '1578.1703' '1760.1248']
  post-proj  all modes:['0.0000i' '0.0000i' '0.0000i' '0.0000i' '0.0000' '0.0001' '1776.3032'
 '4112.4185' '4210.8898']

Now, we calculate the Hessian at every step (full_hess_every 1). The
minimization does not converge after 15 steps. The energy printed at
each step is always the initial energy. The frequencies obtained at each
step are always the initial frequencies.

#input: hess1.in
...
set full_hess_every 1
...

#grep '~' hess1.out
      1     -75.93350508   -7.59e+01      1.35e-01      1.14e-01 o    3.44e-01      2.89e-01 o  ~
      2     -75.93350508    5.68e-14 *    6.88e-02      5.91e-02 o    3.43e-01      2.89e-01 o  ~
      3     -75.93350508    0.00e+00 *    1.90e-01      1.55e-01 o    8.83e-02      7.22e-02 o  ~
      4     -75.93350508    0.00e+00 *    9.14e-02      7.47e-02 o    2.21e-02      1.80e-02 o  ~
      5     -75.93350508   -1.42e-14 *    7.13e-02      5.82e-02 o    5.52e-03      4.51e-03 o  ~
      6     -75.93350508    1.42e-14 *    6.65e-02      5.43e-02 o    5.52e-03      4.51e-03 o  ~
      7     -75.93350508    0.00e+00 *    6.18e-02      5.05e-02 o    1.38e-03      1.13e-03 o  ~
      8     -75.93350508   -1.42e-14 *    6.06e-02      4.95e-02 o    7.08e-04 *    5.78e-04 o  ~
      9     -75.93350508   -5.68e-14 *    6.00e-02      4.90e-02 o    7.08e-04 *    5.78e-04 o  ~
     10     -75.93350508    2.84e-14 *    5.94e-02      4.85e-02 o    7.08e-04 *    5.78e-04 o  ~
     11     -75.93350508    2.84e-14 *    5.88e-02      4.81e-02 o    7.08e-04 *    5.78e-04 o  ~
     12     -75.93350508    1.42e-14 *    5.83e-02      4.76e-02 o    7.08e-04 *    5.78e-04 o  ~
     13     -75.93350508    1.42e-14 *    5.77e-02      4.71e-02 o    7.08e-04 *    5.78e-04 o  ~
     14     -75.93350508    2.84e-14 *    5.71e-02      4.66e-02 o    7.08e-04 *    5.78e-04 o  ~
     15     -75.93350508   -4.26e-14 *    5.65e-02      4.61e-02 o    7.08e-04 *    5.78e-04 o  ~

#grep -A1 'post-proj  all' hess1.out
  post-proj  all modes:['0.0000i' '0.0000' '0.0000' '1103.2780' '1246.1860' '1310.1117'
 '1334.3068' '1578.1646' '1760.1239']
  post-proj  all modes:['0.0000i' '0.0000' '0.0001' '1103.2762' '1246.1803' '1310.1384'
 '1334.2986' '1578.1704' '1760.1295']
  post-proj  all modes:['0.0000i' '0.0000i' '0.0000' '1103.2762' '1246.1803' '1310.1384'
 '1334.2986' '1578.1704' '1760.1295']
  post-proj  all modes:['0.0000i' '0.0000' '0.0000' '1103.2762' '1246.1803' '1310.1384'
 '1334.2986' '1578.1704' '1760.1295']
  post-proj  all modes:['0.0000i' '0.0000' '0.0000' '1103.2762' '1246.1803' '1310.1384'
 '1334.2986' '1578.1704' '1760.1295']
  post-proj  all modes:['0.0000i' '0.0000i' '0.0000' '1103.2762' '1246.1803' '1310.1384'
 '1334.2986' '1578.1704' '1760.1295']
  post-proj  all modes:['0.0000i' '0.0000i' '0.0000' '1103.2762' '1246.1803' '1310.1384'
 '1334.2986' '1578.1704' '1760.1295']
  post-proj  all modes:['0.0000i' '0.0000i' '0.0000' '1103.2762' '1246.1803' '1310.1384'
 '1334.2986' '1578.1704' '1760.1295']
  post-proj  all modes:['0.0000i' '0.0000' '0.0000' '1103.2762' '1246.1803' '1310.1384'
 '1334.2986' '1578.1704' '1760.1295']
  post-proj  all modes:['0.0000i' '0.0000i' '0.0000' '1103.2762' '1246.1803' '1310.1384'
 '1334.2986' '1578.1704' '1760.1295']
  post-proj  all modes:['0.0000i' '0.0000i' '0.0000' '1103.2762' '1246.1803' '1310.1384'
 '1334.2986' '1578.1704' '1760.1295']
  post-proj  all modes:['0.0000i' '0.0000i' '0.0000' '1103.2762' '1246.1803' '1310.1384'
 '1334.2986' '1578.1704' '1760.1295']
  post-proj  all modes:['0.0000i' '0.0000' '0.0000' '1103.2762' '1246.1803' '1310.1384'
 '1334.2986' '1578.1704' '1760.1295']
  post-proj  all modes:['0.0000i' '0.0000i' '0.0000' '1103.2762' '1246.1803' '1310.1384'
 '1334.2986' '1578.1704' '1760.1295']
  post-proj  all modes:['0.0000i' '0.0000i' '0.0000' '1103.2762' '1246.1803' '1310.1384'
 '1334.2986' '1578.1704' '1760.1295']

Best regards,

Thomas Gaillard

**Comment by JonathonMisiewicz** [comment]
@tgaillard This bug has been fixed by #1299, so it will be fixed in Psi 1.3 and all future alpha/beta versions of 1.3. If you need this issue fixed for your current research, let us know, and we'll help you get Psi updated in the least painful way possible. (Warning: Psi 1.3 includes updates to physical constants, so results will differ slightly from those in Psi 1.2.) Otherwise, we'll close the issue.

**Comment by tgaillard** [comment]
Thanks for the fix! The issue can be closed.
