### ISSUE TITLE
SCF iteration no longer printed immediatetly

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#1284]
[Psi4 1.3a2.dev48 Git: Rev {master} cb34149]

Can anybody confirm or deny that SCF iterations are no longer printed as they finish, but instead only in bulk when everything is done (like a buffered output). 

For testing if needed:
```
molecule benzene {
symmetry c1
    pubchem:benzene
}

memory 1 GiB
energy('hf/def2-QZVP')
```

**Comment by PeterKraus** [comment]
I can confirm this behaviour both with `Git: Rev {cbs_dict} f7ec10e` and `Psi4 1.3a1 Git: Rev {HEAD} fdfe778`, executed as:

```
psi4 -n 1 input.py -o output.dat
```
When `tail -f`-ing the output, it stops just before the `==> Iterations <==` header is printed, and then prints out the rest of the file once the iterations are converged.

**Comment by dgasmith** [comment]
Doesn't look like I can reproduce this, can a few other try?
