### ISSUE TITLE
possible bug in output file name

### ISSUE THREAD

**Issue by timn2008** [psi4/psi4#1286]
Hi!
It seems that when the input file is e.g. `some_name.dat.xyz.dat` , psi4 creates the 
output file named `some_name.out.xyz.out`  instead of just `some_name.dat.xyz.out`.
My guess would be that enything except for the file extension (the last `.dat` in this case)
should be untouched...

**Comment by amjames** [comment]
[Here](https://github.com/psi4/psi4/blob/f687f496d84aeb72162db36d7da4b5577ed7a4cb/psi4/run_psi4.py#L139) would be the culprit. 

If the input file name ends in `.dat`, then the default name of the output file will replace `.dat` with `.out`. I guess the replacement should only be done on the last occurence of `.dat`. The same for `.in` as something like `some_name.in_group_1.in` would produce an out file name of `some_name.out_group_1.out`.

**Comment by hokru** [comment]
I wanted to do something similar some time ago in a small script.

Here is the code analogue I used, if somebody wants to improve upon it.

```
    elif args["input"].endswith(".in"):
        idx=args["input"].rfind(".in")
        print(idx,args["input"][0:idx]+".out")
        args["output"] = args["input"][0:idx]+".out"
```

**Comment by loriab** [comment]
I think pathlib and suffixes would do the trick https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.suffixes
