### ISSUE TITLE
Replace deprecated `dtzrqf` with alternative

### ISSUE THREAD

**Issue by albandil** [psi4/psi4#1290]
**psi4** uses the LAPACK routine `dtzrqf`. However, at least in the current LAPACK 3.8.0, the routine `dtzrqf` is marked as deprecated, the [suggested alternative](http://www.netlib.org/lapack/explore-html/da/dba/group__double_o_t_h_e_rcomputational_ga2d309addf953bcdd497d58608a7f7935.html) being `dtzrzf`.

As a result, the default build of LAPACK 3.8.0 (<del>as well as of OpenBLAS 0.3.3</del> EDITED) does not contain `dtzrqf`anymore and fails to provide the necessary dependency. Perhaps **psi4** could use the alternative routine to avoid this problem?

**Comment by robertodr** [comment]
I am working on a fix for this and it seems there are additional subroutines that have been deprecated:
```
nm stage/lib/psi4/core.cpython-36m-x86_64-linux-gnu.so | grep ' U '

U dgegs_
U dgegv_
U dgelsx_
U dgeqpf_
U dggsvd_
U dggsvp_
```

**Comment by robertodr** [comment]
I am working on a fix for this and it seems there are additional subroutines that have been deprecated:
```
nm stage/lib/psi4/core.cpython-36m-x86_64-linux-gnu.so | grep ' U '

U dgegs_
U dgegv_
U dgelsx_
U dgeqpf_
U dggsvd_
U dggsvp_
```
