### ISSUE TITLE
Psi4 User Survey

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#1293]
Everyone is entreated to fill out the 2018 Psi4 User survey https://molssi.typeform.com/to/Rwz1KF and to forward it on to anyone you know who has used Psi. We know how the dev groups use Psi4 and how people who walk up to Profs. Crawford and Sherrill at conferences like and use Psi4 but not much else. It’d be a great favor if you’d tell us more.

Please complete by 1 Nov so we can digest results before PsiCon2018.

**Comment by PeterKraus** [comment]
The results of the survey, and other slides from PsiCon2018, can be found [here](https://github.com/psi4/PsiCon2018). Closing.
