### ISSUE TITLE
Odd parallelisation behaviour in frequencies by findif of gradient

### ISSUE THREAD

**Issue by PeterKraus** [psi4/psi4#1295]
During debugging of the failing (on Windows) test in #1235, I have noticed the following:
```
(psi4-dev-cbs_dict) kraus@dream:~/psi4/tests/cbs-xtpl-freq::psi4 -n 1 -i in.dat -o n1.out
	Nuclear repulsion energy..........................................PASSED
 6 displacements needed.
 1 2 3 4 5 6
	SCF/cc-pVDZ Frequency 1...........................................PASSED
	SCF/cc-pVDZ Frequency 2...........................................PASSED
	SCF/cc-pVDZ Frequency 3...........................................PASSED
(psi4-dev-cbs_dict) kraus@dream:~/psi4/tests/cbs-xtpl-freq::psi4 -n 4 -i in.dat -o n4.out
	Nuclear repulsion energy..........................................PASSED
 9 displacements needed.
 1 2 3 4 5 6 7 8 9
Warning: used thermodynamics relations inappropriate for low-frequency modes: ['476.8559' '479.2930' '484.2715']
	SCF/cc-pVDZ Frequency 1: computed value (1809.246) does not match (476.856) to 2 digits.
Traceback (most recent call last):
  File "/home/kraus/Applications/psi4-cbs_dict/bin/psi4", line 271, in <module>
    exec(content)
  File "<string>", line 34, in <module>
  File "/home/kraus/Applications/psi4-cbs_dict/lib/psi4/driver/p4util/util.py", line 227, in compare_values
    raise TestComparisonError(message)

TestComparisonError: 	SCF/cc-pVDZ Frequency 1: computed value (1809.246) does not match (476.856) to 2 digits.
```
The in.dat, n1.out and n2.out files are attached.
[in.txt](https://github.com/psi4/psi4/files/2488549/in.txt)
[n1.txt](https://github.com/psi4/psi4/files/2488550/n1.txt)
[n4.txt](https://github.com/psi4/psi4/files/2488551/n4.txt)

The number of SALC's  in the parallel version (see line 362) is wrong: it should be 3, it is 6. @JonathonMisiewicz , ideas?

**Comment by JonathonMisiewicz** [comment]
Compare line 348 between the two files. The gradient rms differs, leading to rotations to be projected in the serial version but not the parallel. The gradients printed immediately above agree to ten decimal places, but the reported discrepancy in the rms gradients is in the third decimal place. It looks like the rms gradient isn't being computed correctly.

**Comment by PeterKraus** [comment]
The gradient rms is huge. In fact, the geometry clearly isn't at the minimum - when optimised with `g_convergence gau_verytight`, the bond length is a lot different. I've modified the test case.

Is such a large discrepancy in RMS of the gradient (23%), just due to the number of cores, something worrying (even though it's not at the minimum)? Or is that to be expected, and I should just close this issue?

**Comment by PeterKraus** [comment]
The serial jobs don't have any scatter, the RMS is always `rms=9.29E-03` with total gradient:
```
    -Total Gradient:
       Atom            X                  Y                   Z
      ------   -----------------  -----------------  -----------------
         1       -0.000000000000     0.000000000000    -0.017641624495
         2        0.000000000000    -0.012438412634     0.008820812248
         3       -0.000000000000     0.012438412634     0.008820812248
```

The parallel jobs differ in the last 2 significant figures of the gradient, and the RMS itself varies between `rms=1.14E-02` and `1.61E-02`. If I can help any further, let me know.
