### ISSUE TITLE
Backwards Incompatibility: Coordinates Have Been Set in the Wrong Order

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#1325]
Discovered on a build of 8db12d6 while investigating [a forum post](http://forum.psicode.org/t/ri-mp2-def2-tzvppd-convergence-issue-for-calculations-with-iodide/1106/5). The user's input file crashes during the MP2 computation with traceback:

```
Traceback (most recent call last):
  File "/opt/vulcan/opt/vulcan/linux-x86_64/intel-16.0.1/psi4-master-avducsgnonqrcpftiesq432gagal6y7r/bin/psi4", line 272, in <module>
    exec(content)
  File "<string>", line 100, in <module>
  File "/opt/vulcan/opt/vulcan/linux-x86_64/intel-16.0.1/psi4-master-avducsgnonqrcpftiesq432gagal6y7r/lib/psi4/driver/driver.py", line 431, in energy
    return driver_nbody.nbody_gufunc(energy, name, ptype='energy', **kwargs)
  File "/opt/vulcan/opt/vulcan/linux-x86_64/intel-16.0.1/psi4-master-avducsgnonqrcpftiesq432gagal6y7r/lib/psi4/driver/driver_nbody.py", line 225, in nbody_gufunc
    component_results = compute_nbody_components(func, method_string, metadata)
  File "/opt/vulcan/opt/vulcan/linux-x86_64/intel-16.0.1/psi4-master-avducsgnonqrcpftiesq432gagal6y7r/lib/psi4/driver/driver_nbody.py", line 411, in compute_nbody_components
    current_mol = molecule.extract_subsets(list(pair[0]), ghost)

RuntimeError: 
Fatal Error: Coordinates have been set in the wrong order
Error occurred in file: /home/vulcan/vadmin/programs/psi4/psi4/src/psi4/libmints/coordentry.cc on line: 239 
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)
psi::Molecule::operator=(psi::Molecule const&)
psi::Molecule::Molecule(psi::Molecule const&)
```

Given that the user's problem is failure for the SCF to converge, I can only assume some change since the 1.2.1 release is at fault. I've been able to get the crash with the following simplified input file:
```
molecule dimer {
1 1
 C1      0.000000    0.513942    0.000000
 N2      0.628754    1.703580    0.000000
 H3      0.109407    2.571793    0.000000
 H4      1.638743    1.762759    0.000000
 N5     -1.342220    0.473050    0.000000
 H6     -1.890262    1.323784    0.000000
 H7     -1.839824   -0.407373    0.000000
 N8      0.700723   -0.623756    0.000000
 H9      1.712010   -0.555355    0.000000
 C10     0.085273   -1.957243    0.000000
 H11     0.892679   -2.697454    0.000000
 H12    -0.522596   -2.104233    0.905528
 H13    -0.522596   -2.104233   -0.905528
--
-1 1
 I   N8   3.6   H9   90.0   C1   90.0
}

basis {

   assign H   def2-tzvpd
   assign C   def2-tzvpd
   assign N   def2-tzvpd

   assign I   def2-tzvpd
}

set guess sad
set scf_type df
set maxiter 500
set soscf true
set soscf_max_iter 15
set soscf_conv 1.e-4
set freeze_core false   ## false for ions

energy("mp2", bsse_type = "cp")
```
This can probably be simplified further. It would be worth investigating whether this is a consequence of mixing Cartesian and ZMAT coordinates.

**Comment by loriab** [comment]
Do we allow non-integer indexing for zmat? I hadn't thought so. Same error if `I 8 3.6 9 90.0 1 90.0`?

**Comment by JonathonMisiewicz** [comment]
Yes, the error remains upon replacing the ZMAT line to use integer indices.

**Comment by loriab** [comment]
I think it's a bad interaction between mixed-cart/zmat + counterpoise. The below triggers it, but it's fine w/o cp or with pure zmat frags.

```
molecule {
He 0 0 0
He 1 0 0
He 2 0 0
--
He 1 2.0 2 90.0 3 176.0
}

basis {
assign He def2-tzvpp
}

energy("mp2", bsse_type="cp")
```

A bug, but probably one to be warded off rather than hunted down?

**Comment by JonathonMisiewicz** [comment]
I'm of the opinion that we should either hunt it down or leave an error message describing how the input _should_ have been written. Given what the user is trying to do, the approach they took is the one I would have tried first.

**Comment by PeterKraus** [comment]
I'd vote for this being fixed. If it's not super urgent, I might give it a go over the next month. I can see this zmat/cart combination being useful when someone would like to investigate a PES for non-covalent complexes.

**Comment by JonathonMisiewicz** [comment]
This bug has been holding up a forum help request for a couple weeks, but beyond that, this isn't urgent at all. Good luck!

It occurs to me that I was messing with the ZMAT/Cartesian recognition system in #1108. The changes I made _shouldn't_ have broken anything, but that would explain why we're getting this bug in dev, but user isn't getting it in 1.2.1. Send me a message if you need me to explain the context for that PR. The bug I was wrangling was nasty, so my issue description may be a little confusing.

**Comment by JonathonMisiewicz** [comment]
Unfortunately, I was right. Commenting out [this line I added in #1108 ](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libmints/coordentry.h#L372) fixes the issue.

That particular line ensures that when cloning a CoordEntry as part of cloning a molecule, the clone of a ZMAT coordinate inherits the computed Cartesians of the original atom, if any. That change was vital to prevent a bug where basis sets wouldn't be centered on atoms after cloning, and I believe that needs to be kept.

I know Peter said he planned to hack on this, but I'm tempted to take this myself. This is holding me up from helping a user on the forum.

**Comment by PeterKraus** [comment]
Go ahead, I have not even started.
