### ISSUE TITLE
PsiPEP 002

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#1375]
# PsiPEP2: Rationalize Variable Access

Pursuant to #883, common driver migration, the War Against Globals, and [QCSchema](https://github.com/molssi/qcschema), we want clear programmatic access to QC quantities, and we want them on the Wfn/JSONrec, not off `Process.environment.globals`. First step toward this is duplication of `P::e.globals` onto `Wfn`. Unfortunately, the syntax and methods don't align (see table below). Also unfortunately, we have many redundant `get_`s. This PsiPEP proposes the following syntax changes and additions.

### Final Proposal (dynamic)

* **W-C** means C-side access to `psi4.core.Wavefunction`
* **W-Py** means Py-side access to `psi4.core.Wavefunction`
* **G-Py** means Py-side access to `psi4.core` globals

| Now `Wavefunction` | Now `psi4.core` | Proposed Both | W-C | W-Py | G-Py | doc |
|-----|----|----|---|---|---|---|
| | has_variable | has_scalar_variable |y|y|y| is float var set ? |
| get_variable | get_variable | scalar_variable |y|y|y| return float var value |
| set_variable | set_variable | set_scalar_variable |y|y|y | set float var value |
| | | del_scalar_variable |y|y|y | unset float var |
| variables | get_variables | scalar_variables |y|y|y| return dict of all float vars |
| |
| | | has_array_variable |y|y|y| is array var set ? |
| get_array | get_array_variable | array_variable |y|y|y| return array var value |
| set_array | set_array_variable | set_array_variable |y|y|y| set array var value |
| | | del_array_variable |y|y|y| unset array var |
| arrays | get_array_variables | array_variables |y|y|y| return dict of all array vars |
| |
| | | has_variable |–|y|y| is any float or array var set ?|
| | | variable |–|y|y| return float or array var value |
| | | set_variable |–|y|y| set float/Matrix/ndarray var value |
| | | del_variable |–|y|y| unset float or array var |
| | | variables |–|y|y| return dict of all float or array vars |
| | clean_variables | clean_variables |–|–|y| unset all float or array vars |

### Original Proposal (static)

| Now `Wavefunction` | Now `psi4.core` | Proposed Both | doc |
|-----|----|----|---|
| | has_variable | has_variable | is float var set ? |
| get_variable | get_variable | variable | return float var value |
| set_variable | set_variable | set_variable | set float var value |
| | | del_variable | unset float var |
| |
| variables | get_variables | variables | return dict of float vars |
| | clean_variables | clean_variables | unset all float vars |
| |
| | | has_array_variable | is array var set ? |
| get_array | get_array_variable | array_variable | return array var value |
| set_array | set_array_variable | set_array_variable | set array var value |
| | | del_array_variable | unset array var |
| |
| arrays | get_array_variables | array_variables | return dict of array vars |
| | | clean_array_variables | unset all array vars |

### Questions

- [x] No, nothing will break immediately. Use of old syntax will yield runtime `FutureWarning`s if called from Python or compile-time `PSI_DEPRECATED` warnings if called from C++. Old syntax will stop working in Psi4 v1.4.

- [x] Note that QCDB (common driver) and QCSchema (I think) merge float vars and array vars into single ~dict. Do we want to consider single access / multi storage in the C++ classes so number of accessors is halved? **EDIT** Answer: yes (see table above), going with multi storage C-side, multi access C-side, unified access Py-side.

- Any other changes to suggested syntax.

- Whole point of posting this as a PEP instead of leaving it on core-dev is so users/downstream/interested parties can weigh in. Please do so.

**Comment by JonathonMisiewicz** [comment]
Can you elaborate on the first sentence? I understand that globals are a bad for code writing (you have to worry about interference from parts of the code you don't even know about) and maintainability (it's much harder to find what changed a variable value in debugging). I do not understand what globals have to do with QCDB, QCSchema, or to quote #883, "complex Psi4 runs involving multiple computations."

**Comment by loriab** [comment]
Sure. When you do a complex Psi4 job with multiple computations and one global variable space, there's nothing preventing a fci/sto-3g followed by a hf/cc-pvqz from getting a value from `get_variable('FCI TOTAL ENERGY')` or a `DISPERSION CORRECTION` after a CC job. Whereas for `P::e.globals` you'd have to deliberately `clean_variables()`, variable attached to a wavefunction are more likely rationally related. (Though not always. We still have to delete `MP2 TOTAL ENERGY` after a double-hybrid DFT job.)

Whereas the psi4 driver operates a lot with "wavefunction passing" with `return_wfn` and most useful info (primary return val, psivars, basisset, orbital info, mol) stored on it, the analogy with generic objects (e.g., no `psi4.core.Matrix`) is a QCSchema dictionary being passed around via `return_json` holding psivars (or "qcvars" to be generic). Multiple json/wfn structures can be organized into a CBS dict record to describe extrapolations or a findif dict record as you have done. This "dict passing" is how qcdb works. So `P::e.globals` --> `Wfn.variables_` gets quantities localized onto calculations. Then `Wfn.variables_` --> QCSchema `psi4:variables` gets quantities generic and serializable. Let me know if anything needs elaboration.

**Comment by JonathonMisiewicz** [comment]
That's much clearer, thank you.

The syntax seems good to me, but I vote for single access / multi storage. That prevents the syntax from getting unwieldy if we decide we need variables of types other than float and array. My main reason is that having different accessors feels like a clunky interface to me, especially for PsiAPI. Variable getting in PsiAPI should treat types like Python does, not C++.

**Comment by PeterKraus** [comment]
>  (Though not always. We still have to delete `MP2 TOTAL ENERGY` after a double-hybrid DFT job.)

I don't follow - what's wrong with keeping the MP2 total energy around?

**Comment by loriab** [comment]
@PeterKraus I have a dream that (barring SCF convergence, FC/non-FC, DF/CONV, etc.) `MP2 TOTAL ENERGY` for a molecular system should have one value. The contrasting view is that `MP2 TOTAL ENERGY` is whatever is the final result of a MP2 module, regardless of whether the SS/OS components have been SCS-ed or the input reference wavefunction changed from HF to B3LYP.

So for the DH case where the MP2 is using DFT orbitals and the MP2 energies won't be canonical, I'd rather delete the vars. I'm fairly settled on this, but I'm glad to hear other views.
