### ISSUE TITLE
D3 vs D3(BJ) alias handling

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#1404]
Aliasing does not apply to functionals pre-defined in our dictionaries. 

Currently problematic is (again..) `DSD-BLYP` as `dsd-blyp-d3bj` and `dsd-blyp-d3(bj)` use different `dsd-blyp` functional parameters. The first uses the correct dictionary setup, the second uses the `dsd-blyp` fit plus `dashparam.py` data, leading to different results.

The latter can be resolved by defined an alias in the dictionary as well.
I added several aliases in #1320 and this could be considered fixed unless it should be caught somehow.

**Comment by PeterKraus** [comment]
I've checked with 1.3a1, and there trying to run `dsd-blyp-d3(bj)` simply fails.
