### ISSUE TITLE
SNS MP2 installation fails

### ISSUE THREAD

**Issue by jgonthier** [psi4/psi4#1425]
I'm compiling the latest master of Psi4. SNS-MP2 automatic download failed with 
``Cloning into 'snsmp2_external'...
fatal: invalid reference: a035c27
CMake Error at /home/jerome/Documents/Atlanta/PSIcode/psi4public_JFG/obj_rel/external/downstream/snsmp2/snsmp2_external-prefix/tmp/snsmp2_external-gitclone.cmake:75 (message):
  Failed to checkout tag: 'a035c27'
``
Looking up the SNS-MP2 Git I found the tag of the current release to be dd286d3. I replaced it in ``external/downstream/snsmp2/CMakeLists.txt`` and the compilation proceeded.
Is this actually the correct version for SNS-MP2? Should I submit a PR with this tiny change?

**Comment by loriab** [comment]
I had a pr out to them with the codata change. They merged it and I must have deleted the branch with that commit. Will fix. Thanks for catching.
