### ISSUE TITLE
CUHF doesn't include external potential

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#1430]
```psi4/src/psi4/libscf_solver/cuhf.cc``` presently does not include the external potential.

This issue is fixed by #1429.

**Comment by susilehtola** [comment]
To me it seems weird that these aren't included in the core Hamiltonian (?)

**Comment by robertodr** [comment]
These are not in the core Hamiltonian as they are updated at each SCF iteration. Maybe the name of the data member is misleading.

**Comment by susilehtola** [comment]
Fixed in #1456 .
