### ISSUE TITLE
FCIDUMP format

### ISSUE THREAD

**Issue by SebWouters** [psi4/psi4#1431]
Dear developers,

I've received an issue from a user of chemps2. I traced it back to incompatible fcidump and molden files. In particular, the number of orbitals per irrep as indicated in "ORBSYM" of the FCIDUMP file and as written per orbital in the the molden file were different. I might be mistaken, but seems that you write out a symmetry in psi4 numbering convention plus one, from the line:

https://github.com/psi4/psi4/blob/c0b8eb86430673c9e09a180dfe91bf6980a1f9c1/psi4/driver/p4util/fcidump.py#L99

This is not the convention for FCIDUMP. The irrep numbering should be the one originally used in molcas. For d2h, for example, this should be:

    psi4 irrep "0" = Ag  = molcas irrep "1";
    psi4 irrep "1" = B1g = molcas irrep "4";
    psi4 irrep "2" = B2g = molcas irrep "6";
    psi4 irrep "3" = B3g = molcas irrep "7";
    psi4 irrep "4" = Au  = molcas irrep "8";
    psi4 irrep "5" = B1u = molcas irrep "5";
    psi4 irrep "6" = B2u = molcas irrep "3";
    psi4 irrep "7" = B3u = molcas irrep "2";

For a complete mapping of all abelian real-valued point group irreps, see e.g.

https://github.com/SebWouters/CheMPS2/blob/master/CheMPS2/Irreps.cpp#L184

Thanks!

Sebastian

**Comment by dgasmith** [comment]
@andysim I believe this is correct, do you concur?

@SebWouters You seem to have a pretty good handle on exactly where this error occurs, would you mind making a PR to patch this up?

**Comment by SebWouters** [comment]
@dgasmith 
@andysim 
@sunqm

I saw it occurs in 

    psi4/psi4/driver/p4util/fcidump.py

which may be fixed via

    def fcidump_helper(wfn):
    
        nirrep = wfn.nirrep()
        symm   = wfn->molecule().sym_label()
        psi2dump = np.zeros([nirrep], dtype='int')
    
        if ( 'c1' == symm ):
            psi2dump[0] = 1    # A
        if ( 'ci' == symm ):
            psi2dump[0] = 1    # Ag
            psi2dump[1] = 2    # Au
        if ( 'c2' == symm ):
            psi2dump[0] = 1    # A
            psi2dump[1] = 2    # B
        if ( 'cs' == symm ):
            psi2dump[0] = 1    # A'
            psi2dump[1] = 2    # A"
        if ( 'd2' == symm ):
            psi2dump[0] = 1    # A
            psi2dump[1] = 4    # B1
            psi2dump[2] = 3    # B2
            psi2dump[3] = 2    # B3
        if ( 'c2v' == symm ):
            psi2dump[0] = 1    # A1
            psi2dump[1] = 4    # A2
            psi2dump[2] = 2    # B1
            psi2dump[3] = 3    # B2
        if ( 'c2h' == symm ):
            psi2dump[0] = 1    # Ag
            psi2dump[1] = 4    # Bg
            psi2dump[2] = 2    # Au
            psi2dump[3] = 3    # Bu
        if ( 'd2h' == symm ):
            psi2dump[0] = 1    # Ag
            psi2dump[1] = 4    # B1g
            psi2dump[2] = 6    # B2g
            psi2dump[3] = 7    # B3g
            psi2dump[4] = 8    # Au
            psi2dump[5] = 5    # B1u
            psi2dump[6] = 3    # B2u
            psi2dump[7] = 2    # B3u

        return psi2dump

and the replacement

    core.print_out('Writing integrals in FCIDUMP format to ' + fname + '\n')
    psi2dump = fcidump_helper(wfn)
    # Generate FCIDUMP header
    header = '&FCI\n'
    header += 'NORB={:d},\n'.format(nbf)
    header += 'NELEC={:d},\n'.format(nelectron)
    header += 'MS2={:d},\n'.format(wfn.nalpha() - wfn.nbeta())
    header += 'UHF=.{}.,\n'.format(not wfn.same_a_b_orbs()).upper()
    orbsym = ''
    for h in range(active_mopi.n()):
        for n in range(frzcpi[h], frzcpi[h] + active_mopi[h]):
            orbsym += '{:d},'.format(psi2dump[h])
            if not wfn.same_a_b_orbs():
                orbsym += '{:d},'.format(psi2dump[h])
    header += 'ORBSYM={}\n'.format(orbsym)
    header += 'ISYM={:d},\n'.format(psi2dump[wfn.irrep()])
    header += '&END\n'
    with open(fname, 'w') as intdump:
        intdump.write(header)

Please also note that "ISYM" is printed according to FCIDUMP convention on a separate line subsequent the "ORBSYM" line. I do not have an idea whether the wfn.irrep() call is implemented or which equivalent to use, but better versed psi4 programmers will know what to do.

Please note that, for example, in pyscf, there is:

- a package-provided [fcidump](https://github.com/sunqm/pyscf/blob/a22a531a07c862ce3681c0d069c97aa192ede032/pyscf/tools/fcidump.py), and
- a separate [fcidump](https://github.com/sunqm/pyscf/blob/a22a531a07c862ce3681c0d069c97aa192ede032/pyscf/fciqmcscf/fciqmc.py) for interfacing with fciqmc (with reordered orbital irreps),

so it's a common error.

Best regards,
Sebastian

**Comment by SebWouters** [comment]
@sunqm
@dgasmith 

Perhaps one last comment:

There are advantages with the irrep ordering of psi4, chemps2 and pyscf, which Qiming told me. You can use bitwise XOR for performing the group operation. So I thoroughly agree that the convention is better.

I guess that trying to amend the FCIDUMP format, also in openMolcas and Molpro, will yield significant compatibility and backwards compatibility issues, so this is not an option.

But perhaps it wouldn't be bad to establish an own integral dump standard anno 2019, some 30 years of development having occurred since the FCIDUMP file (Comp. Phys. Commun. 54 75 (1989)). I know that openMolcas is also investing time and effort in hdf5, so perhaps something can be done in that direction? Perhaps reach out to them? It doesn't make sense to represent one double with some 20-ish 8-bit characters in a text format. The best arguments in favor of FCIDUMP are readability and manual adjustment, at least the former of which seems not to hold up against hdf5.

Best regards,
Sebastian

**Comment by dgasmith** [comment]
While I agree raw ASCII isn't particularly a good way to go for information transfer as you noted it does seem to be in many places already.

Does FCIDUMP become all that large? It would be hard to justify HDF5 for just a few megabytes of data when there are other formats like JSON/MsgPack/etc that are much more portable.

Microsoft Quantum has a way of passing FCIDUMP like data using YAML with NWChem: https://docs.microsoft.com/en-us/quantum/libraries/chemistry/schema/spec?view=qsharp-preview

However that representation is pretty horrible in terms of data density.

**Comment by robertodr** [comment]
HANDE reads in FCIDUMP and emits HDF5 with the format specified here: https://github.com/hande-qmc/hande/blob/master/src/hdf5_system.F90 Maybe that can be expanded upon?

**Comment by fevangelista** [comment]
@SebWouters, I was on the verge of introducing FCIDUMP in Forte but if an alternative like you describe is available, we would be happy to adopt it instead.

**Comment by JonathonMisiewicz** [comment]
Is this still an issue, given #1453 was merged in?

**Comment by dgasmith** [comment]
Closing, #1453 as @JonathonMisiewicz notes should have fixed this. Please reopen if you find otherwise.
