### ISSUE TITLE
Convergence problem in dfmp2-ecp test

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#1433]
Trying to debug why #1429 is failing, I realized that ```dfmp2-ecp``` is broken also in master. Namely, if you change the guess to ```core```, the output shows
```
  ==> Iterations <==

                           Total Energy        Delta E     RMS |[F,P]|

    Occupation by irrep:
             A1    A2    B1    B2 
    DOCC [     9,    1,    4,    4 ]

   @DF-RHF iter   1:  -308.91202925462852   -3.08912e+02   3.76534e-01 
    Occupation by irrep:
             A1    A2    B1    B2 
    DOCC [     8,    2,    4,    4 ]

   @DF-RHF iter   2:   -50.26696275258255    2.58645e+02   1.14194e-01 DIIS
   @DF-RHF iter   3:  -312.20691537679136   -2.61940e+02   3.74738e-01 DIIS
   @DF-RHF iter   4:  -312.28132654669946   -7.44112e-02   3.74788e-01 DIIS
   @DF-RHF iter   5:  -312.28135900254506   -3.24558e-05   3.74789e-01 DIIS
   @DF-RHF iter   6:  -312.69660060629286   -4.15242e-01   3.74879e-01 DIIS
   @DF-RHF iter   7:  -314.97714389188246   -2.28054e+00   3.75872e-01 DIIS
   @DF-RHF iter   8:  -315.30129310258837   -3.24149e-01   3.76020e-01 DIIS
   @DF-RHF iter   9:  -315.76973734256387   -4.68444e-01   3.76541e-01 DIIS
   @DF-RHF iter  10:  -314.13107099910633    1.63867e+00   3.75335e-01 DIIS
   @DF-RHF iter  11:  -314.88897775403694   -7.57907e-01   3.75895e-01 DIIS
   @DF-RHF iter  12:  -312.91138860100165    1.97759e+00   3.74941e-01 DIIS
   @DF-RHF iter  13:  -313.42095297268111   -5.09564e-01   3.75328e-01 DIIS
   @DF-RHF iter  14:  -314.00208386703940   -5.81131e-01   3.74845e-01 DIIS
   @DF-RHF iter  15:  -313.82934050347035    1.72743e-01   3.74976e-01 DIIS
   @DF-RHF iter  16:  -315.89990741359236   -2.07057e+00   3.76160e-01 DIIS
   @DF-RHF iter  17:  -313.12609734973461    2.77381e+00   3.74988e-01 DIIS
   @DF-RHF iter  18:  -312.92378783647285    2.02310e-01   3.74498e-01 DIIS
   @DF-RHF iter  19:  -317.24645796226451   -4.32267e+00   3.77492e-01 DIIS
   @DF-RHF iter  20:  -317.60418344797176   -3.57725e-01   3.78088e-01 DIIS
   @DF-RHF iter  21:  -316.25416490484400    1.35002e+00   3.76492e-01 DIIS
   @DF-RHF iter  22:  -315.51131292261630    7.42852e-01   3.75711e-01 DIIS
   @DF-RHF iter  23:  -315.37233230819385    1.38981e-01   3.75579e-01 DIIS
   @DF-RHF iter  24:  -315.37427315424492   -1.94085e-03   3.75585e-01 DIIS
   @DF-RHF iter  25:  -315.36730485039720    6.96830e-03   3.75579e-01 DIIS
   @DF-RHF iter  26:  -315.36589297460404    1.41188e-03   3.75578e-01 DIIS
   @DF-RHF iter  27:  -315.36543355687996    4.59418e-04   3.75578e-01 DIIS
   @DF-RHF iter  28:  -315.36456132195099    8.72235e-04   3.75577e-01 DIIS
   @DF-RHF iter  29:  -315.36496171844306   -4.00396e-04   3.75577e-01 DIIS
   @DF-RHF iter  30:  -315.36444779551914    5.13923e-04   3.75577e-01 DIIS
   @DF-RHF iter  31:  -315.36454935016326   -1.01555e-04   3.75577e-01 DIIS
   @DF-RHF iter  32:  -315.36429506717400    2.54283e-04   3.75577e-01 DIIS
   @DF-RHF iter  33:  -315.36492875519383   -6.33688e-04   3.75577e-01 DIIS
   @DF-RHF iter  34:  -315.36475459725352    1.74158e-04   3.75577e-01 DIIS
   @DF-RHF iter  35:  -315.36472123328099    3.33640e-05   3.75577e-01 DIIS
   @DF-RHF iter  36:  -315.36482066630248   -9.94330e-05   3.75577e-01 DIIS
```
The DIIS error hangs around the same number as with the new version of the SAD guess.

The above output is especially weird, since the energy error becomes small while the DIIS error is large.

Could the ECP contribution to the Fock matrix asymmetric? This can yield an energy that appears converged but a large orbital gradient.

**Comment by susilehtola** [comment]
Simplified test case
```
molecule dimer {
    0 1
    Ne 0.0 0.0 0.0
    --
    0 1
    Xe 0.0 0.0 3.0
}

set {
    basis def2-svp
    print 2
}

set guess core
Eall = energy('scf')
```

**Comment by dspoel** [comment]
Having similar convergence problems in a different method trying to run SAPT2+ as a function of distance between two ions. Frozen core on or off does not fix the problem. Has this been fixed in master? Using 1.2.1 for now.

Input:

molecule LiF {
        1 1
        Li  0.000000000  0.000000000  0.000000000
        --
        -1 1
        F  16.000000000  0.000000000  0.000000000

        units angstrom
        no_reorient
}
set globals {
        basis cc-pVTZ
        freeze_core false
        df_scf_guess false
}
set_memory(32000000000)
energy('sapt2+')

Output:

   @DF-RHF iter  96:  -105.75609224148533   -5.68434e-14   1.64830e-02 DIIS
   @DF-RHF iter  97:  -105.75609224148535   -1.42109e-14   1.64830e-02 DIIS
   @DF-RHF iter  98:  -105.75609224148535    0.00000e+00   1.64830e-02 DIIS
   @DF-RHF iter  99:  -105.75609224148502    3.26850e-13   1.64830e-02 DIIS
   @DF-RHF iter 100:  -105.75609224148509   -7.10543e-14   1.64830e-02 DIIS

  ==> Post-Iterations <==

  Failed to converge.
Iterations did not converge.

**Comment by susilehtola** [comment]
Reduced @dspoel test case
```
molecule LiF {
1 1
Li 0.000000000 0.000000000 0.000000000
--
-1 1
F 16.000000000 0.000000000 0.000000000
    units angstrom
    no_reorient
}
set basis cc-pVDZ
set df_scf_guess false
set scf_type direct

energy('scf')
```
Ends up in 
```
   @RHF iter  99:   -93.26608062600357    7.76623e-11   9.86087e-02 DIIS
   @RHF iter 100:   -93.26608062574179    2.61778e-10   9.86087e-02 DIIS
```

If you use an augmented basis set, the calculation converges.

**Comment by susilehtola** [comment]
This is on master, so still not fixed in 1.3.

**Comment by dspoel** [comment]
Thanks for your quick reply, with 1.2.1 and an augmented basis set I still have problems in another system, see below. But do I understand correctly that master should work?

molecule ClCl {
        -1 1
        Cl  0.000000000  0.000000000  0.000000000
        --
        -1 1
        Cl  0.700000000  0.000000000  0.000000000

        units angstrom
        no_reorient
}
set globals {
        basis aug-cc-pVTZ
}
set_memory(32000000000)
energy('sapt2+3(ccd)dmp2')

**Comment by susilehtola** [comment]
Yeah, the calculations with augmented basis sets including the above converge fine in master.
PS. You should enclose the inputs with ``` on either side to make them show verbatim.

**Comment by JonathonMisiewicz** [comment]
> Simplified test case
> 
> ```
> molecule dimer {
>     0 1
>     Ne 0.0 0.0 0.0
>     --
>     0 1
>     Xe 0.0 0.0 3.0
> }
> 
> set {
>     basis def2-svp
>     print 2
> }
> 
> set guess core
> Eall = energy('scf')
> ```

I tried this with 1.6, including `ecpint`.

_With_ ADIIS on, we are able to find the correct minimum readily. _Without_ ADIIS on, we see oscillatory convergenceat -316 E_h, well above the -457 E_h.

```
molecule LiF {
1 1
Li 0.000000000 0.000000000 0.000000000
--
-1 1
F 16.000000000 0.000000000 0.000000000
}
set basis cc-pVDZ
set df_scf_guess false
set scf_type direct

energy('scf')
```

This fails, per Susi's earlier report, with 1.6 and ADIIS off. With ADIIS on, we observe frequent occupation flips, but also no convergence.

Tragically, I'm still unconvinced that the ECPs are in good shape.

**Comment by JonathonMisiewicz** [comment]
Closing the issue because of ADIIS.

The first example here converges with ADIIS and/or a better SCF guess.
The second example here converges with a suitable basis set (please use augmented functions for anions). With a slight (ADIIS-enabled) modification of the original input file:
```
molecule LiF {
symmetry c1
1 1
Li 0.000000000 0.000000000 0.000000000
--
-1 1
F 16.000000000 0.000000000 0.000000000
}
set basis cc-pVDZ
set stability_analysis follow
set reference uhf 
set max_attempts 5
set SCF_INITIAL_START_DIIS_TRANSITION 1e-2

energy('scf')
```

I converge to a solution with an instability eigenvalue of: -0.000001. Given the choice between using a physical basis set or trying to deal with _that_ instability, I'd rather use the physical basis set.
