### ISSUE TITLE
ECPs Break Basis Guess

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#1439]
The following input file gives absurd results using the current dev version of Psi:
```
memory 1000 mb

molecule {
-1 1
 I
}

basis {
   assign I def2-tzvppd
}

set basis_guess true

energy('scf')
```

The small basis computation ends with
```
    Final Occupation by Irrep:
             Ag   B1g   B2g   B3g    Au   B1u   B2u   B3u 
    DOCC [     9,    2,    2,    2,    0,    4,    4,    4 ] 

  @DF-RHF Final Energy: -6892.35157729932507
```

Here's how the large basis computation went:
```
   @DF-RHF iter   0:   590.08005432721836    5.90080e+02   2.80084e-01
    Occupation by irrep:
             Ag   B1g   B2g   B3g    Au   B1u   B2u   B3u 
    DOCC [     5,    2,    2,    2,    1,    5,    5,    5 ] 

   @DF-RHF iter   1:   -67.13552163426122   -6.57216e+02   3.44500e-01 
    Occupation by irrep:
             Ag   B1g   B2g   B3g    Au   B1u   B2u   B3u 
    DOCC [     7,    2,    2,    2,    0,    5,    4,    5 ] 

   @DF-RHF iter   2:    -5.42420113211885    6.17113e+01   6.71875e-01 DIIS
   @DF-RHF iter   3:  -208.00917694080209   -2.02585e+02   3.53265e-01 DIIS
    Occupation by irrep:
             Ag   B1g   B2g   B3g    Au   B1u   B2u   B3u 
    DOCC [     8,    2,    2,    3,    0,    4,    4,    4 ] 

   @DF-RHF iter   4:  -213.73836050769307   -5.72918e+00   3.05852e-01 DIIS
   @DF-RHF iter   5:  -229.29046486569237   -1.55521e+01   1.60752e-01 DIIS
   @DF-RHF iter   6:  -231.83352362698204   -2.54306e+00   8.54643e-02 DIIS
   @DF-RHF iter   7:  -233.14739556085581   -1.31387e+00   1.00459e-02 DIIS
   @DF-RHF iter   8:  -233.26115993293257   -1.13764e-01   6.01984e-03 DIIS
   @DF-RHF iter   9:  -233.30679760470645   -4.56377e-02   2.25206e-03 DIIS
   @DF-RHF iter  10:  -233.31593146369286   -9.13386e-03   6.80191e-04 DIIS
   @DF-RHF iter  11:  -233.31660737631540   -6.75913e-04   2.28951e-04 DIIS
   @DF-RHF iter  12:  -233.31678610778147   -1.78731e-04   1.58902e-04 DIIS
   @DF-RHF iter  13:  -233.31696020659965   -1.74099e-04   1.02174e-04 DIIS
   @DF-RHF iter  14:  -233.31707462571032   -1.14419e-04   1.37466e-05 DIIS
   @DF-RHF iter  15:  -233.31707485378129   -2.28071e-07   3.16438e-06 DIIS
   @DF-RHF iter  16:  -233.31707486465362   -1.08723e-08   5.35650e-07 DIIS
  Energy converged.
```

(Are ECP electrons supposed to be included in DOCC?)

The listed doubly occupied orbitals are
```
    Doubly Occupied:

       1Ag    -1.892135     1B1u    0.256341     1B3u    0.256341
       1B2u    0.256341     2B1u    2.685551     2B3u    2.685551
       2B2u    2.685551     2Ag     3.556568     1B3g    3.556568
       1B2g    3.561885     3Ag     3.561885     1B1g    3.561885
       4Ag     3.830228     5Ag     3.956522     2B2g    3.956522
       2B1g    3.956522     2B3g    3.967605     6Ag     3.967605
       3B1u    4.573133     3B3u    4.573133     3B2u    4.573133
       7Ag     4.839905     4B1u    5.327348     4B3u    5.327348
       4B2u    5.327348     8Ag     5.637776     3B3g    5.637776
```

(Surely ECP electrons shouldn't be included here?)

Switching out the ECP-containing basis for a manually defined Pople basis set resolved all strangeness. Needless to say, basis guess and ECP really don't play nicely. I'll leave it to the people working on ECPs to decide what the right fix is.

**Comment by susilehtola** [comment]
Maybe all that is necessary is to reset the occupations if ```basis_guess``` is used. It's done in ```guess read```, as well...

**Comment by susilehtola** [comment]
It does work both in the current master as well as after the ```reset_occ_ = True``` fix if you use ```basis_guess def2-svp```, which is what you would like to do in any case - orbital projections to/from different ECPs is not going to be easy.

**Comment by JonathonMisiewicz** [comment]
We _could_ just raise an error if a user tries a combination of guess basis and compute basis where one has ECPs and the other doesn't.

**Comment by susilehtola** [comment]
A warning message might be better.

Or, if the main basis has ECPs, then the same ECP could be used in the small basis calculation.

**Comment by susilehtola** [comment]
Well, #1456 has been merged, which included the fix to this issue.

**Comment by JonathonMisiewicz** [comment]
I reran the input file from the OP with a newly updated version of Psi. The large basis computation gives the same result as before. #1456 does not fix this issue.

**Comment by susilehtola** [comment]
Hmh, I think it worked in a previous try... huh

**Comment by dgasmith** [comment]
What is the status of this? Anything we can do quickly?

**Comment by susilehtola** [comment]
In addition, ```basis_guess true``` should be changed so that it does something similar to the automatic auxiliary basis set selection routine. E.g. use ```pcseg-0``` as guess basis for ```(aug-)pcseg-n``` series, ```def2-SVP``` (or a version thereof with some functions removed)  for ```def2``` series, etc. That way you can assure that the ECPs match.
