### ISSUE TITLE
nonsensical fitting basis

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#144]
When a fitting basis isn't available, defaults to ``def2-qzvpp-jkfit``. This sounds great, and is, until you notice a scf/cc-pv6z calc is using a quad-zeta auxiliary basis. Remedy this.

**Comment by loriab** [comment]
Maybe:

* Switch out Pople basis fitting bases to appropriate-zeta def2-*-ri/jkfit, rather than Dunning ri/jkfit, as former has fewer element holes.
* Create another layer of defaulting so that aug-cc-pvdz orbital uses aug-cc-pvdz-ri/jkfit when available (as at present), then def2-tzvp-ri/jkfit (not at present), then the ultimate default def2-qzvpp-ri/jkfit (as at present). This way don't get high AM cost on supposedly cheap orbital basis sets.
* Disqualify default for 5Z and 6Z basis sets. if aug-cc-pv5/6Z-ri/jkfit aren't defined for a certain element, we've nothing to put in their place.

**Comment by CDSherrill** [comment]
Sounds reasonable

**Comment by dgasmith** [comment]
This has been rolled into #43.
