### ISSUE TITLE
Segfaults in DFHelper during testsuite 

### ISSUE THREAD

**Issue by mbanck** [psi4/psi4#1457]
Those `Exit Status: infile ( -11 );` are segfaults (`SIGSEGV` is 11), I've pasted the backtrace here: http://paste.debian.net/1058664 The `output.dat` (`fsapt2` testcase) is here: http://paste.debian.net/1058665

Do I need to maybe setup some environment variables, e.g. for scratch space in order to run the tests?

_Originally posted by @mbanck in https://github.com/psi4/psi4/issue_comments#issuecomment-451527924_

**Comment by mbanck** [comment]
I checked all of them and the common theme seems to be `DFHelper Memory: [...]` in the last line out the `output.dat`.

**Comment by mbanck** [comment]
Hrm, maybe due to too small `MAX_AM_ERI` in libint?

**Comment by loriab** [comment]
`MAX_AM_ERI` is certainly the first thing to try. gau2grid was also at 1.1 (not 1.3) c. psi 1.2.1, but I don't recall any semver violations there.

**Comment by mbanck** [comment]
I cranked it up to 

```
-- Found Libint 6: /usr/lib/libint.a (found version 1.2.0)
```

but the segfaults remain.

**Comment by mbanck** [comment]
Stepping through, it seems it crashes in `DFHelper::transform()` when calling in `identify_order()`, in particular in this line:

```
1521	            op = (!(std::get<0>(transf_[*itr]).compare(str)) ? 1 : op);
```

segfault seems to happen in C++ standard lib at

```
/usr/include/c++/8/bits/stl_tree.h:1888
1888		if (!_M_impl._M_key_compare(_S_key(__x), __k))
```

This is C++ 8.2.0-13 (the -13 being Debian's revision). Will try to dig deeper.

**Comment by mbanck** [comment]
Current theory: e286fcebfbbf fixes this.

**Comment by dgasmith** [comment]
@mbanck If I read the comments correctly this should be closed? Please reopen if I misunderstood.
