### ISSUE TITLE
fcidump.py np.einsum errors on some architectures

### ISSUE THREAD

**Issue by mbanck** [psi4/psi4#1465]
On some architectures, the testsuite has errors like:

```
 52/140 Test #191: fcidump ..........................***Failed    0.47 sec
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/builddir/stage/usr/bin/psi4", line 269, in <module>
    exec(content)
  File "<string>", line 32, in <module>
  File "/<<PKGBUILDDIR>>/builddir/stage/usr/lib/s390x-linux-gnu/psi4/driver/p4util/fcidump.py", line 339, in compare_fcidumps
    ref_energies = _energies_from_fcidump(ref_intdump)
  File "/<<PKGBUILDDIR>>/builddir/stage/usr/lib/s390x-linux-gnu/psi4/driver/p4util/fcidump.py", line 363, in _energies_from_fcidump
    intdump['uhf'])
  File "/<<PKGBUILDDIR>>/builddir/stage/usr/lib/s390x-linux-gnu/psi4/driver/p4util/fcidump.py", line 379, in _scf_energy
    exchange = np.einsum('ijij->', ERI[np.ix_(occ_sl, occ_sl, occ_sl, occ_sl)])
  File "/usr/lib/python3/dist-packages/numpy/core/einsumfunc.py", line 1346, in einsum
    return c_einsum(*operands, **kwargs)

ValueError: dimensions in operand 0 for collapsing index 'þ' don't match (-168832168 != 5)
Exit Status: infile ( 1 ); autotest ( None ); sowreap ( None ); overall ( 1 )
```

These are the lines, it is failing during the `exchange`:

```
    coulomb = np.einsum('iijj->', ERI[np.ix_(occ_sl, occ_sl, occ_sl, occ_sl)])
    exchange = np.einsum('ijij->', ERI[np.ix_(occ_sl, occ_sl, occ_sl, occ_sl)])
```

Now when I duplicate the `coulomb` line in place of the `exchange` line, it runs fine. Also, if I dump out something between the two, e.g. `print(occ_sl)`, it runs fine, so there is probably some subtle issue in NumPy's `einsum`.

I was not able to produce a minimal test-case, mostly because my Python/NumPy-fu is not strong enough to figure out what `ERI[np.ix_(occ_sl, occ_sl, occ_sl, occ_sl)]` really is.

Any idea what it could be and whether there's a robust was (some barrier?) to get around it?

**Comment by mbanck** [comment]
Well, why would it work fine if I dump something out in the meantime? To be clear, this works:

```
    coulomb = np.einsum('iijj->', ERI[np.ix_(occ_sl, occ_sl, occ_sl, occ_sl)])
    print(occ_sl)
    exchange = np.einsum('ijij->', ERI[np.ix_(occ_sl, occ_sl, occ_sl, occ_sl)])
```

I dumped the ERI object and it is just numbers I think?

This is on s390x, so a somewhat obscure architecture (big endian).

**Comment by dgasmith** [comment]
I mean the `iijj->` and `ijij->` string are being parsed as unicode somehow due to this line here: `collapsing index 'þ'`. I would be curious if `einsum` works on `s390x` in general. You can try via:

```python
tensor = np.random.rand(10, 10, 10, 10)
np.einsum('iijj->', tensor)
```

**Comment by mbanck** [comment]
It does (note that the `coulomb np.einsum('iijj'` also works, it only crashes at the `exchange` expression):
```
>>> import numpy as np
>>> tensor = np.random.rand(10, 10, 10, 10)
>>> np.einsum('iijj->', tensor)
47.082188304843505
```

I'd like to try out `opt_einsum`, but I am not quite sure what to change in `fcidump.py` in order to switch to it?

**Comment by mbanck** [comment]
I checked older versions, and 1.15 binaries have the same issue. Debian stable/stretch is at 1.12.1 and there it works fine:

```
(stretch_s390x-dchroot)mbanck@zelenka:~$ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> tensor = np.random.rand(10, 10, 10, 10)
>>> np.einsum('iijj->', tensor)
42.006967955738595
>>> np.einsum('ijij->', tensor)
45.959642153948728
```

**Comment by dgasmith** [comment]
Well, that is very odd. If `iijj->` works, I would expect `ijij->`to work as well. So this is something in the einsum parsing tech or Python's view of string. Can you try `"ijij->".encode().decode("latin-1")`?

**Comment by mbanck** [comment]
```
>>> "ijij->".encode().decode("latin-1")
'ijij->'
>>> r"ijij->"
'ijij->'
>>> 
```

**Comment by mbanck** [comment]
Ok, so in the `ijij` case I see this difference between s390 and amd64:

amd64:

```
2114	        int label = (signed char)labels[idim];
(gdb) n
2116	        if (label < 0) {
(gdb) p label
$43 = -2
(gdb) p idim
$44 = 3
(gdb) p labels[idim]
$45 = -2 '\376'
(gdb) p labels
$46 = 0x7fffffffcd20 "ij\376\376"
```

s390x:

```
2114            int label = (signed char)labels[idim];
(gdb) n
2116            if (label < 0) {
(gdb) p label
$278 = -1
(gdb) p idim
$279 = 3
(gdb) p labels[idim]
$280 = 255 '\377'
(gdb) p labels                  
$281 = 0x3ffffffcdf8 "ij\376\377\375\377\061\340"
```

If I then go on on s390 by mangling the `label` variable, it exits fine.

```
(gdb) set variable label = -2
(gdb) c
Continuing.
47.048397425357216
[Inferior 1 (process 26977) exited normally]
```

So I guess the `int label = (signed char)labels[idim];` is to fault here.

**Comment by mbanck** [comment]
I would say the problem is that on s390x:

```
(gdb) p (char )0xFF
$322 = 255 '\377'
(gdb) p (char )0x80
$323 = 128 '\200'
(gdb) p (signed char )0x80
$324 = -128 '\200'
```

while on amd64:

```
(gdb) p (char )0xFF
$102 = -1 '\377'
(gdb) p (char )0x80
$103 = -128 '\200'
(gdb) p (signed char )0x80
$104 = -128 '\200'
```

**Comment by mbanck** [comment]
Seems to be a numpy error.

**Comment by dgasmith** [comment]
Yea, small world that it is an einsum bug.

**Comment by dgasmith** [comment]
Fixed by NumPy upstream.
