### ISSUE TITLE
Decontracted Basis Set Not Recognized When Seeking Decontracted Basis Sets for Relativistic

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#1471]
Issue carried over from [forums](http://forum.psicode.org/t/cant-run-relativistic-calcs-with-decontracted-basis-sets/1177).

If the input basis set is decontracted, Psi will fail to recognize the basis set when trying to use a decontracted version of the input basis for relativistic computations. The following input file will fail due to the commented out line.

```
molecule {
0 1
CL        0.000000000000  0.000000000000  -0.035925275852
H         0.000000000000  0.000000000000   1.246511684916
symmetry c1
}

basis {


set {
  basis         cc-pvdz-decon
  #basis_relativistic cc-pvdz-decon
  df_basis_scf  cc-pvdz-jkfit
  reference     rhf 
  e_convergence 1.e-10
  relativistic x2c 
}

energy('scf')
```

The bug itself is probably an easy fix once you know what information is not being handled/passed correctly in the basis set machinery. The hard part is knowing that machinery well enough to figure out where.

Reporter also noted that this is a blind spot in the test suite, so additional tests here are welcome.

**Comment by susilehtola** [comment]
This is a duplicate of #662

**Comment by JonathonMisiewicz** [comment]
Closed per above.
