### ISSUE TITLE
Feature natural orbitals to molden file still needs some work

### ISSUE THREAD

**Issue by tovrstra** [psi4/psi4#1485]
This is a follow-up on #504. It's been a while that I looked into this. I managed to write post-SCF natural orbitals to a molden file, but there is still a problem with documentation (http://www.psicode.org/psi4manual/1.2/molden.html):

This is a fully working example:

```
molecule {
0 1
O          1.01646        0.05097        0.09714
H          1.98435        0.06069        0.05173
H          0.73761        0.24513       -0.81034
}
set basis cc-pVTZ

E, wfn = properties('ccsd', properties=['dipole'], return_wfn=True)
nmopi = wfn.nmopi()
Da_so = wfn.Da()
Ca_inv = core.Matrix("CA inv", nmopi, nmopi)
Ca_inv.copy(wfn.Ca())
Ca_inv.general_invert()
Da_mo = Matrix.triplet(Ca_inv, Da_so, Ca_inv, False, False, True)
# Da_mo = Matrix.triplet(wfn.Ca(), Da_so, wfn.Ca(), True, False, False)  # line from documentation
molden(wfn, 'ccsd_no.molden', density_a=Da_mo)
```

Loading this into Molden gives normals results:

```

                         COORDINATES
                    used for orbitals/density

                    X         Y         Z

             1 O   -0.103043    0.072862    0.000000
             2 H   -0.015287   -1.756185    0.000000
             3 H    1.650657    0.599812    0.000000
 
                        Mulliken Charges
                        ================
 
               O  -0.4661
               H   0.2332
               H   0.2332
```

When following the documentation, I got:

```
                         COORDINATES
                    used for orbitals/density

                    X         Y         Z

             1 O   -0.103043    0.072862    0.000000
             2 H   -0.015287   -1.756185    0.000000
             3 H    1.650657    0.599812    0.000000
 
                        Mulliken Charges
                        ================
 
               O -94.4305
               H -12.0740
               H -12.0736
 
Sum of Mulliken Charges: ********
```

(FYI: my actual intention is not to visualize in Molden, but this is just an easy check.)

Besides the documentation, there are some additional minor issues. I'll make a list here:

- [ ] Fix docs.
- [ ] When running the input for a second time, the new output is appended to the existing molden file, which is never useful.
- [ ] The current approach is not the most efficient, nor convenient: the user first has to compute a pseudo-inverse and then in the `molden` function a matrix is diagonalized. This can be done in one step by performing a generalized eigenvalue decomposition. This could happen inside the `molden` function, but then the API would need to change, because that would require the density matrix in the AO basis as input.

**Comment by susilehtola** [comment]
```
Ca_inv = core.Matrix("CA inv", nmopi, nmopi)
Ca_inv.copy(wfn.Ca())
Ca_inv.general_invert()
```
... why would you want to invert an orbital coefficient matrix? It's not even expressed in an orthonormal basis set!

What you should do is get the density matrix in the MO basis and diagonalize that to get the NOs.

If the Python code only gives you the AO density matrix ```D_AO```, then it's easy to translate it to the MO basis by ```D_MO = C^T D_AO C```. Then you diagonalize ```D_MO``` to get eigenvectors ```v``` and eigenvalues ```e```, and rotate ```C``` as ```C=Cv``` to get the NOs in the AO space.

**Comment by tovrstra** [comment]
Sorry, I don't agree. I'll explain why you need the inverse. The following very similar formula is correct (but different):

`D_AO = C D_MO C^T`

In case of an SCF density matrix `D_MO` is diagonal with occupation numbers on the diagonal.
`C` is not unitary, so you need to perform a matrix inverse to get `D_MO` out of `D_AO`.

---

As I said, I don't like doing the inverse and there are better ways to deal with this, basically solve the following generalized eigenvalue problem:

`S D_AO S C_NO = S C_NO N_NO`

where `S` is the overlap matrix, `C_NO` are the natural orbital coefficients and `N_NO` are the natural occupation numbers. This way, you get the natural orbitals in one step.

**Comment by susilehtola** [comment]
You don't need an inverse. I'll try to explain.

```C^T S C = 1``` is the resolution of the identity in the MO basis. This means that 

```D_MO = (C^T S C) D_MO (C^T S C) = C^T S (C D_MO C^T) S C = C^T S D_AO S C = (S C)^T D_AO S C```

That is, ```D_AO = C D_MO C^T``` - like you said above - and ```D_MO = (S C)^T D_AO S C```. I appear to just have flipped AO/MO above :tongue:

**Comment by tovrstra** [comment]
Good, I agree that is the best way to fix the documentation. I just put this in the example as a test:

```
molecule {
0 1
O          1.01646        0.05097        0.09714
H          1.98435        0.06069        0.05173
H          0.73761        0.24513       -0.81034
}

set basis cc-pVTZ

E, wfn = properties('ccsd', properties=['dipole'], return_wfn=True)

nmopi = wfn.nmopi()
Da_so = wfn.Da()
SCa = core.Matrix("Overlap times Ca", nmopi, nmopi)
SCa.gemm(False, False, 1.0, wfn.S(), wfn.Ca(), 0.0)
Da_mo = Matrix.triplet(SCa, Da_so, SCa, True, False, False)
molden(wfn, 'ccsd_no.molden', density_a=Da_mo)
```

and the corresponding output from Molden:

```
                         COORDINATES
                    used for orbitals/density

                    X         Y         Z

             1 O   -0.103043    0.072862    0.000000
             2 H   -0.015287   -1.756185    0.000000
             3 H    1.650657    0.599812    0.000000
 
                        Mulliken Charges
                        ================
 
               O  -0.4661
               H   0.2332
               H   0.2332
 
Sum of Mulliken Charges:   0.0003
```

**Comment by susilehtola** [comment]
That's still a bit disappointing; the sum of the Mulliken should be ```O(1e-15)```. But, I guess that's because Molden uses stupid fixed precision.

For anything beyond visualization purposes, one should use the formatted checkpoint format which yields quasi-native precision.

**Comment by tovrstra** [comment]
I agree it is not a great format, but the poor sum may be something different than a rounding issue in the file format. The basis set and the orbitals are written with quite a few digits:

````
[GTO]
  1 0
 s    8  1.00
    15330.0000000000         0.0005080000
     2299.0000000000         0.0039290000
      522.4000000000         0.0202430000
      147.3000000000         0.0791810000
       47.5500000000         0.2306870000
       16.7600000000         0.4331180000
        6.2070000000         0.3502600000
        0.6882000000        -0.0081540000
 s    8  1.00
    15330.0000000000        -0.0001150000
     2299.0000000000        -0.0008950000
      522.4000000000        -0.0046360000

...

[MO]
 Sym= A'
 Ene=         0.0000019291
 Spin= Alpha
 Occup=  0.0000
  1      -0.000002858808
  2      -0.000004884938
  3       0.000005659962
  4      -0.000034586276
  5       0.034482444539
  6       0.048763669588
  7       0.000000000000
  8      -1.012771593783
  9      -1.432261920310
 10       0.000000000000
 11      -1.686054934207
 12      -2.384426538125
 13       0.000000000000
 14       0.000000095953
 15       0.000000000000
 16       0.000000000000
 17      -0.009074401514
 18      -0.003208359950
 19       0.000008282989
 20       0.000000000000
 21       0.000000000000
 22      -0.900874210990
 23      -0.318520214440
 24       0.000000000000

...

**Comment by tovrstra** [comment]
Oh, wait, the rounding of the occupation numbers is bad. That is probably the cause.

**Comment by tovrstra** [comment]
Just checked, the low precision of the occupation numbers is indeed the problem. This precision is not specified in the Molden format, so it can easily be increased to make the molden output a little more useful. I'll open another ticket for this.

(I tried using the FCHK writer in PSI4, but its output was too different from what Gaussian produced, so it did not look into it any further. If you want, I can open a ticket to describe these problems in more detail.)

**Comment by susilehtola** [comment]
@tovrstra you should look at #1475 which addresses those differences.

**Comment by tovrstra** [comment]
Good, I'll take a look.

**Comment by susilehtola** [comment]
That's still only if you're just looking at the density itself.

If you want properties, then a O(1e-12) error in the NO coefficients can still yield noticable errors in matrix elements, since those get weighted by exponents. E.g. tight core exponents will have huge kinetic energy elements T_{ij}, but very small expansion coefficients. Still, the product of the two may well be significant.

**Comment by tovrstra** [comment]
Good point. I'll check how liberal Molden is regarding formatting of floats in the format. If everything can be written in scientific notation, then full precision is an option.
