### ISSUE TITLE
snippets in manual that don't run

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#149]
- [x] [1st dcft input](https://github.com/psi4/psi4/blob/master/doc/sphinxman/source/dcft.rst)
- [x] [2nd dcft input](https://github.com/psi4/psi4/blob/master/doc/sphinxman/source/dcft.rst)

@ssh2 the two above work if you use `set r_convergence 6` but the default is 10. should this be loosened?
- [ ] [1st cfour input](https://github.com/psi4/psi4/blob/master/doc/sphinxman/source/cfour.rst)
- [ ] [2nd cfour input](https://github.com/psi4/psi4/blob/master/doc/sphinxman/source/cfour.rst)
- [ ] [3rd cfour input](https://github.com/psi4/psi4/blob/master/doc/sphinxman/source/cfour.rst)
- [ ] [8th cfour input](https://github.com/psi4/psi4/blob/master/doc/sphinxman/source/cfour.rst)
- [x] [3rd dft input](https://github.com/psi4/psi4/blob/master/doc/sphinxman/source/dft.rst)
- [x] [dkh input](https://github.com/psi4/psi4/blob/master/doc/sphinxman/source/dkh.rst)
- [x] [1st energy input](https://github.com/psi4/psi4/blob/master/doc/sphinxman/source/energy.rst)
- [ ] [2nd energy input](https://github.com/psi4/psi4/blob/master/doc/sphinxman/source/energy.rst)
- [x] [2nd libefp input](https://github.com/psi4/psi4/blob/master/doc/sphinxman/source/libefp.rst)

**Comment by ssh2** [comment]
Thanks, Lori! Indeed, it didn't run because I changed the default convergence scheme. I changed the basis set to cc-pvdz in the manual, this runs on my machine.

**Comment by loriab** [comment]
Thanks, @ssh2. @tmpchem hunted down all the malfunctioning manual entries this week. Two bullets fixed by https://github.com/psi4/psi4/commit/e1bae5b028c15aef889480978e4f70d247f8821e

**Comment by fevangelista** [comment]
Lori, is there a way to link examples in the manual to test case input files?

Francesco

On Jul 17, 2015, at 8:50 PM, Lori A. Burns <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks, @ssh2<https://github.com/ssh2>. @tmpchem<https://github.com/tmpchem> hunted down all the malfunctioning manual entries this week. Two bullets fixed by psi4/psi4@e1bae5b<https://github.com/psi4/psi4/commit/e1bae5b028c15aef889480978e4f70d247f8821e>

-
Reply to this email directly or view it on GitHub<https://github.com/psi4/psi4public/issues/149#issuecomment-122461767>.

________________________________

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).

**Comment by loriab** [comment]
Yes, if you look at the source of http://psicode.org/psi4manual/master/_sources/tutorial.txt , there's statements like ``.. literalinclude:: /../../../../samples/tu6-cp-ne2/input.dat`` that directly include sample files in the documentation. It can also be trimmed like so:

```
.. literalinclude:: /../../../../lib/python/p4const/physconst.py
   :lines: 25-
```

**Comment by fevangelista** [comment]
Great and thanks!

Francesco

On Jul 17, 2015, at 11:04 PM, Lori A. Burns <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, if you look at the source of http://psicode.org/psi4manual/master/_sources/tutorial.txt , there's statements like .. literalinclude:: /../../../../samples/tu6-cp-ne2/input.dat that directly include sample files in the documentation. It can also be trimmed like so:

.. literalinclude:: /../../../../lib/python/p4const/physconst.py
   :lines: 25-


-
Reply to this email directly or view it on GitHub<https://github.com/psi4/psi4public/issues/149#issuecomment-122477178>.

________________________________

This e-mail message (including any attachments) is for the sole use of
the intended recipient(s) and may contain confidential and privileged
information. If the reader of this message is not the intended
recipient, you are hereby notified that any dissemination, distribution
or copying of this message (including any attachments) is strictly
prohibited.

If you have received this message in error, please contact
the sender by reply e-mail message and destroy all copies of the
original message (including attachments).

**Comment by loriab** [comment]
@CDSherrill , the halfway-corrected version of bullet 2nd energy above is

```
molecule ne {\nNe\n}
set basis cc-pVDZ
set transqt2 delete_tei false
energy('cisd')
energy('fci', bypass_scf='True')
```

where the integrals from the CISD aren't available for the FCI calc. I think we had seen this earlier with the file numbers used by detci aren't registered in psifiles.h . This input is in a docstring in ``lib/python/energy.py``, not ``tests/`` so we could just drop it from there for now and add an issue if it's an involved fix.

**Comment by Hassenky** [comment]
Are there other ways to deal with Douglas-Kroll-Hess (DKH) Hamiltonian? When running dk input:

molecule {
Mg
}
set basis aug-cc-pvdz-dk
set relativistic dkh
energy('scf')

---------------------------
I got this error output:
Traceback (most recent call last):
  File "<string>", line 20, in <module>
RuntimeError: DKH is not a valid choice

**Comment by jturney** [comment]
Did you compile the code with a Fortran compiler? One is required for using DKH.

**Comment by Hassenky** [comment]
I installed psi4 from miniconda.

**Comment by loriab** [comment]
True, due to a recently noticed oddity of the cmake build system, I can't build dkh w/o also building pcmsolver and that's not quite ready for public use. If you'd like dkh, I can see about including it. 

Lori

**Comment by Hassenky** [comment]
What will happen if I compile PSI4 from the source code? Can I use dkh?

**Comment by loriab** [comment]
If you supply a fortran compiler and pass -D enable_fortran (caps) that will probably give you workable dkh. Otherwise, wait a couple days until I'm back in town, and I'll add it to the miniconda distro.

**Comment by Hassenky** [comment]
Thank you. I am waiting for the new fixed version from Miniconda.

**Comment by kannon92** [comment]
If DKH is not working, the Evangelista group recently pushed some new code for relativistic one electron operators.  The results are almost exactly like DKH and both modify the one electron integrals .  

Here is a sample using DKH.  

https://github.com/psi4/psi4public/blob/master/samples/x2c1/input.dat

**Comment by Hassenky** [comment]
Thanks kannon92 . I'm actually employing x2c. However, all of my multi-reference (CASPT2, NEVPT2) and DFT results were done with DKH correction. Therefore I would like to use DKH correction for CCSD(T) calculations performed by PSI4 (easy to get scf convergence in comparison to others). Of course the report will be ....

**Comment by kannon92** [comment]
Oh okay.  Well good luck then.

**Comment by loriab** [comment]
dkh now in conda 0.2.291

**Comment by Hassenky** [comment]
Thanks Loriab

**Comment by loriab** [comment]
Plan for 19 Apr task:
* wait until #349 has finished its first task
* ignore the cfour snippets
* [ ] many examples have changed since wavefunction pass, esp in driver docstrings, so re-collect snippets.

**Comment by loriab** [comment]
I did a pass on manual snippets in September 2016. This is still a task, but it should be started afresh.
