### ISSUE TITLE
finalize CheMPS2

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#150]
Lingering issues for finalizing CheMPS2:

- [ ] Make sure can detect Debian installation of CheMPS2 in "list of files" https://packages.debian.org/sid/libchemps2-dev 

- [ ] make up new conda package

- [ ] add conda package to metapackage

- [ ] add chemps2.rst to interfaces in docs

- [ ] add chemps2 to binary

- [ ] review keywords

- [ ] add acceptance for Intel redistributable for ``chemps2.so``

**Comment by SebWouters** [comment]
Regarding the debian detection: since CMake decides the folder location,
CMake should also detect it:

The headers are always in /usr/include/chemps2/, but since in
https://github.com/psi4/psi4public/blob/f81842d2e9c255490d450681bc6bdeca551b81e1/src/bin/dmrg/dmrgscf.cc
they are included as "chemps2/DMRG.h" etc, it will always need

    /usr/include

I suppose CMake will always look there, but it cannot hurt to append this
folder again :-).

The library is in the folder

    /usr/${CMAKE_INSTALL_LIBDIR}

where the latter part is automatically set by calling

    include(GNUInstallDirs)

in the CMakeLists.txt. Check
https://github.com/SebWouters/CheMPS2/blob/master/CMakeLists.txt#L10 and
https://github.com/SebWouters/CheMPS2/blob/master/CheMPS2/CMakeLists.txt#L21
for an example.

Best wishes,
Sebastian

2015-07-19 16:23 GMT-04:00 Lori A. Burns <notifications@github.com>:

> Lingering issues for finalizing CheMPS2:
>
>    -
>
>    Make sure can detect Debian installation of CheMPS2 in "list of files"
>    https://packages.debian.org/sid/libchemps2-dev
>    -
>
>    make up new conda package
>    -
>
>    add conda package to metapackage
>    -
>
>    add chemps2.rst to interfaces in docs
>    -
>
>    add chemps2 to binary
>    -
>
>    review keywords
>    -
>
>    add acceptance for Intel redistributable for chemps2.so
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psi4/psi4public/issues/150>.
>



-- 
****************************************************

  dr. ir. Sebastian Wouters
  Fellow of the Belgian American Educational Foundation
  Princeton University
  (address) Department of Chemistry
            Frick Laboratory 351
            Princeton, NJ 08544, USA
  (e-mail)  sebastianwouters@gmail.com

****************************************************

**Comment by loriab** [comment]
Good point! I made commit https://github.com/psi4/psi4public/commit/7e4889b924e67be11c5f7b5d42c85673a90c5c17 . If CMake pastes together a `PATHS` and `PATH_SUFFIX` and `NAMES`, it should get the Debian locations. If you should happen to try it out, let me know.

**Comment by SebWouters** [comment]
I can try it out on ubuntu. A good test will also to run it actually on
debian/sid. Perhaps we can ask Michael?

2015-07-20 17:37 GMT-04:00 Lori A. Burns <notifications@github.com>:

> Good point! I made commit 7e4889b
> <https://github.com/psi4/psi4public/commit/7e4889b924e67be11c5f7b5d42c85673a90c5c17>
> . If CMake pastes together a PATHS and PATH_SUFFIX and NAMES, it should
> get the Debian locations. If you should happen to try it out, let me know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psi4/psi4public/issues/150#issuecomment-123051328>.
>



-- 
****************************************************

  dr. ir. Sebastian Wouters
  Fellow of the Belgian American Educational Foundation
  Princeton University
  (address) Department of Chemistry
            Frick Laboratory 351
            Princeton, NJ 08544, USA
  (e-mail)  sebastianwouters@gmail.com

****************************************************

**Comment by mbanck** [comment]
I can try to test PR #388 on top of 1.0rc on Debian this weekend along with the newly uploaded v1.7

**Comment by loriab** [comment]
Only a year after the ticket, and I've finally reviewed the keywords. @SebWouters, @dgasmith, @kannon92, please find below an options mapping between the two versions of chemps2 embedded in psi4, the chemps2 plugin for psi4, and the chemps2 executable. Column [E] is what I would have named the options had this been an intrinsic psi4 module.

My current philosophy wrt options of add-on modules in psi4 is to leave them exactly as they are in the add-on program (so that users of e.g., CheMPS2 in psi4 and pyscf control CheMPS2 with exactly the same set of options) then let a layer above the psi4 driver handle mappings of identical-intent keywords into the psi4-consistent set (so that users of psi4 can `set detci diis true` and `set dmrg diis false`).

So, I propose that we go entirely with [D] if that's the official CheMPS2 options set or entirely with [E] as those are the psi4-like versions. I don't see much point in maintaining _three_ options sets. Thoughts?

```text
Various of the dmrg options map nicely in meaning onto psi4's
e/d/r_convergence options. But in dmrg, e/r_convergence must be
arrays of floats, not floats, so they need the dmrg_ prefix for
differentiation. So, d_convergence may as well match with dmrg_.

-------------           -------------           ---------------         -----------             --------------
[A]                     [B]                     [C]                     [D]                     [E]
psi4 dmrg 1.5           psi4 dmrg 1.7           chemps2 plugins         chemps2 exe             most psi4-like
-------------           -------------           ---------------         -----------             --------------
-->                     GLOBAL frozen_docc      frozen_docc             nocc                    frozen_docc
-->                     GLOBAL active           active                  nact                    active
dmrg_wfn_multp          wfn_multp               wfn_multp               multiplicity            wfn_multp
dmrg_wfn_irrep          wfn_irrep               wfn_irrep               irrep/group/symmetry    wfn_irrep
-->                     dmrg_states             dmrg_states             sweep_states            dmrg_states             ArrayType
-->                     dmrg_e_convergence      dmrg_e_convergence      sweep_energy_conv       dmrg_e_convergence      ArrayType
d_convergence           dmrg_d_convergence      d_convergence           scf_grad_thr?           dmrg_d_convergence
-->                     dmrg_maxsweeps          dmrg_maxsweeps          sweep_max_sweeps        dmrg_max_sweeps         ArrayType
-->                     dmrg_noiseprefactors    dmrg_noiseprefactors    sweep_noise_prefac      dmrg_noise_magnitude    ArrayType
(none)                  dmrg_dvdson_rtol        dmrg_dvdson_rtol        sweep_dvdson_rtol       dmrg_r_convergence      ArrayType
-->                     dmrg_print_corr         dmrg_print_corr         print_corr              dmrg_corr_print
-->                     dmrg_chkpt              dmrg_chkpt                                      dmrg_mps_write
-->                     dmrg_store_unit         dmrg_store_unit                                 dmrg_unitary_write
-->                     dmrg_do_diis            dmrg_do_diis                                    dmrg_diis
-->                     dmrg_diis_branch        dmrg_diis_branch        scf_diis_thr            dmrg_diis_start_convergence
-->                     dmrg_store_diis         dmrg_store_diis                                 dmrg_diis_write
dmrg_maxiter            dmrg_max_iter           dmrg_max_iter           scf_max_iter            dmrg_maxiter
-->                     dmrg_which_root         dmrg_which_root         excitation (offset-1)   dmrg_follow_root
dmrg_avg_states         dmrg_state_avg          dmrg_state_avg          scf_state_avg           dmrg_avg_states
-->                     dmrg_active_space       dmrg_active_space       scf_active_space        dmrg_scf_orbs
-->                     dmrg_loc_random         dmrg_loc_random                                 dmrg_local_init
(none)                  dmrg_caspt2             dmrg_caspt2             caspt2_calc             dmrg_caspt2
(none)                  dmrg_caspt2_orb         dmrg_caspt2_orb         caspt2_orbs             dmrg_caspt2_orbs
(none)                  dmrg_ipea               dmrg_ipea               caspt2_ipea             dmrg_caspt2_ipea
(none)                  dmrg_imag_shift         dmrg_imag_shift         caspt2_imag             dmrg_imag_level_shift
(none)                  dmrg_molden             dmrg_molden                                     dmrg_molden_write
(none)                  dmrg_density_ao         dmrg_density_ao                                 dmrg_opdm_ao_print
                                                                        
                                                dumpfilename (fcidump)  fcidump
                                                                        nelectrons
                                                                        nvir
                                                                        caspt2_checkpt
                                                                        caspt2_cumul
                                                                        tmp_folder
```

**Comment by kannon92** [comment]
I have no problem with this, but there should be more distinction in the nocc setting.  For example, frozen_docc in CHEMPS2 means that the orbitals are optimized in the CASSCF procedure and are correlated in CASPT2.  This corresponds to restricted_docc through psi4 lingo.  frozen_docc (in psi4) typically means that the orbitals are "frozen" and are taken to be RHF orbitals.  

In all, I would say that CHEMPS2 should use nocc -> restricted_docc rather than frozen_core.

**Comment by loriab** [comment]
I was wondering about that. If `frozen_docc` _and_ `restricted_docc` were defined in psi4, do you know if CheMPS2 needs info on the latter, too, for accounting purposes?

**Comment by SebWouters** [comment]
Hi everyone,

The Hamiltonian that is given to chemps2 should not know about the truly
frozen DOCC's. Since the chemps2 stand-alone is based on dumped integrals,
the frozen DOCC integrals are always taken up in the constant and
one-electron integrals, so that those orbitals don't exist for chemps2.

Best wishes,
Seb

2016-06-06 8:41 GMT+02:00 Lori A. Burns <notifications@github.com>:

> I was wondering about that. If frozen_docc *and* restricted_docc were
> defined in psi4, do you know if CheMPS2 needs info on the latter, too, for
> accounting purposes?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/psi4/psi4/issues/150#issuecomment-223879708>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAkjp3Y47dFIvgG9m6YX4F9-VUDtTORRks5qI8EogaJpZM4FblU->
> .
>



-- 
****************************************************

  dr. ir. Sebastian Wouters
  Postdoctoral Fellow of the Research Foundation Flanders (FWO)
  Ghent University
  (address) Center for Molecular Modeling
            Technologiepark 903
            9052 Zwijnaarde (Belgium)
  (e-mail)  sebastianwouters@gmail.com

****************************************************

**Comment by loriab** [comment]
Switch from B/C --> F imminent
```
-------------           -------------           ---------------         -----------             --------------			-----------------
[A]                     [B]                     [C]                     [D]                     [E]			       	    [F]
Apr2015–Apr2016         May–Jun2016                                                                                     late Jun 2016
psi4 dmrg 1.5           psi4 dmrg 1.7           chemps2 plugins         chemps2 exe             most psi4-like			psi4 1.0 dmrg 1.7
-------------           -------------           ---------------         -----------             --------------			-----------------
-->                     GLOBAL frozen_docc      frozen_docc             nocc                    restricted_docc (edit)  GLOBAL restricted_docc
-->                     GLOBAL active           active                  nact                    active		            GLOBAL active (n/c)
dmrg_wfn_multp          wfn_multp               wfn_multp               multiplicity            wfn_multp			    dmrg_multiplicity
dmrg_wfn_irrep          wfn_irrep               wfn_irrep               irrep (edit)		    wfn_irrep		 	    dmrg_irrep
-->                     dmrg_states             dmrg_states             sweep_states            dmrg_states []	        dmrg_sweep_states
-->                     dmrg_e_convergence      dmrg_e_convergence      sweep_energy_conv       dmrg_e_convergence []   dmrg_sweep_energy_conv
d_convergence           dmrg_d_convergence      d_convergence           scf_grad_thr?           dmrg_d_convergence		dmrg_scf_grad_thr
-->                     dmrg_maxsweeps          dmrg_maxsweeps          sweep_max_sweeps        dmrg_max_sweeps []  	dmrg_sweep_max_sweeps
-->                     dmrg_noiseprefactors    dmrg_noiseprefactors    sweep_noise_prefac      dmrg_noise_magnitude [] dmrg_sweep_noise_prefac
(none)                  dmrg_dvdson_rtol        dmrg_dvdson_rtol        sweep_dvdson_rtol       dmrg_r_convergence []   dmrg_sweep_dvdson_rtol
-->                     dmrg_print_corr         dmrg_print_corr         print_corr              dmrg_corr_print			dmrg_print_corr (n/c)
-->                     dmrg_chkpt              dmrg_chkpt                                      dmrg_mps_write			dmrg_mps_write
-->                     dmrg_store_unit         dmrg_store_unit                                 dmrg_unitary_write		dmrg_unitary_write
-->                     dmrg_do_diis            dmrg_do_diis                                    dmrg_diis		    	dmrg_diis
-->                     dmrg_diis_branch        dmrg_diis_branch        scf_diis_thr            dmrg_diis_start_convergence	dmrg_scf_diis_thr
-->                     dmrg_store_diis         dmrg_store_diis                                 dmrg_diis_write			dmrg_diis_write
dmrg_maxiter            dmrg_max_iter           dmrg_max_iter           scf_max_iter            dmrg_maxiter			dmrg_scf_max_iter
-->                     dmrg_which_root         dmrg_which_root         excitation (offset-1)   dmrg_follow_root		dmrg_excitation
dmrg_avg_states         dmrg_state_avg          dmrg_state_avg          scf_state_avg           dmrg_avg_states			dmrg_scf_state_avg
-->                     dmrg_active_space       dmrg_active_space       scf_active_space        dmrg_scf_orbs			dmrg_scf_active_space
-->                     dmrg_loc_random         dmrg_loc_random                                 dmrg_local_init			dmrg_local_init
(none)                  dmrg_caspt2             dmrg_caspt2             caspt2_calc             dmrg_caspt2			    dmrg_caspt2_calc
(none)                  dmrg_caspt2_orb         dmrg_caspt2_orb         caspt2_orbs             dmrg_caspt2_orbs		dmrg_caspt2_orbs
(none)                  dmrg_ipea               dmrg_ipea               caspt2_ipea             dmrg_caspt2_ipea		dmrg_caspt2_ipea
(none)                  dmrg_imag_shift         dmrg_imag_shift         caspt2_imag             dmrg_imag_level_shift   dmrg_caspt2_imag
(none)                  dmrg_molden             dmrg_molden                                     dmrg_molden_write		dmrg_molden_write
(none)                  dmrg_density_ao         dmrg_density_ao                                 dmrg_opdm_ao_print		dmrg_opdm_ao_print

                                                dumpfilename (fcidump)  fcidump
                                                                        nelectrons
                                                                        nvir
                                                                        caspt2_checkpt
                                                                        caspt2_cumul
                                                                        tmp_folder
									group (edit)
```

**Comment by loriab** [comment]
@susilehtola, @Hassenky, @mbanck, @kannon92, @lucamontana, @SebWouters: You've been identified from issues posted as the likely users of Psi4+CheMPS2. FYI, all your keywords are about to change according to the table above. See checkins referencing this issue for examples switching over your input files.
