### ISSUE TITLE
Problems with FCHK file for some systems

### ISSUE THREAD

**Issue by ajmisquitta** [psi4/psi4#1501]
Hi Psi4 team,

I've seen some strange problems with the FCHK file in recent versions of Psi4. This includes 1.2 (release) and v1.3a1-405-gdcb0159 from github.
I am using the following commands to write out the FCHK file: 

> energy, wfn = energy('PBE0', return_wfn=True)
> 
> fchk_writer = psi4.FCHKWriter(wfn)
> fchk_writer.write('TNB_n2_A.fchk')

This works correctly for small systems like H2O: all expected fields in the FCHK file are present. But for larger systems like TNB (file enclosed below), the following are missing:
1) Alpha MO coefficients (Beta is present)
2) No orbital energies are present.

There may be more fields missing, but these are the ones I know of. 

What is odd is that the problem is not apparently systematic: the FCHK file is correct for the RDX molecule (all fields are present), but not TNB. 

I need both the MO coefficients and MO energies for subsequent SAPT(DFT) calculations in CamCASP. We never had problems with Psi4 1.1, but need the AC in 1.2/3. Unfortunately this problem arises. 

I hope this can be fixed and the structure/fields in the FCHK file made consistent with the specs. 
All the best,
Alston

**Input file:**

> memory 61440 MB
> 
> basis {
>   assign aug-cc-pvdz
> }
> 
> molecule TNB_1 {
>   no_reorient
>   no_com
>   units bohr
>    0  1
>    O1              1.09555107       3.76703629      -7.83852576
>    O2              1.12573623       6.36725616      -4.70326928
>    O3             -2.95373205       4.13977831       3.05907653
>    O4             -4.81462989       0.53449898       3.42022641
>    O5             -3.04576492      -4.23365310      -7.04056005
>    O6             -4.88147857      -5.23919973      -3.54614660
>    N1              0.56718784       4.39077285      -5.70465171
>    N2             -3.61888234       2.10279732       2.26585157
>    N3             -3.68554450      -3.82553238      -4.88515975
>    C1             -0.89474878       2.57110902      -4.18157565
>    C2             -1.53597193       3.21430712      -1.73399499
>    C3             -2.90523393       1.47230460      -0.35362235
>    C4             -3.63263104      -0.83708361      -1.32968698
>    C5             -2.93743373      -1.37538831      -3.78771254
>    C6             -1.56886658       0.29097245      -5.25919020
>    H1             -0.98802906       5.00949031      -0.93088016
>    H2             -4.70324490      -2.17020139      -0.21423238
>    H3             -1.04610204      -0.17104401      -7.17780858
> }
> set {
>   s_tolerance    1.0E-04
>   ints_tolerance 1.0E-10
>   dft_grac_shift        0.053900
> }
> 
> energy, wfn = energy('PBE0', return_wfn=True)
> 
> fchk_writer = psi4.FCHKWriter(wfn)
> fchk_writer.write('TNB_minimal.fchk')

**Comment by ajmisquitta** [comment]
Some more information:
As I said above, for H2O the orbital energies and coeffcients are printed out in the FCHK file, but the field headers are not standard. They are:

- orbital energies 
- MO coefficients

This is not the case for Psi4 1.1 where these headers are
- Alpha Orbital Energies
- Alpha MO coefficients

Why was this change made? 

Input file below:

> memory 61440 MB
> 
> basis {
>   assign aug-cc-pvdz
> }
> 
> molecule H2O_1 {
>   no_reorient
>   no_com
>   units bohr
>    0  1
>    O1   0.0                0.0          0.1246319249
>    H1  -1.4536519623       0.0         -0.9970553993
>    H2   1.4536519623       0.0         -0.9970553993
> }
> set {
>   s_tolerance    1.0E-08
>   ints_tolerance 1.0E-10
> }
> 
> energy, wfn = energy('PBE0', return_wfn=True)
> 
> fchk_writer = psi4.FCHKWriter(wfn)
> fchk_writer.write('H2O_minimal.fchk')

**Comment by susilehtola** [comment]
See #708 and #1475 which should fix your problems.

**Comment by ajmisquitta** [comment]
Hi susilehtola, I did see that thread but I was not sure how to obtain your fix. It is not in the master, right? So do I need to take your writer.cc file and re-compile? 

Let me know if there is a better way of obtaining your changes. 

Thanks

**Comment by susilehtola** [comment]
Well, an easy way is to download the patch
  https://github.com/psi4/psi4/pull/1475.patch
and apply it on top of master.

The alternative would be to git pull from my branch.

**Comment by ajmisquitta** [comment]
Thanks a lot. I've just tested your version on both TNB and H2O and both work. I hope you will commit it to the master. 
All the best.
