### ISSUE TITLE
MP2 RI Basis Sets

### ISSUE THREAD

**Issue by dgasmith** [psi4/psi4#1512]
Reading the docs [here](http://www.psicode.org/psi4manual/master/dfmp2.html) we have the comment line "The automatic basis selector should work fine for all of the Dunning and Pople bases" which was misinterpreted to mean that all def2 basis sets needed an explicit RI keyword set. We should change this simply say that the automatic basis selection should work fine for all basis sets. 

Also looking through the [basis set list](http://www.psicode.org/psi4manual/master/basissets_byfamily.html) we have MP2 basis sets for all of the def2 series except for def2-QZVPD. Can we just default this to something reasonable?

**Comment by loriab** [comment]
> Also looking through the basis set list we have MP2 basis sets for all of the def2 series except for def2-QZVPD. Can we just default this to something reasonable?

Not following exactly. We don't have an ideal aux basis for that one, but it'll fall back on qzvpp-ri as the universal default.

Note that many default are changing in #1484

**Comment by dgasmith** [comment]
Gotcha, should be fine.
