### ISSUE TITLE
snsmp2 using old npz format before wavefunction serialization

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#1514]
the snsmp2 plugin (https://github.com/DEShawResearch/sns-mp2/blob/master/snsmp2/wavefunctioncache.py) is a big user of the npz format for file 180 before wavefunction serialization to a npy file. (Probably the only external user.) Moreover, they both use them and write out new ones for consumption.

They also modify and store `Ca_occ` in their exchange files. (Looks like npz did this: https://github.com/psi4/psi4/commit/e5b12a40c8c2d65a5e59f758df871407afdc544c#diff-dbf22cd80d16f6d8ef8250145a6d91bf) For those from a psi4 run, the Ca_occ can just be extracted by API from the deserialized wfn. But is there any facility for storing extra items in the npy?

There's some lengthy workarounds for issues since resolved (custom cast-up) but the guess of dimer from stack of monomer isn't in psi4 and the plugin isn't being actively developed (to my knowledge), so I suggest a minimal patch-up rather than thorough update.

The way to run this is to build an up-to-date psi, edit it to apply #1508, then clone the snsmp2 repo (above), navigate to `<sns-mp2-repo>/tests/` and run an input with `PYTHONPATH=../ <path-to-psi4-objdir>/stage/bin/psi4 simple.in`

If this doesn't get taken up, we'll tackle it next Wednesday the @CDSherrill group programming. In the meantime, snsmp2 is getting dropped from `psi4-rt`.

FYI @rmcgibbo

**Comment by dgasmith** [comment]
Extra items in the NumPy can be done by either adding unused fields or putting the the `array` or `variable` attributes on the Wavefunction.

**Comment by loriab** [comment]
ah yes, I had forgotten about `arrays()` as expansion space. will plan to use that for `Ca_occ`, etc.

**Comment by rmcgibbo** [comment]
Thanks for subscribing me to the thread -- I would have missed it otherwise.

> I suggest a minimal patch-up rather than thorough update.

Is your sense that this is something we could fix on the sns-mp2 side with a minimal patch up? Perhaps by adding the fields we need to `arrays()` or something? I confess that I haven't been following psi4 development closely enough recently to have much of a context here about what the API changes are or what the simplest way forward is.

Is there a ticket you can direct me towards describing the change in the API related to the npz format for file 180?

> In the meantime, snsmp2 is getting dropped from psi4-rt.

Is this the plan only if we don't fix the incompatibilty in the sns-plugin, or are you planning to drop snsmp2 from psi4-rt regardless of whether or not this gets fixed?

**Comment by rmcgibbo** [comment]
(Also subscribing @tallakahath, who is working on the sns method and code from our side)

**Comment by loriab** [comment]
Thanks for joining in, @rmcgibbo and @tallakahath.

The breaking API change is that we can now properly serialize and reconstitute wavefunction objects. What gets stored and an example [here](https://github.com/psi4/psi4/pull/1304/files). So after that, the `180.npz` storage structure doesn't have to be [written out explicitly](https://github.com/psi4/psi4/commit/e5b12a40c8c2d65a5e59f758df871407afdc544c#diff-dbf22cd80d16f6d8ef8250145a6d91bfR1410) and uses of the `180` file [can be much simpler](https://github.com/psi4/psi4/pull/1495/files#diff-ce55390d6b954c38f0c1fe9df10e0eceL87). The file also now has extension `180.npy`.

This is a definite improvement psi-side, but the break to snsmp2 is definitely our fault, so we're willing to fix it. We'd probably do the minimal disruption that gets the code running again. I think that means switching to reading npy from npz, and dealing with Ca_occ by either pulling it from a reconstitued wfn, `Ca_occ = scf_wfn.Ca_subset("SO", "OCC")` or saving it in the array psivar slot `scf_wfn.set_array("CA_OCC", Ca_occ)`. If you'd like to try doing the fix yourselves, or do greater renovations after some of the bug workarounds or progress in psi, we'd be glad of it.

I'm trying to get a psi4 v1.3rc1 out, which means conda pkg `psi4` (psi4 itself and optional compiled-in addons) and `psi4-rt` (optional run-time addons) need to be in working order. That's pretty much the case except for snsmp2 (I didn't realize the trouble was more than a `npz` --> `npy` switch until yesterday.) So I was going to drop snsmp2 from `psi4-rt` for the v1.3rc1 and expect to get it back by v1.3.

**Comment by loriab** [comment]
fix for this has commenced at https://github.com/obrien951/sns-mp2/tree/serial_wfn . it doesn't strictly involve psi4 changes, so it's possible  we may mint v1.3 and then produce a new `psi4-rt` conda metapackage with snsmp2 restored after the fix is available.

**Comment by loriab** [comment]
@zachglick has fixed this with https://github.com/DEShawResearch/sns-mp2/pull/6, and conda packages are up as snsmp2 1.0.3 .
