### ISSUE TITLE
odd SAD guess values when ghost atoms are involved

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#1528]
Possibly wrong(?) SAD guess when the first specified atoms in the molecule are ghost atoms.
Saw it first in my molecules, but already visible in test cases.

output of `/tests/ghosts/` (formic dimer):
Dimer:

    @DF-RHF iter SAD:  -376.24275022516485   -3.76243e+02   0.00000e+00 
    @DF-RHF iter   1:  -377.42229133540047   -1.17954e+00   1.11411e-02 DIIS

monomer1 (ghosts first):

    @DF-RHF iter SAD:   294.96051138857882    2.94961e+02   0.00000e+00 
    @DF-RHF iter   1:  -171.55187514768130   -4.66512e+02   5.45148e-02 DIIS

monomer1 (ghosts last):

    @DF-RHF iter SAD:  -188.00026763307497   -1.88000e+02   0.00000e+00 
    @DF-RHF iter   1:  -188.67971697531274   -6.79449e-01   6.02580e-03 DIIS

**Comment by susilehtola** [comment]
This might be related to the issue in #1497

**Comment by susilehtola** [comment]
#1497 is actually something else. Anyway, #1529 addresses the issue:
```
$ grep -A1 "DF-RHF iter SAD" output.dat 
   @DF-RHF iter SAD:  -376.24275022510938   -3.76243e+02   0.00000e+00 
   @DF-RHF iter   1:  -377.42229133534454   -1.17954e+00   1.11411e-02 DIIS
--
   @DF-RHF iter SAD:  -188.00026763308622   -1.88000e+02   0.00000e+00 
   @DF-RHF iter   1:  -188.67971697532357   -6.79449e-01   6.02580e-03 DIIS
--
   @DF-RHF iter SAD:  -188.00026763307233   -1.88000e+02   0.00000e+00 
   @DF-RHF iter   1:  -188.67971697531033   -6.79449e-01   6.02580e-03 DIIS
```
