### ISSUE TITLE
Basis set DZVP (DFT Orbital) 5x too large

### ISSUE THREAD

**Issue by leeping** [psi4/psi4#1547]
Hello there,

When running a calculation on the following system (48 atoms, C27H20S), Psi4 reports that the system has a very large number of basis functions: 

```Basis Set: DZVP
    Blend: DZVP
    Number of shells: 1106
    Number of basis function: 2352
    Number of Cartesian functions: 2550
    Spherical Harmonics?: true
    Max angular momentum: 2
```

When I look up the original citation, the number of basis functions per atom is not so large, and is in fact closer to def2-SV(P):

<img width="593" alt="screenshot 2019-02-19 20 27 20" src="https://user-images.githubusercontent.com/1441560/53067672-12612b80-348a-11e9-8fd1-9206cda39ec2.png">

Using def2-SV(P) the number of basis functions is much more reasonable:

```Basis Set: DEF2-SV(P)
    Blend: DEF2-SV(P)
    Number of shells: 210
    Number of basis function: 436
    Number of Cartesian functions: 464
    Spherical Harmonics?: true
    Max angular momentum: 2
```

Looking at the basis set file, there are actually three sets of coefficients for the AO basis, plus two density-fitting basis sets.  Here it loops from xenon back to hydrogen:
https://github.com/psi4/psi4/blob/master/psi4/share/psi4/basis/dzvp.gbs#L2198

The coefficients of the second set match the auxiliary basis set coefficients in the original paper:

<img width="466" alt="screenshot 2019-02-19 21 08 56" src="https://user-images.githubusercontent.com/1441560/53067773-9ca98f80-348a-11e9-9943-8bf06d49ad32.png">

Thus, I think the dzvp.gbs file incorrectly contains three basis sets (AO + Coulomb fitting + exchange fitting) and Psi4 is combining them all into a single AO basis set.  This is consistent with what you get when querying the EMSL basis set exchange.

**Comment by leeping** [comment]
Here's the input file:

```
#! Test

memory 120 GB

molecule {
C          -0.3648219    -0.2558995     0.0923050
C          -0.8237370    -0.4341058     1.4009892
C           0.0631893    -0.4945023     2.4676115
C           1.4325282    -0.3891253     2.2383352
C           1.9137275    -0.2544564     0.9427619
C           1.0188673    -0.2008603    -0.1248541
S           1.6337601    -0.0364981    -1.7761054
C           0.4221959    -1.0586124    -2.5697098
C           0.8238102    -1.8523826    -3.6439926
C          -0.0849812    -2.6907175    -4.2763478
C          -1.3956898    -2.7594648    -3.8167039
C          -1.7946816    -1.9614268    -2.7530877
C          -0.9127618    -1.0695029    -2.1338664
C          -1.3561501    -0.1563074    -1.0295856
C          -1.9665877     1.0501577    -1.2219860
C          -3.4084245     1.3237948    -1.5387008
C          -4.1778103     0.9153814    -2.6656460
C          -3.6040754     0.3592572    -3.8324065
C          -4.3883329    -0.0114701    -4.8966852
C          -5.7880208     0.1587824    -4.8485691
C          -6.3715656     0.7419527    -3.7516437
C          -5.5875462     1.1595529    -2.6489158
C          -6.1606962     1.8632603    -1.5594824
C          -5.3698613     2.3529990    -0.5506849
C          -3.9860050     2.0985433    -0.5554402
C          -2.9661061     2.5564496     0.4375737
C          -1.6390824     2.2179359    -0.2602651
C          -1.1154328     3.3910761    -1.1017198
H          -0.3127358    -0.6228208     3.4762500
H          -1.8927706    -0.5052113     1.5726366
H           1.8586583    -1.8262256    -3.9659948
H           0.2398716    -3.3060821    -5.1077784
H          -2.1089392    -3.4246186    -4.2897038
H          -2.8205109    -1.9987160    -2.4069456
H          -3.0590481     1.9923608     1.3740789
H          -3.0646319     3.6174136     0.6841579
H          -0.8780603     1.9494578     0.4669513
H          -1.8608701     3.7224689    -1.8292206
H          -0.8671432     4.2380262    -0.4563872
H          -0.2145328     3.1009119    -1.6469308
H           2.1299487    -0.4343560     3.0671308
H          -2.5302569     0.2498912    -3.8883093
H          -5.8058019     2.9352268     0.2545431
H          -3.9272763    -0.4346889    -5.7821545
H          -7.4432146     0.9114819    -3.7244639
H          -7.2306828     2.0442982    -1.5581508
H          -6.3974861    -0.1494268    -5.6908797
H           2.9804384    -0.2081479     0.7541413
}

set {
basis dzvp
scf_type df
reference uks
}

set_num_threads(4)

gradient('b3lyp-D3BJ')
```

**Comment by loriab** [comment]
wow, great catch, @leeping. Looks like it's been that way since the beginning, 2012. https://github.com/psi4/psi4archive/blob/4.0b1/lib/basis/dzvp.gbs#L2198 .

forwarding to @bennybp as an EMSL blooper.

**Comment by bennybp** [comment]
Ah interesting. This seems to be a special case where the EMSL BSE automatically included fitting basis sets when you requested the orbital basis. I don't know of any other case where they did that.

That seems to break their gaussian formatter. The NWChem format looks ok, though.

Noted in https://github.com/MolSSI-BSE/basis_set_exchange/issues/43
