### ISSUE TITLE
Second-order convergence acceleration for SCF

### ISSUE THREAD

**Issue by dgasmith** [psi4/psi4#155]
Second-order SCF is now partially implemented (b8315f8b4e0645f7fd15f24ae099ca6968d91809). If anyone has some brutal RHF/UHF/ROHF test cases please send them over or try them out.

The current TODO list:
- [x] RHF capability
- [x] UHF capability
- [x] ROHF capability
- [x] The JK algorithm must support non-symmetric density matrices (e.g. not the PK algorithm)
- [x] A few brutal tests cases for longtest
- [x] Documentation

**Comment by susilehtola** [comment]
A good test case might be the Cadmium-imidazole complex in
 http://www.chem.duke.edu/~xqhu/geoms.tar.gz
in the 3-21G basis which fails to converge with plain DIIS, see
 http://dx.doi.org/10.1063/1.3304922

**Comment by jgonthier** [comment]
Daniel, I have some non-converging UHF test cases for DIIS when your code
is ready to handle them.

2015-07-28 2:59 GMT-04:00 Susi Lehtola <notifications@github.com>:

**Comment by dgasmith** [comment]
@susilehtola 
This really looks like an initial guess issue. With a SAD guess both DIIS and SORHF converge fairly smoothly. With a core guess we are never close enough to a minima where second-order methods will really help you without some kind of trust-region mechanics.

**Comment by lothian** [comment]
It's possible recent changes have introduced errors with the v15 Intel compilers.  See, e.g.,

https://testboard.org/cdash/buildSummary.php?buildid=24529

The overall dashboard is here, and you can see that all instances of the v15 builds have started dying in libscfsolver/hf.cc.

**Comment by jturney** [comment]
@lothian I've determined on my boxes where the compile failed it due to Intel compilers still use my gcc headers for the standard library. My gcc compilers on that box are a little dated (version 4.3.4) which do not provide the C++11 std::to_string functions. Is this the case for you?

I have some implementations of this function in one of our libraries just need to put in a test whether to include them or not.

**Comment by ryanmrichard** [comment]
As @jturney  said, this is a C++11 header issue.  As a side note, the line in question is easily, and canonically, fixed with a stringstream...

**Comment by jturney** [comment]
Which is essentially what the wrappers I wrote do.

**Comment by dgasmith** [comment]
@lothian 
Fixed in a2d3336.

This brings up an interesting question: do we require C++11 headers yet?

**Comment by ryanmrichard** [comment]
@dgasmith I started a C++11 topic over on the forum, http://forum.psicode.org/t/c-11-is-it-time/43?u=ryanmrichard.  The C++11 topic keeps coming up in issues on GitHub and then lost, perhaps this will get it some attention.

**Comment by dgasmith** [comment]
This is now implemented with the wavefunction_pass update. Please post any issues that you may have with SOSCF in a new issue.
