### ISSUE TITLE
SAPT with aug-cc-pV5Z

### ISSUE THREAD

**Issue by dspoel** [psi4/psi4#1557]
Normal CCSD and CCSD(T) calculations work fine with big basis sets up to aug-cc-pV5Z but SAPT crashes for me with:

QcdbException BasisSetNotFound: BasisSet::construct: Unable to find a basis set for atom 1 for key BASIS among:
  Shell Entries: ['LI']
  Basis Sets: [('AUG-CC-PV5Z', 'AUG-CC-PV5Z', None)]

Input:

```
molecule LiF {
        1 1
        Li  0.000000000  0.000000000  0.000000000
        --
        -1 1
        F  0.500000000  0.000000000  0.000000000

        units angstrom
        no_reorient
}

set globals {
        basis aug-cc-pv5z
}

set_memory(32000000000)
energy('sapt2+3(ccd)dmp2')
```

**Comment by andysim** [comment]
It looks like the [cc-pV5Z](https://github.com/psi4/psi4/blob/master/psi4/share/psi4/basis/cc-pv5z.gbs#L92-L167) basis exists for Li, but the [aug-cc-pV5Z](https://github.com/psi4/psi4/blob/master/psi4/share/psi4/basis/aug-cc-pv5z.gbs) files doesn't contain an entry for that atom.  Were your tests with CC calculations on a molecule that does not contain Li?

**Comment by dspoel** [comment]
No, the same compound:

```
molecule LiF {
  0 1
  Li
  F 1 1.5
}

set {
   basis cc-pv5z
   df_scf_guess false
   freeze_core false
}
set_memory(32000000000)

energy('ccsd(t)')
```

**Comment by dspoel** [comment]
I see this was without augmented keyword, with that added the test above crashes as well.

**Comment by hokru** [comment]
There are (still?) unpublished basis sets from Feller on the EMSL. But also published basis sets from Dunning in 2011. Careful what to take when you want to compare data.
The latter can be found here: http://www.grant-hill.group.shef.ac.uk/ccrepo/

**Comment by dspoel** [comment]
There is a basis set at EMSL anyway. Will experiment.

**Comment by dspoel** [comment]
Thanks for tip hokru, added the basis from ccrepo and now it is running. 
Are there any plans to update or should I just drop in a pull request?

**Comment by hokru** [comment]
I recall @loriab mentioning that short term psi4 will handle basis sets through https://github.com/MolSSI-BSE/basis_set_exchange.
I just checked and it looks like it has already the correct basis set included https://github.com/MolSSI-BSE/basis_set_exchange/blob/master/basis_set_exchange/data/dunning/cc-pV5Z-diffuse_prascher2011a.1.json

--
The calculation works? I would have expected problems with missing density fitting basis sets. For the SAPT level you might need all of these (I think):
```
df_basis_scf=
df_basis_sapt=
df_basis_mp2=
```

**Comment by andysim** [comment]
I am glad you were able to get it running: I failed in my attempt.  I added the orbital basis sets from Grant Hill's site to your input, but there do not appear to be any auxiliary basis sets available for the density fitting procedure that's used in the SCF and, I believe, the SAPT parts.  Please check your output to make sure that a reasonable auxiliary basis set is being used for the density fitting calculations: the aux basis should normally be about a factor of 3 larger than the orbital basis, but it's possible that a slightly smaller one will suffice for something as large as aug-cc-pV5Z.   There is an [effort underway](https://github.com/MolSSI-BSE/basis_set_exchange) at MolSSI to curate basis sets in a more organized way and we will almost certainly be using that to update the library when it is ready to go, so I don't think a PR is needed at this time, thanks.

**Comment by dspoel** [comment]
However, now my test run crashes with the message below. Is it trying to write a file in a directory where I don't have permissions or so?

Traceback (most recent call last):
  File "/home/apps/psi/psi4conda/bin/psi4", line 248, in <module>
    exec(content)
  File "<string>", line 31, in <module>
  File "/home/apps/psi/psi4conda/lib//python3.6/site-packages/psi4/driver/driver.py", line 460, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/apps/psi/psi4conda/lib//python3.6/site-packages/psi4/driver/procrouting/proc.py", line 860, in select_ccsd_t_
    return func(name, **kwargs)
  File "/home/apps/psi/psi4conda/lib//python3.6/site-packages/psi4/driver/procrouting/proc.py", line 2197, in run_ccenergy
    core.cctransort(ref_wfn)

RuntimeError: 
Fatal Error: PSIO Error
Error occurred in file: /scratch/psilocaluser/conda-builds/psi4_1495014881710/work/psi4/src/psi4/libpsio/error.cc on line: 129
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)
psi::psio_error(unsigned int, unsigned int)
psi::PSIO::rw(unsigned int, char*, psi::psio_address, unsigned long, int)
psi::psio_write(unsigned int, char const*, char*, unsigned long, psi::psio_address, psi::psio_address*)
psi::DPD::file4_mat_irrep_wrt(psi::dpdfile4*, int)

*** Psi4 encountered an error. Buy a developer more coffee!
*** Resources and help at github.com/psi4/psi4.

**Comment by andysim** [comment]
It's a bit of a guess, but perhaps the scratch disk is full?

**Comment by loriab** [comment]
transition to MolSSI BSE will start in April at the earliest and one family at a time, probably def2 first, according to plan I just formulated with @bennybp, who's doing that valuable project.

however, I did spend a whole weekend in Sept/Oct 2017 updating the Li/Be/Na/Mg basis sets from developer sources. then Monday came, and everything was lost from my memory. I've still got the directory, so I'll push a PR. Don't think I'll have time to study it enough to have confidence to merge it.

**Comment by bennybp** [comment]
> do not appear to be any auxiliary basis sets available for the density fitting procedure that's used in the SCF and, I believe, the SAPT parts.

If I'm following this correctly, you are talking about RI fitting for Li? It looks like the EMSL BSE was missing that, but I've taken the values from turbomole for the new BSE. (The developers of that fitting basis were turbomole developers)

**Comment by loriab** [comment]
#1559 has basis sets, orbital and fitting for Li, Be, Na, Mg

**Comment by PeterKraus** [comment]
#1559 has been merged, but the example in the OP still doesn't work with current master. The LiF pair works with aTZ, aQZ, but crashes with a5Z for both `Li+ F-` and `He F-`; `Ne F-` works. I was under the impression that #1559 should have included the fitting bases for Li, but they're not present in either the (RI)[https://raw.githubusercontent.com/psi4/psi4/master/psi4/share/psi4/basis/aug-cc-pv5z-ri.gbs] or the (JKFIT)[https://raw.githubusercontent.com/psi4/psi4/master/psi4/share/psi4/basis/aug-cc-pv5z-jkfit.gbs] basis.

Have I missed something?

**Comment by loriab** [comment]
If my statement https://github.com/psi4/psi4/issues/1557#issuecomment-467273962 "and fitting" had been correct, then yes, it should have worked. But looking again, http://tyr0.chem.wsu.edu/~kipeters/basissets/alkal-nr.html is focused on orbital, and old EMSL for Dunning alkali has no fitting for _diffuse_ RI or for any JK. So #1559 wouldn't have fixed the original issue. But Ben extracted fitting sets from Turbomole, so at least aug-cc-pV5Z-RI for Li is accessible with the [new EMSL](https://www.basissetexchange.org/) and from Grant Hill's site (thanks, @hokru). No JK in sight. Basis sets have too many dimensions ...

**Comment by PeterKraus** [comment]
After discussing this with @loriab, the main problem with this calculation is that the aug-cc-pV5Z-JKFIT basis set just doesn't exist. From Psi4 point of view, there's not much that can be done at the moment. I've checked that the aug-cc-pVQZ calculation works, and the -RI fitting basis added in #1559 might be of some help, if it's any consolation... Closing.
