### ISSUE TITLE
Symmetry Can Mangle NBO Output

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#1566]
The following input 
```
molecule {
   0 1 
 S          0.0904282062       -0.4095883553        0.0000000000
 O          1.3547506908        0.3023925212        0.0000000000
 O         -0.7450974916        0.1927054620        1.2404690507
 H         -0.3631668951        1.0551025998        1.4663407894
 O         -0.7450974916        0.1927054620       -1.2404690507
 H         -0.3631668951        1.0551025998       -1.4663407894
}


set basis cc-pV(D+d)Z

en, wfn = energy('b3lyp', return_wfn = True)
nbo = NBOWriter(wfn)
nbo.write("input.47")
```
produces an absolute nonsense NBO analysis, with heavily delocalized core orbitals, orbital energies over 350, and 1000+ strong donor-acceptor interactions. When you add `symmetry c1`, all is normal again.

I haven't been successful in finding the minimal possible example input that displays the problem. Water, for instance, seems to be just fine.

**Comment by loriab** [comment]
I wonder if d-fns on sulfur are the instigators.

**Comment by JonathonMisiewicz** [comment]
I'll start looking into this, because I need NBO on sulfur systems. I do not promise a fix, but hopefully I can at least ID the problem. My money is with Lori's guess - d functions on sulfur.
