### ISSUE TITLE
Can't Solve CPHF for H2

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#1573]
The following input file...
```
molecule {
H
H 1 1.0 
}

set basis sto-3g
set scf_type pk

hessian('scf')
```

crashes, as Psi can't solve the CPHF equations for the hessian.

**Comment by loriab** [comment]
should diagnose for sure but cc-pvdz works so not a crisis

**Comment by JonathonMisiewicz** [comment]
Probably best to let this one be until #1550 comes in, as well.

**Comment by JonathonMisiewicz** [comment]
Now that #1550 is in, the computation finished successfully.
