### ISSUE TITLE
Error in normalization of h basis functions

### ISSUE THREAD

**Issue by AJStone** [psi4/psi4#1574]
I have been modifying my gdma code so that it can handle h functions. It's a fairly straightforward change, but I found that I got errors in the multipoles when there were h functions in the basis. In particular, the total charge was always nonzero. Repeated checks found no errors in the gdma code.

Finally I found that there is a bug in the treatment of h functions in Psi4, or at least an inconsistency with d, f and g. If the normalization factor for z^2 exp(-zeta r^2) is N, then the factor for xy exp(-zeta r^2) is \sqrt(3)N -- it needs the extra sqrt(3). Similarly z^5, xz^4, x^2z^3, xyz^3 and x^2y^2z cartesian h functions all need different normalization factors. If the gdma code takes account of these as it does for d, f and g, I get the errors. If however I treat them all as having the same normalization factor as z^5, I get sensible results -- total charges are now zero. Whether the results are correct, however, is doubtful, because the normalization error probably affects the wavefunction.

Using an fchk file from Gaussian16 gives the same errors. Was the Psi4 fchk code derived from gaussian?

My revised version of gdma is available at https://git.uis.cam.ac.uk/x/ch-stone/u/ajs1/gdma.git

**Comment by susilehtola** [comment]
The fchk writer for psi4 doesn't handle H functions, it stops at G. Also, it looks like the G code is not similar to what the code that shall not be mentioned (CSNBM) is using
https://github.com/psi4/psi4/blob/a79a6851fbb97fd7b433fb1260230a0c70e4bf94/psi4/src/psi4/libmints/writer.cc#L453

because apparently gdma is using another convention.

**Comment by hokru** [comment]
I don't see a limitation for spherical functions? Only for cartesian where psi4 would throw an error.

**Comment by susilehtola** [comment]
@hokru the problem report is discussing cartesian functions.

**Comment by AJStone** [comment]
For clarification: the wavefunction calculation used spherical basis functions, but gdma needs cartesians, so it carries out the transformation. The order of the cartesian functions is a private matter for gdma if the wavefunction is expressed in spherical functions. It wouldn't be for cartesian basis functions, but I don't envisage anyone using cartesians for h orbitals. Gdma does expect the spherical components to be normalised and orthogonal, but it appears that this is not the case for h functions in the fchk file.

I had heard that the Psi4 fchk writer doesn't handle h functions, so I was surprised to find that it does. However it does seem that the code is not correct, either in Psi4 or elsewhere. I hope that the problem lies just in the conversion to fchk format. It would be good to have it fixed, and it probably wouldn't be hard to do.

**Comment by andysim** [comment]
I will need a little bit of time to properly parse the original message, but I suspect I know the source of the discrepancy.  I am guilty of writing the original FCHK implementation; I wrote it as a simple interface to the GDMA code.  I don't have access to any versions of Gaussian, so I used a combination of the example FCHK files that ship with GDMA, and the GDMA source, to reverse-engineer something resembling an FCHK file (that decision has backfired in recent weeks as people use the FCHK files we produce for other interfaces and find that it's incomplete: we've been working through those bug reports steadily).  Where things get tricky is that Psi4 (and its progenitor) uses the [CCA integral](https://github.com/psi4/psi4/files/2957296/CCA.pdf) "natural" norm convention, unlike that other code (detailed on the last page of that attachment).  Therefore, there's a factor of 
![image](https://user-images.githubusercontent.com/201881/54209345-029a9d00-44b4-11e9-85b3-0789d498cc93.png)
present in our basis function norms that some other codes lack.  The presence of the overlap metric in the SCF equations means that the alternative basis function normalization manifests itself in different MO coefficients, but both conventions yield equivalent wavefunctions and properties.  It's these corrections that are being applied in the snippet of code that @susilehtola referenced above.  I surmise that these are not being applied consistently somewhere in the translation between Psi4 and GDMA.

**Comment by susilehtola** [comment]
@andysim but isn't psi4 using the spherical basis to write the orbitals? The spherical functions should always be normalized, the only question then is just the order in which the functions are reported, i.e. is it `-m, ..., -1, 0, 1, ..., +m` or `0, -1, +1, -2, +2, ..., -m, +m`.

**Comment by susilehtola** [comment]
At least the FCHK writer isn't doing anything for spherical functions, except permuting `zxy -> xyz`.

**Comment by andysim** [comment]
@susilehtola: that's correct.  I wrote my reply before I saw the second message from @AJStone, so I had assumed the basis itself is Cartesian.  As long as the extra factors that I mentioned are folded into the backtransformation it *should* be fine.  I'll keep digging around and let you know if I find anything.  The spherical code should work for any angular momentum; it's only the Cartesians where there are subtleties to handle.

**Comment by susilehtola** [comment]
@AJStone it might be that the problem is in your conversion code.

If you like, you're free to use the code from ERKALE to calculate the cartesian coefficients of arbitrary order solid harmonics https://github.com/susilehtola/erkale/blob/master/src/solidharmonics.cpp

**Comment by andysim** [comment]
I could well be misreading the code here, but I think there's a problem in the H function transformation.  If I look at [the transformation coefficients](https://git.uis.cam.ac.uk/x/ch-stone/u/ajs1/gdma.git/blob/HEAD:/src/gdma.f90#l275) and compare them to Table 1 of [this paper](http://onlinelibrary.wiley.com/doi/10.1002/qua.560540202/full), there appears to be many discrepancies.  The G functions that I looked at seem to match up perfectly, accounting for the factor of sqrt(2) for m≠0 terms, so I'd expect to be able to compare to the paper.  However, e.g., the v203 component for the m=0 of an H function is off by a factor of sqrt(21), which implies that the normalization coefficients that I mentioned before have already been rolled into the coefficient on line 286 of gdma.f90.  That's also consistent with the observation that applying the same normalization again leads to strange results.  Similarly, the discrepancy for v401 is a factor of three, also consistent with the Cartesian normalization factor.

**Comment by AJStone** [comment]
Dear Andy,

The treatment of the spherical harmonic functions in gdma is a bit odd
(it was originally based on Cadpac code). The spherical harmonics are
the R_lm (no sqrt(2l+1/4pi) factor) so the coefficient of the z^n term
in R_n0 is always 1. The normalizing factor for z^n exp[-zeta r^2] is
attached to the contraction coefficents so one doesn't need to worry
about it any more. I got the coefficients for the R_lm using
Mathematica, so they should be alright, but I admit that I haven't
checked them for orthogonality. The ratio of the normalising factors for
x^ly^mz^n and z^(l+m+n) is applied to the density matrix in lines 1810
onwards of dma.f90, so the normalization is done there and it's only
necessary to accumulate the integrals over the products of x^ly^mz^n terms.

But this means that the spherical harmonics as they appear in the
spherical-cartesian transformation in gdma.f90 are not actually
orthonormal as they stand.

This is easier to handle than it might sound. As far as the fchk file is
concerned, it is only necessary to provide orbitals described in terms
of orthonormal spherical harmonics, and the corresponding density matrix.

I hope this clarifies things. I may well have made some mistakes in
implementing it for the h functions, but I have checked it carefully
several times. What puzzles me is how the normalising coefficients for
the cartesian terms get into the fchk description in terms of spherical
harmonics.

Best wishes,
Anthony

**Comment by AJStone** [comment]
Correction (I have a very bad cold at the moment so my mind is even less reliable than usual):
The spherical harmonics expressed in terms of cartesians in the th transformation matrix in gdma.f90 are not normalized to unity but they should be orthogonal with respect to integration over a sphere. Note that the x^i y^j z^k are not the normalized v(i,j,k) of Schlegel and Frisch but literal products of powers of x, y and z.

**Comment by andysim** [comment]
Dear Anthony,

Thank you for the detailed explanation.  In terms of spherical harmonics in Psi4, there are no hard coded terms anywhere as far as I can remember: all integrals are transformed on the fly, using a general regular solid harmonic generating routine.  Therefore, G and H functions are both handled by the same arbitrary-order transformation code.  Your illness-addled brain is still more powerful than mine, so apologies if I'm wrong here, but I think I have confirmed my error diagnosis from last night.  I found my old Mathematica code for generating (real) regular solid harmonics and can exactly match the [L=5 transformation coefficients](https://git.uis.cam.ac.uk/x/ch-stone/u/ajs1/gdma.git/blob/HEAD:/src/gdma.f90#l275), as well as the the coefficients listed in Table 1 of the GDMA manual.  However, for the L<5 coefficients in gdma.f90 my RSH generating code does not match.  I can get exact agreement for these lower angular momentum terms by adding a factor of
![image](https://user-images.githubusercontent.com/201881/54278407-a47bc180-4568-11e9-8875-e9ea637c3c1b.png)
to the generating code.  Therefore it appears that there is an inconsistency in the Cartesian normalization convention between the {s,p,d,f,g} and the {h} functions in gdma.f90.  I hope this helps,

Best regards,

Andy

**Comment by AJStone** [comment]
Yes, you're right, Andy, there is an inconsistency. I believe that gdma is actually correct as it now stands, and there's no error in Psi4, but I need to remove the inconsistency.
It is a such a help to have someone else look at the code and see what I hadn't seen myself. Thanks.

**Comment by JonathonMisiewicz** [comment]
It looks like there's no error in Psi here. Happy to reopen if I'm mistaken.
