### ISSUE TITLE
DF DCFT Properties Incorrect

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#1579]
An error which is very high on my to-fix list, but where the fix is very involved.

DF-DCT properties as present are not correct. I've tested against my own Python code and the Psi code and found disagreements in the fifth and sixth decimal place between finite difference and analytic properties. I've spoken with the code authors, and we are aware of two sources of disagreement.
1. For gradients, the RDMs are contracted against the conventional derivative integrals, not the density fitted derivative integrals.
2. Due to a subtle point in the derivation, the DF-DCT cumulant stationarity conditions are not variational minimization of the energy, as they are in conventional DCT. Accordingly, you're missing a cumulant response term for gradients and other properties.

The fix for point 1 will hopefully just be marking the wavefunction as density fitted and leave the contractions to the `Deriv` object. However, DCT at present interferes with RDM processing in `libtrans`, so the fix will be likely be more involved.

The fix for point 2 is not clear. I'm aware of three options:
* Change the DF-DCFT stationarity conditions to be variational minimization of the energy
* Change which terms are to be contracted against JKFIT integrals and which against RIFIT integrals, so the stationarity conditions are "fixed" automatically
* Add a cumulant response term. (Please don't make me do this.)

I favor option B, but it'll take time to see what B does to energies.

**Comment by ssh2** [comment]
I agree that option B is the best. The effect of the fix will be very minor. This can be easily tested by comparing to DCT code with conventional integrals (and we have done this in the past). Also, current version of the code should recover the exact DCT energy and gradient when using a very large auxiliary basis set.

**Comment by JonathonMisiewicz** [comment]
Status update on this, including developments from half an hour ago.

Numerical tests indicate the difference in reaction energies between the current DF scheme and the new one are negligible. The Excel file is attached if anybody wants to look over the numbers themselves. @ssh2 and I are agreed that between that and some additional theoretical points, we'll just switch the density fitting scheme to fix Point 2. In the new scheme, the cumulant gets contracted against RIFIT integrals as before, and the _entire_ rest of the 2RDM gets contracted against JKFIT integrals.

[df_dcft_comparison.xlsx](https://github.com/psi4/psi4/files/3023032/df_dcft_comparison.xlsx)

Point 1 is trickier. I've spoken with @jturney about DF gradients in Psi. Although `deriv.cc` does a check to see if the wavefunction is density fitted in the gradient code, it isn't for density fitted gradients but to check whether necessary tensors exist on disk or as member variables. As far as I know, every DF gradient in Psi runs through its own module. DF-MP2 gradients have `dfmp2`, DF-SCF has `scfgrad`, and Bozkaya has `dfocc`. This will require some attention, but likely won't get it until after ACS Orlando.

**Comment by JonathonMisiewicz** [comment]
Fixed by #2100. The new implementation uses JKFIT integrals for 1RDM product terms and RIFIT integrals for cumulant terms. Finite difference dipoles and gradients both come up clean.
