### ISSUE TITLE
qcengine install fails

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#1582]
The compilation of Psi4 wants to install qcengine, but it's trying to do it in the wrong target directory
```
running install_scripts
Installing qcengine script to /usr/local/bin
error: [Errno 13] Permission denied: '/usr/local/bin/qcengine'
make[2]: *** [external/upstream/qcengine/CMakeFiles/qcengine_external.dir/build.make:74: external/upstream/qcengine/qcengine_external-prefix/src/qcengine_external-stamp/qcengine_external-install] Error 1
make[2]: Leaving directory '/home/work/psi4/objdir'
make[1]: *** [CMakeFiles/Makefile2:1440: external/upstream/qcengine/CMakeFiles/qcengine_external.dir/all] Error 2
make[1]: Leaving directory '/home/work/psi4/objdir'
make: *** [Makefile:141: all] Error 2
```

**Comment by loriab** [comment]
Hmm, sounds like #1548, which I wasn't able to hunt down. Really should be installing to `<objdir>/stage/lib/${PYMOD_INSTALL_LIB}/`. Are you setting `CMAKE_INSTALL_PATH`?

**Comment by loriab** [comment]
I'm closing this in favor of #1548. If anyone sees this, please stop and ping me to discuss your build environment, as I can't figure out how it's coming about.
