### ISSUE TITLE
Psi4 litters empty files named "fort.56"

### ISSUE THREAD

**Issue by TiborGY** [psi4/psi4#1584]
Default 1.2 conda install. Even a very simple HF calculation creates and leaves behind an empty file named "fort.56", right next to the input file. I do not know what this file is used for (it looks like something a Fortran program would create), but I see no reason why Psi4 should leave behind litter in the working directory.

Probably the easiest solution would be to just delete it at exit.

PS: It seems like I have accidentally installed 1.2 instead of 1.3...oops.

**Comment by hokru** [comment]
Get 1.3 from here: https://admiring-tesla-08529a.netlify.com/installs/v13/

I have no fort.56 files with it

**Comment by TiborGY** [comment]
I followed links from the manual, so it looks like the manual is still linking to 1.2, in a number of pages.

**Comment by PeterKraus** [comment]
Could you be a bit more verbose?

**Comment by hokru** [comment]
Yes psicode.org is outdated and will be replaced soon. Maybe @loriab could update the download link until then.

The latest releases are also linked on the github release page: https://github.com/psi4/psi4/releases

**Comment by TiborGY** [comment]
Sure thing, the link on this page [http://www.psicode.org/psi4manual/master/conda.html](url) point to 1.2, and the link here [http://www.psicode.org/psi4manual/master/build_obtaining.html#binary-installer](url) is also pointed at 1.2. (via a redirect from http://www.psicode.org/downloads.html)

**Comment by PeterKraus** [comment]
Ouch, the "latest" in http://www.psicode.org/psi4manual/master/conda.html#how-to-install-a-psi4-binary-with-the-psi4conda-installer-command-line suggests the python-3.5 version, which is `psi4-1.1rc1+6db9b1f-py35_0`. The latest folder really is not latest at all ...

**Comment by TiborGY** [comment]
OK, installed 1.3 and the littering is gone, thanks!

**Comment by loriab** [comment]
thanks. I've redirected the link from current psicode.org. Didn't realize we weren't going to get the domain transferred for a while. And Radovan Bast has sent me a loadtime analysis of the new site, so I should be able to speed that up dramatically.
