### ISSUE TITLE
unable to install on ubuntu

### ISSUE THREAD

**Issue by patrashantigopal** [psi4/psi4#1586]
dabu@RES-SHANTIPA:/mnt/c/Windows/System32$ curl -O "http://vergil.chemistry.gatech.edu/download/Psi4conda-latest-py35-Windows-x86_64.sh"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file Psi4conda-latest-py35-Windows-x86_64.sh:
Warning: Permission denied
100   246  100   246    0     0    710      0 --:--:-- --:--:-- --:--:--   710
curl: (23) Failed writing body (0 != 246)

**Comment by loriab** [comment]
That's because there's no longer a py35 among the "latest" release. I'm retiring those docs. Please follow the commands at https://admiring-tesla-08529a.netlify.com/installs/v13/ (linked off "Downloads" from psicode.org). You'll want to select Linux/Installer/"Stable Release".

Thanks for pointing out ways we're leading people astray.

**Comment by patrashantigopal** [comment]
I want to download windows WSL

**Comment by loriab** [comment]
Ah, then choose the "Windows WSL" button instead (I forgot that "Ubuntu") could mean both. The binaries are actually identical btwn Linux and WSL.

**Comment by patrashantigopal** [comment]
dabu@RES-SHANTIPA:/mnt/c/Windows/System32$ curl "http://vergil.chemistry.gatech.edu/psicode-download/Psi4conda-1.3-py36-WindowsWSL-x86_64.sh" -o Psi4conda-1.3-py36-WindowsWSL-x86_64.sh --keepalive-time 2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file Psi4conda-1.3-py36-WindowsWSL-x86_64.sh:
Warning: Permission denied
  0  515M    0  3759    0     0   6382      0 23:31:28 --:--:-- 23:31:28  6371
curl: (23) Failed writing body (0 != 3759)

**Comment by susilehtola** [comment]
@patrashantigopal your problem is that you're trying to write to a directory that you don't have permissions to.

**Comment by patrashantigopal** [comment]
can I write it in another directory something like 

c/Users/shantigp/projects

**Comment by patrashantigopal** [comment]
dabu@RES-SHANTIPA:/mnt/c/Users/shantigp/projects$ curl "http://vergil.chemistry.gatech.edu/psicode-download/Psi4conda-1.3-py36-Linux-x86_64.sh" -o Psi4conda-1.3-py36-Linux-x86_64.sh --keepalive-time 2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  515M  100  515M    0     0  4751k      0  0:01:51  0:01:51 --:--:-- 4323k

**Comment by patrashantigopal** [comment]
Please look at the test result now:

(base) dabu@RES-SHANTIPA:/mnt/c/Users/shantigp/projects/psi4conda/bin$ psi4 --test
numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
================================================= test session starts ==================================================
platform linux -- Python 3.6.8, pytest-4.3.0, py-1.8.0, pluggy-0.9.0 -- /mnt/c/Users/shantigp/projects/psi4conda/bin/python
cachedir: .pytest_cache
rootdir: /mnt/c/Users/shantigp/projects/psi4conda, inifile:
collected 1024 items / 1002 deselected / 22 selected

../lib/python3.6/site-packages/psi4/tests/test_addons.py::test_gdma PASSED                                       [  4%]
../lib/python3.6/site-packages/psi4/tests/test_addons.py::test_mrcc SKIPPED                                      [  9%]
../lib/python3.6/site-packages/psi4/tests/test_addons.py::test_chemps2 PASSED                                    [ 13%]
../lib/python3.6/site-packages/psi4/tests/test_addons.py::test_dftd3 FAILED                                      [ 18%]
../lib/python3.6/site-packages/psi4/tests/test_addons.py::test_libefp LIBEFP: parameters for fragment "NH3" are already loaded
PASSED                                     [ 22%]
../lib/python3.6/site-packages/psi4/tests/test_addons.py::test_pcmsolver PASSED                                  [ 27%]
../lib/python3.6/site-packages/psi4/tests/test_addons.py::test_erd SKIPPED                                       [ 31%]
../lib/python3.6/site-packages/psi4/tests/test_addons.py::test_simint PASSED                                     [ 36%]
../lib/python3.6/site-packages/psi4/tests/test_addons.py::test_json PASSED                                       [ 40%]
../lib/python3.6/site-packages/psi4/tests/test_addons.py::test_cfour SKIPPED                                     [ 45%]
../lib/python3.6/site-packages/psi4/tests/test_addons.py::test_v2rdm_casscf PASSED                               [ 50%]
../lib/python3.6/site-packages/psi4/tests/test_addons.py::test_gpu_dfcc SKIPPED                                  [ 54%]
../lib/python3.6/site-packages/psi4/tests/test_addons.py::test_grimme_3c FAILED                                  [ 59%]
../lib/python3.6/site-packages/psi4/tests/test_addons.py::test_dkh PASSED                                        [ 63%]
../lib/python3.6/site-packages/psi4/tests/test_addons.py::test_snsmp2 SKIPPED                                    [ 68%]
../lib/python3.6/site-packages/psi4/tests/test_addons.py::test_resp PASSED                                       [ 72%]
../lib/python3.6/site-packages/psi4/tests/test_psi4.py::test_psi4_basic PASSED                                   [ 77%]
../lib/python3.6/site-packages/psi4/tests/test_psi4.py::test_psi4_cc PASSED                                      [ 81%]
../lib/python3.6/site-packages/psi4/tests/test_psi4.py::test_psi4_cas PASSED                                     [ 86%]
../lib/python3.6/site-packages/psi4/tests/test_psi4.py::test_psi4_dfmp2 PASSED                                   [ 90%]
../lib/python3.6/site-packages/psi4/tests/test_psi4.py::test_psi4_sapt PASSED                                    [ 95%]
../lib/python3.6/site-packages/psi4/tests/test_psi4.py::test_psi4_scfproperty PASSED                             [100%]

======================================================= FAILURES =======================================================
______________________________________________________ test_dftd3 ______________________________________________________

molrec = {'elbl': ['', '', '', '', '', '', ...], 'elea': [12, 12, 1, 1, 1, 1, ...], 'elem': ['C', 'C', 'H', 'H', 'H', 'H', ...], 'elez': [6, 6, 1, 1, 1, 1, ...], ...}
name_hint = 'b3lyp', level_hint = 'd2', param_tweaks = None, ptype = 'gradient', dashcoeff_supplement = None
verbose = 1

    def run_dftd3_from_arrays(molrec,
                              name_hint=None,
                              level_hint=None,
                              param_tweaks=None,
                              ptype='energy',
                              dashcoeff_supplement=None,
                              verbose=1):
        """Specialized signature disentangling dispersion level and
        parameters for computing on `molecule` with engine `DFTD3`. See
        `dashparam.from_array` for parameter details.

        """
        jobrec = {}
        jobrec['error'] = ''
        jobrec['success'] = None
        jobrec['return_output'] = True
        prov = {}
        prov['creator'] = 'QCDB'
        prov['version'] = __version__
        prov['routine'] = sys._getframe().f_code.co_name
        jobrec['provenance'] = prov

        # strip engine hint
        if name_hint.startswith('d3-'):
            name_hint = name_hint[3:]

        opts = {}
        opts['level_hint'] = level_hint
        opts['params_tweaks'] = param_tweaks
        opts['dashcoeff_supplement'] = dashcoeff_supplement

        jobrec['molecule'] = molrec
        jobrec['method'] = name_hint
        _, jobrec['driver'] = parse_dertype(ptype, max_derivative=1)
        jobrec['options'] = opts
        #jobrec['options'] = copy.deepcopy(options)

        try:
>           dftd3_driver(jobrec)

../lib/python3.6/site-packages/psi4/driver/qcdb/intf_dftd3/runner.py:131:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

jobrec = {'driver': 'gradient', 'error': "Dftd3Error('Unsuccessful run. Possibly -D variant not available in dftd3 version.',)"...a': [12, 12, 1, 1, 1, 1, ...], 'elem': ['C', 'C', 'H', 'H', 'H', 'H', ...], 'elez': [6, 6, 1, 1, 1, 1, ...], ...}, ...}
verbose = 1

    def dftd3_driver(jobrec, verbose=1):
        """Drive the jobrec@i (input) -> dftd3rec@i -> dftd3rec@io -> jobrec@io (returned) process.

        Input Fields
        ------------

        Optional Input Fields
        ---------------------

        Output Fields
        -------------

        Optional Output Fields
        ----------------------

        """
        if verbose > 2:
            print('[1] {} JOBREC PRE-PLANT (j@i) <<<'.format('DFTD3'))
            pp.pprint(jobrec)
            print('>>>')

        dftd3rec = dftd3_plant(jobrec)

        # test json roundtrip
        jdftd3rec = json.dumps(dftd3rec)
        dftd3rec = json.loads(jdftd3rec)

        if verbose > 3:
            print('[2] {}REC PRE-SUBPROCESS (m@i) <<<'.format('DFTD3'))
            pp.pprint(dftd3rec)
            print('>>>\n')

        dftd3_subprocess(dftd3rec)  # updates dftd3rec

        if verbose > 3:
            print('[3] {}REC POST-SUBPROCESS (m@io) <<<'.format('DFTD3'))
            pp.pprint(dftd3rec)
            print('>>>\n')

>       dftd3_harvest(jobrec, dftd3rec)  # updates jobrec

../lib/python3.6/site-packages/psi4/driver/qcdb/intf_dftd3/runner.py:183:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

jobrec = {'driver': 'gradient', 'error': "Dftd3Error('Unsuccessful run. Possibly -D variant not available in dftd3 version.',)"...a': [12, 12, 1, 1, 1, 1, ...], 'elem': ['C', 'C', 'H', 'H', 'H', 'H', ...], 'elez': [6, 6, 1, 1, 1, 1, ...], ...}, ...}
dftd3rec = {'command': ['dftd3', 'dftd3_geometry.xyz', '-grad'], 'dashlevel': 'd2', 'dashparams': {'alpha6': 20.0, 's6': 1.05, 'sr6': 1.1}, 'dashparams_citation': '', ...}

    def dftd3_harvest(jobrec, dftd3rec):
        """Process raw results from read-only `dftd3rec` into QCAspect
        fields in returned `jobrec`: jobrec@i, dftd3rec@io -> jobrec@io.

        Parameters
        ----------
        jobrec : dict
            Nested dictionary with input specifications for DFTD3 in generic
            QC terms.
        dftd3rec : dict
            Nested dictionary with input specification and output collection
            from DFTD3 in program-specific commands, files, & output capture.

        Returns
        -------
        jobrec : dict
            Nested dictionary with input specification and output collection
            from DFTD3 in generic QC terms.

        """
        try:
            jobrec['molecule']['real']
            jobrec['driver']
            jobrec['provenance']
            jobrec['options']['fctldash']
        except KeyError as err:
            raise KeyError('Required field ({}) missing from ({})'.format(str(err), list(jobrec.keys()))) from err

        try:
            dftd3rec['stdout']
        except KeyError as err:
            raise KeyError('Required field ({}) missing from ({})'.format(str(err), list(dftd3rec.keys()))) from err

        # amalgamate output
        text = dftd3rec['stdout']
        text += '\n  <<<  DFTD3 Results  >>>\n'

        for fl in ['dftd3_gradient']:
            field = 'output_' + fl.lower()
            if field in dftd3rec:
                text += '\n  DFTD3 scratch file {} has been read.\n'.format(fl)
                text += dftd3rec[field]

        # parse energy output (could go further and break into E6, E8, E10 and Cn coeff)
        real = np.array(jobrec['molecule']['real'])
        full_nat = real.shape[0]
        real_nat = np.sum(real)

        for ln in dftd3rec['stdout'].splitlines():
            if re.search('DFTD3 V', ln):
                version = ln.replace('DFTD3', '').replace('|', '').strip().lower()
            elif re.match(' Edisp /kcal,au', ln):
                ene = Decimal(ln.split()[3])
            elif re.match(' normal termination of dftd3', ln):
                break
        else:
            if not ((real_nat == 1) and (jobrec['driver'] == 'gradient')):
>               raise Dftd3Error('Unsuccessful run. Possibly -D variant not available in dftd3 version.')
E               psi4.driver.qcdb.exceptions.Dftd3Error: Unsuccessful run. Possibly -D variant not available in dftd3 version.

../lib/python3.6/site-packages/psi4/driver/qcdb/intf_dftd3/runner.py:301: Dftd3Error

The above exception was the direct cause of the following exception:

    @pytest.mark.smoke
    @using_dftd3
    def test_dftd3():
        """dftd3/energy"""
        #! Exercises the various DFT-D corrections, both through python directly and through c++

        ref_d2         = [-0.00390110, -0.00165271, -0.00058118]
        ref_d3zero     = [-0.00285088, -0.00084340, -0.00031923]
        ref_d3bj       = [-0.00784595, -0.00394347, -0.00226683]

        ref_pbe_d2     = [-0.00278650, -0.00118051, -0.00041513]
        ref_pbe_d3zero = [-0.00175474, -0.00045421, -0.00016839]
        ref_pbe_d3bj   = [-0.00475937, -0.00235265, -0.00131239]

        eneyne = psi4.geometry("""
        C   0.000000  -0.667578  -2.124659
        C   0.000000   0.667578  -2.124659
        H   0.923621  -1.232253  -2.126185
        H  -0.923621  -1.232253  -2.126185
        H  -0.923621   1.232253  -2.126185
        H   0.923621   1.232253  -2.126185
        --
        C   0.000000   0.000000   2.900503
        C   0.000000   0.000000   1.693240
        H   0.000000   0.000000   0.627352
        H   0.000000   0.000000   3.963929
        """)

        print('  -D correction from Py-side')
        eneyne.update_geometry()
>       E, G = eneyne.run_dftd3('b3lyp', 'd2')

../lib/python3.6/site-packages/psi4/tests/test_addons.py:202:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../lib/python3.6/site-packages/psi4/driver/qcdb/molecule.py:1298: in run_dftd3
    verbose=verbose)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

molrec = {'elbl': ['', '', '', '', '', '', ...], 'elea': [12, 12, 1, 1, 1, 1, ...], 'elem': ['C', 'C', 'H', 'H', 'H', 'H', ...], 'elez': [6, 6, 1, 1, 1, 1, ...], ...}
name_hint = 'b3lyp', level_hint = 'd2', param_tweaks = None, ptype = 'gradient', dashcoeff_supplement = None
verbose = 1

    def run_dftd3_from_arrays(molrec,
                              name_hint=None,
                              level_hint=None,
                              param_tweaks=None,
                              ptype='energy',
                              dashcoeff_supplement=None,
                              verbose=1):
        """Specialized signature disentangling dispersion level and
        parameters for computing on `molecule` with engine `DFTD3`. See
        `dashparam.from_array` for parameter details.

        """
        jobrec = {}
        jobrec['error'] = ''
        jobrec['success'] = None
        jobrec['return_output'] = True
        prov = {}
        prov['creator'] = 'QCDB'
        prov['version'] = __version__
        prov['routine'] = sys._getframe().f_code.co_name
        jobrec['provenance'] = prov

        # strip engine hint
        if name_hint.startswith('d3-'):
            name_hint = name_hint[3:]

        opts = {}
        opts['level_hint'] = level_hint
        opts['params_tweaks'] = param_tweaks
        opts['dashcoeff_supplement'] = dashcoeff_supplement

        jobrec['molecule'] = molrec
        jobrec['method'] = name_hint
        _, jobrec['driver'] = parse_dertype(ptype, max_derivative=1)
        jobrec['options'] = opts
        #jobrec['options'] = copy.deepcopy(options)

        try:
            dftd3_driver(jobrec)
        except Exception as err:
            jobrec['success'] = False
            jobrec['error'] += repr(err)
>           raise RuntimeError(err) from err
E           RuntimeError: Unsuccessful run. Possibly -D variant not available in dftd3 version.

../lib/python3.6/site-packages/psi4/driver/qcdb/intf_dftd3/runner.py:135: RuntimeError
------------------------------------------------- Captured stdout call -------------------------------------------------
  -D correction from Py-side

Dftd3Error: Unsuccessful run. Possibly -D variant not available in dftd3 version.


____________________________________________________ test_grimme_3c ____________________________________________________

molrec = {'elbl': ['', '', '', ''], 'elea': [12, 12, 1, 1], 'elem': ['C', 'C', 'H', 'H'], 'elez': [6, 6, 1, 1], ...}
name_hint = 'pbeh3c', level_hint = 'd3bj', param_tweaks = {'a1': 0.486, 'a2': 4.5, 's6': 1.0, 's8': 0.0}
ptype = 'energy'
dashcoeff_supplement = defaultdict(<function <lambda> at 0x7f5e8db768c8>, {'d2': defaultdict(<class 'dict'>, {'definitions': {'opbe-d2': {'ty...0093}, 'citation': '    M. K. Kesharwani, A. Karton, J.M. L. Martin, J. Chem. Theory Comput. 12, 444-454, 2016\n'}}})})
verbose = 1

    def run_dftd3_from_arrays(molrec,
                              name_hint=None,
                              level_hint=None,
                              param_tweaks=None,
                              ptype='energy',
                              dashcoeff_supplement=None,
                              verbose=1):
        """Specialized signature disentangling dispersion level and
        parameters for computing on `molecule` with engine `DFTD3`. See
        `dashparam.from_array` for parameter details.

        """
        jobrec = {}
        jobrec['error'] = ''
        jobrec['success'] = None
        jobrec['return_output'] = True
        prov = {}
        prov['creator'] = 'QCDB'
        prov['version'] = __version__
        prov['routine'] = sys._getframe().f_code.co_name
        jobrec['provenance'] = prov

        # strip engine hint
        if name_hint.startswith('d3-'):
            name_hint = name_hint[3:]

        opts = {}
        opts['level_hint'] = level_hint
        opts['params_tweaks'] = param_tweaks
        opts['dashcoeff_supplement'] = dashcoeff_supplement

        jobrec['molecule'] = molrec
        jobrec['method'] = name_hint
        _, jobrec['driver'] = parse_dertype(ptype, max_derivative=1)
        jobrec['options'] = opts
        #jobrec['options'] = copy.deepcopy(options)

        try:
>           dftd3_driver(jobrec)

../lib/python3.6/site-packages/psi4/driver/qcdb/intf_dftd3/runner.py:131:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

jobrec = {'driver': 'energy', 'error': "Dftd3Error('Unsuccessful run. Possibly -D variant not available in dftd3 version.',)", ...ule': {'elbl': ['', '', '', ''], 'elea': [12, 12, 1, 1], 'elem': ['C', 'C', 'H', 'H'], 'elez': [6, 6, 1, 1], ...}, ...}
verbose = 1

    def dftd3_driver(jobrec, verbose=1):
        """Drive the jobrec@i (input) -> dftd3rec@i -> dftd3rec@io -> jobrec@io (returned) process.

        Input Fields
        ------------

        Optional Input Fields
        ---------------------

        Output Fields
        -------------

        Optional Output Fields
        ----------------------

        """
        if verbose > 2:
            print('[1] {} JOBREC PRE-PLANT (j@i) <<<'.format('DFTD3'))
            pp.pprint(jobrec)
            print('>>>')

        dftd3rec = dftd3_plant(jobrec)

        # test json roundtrip
        jdftd3rec = json.dumps(dftd3rec)
        dftd3rec = json.loads(jdftd3rec)

        if verbose > 3:
            print('[2] {}REC PRE-SUBPROCESS (m@i) <<<'.format('DFTD3'))
            pp.pprint(dftd3rec)
            print('>>>\n')

        dftd3_subprocess(dftd3rec)  # updates dftd3rec

        if verbose > 3:
            print('[3] {}REC POST-SUBPROCESS (m@io) <<<'.format('DFTD3'))
            pp.pprint(dftd3rec)
            print('>>>\n')

>       dftd3_harvest(jobrec, dftd3rec)  # updates jobrec

../lib/python3.6/site-packages/psi4/driver/qcdb/intf_dftd3/runner.py:183:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

jobrec = {'driver': 'energy', 'error': "Dftd3Error('Unsuccessful run. Possibly -D variant not available in dftd3 version.',)", ...ule': {'elbl': ['', '', '', ''], 'elea': [12, 12, 1, 1], 'elem': ['C', 'C', 'H', 'H'], 'elez': [6, 6, 1, 1], ...}, ...}
dftd3rec = {'command': ['dftd3', 'dftd3_geometry.xyz'], 'dashlevel': 'd3bj', 'dashparams': {'a1': 0.486, 'a2': 4.5, 's6': 1.0, 's8': 0.0}, 'dashparams_citation': False, ...}

    def dftd3_harvest(jobrec, dftd3rec):
        """Process raw results from read-only `dftd3rec` into QCAspect
        fields in returned `jobrec`: jobrec@i, dftd3rec@io -> jobrec@io.

        Parameters
        ----------
        jobrec : dict
            Nested dictionary with input specifications for DFTD3 in generic
            QC terms.
        dftd3rec : dict
            Nested dictionary with input specification and output collection
            from DFTD3 in program-specific commands, files, & output capture.

        Returns
        -------
        jobrec : dict
            Nested dictionary with input specification and output collection
            from DFTD3 in generic QC terms.

        """
        try:
            jobrec['molecule']['real']
            jobrec['driver']
            jobrec['provenance']
            jobrec['options']['fctldash']
        except KeyError as err:
            raise KeyError('Required field ({}) missing from ({})'.format(str(err), list(jobrec.keys()))) from err

        try:
            dftd3rec['stdout']
        except KeyError as err:
            raise KeyError('Required field ({}) missing from ({})'.format(str(err), list(dftd3rec.keys()))) from err

        # amalgamate output
        text = dftd3rec['stdout']
        text += '\n  <<<  DFTD3 Results  >>>\n'

        for fl in ['dftd3_gradient']:
            field = 'output_' + fl.lower()
            if field in dftd3rec:
                text += '\n  DFTD3 scratch file {} has been read.\n'.format(fl)
                text += dftd3rec[field]

        # parse energy output (could go further and break into E6, E8, E10 and Cn coeff)
        real = np.array(jobrec['molecule']['real'])
        full_nat = real.shape[0]
        real_nat = np.sum(real)

        for ln in dftd3rec['stdout'].splitlines():
            if re.search('DFTD3 V', ln):
                version = ln.replace('DFTD3', '').replace('|', '').strip().lower()
            elif re.match(' Edisp /kcal,au', ln):
                ene = Decimal(ln.split()[3])
            elif re.match(' normal termination of dftd3', ln):
                break
        else:
            if not ((real_nat == 1) and (jobrec['driver'] == 'gradient')):
>               raise Dftd3Error('Unsuccessful run. Possibly -D variant not available in dftd3 version.')
E               psi4.driver.qcdb.exceptions.Dftd3Error: Unsuccessful run. Possibly -D variant not available in dftd3 version.

../lib/python3.6/site-packages/psi4/driver/qcdb/intf_dftd3/runner.py:301: Dftd3Error

The above exception was the direct cause of the following exception:

    @pytest.mark.smoke
    @using_dftd3
    @using_gcp
    def test_grimme_3c():

        s16di = psi4.geometry("""
        C   0.000000  -0.667578  -2.124659
        C   0.000000   0.667578  -2.124659
        H   0.923621  -1.232253  -2.126185
        H  -0.923621  -1.232253  -2.126185
        H  -0.923621   1.232253  -2.126185
        H   0.923621   1.232253  -2.126185
        --
        C   0.000000   0.000000   2.900503
        C   0.000000   0.000000   1.693240
        H   0.000000   0.000000   0.627352
        H   0.000000   0.000000   3.963929
        symmetry c1
        """)

>       ene = psi4.energy('pbeh3c', bsse_type='nocp')

../lib/python3.6/site-packages/psi4/tests/test_addons.py:830:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../lib/python3.6/site-packages/psi4/driver/driver.py:494: in energy
    return driver_nbody.nbody_gufunc(energy, name, ptype='energy', **kwargs)
../lib/python3.6/site-packages/psi4/driver/driver_nbody.py:266: in nbody_gufunc
    component_results = compute_nbody_components(func, method_string, metadata)
../lib/python3.6/site-packages/psi4/driver/driver_nbody.py:475: in compute_nbody_components
    ptype_dict[pair], wfn = func(method_string, molecule=current_mol, return_wfn=True, **kwargs)
../lib/python3.6/site-packages/psi4/driver/driver.py:556: in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
../lib/python3.6/site-packages/psi4/driver/procrouting/proc.py:2002: in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
../lib/python3.6/site-packages/psi4/driver/procrouting/proc.py:1351: in scf_helper
    disp_energy = scf_wfn._disp_functor.compute_energy(scf_wfn.molecule())
../lib/python3.6/site-packages/psi4/driver/procrouting/empirical_dispersion.py:195: in compute_energy
    verbose=1)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

molrec = {'elbl': ['', '', '', ''], 'elea': [12, 12, 1, 1], 'elem': ['C', 'C', 'H', 'H'], 'elez': [6, 6, 1, 1], ...}
name_hint = 'pbeh3c', level_hint = 'd3bj', param_tweaks = {'a1': 0.486, 'a2': 4.5, 's6': 1.0, 's8': 0.0}
ptype = 'energy'
dashcoeff_supplement = defaultdict(<function <lambda> at 0x7f5e8db768c8>, {'d2': defaultdict(<class 'dict'>, {'definitions': {'opbe-d2': {'ty...0093}, 'citation': '    M. K. Kesharwani, A. Karton, J.M. L. Martin, J. Chem. Theory Comput. 12, 444-454, 2016\n'}}})})
verbose = 1

    def run_dftd3_from_arrays(molrec,
                              name_hint=None,
                              level_hint=None,
                              param_tweaks=None,
                              ptype='energy',
                              dashcoeff_supplement=None,
                              verbose=1):
        """Specialized signature disentangling dispersion level and
        parameters for computing on `molecule` with engine `DFTD3`. See
        `dashparam.from_array` for parameter details.

        """
        jobrec = {}
        jobrec['error'] = ''
        jobrec['success'] = None
        jobrec['return_output'] = True
        prov = {}
        prov['creator'] = 'QCDB'
        prov['version'] = __version__
        prov['routine'] = sys._getframe().f_code.co_name
        jobrec['provenance'] = prov

        # strip engine hint
        if name_hint.startswith('d3-'):
            name_hint = name_hint[3:]

        opts = {}
        opts['level_hint'] = level_hint
        opts['params_tweaks'] = param_tweaks
        opts['dashcoeff_supplement'] = dashcoeff_supplement

        jobrec['molecule'] = molrec
        jobrec['method'] = name_hint
        _, jobrec['driver'] = parse_dertype(ptype, max_derivative=1)
        jobrec['options'] = opts
        #jobrec['options'] = copy.deepcopy(options)

        try:
            dftd3_driver(jobrec)
        except Exception as err:
            jobrec['success'] = False
            jobrec['error'] += repr(err)
>           raise RuntimeError(err) from err
E           RuntimeError: Unsuccessful run. Possibly -D variant not available in dftd3 version.

../lib/python3.6/site-packages/psi4/driver/qcdb/intf_dftd3/runner.py:135: RuntimeError
------------------------------------------------- Captured stdout call -------------------------------------------------

Dftd3Error: Unsuccessful run. Possibly -D variant not available in dftd3 version.


=============================================== short test summary info ================================================
SKIPPED [1] lib/python3.6/site-packages/psi4/tests/test_addons.py:99: Psi4 not detecting MRCC. Add `dmrcc` to envvar PSIPATH or PATH
SKIPPED [1] lib/python3.6/site-packages/psi4/tests/test_addons.py:633: Psi4 not compiled with erd. Rebuild with -DENABLE_erd
SKIPPED [1] lib/python3.6/site-packages/psi4/tests/test_addons.py:686: Psi4 not detecting CFOUR. Add `xcfour` to envvar PSIPATH or PATH
SKIPPED [1] lib/python3.6/site-packages/psi4/tests/test_addons.py:773: Psi4 not detecting plugin gpu_dfcc. Build plugin if necessary and add to envvar PYTHONPATH
SKIPPED [1] lib/python3.6/site-packages/psi4/tests/test_addons.py:923: Psi4 not detecting plugin snsmp2. Build plugin if necessary and add to envvar PYTHONPATH (or rebuild Psi with -DENABLE_snsmp2)

**Comment by loriab** [comment]
The warning is fine -- http://forum.psicode.org/t/numpy-ufunc-size-change-warning/1305?u=loriab .

The dftd3 error is curious. May be related to https://github.com/MolSSI/QCEngine/issues/45 . Can probe later (most everyone Psi4 is away at a conference next week).

Unless DFT-D3 was your target, you're installed, passing, and ready to run.

**Comment by loriab** [comment]
original issue resolved, and dftd3 issue covered by #1587, so closing
