### ISSUE TITLE
psi4 1.3 with dftd3-3.2.1 failed under Win10/WSL-Ubuntu18.04

### ISSUE THREAD

**Issue by chrinide** [psi4/psi4#1587]
Hi all,

I have installed psi4-1.3 in Win10/WSL-Ubuntu18.04 successfully, and when run 'psi4 --test', only _dftd3_ and _grimme_3c_ failed.

I have found that psi4-v1.3 integrated dftd3 shown error when run "dftd3"under WSl:

**_Segmentation fault (core dumped)_**

Then I rebuild _dftd3_ under WSL and use the newly build _dftd3_, then the  'psi4 --test' show all pass.

So, this is just a build-bug report.

**Comment by loriab** [comment]
> Then I rebuild dftd3 under WSL

You mean you go to https://github.com/loriab/dftd3, clone and compile and it works? (`make` or `cmake`?) Or you mean downloading the 3.2.0 tarball from Grimme and `make`ing it works?

In either case, thanks for the investigation. I must have done something in the conda package that disagrees with WSL. Will fix by v1.3.1.

**Comment by chrinide** [comment]
From Grimme and just 'make' it, then copy it.

**Comment by loriab** [comment]
Thanks. Then the culprit is either my separation of the 3-body ATM gradients or my cmake.

**Comment by loriab** [comment]
@chrinide, @patrashantigopal, @sjayellis, I've built a new dftd3 that fixed segfaults on a Linux system (whereas many linux systems were fine with the existing `3.2.1_<stuff>_0` dftd3 pkg). Would you `conda update dftd3 -c psi4/label/dev` to get the new executable (it'll be a `_0` to `_1`) update, try it, and report back success or still failing, please?

**Comment by chrinide** [comment]
@loriab I have just tried the new dftd3 , it is OK in WSl, thanks so much for your hard work.

**Comment by loriab** [comment]
Thanks very much for testing! The difference is that _0 was built as a static executable, whereas _1 links to some system libraries dynamically. I may publish a _2 that just adjusts the conda deps. Please report back if it ever breaks again. I'll rebuild `gcp`, too, since it possibly has the same trouble (though both dftd3 and gcp have been static binaries for years on conda).

**Comment by patrashantigopal** [comment]
Thank you for you kind help @

**Comment by patrashantigopal** [comment]
../lib/python3.6/site-packages/psi4/tests/test_addons.py::test_dftd3 PASSED
