### ISSUE TITLE
missing CBS parameters in doc

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#1593]
The auto-documentation of the `cbs` function is incomplete. At quick glance, everything below and including `:type scf_alpha: float` is not generated correctly.

**Comment by PeterKraus** [comment]
Noted.

**Comment by loriab** [comment]
Yes, good to know. The cbs docs are going to need some restructuring (along with nbody and find if) because there’s actually no cbs() func left in distributed driver after it turned into a class.
