### ISSUE TITLE
diatomic.anharmonicity() - numpy.linalg.LinAlgError: Array must not contain infs or NaNs

### ISSUE THREAD

**Issue by MartinBeseda** [psi4/psi4#1600]
I've installed `psi4` according to the [Quick install tutorial](http://www.psicode.org/psi4manual/1.3/conda.html#sec-quickconda) on Ubuntu 18.10.

I want to compute spectroscopic constants for vibrational levels of N2+, so I've written a following input:

```
memory 2GB 

molecule dinitrogen_cation {1 2
                            N1  
                            N2 N1 1
                            units angstrom
                            symmetry d2h}

r=[0.8, 0.85, 0.9, 0.95, 1.0, 1.05, 1.1, 1.15, 1.2, 1.25, 1.3, 1.35, 1.4, 1.45, 1.5, 1.55, 1.6, 1.65, 1.7, 1.75, 1.8, 1.85, 1.9, 1.95, 2.0, 2.05, 2.1, 2.15, 2.2, 2.25, 2.3, 2.4, 2.45, 
2.5, 2.55, 2.6, 2.65, 2.7, 2.75, 2.8, 2.85, 2.9, 2.95, 3.0, 3.05, 3.1, 3.15, 3.2, 3.25, 3.3, 3.35, 3.4, 3.45, 3.5, 3.55, 3.6, 3.65, 3.7, 3.75, 3.8, 3.85, 3.9, 3.95, 4.0, 4.05, 4.1, 
4.15, 4.2, 4.25, 4.3, 4.35, 4.4, 4.45, 4.5, 4.55, 4.6, 4.65, 4.7, 4.75, 4.8, 4.85, 4.9, 4.95, 5.0, 30.0]

eng=[-108.20769157984833, -108.40283941756965, -108.5304405614308, -108.60907987217198, -108.65255814638125, -108.67615436957043, -108.67796355601384, -108.6687799248285, 
-108.6529295435983, -108.63448928177459, -108.61710861201114, -108.60250322145204, -108.59095590797817, -108.5816692775646, -108.57377233673783, -108.56672198956738, 
-108.56024733808314, -108.55422338322172, -108.54858992543426, -108.54332586487885, -108.53838700188666, -108.53376273653713, -108.52943746894715, -108.52539739922014, 
-108.5216299274505, -108.5181229537289, -108.51486517814001, -108.51184580076476, -108.50905562167209, -108.50648624092493, -108.504130358578, -108.50003198928782, -108.4982747024555, 
-108.49670061425044, -108.49529952474904, -108.49406023403529, -108.49297114219605, -108.49202014932202, -108.4911954555016, -108.49048556082097, -108.48987916536481, 
-108.48936536921477, -108.48893387244806, -108.4885456753569, -108.48825797751267, -108.48802517925705, -108.48783928065005, -108.48769318174477, -108.48758038259001, 
-108.48749538322693, -108.48743328369225, -108.48738988401745, -108.4873615842295, -108.4873453843509, -108.48733858440185, -108.48733918439734, -108.48734528435165, -108.487544082862,
-108.4875574827616, -108.48757248264921, -108.48758858252856, -108.48760498240567, -108.48762118228429, -108.48763708216514, -108.48765208205275, -108.4876661819471, 
-108.48767918184969, -108.48769108176053, -108.4877016816811, -108.48771108161066, -108.48771918154995, -108.48772618149751, -108.48773188145479, -108.48773658141958, 
-108.48774018139261, -108.48774268137387, -108.48774438136114, -108.48774518135515, -108.48774518135515, -108.48774438136114, -108.48774298137162, -108.48774098138661, 
-108.48773838140609, -108.48773538142858, -108.48720108543215]

psi4.diatomic.anharmonicity(r,eng,'result.out')
```

But when I run it with Psi4, I'm getting the following error:
```
m1: 14.00307400443, m2: 14.00307400443
d2: -0.02414940264774275, mu: 1.1626325532182573e-26
invalid value encountered in sqrt
invalid value encountered in sqrt
Traceback (most recent call last):
  File "/home/martin/miniconda/bin/psi4", line 287, in <module>
    exec(content)
  File "<string>", line 41, in <module>
  File "/home/martin/miniconda/lib//python3.7/site-packages/psi4/driver/diatomic.py", line 194, in anharmonicity
    roots2 = np.roots(coefs2)
  File "/home/martin/miniconda/lib//python3.7/site-packages/numpy/lib/polynomial.py", line 245, in roots
    roots = eigvals(A)
  File "/home/martin/miniconda/lib//python3.7/site-packages/numpy/linalg/linalg.py", line 1059, in eigvals
    _assertFinite(a)
  File "/home/martin/miniconda/lib//python3.7/site-packages/numpy/linalg/linalg.py", line 219, in _assertFinite
    raise LinAlgError("Array must not contain infs or NaNs")

numpy.linalg.LinAlgError: Array must not contain infs or NaNs

Printing out the relevant lines from the Psithon --> Python processed input file:
    -108.48749538322693, -108.48743328369225, -108.48738988401745, -108.4873615842295, -108.4873453843509, -108.48733858440185, -108.48733918439734, -108.48734528435165, -108.487544082862,
    -108.4875574827616, -108.48757248264921, -108.48758858252856, -108.48760498240567, -108.48762118228429, -108.48763708216514, -108.48765208205275, -108.4876661819471, 
    -108.48767918184969, -108.48769108176053, -108.4877016816811, -108.48771108161066, -108.48771918154995, -108.48772618149751, -108.48773188145479, -108.48773658141958, 
    -108.48774018139261, -108.48774268137387, -108.48774438136114, -108.48774518135515, -108.48774518135515, -108.48774438136114, -108.48774298137162, -108.48774098138661, 
    -108.48773838140609, -108.48773538142858, -108.48720108543215]
--> psi4.diatomic.anharmonicity(r,eng,'result.out')
```

where I've added printing of first two lines to help me with debugging.

I believe, that the problem occurs in the line `138` of `diatomic.py`, i.e. on the line
```
we = 5.3088375e-11 * np.sqrt(d2/mu)
```

where, as we can see, is `d2/mu`, which is considered a `nan` by `numpy.sqrt()` function. I've tried it separately from Psi4 and its exhibiting the same behavior. 

```
>>> numpy.sqrt(-0.02414940264774275 / 1.1626325532182573e-26)
__main__:1: RuntimeWarning: invalid value encountered in sqrt
nan
```

Is there anything, that can be done to prevent this problem?

---

### My software versions:

* Ubuntu 18.10
* Psi4 1.3
* Python 3.7.3
* Numpy 1.16.2

---

### Full output file

```

    -----------------------------------------------------------------------
          Psi4: An Open-Source Ab Initio Electronic Structure Package
                               Psi4 1.3 release

                         Git: Rev {HEAD} 20e5c7e 


    R. M. Parrish, L. A. Burns, D. G. A. Smith, A. C. Simmonett,
    A. E. DePrince III, E. G. Hohenstein, U. Bozkaya, A. Yu. Sokolov,
    R. Di Remigio, R. M. Richard, J. F. Gonthier, A. M. James,
    H. R. McAlexander, A. Kumar, M. Saitow, X. Wang, B. P. Pritchard,
    P. Verma, H. F. Schaefer III, K. Patkowski, R. A. King, E. F. Valeev,
    F. A. Evangelista, J. M. Turney, T. D. Crawford, and C. D. Sherrill,
    J. Chem. Theory Comput. 13(7) pp 3185--3197 (2017).
    (doi: 10.1021/acs.jctc.7b00174)


                         Additional Contributions by
    P. Kraus, H. Kruse, M. H. Lechner, M. C. Schieber, R. A. Shaw,
    A. Alenaizan, R. Galvelis, Z. L. Glick, S. Lehtola, and J. P. Misiewicz

    -----------------------------------------------------------------------


    Psi4 started on: Sunday, 14 April 2019 03:29PM

    Process ID: 6064
    Host:       martin-pc
    PSIDATADIR: /home/martin/miniconda/share/psi4
    Memory:     500.0 MiB
    Threads:    1
    
  ==> Input File <==

--------------------------------------------------------------------------
#import numpy as np
#np.seterr(invalid="raise")

memory 2GB

molecule dinitrogen_cation {1 2
                            N1
                            N2 N1 1
                            units angstrom
                            symmetry d2h}

r=[0.8, 0.85, 0.9, 0.95, 1.0, 1.05, 1.1, 1.15, 1.2, 1.25, 1.3, 1.35, 1.4, 1.45, 1.5, 1.55, 1.6, 1.65, 1.7, 1.75, 1.8, 1.85, 1.9, 1.95, 2.0, 2.05, 2.1, 2.15, 2.2, 2.25, 2.3, 2.4, 2.45, 
2.5, 2.55, 2.6, 2.65, 2.7, 2.75, 2.8, 2.85, 2.9, 2.95, 3.0, 3.05, 3.1, 3.15, 3.2, 3.25, 3.3, 3.35, 3.4, 3.45, 3.5, 3.55, 3.6, 3.65, 3.7, 3.75, 3.8, 3.85, 3.9, 3.95, 4.0, 4.05, 4.1, 
4.15, 4.2, 4.25, 4.3, 4.35, 4.4, 4.45, 4.5, 4.55, 4.6, 4.65, 4.7, 4.75, 4.8, 4.85, 4.9, 4.95, 5.0, 30.0]

eng=[-108.20769157984833, -108.40283941756965, -108.5304405614308, -108.60907987217198, -108.65255814638125, -108.67615436957043, -108.67796355601384, -108.6687799248285, 
-108.6529295435983, -108.63448928177459, -108.61710861201114, -108.60250322145204, -108.59095590797817, -108.5816692775646, -108.57377233673783, -108.56672198956738, 
-108.56024733808314, -108.55422338322172, -108.54858992543426, -108.54332586487885, -108.53838700188666, -108.53376273653713, -108.52943746894715, -108.52539739922014, 
-108.5216299274505, -108.5181229537289, -108.51486517814001, -108.51184580076476, -108.50905562167209, -108.50648624092493, -108.504130358578, -108.50003198928782, -108.4982747024555, 
-108.49670061425044, -108.49529952474904, -108.49406023403529, -108.49297114219605, -108.49202014932202, -108.4911954555016, -108.49048556082097, -108.48987916536481, 
-108.48936536921477, -108.48893387244806, -108.4885456753569, -108.48825797751267, -108.48802517925705, -108.48783928065005, -108.48769318174477, -108.48758038259001, 
-108.48749538322693, -108.48743328369225, -108.48738988401745, -108.4873615842295, -108.4873453843509, -108.48733858440185, -108.48733918439734, -108.48734528435165, -108.487544082862,
-108.4875574827616, -108.48757248264921, -108.48758858252856, -108.48760498240567, -108.48762118228429, -108.48763708216514, -108.48765208205275, -108.4876661819471, 
-108.48767918184969, -108.48769108176053, -108.4877016816811, -108.48771108161066, -108.48771918154995, -108.48772618149751, -108.48773188145479, -108.48773658141958, 
-108.48774018139261, -108.48774268137387, -108.48774438136114, -108.48774518135515, -108.48774518135515, -108.48774438136114, -108.48774298137162, -108.48774098138661, 
-108.48773838140609, -108.48773538142858, -108.48720108543215]

psi4.diatomic.anharmonicity(r,eng,'result.out')
--------------------------------------------------------------------------

  Memory set to   1.863 GiB by Python driver.


Performing a fit to 85 data points

Optimizing geometry based on current surface:

       E =  -108.48763191189867, x =      3.2252941, grad =     0.00224788400003
       E =  -108.48738990806602, x =      3.3996397, grad =     0.00068618041148
       E =  -108.48734508016932, x =      3.4996883, grad =     0.00016321285348
       E =  -108.48733918433076, x =      3.5300091, grad =     0.00004224053808
       E =  -108.48733835624454, x =      3.5376957, grad =    -0.00000455763475
       E =  -108.48733841386600, x =      3.5368732, grad =     0.00000047690618
       E =  -108.48733840748675, x =      3.5369593, grad =    -0.00000005153221
       E =  -108.48733840817202, x =      3.5369500, grad =     0.00000000555231
       E =  -108.48733840809817, x =      3.5369510, grad =    -0.00000000059873
 Final E =  -108.48733840809817, x =      3.5369510, grad =    -0.00000000059873

Equilibrium Energy  -108.48733840809817 Hartrees
Gradient              -0.00000000059873
Quadratic Force Constant     -0.0241494 MDYNE/A
Cubic Force Constant          0.0817885 MDYNE/A**2
Quartic Force Constant       -0.1482087 MDYNE/A**3

Traceback (most recent call last):
  File "/home/martin/miniconda/bin/psi4", line 287, in <module>
    exec(content)
  File "<string>", line 41, in <module>
  File "/home/martin/miniconda/lib//python3.7/site-packages/psi4/driver/diatomic.py", line 194, in anharmonicity
    roots2 = np.roots(coefs2)
  File "/home/martin/miniconda/lib//python3.7/site-packages/numpy/lib/polynomial.py", line 245, in roots
    roots = eigvals(A)
  File "/home/martin/miniconda/lib//python3.7/site-packages/numpy/linalg/linalg.py", line 1059, in eigvals
    _assertFinite(a)
  File "/home/martin/miniconda/lib//python3.7/site-packages/numpy/linalg/linalg.py", line 219, in _assertFinite
    raise LinAlgError("Array must not contain infs or NaNs")

numpy.linalg.LinAlgError: Array must not contain infs or NaNs


Printing out the relevant lines from the Psithon --> Python processed input file:
    -108.48749538322693, -108.48743328369225, -108.48738988401745, -108.4873615842295, -108.4873453843509, -108.48733858440185, -108.48733918439734, -108.48734528435165, -108.487544082862,
    -108.4875574827616, -108.48757248264921, -108.48758858252856, -108.48760498240567, -108.48762118228429, -108.48763708216514, -108.48765208205275, -108.4876661819471, 
    -108.48767918184969, -108.48769108176053, -108.4877016816811, -108.48771108161066, -108.48771918154995, -108.48772618149751, -108.48773188145479, -108.48773658141958, 
    -108.48774018139261, -108.48774268137387, -108.48774438136114, -108.48774518135515, -108.48774518135515, -108.48774438136114, -108.48774298137162, -108.48774098138661, 
    -108.48773838140609, -108.48773538142858, -108.48720108543215]
--> psi4.diatomic.anharmonicity(r,eng,'result.out')

    Psi4 stopped on: Sunday, 14 April 2019 03:29PM
    Psi4 wall time for execution: 0:00:00.26

*** Psi4 encountered an error. Buy a developer more coffee!
*** Resources and help at github.com/psi4/psi4.

```

**Comment by PeterKraus** [comment]
I had a quick look at this, and it looks like the `least_squares_fit_polynomial()` function behaves a little dodgy on the first iteration -  the minimum of your supplied potential is clearly the 1.1\AA value, while on the first iteration the solver settles on 3.2\AA and keeps increasing.

The 30\AA point seems to be throwing the solver off, as the initial guess is taken as mean(r). To get a quick fix, try to remove it - it seems to work fine on my computer without that one. 

What also seems to work is to switch off weighting for the first iteration of calculating the derivatives - then it doesn't care about the far away point. It's perhaps better to hear from @andysim whether that's sensible or not.

**Comment by MartinBeseda** [comment]
@PeterKraus Thank you for your response! I tried to remove the value at 30A, but it doesn't work for me - the problem persists. Maybe it would be worth to implement parameter allowing user to specify an initial guess, or another methods to get it (median, mode etc.). Also, I've tried to run `least_squares_fit_polynomial()` with `weighted=False` parameter in the first iteration and it seems to compute something, but the result is really off as can be seen in the attached PDF.

[result.pdf](https://github.com/psi4/psi4/files/3077686/result.pdf)

**Comment by PeterKraus** [comment]
If you can change line [109 of diatomic.py](https://github.com/psi4/psi4/blob/73351f5444a46f6f2e87414ecddb1874817dabc8/psi4/driver/diatomic.py#L109) to:
`re = rvals[energies.index(np.min(energies))]`
that should work. It basically starts with r_e as the minimum of the provided potential. I'll have to have a look in the paper at why `np.mean(rvals)` was used instead...

**Comment by loriab** [comment]
For the anharmonicity fn, you may want to try more tightly spaced points just around the min. We often use 5 points and keep adjusting so one nearly at the min.

**Comment by MartinBeseda** [comment]
@PeterKraus Then I have problems with plotting the result:

```
roots2: [ 0.04389819 -0.04389819], roots4: [ 1.02159374  0.65293396  0.04649873 -0.04163826]
xvals2: [1.12745735 1.03966097]
xvals4: [2.1051529  1.73649312 1.13005789 1.0419209 ]
Eharm: -108.67334599996312
Evpt2:-108.67337188814578
Traceback (most recent call last):
  File "/home/martin/miniconda/bin/psi4", line 287, in <module>
    exec(content)
  File "<string>", line 42, in <module>
  File "/home/martin/miniconda/lib//python3.7/site-packages/psi4/driver/diatomic.py", line 221, in anharmonicity
    plt.plot(xvals4, [Evpt2, Evpt2], 'g', linewidth=1)
  File "/home/martin/miniconda/lib//python3.7/site-packages/matplotlib/pyplot.py", line 2811, in plot
    is not None else {}), **kwargs)
  File "/home/martin/miniconda/lib//python3.7/site-packages/matplotlib/__init__.py", line 1810, in inner
    return func(ax, *args, **kwargs)
  File "/home/martin/miniconda/lib//python3.7/site-packages/matplotlib/axes/_axes.py", line 1611, in plot
    for line in self._get_lines(*args, **kwargs):
  File "/home/martin/miniconda/lib//python3.7/site-packages/matplotlib/axes/_base.py", line 393, in _grab_next_args
    yield from self._plot_args(this, kwargs)
  File "/home/martin/miniconda/lib//python3.7/site-packages/matplotlib/axes/_base.py", line 370, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "/home/martin/miniconda/lib//python3.7/site-packages/matplotlib/axes/_base.py", line 231, in _xy_from_xy
    "have shapes {} and {}".format(x.shape, y.shape))

ValueError: x and y must have same first dimension, but have shapes (4,) and (2,)

```

**Comment by MartinBeseda** [comment]
@loriab I'll try to do it, but, as we can see, the grid is already computed with 0.05A step - that should be enough for an efficient interpolation, in my opinion.

**Comment by loriab** [comment]
0.05A is definitely sensible for an interpolation of the whole potential energy curve. But for this function, what you want is a region that looks essentially harmonic so that the function can pick out the anharmonicity. Recently, I used 0.005A.

**Comment by MartinBeseda** [comment]
@loriab Well, in what interval would you compute such a dense grid? +-0.2A from the minimum?

**Comment by loriab** [comment]
5 or 7 or 9 pts with 0.005A spacing, so approx [-0.02 + r_e, +0.02 + r_e]

**Comment by andysim** [comment]
Sorry for being late on this one - I've been doing taxes all day :(  The original error comes from a negative argument to the sqrt function, which is very suspicious.  It implies that the surface has strange curvature at that point, likely a) due to numerical noise or b) due to the method of choice not being able to globally describe the surface.  The first of these is usually to blame - you need *very* tightly converged energies when trying to get higher order derivatives (I'd say 12 digits after the decimal, so make sure all densities / residuals of your method of choice are tightly converged).  Very few methods can describe a full dissociation curve, and the very wide range of r values that you're using means that there's potential to probe some bond lengths that are problematic, which could lead to strange behavior like what was observed.

I think @loriab is right - keeping the points close to the minimum is much safer.  The cubic and quartic force constants that you get from the analysis are derivatives taken *at* the minimum, so points far away are not needed.  Moreover, the default behavior is to weight the points in the fit by distance from the minimum, so only those nearby will contribute appreciably.

I added that code to get rid of some very messy Lagrangian interpolation code that was used before.  The previous code used 5 or 9 points spaced around the minimum, and similar amounts of data were successful for my testing.  I think 0.05A might be ok as long as the points chosen bracket the minimum.  I'd recommend some testing of this - if you take a really cheap method and try different spacings, you should see a plateau in the results w.r.t. grid spacing; too small a spacing is susceptible to roundoff error, while large spacing pushes the definition of 'finite' in finite differences, but the plateau in between defines the optimal region.  When I tested on H2 (in the psithon1 test case, by the way) I found that it was quite insensitive to the grid size, but I was also using tightly converged full CI so there were no problems with the underlying potential.  Good luck!

**Comment by PeterKraus** [comment]
@andysim the potential provided by @MartinBeseda (see figure) has a slight dip at around 4.50 angstrom, and the mean of the provided radii puts it around 3.5 there. That's my take on this.
![issue-1600](https://user-images.githubusercontent.com/5336995/56111506-82ef6a80-5f58-11e9-8435-3803035cb374.png)

As for the plotting issue - I wouldn't know, as I didn't install matplotlib into that environment. I can have a look later, but it is confusing that it wouldn't work, when it calculates all spectroscopic constants properly.

**Comment by loriab** [comment]
By the way, the posted graphs are covering the bond-breaking region, not the equilibrium bond length. And the method isn't mentioned, but any single-ref method isn't going to break a triple bond sensibly. 

May be useful to have the fn check its assumption that the mean of the displacements is somewhere near the equilibrium bond length  https://github.com/psi4/psi4/blob/master/psi4/driver/diatomic.py#L109

**Comment by andysim** [comment]
@PeterKraus's suggestion of using the index of the minimum is way smarter than my use of np.mean.  At the time of writing the code I was considering only the case where there are a handful of points distributed somewhat evenly around the true minimum, which is not the case here at all.  With the weighting function and that guess used, the original data *might* work here, because all the noise in the bond breaking region will be filtered out to some extent.

**Comment by MartinBeseda** [comment]
@loriab @PeterKraus @andysim Thank you all for valuable advice!

I've computed 9 points as @loriab suggested:
```
r=[1.08, 1.085, 1.09, 1.095, 1.1, 1.105, 1.11, 1.115, 1.12]
eng=[-108.679699, -108.679654, -108.6794818, -108.679188, -108.6787779, -108.6782569, -108.6776548, -108.6769276, -108.6761047]
```

Fit now looks much better, as can be seen in the file [fit.pdf](https://github.com/psi4/psi4/files/3082472/fit.pdf). The results:
```
Equilibrium Energy  -108.67970105590722 Hartrees
Gradient               0.00000000002038
Quadratic Force Constant     24.8569214 MDYNE/A
Cubic Force Constant       -505.1574283 MDYNE/A**2
Quartic Force Constant    17972.8369840 MDYNE/A**3

re     =   1.080957 A  check:   1.080957
r0       =   1.089667 A
we       =  2454.7194 cm-1
wexe     =   -10.4449 cm-1
nu       =  2475.6093 cm-1
ZPVE(nu) =  1229.9709 cm-1
Be       =     2.0606 cm-1
B0       =     2.0278 cm-1
ae       =     0.0656 cm-1
De       =  0.0000058 cm-1
```

seem quite good, except `wexe`, `ae` and `De`. Let's take [this paper](https://www.researchgate.net/publication/257738988_Spectroscopic_constants_and_molecular_properties_of_X2Sg_A2Pu_B2Su_and_D2Pg_electronic_states_of_the_N2_ion) as a reference, or let's see a summary of their results compared with results from other publications
![header](https://user-images.githubusercontent.com/8162544/56172997-1b82fa80-5fec-11e9-970f-cc318f6e422d.png)
![sigmau+_reference](https://user-images.githubusercontent.com/8162544/56172944-fa220e80-5feb-11e9-9dc1-48b50ab25730.png)

Apart from `wexe` and `ae`, which are clearly different from the results of the paper, `De` has a value of `0.0000058 cm-1 = 7.1910832e-10 eV`, which is significantly different from the reference results.

What am I missing now?

And thank you for your help once more!

**Comment by andysim** [comment]
I think you need some more data for shorter bond lengths for one; your computed `re` is right at the bottom end of the input values.  I'd also recommend testing to see how sensitive the results are to the grid spacing.

**Comment by MartinBeseda** [comment]
@andysim Well, I've tried to add more points with the same 0.005A step. 

Results are as following:
```
Equilibrium Energy  -108.68016248232071 Hartrees
Gradient              -0.00000000054148
Quadratic Force Constant     23.1018206 MDYNE/A
Cubic Force Constant       -201.1767529 MDYNE/A**2
Quartic Force Constant      945.5330232 MDYNE/A**3

re     =   1.080176 A  check:   1.080176
r0       =   1.083206 A
we       =  2366.4716 cm-1
wexe     =    25.7210 cm-1
nu       =  2315.0297 cm-1
ZPVE(nu) =  1176.8056 cm-1
Be       =     2.0635 cm-1
B0       =     2.0520 cm-1
ae       =     0.0231 cm-1
De       =  0.0000063 cm-1
```
And [fit.pdf](https://github.com/psi4/psi4/files/3082699/fit.pdf) looks really well. The only value which looks really off is `De`. Is it really computed in `cm-1`?

**Comment by PeterKraus** [comment]
Should be in `cm-1`:
https://github.com/psi4/psi4/blob/73351f5444a46f6f2e87414ecddb1874817dabc8/psi4/driver/diatomic.py#L146
where `de` is De, `we` is we, and `B` is Be...

**Comment by PeterKraus** [comment]
Oh I got it now. The `De`'s in the paper are binding / dissociation energies, the `De` calculated here is the harmonic centrifugal distortion constant. Obviously. Can we switch to an alphabet with 50 letters?

**Comment by MartinBeseda** [comment]
@PeterKraus Thank you! That explains it. So, one last question - is it possible to get the dissociation energy somehow?

**Comment by PeterKraus** [comment]
Yes, one way is to compare your energies at the minimum (r_e) from the dissociated energy (eg. the 30 angstrom value) and correct by adding zero point energy:
```
De = E(30A) - E(r_e) + ZPE
```
Another way is to do a counterpoise-corrected calculation, which due to the charges is a little more tricky to set up:
```
mol = psi4.core.Molecule.from_arrays(
    elez=[7, 7],
    fragment_separators=[1],
    fix_com=True,
    fix_orientation=True,
    fix_symmetry='c1',
    fragment_multiplicities=[2, 1],
    fragment_charges=[0, 1],
    molecular_charge=1,
    molecular_multiplicity=2,
    geom= [
       0.000, 0.000, 0.000000,
       0.000, 0.000, 1.080176])
activate(mol)

...
set reference uks
energy("method/basis", bsse_type="cp")
```
where 1.080176 is the `re` from above, and i'm using UKS assuming it's a DFT calc (for wavefunction theory the alternative is UHF). The other text is pretty self-explanatory. You still have to correct the resulting interaction energy by the ZPE of N2+, though.

**Comment by MartinBeseda** [comment]
@PeterKraus Thank you once again!
@loriab @andysim Also thank you for your help.

**Comment by PeterKraus** [comment]
Happy to help. I'll reopen this issue as I believe there is a a todo item:

The `np.mean(rvals)` is probably not the best idea as a first guess of `r_e` for the fit. We should probably find the minimum of energy along the `rvals`, and then look at how symmetrically the points are distributed around it: I'd suggest if we have less than 3 points at either side of the minimum, we raise a warning. We could also rise the minimum number of points to 7...

**Comment by MartinBeseda** [comment]
@PeterKraus And, as I'm looking at it now, it would be also nice to have an equilibrium energy in the returned dictionary.

**Comment by andysim** [comment]
I agree with all of the above, especially a sanity check on the number of points provided and the use of the minimum as a guess.  One very minor correction: the "bottom of the well" dissociation energy `De` is the difference between the minimized energy and the dissociated products.  The zero-point corrected value (which is what's really measured in experiments, because the molecule cannot reach the bottom of the well), is `D0` and comes from subtracting the `ZPVE(nu)` value reported in the dictionary from `De`.  For the record, that ZPVE is `0.5 we - 0.25 wexe`.

**Comment by JonathonMisiewicz** [comment]
Now that #1601 is merged, does this still need to be open?

**Comment by loriab** [comment]
Still more docs coming soon!
