### ISSUE TITLE
Supplying Basis Set as Method String Breaks FNOCC

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#1604]
Carrying forward from [the forums](http://forum.psicode.org/t/problem-when-passing-a-reference-wavefunction-to-df-ccsd-in-the-fnocc-module/1346). 

The following input file leads to a PSIO error:
```
molecule {
O
H 1 r
H 1 r 2 a

r=0.958
a=104.5

symmetry c1
}

set scf_type df
set cc_type df
set df_ints_io save
eng, wfn = psi4.energy('hf/cc-pvdz', return_wfn=True)
cc_eng = psi4.energy('ccsd/cc-pvdz', ref_wfn=wfn)
```

The following workaround input file runs fine:
```
molecule {
O
H 1
H 1 r 2 a
r=0.958
a=104.5
symmetry c1
}

set basis cc-pvdz
set scf_type df
set cc_type df
set df_ints_io save
eng, wfn = psi4.energy(‘hf’, return_wfn=True)
cc_eng = psi4.energy(‘ccsd’, ref_wfn=wfn)
```

Still, it would be good to figure out what is differing between these two cases.

**Comment by maxscheurer** [comment]
I've just hit this issue when running TDSCF, so it seems to be a more general problem...
When specifying the basis set separately, Psi4 runs fine, however...

**Comment by loriab** [comment]
Something like this was also reported last summer where the t2 amplitude return was all zeros if string basis. I couldn't track it down in quarter hour. Thanks for harvesting report.

**Comment by maxscheurer** [comment]
Me neither... though the issue feels awkward enough that it should be somehow addressed. In the TDSCF case, it happens only for "larger" molecules... (Methyloxirane example from PsiCon 2020 notebook works fine).

**Comment by JonathonMisiewicz** [comment]
Were you using DF integrals? When I run the `fnocc` example, I get:
```
PSIO_ERROR: Can't find TOC Entry (Q|mn) Integrals
PSIO_ERROR: unit = 97, errval = 13
```

...Which suggests that "how do DF integrals get to where the module expects?" is the question to ask. I can't commit the time to further investigation, unfortunately.

**Comment by maxscheurer** [comment]
Indeed, that's the question to ask 😄 
Varying `scf_type`, I only get failures for `disk_df` (`mem_df` and `pk` are fine).

**Comment by maxscheurer** [comment]
Before anyone else tries to track down what's going on: I've found the "problem", working on a sustainable fix with @loriab 😬
