### ISSUE TITLE
A bug in molden() function

### ISSUE THREAD

**Issue by yingxingcheng** [psi4/psi4#1647]
Hi,

There is a bug in `psi4.driver.molden()` function. https://github.com/psi4/psi4/blob/bff32c9b580034941289fa2bcd9bf188652d6e6c/psi4/driver/driver.py#L1809
The fourth and fifth arguments should be energies, e.g., `wfn.epsilon_a()`, `wfn.epsilon_b()` respectively.

**Comment by loriab** [comment]
I agreed with you at first, but upon further investigation, I think this is following the tradition of the Cfour `MOLDEN_NAT` file, where for post-HF when orbital energies aren't defined, the `Ene` duplicates the `Occup`:

```
 83       -0.0035499996
 84       -0.0080147460
 85        0.0164654617
 86        0.0034089720
 Sym= A
 Ene=   1.96554366353590
 Spin= Alpha
 Occup=   1.96554366353590
  1        0.0000000000
  2        0.0000000000
  3        0.0000000000
  4        0.0000000000
```

When density isn't present, the expected `mw.write()` call happens: https://github.com/psi4/psi4/blame/master/psi4/driver/driver.py#L1822 Does this address your concern?

**Comment by yingxingcheng** [comment]
Thank you for the fast reply! 

Yes! I understood. Previously, I thought when one specifies `density_a` without `density_b` e.g., in a ROHF calculation with CISD, and this function will write orbital information only involving spin up.  It is therefore that results look like weird, and after checking the source code, I finally find that the results include the information of all electrons though `density_b` take a default value `None`.
