### ISSUE TITLE
No package for 1.3.2 for WSL

### ISSUE THREAD

**Issue by nseifert** [psi4/psi4#1658]
Not a major issue per-say since I currently run Psi4 on a Linux system, but I wanted to try it on WSL for fun. However, I kept getting curl 404s when I went to download 1.3.2. It turns out there are currently no binaries for 1.3.2 on the [download page](https://admiring-tesla-08529a.netlify.com/installs/v132/) for WSL. 

Not sure if this version is broken on WSL or it's just been overlooked, figure you'd like to know!

**Comment by loriab** [comment]
Sorry about that!

Now fixed, and thanks for the notice.
