### ISSUE TITLE
DiskDFJK::memory_estimate() doesn't catch coefficient matrices.

### ISSUE THREAD

**Issue by obrien951** [psi4/psi4#1660]
`DiskDFJK::memory_estimate()` keeps track of the three index integrals and the coulomb metric  (line 78-80 of `DiskDFJK.cc`,) but there's a problem when it tries to keep track of the density and coefficient matrices. To do this, `DiskDFJK::memory_estimate()` calls `JK::memory_overhead()` which counts up the sizes of all the matrices in the `JK::C_left()` vector. 

The trouble is that when `memory_estimate()` is called, `JK::C_left()` is empty, so `DiskDFJK::memory_estimate()` misses these matrices because `JK::memory_overhead()` does a `for` loop over `JK::C_left().size()`. In the meantime, `JK::C_left()` doesn't get filled until `HF::form_G()`, so when `DiskDFJK::memory_estimate()` gets called, there are not vector elements to loop over.

**Comment by dgasmith** [comment]
This usually fall in our memory overhead buffers (our safety margins of 20%). Can just assume nbf x nbf, the size is trivial enough to elide any possible space saving in general.

**Comment by dgasmith** [comment]
@obrien951 In general, the above catches these kinds of estimations. Do you have further changes you wish to make here?
