### ISSUE TITLE
Bug in the E(30)ind SAPT correction?

### ISSUE THREAD

**Issue by konpat** [psi4/psi4#1677]
While testing out some enhancements to third-order SAPT, Jonathan Waldrop and I seem to have found a bug in the E(30)ind implementation in psi4/psi4/src/psi4/libsapt_solver/ind30.cc.

The E(30)ind correction is given by Eq. (72) of JCP 125, 154107 (2006), which stems from evaluating the matrix elements in Eq. (75) using the second-order induction amplitudes in Eq. (79). Psi4 proceeds slightly differently, by actually evaluating the induction amplitudes from Eq. (79) (as far as I can see, the code in psi4/psi4/src/psi4/libsapt_solver/amplitudes.cc matches Eq. (79) exactly) and contracting them with the \omega electrostatic potential matrix elements in psi4/psi4/src/psi4/libsapt_solver/ind30.cc in SAPT2p3::ind30(). The problem is that this algorithm accounts for the first 2 matrix elements in Eq. (75) but not for the last one, <VS_AS_B>. Unless I understand something incorrectly, the Psi4 code is missing the <VS_AS_B> contribution in E(30)ind.

Going now back to Eq. (72), it is easy to prove that <VS_AS_B>=4s^r_a v^{ab}_{rs} s^s_b, that is, it contributes a quarter of the last term in Eq. (72). Our working hypothesis was that, because of the omission of this term, E(30)ind programmed in Psi4 has the last term in Eq. (72) multiplied by 12 instead of 16. Therefore, Jonathan modified his Psi4NumPy E(30)ind code to include this last term with the incorrect factor of 12, and now his values are matching Psi4 perfectly! In other words, we are quite certain that the Psi4 implementation includes the last term in Eq. (72) with an erroneous factor of 12 instead of 16. Fortunately, this doesn’t affect the SAPT2+(3) or SAPT2+3 results that also include delta HF, but it will (slightly) affect the third-order SAPT results computed without delta HF.

I think the E(30)ind,resp code is fine but the wrong E(30)ind will slightly affect the scaled approximated value of E(30)exch-ind,resp.

Please let me know if I need to explain anything better or if I can be of any further help.

All the best,
-Konrad Patkowski

**Comment by dgasmith** [comment]
Hi Konrad,
Thanks for bringing this up. Do you know the magnitude of the change that this will introduce? We will likely need to make the fix and then highlight this heavily in our patch notes.

@ehohenstein2 any thoughts here?

**Comment by konpat** [comment]
Hi Daniel,
Fortunately, the other (hyperpolarizability) terms are dominant in E(30)ind, and the changes are quite small. Here's the breakdown of the E(30)ind/jun-cc-pVDZ comparison for the A24 database.

               E30ind (correct)  E30ind(Psi4)
System    R/R0
C2H4_OH2  1.0000  -3.0226       -3.0111
C2H4_NH3  1.0000  -1.0799       -1.0750
CH4_BH3   1.0000  -1.1568       -1.1573
C2H2_C2H2 1.0000  -0.6210       -0.6140
HF_HF     1.0000  -2.8255       -2.8149
H2C2_H2C2 1.0000  -2.3226       -2.3207
CH4_CH4   1.0000  -0.1226       -0.1226
NE_NE     1.0000  -0.0289       -0.0289
C2H4_CH4  1.0000  -0.2394       -0.2385
HCN_HCN   1.0000  -0.9550       -0.9254
NH3_NH3   1.0000  -1.3439       -1.3342
C2H6_CH4  1.0000  -0.1434       -0.1434
CH4_C2H6  1.0000  -0.1793       -0.1792
C2H4_C2H4 1.0000  -1.0483       -1.0456
C2H4_C2H2 1.0000  -3.0695       -3.0663
OH2_OH2   1.0000  -3.3464       -3.3202
NH3_CH4   1.0000  -0.3153       -0.3126
OH2_NH3   1.0000  -5.9326       -5.8703
CH2O_CH2O 1.0000  -5.3882       -5.3465
CH4_HF    1.0000  -0.8671       -0.8681
C2H4_CH2O 1.0000  -1.7569       -1.7516
CH4_OH2   1.0000  -0.3754       -0.3741
H4C2_H4C2 1.0000  -3.7882       -3.7830

**Comment by dgasmith** [comment]
Looks like 0-60 cal/mol, thanks for already doing this benchmark!

**Comment by loriab** [comment]
Apparently I can't change a 12 to a 16 in an hour in the SAPT code, so pasting in the clues thus far, namely Ed's thesis. Ed's (168) is (72) above, assuming some typos or notation changes. So something awry upon (169–171) reformulation.

<img width="374" alt="Screen Shot 2019-07-29 at 3 08 50 PM" src="https://user-images.githubusercontent.com/2314730/62075537-5adbfc80-b213-11e9-9033-42de7f7bf2bc.png">

**Comment by konpat** [comment]
I feel your pain, Lori. Fixing this involves more than just changing a 12 to a 16 in the code. In fact, it requires programming the additional 4 separately from the original 12: otherwise we mess up the induction amplitudes of Eq. (169)-(170) and therefore mess up E(30)exch-ind.

As far as I can see, Ed's Eqs. (168), (169), and (170) are all correct but (171) is wrong. Out of the terms in Eqs. (169) and (170), the first 2 terms in each together lead to the first 4 terms in Eq. (168), the 3rd terms give the last term of Eq. (168) with a factor of 4 each, and the 4th terms add up to the last term of Eq. (168) with a factor of 4. That's how we're getting a factor of 12 and not 16.

**Comment by loriab** [comment]
fixed by #1803
