### ISSUE TITLE
DETCI Hangs

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#1685]
Transferred from the [forums](http://forum.psicode.org/t/regarding-cisd-calculation/1474).

A user reported a CISD computation on a system with 190 orbitals and C2v symmetry that quit after "Setting up CI strings" with absolutely no error message. I reproduced this with a post-1.3.2 dev version of Psi on my cluster, in serial with 30 GB. (The original reporter is using an antique version of Psi.)

@dgasmith pointed out that DETCI may have problems with a system of this size, but I'm not familiar enough with DETCI's computational costs to know if those problems would crash DETCI. At minimum, there should be an error message printed out. If there is an actual DETCI bug, that should ideally be fixed. My apologies to the person who has to do that.

**Comment by dgasmith** [comment]
Does any 190 basis function DETCI CISD work? It is under the 256 basis function limit for that code though...

**Comment by CDSherrill** [comment]
Yeah, this is just to big a problem for DETCI's poor CISD capabilities.  I answered this in the forums.  Basically, if you optimize to do full CI very efficiently, you can create intermediate data that is small enough to work fine for full CI, but blows up for CISD and makes the code run out of memory.  I'm pretty sure that's what's happening here.  I issued a PR to update the documentation to warn users away from DETCI CISD unless it's a tiny molecule (with a small basis).
