### ISSUE TITLE
Changes in MOM from PSI4 1.1 to 1.4a2.dev78

### ISSUE THREAD

**Issue by rlaplaza** [psi4/psi4#1692]
Hello everyone. Thank you for working on this fantastic project, I've been using it a lot lately and I'm both grateful and impressed.

That said, I've been thoroughly trying to break the code by doing some... unconventional calculations.

I'm converging core holes in molecules. In the simple case of water, this leads to the following total energies, where _opt refers to the neutral GS RHF molecule and +_homo-i refers to the UHF cation, on the GS RHF geometry, with the hole in the homo-ith MO.

[psi4_11.tar.gz](https://github.com/psi4/psi4/files/3469634/psi4_11.tar.gz)

(PSI4 1.1)
water_opt -7.606667516613838e+01
water+_homo -7.566072290801020e+01
water+_homo-1 -7.558091679634278e+01
water+_homo-2 -7.541230326047109e+01
water+_homo-3 -7.423771580655676e+01
water+_homo-4 -5.571830715553878e+01

Noticeably, pulling an electron from the homo-3 and homo-4 require some crafty work, but **I have managed to converge this calculations with several basis sets and in DFT, too, using damping and other tricks, all in PSI4 1.1. Energies are qualitatively the same alway**s. All the output files are attached, in psython mode (I could not make MOM to work from python).

Now then, I wanted to check some things, so I printed the density matrices from .fchk files and plugged them to PySCF, projecting them properly and so on, just to evaluate the energy with UHF on top of those density matrices. I get the same energies for the neutral molecule and the homo, homo-1 and homo-2 cations. I get VERY different energies from the homo-3 and homo-4 states. Now thats weird, because the energies above make sense. So I assumed, okay, maybe there's something odd with the .fchk writer module. I've seen its been updated, so lets try a newer version of PSI4.

So I got the 1.4a2.dev78 and tried to run my calculations using the newest available dev release, from scratch. I get exactly the same energies, except for the homo-4  state, for which I get some very funky results:

[psi4_14.tar.gz](https://github.com/psi4/psi4/files/3469641/psi4_14.tar.gz)

(Psi4 1.4a2...)
water_opt -7.606667516615393e+01
water+_homo -7.566072290809453e+01
water+_homo-1 -7.558091679647397e+01
water+_homo-2 -7.541230326053801e+01
water+_homo-3 -7.423771580754870e+01
water+_homo-4 **9.360901611130924e+00**

And that's the story! I would try to read the .fchk files and see if I can evaluate the UHF energy on top of them with Psi4 intead of PySCF next, but this thing appeared and I guess some checks are due to know what is going on.

Thank you for your patience! I hope its nothing serious!

**Comment by dgasmith** [comment]
This might be an "issue" with the new guess. Can you try a `guess core` or `gwh`?

Issue in this case is in quotes as this may be something odd where the guess pushes this unstable optimization to a poor value.

**Comment by rlaplaza** [comment]
Hi, thanks for the quick answer.

Could be: as I was starting MOM within very few iterations, the impact of the guess may have been decisive. However, changing the guess (specifically from sad to read, taking the orbitals from the previous RHF calculation) did not work. What apparently fixes the issue, independently of the guess, was increasing the number of SCF iterations before activating MOM. So I don't really know what is it. 

Also note that, while my inputs may seem very strange (and, quite possibly, messy), the HF/UHF case is the most simple one. Converging these states with large basis sets in DFT is a true pain, and often requires a lot of toying around).

As an additional note, the energy that the program was giving with that output is exactly 9.3609016111309238, the nuclear repulsion energy. So, for whatever reason, the electronic energy is 0 in that state.

**Comment by susilehtola** [comment]
> As an additional note, the energy that the program was giving with that output is exactly 9.3609016111309238, the nuclear repulsion energy. So, for whatever reason, the electronic energy is 0 in that state.

That sounds highly unlikely. Maybe PySCF isn't getting a properly formatted density matrix, and is not really evaluating anything?

**Comment by rlaplaza** [comment]
Check the output for the water+_homo-4.out in the Psi4 1.4(...) version. **That's the converged energy in PSI4!** Hence this issue. Its clearly converging to some crazy unphysical state. I would not worry if it was just a strange energy... MOM is like that. But this is an impossible energy!

The whole PySCF thing is a different ordeal that probably has to do with some weird reordering in the .fchk writer.

**Comment by susilehtola** [comment]
@rlaplaza but the issue is exactly as I suspected. Look at the log file:
```

    Final Occupation by Irrep:
             A1    A2    B1    B2 
    DOCC [     0,    0,    0,    0 ]
    SOCC [     0,    0,    0,    0 ]
    NA   [     0,    0,    0,    0 ]
    NB   [     0,    0,    0,    0 ]

  @DF-UHF Final Energy:     9.36090161113092
```

There are **no** electrons in the calculation. Getting zero contributions from the energy just doesn't happen otherwise, usually you just get nonsense.

**Comment by rlaplaza** [comment]
@susilehtola indeed. The question is, what is really happening in this step, the 2nd MOM activation:

```
  ==> MOM Excited-State Iterations <==
  Excitations:
   A  -> A :    1A1   ->    4A1
   Total Energy        Delta E      Density RMS
   @DF-UHF iter   0:   -75.32089478045290   -1.26766e+00   1.13211e-02 DIIS/MOM
   @DF-UHF iter   1:     9.36090161113092    8.46818e+01   0.00000e+00 DIIS/MOM
   @DF-UHF iter   2:     9.36090161113092    0.00000e+00   0.00000e+00 DIIS/MOM
  Energy and wave function converged.
```

Are the electrons anihilated in that MOM activation step? Are all the occ. orbitals wrongly deleted, leading to an awkward situation? Maybe then some iterator does not check the virtuals? And, most importantly, what is the change from 1.1 to 1.4(...) that makes this "a thing".

I really have no hypothesis. My point is, this is not a "MOM converging to some weird state" thing: this is probably some sort of bug.

**Comment by loriab** [comment]
A big suspect if MOM changed between v1.2 and v1.3 is the migration of SCF iterations from [C++ to Python](https://github.com/psi4/psi4/pull/953/files). That's an awfully big diff, so the main orientation is that some libscf_solver code headed to driver/proc/scf. I "standardized" the MOM logic a touch in a way I thought to be harmless. Certainly all tests were ok, but there wasn't much MOM testing.

**Comment by JonathonMisiewicz** [comment]
I'm taking this issue as part of a campaign to make sure the SCF capabilities are in a "nothing is _broken_ state" before I start making DIIS changes that could affect a lot of the code. I've been able to figure out _why_ the issue is happening.

The driver includes [a directive to reset the occupations on iteration 0](https://github.com/psi4/psi4/blob/master/psi4/driver/procrouting/proc.py#L1545). The MOM code [fires](https://github.com/psi4/psi4/blob/master/psi4/driver/procrouting/proc.py#L1545) [about](https://github.com/psi4/psi4/blob/master/psi4/driver/procrouting/proc.py#L1545) [here](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libscf_solver/hf.cc#L499) and [resets the iteration number to zero](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libscf_solver/mom.cc#L90). The occupation reset [fires](https://github.com/psi4/psi4/blob/master/psi4/driver/procrouting/scf_proc/scf_iterator.py#L429), which contaminates what SAD already correctly set.

While setting the iteration number back to 1 solves _that_ issue, it creates another issue with computations may converge prematurely.
