### ISSUE TITLE
open-shell coupled-cluster psivars

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#1702]
Note this is only a psivars issue -- printed energies are fine.

singles contributions to UHF & ROHF CCSD (https://github.com/psi4/psi4/blob/master/psi4/src/psi4/cc/ccenergy/energy.cc#L132-L137) and below) aren't getting stored in psivars. in consequence, `CCSD SAME-SPIN CORRELATION ENERGY` and `CCSD OPPOSITE-SPIN CORRELATION ENERGY` don't sum to `CCSD CORRELATION ENERGY`.

* [ ] for the CC people out there -- speak up if the CCSD analogs of the following definitions offend. they're [what qcschema is using](https://github.com/MolSSI/QCSchema/blob/a4329e626903ec0391d21179f0754bdc65e6831b/qcschema/dev/properties/cc_properties.py#L7-L38)
```
qcvardefs['MP2 SAME-SPIN CORRELATION ENERGY'] = {
    'units': 'Eh',
    'glossary': r"""
   The unscaled portion of the MP2 correlation energy
   from same-spin or triplet doubles correlations.

   canonical_corl(os_scale=1, ss_scale=1) = singles + os_scale * (tot_corl - ss_corl) + ss_scale * ss_corl
   :math:`E_{\text{SS}}` in Eq. :eq:`MP2corl`.
"""}

qcvardefs['MP2 OPPOSITE-SPIN CORRELATION ENERGY'] = {
    'units': 'Eh',
    'glossary': r"""
   The unscaled portion of the MP2 correlation energy
   from opposite-spin or singlet doubles correlations.
   :math:`E_{\text{OS}}` in Eq. :eq:`MP2corl`.
"""}

qcvardefs['MP2 SINGLES ENERGY'] = {
    'units': 'Eh',
    'glossary': r"""
   The singles portion of the MP2 correlation energy.
   Zero except in ROHF.
   :math:`E_{\text{S}}` in Eq. :eq:`MP2corl`.
"""}

qcvardefs['MP2 DOUBLES ENERGY'] = {
    'units': 'Eh',
    'glossary': r"""
   The doubles portion of the MP2 correlation energy
   including same-spin and opposite-spin correlations.
   :math:`E_{\text{D}}` in Eq. :eq:`MP2corl`.
"""}
```

- [ ] let us implement storing singles for all three refs in cc* modules (only rohf will be nonzero).
- [ ] let us implement storing all three consistently in any other cc codes
- [ ] let us make sure to place these var on wfn, not in `P::e`.

**Comment by CDSherrill** [comment]
These definitions all look ok.  It's correct that the CCSD energy should
not equal the sum of the same-spin and opposite-spin terms, b/c those terms
refer to the doubles, and singles are held out as separate (
https://aip.scitation.org/doi/10.1063/1.2883974 )
