### ISSUE TITLE
DFTD4 interface in Psi4

### ISSUE THREAD

**Issue by chrinide** [psi4/psi4#1710]
Dear Psi4 Developers,

Is there any plan to add the newly DFTD4 interface in Psi4

**Comment by CDSherrill** [comment]
Yes!  I just spoke to Stefan Grimme about it this week.

**Comment by JonathonMisiewicz** [comment]
I believe #2142 will close this?

**Comment by loriab** [comment]
Yes, I just informed GH. It needs a rebase, and there's some packaging issues, iirc.
