### ISSUE TITLE
set cubeprop_tasks ['frontier_orbitals'] not working as per examples

### ISSUE THREAD

**Issue by declare34** [psi4/psi4#1722]
Tried to run the following keywords, copied directly from examples except for the modification of basis sets & functionals (omitted lengthy molecule which is fine outside of using cubeprop):

`memory 8 Gb

set basis  6-31G
set scf_type df
set freeze_core True
set cubeprop_tasks ['frontier_orbitals']

E, wfn = optimize('b3lyp', return_wfn=True)
cubeprop(wfn)
`
The following error ensues post successful optimisation:

`Traceback (most recent call last):
  File "/usr/bin/psi4", line 248, in <module>
    exec(content)
  File "<string>", line 65, in <module>
  File "/usr/lib/psi4/driver/p4util/util.py", line 101, in cubeprop
    cp.compute_properties()

RuntimeError: 
Fatal Error: FRONTIER_ORBITALSis an unrecognized PROPERTY_TASKS value
Error occurred in file: /build/psi4-XGp1km/psi4-1.1/psi4/src/psi4/libcubeprop/cubeprop.cc on line: 196
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)
psi::CubeProperties::compute_properties()
pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, psi::CubeProperties, , pybind11::name, pybind11::is_method, pybind11::sibling, char [10]>(void (psi::CubeProperties::*)(), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, char const (&) [10])::{lambda(psi::CubeProperties*)#1}, void, psi::CubeProperties*, pybind11::name, pybind11::is_method, pybind11::sibling, char [10]>(pybind11::cpp_function::initialize<void, psi::CubeProperties, , pybind11::name, pybind11::is_method, pybind11::sibling, char [10]>(void (psi::CubeProperties::*)(), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, char const (&) [10])::{lambda(psi::CubeProperties*)#1}&&, void (*)(psi::CubeProperties*), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&, char const (&) [10])::{lambda(pybind11::detail::function_record*, pybind11::handle, pybind11::detail::function_record*, pybind11::detail::function_record*)#3}::_FUN(pybind11::detail::function_record, pybind11::detail::function_record*, pybind11::detail::function_record*, pybind11::detail::function_record*)
pybind11::cpp_function::dispatcher(_object*, _object*, _object*)`

I have tried running a smaller molecule with no cubeprop_task specified which runs fine and produces lots of cube files correctly. Sadly I do not have the disk space to do this for larger molecules. I'll dig around into the problem myself but thought it a good idea to point this out here. Feel free to close if I have missed a glaring error.

**Comment by loriab** [comment]
I just ran 

```memory 8 Gb

molecule {
O
H 1 1.0
H 1 1.0 2 90.0
}

set basis  6-31G
set scf_type df
set freeze_core True
set cubeprop_tasks ['frontier_orbitals']
E, wfn = optimize('b3lyp', return_wfn=True)
cubeprop(wfn)
```

and it correctly produced cube files. Are you running from a conda install or a compiled version? If the latter and you recompiled recently, try `touch`ing the `psi4/src/core.cc` and `psi4/src/export_*` files and re `make`ing. I suspect there's something odd going on with the pybind11 2.3.0 update and mixed versions.

**Comment by declare34** [comment]
Hi, I installed via sudo apt install psi4 on Windows Subsystem for Linux
Ubuntu. I believe this version may not be up to date as the online manual
on the psi4 website for version 1.2 indicates no frontier_orbital option
for cubeprop_tasks, whilst the manual for 1.3 indicates the option.

I will recompile the latest stable release from source tonight and confirm,
which may then allow this issue to be closed. Currently at work so will be
a while until I can check.

Thanks

**Comment by PeterKraus** [comment]
Yeah, that would be the reason - 1.3 was the first release with that `cubeprop` keyword. The easiest way to install is probably using the pre-built binaries for 1.3.2:

https://admiring-tesla-08529a.netlify.com/installs/v132/

If you need further help, give us a shout.

**Comment by PeterKraus** [comment]
@declare34 Any news on this one?

**Comment by declare34** [comment]
Sorry for not updating. I was indeed running the old version and have had
success using the new version.

Thanks for the help, I believe this issue should be closed.

**Comment by PeterKraus** [comment]
Great, thanks!
