### ISSUE TITLE
dftd3 tries to write file in HOME directory

### ISSUE THREAD

**Issue by dspoel** [psi4/psi4#1724]
When running a calculation using

optimize('pwpb95-d3bj')

The program will try to open a file in my home directory rather than the scratch directory and crashes:
RuntimeError: [Errno 13] Permission denied: '/home/s/spoel/dftd3_092b616a'

A workaround is to use in my script
export HOME=$PSI_SCRATCH

**Comment by PeterKraus** [comment]
Where did you get your current Psi4 / dftd3 from? Is it from the installer, via conda, or compiled from source?

**Comment by dspoel** [comment]
This is from psi4conda.
Thanks for the quick reply.

**Comment by loriab** [comment]
It's always going to write at least one file (the parameters file) to $HOME b/c that's where dftd3 wants to read it
```
>>> dftd3 -help
 dftd3 <coord filename> [-options]
...
 variable parameters can be read from <current-directory>/.dftd3par.local
  or 
 variable parameters read from ~/.dftd3par.<hostname>
```

Looks like https://github.com/loriab/psi4/blob/libint2/psi4/driver/procrouting/empirical_dispersion.py#L209 ought to have `local_options={"scratch_directory": core.IOManager.shared_object().get_default_path()}` as an extra argument to put the dftd3 scratch in `$PSI_SCRATCH`.

**Comment by dspoel** [comment]
Apparently, but as you see in weird cases like on the HPC cluster I am using the home directory may be unwritable.

**Comment by loriab** [comment]
Sounds like an uninviting $HOME.

I think we can work around this in future. I could suggest some edits to manoeuvre around the problem for you now, but if you're psi4conda, then that's v1.3.x which has things in different places. I suggest your HOME aliasing workaround for now, and I'll ping when other is in.

**Comment by PeterKraus** [comment]
I'm surprised this is fhe first time we're hitting something like this. Thanks for the report!

**Comment by dspoel** [comment]
Cool, thanks. The workaround works indeed.

**Comment by JonathonMisiewicz** [comment]
Did #1725 not fix this?

**Comment by PeterKraus** [comment]
Right you are. Closing.
