### ISSUE TITLE
Numerical precision too large?

### ISSUE THREAD

**Issue by dspoel** [psi4/psi4#1733]
Hi, I am doing DFT calculations and get results like this:

    @Final double-hybrid DFT total energy =   -76.4165290991355590

Since a double precision floating point number can only store 15 decimals I wonder where the other decimals come from?
 
The excess of precision is a problem if I try to read the output files using a C++ program and the energy is truncated, which of course I can work around but that should not be necessary, right?

**Comment by hokru** [comment]
I remember the binary to output conversion to be tricky in its detail. Something like you usually want 17(?) decimals printed actually.
(Assuming everything is printed from the IEEE doubles and not from the registers)

I don't fully understand the worry about the utmost possible precision. Usually much more crude approximations are done in typical QM codes.

**Comment by loriab** [comment]
If you’re trying to accumulate Psi4 results in C++, I’d advise not parsing the output file but instead running in “psi4 —json” mode and collecting the resulting structured output to read back into c++ through known json or msgpack libs.

**Comment by dspoel** [comment]
Thanks for the json tip. Unfortunately I already did a few hundred thousand calculations that I do not want to redo. https://stackoverflow.com/questions/9999221/double-precision-decimal-places

**Comment by loriab** [comment]
Got it -- `grep` away, then. You're right, though, that the [16 decimals is bizarre](https://github.com/psi4/psi4/blob/master/psi4/driver/procrouting/proc.py#L2124-L2126). 12 is usually our max.

**Comment by dgasmith** [comment]
@dspoel If you are running computations at that scale you may be interested in the [QCArchive](https://qcarchive.molssi.org) project, you can either run through the MolSSI instance or use our [infrastructure](https://docs.qcarchive.molssi.org/en/latest/) to automatically run and structure computational results.

**Comment by dgasmith** [comment]
We are unlikely to change this since a single hydrogen will require this kind of precision and are unlikely to create something that slowly shifts the printed decimals to exact IEEE double precision.
