### ISSUE TITLE
v2rdm_casscf was not compatible with the newly psi4-1.4a2.dev215 version

### ISSUE THREAD

**Issue by chrinide** [psi4/psi4#1750]
Hi all,

Just a report.

Current conda v2rdm_casscf build was not compatible with the newly psi4-1.4a2.dev215 version.

> Traceback (most recent call last):
>   File "/root/miniconda3/envs/psi4/bin/psi4", line 184, in <module>
>     import psi4
>   File "/root/miniconda3/envs/psi4/lib//python3.7/site-packages/psi4/__init__.py", line 82, in <module>
>     from .driver import endorsed_plugins
>   File "/root/miniconda3/envs/psi4/lib//python3.7/site-packages/psi4/driver/endorsed_plugins.py", line 33, in <module>
>     import v2rdm_casscf
>   File "/root/miniconda3/envs/psi4/lib//python3.7/site-packages/v2rdm_casscf/__init__.py", line 45, in <module>
>     psi4.core.plugin_load(sofile)
> RuntimeError:
> Fatal Error: load_plugin: Cannot open library: /root/miniconda3/envs/psi4/lib/python3.7/site-packages/v2rdm_casscf/v2rdm_casscf.so: undefined symbol: _ZN3psi8ERISieveC1ESt10shared_ptrINS_8BasisSetEEd
> Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1573157589938/work/psi4/src/psi4/libplugin/load_plugin.cc on line: 52
> The most recent 5 function calls were:
> 
> 
> forrtl: severe (174): SIGSEGV, segmentation fault occurred
> Image              PC                Routine            Line        Source
> libgdma.so         00007FDBC5B360DC  for__signal_handl     Unknown  Unknown
> libpthread-2.27.s  00007FDBD8DF2890  Unknown               Unknown  Unknown
> ld-2.27.so         00007FDBD9016A31  Unknown               Unknown  Unknown
> libc-2.27.so       00007FDBD8B472DF  _dl_catch_excepti     Unknown  Unknown
> libc-2.27.so       00007FDBD8B4736F  _dl_catch_error       Unknown  Unknown
> libdl-2.27.so      00007FDBD87D1735  Unknown               Unknown  Unknown
> libdl-2.27.so      00007FDBD87D10B3  dlclose               Unknown  Unknown
> core.cpython-37m-  00007FDBC6A8034A  Unknown               Unknown  Unknown
> core.cpython-37m-  00007FDBC672D382  Unknown               Unknown  Unknown
> core.cpython-37m-  00007FDBC6756337  Unknown               Unknown  Unknown
> core.cpython-37m-  00007FDBC6762AB4  Unknown               Unknown  Unknown
> python3.7          00007FDBD94D3B65  PyCFunction_Call      Unknown  Unknown
> python3.7          00007FDBD95B2E74  Unknown               Unknown  Unknown
> python3.7          00007FDBD95B99E7  Py_FinalizeEx         Unknown  Unknown
> python3.7          00007FDBD95D1C63  Unknown               Unknown  Unknown
> python3.7          00007FDBD95D1F7C  _Py_UnixMain          Unknown  Unknown
> libc-2.27.so       00007FDBD8A01B97  __libc_start_main     Unknown  Unknown
> python3.7          00007FDBD9577122  Unknown               Unknown  Unknown

Remove v2rdm_casscf, thePsi4 would be OK.
Previous dev Psi4 builds are all OK (WSL Win10).

**Comment by JonathonMisiewicz** [comment]
I imagine the problem is that we (@zachglick) [changed the relevant constructor a few months back to have a default boolean argument](https://github.com/psi4/psi4/commit/85ce7af9c23d0280946e2040967e12bcd6ab3f01#diff-c513bb8f4c4e0c8ba6348974ebff6db2L182-R182).

objdump tells me Psi exposes a `psi::ERISieve::ERISieve(std::shared_ptr<psi::BasisSet>, double, bool)` symbol, and your error message is looking for a `psi::ERISieve::ERISieve(std::shared_ptr<psi::BasisSet>, double)` symbol. I'm surprised that adding a default argument would force other programs to supply a value, but I'll leave this to somebody more experienced in the ways of plugins.

**Comment by loriab** [comment]
Yes, thanks for the report. A new build (`.dev13` in psi4-rt; `_11` for v2rdm_casscf Linux; `_10` for v2rdm_casscf mac) is up for all platforms.
