### ISSUE TITLE
QMMM charges seem to have no effect

### ISSUE THREAD

**Issue by tovrstra** [psi4/psi4#1757]
I may be doing something wrong, but the outputs I get seems unexpected. When running the following example with or without point charge, the same energy is computed:

```
# Simple example to test QMMM charges

molecule {
  0 1
  He 0.0 0.0 0.0
  symmetry c1
}

Chrgfield = QMMM()
Chrgfield.extern.addCharge(0.0,0.0,5.0,-1.0)
psi4.set_global_option_python('EXTERN', Chrgfield.extern)

set {
    basis aug-cc-pvtz
}

energy('scf')
```

Either with or without, the energy is: -2.8612063084748378 Hartree.

```
grep "Total Energy =" *.out
with.out:    Total Energy =                         -2.8612063084748378
without.out:    Total Energy =                         -2.8612063084748378
```

Full in and outputs are attached: [qmmm_test.zip](https://github.com/psi4/psi4/files/3884810/qmmm_test.zip) These are based on the documentation here: http://www.psicode.org/psi4manual/1.2/scf.html#external-potentials-and-qm-mm

**Comment by loriab** [comment]
I think charge comes first among the arguments. https://github.com/psi4/psi4/blob/master/tests/extern1/input.dat#L24 Your input possibly interpreted as no charge.

**Comment by tovrstra** [comment]
Thanks! At least I was right with my assumption I was doing something wrong. :)
