### ISSUE TITLE
Level Shifting in OCC

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#1777]
I've been investigating orbital convergence problems in the `occ` module, such as in [this test case](https://github.com/psi4/psi4/blob/master/tests/omp2-3/input.dat). I find that convergence massively improves when I turn level shifting _off_, as it is [on by default](https://github.com/psi4/psi4/blob/master/psi4/src/read_options.cc#L2695). `grep -inr 'level_shift' .` indicates that the level shifting is currently being used exclusively [to scale the diagonal elements of the B matrix in the orbital optimization step of DIIS](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/occ/diis.cc#L74-L77).

@bozkaya, I know this is old code, but can you comment on why you did the level shifting this way? This doesn't seem similar to any level shifting scheme I've ever seen. My quick numerical tests indicate that this makes convergence _much worse_, and getting rid of this heals some tests that @loriab is currently concerned about. Comments from @susilehtola are also welcome for this one.

**Comment by bozkaya** [comment]
I scale the DIIS B matrix diagonals based on the suggestion made by Pulay (JCP, 84, 5728, 1986). It is expected to improve convergence in problematic cases, where B matrix is not diagonally dominant. However, it slightly slow down the diis. @JonathonMisiewicz

**Comment by loriab** [comment]
@bozkaya, should we turn level-shifting off by default then, so it can still be invoked for problem cases but doesn't impede ordinary diis convergence?

**Comment by JonathonMisiewicz** [comment]
This is damping, not level shifting. This keyword should be renamed.

To give you some perspective on how severe these convergence problems are, for the test case I gave, which is in the Psi test suite:
No damping: 16 iterations
0.01 damping: 38 iterations
0.02 damping (default): 53 iterations

So we've made convergence **three times harder** to achieve in this example. Have you seen many cases where this damping is necessary or helpful to converge? Otherwise, I agree with Lori about turning this off by default.

For future reference:
Eq. 5 of the paper has a sign error: the - needs to be a + in order for minimizing to favor a solution where c_i^2 B_ii small, which should prevent individual c coefficients blowing up. The (1+d) rule in the paper is correct, as is the Psi implementation.

**Comment by loriab** [comment]
Go for the renaming and default toggling, I think, @JonathonMisiewicz. It's good to get the tests passing and converging under conditions other than early exit from iterations. If you have a non-diagonally dominant B-matrix case around, @bozkaya, it'd be nice to have that in the test suite to make sure we're not favoring one class of systems over others.

**Comment by JonathonMisiewicz** [comment]
Additional tests show that just turning off the damping may not be a good idea after all. Many of the OCEPA/OLCCD tests use the NO radical (ocepa-grad2, ocepa3, ocepa2), and none of them pass if I have damping off. I'll continue investigating and post back when I have something. These convergence problems aren't consistent with my experience with my own OCEPA code, and the damping is far more chaotic than I'd expect.

**Comment by bozkaya** [comment]
I would not suggest turning off the damping. Based on my experience it is very helpful for open-shell systems. "Damping true" was default in Psi3 cscf code, too, for open-shells. @JonathonMisiewicz  @loriab

**Comment by JonathonMisiewicz** [comment]
Is there a reason why non-OO CEPA is the only method in OCC that uses DIIS for amplitudes? I understand that OMP2 amplitudes should converge quickly, but surely OCEPA would benefit from it as well?

My investigation so far indicates the problem with orbital convergence can be fixed by combining it with amplitude DIIS, so unless there is a reason why it doesn't exist in OCC, I intend to add it.

**Comment by bozkaya** [comment]
1) All non-OO CC methods employ DIIS.

2) Most OO methods converge very fast, hence amplitude DIIS has expected to have a little effect on convergence. However, we may explore it.

**Comment by JonathonMisiewicz** [comment]
Status update: I have coupled DIIS working for OCEPA. The OMP family should follow without _much_ additional effort. For `ocepa-grad2`, I'm seeing in 13 iterations what took 33 [before my meddling](https://github.com/psi4/psi4/blob/master/tests/ocepa-grad2/output.ref). I'm going to take some extra time before pushing anything to do a thorough convergence study.
