### ISSUE TITLE
Generating `compile_commands.json` with CMake doesn't work

### ISSUE THREAD

**Issue by berquist** [psi4/psi4#1779]
Specifying `-DCMAKE_EXPORT_COMPILE_COMMANDS=1` doesn't work. It should generate a `compile_commands.json` in the build directory immediately after running `cmake`.

**Comment by loriab** [comment]
It's showing up for me after compile at `./objdir38/psi4-core-prefix/src/psi4-core-build/compile_commands.json` (where `objdir38` is my `-Bobjdir38`). I've never made up of this file. Is it just not where you expected because of the  superbuild setup?

**Comment by berquist** [comment]
> Is it just not where you expected because of the superbuild setup?

Yep, found it.
