### ISSUE TITLE
turn off mol positioning with frozen cart opt

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#179]
If you use the new optking feature that allows freezing of individual Cartesian coordinates *without* also setting `no_reorient` and `no_com`, the molecule reportedly turns into a "high-speed car wreck". It is requested that the driver turn those molecule options on when performing such optimizations.

**Comment by loriab** [comment]
To solve:
* find a system that becomes a car wreck while optimizing frozen coords and w/o `no_reorient` & `no_com`. (probably intermolecular optimization). see tests opt-[6789] for frozen opt examples.
* check that opt healed w/`no_reorient` & `no_com`
* around here (https://github.com/psi4/psi4/blob/master/lib/python/driver.py#L1193), test if any of those freeze options were set `psi4.get_option('OPTKING', 'FREEZE<fill in>')` and if so, add

```python
    molecule.fix_orientation(True)
    molecule.fix_com(True)  
    molecule.update_geometry()
```
* check all working

**Comment by dgasmith** [comment]
@tparker36 Can I get test case where this dies horribly?

**Comment by tparker36** [comment]
.Any constrained optimization example where "no_com" and/or "no_reorient"
isn't in the molecule input section and the geometry isn't in the standard
nuclear orientation. The job won't fail, but the constrained coordinates
will not be identical to their original values in the final output.

-Trent

On Wed, Apr 20, 2016 at 3:31 PM, Daniel Smith <notifications@github.com>
wrote:

> @tparker36 <https://github.com/tparker36> Can I get test case where this
> dies horribly?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/psi4/psi4/issues/179#issuecomment-212570814>
>



-- 
Trent Parker
Sherrill Research Group
Georgia Institute of Technology

Center for Computational Molecular Science and Technology
School of Chemistry and Biochemistry
4201 Molecular Science and Engineering Building

901 Atlantic Drive NW
Atlanta, GA 30332

**Comment by tparker36** [comment]
Example attached.

Thanks,

-Trent

On Wed, Apr 20, 2016 at 3:41 PM, Trent Parker <
trent.michael.parker@gmail.com> wrote:

> .Any constrained optimization example where "no_com" and/or "no_reorient"
> isn't in the molecule input section and the geometry isn't in the standard
> nuclear orientation. The job won't fail, but the constrained coordinates
> will not be identical to their original values in the final output.
>
> -Trent
>
> On Wed, Apr 20, 2016 at 3:31 PM, Daniel Smith <notifications@github.com>
> wrote:
>
>> @tparker36 <https://github.com/tparker36> Can I get test case where this
>> dies horribly?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/psi4/psi4/issues/179#issuecomment-212570814>
>>
>
>
>
> --
> Trent Parker
> Sherrill Research Group
> Georgia Institute of Technology
>
> Center for Computational Molecular Science and Technology
> School of Chemistry and Biochemistry
> 4201 Molecular Science and Engineering Building
>
> 901 Atlantic Drive NW
> Atlanta, GA 30332
>



-- 
Trent Parker
Sherrill Research Group
Georgia Institute of Technology

Center for Computational Molecular Science and Technology
School of Chemistry and Biochemistry
4201 Molecular Science and Engineering Building

901 Atlantic Drive NW
Atlanta, GA 30332

**Comment by dgasmith** [comment]
I have this one as well.
