### ISSUE TITLE
Rename `dft_spherical_*` to `dft_angular_*`

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#1816]
The keywords `dft_spherical_points` and `dft_spherical_scheme` are misleading, since they control the angular quadrature scheme instead of the spherical quadrature that is a direct product of the radial and angular grids.

**Comment by dgasmith** [comment]
I think it would be hard to change such a core keyword at the moment for fairly small reason.

**Comment by JonathonMisiewicz** [comment]
Closing, per DGAS's comment - it's just too inconvenient to rename keywords that are so frequently used.
