### ISSUE TITLE
omp_set_nested routine deprecated

### ISSUE THREAD

**Issue by OleinikovasV** [psi4/psi4#1820]
I get this error:
> OMP: Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

Using this as an input:

```
molecule {
He 0 0 0
--
He 2 0 0
}
import snsmp2
energy('sns-mp2')
```

I have installed it from conda channel of psi4:

> conda create -n psi4 psi4 snsmp2 -c psi4

I also did

> conda update psi4 -c psi4

as advised on the [psi4 website](http://www.psicode.org/psi4manual/master/build_obtaining.html#faq-binarypackage) 

Package versions:
```
>>> import psi4
>>> psi4.__version__
'1.3.2'
>>> snsmp2.__version__
'1.0.1.dev24'
```

**Comment by loriab** [comment]
Thanks for the report. I think we've averting the warning in the linked issue. It was just a warning for you, not an error, right?

**Comment by loriab** [comment]
#1823 should have fixed this.

**Comment by dgasmith** [comment]
Reopend by #1849, the following fix did not work:

```C++
    omp_set_max_active_levels(0);
    omp_set_nested(0);
```

We need to get to the bottom of this. @loriab Can you paste the failing input file for posterity?

**Comment by loriab** [comment]
failing input is tu5 changed to jaTZ or jaQZ (which is also the tes_theading test, https://github.com/psi4/psi4/blob/master/psi4/share/psi4/scripts/test_threading.py#L72-L102). The `omp_set_nested` is only deprecated in OMP 5.0, so we've got some time.

**Comment by hokru** [comment]
I understand the docs (https://www.openmp.org/spec-html/5.0/openmpse57.html) such that an integer of  `1`  is the same behaviour as `(omp_set_nested(0);` where 0 is a bool.

> If the environment variable is set to false, the initial value of max-active-levels-var is set to 1.

The `max-active-levels-var` corresponds to `omp_set/get_max_active_levels`.


Below does seem to pass the sapt-tu5 test with jaQZ (and which I can make fail with `omp_set_max_active_levels(0);`). 

```
#ifdef _OPENMP
    omp_set_max_active_levels(1);
#endif
```

The threading test gives the same level of threading as compiling with `omp_set_nested(0)` (and conda psi4). 

Though I am hesitant making a 'too quick' PR about it. Opinions?

**Comment by loriab** [comment]
If (a) tu5 with jaQZ passes on single and multiple threads and (b) a larger sapt job that takes at least a few minutes shows roughly the same threading speedups as the current omp commands, then I think you've found the remedy. (Can't be worse than my previous "too quick" PR.)
