### ISSUE TITLE
OMP2 optimized orbitals dump to molden file

### ISSUE THREAD

**Issue by Konjkov** [psi4/psi4#185]
Hi PSI4 developers.
I want to do OMP2 (OMP3/OCEPA) run and dump out optimized orbitals into molden file like "molden_write true" does.
Is it possible at the moment?

Vladimir.

**Comment by bozkaya** [comment]
Dear Vladimir,

For OCC module "molden_write true" option is not active. Hence for the conventional OO methods it is not available. But, for DFOCC module it should be. Hence, for DF/CD-OO methods you should be use the "molden_write true" option.

Best ragrds,
Ugur Bozkaya

**Comment by Konjkov** [comment]
Many thanx Ugur, all works fine but sum of orbitals occupation in molden file is twice of electrons in RHF case.
Is there any plans to implement "molden_write" in Orbital optimized DCFT case?

Vladimir.

**Comment by bozkaya** [comment]
You are welcome!

I will take a look to the molden_write function for occupation numbers. It has been written a while ago but not tested well. If there is a bug in the molden_write function I will fix it. As far as I know for OO-DCFT there is also a molden_write option. 

Best regards,
Ugur.

**Comment by bozkaya** [comment]
Hi Vladimir,

For RHF case I build the entire OPDM, however SCF code builds only alpha-part of it. MoldenWriter is a function of libmints and it assumes that only alpha-part available, then it scale the OPDM by 2. However, for DFOCC module it is unnecessary and therefore you obtain the twice of occupation numbers. 

I will fix it and push my changes in a minute.

Best regards,
Ugur.

**Comment by Konjkov** [comment]
Hi, Ugur.
I've found that something had changed in molden file since https://github.com/psi4/psi4public/commit/521f06adb441ac1e2f1732eb1cd090190b409c49.
"Normalized contraction coefficients" in [GTO] section are differ.

Vladimir.

**Comment by Konjkov** [comment]
Anyhow MP2 orbital-optimization works (I compared it with ORCA OO-MP2).
It would be interesting to find out the date of df-ocepa release.

Vladimir.

**Comment by bozkaya** [comment]
Hi Vladimir,

Thank you for your interest for our OO codes. 

In fact, I am working on df-ocepa implementation now. This week I will leave the city for a conference and then I will join a workshop camp for our chemistry olympiad students, I am teaching physical chemistry for chemistry olympiad team. All these will take a two-weeks period. Then, I can finish and release it. I guess a few weeks later the code will be ready for public release. Also note that I will prefer the "orbital-optimized linearized coupled-cluster doubles" as the name of new code because cepa is mixed up with other cepa variants. Hence, the new code will be called by energy('df-olccd').

You may follow the psi4public for the new release. Alternatively, I can inform you when it has been released if you provide me your e-mail address.

Best regards,
Ugur.

**Comment by Konjkov** [comment]
Hi, Ugur
I've been doing Quantum Monte Calro calculations in CASINO program https://vallico.net/casinoqmc/
It uses Diffusion Monte Carlo (DMC) method for solving for the ground state of the many-body Schrödinger equation. In principle for bosonic state the DMC method is exact, but fermionic system has nodes and consequently regions of positive and negative sign, consequently several well-controlled approximations must be introduced for calculations to remain tractable.
The fixed-node approximation, is the simplest of them 
http://web.ornl.gov/~pk7/thesis/pkthnode21.html#SECTION00844000000000000000
CASINO program takes initial MO from external MOLDEN file usually from HF calculation (if single reference WFN is suitable). But I found that Orbital Optimized MO turns out better in this case.
I usually doing calculations in large bases up to cc-pV6Z and pV7Z.
I do not know whether it is possible to do such a calculation in psi4.

with respect, Vladimir.

**Comment by bozkaya** [comment]
I think it is very possible to use Psi4 for large basis set calculations as long as you use df or cd approximations. Of course, depending on your molecular system you should provide enough memory for OO methods. Finally, you should compile your psi4 with "--max-am-eri=7" option, which is necessary for our integral library (libint). I guess our binary versions are also compiled with high angular momentum options.

Best regards,
Ugur.

**Comment by dgasmith** [comment]
@bozkaya @Konjkov If I am reading this correctly the primary issue here has been solved?

**Comment by loriab** [comment]
Just be aware that there aren't fitting basis sets available for 6Z & 7Z orbital basis sets (https://github.com/psi4/psi4/issues/144), so switching to df-oo won't really work.

**Comment by bozkaya** [comment]
After wfn changes I am not sure whether it really works or not now. I would be glad if someone, who know the latest wfn stuff, take a look at the save_mo_to_wfn() function, which is in the occ_iterations.cc file (in dfocc module), to check if it is consistent with the present wfn. @loriab @dgasmith

**Comment by dgasmith** [comment]
@bozkaya Yes, we updated this file and `molden_write true` works for all OOand DCFT methods.

**Comment by Konjkov** [comment]
Primary issue is really solved. I think to close it.
