### ISSUE TITLE
Teach Parser to Accept `true`

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#1859]
A recent [forum issue](http://forum.psicode.org/t/error-in-running-on-centos-undefinted-name-true/1727/2) traced back to a user writing `return_wfn=true` rather than `return_wfn=True`. Can we teach the parser to automatically correct this, or at least print a better error message?

**Comment by dgasmith** [comment]
It would be fairly hard to get this right I think. This falls under more of a "Switch to an AST-based parser rather than re" than a quick first.

**Comment by loriab** [comment]
Yeah, string `'true'` (or 0/1/yes/no/on/off) would be properly cast to bool by https://github.com/psi4/psi4/blob/master/psi4/driver/p4util/procutil.py#L82-L86, but `true` is plain bad syntax that won't even get into that fn. It would have to be substituted at the inputparser (as you said). And then I'm not keen that psithon should be so subtly different from psiapi. I'm leaning toward wontfix, too.

**Comment by JonathonMisiewicz** [comment]
Fair enough. If not catching `true` rather than `True` is good enough for Python...
