### ISSUE TITLE
Document the relationship between OCC/DFOCC and frozen core

### ISSUE THREAD

**Issue by TiborGY** [psi4/psi4#1863]
Currently the OCC/DFOCC page of the docs makes no mention of frozen core.
DFOCC seems to default to all-electron, but _does_ seem to run with `set freeze_core true`.
OCC throws a RuntimeError, and claims that "Frozen core/virtual not implemented in Orbital-optimized methods"

I can see two issues here:

1. The error message from OCC suggests that none of the orbital-optimized methods in Psi4 support FC. This is either wrong and misleading (if DFOCC really does support FC) or DFOCC should also throw the same error.
2. Regardless of the answer to 1, [the relevant doc page](http://www.psicode.org/psi4manual/master/occ.html) ought to have a few words about FC support or the lack thereof.

**Comment by JonathonMisiewicz** [comment]
Good catch! Yes, I agree that the docs need to be updated. That particular manual page was already a [target to be updated](https://github.com/psi4/psi4/issues/1796), but we hadn't specifically realized the problem with frozen core.

As for frozen core support... `occ` includes methods that are orbital-optimized and methods that are not. The non-orbital optimized methods support frozen core energies but not gradients, but there is no frozen core for orbital optimized methods. `dfocc` universally has frozen-core for its orbital optimized methods, but orbital-optimized methods in `dfocc` are known for convergence issues, and trying to use frozen core makes them worse.

Getting frozen core (and frozen virtual!) support into orbital-optimized methods of the `occ` module is on my to-do list, but my current ETA is Spring 2021 due to circumstances you probably don't care about.

If you don't mind me asking, what are you trying to do?

**Comment by TiborGY** [comment]
Thanks for the information!
> 
>  orbital-optimized methods in `dfocc` are known for convergence issues, and trying to use frozen core makes them worse.

I kinda thought you solved all the the DFOCC convergence issues recently, at great effort.
> 
> If you don't mind me asking, what are you trying to do?

I don't mind it at all, as long as you don't mind a long winded explanation. ;-) Also, I am mostly just poking around, trying to weigh my options.
Essentially I am looking for code that can do open-shell Brueckner coupled-cluster doubles with perturbative triples ( either RBCCD(T) or UBCCD(T) ), using an ROHF reference.

We have recently published a [paper](https://doi.org/10.1039/C9CP07007A), where we found that the (T) contribution of BCCD(T) is much more stable than the (T) of CCSD(T) at geometries far from equilibrium, which is what we need a lot (about 1e+5 single point energies) of for our purposes.

Unfortunately, open-shell Brueckner or OO coupled cluster does not seem to be a common feature in QC programs, so I am trying to survey which programs have open-shell capable OO methods. Also, a performant OMP2 or OMP2.5 implementation could potentially be useful for us, even if it does not directly solve the lack of an RBCCD(T) implementation.

**Comment by hokru** [comment]
Yes, the shortcoming of (T) on non-equilibrium structures is know.
PSI4 has UBCC(T) `energy('bcc(t)')` on a ROHF reference, but only conventional integrals with the `ccenergy` module. Maybe you already found it.

You may want to have a look at Piecuch's methods (and his group's general work) for which now there is a plugin available https://github.com/piecuch-group/psi4_cct3 .

**Comment by TiborGY** [comment]
> 

> PSI4 has UBCC(T) `energy('bcc(t)')` on a ROHF reference, but only conventional integrals with the `ccenergy` module. Maybe you already found it.

o_O No, in fact I would have completely missed that! I checked the method table [here](http://www.psicode.org/psi4manual/master/notes_c.html#alternate-implementations) and thought Psi4 cannot do BCCD(T) at all. Perhaps BCCD and BCCD(T) could be added as methods to that docpage?

> 
> You may want to have a look at Piecuch's methods (and his group's general work) for which now there is a plugin available https://github.com/piecuch-group/psi4_cct3 .

Thanks, I will check it out.

**Comment by JonathonMisiewicz** [comment]
> I kinda thought you solved all the the DFOCC convergence issues recently, at great effort.

OCC convergence issues, not DFOCC convergence issues. The same trick should solve the convergence issues in DFOCC, but DFOCC is a much more difficult module to work with, so I'm avoiding fixing things there unless absolutely necessary for my research.

> Unfortunately, open-shell Brueckner or OO coupled cluster does not seem to be a common feature in QC programs, so I am trying to survey which programs have open-shell capable OO methods. Also, a performant OMP2 or OMP2.5 implementation could potentially be useful for us, even if it does not directly solve the lack of an RBCCD(T) implementation.

I don't know if your Robosurfer can use this, but depending on your orbital-optimized method, once you have the energy, the gradient is free. All the orbital-optimized methods in Psi have this property.

> o_O No, in fact I would have completely missed that! I checked the method table [here](http://www.psicode.org/psi4manual/master/notes_c.html#alternate-implementations) and thought Psi4 cannot do BCCD(T) at all. Perhaps BCCD and BCCD(T) could be added as methods to that docpage?

That page is for methods that _multiple modules_ support, so you can straighten out which module you want given your specific use for a method.

That said, is there a place in the manual where we list all the methods we have? I genuinely don't think so. We should add it, if there isn't one.

If you want to see all the energy keywords that Psi recognizes, you can find it in the code [here](https://github.com/psi4/psi4/blob/master/psi4/driver/procrouting/proc_table.py#L41).

I'd be remiss if I didn't point out that the `dct` module _also_ has some orbital optimized methods. The best one is the default upon entering `energy(dct)`, ODC-12. Use of the others is not recommended for _any_ purpose other than benchmarking.

We also have density-fitting for ODC-12. I'll warn you that there is some slight error in the DF gradients, on the order of E-5. That is _also_ on my to-fix list, but given some other papers I need to write, I don't expect to get to that until Winter 2020.

The other potential dealbreaker is that method _also_ lacks frozen core support, DF or not. Fixing that is a Spring 2021 target.

**Comment by loriab** [comment]
Yeah, that "fc not implemented for oo" message is of module scope. That's not unreasonable for a module author to write, but it is harder to interpret b/c of the known connection btwn occ/dfocc. And reasonably impossible for an outsider who sees psi as a cohesive entity to interpret.

Some mention in the docs would be nice. But the scalable way forward as I see it is to add ae/fc to managed methods like https://github.com/psi4/psi4/pull/1850/files#diff-dbf22cd80d16f6d8ef8250145a6d91bfR153 and to expand explicit testing for NYI https://github.com/psi4/psi4/pull/1850/files#diff-ac285870f28f146a56a93bd3592ff776R154. That way, a user who doesn't specify a module will get a "can't do" at the driver level and module authors can stay module-local in their messaging.
