### ISSUE TITLE
Crash due to "Timer ccenergy is not on." if maxiter is exceeded in CCENERGY

### ISSUE THREAD

**Issue by TiborGY** [psi4/psi4#1864]
If during a BCCD(T) calculation CCENERGY errors out due to the CC iterations not converging, Psi4 crashes with an error due to a timer not being on. Cut down input that intentionally triggers the issue:
```
memory 8 GiB
molecule {
0 2
H  3.14661583 0.50221279  16.95640639
H  -2.34237367 -1.18278602  -9.14879752
H  -1.21364759 -0.97589031  -7.97279014
H  -0.76962046 -0.48732090  -9.68891324
H  -2.68966560 0.90001402  -8.13713011
O  3.52147514 -0.34931909  16.40682068
O  -2.05471741 0.80770143  -8.67788722
C  -1.63014171 -0.50652361  -8.79096870
symmetry c1
}

set basis aug-cc-pvdz
set reference rohf
set ints_tolerance 1e-14
set d_convergence 5e-9
set e_convergence 1e-10
set ccenergy maxiter 2

energy('BCCD(T)')
```

Tail of the produced output:
```
                Solving CC Amplitude Equations
                ------------------------------
  Iter             Energy              RMS        T1Diag      D1Diag    New D1Diag    D2Diag
  ----     ---------------------    ---------   ----------  ----------  ----------   --------
     0        -0.533075915819886    0.000e+00    0.006541    0.000000    0.000000    0.000000
     1        -0.556071307119493    7.982e-02    0.013677    0.000000    0.000000    0.000000
     2        -0.568751401183405    2.374e-02    0.014574    0.000000    0.000000    0.000000

     ** Wave function not converged to 1.0e-07 ** 

Traceback (most recent call last):
  File "/home/jzz/psi4conda/bin/psi4", line 331, in <module>
    exec(content)
  File "<string>", line 40, in <module>
  File "/home/jzz/psi4conda/lib//python3.7/site-packages/psi4/driver/driver.py", line 570, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/jzz/psi4conda/lib//python3.7/site-packages/psi4/driver/procrouting/proc.py", line 2673, in run_bccd
    ref_wfn = core.ccenergy(ref_wfn)

RuntimeError: 
Fatal Error: Timer ccenergy is not on.
Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1584239292352/work/psi4/src/psi4/libqt/timer.cc on line: 1143
The most recent 5 function calls were:

psi::timer_off(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)



Printing out the relevant lines from the Psithon --> Python processed input file:
    core.set_global_option("REFERENCE", "rohf")
    core.set_global_option("INTS_TOLERANCE", 1e-14)
    core.set_global_option("D_CONVERGENCE", 5e-9)
    core.set_global_option("E_CONVERGENCE", 1e-10)
    core.set_local_option("CCENERGY", "MAXITER", 2)
--> energy('BCCD(T)')

    Psi4 stopped on: Friday, 10 April 2020 10:27PM
    Psi4 wall time for execution: 0:00:27.38

*** Psi4 encountered an error. Buy a developer more coffee!
```

**Comment by JonathonMisiewicz** [comment]
I'm not going to debug this myself, but if a new developer wants to take this on, the first steps are simple enough. Compile a debug build, run the input file with a breakpoint on the timer.cc:1143, then get the traceback to see which timer we're trying to turn _off_ that was never turned _on_. You can figure out a fix from there.

**Comment by andysim** [comment]
In the middle of some other stuff right now so also can't debug, but my money is on [this line](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/cc/ccenergy/ccenergy.cc#L307) being the problem.  Somebody just needs to verify that the `ccenergy` timer never gets started.  If that's the case, the line can be deleted.

**Comment by andysim** [comment]
Ah, yes, I'm right (for once).  The `ccenergy` timer is stopped on the line I linked.  Then the `exit_io` call on the line below attempts to stop it again, triggering the bug.  The fix is to delete the line that I linked.  It will be good practice to learn the pull request process for anybody who wants to implement it.  Also, kudos for the minimal working example in your bug report @TiborGY - it really helps.

**Comment by JonathonMisiewicz** [comment]
This issue has been open for almost a month now. I'll deal with this in a week if it hasn't been taken by then.

I've plugged this as a good new developer issue in the HFS group, so we'll see if anything happens.

**Comment by TiborGY** [comment]
> 
> 
> This issue has been open for almost a month now. I'll deal with this in a week if it hasn't been taken by then.
> 
> I've plugged this as a good new developer issue in the HFS group, so we'll see if anything happens.

I might have done it, but at the moment I cannot really invest the time to properly set up a dev env (especially all the numpy/BLAS/OMP dependency migraine), fix the issue, and send in a PR.
Sorry.

**Comment by JonathonMisiewicz** [comment]
This issue has a bit more to it than just removing the line Andy mentioned. The computation dies due to `'psi4.core.variable: Requested variable BRUECKNER CONVERGED was not set!\n'`, rather than the fact that convergence failed.

Is there a standard way to represent a convergence error, C-side? `dct` and LMP2 in `cc` throw `ConvergenceError`, failure during an orbital-optimized `occ` computation gets you a generic `PSIEXCEPTION`, and I haven't checked other things.
