### ISSUE TITLE
New Error Printing Bungles Newlines

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#1867]
The new error printing in #1862 seems to struggle when the message it's trying to print contains newlines. Consider the following input file

```
molecule {
 symmetry c1
 N
 N 1.500
}
set {
     basis cc-pVD
}
energy('scf')
```

This will raise a syntax error because I have a malformed Z-matrix. The new box will print out

```
!----------------------------------------------------------------------------------!
!                                                                                  !
!  Unprocessable Molecule remanents under [psi4, xyz, xyz+, psi4+]: symmetry c1  N !
! N 1.500                                                                          !
!                                                                                  !
!----------------------------------------------------------------------------------!
```

where the original error message is the more readable

```
qcelemental.exceptions.MoleculeFormatError: Unprocessable Molecule remanents under [psi4, xyz, xyz+, psi4+]:
symmetry c1
 N
 N 1.500
```

**Comment by hokru** [comment]
All newlines are removed in favour of a making a single long string that can be easily wrapped.
But one could instead wrap all lines of the error message separately to preserve these kind of formatted errors?

**Comment by dgasmith** [comment]
Oh yea, this need to have a double split so that original line breaks are kept.
```python
lines = []
for x in msg.splitlines():
      lines.extend(wrap(x, linewidth).splitlines())
```

**Comment by hokru** [comment]
I have a PR ready. It will probably be not the last modification.
