### ISSUE TITLE
libiomp5.dylib not found

### ISSUE THREAD

**Issue by bsenjean** [psi4/psi4#1870]
Hi,

I am trying to install psi4 from source, as I need one feature recently added in psi4.
I am working on MacOS but uses GNU compiler (v8.3.0) because I don't manage to make it work with clang, and I'm usually always using GNU anyway.

After several trial and error, I manage to build the code with the following CMake options:

cmake -H. -Bobjdir -DCMAKE_CXX_FLAGS="-march=native" -DOpenMP_LIBRARY_DIRS=/opt/intel/lib

Once built, I tried the ctest command to see if everything was working, but all tests fail with the error that libiomp5 seems to not be found. However, I have the following libraries in /opt/intel/lib:
libiomp5.a
libiomp5.dylib
libiomp5_db.dylib
libiompstubs5.a
libiompstubs5.dylib

Here is the error output for the test:
```
252/448 Testing: nbody-convergence
252/448 Test: nbody-convergence
Command: "/usr/local/bin/python3" "/Users/bsenjean/Documents/Git_repositories/psi4/tests/runtest.py" "/Users/bsenjean/Documents/Git_repositories/psi4/tests/nbody-convergence/input.dat" "/Users/bsenjean/Documents/Git_repositories/psi4/objdir/testresults.log" "false" "/Users/bsenjean/Documents/Git_repositories/psi4" "false" "/Users/bsenjean/Documents/Git_repositories/psi4/objdir/tests/nbody-convergence/output.dat" "/Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/bin/psi4" "/Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/share/psi4" "/Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/"
Directory: /Users/bsenjean/Documents/Git_repositories/psi4/objdir/tests/nbody-convergence
"nbody-convergence" start time: Apr 16 15:44 CEST
Output:


Traceback (most recent call last):
  File "/Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/__init__.py", line 55, in <module>
    from . import core
ImportError: dlopen(/Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/core.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libiomp5.dylib
  Referenced from: /Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/core.cpython-37m-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/bin/psi4", line 184, in <module>
    import psi4
  File "/Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/__init__.py", line 60, in <module>
    raise ImportError("{0}".format(err))
ImportError: dlopen(/Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/core.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libiomp5.dylib
  Referenced from: /Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/core.cpython-37m-darwin.so
  Reason: image not found
Exit Status: infile ( 1 ); autotest ( None ); sowreap ( None ); overall ( 1 )
<end of output>
Test time =   0.40 sec

Test Failed.
"nbody-convergence" end time: Apr 16 15:44 CEST
"nbody-convergence" time elapsed: 00:00:00
```

Thank you for your help !

**Comment by andysim** [comment]
It looks like you are linking against Intel OMP libraries in `/opt/intel/lib`, which could be quite tricky.  It looks like the dynamic libraries are not being found at run time.  What's the output of `otool -L /Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/core.cpython-37m-darwin.so`?

**Comment by loriab** [comment]
Adding `/opt/intel/lib` to envvar `DYLD_LIBRARY_PATH` will probably fix your immediate problem.(The `-DOpenMP_LIBRARY_DIRS` can only influence how the lib gets built, not the runtime env.)

A greater concern is that your psi and the numpy you use in running it need to have the same blas (hopefully MKL) libraries and the same threading (omp/iomp5 vs. gomp; gomp *strongly* discouraged), and gcc _really_ wants to link gomp in there. If you do get a working compile, make sure to run a simple test (like tu1) again with multiple threads to make sure it gives the correct answer before declaring victory.

**Comment by bsenjean** [comment]
Thank you for your fast answers ! 

@loriab, this indeed solved my problem. The first test failed but the other passed for now (still running). I will provide you a feedback on the tests which fail when it is finished. I'll also run the test you suggest.

@andysim This is the results of the output of the command you asked:
```
/Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/core.cpython-37m-darwin.so:
	@rpath/core.cpython-37m-darwin.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
	@rpath/libmkl_rt.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libiomp5.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/local/opt/gcc@8/lib/gcc/8/libgomp.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/local/opt/gcc@8/lib/gcc/8/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.25.0)
	/usr/local/lib/gcc/8/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by bsenjean** [comment]
Ok I got the following test failures:

```
252:nbody-convergence
306:psimrcc-ccsd_t-4
420:psi4numpy-cphf
421:psi4numpy-dfmp2
422:psi4numpy-rhf
423:psi4numpy-rhf-gradient
424:psi4numpy-rhf-hessian
425:psi4numpy-fci
429:python-energy
430:python-curve
431:python-pubchem
432:python-mints9
433:python-mints2
434:python-cc54
435:python-3-index-transforms
436:python-mints13
437:python-cc_amps
438:json-schema-1-energy
439:json-schema-1-ghost
440:json-schema-1-orient
441:json-schema-1-throws
442:json-schema-1-gradient
443:json-schema-1-properties
444:gcp-pbeh3c
445:gcp-hf3c
446:gcp-hf3c-gradient
447:gcp-hf3c-hessian
448:gcp-dft-custom-hybrid
```

And now my problem is on the import psi4. I tried adding the correct PYTHONPATH as follows:

```
export PATH=/usr/local/bin:$PATH  # python interpreter
export PATH=/Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/bin:$PATH  # psi4 executable
export PYTHONPATH=/Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib//:$PYTHONPATH  # psi4 pymodule
```

But I get a new kind of error. Any idea how to fix it? :

```
>>> import psi4
Traceback (most recent call last):
  File "/Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/__init__.py", line 55, in <module>
    from . import core
ImportError: dlopen(/Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/core.cpython-37m-darwin.so, 2): Symbol not found: __gfortran_concat_string
  Referenced from: /Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/core.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/core.cpython-37m-darwin.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/__init__.py", line 60, in <module>
    raise ImportError("{0}".format(err))
ImportError: dlopen(/Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/core.cpython-37m-darwin.so, 2): Symbol not found: __gfortran_concat_string
  Referenced from: /Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/core.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/core.cpython-37m-darwin.so
```

**Comment by hokru** [comment]
Are you compiling all standard addons by yourself or are you using pre-compiled libraries from miniconda?

**Comment by bsenjean** [comment]
I'm compiling everything by myself. I think the error might be because I got rid of the ```libstdc++``` flag, because I configured with:
```-DCMAKE_CXX_FLAGS="-march=native" ```

This might be an issue related to:
https://stackoverflow.com/questions/35006614/what-does-symbol-not-found-expected-in-flat-namespace-actually-mean

But when I kept it I couldn't configure if I remember correctly. I will check this again.

**Comment by hokru** [comment]
flat namespace errors are a nightmare..

It is easier and faster to compile against the `psi4-dev` miniconda package.
It comes with a cmake advisor (run `psi4-path-advisor -h)` that will set a correct `cmake` command line with proper flags and library location.
Custom CXX_FLAGS should not be needed anymore then.
You can use the miniconda provided gcc/clang setup or your own gcc.

**Comment by bsenjean** [comment]
So do you mean I should follow those instructions?:

```
 git clone https://github.com/psi4/psi4.git && cd psi4
 conda create -n p4dev psi4-dev python=3.7 -c psi4/label/dev
 conda activate p4dev
 `psi4-path-advisor --clang`
 cd objdir && make -j`getconf _NPROCESSORS_ONLN`
```

but replace ```--clang``` by ```-h```?

**Comment by andysim** [comment]
I'm pretty sure that the missing `__gfortran_concat_string` lives in `libgfortran.dylib`.  Try adding the `/path/to/gcc/lib64` to the `DYLD_LIBRARY_PATH`, after verifying that `libgfortran.dylib` is in that folder.  Don't forget to add it to the path, rather than replace the entry that @loriab suggested you add earlier.

**Comment by hokru** [comment]
Those introductions should be fine.
At some point the options for the path-advisor changed and the manual is not 100% up to date i think.
`--clang` still exists, but if you want your own gcc you leave it out. `-h` just gives you the help.

**Comment by loriab** [comment]
The `psi4-dev` pkg is generally preferred (though probably need to update qcel and qcng separately these days), but `--clang` is valid for Mac only and `--gcc` for Linux only.

For single-core, I wouldn't be surprised if you're pretty close, since the psithon tests overwhelmingly worked. I'd try Andy's library manip, but I'm also a little suspicious of `/usr/local/bin/python` unless that's truly your everyday python and you install (or build) numpy w/MKL to that installation's site-packages.

**Comment by bsenjean** [comment]
@andysim  Thanks, I added the path to this library but it doesn't fix the issue:
```
export DYLD_LIBRARY_PATH=/opt/intel/lib:/usr/local/gfortran/lib/
source ~/.bash_profile
```

I'm now trying the installation suggested by @hokru.

**Comment by bsenjean** [comment]
Ok then no point of trying the ```psi-dev``` as I'm on a Mac but want to use ```gcc``` (right?).

@loriab I just reinstalled python few days ago with homebrew. Before it was installed with the psi4conda package but I decided to get rid of it for now, as I want the source version of the code. But then I reainstalled numpy using pip, as follows, so I guess it's ok?:

```$> pip3 install numpy
Requirement already satisfied: numpy in /usr/local/lib/python3.7/site-packages (1.18.2)```

**Comment by loriab** [comment]
The `pip` numpy probably doesn't use MKL (you'd have to `otool -L` one of numpy's internal `.dylib`s to figure out where it's getting blas and what threading library it's using), so that can interact very badly (wrong answers or n-thread-dependent answers) with a psi4 that does use MKL.

If your aim is solely psithon (running psi as executable), you may want to backtrack to before the triple export when ~all the testsuite besides the psiapi (start with json/psi4numpy/python) was working, run `which python psi4` to confirm you're running what you expect, check the multithreaded answers to make sure that's not wrong, then work with that until I get a recent nightly build up.

What you're doing (Mac + GCC + indep numpy) should be perfectly do-able, but Psi needs MKL for best performance (and it's easy to get _wrong_ performance from other libs) and that means numpy needs to be MKL (whichever symbols of numpy or psi loaded first are what the other one has to use, so it's best if they're identical) so we encourage the conda groove for numpy.

The psi4-dev (w/o --clang/intel/gcc) that Holger mentioned will help compiling with conda python, numpy, libint, etc. But it isn't powerful enough to counteract the gomp that gcc will try to impose.

**Comment by bsenjean** [comment]
Thanks a lot for this detailed answer. I need some time to understand everything as I'm a beginner on those issues. I'll try different things according to your advices and report here when I'm done.

**Comment by bsenjean** [comment]
I've reinstalled everything and indicated the path to the libstdc++, so this might fix the issue I had before (I'm running the tests now and I'll see).

Just a small question. I did the ```otool -L``` as follows, does the output looks good to you ?

```
otool -L /Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/core.cpython-37m-darwin.so
/Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/core.cpython-37m-darwin.so:
	@rpath/core.cpython-37m-darwin.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
	@rpath/libmkl_rt.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libiomp5.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/local/opt/gcc@8/lib/gcc/8/libgomp.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/local/opt/gcc@8/lib/gcc/8/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.25.0)
	/usr/local/lib/gcc/8/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

About numpy, I have something like this, does it look good as well ?
```
otool -L /usr/local/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so
/usr/local/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so:
	@loader_path/../.dylibs/libopenblasp-r0.3.7.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
```

Otherwise, do you advise me to download the INTEL distribution ? https://software.intel.com/en-us/distribution-for-python/choose-download

**Comment by loriab** [comment]
It might work for single thread. But the openblas in numpy and the gomp in psi4 were what I was afraid of.

I haven't tried the Intel distribution of Python. I expect it'd do nicely and be similar to the conda packages.

**Comment by bsenjean** [comment]
So I've installed the intel distribution of Python, and now the numpy seems ok (no more openblas):

```
bsenjean@MBP-de-Bruno:~/Documents/intelpython3/pkgs/numpy-base-1.17.5-py37_1/lib/python3.7/site-packages/numpy/linalg]$ otool -L lapack_lite.cpython-37m-darwin.so
lapack_lite.cpython-37m-darwin.so:
	@rpath/libmkl_rt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
	@rpath/libimf.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libsvml.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libirng.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 800.7.0)
	@rpath/libintlc.dylib (compatibility version 1.0.0, current version 1.13.0)
```

However, after reinstalling psi4, it still has gomp:
```
bsenjean@MBP-de-Bruno:~/Documents/Git_repositories/psi4/objdir]$ otool -L /Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/core.cpython-37m-darwin.so
/Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/core.cpython-37m-darwin.so:
	@rpath/core.cpython-37m-darwin.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
	@rpath/libmkl_rt.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libiomp5.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/local/opt/gcc@8/lib/gcc/8/libgomp.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/local/opt/gcc@8/lib/gcc/8/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.25.0)
	/usr/local/lib/gcc/8/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

As you said, it seems ```gcc``` tries to impose ```gomp```. How can I bypass it ?
Because I still have the error:
```
E   ImportError: dlopen(/Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/core.cpython-37m-darwin.so, 2): Symbol not found: __gfortran_concat_string
E     Referenced from: /Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/core.cpython-37m-darwin.so
E     Expected in: flat namespace
E    in /Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/core.cpython-37m-darwin.so
```

which (I think) is due to that right ?

**Comment by hokru** [comment]
Btw, which OSX version do you use? 

You still need to get libgfortran.dylib in there somewhere to get rid of this error. See @andysim answer above. You could also try a flag like `-DCMAKE_FFLAGS='-lgfortran'` (not sure..)

If it's any consolidation, I am compiling psi4 with gcc9(homebrew) and MKL against `psi4-dev` conda and also cannot get rid of `gomp`. This breaks threading for me, but serial execution is fine and anyway enough workload for my old macbook.

**Comment by bsenjean** [comment]
Yes I've tried @andysim answer above about libgfortran.dylib already but it didn't solve it. I'll try the ```-DCMAKE_FFLAGS='-lgfortran'``` you suggest.

I am actually fine having a serial execution only as well on my laptop, all I want is this ```import psi4``` to work. You said you couldn't get rid of gomp so how did you bypass it to only have the serial distribution ?

**Comment by hokru** [comment]
> You said you couldn't get rid of gomp so how did you bypass it to only have the serial distribution

I didn't. Just make sure you don't use more than 1 thread.

The problem, as @loriab explained me once, is to somehow tell the linker to exclude `gomp`.
This works on Linux but not on OSX. If you know a way you can try here:
https://github.com/psi4/psi4/blob/master/external/common/lapack/FindMathOpenMP.cmake#L80-L85

**Comment by bsenjean** [comment]
I realize I did not answer to your question about my Mac version: MacOS Mojave, 10.14.5.

Thanks for the tips !

**Comment by bsenjean** [comment]
What is the difference between building from source or using the conda installer, but choosing the nightly build ? Because the conda installation seems to work on my laptop compare to the source one. As I just need the developper version, i.e. the last one on the master branch of Github, I wonder if the conda installation is sufficient or not ?

```
conda install psi4 psi4-rt python=3.7 -c psi4/label/dev
conda activate p4dev
```

**Comment by hokru** [comment]
Building from source builds from the current head of the master, while the psi4 binary in `psi4/label/dev` is currently not really "nightly" and maybe be older.  The lastest version is 1 month old.

What recent feature do you need?

**Comment by JonathonMisiewicz** [comment]
He needs [#1861](https://github.com/psi4/psi4/pull/1861), which enables reading serialized wavefunctions for CASSCF/CASCI/`detci` computations. That is not on `conda` "nightly".

**Comment by bsenjean** [comment]
If you tell me that this will be in the conda "nightly" in about a month, I can wait. The feature I need is important but not of absolute necessity for now.

**Comment by hokru** [comment]
This is what I do for my Catalina build with gcc9/mkl against conda python+libraries. 

a) get `psi4-dev psi4-rt psi4 -c psi4/label/dev` from conda (conda psi4 binaries plus dependencies to build from source)
(`conda remove -f v2rdm_casscf` because it gives symbol errors)
b) `export PATH=/Users/kruse/homebrew/bin:$PATH` for my homebrew gcc-9
c) run the below script (This is what `psi4-path-advisor` gave me plus making sure the correct compilers are used, plus a custom installation dir. Since recently I also have to turn of 2 default plugins because of symbol problems `-DENABLE_ambit=OFF -DENABLE_CheMPS2=OFF`, might not be necessary for everyone)

```
#!/bin/bash
export MKLROOT=/Users/kruse/qc/miniconda3
rm -rif objdir
/Users/kruse/qc/miniconda3/bin/cmake    -H.    -C/Users/kruse/qc/miniconda3/share/cmake/psi4/psi4DepsCache.cmake    -C/Users/kruse/qc/miniconda3/share/cmake/psi4/psi4DepsMKLCache.cmake -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9 -DCMAKE_Fortran_COMPILER=gfortran-9    -Bobjdir -DCMAKE_INSTALL_PREFIX=/Users/kruse/qc/psi4.bin -DENABLE_ambit=OFF -DENABLE_CheMPS2=OFF
```

**Comment by bsenjean** [comment]
Ok the build is finally over with the new options I provided in the configure steps and now it works ! It was indeed, as many of you suggested already, this libgfortran.dylib issue. After some trials and errors (that's why I took so much time, sorry about that), here is the configure options that worked for me:

```
cmake -H. -Bobjdir -DOpenMP_LIBRARY_DIRS=/opt/intel/lib -DCMAKE_Fortran_FLAGS="-L/usr/local/opt/gcc@8/lib/gcc/8 -lgfortran"
```

@JonathonMisiewicz now the restart with ```'fci'``` works ! But for ```'casscf'``` I get the following error:

```
Could not find requested basisset (DF_BASIS_SCF).Traceback (most recent call last):
  File "PSI4_CAS_sim.py", line 89, in <module>
    CASSCF_energy = psi4.energy('casscf', molecule=mol, ref_wfn=original_wfn,  return_wfn=False)
  File "/Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/driver/driver.py", line 570, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/driver/procrouting/proc.py", line 4804, in run_detcas
    ciwfn = mcscf.mcscf_solver(ref_wfn)
  File "/Users/bsenjean/Documents/Git_repositories/psi4/objdir/stage/lib/psi4/driver/procrouting/mcscf/mcscf_solver.py", line 100, in mcscf_solver
    mcscf_obj = ciwfn.mcscf_object()
RuntimeError: 
Fatal Error: Wavefunction::get_basisset: Requested basis set (DF_BASIS_SCF) was not set!

Error occurred in file: /Users/bsenjean/Documents/Git_repositories/psi4/psi4/src/psi4/libmints/wavefunction.cc on line: 670
```


Though that's not related to the issue here so I guess I can ask it on the forum or in another github issue ?

Thanks a lot, all of you, for your precious help !

**Comment by hokru** [comment]
Either new forum or github issue. 

Please close this issue if it is resolved for you.
