### ISSUE TITLE
Inconsistent `psimrcc` Warnings

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#1877]
For historical reasons, Mk-MRCC was only implemented in Psi4 assuming small active spaces, and `psimrcc` rightly gives you [two](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/psimrcc/main.cc#L114-L124) [warnings](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/psimrcc/main.cc#L130-L143) that the equations it is using are not the exact Mk-MRCC equations if your active space is any larger.

If you use Mk-MRPT2, the first warning fires, but the second does not. Further, the error message is specific to Mk-MRCC and says nothing about Mk-MRPT2. Is the Mk-MRPT2 procedure implemented in `psimrcc` exact or approximate? If it's exact, we need to stop the first warning from firing for Mk-MRPT2. If it's approximate, we need to make sure the second warning does fire for Mk-MRPT2. I checked the original paper, but couldn't find a clear statement either way, and I'd rather not learn Mk-MRCC theory just to fix this error message.

I'm going to get back to giving `psimrcc` a wavefunction, so I'll fix this as part of that PR. I need to touch this part of the logic anyways.

@fevangelista? @andysim?

**Comment by fevangelista** [comment]
Ok, so this is the issue. When you compute matrix elements of the effective Hamiltonian, <Psi_nu | Hbar(mu)|Psi_mu>, if the two determinants Psi_mu and Psi_nu differ by more than a double excitation you need the higher moments of the CC equations. These are not implemented in psimrcc. That's the reason for the warning in the CC code. In the PT2 code, everything is truncated at the second-order, and the matrix elements <Psi_nu | Hbar(mu)^(2) |Psi_mu> exist up to difference in three electron substitutions. So, I checked the paper and the code. The paper shows the formulas for the three-body couplings and some of these terms are coded in `psiumrcc/idmrpt2_Heff.cc` but are never called! So, the same warning should apply to PT2. My guess is that we were in the process of implementing them but then stopped (cannot remember why). So the following functions are dead code:
```
    void build_Heff_ijkabc();
    void build_Heff_ijKabC();
    void build_Heff_iJKaBC();
    void build_Heff_IJKABC();
```

**Comment by JonathonMisiewicz** [comment]
Thanks for the investigation!

Am I clear to remove dead code in `psimrcc` so we have less to maintain, or do you want it kept around in case somebody decides to pick up?

If you want dead code removed, be warned that all of `MP2_CCSD` seems to be dead code.

**Comment by fevangelista** [comment]
Let's go for removing the code. I think if there is some interest, someone will have to re-derive everything from scratch and understand how to implement it anyway. Can we hold onto `MP2_CCSD` for a bit more? I am not aware of anyone using it but I am thinking that perhaps I should finally write the article that was never written.

**Comment by JonathonMisiewicz** [comment]
That all sounds good to me.

Hopefully last question: I have most of the globals on the wavefunction at this point, but there are two left that I'm inclined to just delete. `debugging` and `memory_manager`. I think the `memory_manager` should just be replaced by using smart pointers and using other tools for memory profiling. The vast majority of the debug calls are printing tensors. Anybody debugging the code, I think, knows which tensors they want, and the rest are just noise.

Do you want either of those kept, or am I free to delete more?

**Comment by fevangelista** [comment]
I like your idea: let's get rid of debugging and convert memory_manager to a smart pointer. All this code was written pre C++11 so it does need some modernization. Thank you!

**Comment by JonathonMisiewicz** [comment]
For organization purposes:

- [x] Remove debugging
- [x] Remove dead three-body coupling terms
- [ ] Replace memory_manager with smart pointers (target of next PR)
- [ ] Add additional warning for PT (target of two PRs in, will also add the `wfn`)

I'm going to shift my focus back to a paper I'm writing but should resume the smart pointer-ing when I feel I need a break (probably a week or so).

**Comment by JonathonMisiewicz** [comment]
I'm now resuming work on this. Something I had overlooked previously was that most of the memory being managed were of containers of numeric types. Lots of `int *`, `double **`, `double ***`, and so on. What's the "right" way to modernize those? I haven't seen smart pointers being used for this before.

I'm inclined to convert to `std::vector` for things that are obviously not performance critical, but leave raw pointers otherwise. (_Especially_ for things that need to call BLAS.) Is this the right decision, or should I modernize differently?

**Comment by loriab** [comment]
My impression is that raw pointers are still fine (and widespread) for single module and single class usage, especially for picking data out of a larger structure to send to BLAS, so I wouldn't feel obliged to modernize those. But yeah, if today you'd type `std::vector` for a usage without a second thought, it'd be nice to update.

**Comment by JonathonMisiewicz** [comment]
Next PR should be the last one of the `psimrcc` series. I'm going to be occupied with referee reports for a while, so finishing this series is not a priority for me. Let me know if you need this out fast for 1.4 purposes.

**Comment by JonathonMisiewicz** [comment]
@fevangelista Am I clear to eliminate [`transform_tei_so_integrals`](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/psimrcc/transform.cc#L149) and other unused integral transformation code I find in `psimrcc`? I'm currently migrating the responsibility of storing memory expenses to the wavefunction, and getting rid of this dead code means less code to be responsible for.
