### ISSUE TITLE
inconsistency between release and developer version ?

### ISSUE THREAD

**Issue by bsenjean** [psi4/psi4#1878]
Hi,

I am now using the developer version 1.4a2.dev215, and I realized that some of my calculation are not giving the same results as before. I asked someone to do the same calculation with the release version of psi4 and we indeed have something really different.

We did H4, square shape. I enclose the output of both files. Note that this was done with the OpenFermion-Psi4 interface and the output contains HF, CISD, FCI and CCSD calculations.

I do not see any difference in the settings, so I don't understand why I get wrong HF energy for instance. Can anyone see something or knows something about it ?

[version_1.4a2.dev215.txt](https://github.com/psi4/psi4/files/4579640/version_1.4a2.dev215.txt)
[release_1.3.2.txt](https://github.com/psi4/psi4/files/4579639/release_1.3.2.txt)

**Comment by hokru** [comment]
FYI, although `Psi4 1.4a2.dev215 dfb86f5` is the latest mac developer version on conda. It is already 5 months old now.

There have been improvements and fixes to the SAD guess compared to `v1.3.2`. Though the SAD energy here seems to be equal. 
That's the first difference that comes to my mind now.

**Comment by susilehtola** [comment]
H4 is a system with significant static correlation and Hartree-Fock can converge to several possible solutions. In these cases it is important to always run stability analysis to ensure that you actually are at a local minimum.

You can also play around with different initial guesses to see if they land on different solutions.

**Comment by susilehtola** [comment]
I checked your calculation just for fun with a two-week old snapshot. I get
```
  ==> Iterations <==

                        Total Energy        Delta E     RMS |[F,P]|

   @RHF iter SAD:    -1.10951830992328   -1.10952e+00   0.00000e+00 
   @RHF iter   1:    -1.54125526228531   -4.31737e-01   0.00000e+00 DIIS
   @RHF iter   2:    -1.54125526228531    0.00000e+00   0.00000e+00 DIIS
  Energy and wave function converged.
```
which is the same solution as you reported with 1.3.2, only it converges in 2 iterations instead of 8. `guess huckel` and `guess core` also converge in 2 iterations, and they don't need the extra Fock build at the beginning.

**Comment by hokru** [comment]
For RHF calculations one can use `set stability_analysis check`.
While for UHF you can follow a solution with `set stability_analysis follow` automatically.

**Comment by bsenjean** [comment]
So with this ```stability_analysis check``` I get the following:

```
      Lowest singlet (RHF->RHF) stability eigenvalues:-
         A -0.905654        A -0.838815        A -0.700307        A 0.647034
  
      Lowest triplet (RHF->UHF) stability eigenvalues:-
         A -1.656571        A -1.464744        A -0.909775        A 0.250543
```

I don't know how to interpret those values ?

So maybe I should just git pull the last version of psi4 of the master branch ? It's not an issue if I have a mac right, is it ?

**Comment by hokru** [comment]
These are the lowest eigenvalues of the electronic Hessian showing you that you are not in a minimum. 
You can either search for a SCF guess that works or run it as a UHF calculation and use the `follow` keyword.

Compiling on mac is fine but multi-threading might not work well. I also use a mac. You might want do this: http://psicode.org/psi4manual/master/conda.html?highlight=advisor#how-to-use-conda-to-compile-psi4-faster-and-easier
The `psi4-dev` package can be installed to your existing psi4 dev version from psi4/label/dev. It installs compilers and needed libraries.

**Comment by bsenjean** [comment]
Ok, that was an interesting problem for this version of psi4 ! I now got the very last one and things work fine again:

```
                          Total Energy        Delta E     RMS |[F,P]|                   
                                                                                        
     @RHF iter SAD:    -1.10951830992328   -1.10952e+00   0.00000e+00                   
     @RHF iter   1:    -1.42989087630227   -3.20373e-01   2.63944e-02 DIIS
     @RHF iter   2:    -1.48669699030023   -5.68061e-02   1.49695e-02 DIIS
     @RHF iter   3:    -1.52194618795963   -3.52492e-02   1.34968e-02 DIIS
     @RHF iter   4:    -1.53906330108634   -1.71171e-02   5.44189e-03 DIIS
     @RHF iter   5:    -1.54087887085299   -1.81557e-03   2.40827e-03 DIIS
     @RHF iter   6:    -1.54117109557693   -2.92225e-04   1.16803e-03 DIIS
     @RHF iter   7:    -1.54123744472211   -6.63491e-05   5.44231e-04 DIIS
     @RHF iter   8:    -1.54125234553558   -1.49008e-05   2.21654e-04 DIIS
     @RHF iter   9:    -1.54125494714724   -2.60161e-06   7.30916e-05 DIIS
     @RHF iter  10:    -1.54125524201882   -2.94872e-07   1.85602e-05 DIIS
     @RHF iter  11:    -1.54125526151990   -1.95011e-08   3.60860e-06 DIIS
     @RHF iter  12:    -1.54125526228451   -7.64613e-10   1.18266e-07 DIIS
    Energy and wave function converged.                                                 
                                                                                        
      SO Integrals not on disk. Computing...done.
          Presorting SO-basis two-electron integrals.
          Sorting File: SO Ints (nn|nn) nbuckets = 1
          Transforming the one-electron integrals and constructing Fock matrices
          Starting first half-transformation.
          Sorting half-transformed integrals.
          First half integral transformation complete.
          Starting second half-transformation.
          Two-electron integral transformation complete.
          Starting first half-transformation.
          Sorting half-transformed integrals.
          First half integral transformation complete.
          Starting second half-transformation.
          Two-electron integral transformation complete.
      Lowest singlet (RHF->RHF) stability eigenvalues:-
         A 0.118946         A 0.152195         A 0.527951         A 0.790910  
      
      Lowest triplet (RHF->UHF) stability eigenvalues:-
         A -0.429230        A -0.408687        A 0.114615         A 0.215652  
```

Thank you for your help ! I'll close the issue.
