### ISSUE TITLE
Select TDMs Inaccessible

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#1890]
Carried forward from [forum post](http://forum.psicode.org/t/calculating-transition-and-state-density-matrices-and-dipole-moment-matrices/1784).

The API to get transition density matrix elements out of a `detci` computation currently fails unless the first state is zero. This is [not expected behavior](https://github.com/psi4/psi4/issues/1638#issuecomment-489080431). Doing `grep` for a minute leads me to think the culprit is [these lines](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/detci/opdm.cc#L113-L117). This looks like an extremely easy fix: just loop over another variable to change the first element in the tuple as well.

Can a developer more experienced in the ways of `detci` (probably @dgasmith) confirm this?

**Comment by dgasmith** [comment]
Those are the troubling lines for sure, extended them should work as long as the CI Vector is present (`n < num_roots`).

I mimicked the transition behavior from @cdsgroup original code. Might get him to weigh in here on the API.

**Comment by JonathonMisiewicz** [comment]
Ping for @CDSherrill to weigh in, per DGAS recommendation. I can fix this issue myself if you have nothing to add.
