### ISSUE TITLE
implement B97-3c composite method

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#1898]
what needs to happen:

- [x] wait for https://github.com/psi4/psi4/pull/1101
- [ ] update gcp used by PSI4 (I already have Gerrit's new code) (LAB edit: https://github.com/psi4/psi4/pull/2791)
- [ ] setup a modified B97 (GGA)
- [ ] provide the custom basis set
- [ ] hook up all components

If someone is eager to do this let me know, I can help. Otherwise I'll do it once the libxc5 move is complete.

**Comment by awvwgk** [comment]
The B97-3c SRB correction is now available with the latest `gcp` version at https://github.com/grimme-lab/gcp and via the conda package `gcp-correction`.

**Comment by loriab** [comment]
`gcp-correction` for qcng is in PR https://github.com/MolSSI/QCEngine/pull/290 . needs to be locally compiled for Linux, though, b/c the c-f packages use gomp. one can instruct the c-f recipe to build both mkl+iomp5 and openblas+gomp variants, but I need to do some experimentation to advise how.

**Comment by awvwgk** [comment]
OpenBLAS and MKL can be easily switched out by the usual conda-forge mechanism, not sure about OpenMP. Is there Intel OpenMP available on conda-forge?

**Comment by loriab** [comment]
explicitly only for Windows, https://anaconda.org/conda-forge/intel-openmp/files . but c-f mkl is pulling in `llvm-openmp`, which should be fine. https://anaconda.org/conda-forge/mkl/files

**Comment by awvwgk** [comment]
Windows distribution is a different issue, would a PKGBUILD for MSYS2 work for you?

**Comment by loriab** [comment]
I've got GHA+OneAPI+Windows+conda-build hacked together for dftd3 off the psi4 channel, so I can do the same for gcp. No need to worry about Windows + c-f for my part.

**Comment by susilehtola** [comment]
Basis tracker at 
https://github.com/MolSSI-BSE/basis_set_exchange/issues/151

**Comment by loriab** [comment]
closed by #2842
