### ISSUE TITLE
--test error

### ISSUE THREAD

**Issue by junjiang123** [psi4/psi4#1902]
Hi,

I encountered the following error message after I did the --test after installation

"_ ERROR collecting envs/p4env/lib/python3.7/site-packages/psi4/tests/test_addons.py _
'quick' not found in `markers` configuration option
_ ERROR collecting envs/p4env/lib/python3.7/site-packages/psi4/tests/test_dft_benchmarks.py _
'scf' not found in `markers` configuration option
_ ERROR collecting envs/p4env/lib/python3.7/site-packages/psi4/tests/test_fcidump_energy.py _
'quick' not found in `markers` configuration option
_ ERROR collecting envs/p4env/lib/python3.7/site-packages/psi4/tests/test_molecule_to_string.py _
'quick' not found in `markers` configuration option
_ ERROR collecting envs/p4env/lib/python3.7/site-packages/psi4/tests/test_psi4.py _
'quick' not found in `markers` configuration option
_ ERROR collecting envs/p4env/lib/python3.7/site-packages/psi4/tests/test_qcvars.py _
'quick' not found in `markers` configuration option
_ ERROR collecting envs/p4env/lib/python3.7/site-packages/psi4/tests/test_solvers.py _
'unittest' not found in `markers` configuration option
_ ERROR collecting envs/p4env/lib/python3.7/site-packages/psi4/tests/test_tdscf_excitations.py _
'unrestricted' not found in `markers` configuration option
_ ERROR collecting envs/p4env/lib/python3.7/site-packages/psi4/tests/test_tdscf_products.py _
'unittest' not found in `markers` configuration option
_ ERROR collecting envs/p4env/lib/python3.7/site-packages/psi4/tests/test_vector.py _
'quick' not found in `markers` configuration option
_ ERROR collecting envs/p4env/lib/python3.7/site-packages/psi4/tests/test_vibanalysis.py _
'quick' not found in `markers` configuration option
"

I am wondering what the issues are, and if the issues are just with the test files.

Thanks

JJ

**Comment by loriab** [comment]
It's no problem -- they're just warning that some of the test subset labels haven't been registered. All those warnings have vexed others, too, so it's set up to be fixed in #1351 and #1814 by the setup.cfg file. Thanks for the report!
