### ISSUE TITLE
Multi-reference CI calculation on C2

### ISSUE THREAD

**Issue by junjiang123** [psi4/psi4#1907]
Hi,
I am just wondering if anyone could provide an example/instruction how to carry out (or if it is feasible to carry out) MRCI calculation using Psi4. In this paper (https://doi.org/10.1063/1.1867379), it sounded like that it was possible to carry out MRCI on Psi 3.2, but I couldn't find much information on the Psi4 manual (nor on the Psi3 manual) on how to do that calculation. I was able to obtain CASSCF energies and wavefunctions, and was going to just use the CASSCF wavefunction as the reference for MRCI calculation, but had little success in doing so. The followings are my code (python), trying to optimize the energy for the C state of the C2 molecule (which has two main configurations near its equilibrium bond length). The paper included above deals with the X, B, and B' state of C2, but those are not the states that I want. (I want the singlet C state)

## geometry
c2=psi4.geometry("""
0 1
c 
c 1  1.25
symmetry d2h
""")
##

## use the C-state main electron configuration as the reference for CASSCF
psi4.set_options({
  'basis':               'cc-pVdz',
  'reference':           'rohf',
  'docc':                [2, 0, 0, 0, 0, 1, 0, 1],
  'socc':                [0, 0, 0, 0, 0, 1, 1, 0],
  'restricted_docc':     [1, 0, 0, 0, 0, 1, 0, 0],
  'active':              [2, 0, 1, 1, 0, 2, 1, 1],
  'mcscf_r_convergence': 5.e-6
})

psi4.set_module_options('detci',{
  'num_roots': 1,
  'calc_s_squared': True
})

casscf_energy, casscf_wfn = psi4.energy('casscf', return_wfn=True)

#the code works up to this point

## my way of feeding the casscf_wfn for another round of CI, but it did not work at all
psi4.set_options({
  'wfn': 'detci',
  'guess': 'gwh',
  'basis': 'cc-pVDZ',
  'restricted_docc': [1, 0, 0, 0, 0, 1, 0, 0],
  'active':          [2, 0, 1, 1, 0, 2, 1, 1],
  'e_convergence': 10,
  'd_convergence': 10
})

thisenergy = psi4.energy('detci',ref_wfn=casscf_wfn)

When I did the second round of CI, psi4 crashed. It got stuck at the "Starting CI iterations" part, with the error message "Segmentation fault: 11"

I am quite new to Psi4, but hopefully I am not talking complete non-sense here. Also, while the CASSCF bit worked, the CASSCF energy is much higher than I expected (by ~0.2 hartree). The C-state minimum lies above the 3P+3P limit, instead ~2-3 eV below it. So, it would also be helpful if someone could teach me the best way to carry out the CASSCF calculation on the C state.

Thanks,

JJ

**Comment by JonathonMisiewicz** [comment]
I see three different questions here:
1. Is it possible to carry out MRCI in Psi?
2. Can we get an error message better than a segfault, or for this not to segfault?
3. Does the energy error indicate you've landed on the wrong electronic state? If so, how do you land on the right one?

1. Reading that paper, it looks like Sherrill and Piecuch did (as you suspected), a two-step computation. First, they did a CASSCF computation. Then they used the orbitals from that computation to do a RASCI computation. Then they fed those orbitals into a RAS computation to do their MRCI. That said, I cannot figure out what keywords they might have used to specify the right excitation levels. None of the keywords in the manual level.
2. I would expect that the program should be able to accept orbitals this way. Unless another developer more experienced in detci sees otherwise, this looks to me a like a bug. I'll give some time for them to comment before investigating further myself.
3. Just to be clear, do you have any reason to think that you landed on the C electronic state? If not, you may have landed on a different electronic state entirely. I recommend you look at the section of your SCF computation marked "Final Occupation by Irrep". Is that consistent with your desired electronic state? Is there any other low-lying electronic state that occupation could match?

**Comment by junjiang123** [comment]
@JonathonMisiewicz 
Thanks for you reply. Your comments summarizes my questions very nicely. Now, I am just focusing on the CASSCF part first. 
I realized that there was a mistake in the 'docc' assignment in my previous run. The docc part should be: [3, 0, 0, 0, 0, 1, 1, 0]. I thought that I needed to exclude the restricted_docc in the docc input.
After correcting this mistake, I started calculating the potential energy curves (the lowest 6 Pi_g symmetry). However, I obtained some mysterious roots that I initially did not know what they were, but now I think these extra roots are the quintet (S=2) states that somehow show up in the calculation results, even though I asked for only the singlet (S=0) 

In the figure titled as Singlet_pig, the blue dots are the singlet states and the yellow dots are what I believe the quintet states. Note that straight from the calculations, there are two states that converge to the lowest C+C dissociation limit (triplet P+triplet P). This can't happen because triplet P+triplet P dissociation channel correlates with only one singlet Pi_g state. Now, the red curves are from a calculation that explicitly calculates quintet Pi_g states. The red curves overlap well with the yellow dots (except for one curve, which I don't understand). If I took out the quintet states (by looking at the coefficients of the CI determinants), the remaining singlet potential energy curves (Pi_g +Phi_g symmetry) agree with CASSCF calculations from Molpro (provided by my collaborator; I was trying to reproduce his curves)

![singlet_Pigs](https://user-images.githubusercontent.com/65833552/83825292-c1c90e00-a68d-11ea-9a30-1c0d8cdbdfe3.png)

I am wondering why do those quintet states show up in the calculation of singlet states. Similar things happen when I tried to calculate the triplet Pi_g states. (see the other figure). As you can see the extra roots occur at essentially the same spot in both singlet and triplet Pi_g calculations.
![triplet_Pigs](https://user-images.githubusercontent.com/65833552/83825891-6b5ccf00-a68f-11ea-8f21-4baae2e6f8cc.png)

**Comment by junjiang123** [comment]
@JonathonMisiewicz for completeness, at each R value, my CASSCF code is

psi4.set_options({
  'basis':               'cc-pVtz',
  'reference':           'rohf',
  'docc':                [3, 0, 0, 0, 0, 1, 1, 0],
  'socc':                [0, 0, 0, 0, 0, 1, 0, 1],
  'restricted_docc':     [1, 0, 0, 0, 0, 1, 0, 0],
  'active':              [2, 0, 1, 1, 0, 2, 1, 1],
  'MCSCF_MAXITER': 100
})

c2_geometry = """
0 1
c 
c 1 {0}
symmetry d2h
"""
psi4.set_module_options('detci',{'num_roots': 24,'follow_root': 0,'NUM_DETS_PRINT': 40})
#'follow_root' is set to either 0 or 1, depending on the R value

casscf_energy = psi4.energy('casscf')

**Comment by JonathonMisiewicz** [comment]
Thanks for waiting. I've had a lot to do lately.

Psi4 isn't interpreting your input file like you intended. Psi4 1.4 will contain an error message indicating something is an amiss.

The first issue is that you never actually create a molecule in the input fragment you gave me. Maybe you account for this in the full script, but if you don't, supply your string to the function `psi4.geometry`.

The second issue is a deeper one. Psi interprets all singly-occupied orbitals as alpha orbitals, so Psi sees your input file and thinks you want a singlet with two unpaired alpha electrons. That's physical nonsense, so Psi4 will (in an error message we added in 1.4) complain and refuse to proceed. In 1.3, it will not be smart enough to realize an issue, proceed, and potentially give nonsense. Of course, what you want is a singlet diradical ROHF state, with an unpaired alpha electron and an unpaired beta electron in each determinant in your linear combination. I know how to tell Psi you want a singlet, but I'm not aware of any way to further specify that you want a singlet diradical ROHF state.

Is there a reason why you need the diradical to be the starting point for your CASSCF?

**Comment by junjiang123** [comment]
@JonathonMisiewicz Thanks for your response
In the loop over R that I used to calculate the potential energy curves, I do have the "c2 = psi4.geometry(c2_geometry.format(R))" command, with c2_geometry defined in an earlier thread.

Regarding why I use a singlet diradical ROHF reference: it looks like, based on the DETCI module manual, DETCI only calculates excited states with the same irrep as the reference, and there is not a keyword for me to select irrep symmetry (please correct me if I am wrong here). As a result, in order for me to calculate the Pi_g manifold states (B2g+B3g in D2h), I need to use a B2g (or B3g) reference state, which for C2 (with an even number of total electron) is at least a biradical state. Also, as I mentioned before, I encountered the same problem when I calculated the triplet Pi_g manifold states, for which the issue with the alpha electrons in the ROHF reference shouldn't be an issue, right? (see the figure below for the triplet-state manifold, the yellow dots are what I think the quintet states)

![triplet_Pigs](https://user-images.githubusercontent.com/65833552/84192270-9871fe80-aa4e-11ea-84b3-9b8dd486edfe.png)

**Comment by junjiang123** [comment]
@JonathonMisiewicz for completeness, here is my full code:

import psi4
import numpy as np

psi4.set_options({
  'basis':               'cc-pVtz',
  'reference':           'rohf',
  'docc':                [3, 0, 0, 0, 0, 1, 1, 0],
  'socc':                [0, 0, 0, 0, 0, 1, 0, 1],
  'restricted_docc':     [1, 0, 0, 0, 0, 1, 0, 0],
  'active':              [2, 0, 1, 1, 0, 2, 1, 1],
  #'mcscf_r_convergence': 5.e-6
  'MCSCF_MAXITER': 100
})


psi4.set_memory('8000 MB')

c2_geometry = """
0 1
c 
c 1 {0}
symmetry d2h
"""

#singlet
a_end=1.325
b_start=1.355
a_num=10
b_num=20
aa=np.linspace(1,1.2,6)
a=np.linspace(1.25,a_end,3)  
b=np.linspace(b_start,2.5,b_num)
c=np.linspace(2.6,4,8)
Rvals=np.concatenate((aa,a, b, c), axis=None)

ecp = {}

for R in Rvals:
    if R<=a_end:
        psi4.set_module_options('detci',{'num_roots': 24,'follow_root': 0,'NUM_DETS_PRINT': 40})
    elif R>=b_start:
        psi4.set_module_options('detci',{'num_roots': 24,'follow_root': 1,'NUM_DETS_PRINT': 40})
        
    c2 = psi4.geometry(c2_geometry.format(R))
    casscf_energy = psi4.energy('casscf')
    ecp[R] = [casscf_energy,
        psi4.core.variable('ci root %d TOTAL ENERGY' %0),
        psi4.core.variable('ci root %d TOTAL ENERGY' %1),
        psi4.core.variable('ci root %d TOTAL ENERGY' %2),
        psi4.core.variable('ci root %d TOTAL ENERGY' %3),
        psi4.core.variable('ci root %d TOTAL ENERGY' %4),
        psi4.core.variable('ci root %d TOTAL ENERGY' %5),
        psi4.core.variable('ci root %d TOTAL ENERGY' %6),
        psi4.core.variable('ci root %d TOTAL ENERGY' %7),
        psi4.core.variable('ci root %d TOTAL ENERGY' %8),
        psi4.core.variable('ci root %d TOTAL ENERGY' %9),
        psi4.core.variable('ci root %d TOTAL ENERGY' %10),
        psi4.core.variable('ci root %d TOTAL ENERGY' %11),
        psi4.core.variable('ci root %d TOTAL ENERGY' %12),
        psi4.core.variable('ci root %d TOTAL ENERGY' %13),
        psi4.core.variable('ci root %d TOTAL ENERGY' %14),
        psi4.core.variable('ci root %d TOTAL ENERGY' %15),
        psi4.core.variable('ci root %d TOTAL ENERGY' %16),
        psi4.core.variable('ci root %d TOTAL ENERGY' %17),
        psi4.core.variable('ci root %d TOTAL ENERGY' %18),
        psi4.core.variable('ci root %d TOTAL ENERGY' %19),
        psi4.core.variable('ci root %d TOTAL ENERGY' %20),
        psi4.core.variable('ci root %d TOTAL ENERGY' %21),
        psi4.core.variable('ci root %d TOTAL ENERGY' %22),
        psi4.core.variable('ci root %d TOTAL ENERGY' %23)]
    
    psi4.core.clean()

**Comment by junjiang123** [comment]
@JonathonMisiewicz 
There is indeed a warning in the output file
"Warning: iopen=0,opentype!=closed. Making iopen=1"
but that just switch from a closed-shell to a open-shell calculation automatically for me, right? The exact same warning showed up in the triplet state calculation output file

**Comment by JonathonMisiewicz** [comment]
You're correct: DETCI only calculates excited states with the same irrep as the reference, and there is no keyword to select irrep symmetry directly.

It's been a few years since I've had to worry about diatomic symmetry, but let's see if I remember how this works. The two lowest energy singlet Pi gerade states are going to be [Be]p+ap-b and [Be]p-ap+b. However, Psi4 doesn't believe in complex orbitals. Ignoring normalization, p+ = px + i py, and p- = px - i py. Then using multilinearity of determinants, our states become (pxa + i pya)(pxb - i pyb) and (pxa - i pya)(pxb + i pyb) equalling (pxa pxb + i pya pxb - i pxa pyb + pya pyb) and (pxa pxb - i pya pxb + i pxa pyb + pya pyb). However, Psi4 doesn't believe in imaginary numbers. Taking the plus linear combination gives us (pxa pxb + pya pyb), and taking the - linear combination and normalizing away i gives us (pya pxb + pxa pyb).

The conclusion of all this math is that because Psi4 doesn't use complex orbitals or complex linear combinations, the electronic states you're looking for are simply **not** going to be well-described by a single (real) Slater Determinant. The only solution I see is to make peace with that and modify your target symmetry to match one of those determinants. pxa pxb does not look like a diradical to me.

**Comment by JonathonMisiewicz** [comment]
Closing issue. This doesn't seem to be an issue in Psi4, so much as a confusion about the implications of working with real wavefunctions.
