### ISSUE TITLE
PCM fails with symmetry group coordinates, need to add error message for this to help user

### ISSUE THREAD

**Issue by bdw2292** [psi4/psi4#1939]
Hello,

I realize that there is a warning about PCM failing with symmetry point groups however, it would be nice to add like a 1-3 line error message that would go a long way to helping out any user that has not read all of the docs very carefully.

**Comment by hokru** [comment]
Dear @bdw2292. Thanks for the report!
Yes, this is a bug that in principle also affects also other addons.
Also sorry for the late reply!

Please follow eventual discussions in #1978 as it's more general.
