### ISSUE TITLE
dft-cut-dens test fails with gcc5

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#1943]
wb97X-V with density threshold of 1e-10 stops before printing the first SCF/SAD energy in the SCF iteration output.

I dont have access to gcc5 and I cannot reproduce the error otherwise for now.

e.g.:
https://dev.azure.com/psi4/psi4/_build/results?buildId=2170&view=logs&j=96451287-da82-57a8-2c11-8da7db9ab71a&t=895e49e6-cad9-5b25-6d66-c0b61859d928&l=801

**Comment by loriab** [comment]
gtk. I've suspected that from some CI patterns, but hadn't forced a test yet. I think conda has gcc 5.4 compilers for linux, so I can probe.

**Comment by loriab** [comment]
hmpf, works fine with gcc54

```
>>> stage/bin/psi4 ../tests/dft-dens-cut/input.dat 
    is_libxc SuperFunctional..........................................PASSED
    is_libxc density_tolerance........................................PASSED
    Empty SuperFunctional.............................................PASSED
    C-only SuperFunctional............................................PASSED
    LibXCFunctional density_cutoff....................................PASSED
    SuperFunctional density_tolerance.................................PASSED
    X-only SuperFunctional............................................PASSED
    normal XC SuperFunctional.........................................PASSED
    individual screening..............................................PASSED
    screening value C.................................................PASSED
    screening value X.................................................PASSED
>>> $CXX --version
x86_64-conda_cos6-linux-gnu-c++ (crosstool-NG fa8859cb) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by hokru** [comment]
It did pass CI's gcc5 for the merge at least once.

**Comment by loriab** [comment]
10 runs produce 7 success and 3 segfaults, hooray! I can work with that.

**Comment by loriab** [comment]
Trouble happening at https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libfock/cubature.cc#L3536. When scheme is treutler, `opt.prunefunction` may not be getting set right -- I'm seeing random large numbers as its value.

**Comment by hokru** [comment]
Hmm, i see. Thank you for digging!

`opt.prunefunction` should be undefined since I didnt set it here: :https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libfock/cubature.cc#L4109 
I wasn't aware it is still used (it's not needed for the REGION scheme).

Is this https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libfock/cubature.cc#L3534 called whenever the class is initialized?

**Comment by PeterKraus** [comment]
Yeah, that looks like the constructor. https://github.com/psi4/psi4/blob/26bae16efac9e3bd212a7433def625f370fb9a17/psi4/src/psi4/libfock/cubature.cc#L3512

**Comment by loriab** [comment]
Yes, https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libfock/cubature.cc#L3620 calls 3534. I can completely avert the issue by #1945 but that may not be best. I think the opt is undefined at time of RadialPruneMgr construction and it's not a big int so it's sometimes undefined and segfaults. This is the first Treutler test in the suite.

**Comment by loriab** [comment]
@hokru #1945 squashes the issue but not in a thoughtful way, so feel free to forget it and propose a better. I'm glad to try anything out locally in a loop since it naturally fails only ~1/3 of the time.

**Comment by hokru** [comment]
That fix is what I would have proposed as well. I have no better solution short of a larger re-design.
