### ISSUE TITLE
Crash- overlapping atoms

### ISSUE THREAD

**Issue by wjg3** [psi4/psi4#195]
If two atoms get within 0.5 Bohr of each other, psi4 crashes. I tracked this down to the overlap matrix having NAN in rows/columns involving AOs centered on the overlapping atom. This seems to be a problem in the part of the code that computes atom mappings, because when I change the tol in petitelist.h:62 to:
`int **compute_atom_map(const Molecule* mol, double tol = 0.1);`
(and the line above), the problem goes away. It seems the AO shells are not created for the overlapping atom, even though parts of the code expect them. Setting c1 symmetry does not help.

Here's a small input deck that recreates the problem:

    #! H Ghost test
    
    molecule h  { 
    -1 1
    H                   0.00000000    0.00000000             0.0
    Gh(He)    0.0000000000    0.0000000000    0.2
    }
    
    
    set {
    SCF_TYPE DIRECT
    DF_SCF_GUESS FALSE
    print 4
    }
    
    basis {
    assign sto-3g
    }
    energy('scf')

**Comment by dgasmith** [comment]
@jturney @andysim @psi-rking Does anyone object to reducing the tolerance here? Alternatively we can make a special case for ghost atoms. Although two centers so close will increase linear dependency issues.

**Comment by psi-rking** [comment]
My only concern was that symmetrize uses atom_map, and optking uses symmetrize to remove numerical noise.  However, since the tolerance is passed through as an optional argument, I have no objection.

**Comment by andysim** [comment]
No objection here.

**Comment by dgasmith** [comment]
@psi-rking I would think `0.1` (bohr?) would be fairly large for numerical noise or is this incorrect?

It looks like `atom_map` is almost always called with the default `tol` exception in `Molecule::symmetrize`, so changing the default would be a nearly universal change.

**Comment by psi-rking** [comment]
Granted.  I was vaguely remembering that I also use 'valid_atom_map' to test whether RFO eigenvectors are symmetric - and they can be large and asymmetric.  But for valid_atom_map it looks like I pass a tolerance in from optking, so I don't forsee any problems.  Give it a shot.
