### ISSUE TITLE
DF-CCSD(T) Densities

### ISSUE THREAD

**Issue by JoshRackers** [psi4/psi4#1952]
It would extremely useful to have density fitted coupled cluster densities. I know these already exist for conventional coupled cluster, but the density fitted version is so much faster! Would love to see this feature in Psi4!

**Comment by JonathonMisiewicz** [comment]
We have DF-CCSD(T) analytic gradients, so we _have_ the densities. What I _think_ you mean is "to have density fitted coupled cluster densities _on the wavefunction object_." I haven't checked whether these are on the wavefunction or not, but I'd believe that they are not.

I'll get that there as part of the DF gradient refactor. Further progress on that is blocked by the integral changes in #1721.

**Comment by JoshRackers** [comment]
Correct. I can confirm that these are not on the wavefunction object right now. 

Thanks for following up. I'll bring this up again once #1721 is merged.
