### ISSUE TITLE
"Error writing to file" PSi0_error 12

### ISSUE THREAD

**Issue by bsenjean** [psi4/psi4#1959]
Hi,

I am trying to do a large CASCI (16e,16o) but I get an error which I don't understand. Note that the CAS(16e,14o) worked perfectly.

Here is the error:
```
PSIO_ERROR: unit = 53, errval = 12
PSIO_ERROR: 12 (error writing to file)
Traceback (most recent call last):
  File "/marisdata/senjean/Git_repo/SA-OO-VQE//intersection_coniques.py", line 47, in <module>
    en0_casci,en1_casci = get_energies_formaldimine(alpha,phi)
  File "/marisdata/senjean/Git_repo/SA-OO-VQE//intersection_coniques.py", line 35, in get_energies_formaldimine
    E0_casci = psi4.energy('fci')
  File "/home/senjean/psi4conda/lib/python3.7/site-packages/psi4/driver/driver.py", line 556, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/senjean/psi4conda/lib/python3.7/site-packages/psi4/driver/procrouting/proc.py", line 2998, in run_detci
    ciwfn = core.detci(ref_wfn)
RuntimeError:
Fatal Error: PSIO Error
Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1557940846948/work/psi4/src/psi4/libpsio/error.cc on line: 128
The most recent 5 function calls were:

psi::PSIO::rw(unsigned long, char*, psi::psio_address, unsigned long, int)
psi::PSIO::write_entry(unsigned long, char const*, char*, unsigned long)
```

and here is the script:

```
import os
import numpy as np
psi4.set_memory(int(2e9))

# Conical intersection in Formaldimine
pes_origin = [1.498047, 1.066797, 0.987109, 118.359375]
psi4.core.set_output_file("formaldimine.txt", False)
# sto-3g : 13 orbitals, cc-pVDZ: 43, cc-pVTZ: 102. Nelec: 16

def get_energies_formaldimine(alpha,phi):
    #name = "formaldimine_alpha" + str(alpha) + ".txt"
    #psi4.core.set_output_file(name, False)
    psi4.core.clean()
    variables = pes_origin[:] + [alpha, phi]
    psi4.geometry(
        """0 1
        N
        C 1 {0}
        H 2 {1}  1 {3}
        H 2 {1}  1 {3} 3 180
        H 1 {2}  2 {4} 3 {5}
        symmetry c1""".format(*variables))
    psi4.set_options({'basis': 'cc-pVDZ',
                  'reference': 'rhf',
                  'scf_type': 'pk', # set e_convergence and d_convergence to 1e-8 instead of 1e-6
                  'num_roots': 2,
                  #'frozen_docc':[2],
                  'active':[16]})
    E0_casci = psi4.energy('fci')
    E1_casci = psi4.variable('CI ROOT 1 TOTAL ENERGY')
    return E0_casci, E1_casci

output = open("formaldimine_CASCI-16e-16o.dat", "w")

phi = 90
start_angle = 90
end_angle = 160
number_of_steps = abs(end_angle - start_angle) + 1
print("{:10s} {:10s} {:10s}".format("alpha","E0","E1"), file = output)
for alpha in np.linspace(start_angle,end_angle,number_of_steps):
    en0_casci,en1_casci = get_energies_formaldimine(alpha,phi)
    print("{:10.6f} {:10.6f} {:10.6f}".format(alpha,en0_casci,en1_casci))
    print("{:10.6f} {:10.6f} {:10.6f}".format(alpha,en0_casci,en1_casci), file = output)
```

does anyone understand the error ? Again, replacing active = 16 by active = 14 works just fine, so I first assumed that it was a memory issue but the error does not mention anything about memory. Note that I ask for 16gb memory on the cluster for this calculation.

**Comment by JonathonMisiewicz** [comment]
PSIO errors are notoriously difficulty to understand, but my intuition is to say that this is a memory issue, if it's dependent on the size of the active space.

What do you mean by "I ask for 16gb memory on the cluster"? I'm not debugging your queuing system, but does that mean you're changing `psi4.set_memory(int(2e9))`? That looks closer to 1.6 than 16 GB.

**Comment by hokru** [comment]
Btw the memory function accepts various formats, e.g. also `set_memory('16 GiB')`

**Comment by bsenjean** [comment]
Thanks, I indeed forgot to change this variable, I just changed the one for the cluster and not for psi4... I've set it to 16GB now. But the problem persists. It is indeed certainly related to memory. For such a large CAS do you have any idea of the amount of memory required ?

**Comment by bsenjean** [comment]
FYI I tried 64 GB but still the same issue. I guess I will have to stick with a CAS(16,14) as my reference energy.

**Comment by hokru** [comment]
Could you perhaps share the output?

On CAS(16,16) also other programs already give up :), but would be good to understand where.

**Comment by JonathonMisiewicz** [comment]
For the record, I wouldn't be optimistic about improvements here. Psi's CI code is not known for its friendliness to new developers. But it's worth having records if somebody does want to take this up.

**Comment by bsenjean** [comment]
So here is the output file for 64 GB:

[formaldimine.txt](https://github.com/psi4/psi4/files/4948227/formaldimine.txt)

and the error:

```
PSIO_ERROR: unit = 51, errval = 12
PSIO_ERROR: 12 (error writing to file)
Traceback (most recent call last):
  File "/marisdata/senjean/Git_repo/SA-OO-VQE//intersection_coniques.py", line 47, in <module>
    en0_casci,en1_casci = get_energies_formaldimine(alpha,phi)
  File "/marisdata/senjean/Git_repo/SA-OO-VQE//intersection_coniques.py", line 35, in get_energies_formaldimine
    E0_casci = psi4.energy('fci')
  File "/home/senjean/psi4conda/lib/python3.7/site-packages/psi4/driver/driver.py", line 556, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/senjean/psi4conda/lib/python3.7/site-packages/psi4/driver/procrouting/proc.py", line 2998, in run_detci
    ciwfn = core.detci(ref_wfn)
RuntimeError:
Fatal Error: PSIO Error
Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1557940846948/work/psi4/src/psi4/libpsio/error.cc on line: 128
The most recent 5 function calls were:

psi::PSIO::rw(unsigned long, char*, psi::psio_address, unsigned long, int)
psi::PSIO::write_entry(unsigned long, char const*, char*, unsigned long)
```

and I confirm the 64 GB used : `  Memory set to  64.000 GiB by Python driver.`

**Comment by hokru** [comment]
Odd that it crashes after the first CI iteration. Memory wise it should be fine.
Did you check (and set) the scratch directory? (size, no network dir)

**Comment by hokru** [comment]
The default scratch directory is `/tmp/`, which is often limited in size (few Gib) and large calculation will crash because the "disk is full".

Set either the env variable `PSI_SCRATCH` or use the python command `psi4.core.IOManager.shared_object().set_default_path('/path/')`  and specify, in the best case, a local disk on the HPC node.
Slow network directories can stall I/O and also crash calculations.

Unclear how much you will need in terms of size, I am not familiar with the implementation details.

**Comment by bsenjean** [comment]
You were right, it is indeed because /tmp/ is apparently limited to 10GB on the cluster ! I didn't know. Working in another scratch directory (with 2TB) works perfectly now and in less than one day (on 32 CPUs) I can have one point of the CAS(16,16) PES. Thank you !

**Comment by JonathonMisiewicz** [comment]
@hokru, correct me if I'm wrong, but isn't it fairly formulaic at this point to ask people to check how much memory they gave Psi and then check their scratch directory in the face of a PSIO read error? If it is, I have half a mind to update the error message with this advice. I'd need to check, but I think this is doable, and it would save us a lot of questions.

**Comment by hokru** [comment]
Perhaps a good idea. PSIO should mainly be disk issues IMO. And only memory issues if the C code made bad estimates, right? Unless there are there virtual files that are written to RAM.
`PSIO_ERROR: 12 (error writing to file)` should in most cases be a disk space issue.

**Comment by TiborGY** [comment]
> 
> 
> Perhaps a good idea. PSIO should mainly be disk issues IMO. And only memory issues if the C code made bad estimates, right? Unless there are there virtual files that are written to RAM.
> `PSIO_ERROR: 12 (error writing to file)` should in most cases be a disk space issue.

Well, I have seen some systems where /tmp is a ramdisk. But usually, if that is the case, the maximum size of /tmp is quite limited.

**Comment by loriab** [comment]
Yes, disk space is about the only correctable PSIO error besides failing to clean scratch between independent calcs. There are legit fails that should be directed to devs but only after ruling out disk as culprit.
