### ISSUE TITLE
too obscure PSIO errors

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#1965]
The user facing error message for PSIO could be improved.

A general advice after an PSIO error of sth like: 'check your scratch directory location and how much space you got', could go a long way.

Starting of discussion in #1959 (comments copied over)

> @JonathonMisiewicz commented 41 minutes ago
@hokru, correct me if I'm wrong, but isn't it fairly formulaic at this point to ask people to check how much memory they gave Psi and then check their scratch directory in the face of a PSIO read error? If it is, I have half a mind to update the error message with this advice. I'd need to check, but I think this is doable, and it would save us a lot of questions.

> hokru commented 23 minutes ago
Perhaps a good idea. PSIO should mainly be disk issues IMO. And only memory issues if the C code made bad estimates, right? Unless there are there virtual files that are written to RAM.
PSIO_ERROR: 12 (error writing to file) should in most cases be a disk space issue.

> @TiborGY commented 6 minutes ago
Well, I have seen some systems where /tmp is a ramdisk. But usually, if that is the case, the maximum size of /tmp is quite limited.

ramdisks or not is the same, I think. Disk is full and the PSI4 memory option has no influence.
But a trend of having `/tmp` as ramdisk questions PSI4's choice of default scratch directory, because ramdisk space does not take away the OS max ram, right? There could be unexpected memory allocation errors for users.

**Comment by JonathonMisiewicz** [comment]
@hokru, can you close this after #2030 ?
