### ISSUE TITLE
Start FCI calculation from a FCIDUMP file?

### ISSUE THREAD

**Issue by uwhbliu** [psi4/psi4#1967]
Hi, I am wondering If there is a way to start a FCI calculation from a FCIDUMP file? I know psi4 can generate FCIDUMP files, but didn't find any example of using FCIDUMP as input files. Thank you!

**Comment by CDSherrill** [comment]
No, unfortunately there's not a way to do this.

**Comment by fevangelista** [comment]
@uwhbliu : you can run a FCI computation from a FCIDUMP file in [forte](https://github.com/evangelistalab/forte), a psi4 plugin. I would be happy to help with the setup/compilation. A test case that runs FCI with frozen core orbitals is available [here](https://github.com/evangelistalab/forte/tree/master/tests/methods/integrals-fcidump-1).

**Comment by uwhbliu** [comment]
Thank you both! I will try forte.
