### ISSUE TITLE
Installing Psi4 in Conda with Python3.8

### ISSUE THREAD

**Issue by jevandezande** [psi4/psi4#1979]
I attempted to install Psi4 using Conda that used python3.8 and received the following error:

```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

- psi4 -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Your python: python=3.8
```

Install command: `conda install -c psi4 psi4`
Conda version: `4.8.3`
Python version: `3.8.3`
Linux: `Debian Buster`

Is there anything holding back psi4 from being used with python3.8? Does there even need to be an upper limit on the python version one can use?

**Comment by loriab** [comment]
Have you tried installing into an environment (i.e., `conda create -n p4env python=3.8 psi4 -c psi4`)? Especially with heavy main environments like an Anaconda installation, there may be small pinning problems like mkl=2019.4 vs 2020.2 (b/c psi4 releases don't get rebuilt) that manifest as UnsatisfiableError.

For most anyone, a recent psi4 would do. (Testing is the same as for releases.) `conda install psi4 -c psi4/label/dev`.

The upper limit on python version is because psi4 must be built for each version. E.g., one could compile psi against a py3.9 alpha, but until one does (and checks that all the deps do, too), there's an upper limit to what can be installed. (That `2.7.*` is because the constraint solver can find _some_ psi4 for py27 in that channel; it won't be the one you want.)

**Comment by jevandezande** [comment]
I tried `conda create -n p4env python=3.8 psi4 -c psi4` to no avail:

```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
psi4 -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
psi4 -> networkx -> python[version='>=3.5|>=3.8,<3.9.0a0|>=3.6.0|>=3.6']
python=3.8
```

I'm out of my depths here, but it seems that networkx already works in python3.8, so I'm not sure why that would show up as a conflict.

A Python 3.8 build would be great, since it seems to be the default python in Conda now (and it will allow people to start arguing over walrus operators in their code).

Installing with `python=3.7` works.
Thanks.

**Comment by PeterKraus** [comment]
I wonder if this is obvious, but there's no Psi4 for python 3.8 in the main channel:
```
linux-64/psi4-1.3.2+ecbda83-py37h06ff01c_1.tar.bz2
linux-64/psi4-1.3.2+ecbda83-py36h34e5639_1.tar.bz2
```
That being said, unless you really want the current release version (1.3.2), I'd strongly suggest you go for Psi4 from the `dev` channel using `conda create -n p4env python=3.8 psi4 -c psi4/label/dev`.

**Comment by loriab** [comment]
Yes, read my comment above as if I was thinking there was a v1.3.2 py38 build. I was misremembering -- there isn't. 

* v1.3 was py36/37.
* Since then, psi4 is py36/37/38.
* v1.4 release may well be py37/38/39.

**Comment by ErikCVik** [comment]
I still get an error entering 'conda create -n p4env python=3.8 psi4 -c psi4/label/dev' into anaconda prompt.

does my computer being a windows have anything to do with this failed installation?

`(base) C:\Users\erikc>conda create -n p4env python=3.8 psi4 -c psi4/label/dev
WARNING: A directory already exists at the target location 'C:\Users\erikc\anaconda3\envs\p4env'
but it is not a conda environment.
Continue creating environment (y/[n])? y

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
psi4 -> msgpack-python -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0|>=3.6|>=3.5|>=3.6.0']
python=3.8
psi4 -> python=3.8`

I would appreciate any help to get psi4 up and running.

thanks

**Comment by hokru** [comment]
Is this Windows native or Windows WSL?

> WARNING: A directory already exists at the target location 'C:\Users\erikc\anaconda3\envs\p4env'
> but it is not a conda environment.

Does the error persists if you delete the old environment or directory first?
Or use a different name than `p4env`.

**Comment by ErikCVik** [comment]
(base) C:\Users\erikc>conda create -n p4envnew python=3.8 psi4 -c psi4/label/dev
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining @/win-64::__win==0=0:  80%|████████████████████████████████████████████████████████████████████████████▊                   | 4/5 [00:00<00:00, 14.60it/s]-failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
psi4 -> msgpack-python -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0|>=3.6|>=3.5|>=3.6.0']
psi4 -> python=3.8
python=3.8

I dont think it is the environment name

**Comment by JonathonMisiewicz** [comment]
See #2236
