### ISSUE TITLE
`Fa_subset("MO")` Incorrect

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#1989]
Run:
```
molecule h2o {
0 1
o
h 1 0.958
h 1 0.958 2 104.4776 
}

wfn = energy('scf/cc-pvdz', return_wfn=True)[1]
print(wfn.Fa_subset("MO").nph)
```

The result MO basis Fock matrix is not diagonal, as expected.

The correct way to transform the SO basis Fock matrix into the MO basis matrix is contraction against the C coefficient matrices. This is not what the `Fa_subset` function does. It instead goes through [a series of matrix mulitplications involving the overlap matrix](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libmints/wavefunction.cc#L1047-L1050). This is the correct transformation rule for the density matrix. Not-so-coincidentally, `Da_subset` goes through exactly the same function, where this behavior is correct. If you try to use the same logic for both helpers, you're going to get one of them wrong, guaranteed.

While the mechanism of the bug is clear to me, I'm not sure what the best fix should be. Perhaps we should intercept "MO" as a special case in `Fa_subset` so it never sees the `matrix_subset_helper`? Under the hood, the code would return `Fa_->transform(Ca_)`.

**Comment by susilehtola** [comment]
He in STO-3G-decon is maybe an even simpler example.

**Comment by CDSherrill** [comment]
Interesting.  I have examined these functions in the past, but it's been a while.  Can you remind me what is the original basis, AO or SO?

It's not super obvious to me why behavior for D would be correct while behavior for F would be wrong, if they both start in the same original basis.

**Comment by JonathonMisiewicz** [comment]
The original basis is SO.

The behavior for D and F are different because "AO basis quantities" mean different things for those two cases. For the F matrix, "AO basis" means that you have a formula in terms of one-electron functions, and you just throw those in. To change basis, you just linearity. F_pq = C_mu,p C_nu,q F_mu,nu

For D, "AO basis" means "if you contract this against an AO basis integral, you'll get the same result as if you had contracted an MO basis quantity against MO basis integral." In that case, D_mu,nu F_mu,nu = D_p,q F_p,q = D_p,q C_mu,p C_nu,q F_mu,nu, so we end with D_mu,nu = C_mu,p C_nu,q D_p,q.

Note that it _differs_ whether you need to contract your C matrices against the AO or the MO basis quantity.

**Comment by gpwood** [comment]
Hi All,

**Comment by JonathonMisiewicz** [comment]
How soon do you need this? This bug is an easy fix, and I can include it in the Psi4 1.8 release coming out in a couple weeks. If you need this sooner, the "workaround" is simple.

**Comment by gpwood** [comment]
@JonathonMisiewicz that's great news!  I'm in no rush, so I can wait.  The purpose of my calculations is to look at Fock, Coulomb and Exchange matrices in different orbital representations (i.e. from some localisation procedure). For your tests have you looked at the J and K matrices as well as orbital rotations?  Thanks, Geoff.

**Comment by JonathonMisiewicz** [comment]
Your questions may make sense in the context of your research, but they don't make sense in the context of the actual Psi4 code.

* As far as I'm aware, Psi has no built-in function to return J or K in an MO basis, only in the SO basis.
* Psi stores the Fock matrix in the SO basis and transforms it to an MO basis. The problem right now is that it's using the wrong transformation rule. If we can get right in the canonical basis, then it'll be right in any orthogonalized basis.

**Comment by gpwood** [comment]
Completely understand. Just wanted to make sure that if you make a call for K, J, H(core) and density matrices it wouldn't have the same transformation issues as for the Fock. Obviously as long as you can get the rotation matrix/MO coefficients I can make the transformations on J and K myself. Thanks.

**Comment by JonathonMisiewicz** [comment]
Oh, no, those would be just fine. The issue is that Psi _isn't_ using the formula `mf.mo_coeff.T @ Fao @ mf.mo_coeff` to transform Fock, but a more complicated formula which describes how the density matrix transforms. If you can get the SO Fock matrix and do the transformation yourself, it'd work.
