### ISSUE TITLE
No occupied orbitals with beta spin (monoatomic hydrogen)

### ISSUE THREAD

**Issue by pastaalfredo** [psi4/psi4#1995]
Hi,

I've been trying to calculate the energies of monoatomic compounds. All of the atoms ran successfully, except for hydrogen with multiplicity 2.

My in-file:
```
molecule mol_atomic_hydrogen_doublet {
        0 2
        H  0.000000000  0.000000000  0.000000000

        units angstrom
        no_reorient
}

set globals {
        basis aug-cc-pVQZ
        dft_spherical_points 434
        dft_radial_points 85
        reference uhf
}

set_memory(100000000000)
try:
    optimize('pwpb95-d3bj')
except SCFConvergenceError as e:
    unconverged_scf_wfn = e.wfn
    unconverged_scf_wfn.to_file(unconverged_scf_wfn.get_scratch_filename(180))
    set guess read
    optimize('pwpb95-d3bj')
```

The error I got (including previous lines):
```
*** tstart() called on host
*** at Fri Aug 21 16:21:36 2020

   => Loading Basis Set <=

    Name: (AUG-CC-PVQZ AUX)
    Role: RIFIT
    Keyword: DF_BASIS_MP2
    atoms 1 entry H          line    30 file /home/username/miniconda/share/psi4/basis/aug-cc-pvqz-ri.gbs

         --------------------------------------------------------
                                  DF-MP2
              2nd-Order Density-Fitted Moller-Plesset Theory
                      UMP2 Wavefunction,  28 Threads

                Rob Parrish, Justin Turney, Andy Simmonett,
                   Ed Hohenstein, and C. David Sherrill
         --------------------------------------------------------

         --------------------------------------------------------
                         NBF =    46, NAUX =    80
         --------------------------------------------------------
           CLASS    FOCC     OCC    AOCC    AVIR     VIR    FVIR
           ALPHA       0       1       1      45      45       0
            BETA       0       0       0      46      46       0
         --------------------------------------------------------


Traceback (most recent call last):
  File "/home/username/miniconda/bin/psi4", line 287, in <module>
    exec(content)
  File "<string>", line 31, in <module>
  File "/home/username/miniconda/lib//python3.6/site-packages/psi4/driver/driver.py", line 1052, in optimize
    G, wfn = gradient(lowername, return_wfn=True, molecule=moleculeclone, **kwargs)
  File "/home/username/miniconda/lib//python3.6/site-packages/psi4/driver/driver.py", line 710, in gradient
    **kwargs)
  File "/home/username/miniconda/lib//python3.6/site-packages/psi4/driver/driver.py", line 183, in _process_displacement
    derivative, wfn = derivfunc(method, return_wfn=True, molecule=clone, **kwargs)
  File "/home/username/miniconda/lib//python3.6/site-packages/psi4/driver/driver.py", line 556, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/username/miniconda/lib//python3.6/site-packages/psi4/driver/procrouting/proc.py", line 2018, in run_scf
    dfmp2_wfn.compute_energy()

RuntimeError:
Fatal Error: There are no occupied orbitals with beta spin.
Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1563933640427/work/psi4/src/psi4/dfmp2/mp2.cc on line: 196
The most recent 5 function calls were:




Printing out the relevant lines from the Psithon --> Python processed input file:
    core.set_global_option("DFT_SPHERICAL_POINTS", 434)
    core.set_global_option("DFT_RADIAL_POINTS", 85)
    core.set_global_option("REFERENCE", "uhf")
    set_memory(100000000000)
    try:
-->     optimize('pwpb95-d3bj')
    except SCFConvergenceError as e:
        unconverged_scf_wfn = e.wfn
        unconverged_scf_wfn.to_file(unconverged_scf_wfn.get_scratch_filename(180))
        core.set_global_option("GUESS", "read")
        optimize('pwpb95-d3bj')

    Psi4 stopped on: Friday, 21 August 2020 04:21PM
    Psi4 wall time for execution: 0:00:04.47

*** Psi4 encountered an error. Buy a developer more coffee!
*** Resources and help at github.com/psi4/psi4.
```

As I am fairly new to quantum chemistry, I do not really know how to interpret this error.

Any pointers are appreciated.

**Comment by hokru** [comment]
Hi, 
For electron correlation methods like MP2 used in your double-hybrid functional you need at least 2 electrons. 

Older psi4 versions didn't catch this case gracefully. I assume you use v1.3.2?
This has been patched earlier this year in the development version (https://github.com/psi4/psi4/pull/1857 by @PeterKraus ).

**Comment by susilehtola** [comment]
Well, it still fails for triplet helium, which is a case that is perfectly physical!

**Comment by pastaalfredo** [comment]
Thank you for your responses.

Yeah, I do use main v1.3.2. So the dev version should work? Or do I have to change the method to handle the single electron?

**Comment by hokru** [comment]
Yes, the dev version would work for your case. However, there is a small change in the DFT code (see note at the top http://psicode.org/psi4manual/master/dft.html) that is important if you are mid-project since you should not absolute energies between the versions.

All mean-field methods (HF/DFT) will work with the current version but you would need to avoid double-hybrids DFT functionals since they contain an MP2 part.

**Comment by susilehtola** [comment]
But the helium triplet fails even in the dev version!

**Comment by hokru** [comment]
Yes, that still needs fixing. But at least the H doublet will work.

**Comment by PeterKraus** [comment]
Yeah, I didn't think of higher multiplicity cases. There, the fix will be a little more involved I guess. `DF-MP2` (which is used also for DH-DFT) and `CD-MP2` crash, while conventional MP2 via `OCC` runs fine, but the correlation energy is 0 (Is that correct? Shouldn't there be some same-spin contribution?).

**Comment by susilehtola** [comment]
@PeterKraus yes, something like 0.78 mEh of alpha-alpha correlation energy for He triplet in cc-pVTZ.

**Comment by PeterKraus** [comment]
Tagging @JonathonMisiewicz : 
[3he.txt](https://github.com/psi4/psi4/files/5140334/3he.txt)
```
	IRREP   FC   AOCC  BOCC  AVIR    BVIR  FV 
	==========================================
	  Ag     0     2     0     0      2     0
	 B1g     0     0     0     0      0     0
	 B2g     0     0     0     0      0     0
	 B3g     0     0     0     0      0     0
	  Au     0     0     0     0      0     0
	 B1u     0     0     0     1      1     0
	 B2u     0     0     0     1      1     0
	 B3u     0     0     0     1      1     0
	==========================================

	Computing MP2 energy using SCF MOs (Canonical MP2)... 
	============================================================================== 
	Nuclear Repulsion Energy (a.u.)    :     0.00000000000000
	SCF Energy (a.u.)                  :    -1.40116327670131
	REF Energy (a.u.)                  :    -1.40116327670131
	Alpha-Alpha Contribution (a.u.)    :     0.00000000000000
	Alpha-Beta Contribution (a.u.)     :     0.00000000000000
	Beta-Beta Contribution (a.u.)      :     0.00000000000000
	Scaled_SS Correlation Energy (a.u.):     0.00000000000000
	Scaled_OS Correlation Energy (a.u.):     0.00000000000000
	SCS-MP2 Total Energy (a.u.)        :    -1.40116327670131
	SOS-MP2 Total Energy (a.u.)        :    -1.40116327670131
	SCSN-MP2 Total Energy (a.u.)       :    -1.40116327670131
	SCS-MP2-VDW Total Energy (a.u.)    :    -1.40116327670131
	SOS-PI-MP2 Total Energy (a.u.)     :    -1.40116327670131
	MP2 Correlation Energy (a.u.)      :     0.00000000000000
	MP2 Total Energy (a.u.)            :    -1.40116327670131
	============================================================================== 
```

**Comment by hokru** [comment]
Seems we should get a He triplet test cases and run various correlation modules. DCT MP2 guess also gives alpha-alpha=0.0
For RI-MP2 with ORCA I get -0.004692354 Eh

**Comment by susilehtola** [comment]
@PeterKraus cc-pVDZ is too small:
| Basis | Correlation energy|
|---------|-------------------------|
|cc-pvdz| 0.0000000000E+00|
|cc-pvtz |-0.7824302424E-03|
|cc-pvqz| -0.1181868464E-02|
|cc-pv5z| -0.1285572449E-02|

**Comment by CDSherrill** [comment]
Dear Alfred,

Yeah, the problem is, as the code says, "Fatal Error: There are no occupied
orbitals with beta spin." In our program, you can't run an MP2 calculation
on an atom or molecule that doesn't have any beta spin electrons. More
generally, an MP2 calculation doesn't make any sense for systems with only
one electron. Your method is a "double hybrid" that includes MP2 as a part
of it.

Also, it's impossible to "optimize" (like you are trying to do) the
geometry of an atom. It has no internal degrees of freedom to optimize.

These computational chemistry programs require a little bit of training to
be able to use properly... they're not totally bulletproof black boxes.

Best,
David

**Comment by pastaalfredo** [comment]
Thank you for suggesting the dev version. It worked without any further errors or warnings. Cheers!

That is a good point, David. In this case we just wanted to optimize the energy, not the structure, and we already had scripts to do so for larger molecules. Thank you for the heads-up!
