### ISSUE TITLE
Fix issues with spaces in option names and unknown option names (PSIAPI)

### ISSUE THREAD

**Issue by fevangelista** [psi4/psi4#2004]
The following snippet of code fails because of the extra space at the end of `'SCF_TYPE '`

```python
import psi4
psi4.set_options({'SCF_TYPE ' : 'DIRECT'})
```

This is an innocent error that should be fixed by psi4, or reported back to the user with a readable error message. Simply stripping the option label of left and right spaces would prevent this issue (with no potential side effects). If the option is not found, then psi4 should throw an exception saying something like "Option `'...'` is not valid."

This is the error message:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-c64c7a4449ad> in <module>
      1 import psi4
      2 
----> 3 psi4.set_options({'SCF_TYPE ' : 'DIRECT'})

/usr/local/psi4/lib/psi4/driver/p4util/python_helpers.py in set_options(options_dict, verbose)
    444     for k, v, in options_dict.items():
    445         mobj = optionre.match(k)
--> 446         module = mobj.group('module').upper()[:-2] if mobj.group('module') else None
    447         option = mobj.group('option').upper()
    448 

AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by loriab** [comment]
I sense someone in your class hit upon this :-)

If no one else grabs it, I'll claim it to train the GT first-years in the ways of git, PRs, pytest, etc.
