### ISSUE TITLE
Sign coefficients of determinants (SA-CASSCF)

### ISSUE THREAD

**Issue by saadyalouz** [psi4/psi4#2008]
Dear developers,

I am currently running SA-CASSCF calculations on the formaldimine molecule. I am particularly interested by the determinant decomposition of the ground and first excited state of the molecule (singlet symmetry). However, I think I have noticed a pb concerning the sign of the determinants in the output.

First, I give you my INPUT in python : 

    pes_origin = [1.498047, 1.066797, 0.987109, 118.359375]
    variables = pes_origin[:] + [90, 90]
    psi4.geometry(
        """
        N
        C 1 {0}
        H 2 {1}  1 {3}
        H 2 {1}  1 {3} 3 180
        H 1 {2}  2 {4} 3 {5}
        symmetry c1""".format(*variables) )
    
    psi4.set_options({ 'basis': 'cc-pvdz',
                        'DETCI_FREEZE_CORE' : False,
                        'reference': 'RHF',
                        'num_roots': 2,
                        'frozen_docc':[0],
                        'restricted_docc': [6],
                        'active': [3],
                        'restricted_uocc': [11], 
                        'frozen_uocc': [23],
                        'mcscf_maxiter': 1000,                       
                        'avg_states'      : [ 0, 1],
                        'avg_weights'     : [ 0.5, 0.5 ]
                        })
    
    sacasscf, sacasscf_wfn = psi4.energy('casscf',return_wfn=True)
    E0_sacasscf = psi4.variable('CI ROOT 0 TOTAL ENERGY')
    E1_sacasscf = psi4.variable('CI ROOT 1 TOTAL ENERGY') 

Then, I give you from the OUTPUT FILE the decomposition I obtain : 

*******************************************************************
*******************************************************************
    ==> MCSCF root 0 information <==

    MCSCF Root 0 energy =   -93.931448649953467

   Active Space Natural occupation numbers:

         A   2.000000         A   1.000000         A   1.000000

   The 9 most important determinants:

    *   1    0.691216  (    0,    1)  7AX 8AA 9AB 
    *   2    0.691216  (    1,    0)  7AX 8AB 9AA 
    *   3   -0.149064  (    1,    2)  7AA 8AB 9AX 
    *   4   -0.149064  (    2,    1)  7AB 8AA 9AX 
    *   5    0.000000  (    0,    0)  7AX 8AX 
    *   6    0.000000  (    0,    2)  7AA 8AX 9AB 
    *   7    0.000000  (    2,    0)  7AB 8AX 9AA 
    *   8   -0.000000  (    2,    2)  8AX 9AX 
    *   9   -0.000000  (    1,    1)  7AX 9AX 

   ==> MCSCF root 1 information <==

    MCSCF Root 1 energy =   -93.902550337672878

   Active Space Natural occupation numbers:

         A   1.999537         A   1.843676         A   0.156787

   The 9 most important determinants:

    *   1   -0.887365  (    0,    0)  7AX 8AX 
    *   2   -0.291143  (    0,    2)  7AA 8AX 9AB 
    *   3   -0.291143  (    2,    0)  7AB 8AX 9AA 
    *   4    0.206936  (    2,    2)  8AX 9AX 
    *   5    0.015212  (    1,    1)  7AX 9AX 
    *   6    0.000000  (    1,    0)  7AX 8AB 9AA 
    *   7    0.000000  (    0,    1)  7AX 8AA 9AB 
    *   8   -0.000000  (    1,    2)  7AA 8AB 9AX 
    *   9   -0.000000  (    2,    1)  7AB 8AA 9AX 
*******************************************************************
*******************************************************************

As you can see, there is typically the same kind of sign for some determinants sharing a similar coefficient. For example, for the groundstate  we have  : 0.691216  (    0,    1)  7AX 8AA 9AB  and  0.691216  (    1,    0)  7AX 8AB 9AA.  However, in the context of a singlet spin symmetry, these determinants should present opposite signs. To check this, I used a personal code to build up from scratch the frozen core Hamiltonian associated to the (4,3) active space. I used for this the resulting Optimized MO coeff matrix obtained from SA-CASSCF Psi4. Diagonalizing this Hamiltonian gives the following two lowest states expressed in the active space : 
| Psi_0 > = 0.149|011011⟩ - 0.149|100111⟩ - 0.691|110110⟩ + 0.691|111001⟩
| Psi_1 > = 0.207|001111⟩ - 0.291|011110⟩ + 0.291|101101⟩ + 0.015|110011⟩ - 0.887|111100⟩
(NB : the HF determinant is |111100⟩ )

With this diagonalization, we clearly find same coefficients but with opposite signs. As a double check, I also computed the energy of these states and obtained : 
E_0 = -93.93144865003578 Ha
E_1  = -93.90255033754423 Ha

Which exactly coincides with the energy obtained in the Psi4 OUTPUT. Do you have a clue why such a pb arises in the Psi4 output ?

Thanks a lot for you answer

**Comment by JonathonMisiewicz** [comment]
The two codes agree with each other, once you correct for the fact that they store determinants differently, creating a phase disagreement.

Let's restrict ourselves to spatial orbitals 8 and 9 for simplicity.
You order orbitals as 8A 8B 9A 9B. Loop by spatial orbital, then by spin.
Psi orders orbitals as 8A 9A 8B 9B. Loop by spin, then by spatial orbital. Internally, Psi's FCI stores a string of alpha orbitals and then a string of beta orbitals. This is only possible because of this orbital ordering.

So you say that 8A 9B and 8B 9A have opposite phases. Psi says that 8A 9B and 9A 8B have the same phases. Both are correct.

**Comment by CDSherrill** [comment]
I'm not sure what you mean by "pb", but I understand the question.

I'm the author of this part of the code, and I checked the signs very
thoroughly when the code was written.

Most likely, this is a confusion about the sign conventions of the code.
You'll recall that the sign of a determinant depends on the ordering of the
spin orbitals.  In this code, all alpha spin orbitals come first, and then
all beta spin orbitals (this winds up being an easier rule to state and
maintain than alternatives like "order by spatial orbital, and then alpha
first and beta second within spatial orbital numbering").

With that ordering, the signs given are correct.  (See, for example,
equation 2.260 of Szabo and Ostlund).

Best,
David

**Comment by saadyalouz** [comment]
Hello everyone,

Thanks for your quick answer and your very thorough explanations ! 👍 

Indeed, I totally missed the part about the different type of spinorbital storing. In this case as you say, both codes are right. I was confused because for me, as an OpenFermion user (quantum computing package), the second approach was more natural (i.e. storing according to spatial MOs with alternating alpha then beta spinorbital). I was using the OUTPUT from psi4 as a direct reference for my calculations. More precisely, I wanted to compute overlap between an eigenstate from Psi4 and another one generated by OpenFermion. As you could imagine, the results were very strange... This is why all of this appeared as a "pb" for me :) But now, everything is solved ! Thanks for your help !

Before leaving, I would like also to sincerely thank all of you for the very nice work done with Psi4 and Psi4-numpy. As a physicist working in quantum computing, these codes are fundamental tools for my everyday work. Moreover, it helped me learning a lot about practical implementation of quantum chemistry methods. Thanks a lot guys for your investment in this project !!

Best, 
Saad
