### ISSUE TITLE
Frequency convergence issues (density matrix)

### ISSUE THREAD

**Issue by pastaalfredo** [psi4/psi4#2016]
Hi,

I have been comparing the basis sets _aug-cc-pVTZ_ and _aug-cc-pVQZ_. While I was running frequency calculations on a large set of molecules, I found out that some of my molecules never converged. This is not surprising, as there will always be complex geometries that will have a harder time converging within the default number of iterations (100).

One of the molecules which never converged and stood out to me was ammonia (for aug-cc-pVQZ). The optimization of the structure was quick and easy, but the frequency calculation never converged due to the density matrix criterium (got down to ~10e-7, but never 10e-8). The atom coordinates I initially used was retrieved from a force field calculation. As these coordinates didn't work (even after increasing the number of iterations), I then changed the coordinates of ammonia to [this reference](https://www.researchgate.net/figure/Cartesian-coordinates-and-atomic-masses-of-ammonia_tbl2_259630381), but it still didn't do the trick as it got stuck at other atomic displacements instead.

After playing around with these coordinates for a while, I finally got my run to converge. Questions is, is there a better (automated) way to achieve this kind of convergence, instead of doing this manually for the other remaining molecules? Changing the number of iterations feels a bit naive (and inefficient) and randomly displacing the atoms pre-Psi4 could mean a huge increase in CPU hours (especially for molecules > 100 Da). How would lowering the density matrix criterium (e.g. 10e-7) affect the results?

All tips appreciated! 

Example of the ammonia Psi4 infile that finally worked:
```
molecule mol_ammonia {
        0 1
        H  0.000000000  0.000000000  1.208000000
        N  0.000000000  0.000000000  0.000000000
        H  1.150353000  0.000000000  -0.536000000
        H  -0.67517600  -1.0230290000  -0.536000000

        units angstrom
        no_reorient
}

set globals {
	basis aug-cc-pVQZ
	dft_spherical_points 434
	dft_radial_points 85
}

set_memory(80000000000)
try:
    optimize('pwpb95-d3bj')
except SCFConvergenceError as e:
    unconverged_scf_wfn = e.wfn
    unconverged_scf_wfn.to_file(unconverged_scf_wfn.get_scratch_filename(180))
    set guess read
    optimize('pwpb95-d3bj')
E, wfn = frequency('pwpb95-d3bj', return_wfn=True)
print(wfn.frequencies().get(0, 0))
```

**Comment by hokru** [comment]
Is `pwpb95-d3` the method you used? It's a double-hybrid and psi4 has no gradients for it. You should get numerical gradients and double-numerical frequencies.

**Comment by pastaalfredo** [comment]
Yeah, the method I used was `pwpb95-d3`.

How come it works for some structures, but for some not? Under what conditions can `pwpb95-d3` (not) calculate the numerical gradients?

To fix this, do I need to switch to an entirely different method altogether?

**Comment by hokru** [comment]
I remember having trouble with B95-based functional before where I also barely could convergence the density matrix to tight values in the SCF. Setting `DFT_BS_RADIUS_ALPHA > 1.0` (e.g. 1.1 or 1.2) might help to cover those heavy diffuse functions better.
Personally I think the density matrix criterium is too tight anyway.

If CPU time is any issue, I'd stay away from numerical gradients. To get analytical DFT gradients you need to select a functional that has no `VV10` and is no double-hybrid.
However, DFT frequencies will always numerical, except for pure LDA.

`wB97X-D3(BJ)` from the Georigk group could be a good alternative (A. Najib, L. Goerigk, J. Comput. Theory Chem., 14 5725, 2018). (will need a newer psi4 than 1.3.2)
Fast composite methods (defining functional+basis set+corrections) could also be an alternative, e.g. Grimme's `PBEh-3c`, especially for large data sets.

**Comment by pastaalfredo** [comment]
When I joined my project, the standard was to use `pwpb95-d3`, so I'll try to stick with it for as many calculations as possible (to make it easier to compare the different basis sets). This also makes it harder to go from numerical to analytical gradients, which in turn makes the only loss/gain in CPU time to be whether a job failed or not.

Also, would using the (smaller) default grid, i.e. `dft_spherical_points 302` (instead of 434) and `dft_radial_points 75` (instead of 85) improve the convergence?

I'll look into the changes you suggested. Thank you for the quick replies!

**Comment by susilehtola** [comment]
> Also, would using the (smaller) default grid, i.e. `dft_spherical_points 302` (instead of 434) and `dft_radial_points 75` (instead of 85) improve the convergence?

No, this will only worsen the convergence by introducing more numerical error.

**Comment by pastaalfredo** [comment]
All right. I will keep it as it is then. Thanks!

**Comment by pastaalfredo** [comment]
@hokru I now managed to run a (previously failed) job by increasing `DFT_BS_RADIUS_ALPHA`. Thanks! Hopefully this will work for other failed jobs as well. 

Also, I'm still not sure why this would improve the convergence in this case (i.e. what is there to gain/lose by changing the BS radius)?
