### ISSUE TITLE
Write PSIO Error Information to Output File

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#2019]
PSIO errors are currently being written to `stderr`. (See [this line and the switch statement below](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libpsio/error.cc#L54).) Although the fact that there is a PSIO error is written to the output file, I'm semi-frequently encountering forum users who aren't familiar with `stderr`. It either takes longer than it should for me to get this information, or they can't provide it.

For ease of debugging, this error information should be logged somewhere like the output file, where we can guarantee new users will keep it and be able to find it, so they can pass it on to developers.

**Comment by CDSherrill** [comment]
This sounds reasonable to me.

**Comment by JonathonMisiewicz** [comment]
Closed by #2030
