### ISSUE TITLE
Psi4 thinks Iodine is Maganese

### ISSUE THREAD

**Issue by bdw2292** [psi4/psi4#2021]
[_5-iodouracil-dma.psi4.txt](https://github.com/psi4/psi4/files/5410680/_5-iodouracil-dma.psi4.txt)

If you look at the fchk file produced, the atom number for Iodine will say 25, not 53 for Iodine!

**Comment by susilehtola** [comment]
That's probably due to the ECP.

**Comment by hokru** [comment]
Thanks for the report.
The ECPs are not correctly accounted for.
