### ISSUE TITLE
psi4 installation via conda interacts poorly with ambertools>=20 on MacOS

### ISSUE THREAD

**Issue by dotsdl** [psi4/psi4#2024]
Installing `ambertools >=20` alongside `psi4` on MacOS with:

```
conda create --name psi4-at-test -c conda-forge -c psi4/label/dev "ambertools >=20" psi4
```

results in unresolvable dependencies. Using `mamba` instead of `conda` for dependency resolution gives potentially useful output:
```
Encountered problems while solving.
Problem: nothing provides gcc-5-mp needed by psi4-1.2a1.dev458+efadaad-py35_gnu_0
```
This problem was first reported by @SimonBoothroyd, hampering MacOS tests for [openff-recharge](https://github.com/openforcefield/openff-recharge).

**Comment by loriab** [comment]
You're going to need to constrain psi4 to get meaningful dep resolution info. something like `psi4=1.4a2.dev1058 -c psi4/label/dev` right now. From the above, you're pulling an ancient version of psi4, pre v1.2, from before conda upgraded its compilers late 2017, hence the `gcc-5-mp`, which was a local (psi4) copy of a c++11 capable gcc so that psi4 could build.

**Comment by hokru** [comment]
`py35_gnu_0` python3.5 is no longer supported, only 3.6 will give the latest psi4 version.

In any case this will be tough with ambertools and psi4 wanting different blas backends (openblas vs mkl) for numpy.

**Comment by loriab** [comment]
Good point. psi4 is presently py36/37/38 and will soon be py37/38/39. and `blas=*=mkl` is non-negotiable. I should have mentioned that old psi4 wasn't pinned very tightly, so when a resolver chooses, say, v1.2, it's because everything newer with good constraints has a conflict.

**Comment by mattwthompson** [comment]
With the above recommendations, I get this, which is not much more useful without more troubleshooting (slowly going through each dep one by one):

<details>
  <summary>Click to expand</summary>
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package blas conflicts for:
blas[build=mkl]
ambertools[version='>=20'] -> numpy -> blas[version='*|*|1.1|1.0|1.0',build='mkl|mkl|openblas|openblas']
psi4=1.4a2.dev1058 -> blas==1.0=mkl
psi4=1.4a2.dev1058 -> numpy[version='>=1.12.0'] -> blas[version='*|*|1.1|1.0',build='mkl|openblas']

Package libgfortran4 conflicts for:
blas[build=mkl] -> libgfortran4[version='>=7.5.0']
ambertools[version='>=20'] -> libgfortran4[version='>=7.5.0']
ambertools[version='>=20'] -> libgfortran=4 -> libgfortran4
blas[build=mkl] -> libgfortran=4 -> libgfortran4

Package python conflicts for:
ambertools[version='>=20'] -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
ambertools[version='>=20'] -> cython -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|3.4.*|3.7.*|3.8.*|3.9.*']
python[version='>=3.6,<3.8']
psi4=1.4a2.dev1058 -> mkl-service[version='>=2,<3.0a0'] -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.9,<3.10.0a0|>=3.6|>=3.5|>=3.5,<3.6.0a0|3.4.*|>=3.6.0']
psi4=1.4a2.dev1058 -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']

Package numpy-base conflicts for:
ambertools[version='>=20'] -> numpy -> numpy-base[version='1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.14.3|1.14.3|1.14.3|1.14.3|1.14.3|1.14.3|1.14.4|1.14.4|1.14.4|1.14.4|1.14.4|1.14.4|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.3|1.15.3|1.15.3|1.15.3|1.15.3|1.15.3|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.2|1.16.2|1.16.2|1.16.2|1.16.2|1.16.2|1.16.3|1.16.3|1.16.3|1.16.3|1.16.3|1.16.3|1.16.4|1.16.4|1.16.4|1.16.4|1.16.4|1.16.4|1.16.5|1.16.5|1.16.5|1.16.5|1.16.5|1.16.5|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.17.2.*|1.17.3.*|1.17.4.*|1.18.1.*|1.18.5.*|1.19.1|1.19.1|1.19.1|1.19.1|1.19.1|1.19.1|1.19.2|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|1.9.3|>=1.9.3,<2.0a0|1.17.0|1.17.0',build='py36ha711998_0|py27h9797aa9_6|py27ha9ae307_6|py36h9797aa9_6|py37h9797aa9_7|py35ha9ae307_7|py36h9797aa9_7|py27h9797aa9_7|py27h9797aa9_7|py37h9797aa9_7|py36h9797aa9_7|py37ha9ae307_7|py27h9797aa9_8|py37h9797aa9_8|py35ha9ae307_8|py27he97cb71_9|py27h42e5f7b_10|py35h42e5f7b_10|py27ha711998_10|py36ha711998_10|py36ha711998_11|py37h6575580_11|py36h6575580_11|py36ha711998_12|py27ha711998_12|py37h6575580_12|py38h6575580_12|py38h6575580_13|py38ha711998_14|py38ha711998_15|py38h6575580_15|py36h479e554_1|py27h479e554_1|py35h9797aa9_0|py27ha9ae307_0|py36ha9ae307_0|py36ha9ae307_0|py36h9797aa9_0|py27ha9ae307_0|py36h9797aa9_1|py36h9797aa9_2|py36ha9ae307_2|py37ha9ae307_2|py27ha9ae307_2|py36ha9ae307_3|py36h9797aa9_3|py37h9797aa9_3|py27ha9ae307_3|py27ha9ae307_4|py36ha9ae307_4|py37h9797aa9_4|py35h9797aa9_4|py35ha711998_4|py37ha711998_4|py27ha711998_4|py37h8a80b8c_4|py38ha711998_4|py38h6575580_4|py27ha711998_5|py36h6575580_5|py27h6575580_5|py37h8a80b8c_0|py35h8a80b8c_0|py37h42e5f7b_0|py36h8a80b8c_0|py35h42e5f7b_0|py36h42e5f7b_0|py27h42e5f7b_0|py35h8a80b8c_0|py36ha711998_0|py35ha711998_0|py27ha711998_0|py27h8a80b8c_0|py37ha711998_1|py36ha711998_1|py27h8a80b8c_1|py36h8a80b8c_1|py37ha711998_0|py36ha711998_0|py27h8a80b8c_0|py37h8a80b8c_0|py36h8a80b8c_0|py37h6575580_0|py37h6575580_0|py27h6575580_0|py27ha711998_1|py37h6575580_1|py36ha711998_1|py37ha711998_1|py27h6575580_1|py37ha711998_0|py27h6575580_0|py37h6575580_0|py36ha711998_1|py37h6575580_1|py37ha711998_1|py36h6575580_1|py37ha711998_0|py27h6575580_0|py37h6575580_0|py36ha711998_0|py37h6575580_0|py37h6575580_0|py27h6575580_0|py37h6575580_0|py36ha711998_0|py37h6575580_0|py38ha711998_0|py27h6575580_0|py36h68fea81_0|py38hcfb5961_0|py38hcfb5961_0|py36h68fea81_0|py37h68fea81_0|py38h68fea81_0|py37hcfb5961_0|py36hcfb5961_0|py36hcfb5961_0|py37h68fea81_0|py37hcfb5961_0|py38h68fea81_0|py27ha711998_0|py38h6575580_0|py36h6575580_0|py37ha711998_0|py36h6575580_0|py27ha711998_0|py36ha711998_0|py37ha711998_0|py36h6575580_0|py27h6575580_0|py27ha711998_0|py37ha711998_0|py36ha711998_0|py36h6575580_0|py27h6575580_0|py37ha711998_0|py27ha711998_0|py36h6575580_0|py27ha711998_0|py36ha711998_0|py27ha711998_1|py27h6575580_1|py36h6575580_0|py27ha711998_0|py36ha711998_0|py36h6575580_1|py36h6575580_0|py36ha711998_0|py37ha711998_0|py27ha711998_0|py36h6575580_0|py27h6575580_0|py37ha711998_0|py36ha711998_0|py27ha711998_0|py27h8a80b8c_0|py36h8a80b8c_0|py27ha711998_0|py37h8a80b8c_0|py37h8a80b8c_1|py27ha711998_1|py35ha711998_0|py36ha711998_0|py36h8a80b8c_0|py37ha711998_0|py35h8a80b8c_0|py37h8a80b8c_0|py37ha711998_0|py27ha711998_0|py37h8a80b8c_0|py27h8a80b8c_0|py35he97cb71_0|py36he97cb71_0|py37he97cb71_0|py36h8a80b8c_0|py27h8a80b8c_0|py27he97cb71_0|py37h6575580_5|py37ha711998_5|py36ha711998_5|py27h8a80b8c_4|py36h8a80b8c_4|py35h8a80b8c_4|py36ha711998_4|py35ha9ae307_4|py37ha9ae307_4|py36h9797aa9_4|py27h9797aa9_4|py37ha9ae307_3|py27h9797aa9_3|py27h9797aa9_2|py37h9797aa9_2|py36ha9ae307_1|py27ha9ae307_1|py37ha9ae307_1|py37h9797aa9_1|py27h9797aa9_1|py35h9797aa9_0|py35ha9ae307_0|py27h9797aa9_0|py35ha9ae307_0|py36h9797aa9_0|py27h9797aa9_0|py35h7ef55bc_1|py27h7ef55bc_1|py35h479e554_1|py36h7ef55bc_1|py38h6575580_14|py38ha711998_13|py38ha711998_12|py37ha711998_12|py27h6575580_12|py36h6575580_12|py27h6575580_11|py27ha711998_11|py37ha711998_11|py37ha711998_10|py35ha711998_10|py36h42e5f7b_10|py37h8a80b8c_10|py35h8a80b8c_10|py27h8a80b8c_10|py36h8a80b8c_10|py37h42e5f7b_10|py35he97cb71_9|py36he97cb71_9|py35h8a80b8c_9|py36h8a80b8c_9|py27h8a80b8c_9|py37h8a80b8c_9|py37he97cb71_9|py35h9797aa9_8|py37ha9ae307_8|py36h9797aa9_8|py36ha9ae307_8|py27ha9ae307_8|py36ha9ae307_7|py27ha9ae307_7|py27ha9ae307_7|py36ha9ae307_7|py35h9797aa9_7|py37ha9ae307_7|py36ha9ae307_6|py37ha9ae307_6|py37h9797aa9_6|py36h6575580_0']
psi4=1.4a2.dev1058 -> numpy[version='>=1.12.0'] -> numpy-base[version='1.14.3|1.14.3|1.14.3|1.14.3|1.14.3|1.14.3|1.14.4|1.14.4|1.14.4|1.14.4|1.14.4|1.14.4|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.3|1.15.3|1.15.3|1.15.3|1.15.3|1.15.3|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.2|1.16.2|1.16.2|1.16.2|1.16.2|1.16.2|1.16.3|1.16.3|1.16.3|1.16.3|1.16.3|1.16.3|1.16.4|1.16.4|1.16.4|1.16.4|1.16.4|1.16.4|1.16.5|1.16.5|1.16.5|1.16.5|1.16.5|1.16.5|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.17.2.*|1.17.3.*|1.17.4.*|1.18.1.*|1.18.5.*|1.19.1|1.19.1|1.19.1|1.19.1|1.19.1|1.19.1|1.19.2|1.17.0|1.17.0',build='py36h479e554_1|py27h479e554_1|py35h9797aa9_0|py27ha9ae307_0|py36ha9ae307_0|py36ha9ae307_0|py36h9797aa9_0|py27ha9ae307_0|py36h9797aa9_1|py36h9797aa9_2|py36ha9ae307_2|py37ha9ae307_2|py27ha9ae307_2|py36ha9ae307_3|py36h9797aa9_3|py37h9797aa9_3|py27ha9ae307_3|py27ha9ae307_4|py36ha9ae307_4|py37h9797aa9_4|py35h9797aa9_4|py35ha711998_4|py37ha711998_4|py27ha711998_4|py37h8a80b8c_4|py38ha711998_4|py38h6575580_4|py27ha711998_5|py36h6575580_5|py27h6575580_5|py37h8a80b8c_0|py35h8a80b8c_0|py37h42e5f7b_0|py36h8a80b8c_0|py35h42e5f7b_0|py36h42e5f7b_0|py27h42e5f7b_0|py35h8a80b8c_0|py36ha711998_0|py35ha711998_0|py27ha711998_0|py27h8a80b8c_0|py37ha711998_1|py36ha711998_1|py27h8a80b8c_1|py36h8a80b8c_1|py37ha711998_0|py36ha711998_0|py27h8a80b8c_0|py37h8a80b8c_0|py36h8a80b8c_0|py37h6575580_0|py37h6575580_0|py27h6575580_0|py27ha711998_1|py37h6575580_1|py36ha711998_1|py37ha711998_1|py27h6575580_1|py37ha711998_0|py27h6575580_0|py37h6575580_0|py36ha711998_1|py37h6575580_1|py37ha711998_1|py36h6575580_1|py37ha711998_0|py27h6575580_0|py37h6575580_0|py36ha711998_0|py37h6575580_0|py37h6575580_0|py27h6575580_0|py37h6575580_0|py36ha711998_0|py37h6575580_0|py38ha711998_0|py27h6575580_0|py36h68fea81_0|py38hcfb5961_0|py38hcfb5961_0|py36h68fea81_0|py37h68fea81_0|py38h68fea81_0|py37hcfb5961_0|py36hcfb5961_0|py36hcfb5961_0|py37h68fea81_0|py37hcfb5961_0|py38h68fea81_0|py27ha711998_0|py38h6575580_0|py36h6575580_0|py37ha711998_0|py36h6575580_0|py27ha711998_0|py36ha711998_0|py37ha711998_0|py36h6575580_0|py27h6575580_0|py27ha711998_0|py37ha711998_0|py36ha711998_0|py36h6575580_0|py27h6575580_0|py37ha711998_0|py27ha711998_0|py36h6575580_0|py27ha711998_0|py36ha711998_0|py27ha711998_1|py27h6575580_1|py36h6575580_0|py27ha711998_0|py36ha711998_0|py36h6575580_1|py36h6575580_0|py36ha711998_0|py37ha711998_0|py27ha711998_0|py36h6575580_0|py27h6575580_0|py37ha711998_0|py36ha711998_0|py27ha711998_0|py27h8a80b8c_0|py36h8a80b8c_0|py27ha711998_0|py37h8a80b8c_0|py37h8a80b8c_1|py27ha711998_1|py35ha711998_0|py36ha711998_0|py36h8a80b8c_0|py37ha711998_0|py35h8a80b8c_0|py37h8a80b8c_0|py37ha711998_0|py27ha711998_0|py37h8a80b8c_0|py27h8a80b8c_0|py35he97cb71_0|py36he97cb71_0|py37he97cb71_0|py36h8a80b8c_0|py27h8a80b8c_0|py27he97cb71_0|py37h6575580_5|py37ha711998_5|py36ha711998_5|py27h8a80b8c_4|py36h8a80b8c_4|py35h8a80b8c_4|py36ha711998_4|py35ha9ae307_4|py37ha9ae307_4|py36h9797aa9_4|py27h9797aa9_4|py37ha9ae307_3|py27h9797aa9_3|py27h9797aa9_2|py37h9797aa9_2|py36ha9ae307_1|py27ha9ae307_1|py37ha9ae307_1|py37h9797aa9_1|py27h9797aa9_1|py35h9797aa9_0|py35ha9ae307_0|py27h9797aa9_0|py35ha9ae307_0|py36h9797aa9_0|py27h9797aa9_0|py35h7ef55bc_1|py27h7ef55bc_1|py35h479e554_1|py36h7ef55bc_1|py36h6575580_0|py36ha711998_0']

Package intel-openmp conflicts for:
psi4=1.4a2.dev1058 -> ambit[version='>=0.5.1,<0.6.0a0'] -> intel-openmp
blas[build=mkl] -> mkl -> intel-openmp

Package numpy conflicts for:
psi4=1.4a2.dev1058 -> mkl-service[version='>=2,<3.0a0'] -> numpy[version='>=1.11.3,<2.0a0']
psi4=1.4a2.dev1058 -> numpy[version='>=1.12.0']
</details>

Looking at this a little, I can't really find the root of the conflict. There's a lot of text dedicated to blas and NumPy stuff, but nothing that actually seems problematic. The `llibgfortran`/`libgfortran4` split may be something, may not be.

**Comment by loriab** [comment]
I’m still suspicious of those blas/pin/implementation combos up in the first block. Psi really has no constraints on numpy. The >=0.12 was just there to settle a mkl problem iirc. I wonder what installing Psi4, then force removing numpy, then trying an ambertools install would do.

**Comment by mattwthompson** [comment]
>= 1.12 is very reasonable as it's a few years old, and I think pins like >= 1.16 are likely to happen elsewhere

Following your suggestion, conda chokes with more errors than fit on my terminal's history, but mamba complains about 

```
Problem: package ambertools-20.0-py37h18738c5_0 requires netcdf-fortran >=4.5.2,<4.6.0a0, but none of the providers can be installed
```

yet here's a 4.5.3 online: https://anaconda.org/conda-forge/netcdf-fortran/files / https://anaconda.org/conda-forge/netcdf-fortran/files/modal/info/5f8e0b60a58f0d0a54b46bb2

 hdf5 1.10.6 seems to be in the recent psi4 builds, so that shouldn't be the issue. Maybe it's the fortran stuff, it's confusing how and why `libgfortran`/`libgfortran4`/`libgfortran5` all coexist at once.

**Comment by loriab** [comment]
so the environment is solvable on Linux:
```conda create -n amber ambertools=20.9 python=3.7 blas=*=mkl gau2grid psi4/label/dev::libxc psi4/label/dev::psi4=1.4a2.dev1058 -c conda-forge -c defaults -c psi4/label/dev```

on Mac, I agree that `libgfortran` is the problem. it comes about b/c conda-forge pins on gfortran v4 and defaults on gfortran v3 (then there's various soversions and libgfortran versions, too). once upon a time, the pinning that was applied by run_exports was >3.0.1, but that's been narrowed to >3.0.1,<4.0.0 . there's still some old add-on packages with the former, so if I suppress the libgfortran pinning on psi4 itself (psi4=1.4a2.dev1084 for py37 at https://anaconda.org/psi4/psi4/files), then I can get an environment to solve with it and ambertools=20. of course, then the libgfortran.3.dylib is missing, but if I symlink (!) that to libgfortran.4.dylib, I can get some psi4 test cases to pass (gdma fails to load lib, while some dft is off a bit). altogether, not a satisfactory or safe fix. and libxc is both required and fortran, so I can't just build you a non-fortran psi4. so unless I think of something else, I think you just can't mix fortran dependencies when compiled against a mix of c-f and defaults pinnings. sorry.

**Comment by andysim** [comment]
LibXC is written in C, so there might be some hope for a limited functionality (no PCMSolver or GDMA) version of Psi4 as a way forwards.

**Comment by loriab** [comment]
Of course libxc is in C. Thanks, Andy, for the correction. So yes, a non FORTRAN is do-able. Will probably be off a separate sub channel.

**Comment by mattwthompson** [comment]
Thanks for the explanation and digging. It's nice that there appears to be a possible path forward. After some tinkering, I don't think symlinking a partially-functional Psi4 build in the middle of a CI run is going to be the worth the downsides. We don't need this urgently, so it may be best to table this for a bit (unless somebody else happens to need it).

**Comment by loriab** [comment]
I've made a nofortran py37 Mac build accessible through `conda create -n amber3 ambertools=20 blas=*=mkl psi4/label/dev::libxc psi4 -c conda-forge -c psi4/label/nofortran -c psi4/label/dev`. It won't get automatically updated regularly, but I can do so upon pinging. Hopefully this'll do for CI. lmk if a different python preferred.

**Comment by dotsdl** [comment]
Thank you so much @loriab! @SimonBoothroyd, will this work for you for the time being?

**Comment by loriab** [comment]
I'm going to call this solved since we can produce a no-fortran osx build whenever needed.
