### ISSUE TITLE
[feature request] MBIS radial moments

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#2041]
Taken from the forum: http://forum.psicode.org/t/mbis-radial-moments/1990

"Would it be possible to also compute/output the third radial moment of the atomic electron density, ie eq 24 from this paper?: https://pubs.acs.org/doi/10.1021/acs.jctc.6b00456

This would be really valuable for dispersion C6 coefficients, and should be readily accessible from the MBIS partitioned AIM densities."

@andyj10224 @zachglick  thoughts?

**Comment by zachglick** [comment]
Yeah, MBIS radial moments (along with a few other properties) are already in the works. I'll be sure to ping @djcole56 when it's done.

**Comment by djcole56** [comment]
That would be great, thank you!

**Comment by loriab** [comment]
this is planned separately from #2056, right?

**Comment by andyj10224** [comment]
Actually, the third radial moment and the expected volume are the same thing, so for the third radial moment, you would just call my code with an exponent of 3.0

**Comment by djcole56** [comment]
Yes these are the same quantities so #2056 will also resolve my original feature request. Thanks.
