### ISSUE TITLE
improve matrix multiplication order

### ISSUE THREAD

**Issue by zachglick** [psi4/psi4#2052]
When multiplying three matrices `A`, `B`, and `C` together in Psi4, the matrix multiplication is always performed as `((AB)C)`:
https://github.com/psi4/psi4/blob/2f085df4cab054b8b01c3e5c0bc1e1270c2e7bf2/psi4/src/psi4/libmints/matrix.cc#L3404-L3409
In some cases, this might result in more overall work than the equivalent `(A(BC))`. We should probably check for this, and choose the cheaper ordering.

**Comment by loriab** [comment]
closed by #2053
