### ISSUE TITLE
Allow to modify wavefunction from python

### ISSUE THREAD

**Issue by mysovsky** [psi4/psi4#2086]
Dear PSI4 developers,
Your project is amazing!!!
I recently found it and I should say that with Psi4 it is so easy to implement new methods and modify existing ones. Much easier than with any other package! Thank you for that!
Currently I need to implement constraint modification of SCF. It is not very difficult to do from python using Psi4numpy examples.
However, when modified SCF is finished and I have molecular orbitals and density matrix, it is difficult to make population analysis. 
psi4.oeprops requires wavefunction, and it is hardly possible to create correct wavefunction from orbitals and density I have.

**My suggestion is**: implement inside Wavefunction class certain methods to modify MO coefficients and density matrices, number of occupied states, etc. Export these methods in python. This can be done schematically like that:

File ```psi4/src/psi4/libmints/wavefunction.cc```
```c++
void Wavefunction::set_matricies(std::map<std::string, std::shared_ptr<Matrix>> matrices) {
    // set matrices
  if (matrices.count("Ca")==1)
    Ca_ = matrices["Ca"];
  if (matrices.count("Cb")==1)
    Cb_ = matrices["Cb"];
  if (matrices.count("Da")==1)
    Da_ = matrices["Da"];
  if (matrices.count("Db")==1)
    Db_ = matrices["Db"];
  if (matrices.count("Fa")==1)
    Fa_ = matrices["Fa"];
...........................
}

void Wavefunction::set_integers(std::map<std::string, int> ints){
    // set integers
  if (ints.count("nalpha")==1)
    nalpha_ = ints["nalpha"];
  if (ints.count("nbeta")==1)
    nbeta_ = ints["nbeta"];
.....................................
}
```
And, of course, corresponding definitions in ```psi4/src/psi4/libmints/wavefunction.h``` and ``psi4/src/export_wavefunction.cc``

**Comment by hokru** [comment]
There are various ways to modify the wfn object at the python level. E.g. using the numpy interface (https://psicode.org/psi4manual/master/numpy.html) or wfn serialization (https://github.com/psi4/psi4/blob/master/samples/serial-wfn/input.dat)

You can easily overwrite the Density or Coefficient matrix with a numpy array or a psi4 matrix object.

What is an example operation where our current interface is insufficient?

**Comment by mysovsky** [comment]
Thank you very much for your answer! The second link you give really explains how to convert  Wavefunction to dictionary and vice versa. And it is indeed possible to change necessary things in the dictionary.
Concerning the first link, I didn't find there anything about wavefunction. That might be my problem, I often do not see things just in front of my eyes.
However, there is an example when it is difficult modify a wavefunction in a desired manner. If I have normal wavefunction resulting from
```SCF_E_psi, scf_wfn = psi4.energy('SCF', return_wfn=True)```
And after that I want to change 1) nuclear charges in the molecule; 2) number of occupied states; 3) orbitals and density;
the conversion to dictionary and back does not work because psi4 thinks that charge, multiplicity and the number of occupied states are inconsistent (which is not in fact true).

By the way, special thanks to you for the possibility to set arbitrary fractional nuclear charges!!! 
When I found it, I felt really really lucky! It is crucial for the approach I am trying implement.

**Comment by hokru** [comment]
The first link tells you that you can modify psi4's C++ matrices inplace with numpy views like this:
`scf_wfn.Da().np[:]=my_numpy_array` (check the link for matrices with irreps)

What do you want to do (in psi4) with the modified wfn object? With detailed information or some code part it is difficult to advise.

**Comment by mysovsky** [comment]
Thank you! That was really stupid for me. I even didn't try to use wfn.Da() for modification of density matrix. I was sure it is read-only because it is declared ```SharedMatrix Ca() const;```
This removes my question.
