### ISSUE TITLE
Docs Update: NumPy Interface

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#2087]
The code samples on the [Interface to NumPy page of the documentation](https://psicode.org/psi4manual/master/numpy.html) do not currently run. A forum report says that at the least, `psi4.Matrix` needs to be replaced with `psi4.core.Matrix`. Somebody should check that all the code on that page actually runs, and that it's accessible to non-experts. I've had to link a couple forum users to that page lately.

This is a great project for a new developer who wants to learn the fundamentals of the manual.

**Comment by VHchavez** [comment]
I would not mind trying to fix this. 
I am not very familiar with the manual. I have identified the .rts file on the repo. But I am uncertain if any other files need to be updated as well.

**Comment by loriab** [comment]
go for it! since you're not adding more files (that the buildsys would need to be aware of), just editing the one is fine. main thing to remember with restructured text is that it likes its whitespace and neatly aligned tables, so don't clean up blank lines or overextend table cells.

**Comment by loriab** [comment]
closed by #2089
