### ISSUE TITLE
FNO-DF-CCSD problems on i7-5930

### ISSUE THREAD

**Issue by ryanmrichard** [psi4/psi4#209]
The following job converges to a nonsensical CCSD correlation energy (about -4 hartrees) on our i7-5930 nodes.  Even on iteration 2, the problem is manifesting:
```
   Iter  DIIS          Energy       d(Energy)          |d(T)|     time
      0   0 1   -2.3661052959   -2.3661052959    0.8065388359       14
      1   1 1   -3.3098744652   -0.9437691693    1.5557928713      155
```

```
molecule{
C 2.072533 0.400337 0.000000 
C 2.351068 -0.237230 -1.205081 
C 2.351068 -0.237230 1.205081 
C 2.908137 -1.512363 -1.205081 
C 2.908137 -1.512363 1.205081 
C 3.186672 -2.149930 0.000000 
H 1.640169 1.390021 0.000000 
H 2.134886 0.257612 -2.140393 
H 2.134886 0.257612 2.140393 
H 3.124320 -2.007205 -2.140393 
H 3.124320 -2.007205 2.140393 
H 3.619036 -3.139614 0.000000 
C -1.382969 1.594698 0.000000 
C -0.970087 2.154700 -1.205081 
C -0.970087 2.154700 1.205081 
C -0.144324 3.274703 -1.205081 
C -0.144324 3.274703 1.205081 
C 0.268558 3.834704 0.000000 
H -2.023878 0.725418 0.000000 
H -1.290542 1.720059 -2.140393 
H -1.290542 1.720059 2.140393 
H 0.176131 3.709343 -2.140393 
H 0.176131 3.709343 2.140393 
H 0.909467 4.703984 0.000000 
C -0.689564 -1.995035 0.000000 
C -1.380981 -1.917470 -1.205081 
C -1.380981 -1.917470 1.205081 
C -2.763814 -1.762339 -1.205081 
C -2.763814 -1.762339 1.205081 
C -3.455230 -1.684774 0.000000 
H 0.383709 -2.115439 0.000000 
H -0.844344 -1.977672 -2.140393 
H -0.844344 -1.977672 2.140393 
H -3.300450 -1.702138 -2.140393 
H -3.300450 -1.702138 2.140393 
H -4.528503 -1.564371 0.000000 
}
memory 60 Gb
set{
basis cc-pvdz
freeze_core true
scf_type df
guess SAD
}

energy('FNO-DF-CCSD(T)')
```

**Comment by edeprince3** [comment]
I confirm this job fails on i7-5930k with multiple threads, but it works in serial.  I'm working on it.

**Comment by edeprince3** [comment]
Does anyone have an i7-5930 or other Haswell CPU and a version of MKL other than 15.0.2?  

I have convincved myself this is an MKL issue.  MKL_NUM_THREADS=1 and OMP_NUM_THREADS>1 works just fine.  MKL_NUM_THREADS>1 fails.  I stripped out all of my own OMP pragmas, and they aren't the source of the problem.

I've also determined that this job runs fine using ATLAS BLAS.  I haven't been able to get ACML to work on i7-5930k.

**Comment by loriab** [comment]
We've got 15.0.1 and 15.0.3, but I think the problem with the latter is essentially confirmed.

**Comment by ryanmrichard** [comment]
Intel 16.0.2 compilers with MKL 11.3.2 seems to work fine on the i7-5930 with parallel enabled.  Not sure whether it was the compiler or the MKL upgrade that fixed it, but either way, I can run my calculations again.  Yay.  I'm going to chock this up to a compiler bug and close the issue.

**Comment by loriab** [comment]
Sounds good. Maybe leave a note in the fnocc.rst docs that this can go wrong on some architecture/compiler combinations and point to this issue.
