### ISSUE TITLE
Missing basis sets in file, even though it says should be on top?

### ISSUE THREAD

**Issue by bdw2292** [psi4/psi4#2097]
/home/bdw2292/miniconda3/envs/p4env/share/psi4/basis/6-311pgs.gbs

! Ga - Kr:    L. A. Curtiss, M. P. McGrath, J-P. Blandeau, N. E. Davis,
!             R. C. Binning, Jr. L. Radom, J. Chem. Phys. 103, 6104 (1995).
! I      :    M.N. Glukhovstev, A. pross, M.P. McGrath, L. Radom, J. Chem. Phys.
!             103, 1878 (1995)
!
!
!  6-311G* Polarization  EMSL  Basis Set Exchange Library   8/18/10 10:51 PM
! Elements                             References
! --------                             ----------

! Ga - Kr: L. A. Curtiss, M. P. McGrath, J-P. Blandeau, N. E. Davis, R. C.
!          Binning, Jr., L. Radom, J. Chem. Phys. 103, 6104 (1995)
!
Some of these elements seem to be missing in this file.

**Comment by loriab** [comment]
Those comments aren't always 1:1 with the contents.

But what's happening for 6-311+G* in particular is that 3 partial basis sets are getting merged: the 6-311 defined through Kr, the polarization defined through Kr, and the diffuse only defined through Ca. Only elements with partial basis sets available for all three pieces show up in the full basis file, so Kr, etc. are missing. Looking at 6-311+G* at https://www.basissetexchange.org/, that ends at Ca, too, so nothing to update. Does this clear up what's going on?

**Comment by bdw2292** [comment]
Okay thanks! I will close :)
