### ISSUE TITLE
Runtime error while running DMRG calculation

### ISSUE THREAD

**Issue by alhajri** [psi4/psi4#2102]
Hi all,

I am getting the following error while running a DMRG calculation. I am using version 1.1rc1

> `###########################################################
> ###                                                     ###
> ###                       DMRG-SCF                      ###
> ###                                                     ###
> ###            CheMPS2 by Sebastian Wouters             ###
> ###        https://github.com/SebWouters/CheMPS2        ###
> ###   Comput. Phys. Commun. 185 (6), 1501-1514 (2014)   ###
> ###                                                     ###
> ###########################################################
> 
> Number of variables in the x-matrix = 22549
> CheMPS2 output is temporarily written to the file singlet.dmrg.out.chemps2 and will be copied here.
>         Presorting SO-basis two-electron integrals.
>         Sorting File: SO Ints (nn|nn) nbuckets = 47
> 
> Traceback (most recent call last):
>   File "/home/AzureUser/psi4conda/bin/psi4", line 247, in <module>
>     exec(content)
>   File "<string>", line 100, in <module>
>   File "/home/AzureUser/psi4conda/lib//python3.5/site-packages/psi4/driver/driver.py", line 454, in energy
>     wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
>   File "/home/AzureUser/psi4conda/lib//python3.5/site-packages/psi4/driver/procrouting/proc.py", line 3081, in run_dmrgci
>     dmrg_wfn = core.dmrg(ref_wfn)
> 
> RuntimeError:
> Fatal Error: PSIO Error
> Error occurred in file: /scratch/psilocaluser/conda-builds/psi4_1491459515796/work/psi4/src/psi4/libpsio/error.cc on line: 128
> The most recent 5 function calls were:
> 
> psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)
> psi::psio_error(unsigned int, unsigned int)
> psi::PSIO::rw(unsigned int, char*, psi::psio_address, unsigned long, int)
> psi::IntegralTransform::presort_so_tei()
> psi::IntegralTransform::transform_tei_first_half(std::shared_ptr<psi::MOSpace>, std::shared_ptr<psi::MOSpace>)
> 
> 
> *** Psi4 encountered an error. Buy a developer more coffee!
> *** Resources and help at github.com/psi4/psi4.`

**Comment by TiborGY** [comment]
While I do not know the cause of this I have 2 comments:
1. You are using a very old psi4 version, maybe you should consider upgrading.
2. Check that you have not ran out of disk space on the volume that you are using for scratch

**Comment by JonathonMisiewicz** [comment]
In addition to TiborGY's very important points, without an input file, we cannot offer much assistance.

**Comment by alhajri** [comment]
Thank you for the comments, here is my input file:

> molecule DBT {
> 0 1
>     C           -5.001124515335    -0.696370177621    -0.000000001110
>     C           -5.001124776935     0.696369011536    -0.000000001080
>     C           -3.790985436281     1.324918263121    -0.000000000781
>     C           -2.484189865656     0.725977543234    -0.000000000461
>     C           -2.484189231540    -0.725978465954    -0.000000000428
>     C           -3.790984907078    -1.324919088326    -0.000000000804
>     C           -1.260556476854    -1.493619214818    -0.000000000020
>     C           -1.253840838229    -3.006151300763     0.000000000286
>     C           -2.376986345192    -3.864004327695     0.000000000650
>     C           -2.371008169108    -5.260721617653     0.000000000787
>     C           -1.186070559950    -5.926401470223     0.000000000627
>     C            0.000034813738    -5.168619628056     0.000000000425
>     C            1.186076421827    -5.926418032065     0.000000000396
>     C            2.371027308777    -5.260778866433     0.000000000252
>     C            2.377201552688    -3.864082335540     0.000000000112
>     C            1.254036161725    -3.006197699269     0.000000000127
>     C            0.000119384846    -3.710808325660     0.000000000275
>     C            1.260479526897    -1.493606925183     0.000000000003
>     C            2.484054456823    -0.725929715557    -0.000000000143
>     C            3.790822029142    -1.324855222289    -0.000000000258
>     C            5.000968382164    -0.696360998262    -0.000000000427
>     C            5.000968461797     0.696359319911    -0.000000000492
>     C            3.790822184646     1.324853439246    -0.000000000402
>     C            2.484054849326     0.725927552706    -0.000000000250
>     C            1.260479850438     1.493607229257    -0.000000000237
>     C            1.254036594003     3.006197788669    -0.000000000198
>     C            2.377202449559     3.864082579975    -0.000000000284
>     C            2.371028479258     5.260779551299     0.000000000016
>     C            1.186076881291     5.926418880955     0.000000000435
>     C            0.000034230769     5.168621037950     0.000000000460
>     C           -1.186070982869     5.926402665426     0.000000000862
>     C           -2.371009332819     5.260722574272     0.000000000992
>     C           -2.376988297085     3.864005029304     0.000000000711
>     C           -1.253843032462     3.006151598191     0.000000000160
>     C            0.000118085190     3.710807957900     0.000000000103
>     C           -1.260557226131     1.493619582118    -0.000000000155
>     C           -0.000034659568     0.759625960521    -0.000000000159
>     C           -0.000034625713    -0.759624178218    -0.000000000042
>     H           -5.916030845275    -1.282197811131    -0.000000001395
>     H           -5.916031258658     1.282196125448    -0.000000001329
>     H           -3.903819438194     2.368212991154    -0.000000000840
>     H           -3.903818961364    -2.368213684326    -0.000000000900
>     H           -3.380202809742    -3.532377155298     0.000000000843
>     H           -3.323483157889    -5.783256218484     0.000000001017
>     H           -1.123533880262    -7.010678898257     0.000000000718
>     H            1.123569529821    -7.010687056820     0.000000000512
>     H            3.323444251476    -5.783425057171     0.000000000238
>     H            3.380590817837    -3.532764155114     0.000000000007
>     H            3.903306158089    -2.368093837703    -0.000000000251
>     H            5.915904268397    -1.282153443029    -0.000000000487
>     H            5.915904332310     1.282151831717    -0.000000000600
>     H            3.903306767856     2.368091938384    -0.000000000491
>     H            3.380592041773     3.532764158212    -0.000000000516
>     H            3.323445571900     5.783426049843    -0.000000000059
>     H            1.123570392243     7.010688579024     0.000000000716
>     H           -1.123534819764     7.010680587949     0.000000001092
>     H           -3.323484052934     5.783257818228     0.000000001355
>     H           -3.380204830685     3.532377523087     0.000000001020
> }
> set basis 6-31g
> set reference rhf
> set scf_type DIRECT
> set e_convergence 1e-10
> set d_convergence 1e-8
> set ints_tolerance 0.0
> 
> set dmrg_irrep 0
> set dmrg_multiplicity 1
> set restricted_docc [105,0]
> set active [0,38]
> 
> set dmrg_sweep_states         [200,  400,  600,  800]
> set dmrg_sweep_energy_conv    [1e-6, 1e-6, 1e-8, 1e-10]
> set dmrg_sweep_dvdson_rtol    [1e-5, 1e-5, 1e-5, 1e-8]
> set dmrg_sweep_max_sweeps     [10,   10,   8,   6]
> set dmrg_sweep_noise_prefac   [0.05, 0.05, 0.05, 0.0]
> set dmrg_scf_active_space     loc
> set dmrg_scf_max_iter         100
> set dmrg_mps_write            true
> 
> energy("dmrg-ci")

I believe this might be a memory issue because this exact input file but with the sto-3g basis runs as expected, "upgrading" the basis set introduces this error.

**Comment by JonathonMisiewicz** [comment]
Yes, it looks like you need to include a line to set your memory. Psi4 gives 500 MB unless otherwise specified, and I can imagine CheMPS2 is starved for more.

I recommend you read [the tutorial](https://psicode.org/psi4manual/master/tutorial.html) if you haven't already.

For future bug reports, you do need to give an example on a more up-to-date version of Psi. 1.1rc1 is ancient, by the standards of software development. You can get a newer version off of conda.

**Comment by alhajri** [comment]
Thanks!
