### ISSUE TITLE
SAD and core guesses give very different UHF energies

### ISSUE THREAD

**Issue by robertodr** [psi4/psi4#211]
Choosing a SAD or a core guess for an UHF/cc-pVDZ calculation on H2O+ gives very different energies.
The following input with the core guess gives a total energy of -75.5488580481183476

```
memory 250 mb
molecule h2o {
symmetry c1
1 2
O    0.0000000000         0.0000000000        -0.2249058930
H    1.4523499293         0.0000000000         0.8996235720
H   -1.4523499293         0.0000000000         0.8996235720
units bohr
no_reorient
no_com
}

set {
  basis cc-pVDZ
  scf_type direct 
  guess core 
  reference uhf
  e_convergence 7
  d_convergence 7
}

energy_scf1 = energy('scf')
```

while this input with the SAD guess gives a total energy of -75.6330881795159655

```
memory 250 mb
molecule h2o {
symmetry c1
1 2
O    0.0000000000         0.0000000000        -0.2249058930
H    1.4523499293         0.0000000000         0.8996235720
H   -1.4523499293         0.0000000000         0.8996235720
units bohr
no_reorient
no_com
}

set {
  basis cc-pVDZ
  scf_type direct 
  guess sad 
  reference uhf
  e_convergence 7
  d_convergence 7
}

energy_scf1 = energy('scf')
```

Of course, the initial guess has always a huge impact on the calculation, but is the reported difference reasonable for a system as small as H2O+?

**Comment by robparrish** [comment]
I have seen this before (for this exact system) - the SAD guess converges
to the correct root, but Core does not. Not really much more to it than
that.

-Rob

**Comment by jgonthier** [comment]
Are both solutions stable ? For UHF computations, it seems to me always
more safe to do a stability analysis. In some cases, it allowed me to
eliminate the higher energy solution as unstable.

However, in other cases, both solutions are actually SCF minima... Trying
with different guesses then seems the only way to find the lowest energy
solution.

2016-01-14 2:42 GMT-05:00 Rob Parrish <notifications@github.com>:

> I have seen this before (for this exact system) - the SAD guess converges
> to the correct root, but Core does not. Not really much more to it than
> that.
>
> -Rob
>
>
> On Wed, Jan 13, 2016 at 11:33 PM, Roberto Di Remigio <

**Comment by lothian** [comment]
It is perhaps noteworthy that certain other codes converge this case even
with a core guess.

-TDC

--
Prof. T. Daniel Crawford
crawdad@vt.edu

**Comment by robertodr** [comment]
@jgonthier the solution found when starting from the core guess is indeed unstable.

**Comment by jgonthier** [comment]
@lothian I guess these other codes are using some other convergence accelerator than Psi4 ? I would not be surprised if SOSCF with a core guess would converge on the right solution.

**Comment by dgasmith** [comment]
Looks like we are too deep into the wrong minima when SOSCF kicks in:

```
   @DF-UHF iter   1:   -70.52704301674179   -7.05270e+01   1.15053e-01
   @DF-UHF iter   2:   -73.27465610608667   -2.74761e+00   7.91186e-02 DIIS
   @DF-UHF iter   3:   -75.49454380091507   -2.21989e+00   1.55274e-02 DIIS
   @DF-UHF iter   4:   -75.54596974985091   -5.14259e-02   2.86647e-03 DIIS
   @DF-UHF iter   5:   -75.54856874850068   -2.59900e-03   6.41592e-04 SOSCF, nmicro = 4
   @DF-UHF iter   6:   -75.54884166553249   -2.72917e-04   6.20612e-06 SOSCF, nmicro = 4
   @DF-UHF iter   7:   -75.54884168721047   -2.16780e-08   4.42160e-08 SOSCF, conv
```

We can try adding some trust region mechanics to start a bit earlier if need be.

**Comment by ssh2** [comment]
I would add that lately we have seen a lot of problems with UHF and ROHF
converging on a wrong state for open-shells in Psi4. Although new stability
analysis code helps a lot in fixing some of the problems (for UHF), for
many of these systems finding the lowest root is quite non-trivial and is
accompanied by many SCF convergence issues, as well as symmetry-breaking
issues (UHF). Things get a lot worse for transition metal compounds (even
simple ones, like Fe(CO)5). The most helpful solution is to start with
basis set projection from a small basis, but this strategy doesn't always
work. Sometimes, combining stability analysis root search and basis set
projection helps.

Indeed, other codes (particularly, MOLPRO) sometimes do better job in
finding lowest-energy solutions for systems of this type. Usually, after
investing some time, it is possible to find the necessary solution for
these non-trivial cases with Psi4, but it may be worth investigating some
of these systems for possible improvements in the code.

Best wishes,

Alexander.

**Comment by ssh2** [comment]
To Jerome's point, I would agree that for UHF doing stability analysis
helps a lot. However, we have also seen cases when stability analysis
severely breaks spin symmetry and converges on the wrong (or mixed) spin
state instead of the lowest energy root of desired spin. So one should be
careful about this issue.

Best wishes,

Alexander.

**Comment by jgonthier** [comment]
Yes, one of the cases where a stability analysis is detrimental is
closed-shell benzene with UHF. The closed-shell solution is unstable and
the stable UHF solution looks like a singlet hexaradical... Unfortunately I
believe this is related to the intrinsic spin contamination in UHF. There
are specific methods that can constrain or project UHF solutions to
alleviate this problem.
ROHF also avoids spin contamination, but lacks description of spin
polarization, which may sometimes be of interest.

2016-01-14 9:43 GMT-05:00 ssh2 <notifications@github.com>:

> To Jerome's point, I would agree that for UHF doing stability analysis
> helps a lot. However, we have also seen cases when stability analysis
> severely breaks spin symmetry and converges on the wrong (or mixed) spin
> state instead of the lowest energy root of desired spin. So one should be
> careful about this issue.
>
> Best wishes,
>
> Alexander.
>
> On Thu, Jan 14, 2016 at 9:38 AM, Alexander Sokolov <

**Comment by kannon92** [comment]
Jerome, Have you played around with CUHF at all for the stability analysis?

I know that this method avoids spin contamination.

**Comment by jgonthier** [comment]
No, I haven't. And my next goals for stability analysis are more for RHF
and ROHF, since it's what most people use... But even these, I don't know
when I'll have time for it...

2016-01-14 12:00 GMT-05:00 Kevin Hannon <notifications@github.com>:

**Comment by dgasmith** [comment]
Added a note that SCF could a smarter solver to the developer wish list.
