### ISSUE TITLE
Optimization/frequency calculations using JSON

### ISSUE THREAD

**Issue by pastaalfredo** [psi4/psi4#2117]
I and my colleagues are trying to transition into using JSON in- and output files for Psi4 to add another layer of structure to our database. We understand that this is a work in progress, but I can't find any examples of what would work for optimization and/or frequency calculations in the examples dir (https://github.com/psi4/psi4/tree/master/tests/json).

I tried changing one of the example input files to adapt it to our own type of calculations, but I just get errors while running it using the --qcschema flag as I can't seem to get the structure of the JSON file right. Is there an unfinished guide on how to create these JSON files?

Let say I have a non-JSON file that looks like the following:
```
molecule mol_water {
        0 1
        O  0.000000000  0.000000000  0.117000000
        H  0.000000000  0.763400000  -0.468100000
        H  0.000000000  -0.763400000  -0.468100000

        units angstrom
        no_reorient
}

set globals {
        basis aug-cc-pVTZ
        dft_spherical_points 434
        dft_radial_points 85
}

set_memory(25000000000)

try:
    optimize('pwpb95-d3bj')
except SCFConvergenceError as e:
    unconverged_scf_wfn = e.wfn
    unconverged_scf_wfn.to_file(unconverged_scf_wfn.get_scratch_filename(180))
    set guess read
    optimize('pwpb95-d3bj')

E, wfn = frequency('pwpb95-d3bj', return_wfn=True)
print(wfn.frequencies().get(0, 0))
```

How would it be expressed as a valid JSON file?

**Comment by PeterKraus** [comment]
It is my understanding that this currently cannot be done using a single `json` file with Psi4 only. The interface only exposes `energy`, `gradient`, or `hessian` calls. 

I think the best way to do what you want is via the `qcengine` interface. There's an example of geometry optimization, where you specify a `rdkit` job inside a `geometric` job see here: 

https://github.com/MolSSI/QCEngine/blob/master/examples/Examples.ipynb

That example would have to be adapted for `psi4`.

**Comment by PeterKraus** [comment]
As also discussed in #2198, this won't be implemented until (if?) QC schema defines geometry optimisations. Closing.
