### ISSUE TITLE
Documentation: Obtaining Maintenance

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#2125]
The page for [obtaining Psi4](https://psicode.org/psi4manual/master/build_obtaining.html) has a mixture of broken links and outdated information. Reported on [forums](https://github.com/psi4/psi4/issues/2125).

Obligatory @hokru ping.

**Comment by loriab** [comment]
acknowledged :-(

**Comment by loriab** [comment]
#2164 should have fixed all the broken links, and I gave build_planning.rst, build_obtaining.rst, and conda.rst narrative docs a minimal pass there, too.
