### ISSUE TITLE
pre-1.0.0 items we mustn't forget

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#213]
Everyone feel free to add to this list.

* [x] make sure `(dirty)` isn't in the outfile header along with the git info. It's not supposed to be there when the source clone is clean. this just needs a perfectly clean samples set from the docsbuild.

* [x] make sure Additional authors gets additionally populated.

* change any copyright 2015 to 2016, particularly in copyright. I did psicode.org (moved to #349 )

* [ ] check that license boilerplate is present in all files (py-side and c-side). here's the guidelines from gpl, http://www.gnu.org/licenses/gpl-howto.en.html

* [x] new set of output.ref

**Comment by mbanck** [comment]
Not really related, but I think it makes sense to roll a release candidate once the code is frozen, so people not using git master can try building and running on various platforms. That might make an immediate brown-paperbag 1.0.1 release unnecessary or less likely.

**Comment by loriab** [comment]
Yes, we're planning on a series of release candidates after the necessary features are in wherein only bug fixes permitted. For the most part, we work on a nightly build release schedule, but yes, we do want 1.0.0 to be durable. Thanks for the new term, "brown-paperbag".

**Comment by mbanck** [comment]
OK.

About the brown-paperbag, I've now looked it up in the hacker dictionary, and I didn't mean it in that sense, sorry.

I use it in the sense of "maintainer successfully built and tested on their machine, but it's obviously broken on a different configuration they did not test".

**Comment by loriab** [comment]
Haven't found it in a hacker dictionary, but the sense you meant was the sense I took.

**Comment by wpoely86** [comment]
Euh, what's the version going to be? psi 1.0? psi4 1.0? psi4.1? We always used 4.0 as version, so if you now switch to 1.0, this would cause havoc as 1.0 is older then 4.0.

**Comment by loriab** [comment]
I know havoc and epochs and non-sortability ensue. We're actually trying to be *more* versioning standards compliant, since if we went with project `psi` and version `4.0` we couldn't ever make an API change w/o bumping to psi5. So the plan is that the stable release will be project `psi4` and version `1.0`, as in https://github.com/psi4/psi4public/wiki/Versioning#how-to-get-and-interpret-the-version-number .

**Comment by wpoely86** [comment]
I can understand why you would want to start over but why not start with a number bigger then 4? I mean, if you do an API change, you're gonna bump to `2.0`? That's the same issue as going from 4 to 5.

Why start with `psi4` 5.0? You can cleanly start over again and keep a bigger version number then all previous versions?

**Comment by CDSherrill** [comment]
I do think psi4 1.0 is a bit confusing to people, "official" numbering
schemes for other projects notwithstanding.  However, several members of
the core team thought this to be a good idea.

**Comment by loriab** [comment]
Being one of those who thought psi4 1.0 to be a good idea, I'll state that my main requirement is that the project name is `psi4` and that we have the ability to bump major (in major.minor.patch) in an API change without bumping psi generations to psi5. If everyone prefers the stable release as `psi4` & `4.0.0`, with future `psi4` & `5.0.0` instead of stable release `1.0.0` and future `2.0.0`, I can live with that. (Of course the psi5 folks someday may regret that decision.) Maybe it's time to start naming major releases after (house)cats.

**Comment by lothian** [comment]
I agree with the plan already in place.  API changes as we view them should
not be sufficient to bump us to PSI5, so naming the project PSI4 and
versioning against X.Y.Z makes sense to me.

-TDC

--
Prof. T. Daniel Crawford
crawdad@vt.edu

**Comment by wpoely86** [comment]
I didn't know psi5 already existed :laughing: 

I do prefer to start with a version number that is clearly 'newer' then the previous ones (like 4.0b5). And 1.0 seems like a downgrade.

**Comment by loriab** [comment]
Psi5 only exists in arguments about version naming :-) . I agree that `1.0.0` is out-of-sync with the released beta versions like 4.0b5. But it is in sync with the past 11 months (https://anaconda.org/psi4/psi4/files), ever since we started identifying commits by actual version numbers rather than just git hashes.

**Comment by wpoely86** [comment]
Well, as we already have 4.0b5 installed on our systems, we stuck to this version scheme (we suffixed with a date for git builds). So, suddenly going to 1.0 will not work with our version ordering schemes.

**Comment by loriab** [comment]
I'm sorry about the disruption. The executable or the config script or the output file will spit out the proper version, if that helps.

```bash
>>> bin/psi4 --version
0.4.14
>>> bin/psi4-config --version
0.4.14
```

```
    -----------------------------------------------------------------------
          Psi4: An Open-Source Ab Initio Electronic Structure Package
                              Psi4 0.4.14 Driver

                          Git: Rev {master} 2485238 dirty
```

**Comment by mbanck** [comment]
> Well, as we already have 4.0b5 installed on our systems, we stuck to this version scheme (we 
> suffixed with a date for git builds). So, suddenly going to 1.0 will not work with our version ordering 
> schemes.

Well, there are already the 0.1, 0.2 and 0.3 releases - I complained about the number downgrade, got schooled and bit the bullet by introducing an epoch in the version for the packages I maintain.

But if the developers decide to switch back to 4.0 as stable version, I won't complain, it's not a big deal to skip version numbers.  

In that case I guess there should be a note that psi5 really starts at 0.1 from the beginning (if people still use version numbers by then).

**Comment by CDSherrill** [comment]
Updated list of other contributors
