### ISSUE TITLE
Print additional output from TD-SCF calculations

### ISSUE THREAD

**Issue by lazaroid** [psi4/psi4#2153]
The TD-SCF code seems to work pretty well and comparably with other codes but the current level of output that appears in the output file by default is pretty minimal (energies, symmetries, oscillator strengths, etc.). A lot more info is available through various variables but they are pretty obscure and not the easiest to use.

After a brief discussion on the forum [forum](http://forum.psicode.org/t/td-scf-excited-state-densities-and-or-contributing-excitations-available-yet/2109) I was encouraged to add this as a github issue.

I'm happy to add these additions and, after a fair bit of fiddling, I think I have it mostly sussed. (And it's been a good learning experience: digging into RPA and TDA literature to some extent!)

I have a few additions to scf_response.py to output the set of TDM vectors and the most important excitations (and deexcitations) contributing to each excited state, and I will submit a pull request once I've cleaned it up a bit. However it currently only works for C1, i.e no symmetry.

One thing I have yet to get my head around is how to handle X and Y when symmetry is involved: comparing a calculation with C1 point group with the same molecule but using a higher point group, I can see the same coefficients within the sub-matrices for the different irreducible representations but I can't see how to unpick something like an "A -> B" single excitation that sees to appear only in the A representation sub-matrix. (If that makes sense!)

**Comment by lazaroid** [comment]
Pull request: #2156

It seems to work for all of the combination of rhf / uhf / tda / rpa I've thrown at it but one can ever be completely sure of these things!

**Comment by loriab** [comment]
fixed by #2156
