### ISSUE TITLE
naive Makefile for plugin from binary

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#216]
See conversation at https://github.com/psi4/psi4public/issues/214 . If an experienced psi4 developer checks out a plugin from the binary, he can guess what modifications the Makefile will need and proceed. If an inexperience user checks out a plugin from the binary, he may not even have a compiler. So there needs to be at least one easy and documented way to get the plugin working. This ticket is to make that happen.

* [x] Implement the Makefile template reference in https://github.com/psi4/psi4/issues/214#issuecomment-172256746 . There's a cmake variable `-DENABLE_CONDA_DEST` that you can use to tell c-side if it's a conda build.
* [ ] Use that same cmake variable to print to the user a link to the manual on compiling plugins from conda
* [ ] at that manual page, talk about
    * conda env w/`psi4`, `gcc`, `openblas`
    * must _activate_ conda env
    * register plugins at https://github.com/psi4/psi4public/blob/master/lib/python/aliases.py#L46
    * place plugins a la https://github.com/psi4/psi4meta/blob/master/conda-recipes/csx4psi/build.sh

I'm not sure myself how `PYTHONPATH`/`PSIPATH` is picking up on where plugins located. Conda metapackage is still under assembly, so don't do too detailed docs yet. The first two bullets are ready, though.

* [ ] in doc/sphinxman/plugins.rst, review and update the available plugin flavors
* [ ] in doc/sphinxman/plugins.rst, remove reference to needing `--with-plugins`, as everything is fPIC these days

**Comment by fevangelista** [comment]
@loriab, I think we might be able to check the first box.  I tested on my linux box and I can compile and run plugins with scf and mointegrals.  Do you want a separate manual page or it is ok to post new info in the same page where we describe "--new-plugin"?

**Comment by loriab** [comment]
Great, 1st box checked! Same manual page is fine. Will just link to subsection.

**Comment by fevangelista** [comment]
@loriab, my pull request https://github.com/psi4/psi4/pull/366 should address boxes 3-5.  I am not sure about box 2.  Do we want printing when calling ``--new-plugin``?  Perhaps the message with the manual link should appear for both conda/nonconda installations.  Right now the relevant documentation is in http://www.psicode.org/psi4manual/master/plugins.html.

**Comment by loriab** [comment]
PR #370 also hit various of these points, particularly moving from Makefile, Makefile.conda, Makefile.macconda into configuring at cmake-time. All in at least provisionally working order, so closing out. Thanks, @fevangelista.
