### ISSUE TITLE
threading error in DF-CCSD(T) gradient

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#2192]
Reported by a user in the Forum: http://forum.psicode.org/t/multithreaded-df-ccsd-t-gradient-test-fails/2200

Outputs with `print 3` for the `dfccsd-t-grad` test with conda's `1.4rc1+2d37164`
[1 thread](https://github.com/psi4/psi4/files/6655021/single.txt)
[2 threads](https://github.com/psi4/psi4/files/6655018/parallel.txt)

Visible differences in the `3-center <..> Density Gradient` parts.
<img width="1101" alt="Screenshot 2021-06-15 at 12 52 56" src="https://user-images.githubusercontent.com/1648640/122040872-a3d1d580-cdd8-11eb-9b57-904640b63c05.png">

**Comment by JonathonMisiewicz** [comment]
Are there problems with DF-CCSD gradients? What about 1.3?

I'm asking mainly to get a feel for if this is a problem in DFOCC or my moving the DF gradient pieces around.

**Comment by hokru** [comment]
Already the DF-MP2 gradient of DFOCC is wrong when threaded.

In 1.3.2 the parallel gradient is okay.

**Comment by JonathonMisiewicz** [comment]
So it probably is something from my refactoring, which is strange because I didn't touch any of the parallelization lines...

I'll look into this, but it might take me some time to get set up on the new cluster.

**Comment by bozkaya** [comment]
According to our tests, it is related to minsthelper.cc. Specifically the pragma statement at line 2470, we just turned it off.

//#pragma omp parallel for        
for (int aux = 0; aux &lt; np; aux++) {            
for (int p = 0; p &lt; nprim; p++) {               
 for (int q = 0; q &lt;= p; q++) {

@JonathonMisiewicz

**Comment by JonathonMisiewicz** [comment]
The issue is probably a few lines lower than that: l. 2474 and l.2475 are accessing `data`, which initializes at the first element in the vector, when it should initialize at the first entry for this thread, `data[aux * tri]`...

I'll get a fix up once I'm able to run tests on my cluster. "Turning parallelization off" is not the correct fix.

**Comment by bozkaya** [comment]
I agree we should turn on the parallelization. It will be perfect if you fix it!

**Comment by JonathonMisiewicz** [comment]
If anybody needs this immediately, the patch to get threaded gradients working is

```
--- a/psi4/src/psi4/libmints/mintshelper.cc
+++ b/psi4/src/psi4/libmints/mintshelper.cc
@@ -2469,11 +2469,12 @@ SharedMatrix MintsHelper::three_idx_grad(const std::string& aux_name, const std:
         auto idx3p = idx3_matrix->pointer();
 #pragma omp parallel for
         for (int aux = 0; aux < np; aux++) {
+            auto elt = &data[ntri * aux];
             for (int p = 0; p < nprim; p++) {
                 for (int q = 0; q <= p; q++) {
-                    idx3p[aux][p * nprim + q] = *data;
-                    idx3p[aux][q * nprim + p] = *data;
-                    data++;
+                    idx3p[aux][p * nprim + q] = *elt;
+                    idx3p[aux][q * nprim + p] = *elt;
+                    elt++;
                 }
             }
         }
```

I want to make sure that the quick tests pass with threading before submitting the PR.
