### ISSUE TITLE
Random number of GEOM_MAXITER when option specified

### ISSUE THREAD

**Issue by danieleongari** [psi4/psi4#2195]
Dear psi4 developers,
I'm using psi4 v1.4rc1.

I have troubles to set the max number of geometry iteration steps.
I'm running the following code on JupyterLab:
```
psi4.set_module_options('optking', {'g_convergence': 'gau_loose'})
psi4.set_module_options('optking', {'geom_maxiter': 200})
psi4.optimize(opt_method, 
            bsse_type=None,
            molecule=geom)
```
and before I tried also:
```
psi4.set_options('optking', {'g_convergence': 'gau_loose', 'geom_maxiter': 200})
```

It seems like psi4 is reading some random number for `geom_maxiter`: 
indeed, you can see from my output that the calculation was killed after 17 steps.
```
  **** Optimization has failed! (in 17 steps) ****
			--------------------------
			 OPTKING Finished Execution 
			--------------------------
	Removing binary optimization data file.
	Cleaning optimization helper files.

PsiException: Could not converge geometry optimization in 16 iterations.
```
[02_dimers_00_output.txt](https://github.com/psi4/psi4/files/6686237/02_dimers_00_output.txt)

It is weird however that the number of max iteration, when this threshold gets hit, is different every time, and it is not the default value of 50. Sometimes it allows for enough iterations to converge, so I don't know if in that case the program took my 200 maxiter or it ended up with a randomly high value for maxiter. 

Please, let me know if this is a bug or I'm doing something wrong.
Thanks for your help.

**Comment by hokru** [comment]
The problem is this part in the output.

```
	Back-transformation to cartesian coordinates...
	The INTCO_EXCEPTion handler:
	TORS::compute_val: unable to compute torsion value
	Dynamic level is 0.
	exc.g_really_quit() is 
```

The current C++ optking will be replaced with a python version: https://github.com/psi-rking/optking
You can try it out already (see instructions in the repo) unless you require the CBS driver.

Otherwise you have to chose a different coordinate systems https://psicode.org/psi4manual/master/autodir_options_c/module__optking.html#opt-coordinates
`CARTESIAN` is a safe, but slowly converging, choice.

**Comment by danieleongari** [comment]
Thanks for the explanation, I was confused by the final `PsiException` that reads to me like the number of max iteration was hit. I will give a try to `optking`, thanks!
