### ISSUE TITLE
X2C analytic gradients

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#2197]
Psi4 1.3.2 happily runs analytic derivatives when X2C is enabled, even though as confirmed by @fevangelista on Slack the gradient is not correct since it is missing the terms arising from X2C.

The code should throw an error for analytic derivatives when X2C is employed.

**Comment by JonathonMisiewicz** [comment]
Closed by #2200, but the moment somebody adds a `compute_gradient` call that actually works, this will re-open.
