### ISSUE TITLE
QCSchema can not read multiple basis set extrapolation

### ISSUE THREAD

**Issue by danieleongari** [psi4/psi4#2198]
Dear Psi4 developer, 
I'm using v1.4rc2.

I find very convenient to use the QCSchema for submitting my `energy` calculations, but it is not clear to me what is currently implemented for this input method.
Using `{"basis": "aug-cc-pv[tq]z", "method": "MP2"}`, results in the error
```
npsi4.driver.qcdb.exceptions.BasisSetNotFound: BasisSet::construct: 
Unable to find a basis set for atom 1 for key BASIS among:
Shell Entries: ['N']
Basis Sets: [('AUG-CC-PV[TQ]Z', 'AUG-CC-PV[TQ]Z', None)]
```
which makes me think that CompeteBasisSet (CBS) extrapolations are not yet implemented.
My goal would be to submit even more advanced extrapolation protocols like `mp2/cc-pv[tq]z + D:ccsd(t)/cc-pvdz`.
Is there a way to do this with the current implementation of the QCSchema? Or do you see it possible in a near-future release?

Thank you very much for your help!

**Comment by PeterKraus** [comment]
Hi Daniele. This combination is not supported. I think this functionality request is perhaps better aimed at the QCSchema developers (https://github.com/MolSSI/QCSchema/issues). One main issue is the ambiguity of what an extrapolation (or a composite recipe) actually means.

Running CBS jobs via QCSchema is not implemented in Psi4, and my personal opinion is that it likely won't be implemented in Psi4 itself anytime soon. What may happen is that someone will take the CBS functionality out of Psi4, adapt it to create "schema" jobs for each calculation required in a similar way we do internally in the CBS wrapper, and then combine the individual atomic results to arrive at the composite result.

**Comment by danieleongari** [comment]
Thanks for your reply.
I can see that in order to make the QCScheme general and code agnostic this implies to limit some specific functionalities of the code to keep its core ones.

**Comment by loriab** [comment]
Glad you're finding QCSchema input useful!

Peter's right that not all calculations are possible at the moment through the schema input, most notably optimizations and the "wrappers" like cbs and nbody. What the schema is targeted to express at the moment are single-points, and that's how QCEngine is using it in the various <program>Harnesses.

A major update coming to psi4 is the "distributed" driver that reworks wrapper communication to be more dict-like. The schema input to wrappers isn't well-defined yet, but it will probably inherit from the single-point schema (`AtomicInput`). I think then that what you're asking for could be arranged within schema_wrapper.py, but I'm just not sure yet.

Glad to know you're interested, and we'll keep this use case in mind.
