### ISSUE TITLE
SOSCF Convergence Issues

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#2204]
Carried forward from [forum](http://forum.psicode.org/t/fatal-error-wavefunction-unable-to-obtain-mo-coefficients/2204/12). Even with SOSCF, I'm not able to converge MgF at 3 Angstroms. Several of the iterations display non-monotonic decrease of the residual, sometimes increasing after PCG iterations. This is surprising but I don't think mathematically inpossible, if the MO Hessian isn't positive semi-definite, in which case, CG methods fail. If that was all, we should look into alternate SOSCF methods.

But even when convergence is monotonic, one sees an energy improvement on the order of 1e-4 hartrees, and negligible drop in the residual. What's going wrong here? I have a memory that the SOSCF step isn't being taken correctly (by exponentiation), so that's worth looking into. Probably a weekend project for me...

**Comment by JonathonMisiewicz** [comment]
A troubling example:
```
molecule {
0 2
Mg
F 1 2.8 
}

set reference uhf 
set soscf true
set soscf_print true
set stability_analysis follow

energy('hf/cc-pvdz')
```

Even towards the end, we're seeing non-monotonic convergence.
```
   -----------------------------------------------------
     Iter   Residual RMS      Max RMS  Remain  Time [s]
   -----------------------------------------------------
    Guess      1.771e+00    1.771e+00       1         0
        1      5.715e-01    5.715e-01       1         0
        2      4.809e-01    4.809e-01       1         0
        3      2.494e-01    2.494e-01       1         0
        4      2.512e-01    2.512e-01       1         0
   -----------------------------------------------------
```

This should be impossible for CG, preconditioned or otherwise, applied to a positive-semidefinite problem. But stability analysis swears we're PSD.
```
    DLUSolver converged.

    Wavefunction stable under totally symmetric rotations.
    Lowest totally symmetric eigenvalue: 0.018307
    Lowest UHF->UHF stability eigenvalues:
      B2 0.018307        B1 0.018307        A1 0.038290        A2 0.424251
```

I'm chalking this up to a bug somewhere in our SOSCF code. _siiiiiiiiigh_

**Comment by JonathonMisiewicz** [comment]
After further investigation, I've learned a few things.

First, I was mistaken about the PCG convergence guarantees. Each iteration guarantees that you are closer to the correct solution vector. It does _not_ guarantee that your residual RMS is smaller. For a simple model, just think of z=500x^2+y^2. (1, 0) is closer to the minimum than (0, 10), but (0, 10) gives a smaller value of `z`. In this particular case, you are indeed getting close to the right `x` value, even as your residual increases.

Second, when I throw exact MO hessian diagonalization at the problem, they aren't converging well either. The problem is that the MO hessian becomes often has small, negative eigenvalues along the optimization path, causing steps that can be large and energy increasing. While I think this points out a need for more robust convergence algorithms, the behavior I'm seeing does not need an implementation error to be explained.

As such, I'm inclined to close this issue and mark an item on the developer wishlist. #2183 is worth separate investigation. @susilehtola, any objections?

**Comment by susilehtola** [comment]
@JonathonMisiewicz sounds like the problem is that there's no level shift.

No objections here
