### ISSUE TITLE
Incorrect functional parameters for wB97X-D3

### ISSUE THREAD

**Issue by chienal** [psi4/psi4#2206]
Hello,

I'm a developer at Schrodinger working on our QM engine, Jaguar. Recently I implemented wB97X-D3 and was using PSI4 to check my results. Interestingly, I found discrepancies in our SCF energies (difference of 0.003 Ha on a methane molecule), but the dispersion corrections matched to 1e-6. 

After some investigation, I believe PSI4's wB97X-D3 functional is using the wrong parameters for the functional (the dispersion correction seems fine). 

If you look in the output file, you can see 

>  ==> DFT Potential <==
>
>  => Composite Functional: WB97X-D3ZERO <= 
>
>    wB97X-d3zero Hyb-GGA Exchange-Correlation Functional
>
>    J.-D. Chai and M. Head-Gordon, J. Chem. Phys. 128, 084106 (2008)
>
> ....
>   => Exchange-Correlation Functionals <=
>
>    1.0000   wB97X range-separated functional
>
>   => Exact (HF) Exchange <=
>
>    0.8423            HF,LR [omega = 0.3000]
>    0.1577               HF 

The HF exchange and omega printouts indicate that you are using wB97X parameters in the functional. But note that wB97X and wB97X-D3 differ in their functional parameters (for instance in wB97X-D3, omega=0.25. Other parameters differ as well. See Chai et al, dx.doi.org/10.1021/ct300715s, Table 1 for the full list)

I did some testing by substituting wB97X parameters into Jaguar's wB97X-D3 call. Indeed, Jaguar then returns matching SCF energies with PSI4's wB97X-D3. I was comparing to PSI4 version: Psi4 1.4a2.dev723, Git: Rev {master} fb499f4

If you guys have fixed this in a newer version of PSI4, then great! If not, perhaps the parameters could be updated to match the paper? Of course, if I'm mistaken please let me know as well.

Cheers,
Alan Chien

**Comment by susilehtola** [comment]
wB97X and wB97X-D3 are definitely different in libxc. The problem appears to be isolated to Psi4; it probably arises at
https://github.com/psi4/psi4/blob/35c91d5890da1b96448a989aef9c523bce1b990c/psi4/driver/procrouting/dft/dft_builder.py#L163-L167

@chienal note that libxc is distributed under the Mozilla Public License, so you could use it in Jaguar, too like many other commercial codes (ADF, entos, Molpro, ORCA, Turbomole etc)

**Comment by hokru** [comment]
This is a bug.
psi4 is not aware that `wB97X-D3` is Chai's special version. It gets treated the usual way of `wB97X` plus `D3`. The dispersion correction should have different parameters I'd assume.

Maybe updating and enabling this code section would be enough: https://github.com/psi4/psi4/blob/master/psi4/driver/procrouting/dft/hyb_functionals.py#L85

**Comment by jminuse** [comment]
Just checking, does this affect the related functional `wB97X-D3BJ`?

I note that Psi4 files for `wB97X-D3BJ` say the following:

```
   => Composite Functional: WB97X-D3BJ <= 

    wB97X-V with D3(BJ) instead of VV10 dispersion 

    A. Najib, L. Goerigk, J. Comput. Theory Chem., 14 5725, 2018)
    N. Mardirossian, M. Head-Gordon, Phys. Chem. Chem. Phys, 16, 9904, 2014
```

**Comment by chienal** [comment]
Thanks for the quick replies/bug fixes!

@susilehtola - we have indeed had our eye on integrating libxc, but it's coming down to manpower/tech debt issues right now.
