### ISSUE TITLE
Geometry optimization crashes

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#2208]
This simple run fails to converge in Psi4 1.3.2
```
molecule {
pubchem:methimazole
}

set basis pcseg-0
optimize('wb97x-d')
```
The error is
```

        Back-transformation to cartesian coordinates...
        The INTCO_EXCEPTion handler:
        TORS::compute_val: unable to compute torsion value
        Dynamic level is 0.
        exc.g_really_quit() is 0.

  **** Optimization has failed! (in 1 steps) ****
                        --------------------------
                         OPTKING Finished Execution 
                        --------------------------
        Removing binary optimization data file.
        Cleaning optimization helper files.

PsiException: Could not converge geometry optimization in 0 iterations.
```

**Comment by JonathonMisiewicz** [comment]
While it's worth asking @psi-rking to confirm, this looks like a standard issue that's going to get the standard response:
Set `opt_coordinates` to `both` or `cartesian`. The new optimizer will be smart enough so that you won't need to do any manual key setting.

**Comment by psi-rking** [comment]
This advice is fine.  Try `opt_coordinates = 'cartesian'` (which worked for me)
But I just tried with the psi4 on my macbook 1.4rc3.dev3, and the optimization ran perfectly smoothly.  Also, there is a confusingly named but powerful keyword `dynamic_level = 1`.  This will cause alternative optimization algorithm to run if the first one fails.

**Comment by psi-rking** [comment]
Just added this as a test case too for pyOptking (which had no trouble with it).

**Comment by JonathonMisiewicz** [comment]
Great. Unless Susi has something else, I'm inclined to close the issue.

**Comment by susilehtola** [comment]
Since the optimization works in the upcoming version, I'm closing the issue.
