### ISSUE TITLE
Bug in PK stability analysis

### ISSUE THREAD

**Issue by jgonthier** [psi4/psi4#222]
UHF->UHF stability analysis with PK and direct integrals does not converge to the same eigenvalue in some cases. This should never happen.

Everyone: if you notice unusually large stability eigenvalues, please notify me and report below.

Assigning myself to this issue.

**Comment by dgasmith** [comment]
This will directly effect the stability2 test case.

**Comment by dgasmith** [comment]
@jgonthier We have not noticed this in awhile in the test cases. If you have not seen this, could we consider closing this issue?

**Comment by jgonthier** [comment]
@dgasmith I have not seen it either (although I haven't been actively looking for it). I'm closing and in case this problem comes back it'll be another issue.

**Comment by dgasmith** [comment]
Thanks @jgonthier!
