### ISSUE TITLE
gemm() does not check matrix sizes

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#2226]
The `gemm()` function in libmints does not check that the matrices have the proper size.

For instance, `C.dgemm(false, false, 1.0, A, B, 0.0)` should check that 

- the row dimensions of A and C are the same
- the column dimensions of B and C are the same
- the column dimension of A is the same as the row dimension of B

**Comment by TiborGY** [comment]
As far as I can tell at a glance, PR #2729 has fixed this issue.

**Comment by susilehtola** [comment]
I think so too.
