### ISSUE TITLE
how to get the gradient of external point charges

### ISSUE THREAD

**Issue by chen850512337** [psi4/psi4#2244]
Hello, 
I am using Psi4 to perform QM/MM simulations, but I failed to find the gradient for the point charges.
So is there any way to get the gradient of point charges in QM/MM calculations? 
Thanks in advance

**Comment by JonathonMisiewicz** [comment]
We need _many_ more details.

* What version of Psi4 are you using?
* When you say "gradient for the point charges," do you mean derivative of the energy with respect to nuclear displacements i.e. geometry changes? This is needed for geometry optimizations and frequencies.
* What electronic structure method are you using? Is this some SCF?
* When you say "failed to find" do you mean that the gradient was the same with and without the point charges, or just that you can't find a section in the gradient breakdown labeled "external potentials" or "point charges".
* How are you creating the point charges? A simple input file that displays the problem would be helpful.

**Comment by andysim** [comment]
If I guessed correctly, you're trying to go beyond simple electrostatic embedding, and compute the forces on the MM atoms due to the QM region?  If that's the case, we don't currently support that directly (the QM/MM code is under active development and is quite experimental at this point).  However, something like this _should_ get you what you need:
```
molecule mol {
    O     0.0000   0.0000  -0.0657
    H    -0.7590   0.0000   0.5219
    H     0.7590   0.0000   0.5219
    no_reorient
    no_com
    symmetry c1
}

# The mm charges, and positions
mm_qxyz = [
    [ 1.3, 4.0, -5.3, 4.1],
    [ 1.3, 4.0,  5.3, 4.1],
    [-1.8,-3.2,  4.3,-3.3]
]

Chrgfield = psi4.QMMM()
with open('grid.dat', 'w') as fp:
    for qxyz in mm_qxyz:
        Chrgfield.extern.addCharge(*qxyz)
        fp.write("{} {} {}\n".format(*qxyz[1:]))

psi4.set_global_option_python('EXTERN', Chrgfield.extern)

# Compute the energy with electrostatic embedding
e, wfn = psi4.energy('hf/dz', return_wfn=True)

# Use the grid.dat file created above to define the mm positions at which we want
# to compute the electric field.; results are in grid_field.dat
oeprop(wfn, 'GRID_FIELD')

# Read in the fields that oeprop computed, and scale by each charge to get the force
fields = np.loadtxt('grid_field.dat')
mm_forces = np.zeros_like(fields)
for atom, field in enumerate(fields):
    q = mm_qxyz[atom][0]
    mm_forces[atom,:] = q * field
print(mm_forces)
```

**Comment by chen850512337** [comment]
I am so sorry to make myself unclear.
But thank you very much, the input file works very well : )
