### ISSUE TITLE
Basis set input is not sanity checked

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#2253]
I just made a fool of myself on the GAMESS-US forum by thinking there was a basis set issue in a calculation, since I couldn't reproduce the energy with Psi4.

The problem is the following: if I input a wrong format, e.g.
```
H 0
S 3 1.0
     1 3.386500000000E+01 2.549380000000E-02
     2 5.094790000000E+00 1.903730000000E-01
     3 1.158790000000E+00 8.521610000000E-01
S 1 1.0
     1 3.258400000000E-01 1.000000000000E+00
S 1 1.0
     1 1.027410000000E-01 1.000000000000E+00
P 1 1.0
     1 1.500000000000E+00 1.000000000000E+00
P 1 1.0
     1 3.750000000000E-01 1.000000000000E+00
****
```
this flies through Psi4; it does not check whether the basis set format is correct.

Obviously, here it is not since there is an additional enumeration in every entry.

**Comment by susilehtola** [comment]
After the changes in #2254, the input fails with
```

psi4.driver.qcdb.exceptions.ValidationError: Gaussian94BasisSetParser::parse: Unable to match an exponent with one contraction: line 4: 1 3.386500000000E+01 2.549380000000E-02

Printing out the relevant lines from the Psithon --> Python processed input file:
    """
        return basstrings
    qcdb.libmintsbasisset.basishorde['ANONYMOUSF8B47625'] = basisspec_psi4_yo__anonymousf8b47625
    core.set_global_option("BASIS", "anonymousf8b47625")
    core.set_global_option("STABILITY_ANALYSIS", "check")
--> energy('scf')


!----------------------------------------------------------------------------------!
!                                                                                  !
!  Gaussian94BasisSetParser::parse: Unable to match an exponent with one           !
!     contraction: line 4: 1 3.386500000000E+01 2.549380000000E-02                 !
!                                                                                  !
!----------------------------------------------------------------------------------!
```

**Comment by susilehtola** [comment]
Of course, the question is why does Psi4 not use the Basis Set Exchange to parse basis sets...

**Comment by JonathonMisiewicz** [comment]
I think "use the Basis Set Exchange to parse basis sets" was on our list of things to do when the Basis Set Exchange supported that. If the technology is here, then feel free to make a PR for it. No guarantees on 1.4 or 1.5, since we're so close.

**Comment by loriab** [comment]
Yes, we'd like to depend on BSE rather than the internal library after a round of checking consistency. This is also important for roundtripping QCSchema Wfn.
