### ISSUE TITLE
UHF Dipole Polarizability Calculation Fails

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#2265]
First reported [on forums](http://forum.psicode.org/t/polarizability-error-radical-anion/2240). The following MWE crashes:
```
molecule {
O
H 1 1.0
H 1 1.0 2 104.5
}

set reference uhf

psi4.properties("scf/cc-pVDZ", properties=["DIPOLE_POLARIZABILITIES"])
```

Errors are

```
Fatal Error: UHF::onel_Hx expect incoming vector to alternate A/B
```

and

```
!----------------------------------------------------------------------------------!
!                                                                                  !
! Fatal Error: UHF::onel_Hx expect incoming vector to alternate A/B                !
! Error occurred in file:                                                          !
!     /Users/jonathonmisiewicz/psi4/psi4/src/psi4/libscf_solver/uhf.cc on line:    !
!     744                                                                          !
! The most recent 5 function calls were:                                           !
!                                                                                  !
!----------------------------------------------------------------------------------!
```

It looks like an easy case of arguments not being passed correctly.

**Comment by maxscheurer** [comment]
I think `cpscf_linear_response` does not yet support UHF references (for example [here](https://github.com/psi4/psi4/blob/9485035a0cd5d9a39582c9d7c4406f64aa12b838/psi4/driver/procrouting/response/scf_response.py#L164)...).

Adding this feature would require some coding and testing, or instead a clean `NotImplementedError` should be thrown.

**Comment by JonathonMisiewicz** [comment]
Thanks, that sounds right to me. Since UHF already has a `CPHF_solve` method, this should not be a particularly difficult feature to add.

**Comment by maxscheurer** [comment]
That's right, I'm happy to make a PR and implement it 😄

**Comment by JonathonMisiewicz** [comment]
That would be great, thanks!
