### ISSUE TITLE
Unprocessable Molecule remanents

### ISSUE THREAD

**Issue by AJStone** [psi4/psi4#2287]
I'm trying to optimize the geometry of ethylammonium cation using psi4. I have downloaded the latest version and an optimization of a smaller molecule ran with no trouble. This one fails with the error
qcelemental.exceptions.MoleculeFormatError: Unprocessable Molecule remanents under [psi4, xyz, xyz+, psi4+]:
The complete output file is attached. I don't understand the error message. Can anyone explain it to me, please?

Anthony Stone

[ethylammonium.txt](https://github.com/psi4/psi4/files/7090210/ethylammonium.txt)

**Comment by hokru** [comment]
It means part of the coordinate input is not understood.
In this case H6 misses a decimal point in the z coordinate.

Not sure if the error could be made more explicit by highlighting the specific line(s).

**Comment by AJStone** [comment]
Thank you. The input came from an xyz file sent to me and I hadn't thought to check it for errors.
But that psi4 error message would be much more helpful if translated into intelligible English.

**Comment by JonathonMisiewicz** [comment]
It's not _really_ a Psi4 error message. Psi uses [QCElemental](https://github.com/MolSSI/QCElemental) for molecule parsing. It's QCElemental that raises the difficult error message, and it bubbles up through Psi. As such, I'm inclined to say this issue belongs on QCElemental's repo, not Psi's. @loriab is involved with both and is better equipped to judge where this belongs and whether it's even possible to identify the problematic line in general.

**Comment by loriab** [comment]
I understand now. It's supposed to print something like the below, which is helpful and intelligible. (I think -- can change the wording if there's a suggestion.) This error message _is_ raised, but because the parser tries all formats (e.g., xyz, psi4) in turn, when it fails them all, it raises an error message with the whole molecule string, which is less helpful, and that last error message is what psi4 repeats to you.
```
Traceback (most recent call last):
  File "/psi/gits/QCElemental/i2287.py", line 22, in <module>
    ans = qcel.molparse.from_string(xyz, dtype="psi4")
  File "/psi/gits/QCElemental/qcelemental/molparse/from_string.py", line 228, in from_string
    molstr, molinit = parse_as_psi4_ish(molstr, unsettled=False)
  File "/psi/gits/QCElemental/qcelemental/molparse/from_string.py", line 217, in parse_as_psi4_ish
    raise MoleculeFormatError("""Unprocessable Molecule remanents under {}:\n{}""".format(dtype, molstr))
qcelemental.exceptions.MoleculeFormatError: Unprocessable Molecule remnants under psi4:
H6             1.51000000          0.78000000          0 44000000
```

I've handled this better now to raise the shortest error message among the formats with https://github.com/MolSSI/QCElemental/pull/274, and the psi message looks like:
```
Traceback (most recent call last):
  File "/psi/gits/hrw-l2/objdir39b/stage/bin/psi4", line 333, in <module>
    exec(content)
  File "<string>", line 35, in <module>
  File "/psi/gits/hrw-l2/objdir39b/stage/lib/psi4/driver/molutil.py", line 258, in geometry
    molrec = qcel.molparse.from_string(
  File "/psi/gits/QCElemental/qcelemental/molparse/from_string.py", line 262, in from_string
    raise(e)
  File "/psi/gits/QCElemental/qcelemental/molparse/from_string.py", line 256, in from_string
    molstr, molinit = parse_as_psi4_ish(molstr, unsettled=True)
  File "/psi/gits/QCElemental/qcelemental/molparse/from_string.py", line 217, in parse_as_psi4_ish
    raise MoleculeFormatError(f"""Unprocessable Molecule remnants under {dtype}:\n{molstr}""")

qcelemental.exceptions.MoleculeFormatError: Unprocessable Molecule remnants under [psi4, xyz, xyz+, psi4+]:
H6             1.51000000          0.78000000          0 44000000

Printing out the relevant lines from the Psithon --> Python processed input file:
       H6             1.51000000          0.78000000          0 44000000
       H7             2.97000000          1.82000000          0.70000000
       H8             1.58000000          2.16000000         -0.43000000
    """
    import psi4
--> psi4.geometry(xyz)


!-------------------------------------------------------------------!
!                                                                   !
!  Unprocessable Molecule remnants under [psi4, xyz, xyz+, psi4+]:  !
! H6             1.51000000          0.78000000          0 44000000 !
!                                                                   !
!-------------------------------------------------------------------!
```

**Comment by AJStone** [comment]
Yes, that would have been much more helpful. Thanks for improving it.

**Comment by JonathonMisiewicz** [comment]
The code has been merged in, QCElemental-side. It won't be included until we have Psi use a version of QCElemental including that code, but we don't need any reminders to update Psi's QCElemental when they mint a new release, and there is nothing else we can do.

Do you have any objections to closing the issue now?

**Comment by AJStone** [comment]
No, that's fine. Closing it now.
