### ISSUE TITLE
error when trying to import psi4

### ISSUE THREAD

**Issue by sisselj** [psi4/psi4#2294]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.9/site-packages/psi4/__init__.py in <module>
     54 try:
---> 55     from . import core
     56 except ImportError as err:

ImportError: /srv/conda/envs/notebook/lib/python3.9/site-packages/psi4/core.cpython-39-x86_64-linux-gnu.so: undefined symbol: __svml_exp4_mask_e9

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
/tmp/ipykernel_63/776720746.py in <module>
----> 1 import psi4

/srv/conda/envs/notebook/lib/python3.9/site-packages/psi4/__init__.py in <module>
     58         raise ImportError("{0}\nLikely cause: GCC >= 4.9 not in [DY]LD_LIBRARY_PATH".format(err))
     59     else:
---> 60         raise ImportError("{0}".format(err))
     61 
     62 from psi4.core import set_output_file, get_num_threads, set_num_threads

ImportError: /srv/conda/envs/notebook/lib/python3.9/site-packages/psi4/core.cpython-39-x86_64-linux-gnu.so: undefined symbol: __svml_exp4_mask_e9

Python version = 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:39:48) 
[GCC 9.3.0]

Any ideas?

regards
Sissel

**Comment by JonathonMisiewicz** [comment]
A traceback is never adequate information for a bug report.

We need a Psi4 version number, exact steps to reproduce the error, and need to know what operating system you're using.

**Comment by sisselj** [comment]
Hi

We run jupyter in a container.

writing: import psi4
in a cell and then run it gives the error message (repeated at the 
bottom of mail)

operating system:
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"

psi4 version:  1.4+9485035

and

Python version = 3.9.6 | packaged by conda-forge | (default, Jul 11 
2021, 03:39:48)
[GCC 9.3.0]
IPython version = 7.26.0

best regards
Sissel

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call 
last)
/srv/conda/envs/notebook/lib/python3.9/site-packages/psi4/__init__.py in 
<module>
      54 try:
---> 55     from . import core
      56 except ImportError as err:

ImportError: 
/srv/conda/envs/notebook/lib/python3.9/site-packages/psi4/core.cpython-39-x86_64-linux-gnu.so: 
undefined symbol: __svml_exp4_mask_e9

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call 
last)
/tmp/ipykernel_64/253247311.py in <module>
----> 1 import psi4

/srv/conda/envs/notebook/lib/python3.9/site-packages/psi4/__init__.py in 
<module>
      58         raise ImportError("{0}\nLikely cause: GCC >= 4.9 not in 
[DY]LD_LIBRARY_PATH".format(err))
      59     else:
---> 60         raise ImportError("{0}".format(err))
      61
      62 from psi4.core import set_output_file, get_num_threads, 
set_num_threads

ImportError: 
/srv/conda/envs/notebook/lib/python3.9/site-packages/psi4/core.cpython-39-x86_64-linux-gnu.so: 
undefined symbol: __svml_exp4_mask_e9

**Comment by JonathonMisiewicz** [comment]
I can reproduce this on my Mac, but the problem there is obviously that my Jupyter notebook isn't using the conda environment which has Psi's dependencies. I recommend you look into the interaction between Jupyter and conda environments. I doubt this is a bug in Psi4.

I won't be able to delve further into this for a few more days.

**Comment by PeterKraus** [comment]
As Jonathon said, at least a list of packages in the conda env would be great to have to push this along any further.

**Comment by sisselj** [comment]
Hi

Thank you - I will forward Jonathon's answer to our IT-department and 
ask them to look into this.

I enclose what conda list gave me.

I will appreciate any help you can give us here.

best regards
Sissel

**Comment by bieniekmateusz** [comment]
For anyone else running into this. Having some packages from `-c conda-forge` and some from the main channel can lead to this issue. I had -c conda-forge set as a preferred channel and had to turn it off to resolve this issue. Create a new environment in conda and install psi4 separately to avoid relying on other packages from -c conda-forge.
