### ISSUE TITLE
Can't Pass `ref_wfn` to MRCC

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#2305]
The following input file fails:
```
set {
reference rhf 
basis cc-pVDZ
scf_type pk
freeze_core true
}

_, wfn = energy('mp2',return_wfn = True)
energy('mrccsd', ref_wfn=wfn)
```

The problem is that `run_mrcc` expects [the "CURRENT SCF ENERGY"](https://github.com/psi4/psi4/blob/2d33c3f83bee2d2b87b7a9ee4eb0c5d230b65403/psi4/driver/procrouting/proc.py#L4572) variable to be set in core, which was wiped [as soon as the energy call ran](https://github.com/psi4/psi4/blob/2d33c3f83bee2d2b87b7a9ee4eb0c5d230b65403/psi4/driver/driver.py#L546).

@loriab, is there any reason _not_ to grab this variable from the incoming wavefunction?

**Comment by loriab** [comment]
> is there any reason not to grab this variable from the incoming wavefunction?

I think that's a safe solution nowadays.
