### ISSUE TITLE
Allow computation of GRID_ESP via qcschema

### ISSUE THREAD

**Issue by lilyminium** [psi4/psi4#2307]
Hi Psi4 developers,

The QCSchema method of input to Psi4 is super convenient and plays well with standard I/O packagers like QCEngine, but it only allows the computation of a limited number of properties:

https://github.com/psi4/psi4/blob/9163cbd08865d26129cfbaf5c302fc14f870f30f/psi4/driver/schema_wrapper.py#L69-L71

It would be really convenient to compute other oeprops as well, especially GRID_ESP, using the schema framework. Would it be possible / desirable to have this in Psi4? 

**Example use**

```python
model = qcelemental.models.AtomicInput(
    molecule=mol,
    driver="properties",
    model={"method": "SCF", "basis": "sto-3g", properties=["GRID_ESP", "GRID_FIELD"]},
    keywords={"scf_type": "df",
              "grid": my_mol_grid}
)

result = qcengine.compute(model, "psi4")

assert result.properties.grid_esp is not None
```

**Comment by loriab** [comment]
It's `grid_field.dat` and `grid_esp.dat` files that you're after?

Apart from that `can_do_properties` list you linked, a barrier has been that there isn't a place to stash gridded properties in QCSchema. Most of the other properties are stored in scalar or array qcvariables. Alfter MolSSI/QCElemental#275 is in place, we'll be able to return those, though it still won't be proper QCSchema.

**Comment by lilyminium** [comment]
> It's grid_field.dat and grid_esp.dat files that you're after?

Yes, pretty much. 

> Apart from that can_do_properties list you linked, a barrier has been that there isn't a place to stash gridded properties in QCSchema. Most of the other properties are stored in scalar or array qcvariables. Alfter MolSSI/QCElemental#275 is in place, we'll be able to return those, though it still won't be proper QCSchema.

Thanks for the explanation, I'm not very familiar with either Psi4 or the MolSSI QC stack. That PR is to return the actual files, right? As a user I would immediately read them into arrays; would those arrays be able to be stored as qcvariables?

**Comment by loriab** [comment]
you'd submit to psi4 with `input.protocols.native_files = "all"` and then access the file _contents_ as `result.native_files["grid_field.dat"]`, and that can be readily read into arrays. we don't have any grid-dependent qcvariables at present. adding those would probably need a pass that included MO cube files.

**Comment by loriab** [comment]
There's a stopgap fix for this here https://github.com/MolSSI/QCEngine/issues/434

**Comment by lilyminium** [comment]
Oh fantastic -- thanks @loriab!
