### ISSUE TITLE
CC Property Segfault

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#2310]
The following input segfaults:

```
memory 16GB
molecule{
0 2
C   -1.309749745   1.180176173  -0.025170341
O   -0.725300438   2.155147669   0.452713346
C   -2.816719340   1.155998649  -0.110605975
H   -3.220628949   1.262541455   0.893082386
H   -3.209427538   0.248634016  -0.561900090
H   -3.143158132   2.016595633  -0.688893115

units angstrom
symmetry c1
}

set{
basis def2-svp
reference uhf
DFCC False
Freeze_core True
CACHELEVEL 0
scf_type direct
print 2
}
set_num_threads(32)

properties('ccsd',properties=['polarizability'])
```

I've been able to reproduce this on a serial run. My initial `lldb` run isn't giving reliable information, because it's confusing the various `MOInfo` objects defined in different `cc` modules.

**Comment by lothian** [comment]
So, obviously I'm super-late to this, but we don't have linear response coded for UHF references.  Perhaps this is just a case of the driver not trapping the unsupported workflow?

**Comment by JonathonMisiewicz** [comment]
The driver has failed to trap unsupported workflows for linear response properties before, so you're probably right. I can write up a PR to trap unsupported `cc_property` workflows...

I get a PSIO error when I try an ROHF linear response property. Is that another case of the driver failing to trap an unsupported workflow?

```
PSIO_ERROR: Can't find TOC Entry WAbEi (Ei,Ab)
PSIO_ERROR: unit = 112, errval = 13
```

**Comment by lothian** [comment]
Yep.  The response code is (for now) RHF-reference only.
