### ISSUE TITLE
enable looser symmetry in Molecule

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#232]
All the symmetry detection in the Molecule class is through `tol` arguments for individual methods. For the Molecule as a whole, this is controlled by `DEFAULT_SYM_TOL`, which is compiled in. This means one can't just dial down the symmetry tolerance for an entire optimization.

For this ticket, make the `tol` parameter not a preprocessor option but a bit of member data. Make a set function for this. Export it to python.

**Comment by dgasmith** [comment]
@loriab Are you ok with removing the ability to change this on a per-function-call basis?

**Comment by loriab** [comment]
What would you set? If not `tol` argument, isn't it the preprocessed `DEFAULT_SYM_TOL` that's set at compile time? Of per-compile, per-psi4-instantiation, and per-symmetrize-call, I'm ok with either of the latter two.

**Comment by dgasmith** [comment]
`DEFAULT_SYM_TOL` would simply become an attribute of the Molecule class that would have a getter/setter. The downside to this is it would be difficult to have calls like `symmetrize(double tol)`. It would simply always take the internal attribute.

**Comment by loriab** [comment]
Ah, yes if `DEFAULT_SYM_TOL` was just an attribute of Molecule, that'd work just fine. That was the scheme I originally talked over with Jet, and in that case the argument to `symmetrize()` could certainly be dropped. 

It was later that I noticed the separate tolerance parameter to `symmetrize()` and thought that might be a way around WebMO's problem (point group changing in the course of geom opt) _without_ major construction work on the Molecule class. Brandon was looking into this at one point. Really should reproduce the WebMO problem first.

**Comment by loriab** [comment]
This could still be done, if wanted, but the immediate reason for it psi4/psi4webmo#4 is solved w/o changes needed here.
