### ISSUE TITLE
The calculation results of different versions (v1.3.2 vs v1.4 vs v1.4.1) of Psi4 vary greatly

### ISSUE THREAD

**Issue by blazerygy** [psi4/psi4#2351]
I used Psi4 to calculate the energy of molecules in Conformer Benchmark dataset ( https://github.com/ghutchis/conformer-benchmark/ 702 molecules, each molecule has about 10 conformations).

I tried three versions of Psi4 respectively, including V1.3.2, V1.4 and V1.4.1, and then calculated the correlation between the results of the three versions. The results are shown in the following table. The consistency is not high, especially v1.4.1, which is greatly different from the other two versions. Why are the calculation results of different versions so different?

In addition, I also calculated the correlation between Psi4 results and Orca results (from Conformer benchmark), the correlation is not high, why?

![image](https://user-images.githubusercontent.com/16797849/141259545-c20d1c6c-6fe1-44ec-a0de-1bb8980db327.png)

my code:
```Python
def run_psi4_calc(xyz_str, dtype='xyz', basis_set='WB97X-D/def2-SVP', reference='uks', max_iter=100):

    psi4.set_options({
      'reference': reference,
      'maxiter': max_iter
    })

    mol = psi4.core.Molecule.from_string(xyz_str, dtype=dtype)
    energy = psi4.energy(basis_set, molecule=mol)

    return energy



# get molecular 3d coordinates from Conformer benchmark
xyz_str = get_xyz_str()

energy = run_psi4_calc(
    xyz_str=xyz_str,
    dtype='xyz+',
    basis_set='WB97X-D/def2-SVP',
    reference='uks',
    max_iter=100
)
```

**Comment by JonathonMisiewicz** [comment]
Looking at your GitHub account, I suspect that you have a background in machine learning rather than quantum chemistry, so I'll try to keep this simple.

DFT methods (like WB97X-D) rely on an expensive numerical integration procedure, and different codes use different integration grids with different schemes to remove points to reduce computational time. Chemists are usually interested in _differences_ of energies and will prune points if doing so means energy _differences_ are unchanged, even if final energies are not. Fair comparisons of DFT energies across different programs, like Psi4 and ORCA, are thus very difficult and can only be reliably accomplished by an expert.

Your data for 1.3.2 vs 1.4 does not convince me that anything is wrong. Maybe you're just observing noise because you haven't converged the equations fully tightly. Report the largest differences between the 1.3.1 energy and the 1.4 energies. Since you have the full dataset, that should be a simple Python script to write. If we're seeing differences much above the convergence thresholds, then we should look deeper into this.

There was a [bugfix](https://github.com/psi4/psi4/pull/2283) between 1.4 and 1.4.1 that specifically affected computations with density-fitted integrals (which you use by default), an omega functional, and a linearly dependent basis set like you would see in large systems. @andysim would know more, but the 1.4.1 numbers should be more reliable than the 1.3.2 or 1.4.1 numbers.

**Comment by blazerygy** [comment]
> "Maybe you're just observing noise because you haven't converged the equations fully tightly."

How can I converge the equations fully tightly? Which parameter do I need to modify?

 
> "There was a bugfix between 1.4 and 1.4.1 that specifically affected computations with density-fitted integrals (which you use by default), an omega functional, and a linearly dependent auxiliary basis set like you would see in large systems."

From the calculation results, the results of v1.4 seems to be more reasonable, because it has a higher correlation with other results. For v1.4.1, did I use it wrong? how to modify the code?

@JonathonMisiewicz 

thx

**Comment by PeterKraus** [comment]
I mean, a correlation coefficient of 0.62 is ridiculous. The calculations really should be nearly identical. Are you sure the molecular charges and multiplicities are set correctly?

**Comment by JonathonMisiewicz** [comment]
> > "Maybe you're just observing noise because you haven't converged the equations fully tightly."
> 
> How can I converge the equations fully tightly? Which parameter do I need to modify?

Set `d_convergence`. The default is 1e-6. You could set it to smaller numbers and see if the correlation improves. If you set it too low, the equations may not converge. You will see this problem if you try to set it below 1e-12, but you will probably see it at a larger number. 

> > "There was a bugfix between 1.4 and 1.4.1 that specifically affected computations with density-fitted integrals (which you use by default), an omega functional, and a linearly dependent auxiliary basis set like you would see in large systems."
> 
> From the calculation results, the results of v1.4 seems to be more reasonable, because it has a higher correlation with other results. For v1.4.1, did I use it wrong? how to modify the code?
> 

I feel like you are not listening to me. I don't trust your ORCA and Psi4 comparisons, and it's perfectly reasonable for 1.3.2 and 1.4 to agree with each other but not 1.4.1, if both 1.3.2 and 1.4 had a bug. I do not trust that the results of 1.4 are more reasonable. Like I said before. Find the system where the energy changes the most between 1.4 and 1.4.1, tell us what the energies are, and tell us the system.

**Comment by ajs99778** [comment]
I've only skimmed paper associated with the benchmarking data, but it looks like they used wB97X-D3/def2-TZVP, not wB97X-D/def2-SVP. They only refer to wB97X-D once, and use wB97X-D3 everywhere else. In section 4.2, they say that only B3LYP-D3BJ and PBE-D3BJ were selected to be tested with def2-SVP.

Are you able to reproduce the benchmark energy for any conformer using wB97X-D/def2-SVP or wB97X-D3/def2-TZVP in ORCA 4.0.1? I believe the ORCA input would have
```
! wB97X def2-SVP D2
```
or 
```
! wB97X-D3 def2-TZVP
```

In addition to using the newer version of Psi4 that fixes the bug Jonathon mentioned, ensure that you are comparing like-for-like by spot checking a few of the energies in the benchmark data set using the same software and settings. Using a different dispersion correction and basis set would explain the poor agreement between Psi4 1.4.1 and ORCA 4.0.1.

Also, ORCA 4.0.1 is several years old. I don't know if ORCA had any bug fixes/changes over the years that would impact their results, but you might want to compare to ORCA 5.0.1 energies as well.

**Comment by blazerygy** [comment]
I uploaded my code, psi4 running log and result analysis to google drive: https://drive.google.com/file/d/1yifEuHhVXDsQh30toR0C69HzhE8rYqpn/view?usp=sharing

> "I mean, a correlation coefficient of 0.62 is ridiculous. The calculations really should be nearly identical. Are you sure the molecular charges and multiplicities are set correctly?"

Conformer benchmark provides the charge of each molecule, multiplicity is set to 1 by default. (Psi4-Test/main.py line 63) 
@PeterKraus 

> "Set d_convergence. The default is 1e-6. You could set it to smaller numbers and see if the correlation improves. If you set it too low, the equations may not converge. You will see this problem if you try to set it below 1e-12, but you will probably see it at a larger number."

I tried to set d_convergence to 1e-7, but the calculation results are the same as the results of d_convergence=1e-6. The file I uploaded contains the running logs of both. (Psi4-Test/psi4_energy.csv, Psi4-Test/psi4_energy_tight.csv, Psi4-Test/conformer_benchmark/psi4_log)
@JonathonMisiewicz 

> "I've only skimmed paper associated with the benchmarking data, but it looks like they used wB97X-D3/def2-TZVP, not wB97X-D/def2-SVP. They only refer to wB97X-D once, and use wB97X-D3 everywhere else. In section 4.2, they say that only B3LYP-D3BJ and PBE-D3BJ were selected to be tested with def2-SVP."

The file I uploaded contains the calculation results of wB97X-D3/def2-TZVP and wB97X-D/def2-SVP.  (Psi4-Test/psi4_energy.csv, Psi4-Test/psi4_energy_tight.csv, Psi4-Test/conformer_benchmark/psi4_log)
@ajs99778 

> "Are you able to reproduce the benchmark energy for any conformer using wB97X-D/def2-SVP or wB97X-D3/def2-TZVP in ORCA 4.0.1? " "Also, ORCA 4.0.1 is several years old. I don't know if ORCA had any bug fixes/changes over the years that would impact their results, but you might want to compare to ORCA 5.0.1 energies as well."

Unfortunately, I don’t have ORCA license, so I can’t use ORCA.
@ajs99778

**Comment by hokru** [comment]
Please add `'wcombine: false` to the psi4 options, while we investigate. 

ORCA is free of academic use.

**Comment by ajs99778** [comment]
I don't see any wB97X-D3/def2-TZVP energies from Psi4 1.4.1 in your data, just wB97X-D/def2-SVP. 

Looking at the data you have from Psi4 1.4.1, the wB97X-D/def2-SVP energies relative to the minimum energy conformer for each molecule are similar to the relative energies from ORCA. Though some conformers have significant differences for the relative energy from ORCA vs from Psi4, most differences are around 1 kcal/mol or less. I would expect similar deviations between wB97X-D/def2-SVP and wB97X-D/def2-TZVP results that were both computed using the same software. The energy is sensitive to the quality of the basis set. Using a different dispersion correction than the 'reference' ORCA energies doesn't help either. The differences compound with different implementations of various algorithms between different software packages. For molecules with conformers that are all close in energy, these deviations will bring the r<sup>2</sup> way down.

**Comment by hokru** [comment]
The following example taking from @blazerygy data set indicates the `wcombine` algorithm is responsible, hence the recommendation to disable it.
Plans are to disable the options in the next release. This option affects the efficiency of the range-separated DFT calculations to a moderate degree.

```
molecule mol {
    S           -1.843692634757     0.011818668014    -1.930850360417  
     N           -0.090392634757     0.011818668014    -1.930850360417 
     C            0.380407365243     0.011818668014    -0.711250360417 
     N           -0.598892634757     0.005218668014     0.343749639583 
     C           -1.918692634757     0.001718668014    -0.128850360417 
     N           -2.920292634757    -0.021381331986     0.692349639583 
     C           -4.267092634757    -0.022581331986     0.274749639583 
     O           -4.572492634757    -0.014581331986    -0.897450360417 
     C           -5.238992634757    -0.031881331986     1.408749639583 
     C           -0.276592634757     0.147418668014     1.729149639583 
     C            0.475607365243     1.248918668014     2.154149639583 
     C            0.801207365243     1.363418668014     3.501949639583 
     C            0.368607365243     0.401118668014     4.413949639583 
     C           -0.397892634757    -0.680381331986     3.982449639583 
     C           -0.725892634757    -0.816981331986     2.636249639583 
     N            1.714507365243     0.032718668014    -0.333650360417 
     C            2.783407365243    -0.139581331986    -1.254650360417 
     C            2.720707365243     0.307318668014    -2.578350360417 
     C            3.838007365243     0.163518668014    -3.395850360417 
     C            5.008507365243    -0.412181331986    -2.905450360417 
     C            5.065807365243    -0.847981331986    -1.582450360417 
     C            3.960507365243    -0.717181331986    -0.749250360417 
     H           -5.042492634757    -0.867781331986     2.098449639583 
     H           -6.272792634757    -0.114281331986     1.044849639583 
     H           -5.154492634757     0.890718668014     2.005349639583 
     H            0.788407365243     2.013318668014     1.442549639583 
     H            1.389307365243     2.214918668014     3.843749639583 
     H            0.623207365243     0.499418668014     5.467849639583 
     H           -0.748492634757    -1.422181331986     4.699449639583 
     H           -1.343692634757    -1.647681331986     2.292449639583 
     H            1.920307365243    -0.204681331986     0.639249639583 
     H            1.809107365243     0.759418668014    -2.978250360417 
     H            3.792107365243     0.505518668014    -4.429450360417 
     H            5.874807365243    -0.522581331986    -3.552550360417 
     H            5.980307365243    -1.297781331986    -1.198150360417 
     H            4.013407365243    -1.064281331986     0.279049639583 
}
#memory 8 GiB
#set wcombine false
#set scf_type mem_df

energy('WB97X-D/def2-SVP')
# disk_df disk  -1309.4741157753082916
# mem_df in-core -1309.4749504976896333
# mem_df in-core wcombine=false -1309.4741157748148908
```

**Comment by blazerygy** [comment]
> "Please add 'wcombine': false to the psi4 options, while we investigate."

After I add 'wcombine: False' to the Psi4 options (v1.4 and v1.4.1), the calculation results of different versions are almost the same, and the calculation results of Psi4 and ORCA are almost the same. I think the problem has been solved, thank you everyone. 😄 👍 

![image](https://user-images.githubusercontent.com/16797849/143011201-b1dacd8e-8229-43ef-8400-e20dc9199f54.png)
