### ISSUE TITLE
switch to upstream dftd3 and gcp

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#2360]
dftd3's have proliferated (https://github.com/awvwgk/simple-dftd3/issues/4). @awvwgk thinks everything we use dftd3 classic for has been incorporated into `simple-dftd3`. It should be a medium-term goal to help kill our fork.

may as well tackle the gcp exe to gcp-correction aka mctc-gcp shift at the same time since needed for SCAN. this already has a harness in QCEngine, whereas simple-dftd3 does not.

closed by #2791

**Comment by awvwgk** [comment]
Awesome, thanks!
