### ISSUE TITLE
psivar management

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#239]
Implement scheme whereby c-side modules can define minimum ('METHOD CORRELATION ENERGY') or full sets (corl, ref, & total) of psivars, then manager comes through and 
- fills in any blanks
- checks that definitions met and consistent (tot – corl = ref)
- ensures that overlapping modules are using consistent names

The quantum chemical facts I've already got in programmatic form in pandas in qcdb, so it's mostly the psi4 interfacing and reconciliation to do. This is already done, small scale, for SAPT. Also, would be nice to autodoc the equations.

**Comment by dgasmith** [comment]
This will be handled by QCDB, closing this out.
