### ISSUE TITLE
`diis_min_vecs` Useless

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#2401]
The `diis_min_vecs` option currently has no effect in Psi4. We [check that is at least 1](https://github.com/psi4/psi4/blob/master/psi4/driver/procrouting/scf_proc/scf_iterator.py#L402), but we [already raise an error if it isn't](https://github.com/psi4/psi4/blob/master/psi4/driver/procrouting/scf_proc/scf_iterator.py#L849). I've checked, and it was this way before I started tinkering with DIIS.

This keyword accomplishes absolutely nothing besides giving the user a chance to raise errors. Do we want to _remove the keyword_, _add the intended feature_, or _deprecate and then remove the keyword_?

**Comment by susilehtola** [comment]
What is the option even meant to do? Only do DIIS if you have `N` vectors? This sounds like an idiotic strategy IMNSHO, since doing a bare Roothaan update will be way worse...

I guess the only reasonable option is to mark it as deprecated for the next release and remove it in the  subsequent one.

**Comment by loriab** [comment]
It does seem to be set to non-default in various tests https://github.com/psi4/psi4/search?p=1&q=diis_min_vecs . But if it's not providing an actual useful knob, I'm good with deprecate and remove.

**Comment by JonathonMisiewicz** [comment]
It sounds like we're taking the path of deprecation, then.

> It does seem to be set to non-default in various tests https://github.com/psi4/psi4/search?p=1&q=diis_min_vecs . But if it's not providing an actual useful knob, I'm good with deprecate and remove.

Half of those are setting an option in the DCT module, not the SCF module.

As for the others, the samples were last generated pre-1.1. Something else killed the knob, perhaps the Py-side inversion.

**Comment by loriab** [comment]
> As for the others, the samples were last generated pre-1.1. Something else killed the knob, perhaps the Py-side inversion.

To clarify, `samples/` are generated for each release and after #2364 will be generated for each PR. It's the `output.ref` set that are largely circa pre-1.1.

**Comment by susilehtola** [comment]
The only question I have is about the use of DIIS in e.g. coupled-cluster. There, one typically does bare updates combined with some DIIS iterations in-between. Is this completely unrelated to `DIIS_MIN_VECS`?

**Comment by JonathonMisiewicz** [comment]
> The only question I have is about the use of DIIS in e.g. coupled-cluster. There, one typically does bare updates combined with some DIIS iterations in-between. Is this completely unrelated to `DIIS_MIN_VECS`?

No. Correlation methods that use DIIS have their own `DIIS_MIN_VECS` keyword and use that to decide when to call the DIIS extrapolater. This is why I only deprecated the SCF version of the keyword.
