### ISSUE TITLE
Incompatibility with boost 1.60

### ISSUE THREAD

**Issue by bennybp** [psi4/psi4#243]
There seems to be a regression in Boost 1.60 that causes problems with Psi4 (and other projects).
It has been created as an issue in the boost python repo: https://github.com/boostorg/python/issues/56

Maybe the version could be checked in the CMake configure step. It can then either abort (if the user was trying to force the use of system boost) or use the boost distributed with Psi4.

Adding this since #230 was closed (and it was unrelated anyway)

**Comment by kannon92** [comment]
I am having some trouble with boost, but I don't think this is the same thing.    How can I tell PSI4 to ignore any precompiled boost and use the one distributed by PSI4?

**Comment by jturney** [comment]
Pass ```-DBUILD_CUSTOM_BOOST=TRUE``` to the setup script.

**Comment by dgasmith** [comment]
May be [fixed](https://github.com/Homebrew/homebrew-core/pull/516). @bennybp Do you have an easy setup to test this out?

**Comment by bennybp** [comment]
No, I don't have a mac. I had been waiting for the official 1.61 to come out to actually test it.

**Comment by amjames** [comment]
I was able to build and link against the latest homebrew boost 1.60.0, running the tests now.

**Comment by amjames** [comment]
Sorry I just realized I never followed up on this.

On my mac all of the regular tests pass except 86 dcft-grad1 and 93 dcft4 both timed out.

**Comment by dgasmith** [comment]
Confirmed as @amjames said, 1.60 and 1.61 now works.
