### ISSUE TITLE
Can't Get CC Relaxed Density

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#2432]
For testing purposes, I want a CCSD OPDM including orbital relaxation contributions.

This script works:
```
molecule {    
O
H 1 1.0 
H 1 1.0 2 101.5
}

wfn = gradient('ccsd/cc-pvdz', return_wfn=True)[1]

oeprop(wfn, 'DIPOLE')
```

...and I can confirm it's correct by doing a finite difference test.

My problem is that _I have absolutely no idea how to do this without going through gradient_. If I naively go through properties, the OPDM relaxation terms get dropped because they are expensive. But if I explicitly order OPDM relaxation terms...

```
molecule {    
O
H 1 1.0 
H 1 1.0 2 101.5
}

set opdm_relax true

properties('ccsd/cc-pvdz')
```

The `cc` module rebels and informs me that it is `Turning orbital relaxation off since only onepdm is requested.` (TPDM is needed to construct the CC orbital gradient needed for the Z-vector equation.)

Who told `cc` to only compute the OPDM? [This line of driver code, which the user cannot override.](https://github.com/psi4/psi4/blob/master/psi4/driver/procrouting/proc.py#L3124) Although [docs report](https://github.com/psi4/psi4/blob/master/psi4/src/read_options.cc#L1812) that this flag controls whether the onepdm is computed, internal `ccdensity` [says](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/cc/ccdensity/Params.h#L49) the flag controls whether the 1PDM _alone_ is computed, implicitly denying the 2PDM from ever being computed.

Pinging @loriab for all things keyword standardization and @lothian in case you had a reason for [coding this](https://github.com/psi4/psi4archive/commit/575ec501ee7638cf4ff0c373f78e03ae6aac00c4).

In my view:
- Keyword `onepdm` should be renamed to something like `onepdm_only`.
- `onepdm_only` default changes to `true`.
- Requesting either `relax_opdm` or a method that inherently requires 2-electron densities (gradients for sure) trumps `onepdm_only`.
- In all other cases, the driver is no longer responsible for setting `onepdm_only`.
- Default for `relax_opdm` remains false, and therefore, 2PDM will not be computed unless necessary.

If we're agreed, I'm happy to make these changes. I'm more afraid of the current state of densities in Psi than I am of legacy code. We would need to discuss how we want to handle deprecation, and which CC properties need the 2PDM.

**Comment by loriab** [comment]
The detci analogs have some "if not otherwise reqd" language that seems useful. conveniently have different names, too.

https://github.com/psi4/psi4/blob/master/psi4/src/read_options.cc#L570-L575

**Comment by lothian** [comment]
The changes are fine with me.

My reason was only to save computing time when one only wants dipole moments.  Most users don't care about the difference between relaxed and unrelaxed properties, and I figured, if you're going to go to all the trouble of getting the twopdm, then you might as well just compute the entire gradient.

**Comment by JonathonMisiewicz** [comment]
Thanks both for the quick responses and feedback.

@loriab, any objections to me going ahead and making the discussed changes now? (Changing `onepdm` to `opdm` wherever it appears in `cc` also sounds good to me.) The question is whether to bother deprecating the old keywords, since we're including some behavior changes as well. These keywords are so obscure that I don't think deprecation is worth the effort.
