### ISSUE TITLE
inconsistent cd-mp2 energy

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#244]
I'm finding non-deterministic energies for cd-mp2, depending on amount of extraneous stuff commented in the input file. For example, the below works as is, but gives a different answer when the unused molecules are commented out (not only molecules, but irrelevant keywords can cause the problem, too). The problem shows up in the final output as correlation energy has wrong sign and not matching sum of aa, ab, bb contributions. At first I though it was because you're setting `EcorlL` but printing `Ecorl`, @bozkaya , but that turns out to be innocent. I've got a valgrind if that'll help.

```
molecule methane {
     C     0.0000000    0.0000000    3.0826195
     H     0.5868776    0.8381742    3.4463772
     H    -1.0193189    0.0891638    3.4463772
     H     0.0000000    0.0000000    1.9966697
     H     0.4324413   -0.9273380    3.4463772
}

molecule hf {
H
F 1 0.917
}

molecule bh_h2p {
1 2
B     0.10369114     0.00000000     0.00000000
H    -1.13269886     0.00000000     0.00000000
H     3.00000000     0.37149000     0.00000000
H     3.00000000    -0.37149000     0.00000000
}

set basis cc-pvdz
set scf_type df
set guess sad
set freeze_core true
set e_convergence 8
set d_convergence 7


set reference uhf
set mp2_type cd
energy('mp2')
print_variables()

compare_values(-0.058409837177, get_variable('mp2 correlation energy'), 6, 'mp2 uhf cd: 1 occ*')  #TEST

```

```
	Computing CD-MP2 energy using SCF MOs (Canonical CD-MP2)... 
	======================================================================= 
	Nuclear Repulsion Energy (a.u.)    :     4.91953818754669
	CD-HF Energy (a.u.)                :   -25.94513055914741
	REF Energy (a.u.)                  :   -25.94513055914741
	Alpha-Alpha Contribution (a.u.)    :    -0.00171224403804
	Alpha-Beta Contribution (a.u.)     :    -0.05664223456972
	Beta-Beta Contribution (a.u.)      :    -0.00005535856885
	Scaled_SS Correlation Energy (a.u.):    -0.00058920086896
	Scaled_OS Correlation Energy (a.u.):    -0.06797068148366
	CD-SCS-MP2 Total Energy (a.u.)     :   -26.01369044150004
	CD-SOS-MP2 Total Energy (a.u.)     :   -26.01876546408805
	CD-SCSN-MP2 Total Energy (a.u.)    :   -25.94824153973553
	CD-MP2 Correlation Energy (a.u.)   :     0.02352520344587
	CD-MP2 Total Energy (a.u.)         :   -25.92160535570154
	======================================================================= 
```

**Comment by CDSherrill** [comment]
This is very strange!  Yes, the CD-MP2 Correlation Energy is positive,
which is definitely wrong.  I can't imagine why seemingly innocent
changes to the input file would change the result, unless there is
just a memory leak or something.  Valgrind might be a good idea.

**Comment by bozkaya** [comment]
I do not have the latest revision. However, with the revision I have (Psi4 0.3.431) I removed "set mp2_type cd" and use energy('cd-mp2'), then I get 

CD-MP2 Correlation Energy (a.u.)   :    -0.05840983042460

Hence, with my version it appears to be okay. @loriab @CDSherrill

**Comment by bozkaya** [comment]
and all results are:

        Computing CD-MP2 energy using SCF MOs (Canonical CD-MP2)...
        =======================================================================
        Nuclear Repulsion Energy (a.u.)    :     4.91953818754669
        CD-HF Energy (a.u.)                :   -25.94513055914802
        REF Energy (a.u.)                  :   -25.94513055914802
        Alpha-Alpha Contribution (a.u.)    :    -0.00171224398409
        Alpha-Beta Contribution (a.u.)     :    -0.05664222782838
        Beta-Beta Contribution (a.u.)      :    -0.00005535861213
        Scaled_SS Correlation Energy (a.u.):    -0.00058920086541
        Scaled_OS Correlation Energy (a.u.):    -0.06797067339406
        CD-SCS-MP2 Total Energy (a.u.)     :   -26.01369043340749
        CD-SOS-MP2 Total Energy (a.u.)     :   -26.01876545532492
        CD-SCSN-MP2 Total Energy (a.u.)    :   -25.94824153971737
        CD-MP2 Correlation Energy (a.u.)   :    -0.05840983042460
        CD-MP2 Total Energy (a.u.)         :   -26.00354038957262
        =======================================================================

@loriab @CDSherrill

**Comment by loriab** [comment]
Yes, it's often right (that's how I got the reference value for the compare_values function, from a simple input file). My concern is that in a more complex input file, it started throwing odd energies, depending on the (commented) input file contents. It's possible there was something funny with my setup, but the error is consistent enough that I'm really suspicious.

**Comment by jturney** [comment]
Yeah, something is going on. I can run @loriab 's input from above and it'll randomly pass or fail. I used a binary from 2 days ago and another one that I just pulled and built.

**Comment by andysim** [comment]
Is this problem restricted to CD-MP2, @loriab?  If it's affecting the SCF energy too, it seems like it's a problem with the input parser not correctly handling the commented lines.

**Comment by jturney** [comment]
Here are my results from two failed runs, I only see a difference at the CD-MP2 line:

```
	Computing CD-MP2 energy using SCF MOs (Canonical CD-MP2)... 
	======================================================================= 
	Nuclear Repulsion Energy (a.u.)    :     4.91953818754669
	CD-HF Energy (a.u.)                :   -25.94513055914818
	REF Energy (a.u.)                  :   -25.94513055914818
	Alpha-Alpha Contribution (a.u.)    :    -0.00171224383410
	Alpha-Beta Contribution (a.u.)     :    -0.05664222895157
	Beta-Beta Contribution (a.u.)      :    -0.00005535848549
	Scaled_SS Correlation Energy (a.u.):    -0.00058920077319
	Scaled_OS Correlation Energy (a.u.):    -0.06797067474188
	CD-SCS-MP2 Total Energy (a.u.)     :   -26.01369043466326
	CD-SOS-MP2 Total Energy (a.u.)     :   -26.01876545678522
	CD-SCSN-MP2 Total Energy (a.u.)    :   -25.94824153923064
	CD-MP2 Correlation Energy (a.u.)   :    -0.02055603315430
	CD-MP2 Total Energy (a.u.)         :   -25.96568659230248
	======================================================================= 
```

```
	Computing CD-MP2 energy using SCF MOs (Canonical CD-MP2)... 
	======================================================================= 
	Nuclear Repulsion Energy (a.u.)    :     4.91953818754669
	CD-HF Energy (a.u.)                :   -25.94513055914819
	REF Energy (a.u.)                  :   -25.94513055914819
	Alpha-Alpha Contribution (a.u.)    :    -0.00171224383410
	Alpha-Beta Contribution (a.u.)     :    -0.05664222895157
	Beta-Beta Contribution (a.u.)      :    -0.00005535848549
	Scaled_SS Correlation Energy (a.u.):    -0.00058920077319
	Scaled_OS Correlation Energy (a.u.):    -0.06797067474188
	CD-SCS-MP2 Total Energy (a.u.)     :   -26.01369043466327
	CD-SOS-MP2 Total Energy (a.u.)     :   -26.01876545678523
	CD-SCSN-MP2 Total Energy (a.u.)    :   -25.94824153923066
	CD-MP2 Correlation Energy (a.u.)   :    -0.05918204371032
	CD-MP2 Total Energy (a.u.)         :   -26.00431260285851
	======================================================================= 
```

**Comment by loriab** [comment]
SCF is fine. It's not in that input file, but the case I was running had a SCF compare_values, too, and that was always passing.

**Comment by bozkaya** [comment]
Hi Lori,

I run your input many times, and I always get the correct result. Is it possible that this problem is related with the latest revision in psi4? Since some major changes were done. Is there any developer who can run this input with the psi4 version before the wfn_pass change? Then we can be sure whether this is something recent or not. @loriab @CDSherrill @andysim @jturney

**Comment by bozkaya** [comment]
Now I have install a fresh binary version (Psi4 0.4.16) and run the same input and get:

       Computing CD-MP2 energy using SCF MOs (Canonical CD-MP2)...
        =======================================================================
        Nuclear Repulsion Energy (a.u.)    :     4.91953818754669
        CD-HF Energy (a.u.)                :   -25.94513055914770
        REF Energy (a.u.)                  :   -25.94513055914770
        Alpha-Alpha Contribution (a.u.)    :    -0.00171224403804
        Alpha-Beta Contribution (a.u.)     :    -0.05664223456972
        Beta-Beta Contribution (a.u.)      :    -0.00005535856885
        Scaled_SS Correlation Energy (a.u.):    -0.00058920086896
        Scaled_OS Correlation Energy (a.u.):    -0.06797068148366
        CD-SCS-MP2 Total Energy (a.u.)     :   -26.01369044150033
        CD-SOS-MP2 Total Energy (a.u.)     :   -26.01876546408834
        CD-SCSN-MP2 Total Energy (a.u.)    :   -25.94824153973583
        CD-MP2 Correlation Energy (a.u.)   :    -0.02151506744300
        CD-MP2 Total Energy (a.u.)         :   -25.96664562659070
        =======================================================================

I also tried with another older version (Psi4 0.3.137) I still get the correct result. Hence, the new version yields wrong result while older versions give the correct result. Therefore, it should be related to the recent changes were made. I do not know how to fix it. 
@loriab @CDSherrill @andysim @jturney

**Comment by robparrish** [comment]
I'm a bit late to this party, but what strikes me as interesting (as Jet
says) is that the spin components printed look OK, but the various
summations at the very bottom of the table are wrong. That smells vaguely
like corruption in one of the summations.

-Rob

**Comment by loriab** [comment]
I didn't try too hard to break it on public (which doesn't have wavefunction_pass) so it's possible this never appears before the infrastructure changes. But nevertheless, those changes on the whole are for the better, and it's disturbing that infrastructure changes + suitable tweaking to make the extensive occ/dfocc test suite pass can still hide a situation like this. `Ecorr`, `Emp2AA`, etc. are computed out of sight.

...

Aha! Initializing variable (below) seems to help in https://github.com/psi4/psi4/blob/master/src/bin/dfocc/mp2_direct.cc#L90
Only affects UHF. Will continue explorations along these lines.

```
121     if (mo_optimized == 0) Esosmp2AB = sos_scale * Emp2AB;
122     else if (mo_optimized == 1) Esosmp2AB = sos_scale2 * Emp2AB;
123 
124     Emp2_t1 = 0.0;
125     if (reference == "ROHF" && orb_opt_ == "FALSE") {
126         if (wfn_type_ == "DF-OMP2" || wfn_type_ == "CD-OMP2") {
127         //Singles-contribution
128         Emp2_t1 = 0.0;
129         //Alpha
```

**Comment by bozkaya** [comment]
Yes you are right! it should be related with "Emp2_t1 = 0.0;" initialisation. Just keep it in the line 124 and delete that of line 128. I surprised why it  does not cause to problem for before wfn_pass changes but now it does. @loriab @CDSherrill @jturney @robparrish @andysim

**Comment by CDSherrill** [comment]
Nice job tracking this one down, everyone.

David
