### ISSUE TITLE
`guess` Not Updated After Failed Job

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#2458]
Consider the following:
```
molecule {
O
H 1 1.0 
H 1 1.0 2 104.5
}

set maxiter 2
energy("scf/cc-pvdz")
set guess sadno
energy("scf/cc-pvdz")
```

The second run does not use the new guess type, but the guess type will update if the absurdly low `set maxiter` is removed.

**Comment by hokru** [comment]
I suspect it has something to do with the fact that the exception in `scf_iteration.py` will mess with the option state that is modified in `scf_helper` but never restored.

`set_local_option("SCF","GUESS","SADNO")` will lead to the correct behaviour.

**Comment by JonathonMisiewicz** [comment]
Closing.

Upon rerunning the input file, I get the much saner behavior of Psi simply exiting. While one _could_ intercept the error with a manual try-except, use of `fail_on_maxiter` is the expected behavior and does not have this problem.
