### ISSUE TITLE
`libmints` Raw to Unique Pointer

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#2493]
Several methods in `libmints` export raw pointers. (See the file `libmints/integral.h` and [discussion](https://github.com/psi4/psi4/pull/2386#discussion_r832737185).) Those should be changed to `unique_ptr`.

Please do not start until #2386 is in. Check in here or on Slack before starting this issue, to confirm that you're not going to cause a problem for other ongoing PRs.

**Comment by hmacdope** [comment]
@JonathonMisiewicz is this issue still open for someone to work on?

**Comment by JonathonMisiewicz** [comment]
Yes, this issue is still open and is a good starter issue. Normally, this is when I'd invite you onto the Slack channel, but I see you already found it. Let me know if you have any further questions.
