### ISSUE TITLE
Failed tests

### ISSUE THREAD

**Issue by wpoely86** [psi4/psi4#253]
I thought it might be useful to share the failed tests of psi4 (using commit e4070d0024742579a445) on our systems. We have 4 failed tests:
```
The following tests FAILED:
	223 - opt10 (Timeout)
	240 - pubchem1 (Failed)
	241 - pubchem2 (Failed)
	255 - pywrap-opt-sowreap (Failed)
	264 - sapt4 (Failed)
```
The `pubchem` is probably just the firewall blocking stuff. Several times I've seen things like:
```
253: Unable to read the PSI4 Python folder - check the PSIDATADIR environmental variable
253:       Current value of PSIDATADIR is /user/scratch/gent/vsc403/vsc40307/EB/swalot/software/PSI/4.0b6-20160201-intel-2016a-mt-Python-2.7.11/share/psi4
```
Where the value of `PSIDATADIR` is the install path instead of the build path. I think `pywrap-opt-sowreap` fails because of this.

For the `sapt4` test:
```
264/305 Testing: sapt4
264/305 Test: sapt4
Command: "/apps/gent/CO7/haswell-ib/software/Python/2.7.11-intel-2016a/bin/python" "/dev/shm/ward/PSI/4.0b6-20160201/intel-2016a-mt-Python-2.7.11/psi4public-e4070d0024742579a445e084da9dde078310094d/tests/runtest.py" "/dev/shm/ward/PSI/4.0b6-20160201/intel-2016a-mt-Python-2.7.11/psi4public-e4070d0024742579a445e084da9dde078310094d/tests/sapt4/input.dat" "/dev/shm/ward/PSI/4.0b6-20160201/intel-2016a-mt-Python-2.7.11/obj/testresults.log" "false" "/dev/shm/ward/PSI/4.0b6-20160201/intel-2016a-mt-Python-2.7.11/psi4public-e4070d0024742579a445e084da9dde078310094d" "false" "/dev/shm/ward/PSI/4.0b6-20160201/intel-2016a-mt-Python-2.7.11/obj/tests/sapt4/output.dat" "/dev/shm/ward/PSI/4.0b6-20160201/intel-2016a-mt-Python-2.7.11/obj/bin/psi4"
Directory: /dev/shm/ward/PSI/4.0b6-20160201/intel-2016a-mt-Python-2.7.11/obj/tests/sapt4
"sapt4" start time: Feb 15 13:13 CET
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 65, in <module>
  File "/dev/shm/ward/PSI/4.0b6-20160201/intel-2016a-mt-Python-2.7.11/psi4public-e4070d0024742579a445e084da9dde078310094d/lib/python/p4util/util.py", line 98, in compare_values
    raise TestComparisonError(message)
p4xcpt.TestComparisonError:     SAPT Elst: computed value (-0.0407606) does not match (-0.0407577) to 6 decimal places.
        SAPT Elst: computed value (-0.0407606) does not match (-0.0407577) to 6 decimal places.
Exit Status: infile ( 1 ); autotest ( None ); sowreap ( None ); overall ( 1 )
<end of output>
Test time = 132.94 sec
----------------------------------------------------------
Test Failed.
"sapt4" end time: Feb 15 13:15 CET
"sapt4" time elapsed: 00:02:12
----------------------------------------------------------

```

For `pywrap-opt-sowreap`:
```
255/305 Testing: pywrap-opt-sowreap
255/305 Test: pywrap-opt-sowreap
Command: "/apps/gent/CO7/haswell-ib/software/Python/2.7.11-intel-2016a/bin/python" "/dev/shm/ward/PSI/4.0b6-20160201/intel-2016a-mt-Python-2.7.11/psi4public-e4070d0024742579a445e084da9dde078310094d/tests/runtest.py" "/dev/shm/ward/PSI/4.0b6-20160201/intel-2016a-mt-Python-2.7.11/psi4public-e4070d0024742579a445e084da9dde078310094d/tests/pywrap-opt-sowreap/input.dat" "/dev/shm/ward/PSI/4.0b6-20160201/intel-2016a-mt-Python-2.7.11/obj/testresults.log" "false" "/dev/shm/ward/PSI/4.0b6-20160201/intel-2016a-mt-Python-2.7.11/psi4public-e4070d0024742579a445e084da9dde078310094d" "true" "/dev/shm/ward/PSI/4.0b6-20160201/intel-2016a-mt-Python-2.7.11/obj/tests/pywrap-opt-sowreap/output.dat" "/dev/shm/ward/PSI/4.0b6-20160201/intel-2016a-mt-Python-2.7.11/obj/bin/psi4"
Directory: /dev/shm/ward/PSI/4.0b6-20160201/intel-2016a-mt-Python-2.7.11/obj/tests/pywrap-opt-sowreap
"pywrap-opt-sowreap" start time: Feb 15 13:13 CET
Output:
----------------------------------------------------------
/dev/shm/ward/PSI/4.0b6-20160201/intel-2016a-mt-Python-2.7.11/obj/tests/pywrap-opt-sowreap/output.dat
Traceback (most recent call last):
  File "/dev/shm/ward/PSI/4.0b6-20160201/intel-2016a-mt-Python-2.7.11/psi4public-e4070d0024742579a445e084da9dde078310094d/tests/reap.py", line 127, in <module>
    main(*sys.argv[1:])
  File "/dev/shm/ward/PSI/4.0b6-20160201/intel-2016a-mt-Python-2.7.11/psi4public-e4070d0024742579a445e084da9dde078310094d/tests/reap.py", line 106, in main
    files_list,master_in,master_out= sowList(first_output)
  File "/dev/shm/ward/PSI/4.0b6-20160201/intel-2016a-mt-Python-2.7.11/psi4public-e4070d0024742579a445e084da9dde078310094d/tests/reap.py", line 31, in sowList
    master_in=the_tag+"-master.in"
UnboundLocalError: local variable 'the_tag' referenced before assignment
Performing finite difference calculations
 5 displacements needed ...Exit Status: infile ( 0 ); autotest ( None ); sowreap ( 1 ); overall ( 1 )
<end of output>
Test time =   0.90 sec
----------------------------------------------------------
Test Failed.
"pywrap-opt-sowreap" end time: Feb 15 13:13 CET
"pywrap-opt-sowreap" time elapsed: 00:00:00
----------------------------------------------------------
```

I've saved the output of `sapt4` and `opt10` to https://gist.github.com/wpoely86/60885c5adec8dcc8b63b

Furthermore, `opt2` is flaky. It doesn't always pass. Most of the time but not always.
These tests where run on a dual socket Xeon E5-2660v3 (20 cores in total without HT) with icc/icpc 2016.1.150 + MKL 11.3.1.150.

**Comment by jturney** [comment]
Thank you for the detailed report.  You're probably right about the firewall causing the ```pubchem*``` tests to fail. I'll see what I can figure out about the others.

**Comment by loriab** [comment]
The sowreap one is a failure of both the capability and the testing mechanics. It's been removed temporarily through wfn_pass PR. Sapt4 changes are due to actually turning on by default the nat orb tricks we always recommended. That test case has been modified to pass also in wfn_pass PR. The opt one sounds like an actual problem.

**Comment by jturney** [comment]
```opt10``` is too big for a test case: 15 atoms, C1 symmetry, 322 basis functions, requests 32 GB of memory, and performing a transition state geometry optimization with an initial Hessian by finite difference of gradients. The calculation timed out on the 13 of 79 gradient displacements of the initial Hessian. The only thing that does help is that it's a DF-MP2 calculation.

**Comment by dgasmith** [comment]
Ah yes, this is no longer a used test cases in wavefunction_pass. @psi-rking is it possible to reduce the basis set to something fairly quick?

Daniel Smith
malorian@me.com

**Comment by psi-rking** [comment]
This is an actual representative of the failed (large) optimizations that I
constantly get forwarded to me! :)  I don't choose them.  Do we not have a
way to leave test cases, even 'longertests' in there without them
interfering in the normal course?

The purpose of this tests is that it has challenging quasi-linear angles in
it.  I have no objection to reducing the calculation.  Perhaps removing the
polarization functions would be enough?

-Rollin


--
Dr. Rollin A. King
Professor and Chair of Chemistry
Bethel University
rking@bethel.edu

**Comment by jturney** [comment]
Yeah, we should have that mechanism to leave it as a longertest. Maybe that's what @dgasmith has already done.

**Comment by wpoely86** [comment]
I've run this test (`opt10`) without limits on 128 GB RAM and 20 threads and it takes:
```
Total time:
	user time   =   36215.14 seconds =     603.59 minutes
	system time =     882.69 seconds =      14.71 minutes
	total time  =       2280 seconds =      38.00 minutes
```
So the test works, it just takes some time.

**Comment by dgasmith** [comment]
I just removed opt10 from all ctest labels. Its still present, but will not run unless you specifically request it.

It looks like the reference opt10 ran in about 6 hours on 8 threads.

**Comment by psi-rking** [comment]
I tried the cc-pvdz optimization.  I runs in 16 minutes (on 8 cores) with
1gb of memory.  Is that short enough?  If so, I'll commit the change.

-Rollin

--
Dr. Rollin A. King
Professor and Chair of Chemistry
Bethel University
rking@bethel.edu

**Comment by dgasmith** [comment]
The current cap for ctest is 25 minutes on a single core. Is there any reason not to do this on a tiny basis like 6-31G or 3-21G?

This is just if you want the test case to be run routinely, there is nothing wrong with having extra long test cases that are only run if specifically requested.

**Comment by CDSherrill** [comment]
That 25 minute cap is from Travis CI?  Travis only runs 'quicktests',
so this test case could be added to one of the other test categories, like
longtests, in principle.

That said, the quicker the test runs (while testing the desired feature)
the better.  So, it is worth checking it with 6-31G or even 3-21G, and/or
loosening the convergence criteria.

David

**Comment by psi-rking** [comment]
The 6-31G case runs fine in ~20 minutes on one core.  I'll call it a
'longtest' and check it in now.
-Rollin

**Comment by dgasmith** [comment]
The 25 minute cap is a ctest cap that we control. The cap helps figure out if a test case is stuck in a loop or not.

Cheers,
Daniel Smith

**Comment by dgasmith** [comment]
@wpoely86 Please do a fresh full, the opt10 and sapt4 failures should be resolved. For pubchem you can try running the following python script:

```python
from urllib2 import urlopen
print urlopen('http://pubchem.ncbi.nlm.nih.gov/pug/pug.cgi', "").read()
```

If you can access your server you should see some xml containing the following line:
 `<PCT-Status-Message_messages_E>Status: input-error.`.

If you bounce off your firewall you will likely see something along the lines of `URLError: <urlopen error [Errno 11004] getaddrinfo failed>`.

**Comment by wpoely86** [comment]
@dgasmith yes, `opt10` and `sapt4` no longer complain. However, I've got two new failures: `opt7` and `opt-irc-2`.
For `opt7`:
```
PsiException:   Int. Coord. RHF opt of HOOH with O-O-H fixed to 105, energy: computed value (-150.7861731) does not match (-150.7861769) to 6 decimal places.
```
For `opt-irc-2`:
```
PsiException:   Energy of last IRC point: computed value (-92.869134) does not match (-92.868901) to 5 decimal places.
```

**Comment by dgasmith** [comment]
@wpoely86 Well thats unfortunate. I just pulled through a fix for opt-irc-2. I see opt7 passing on my machine and our server. Can you paste the output to a gist?

**Comment by wpoely86** [comment]
The output can be found at https://gist.github.com/2accb9b2529bae19d209

**Comment by dgasmith** [comment]
@loriab I think this looks like the INTCO file issues again, would you agree?

**Comment by loriab** [comment]
You mean @avcopan should adjust the compare_values test for opt7 to the last-optimized-irc-point from the last structure, similar to what was done for opt-irc-1 & -2, @dgasmith? I think I agree.

**Comment by avcopan** [comment]
Since opt7 is not an IRC test case, I better let @psi-rking decide what he wants to do with it.

**Comment by loriab** [comment]
Sorry @avcopan, I saw all the `@IRC`s in that gist above and thought opt7 was an unlabeled IRC. But that was for opt-irc-2, which should be fixed now.

opt7 fails on a few systems (https://testboard.org/cdash/testSummary.php?project=3&name=opt7&date=2016-03-01). This (https://testboard.org/cdash/testDetails.php?test=7810317&build=63640) looks like the most coherent error message (also copied below), if @psi-rking would like to examine it.

```
Optimizer: Optimization complete!
	Int. Coord. RHF opt of HOOH with O-H fixed to 0.95, energy........PASSED
Optimizer: Optimization complete!
	Int. Coord. RHF opt of HOOH with O-O-H fixed to 105, energy: computed value (-150.7861731) does not match (-150.7861769) to 6 decimal places.
```

**Comment by psi-rking** [comment]
Doesn't really look like a bug.  Either we up the convergence criterion or
we check only 5 decimals.

**Comment by loriab** [comment]
Concur. Whichever you feel meets the testing needs best.
