### ISSUE TITLE
Is it possible to write the geometry of a molecule in python via a function?

### ISSUE THREAD

**Issue by ErikCVik** [psi4/psi4#2553]
Is it possible to write the geometry of a molecule in python via a function?

For example, I want to take an SDF, chop down to only the coordinates of the atoms, then plug those coordinates into "psi4.geometry(...)" all without leaving python. Currently, it looks like "psi4.geometry(...)" only takes comments as an input, so it's impossible to write the coordinates via a function.

I know I can work around this by writing in bash and running a calculation on a stand alone input file, but this makes life more difficult because if I want to run multiple calculations I would either collect 10^x in/output files or write over preceding ones limiting me to non-parallel computing.

**Comment by loriab** [comment]
Yes, you can use `from_arrays` like below that takes [these arguments](https://github.com/MolSSI/QCElemental/blob/master/qcelemental/molparse/from_arrays.py#L136-L293). Then you have to either activate the molecule (`psi4.geometry()` does this behind the scenes) or pass the molecule explicitly to each calculation line. `from_arrays` is the same fn that `geometry()` is calling after parsing the string. If you want to get the arrays back out of a built molecule, there's a `to_dict()` fn. Let me know if there's other functionality that would be handy but you can't find.

Also, be aware of running in schema mode with json in and json out.

```
h2o = psi4.core.Molecule.from_arrays(elem=["O", "H", "H"], units="Angstrom", geom=[
          0.000000000000,     0.000000000000,    -0.065775570538, 
          0.000000000000,    -0.759061990794,     0.521953018295, 
          0.000000000000,     0.759061990794,     0.521953018295]) 
psi4.activate(h2o)
# activate -or- pass into fn
psi4.energy(..., molecule=h2o)
```

**Comment by loriab** [comment]
thanks, @PeterKraus 

> Note that you can find the current implementation of the psi4.Molecule class [here](https://github.com/psi4/psi4/blob/master/psi4/driver/qcdb/molecule.py).

It's pretty much a technicality, as that linked Python class and the C++ libmints class are 99+% interchangeable (except to compilers), but what that linked class builds is a `qcdb.Molecule` and what libmints builds is a `psi4.core.Molecule`. The latter is what calculations happen on internally in the end. The former has convenience purposes along the way.

**Comment by JonathonMisiewicz** [comment]
Question answered, so closing.
