### ISSUE TITLE
clean up tests directory

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#2555]
after #2549, the list from `python tester.py` looks like the below. Most of these are easily healed by figuring out if they're intended to be a test or not. Nots should be removed to an attic or deleted. Also related is #2234 . don't rely on the below -- rerun tester.py as needed.

@psi-rking, do you prefer attic or deletion for the un-run optimizer tests?

Complaints
----------
- [ ]   1. cc5: missing cmake directory registration. `vi CMakeLists.txt`
- [ ]   2. cookbook/manual-sow-reap: missing cmake directory registration. `vi cookbook/CMakeLists.txt`
- [ ]   3. cookbook/manual-sow-reap: missing CMakeLists. `vi cookbook/manual-sow-reap/CMakeLists.txt`
- [ ]   4. dfmp2-freq1: missing cmake directory registration. `vi CMakeLists.txt`
- [ ]   5. dfmp2-freq2: missing cmake directory registration. `vi CMakeLists.txt`
- [ ]   6. dfomp2p5-1: missing ctest registration. `vi dfomp2p5-1/CMakeLists.txt`
- [ ]   7. dfomp2p5-2: missing ctest registration. `vi dfomp2p5-2/CMakeLists.txt`
- [ ]   8. dfomp2p5-grad1: missing ctest registration. `vi dfomp2p5-grad1/CMakeLists.txt`
- [ ]   9. dfomp2p5-grad2: missing ctest registration. `vi dfomp2p5-grad2/CMakeLists.txt`
- [ ]  10. dft-dldf: missing cmake directory registration. `vi CMakeLists.txt`
- [ ]  11. dft-dsd: missing cmake directory registration. `vi CMakeLists.txt`
- [ ]  12. dft-pbe0-2: missing cmake directory registration. `vi CMakeLists.txt`
- [ ]  13. explicit-am-basis: mismatched directory (explicit-am-basis) and ctest registration name (explicit_am_basis). `vi explicit-am-basis/CMakeLists.txt`
- [ ]  14. fsapt-diff1: missing cmake directory registration. `vi CMakeLists.txt`
- [ ]  15. fsapt-diff1: missing CMakeLists. `vi fsapt-diff1/CMakeLists.txt`
- [ ]  16. gcp/hf3c-gradient: mismatched marks ctest () and pytest (gradient). `vi gcp/hf3c-gradient/CMakeLists.txt gcp/hf3c-gradient/test_input.py`
- [ ]  17. gcp/hf3c-hessian: mismatched marks ctest () and pytest (hessian). `vi gcp/hf3c-hessian/CMakeLists.txt gcp/hf3c-hessian/test_input.py`
- [ ]  18. gpu_dfcc/gpudfcc1: missing ctest registration. `vi gpu_dfcc/gpudfcc1/CMakeLists.txt`
- [ ]  19. gpu_dfcc/gpudfcc2: missing ctest registration. `vi gpu_dfcc/gpudfcc2/CMakeLists.txt`
- [ ]  20. large-atoms: missing cmake directory registration. `vi CMakeLists.txt`
- [ ]  21. large-atoms: mismatched directory (large-atoms) and ctest registration name (large_atoms). `vi large-atoms/CMakeLists.txt`
- [ ]  22. min-input: missing cmake directory registration. `vi CMakeLists.txt`
- [ ]  23. min-input: mismatched directory (min-input) and ctest registration name (min_input). `vi min-input/CMakeLists.txt`
- [ ]  24. opt-multi-dimer-c1: missing cmake directory registration. `vi CMakeLists.txt`
- [ ]  25. opt-multi-dimer-c2h: missing cmake directory registration. `vi CMakeLists.txt`
- [ ]  26. opt-multi-frozen-dimer-c2h: missing cmake directory registration. `vi CMakeLists.txt`
- [ ]  27. opt10: missing cmake directory registration. `vi CMakeLists.txt`
- [ ]  28. optking/bakerjcc93: missing cmake directory registration. `vi optking/CMakeLists.txt`
- [ ]  29. optking/bakerjcc93: missing docs comment. `vi optking/bakerjcc93/input.dat`
- [ ]  30. optking/bakerjcc93: missing CMakeLists. `vi optking/bakerjcc93/CMakeLists.txt`
- [ ]  31. optking/beran: missing cmake directory registration. `vi optking/CMakeLists.txt`
- [ ]  32. optking/beran: missing docs comment. `vi optking/beran/input.dat`
- [ ]  33. optking/beran: missing CMakeLists. `vi optking/beran/CMakeLists.txt`
- [ ]  34. optking/dlpc: missing cmake directory registration. `vi optking/CMakeLists.txt`
- [ ]  35. optking/dlpc: missing docs comment. `vi optking/dlpc/input.dat`
- [ ]  36. optking/dlpc: missing CMakeLists. `vi optking/dlpc/CMakeLists.txt`
- [ ]  37. optking/h2o: missing cmake directory registration. `vi optking/CMakeLists.txt`
- [ ]  38. optking/h2o: missing docs comment. `vi optking/h2o/input.dat`
- [ ]  39. optking/h2o: missing CMakeLists. `vi optking/h2o/CMakeLists.txt`
- [ ]  40. optking/h2os: missing cmake directory registration. `vi optking/CMakeLists.txt`
- [ ]  41. optking/h2os: missing docs comment. `vi optking/h2os/input.dat`
- [ ]  42. optking/h2os: missing CMakeLists. `vi optking/h2os/CMakeLists.txt`
- [ ]  43. plugins/skeleton: missing docs comment. `vi plugins/skeleton/input.dat`
- [ ]  44. plugins/skeleton: missing ctest registration. `vi plugins/skeleton/CMakeLists.txt`
- [ ]  45. plugins/skeletonaointegrals: missing docs comment. `vi plugins/skeletonaointegrals/input.dat`
- [ ]  46. plugins/skeletonaointegrals: missing ctest registration. `vi plugins/skeletonaointegrals/CMakeLists.txt`
- [ ]  47. plugins/skeletondfmp2: missing docs comment. `vi plugins/skeletondfmp2/input.dat`
- [ ]  48. plugins/skeletondfmp2: missing ctest registration. `vi plugins/skeletondfmp2/CMakeLists.txt`
- [ ]  49. plugins/skeletonmointegrals: missing docs comment. `vi plugins/skeletonmointegrals/input.dat`
- [ ]  50. plugins/skeletonmointegrals: missing ctest registration. `vi plugins/skeletonmointegrals/CMakeLists.txt`
- [ ]  51. plugins/skeletonscf: missing docs comment. `vi plugins/skeletonscf/input.dat`
- [ ]  52. plugins/skeletonscf: missing ctest registration. `vi plugins/skeletonscf/CMakeLists.txt`
- [ ]  53. plugins/skeletonsointegrals: missing docs comment. `vi plugins/skeletonsointegrals/input.dat`
- [ ]  54. plugins/skeletonsointegrals: missing ctest registration. `vi plugins/skeletonsointegrals/CMakeLists.txt`
- [ ]  55. plugins/skeletonwavefunction: missing docs comment. `vi plugins/skeletonwavefunction/input.dat`
- [ ]  56. plugins/skeletonwavefunction: missing ctest registration. `vi plugins/skeletonwavefunction/CMakeLists.txt`
- [ ]  57. props4: missing cmake directory registration. `vi CMakeLists.txt`
- [ ]  58. python/cc-amps: mismatched directory (python-cc-amps) and ctest registration name (python-cc_amps). `vi python/cc-amps/CMakeLists.txt`
- [ ]  59. python/mints13: missing pytest input generated. check it! `vi python/mints13/test_input.py`
- [ ]  60. pywrap-db2: missing cmake directory registration. `vi CMakeLists.txt`
- [ ]  61. pywrap-freq-e-sowreap: missing cmake directory registration. `vi CMakeLists.txt`
- [ ]  62. pywrap-freq-g-sowreap: missing cmake directory registration. `vi CMakeLists.txt`
- [ ]  63. pywrap-opt-sowreap: missing cmake directory registration. `vi CMakeLists.txt`
- [ ]  64. scf11-freq-from-energies: missing cmake directory registration. `vi CMakeLists.txt`
- [ ]  65. snsmp2/cc-cc: mismatched marks ctest (longtests;snsmp;cart) and pytest (long;cart). `vi snsmp2/cc-cc/CMakeLists.txt snsmp2/cc-cc/test_input.py`
- [ ]  66. snsmp2/cf-o: mismatched marks ctest (snsmp;cart) and pytest (cart). `vi snsmp2/cf-o/CMakeLists.txt snsmp2/cf-o/test_input.py`
- [ ]  67. snsmp2/he-he: mismatched marks ctest (quick;smoke;snsmp;cart) and pytest (quick;smoke;cart). `vi snsmp2/he-he/CMakeLists.txt snsmp2/he-he/test_input.py`
- [ ]  68. v2rdm_casscf/v2rdm1: mismatched marks ctest (v2rdm) and pytest (). `vi v2rdm_casscf/v2rdm1/CMakeLists.txt v2rdm_casscf/v2rdm1/test_input.py`
- [ ]  69. v2rdm_casscf/v2rdm2: mismatched marks ctest (v2rdm) and pytest (). `vi v2rdm_casscf/v2rdm2/CMakeLists.txt v2rdm_casscf/v2rdm2/test_input.py`
- [ ]  70. v2rdm_casscf/v2rdm3: mismatched marks ctest (quick;smoke;v2rdm) and pytest (quick;smoke). `vi v2rdm_casscf/v2rdm3/CMakeLists.txt v2rdm_casscf/v2rdm3/test_input.py`
- [ ]  71. v2rdm_casscf/v2rdm4: mismatched marks ctest (v2rdm;cart) and pytest (cart). `vi v2rdm_casscf/v2rdm4/CMakeLists.txt v2rdm_casscf/v2rdm4/test_input.py`
- [ ]  72. v2rdm_casscf/v2rdm5: mismatched marks ctest (v2rdm) and pytest (). `vi v2rdm_casscf/v2rdm5/CMakeLists.txt v2rdm_casscf/v2rdm5/test_input.py`
- [ ]  73. v2rdm_casscf/v2rdm6: mismatched marks ctest (opt;v2rdm) and pytest (opt). `vi v2rdm_casscf/v2rdm6/CMakeLists.txt v2rdm_casscf/v2rdm6/test_input.py`
- [ ]  74. v2rdm_casscf/v2rdm7: mismatched marks ctest (opt;v2rdm) and pytest (opt). `vi v2rdm_casscf/v2rdm7/CMakeLists.txt v2rdm_casscf/v2rdm7/test_input.py`
- [ ]  75. x2c-perturb-h: mismatched directory (x2c-perturb-h) and ctest registration name (x2c-perturb_h). `vi x2c-perturb-h/CMakeLists.txt`

**Comment by psi-rking** [comment]
The only thing worth hanging onto might be the bakerjcc93.  But if we've
got that database otherwise available, then deletion fine with me.

**Comment by JonathonMisiewicz** [comment]
If @loriab can update current status post-#2655?

**Comment by philipmnel** [comment]
After #2655 `tester.py` complaints look like this:

Complaints
----------
- [ ]   1. fsapt-diff1: missing cmake directory registration. `vi CMakeLists.txt`
- [ ]   2. fsapt-diff1: missing CMakeLists. `vi fsapt-diff1/CMakeLists.txt`
- [ ]   3. large-atoms: missing cmake directory registration. `vi CMakeLists.txt`
- [ ]   4. python/mints13: missing pytest input generated. check it! `vi python/mints13/test_input.py`

------
`fsapt-diff1` contains useful reference data, but not currently tested.

`large-atoms` is a draft test that was waiting on ECP gradients. Now that these are in, this should be able to be fleshed out.

`python/mints13` is not currently working with pytest, so the generated input should be ignored for now. This test works through `python` but fails when run through `psi4` executable (ctest does the first, pytest the latter). It seems that the way pytest treats python input files might need to be fixed. See the note here: https://github.com/psi4/psi4/blob/master/tests/pytests/addons.py#L194-L203

**Comment by loriab** [comment]
Thanks for the round-up, Philip. I agree with your assessments. The remainder aren't readily "solved", so I'm ok with having this issue closed by your PR.

**Comment by loriab** [comment]
closed by #2655
