### ISSUE TITLE
Deep ECPs feel broken

### ISSUE THREAD

**Issue by robparrishqc** [psi4/psi4#2564]
Hello to my dear friends at PSI4. Nick Stair (@nstair) and I were just testing a brand new GPU implementation of ECPs, and ended up needing three codes to do the test. In many cases, all three codes match to the machine epsilon. However, for L+1 = F-type ECPs I'm afraid PySCF and Tachyon match and PSI4 out of the box does not. We see silent differences of O(1.0) au. So while I am not 100% certain, I have a strong suspicion that the F-type ECPs and higher are broke in PSI4. Maybe it is as simple as cranking the compiled L up one in the ECP library? I'm just worried about users silently running broke deep cores. Beer for you all if it is on our end, but thought it was worth raising. 

Tech note: Note that the tests below are of the spectra of the V_pq matrices in the AO basis because Nick is too lazy/clever to reorder the PySCF basis functions. We also have tests lower in L of the PSI4 <-> Tachyon matrix elements (same basis ordering, of course!!) that match to mach eps. 

![image](https://user-images.githubusercontent.com/43890147/165858988-c31c42fa-9c58-4068-993a-5648bec9baaf.png)

**Comment by robparrishqc** [comment]
Small typo in the above - the second system title is ag_do4s:
![image](https://user-images.githubusercontent.com/43890147/165861245-69803e14-52f0-4211-b72c-77c4ff296b32.png)

**Comment by loriab** [comment]
Hi Rob, great to hear from you!

I'll patch up https://github.com/psi4/psi4/pull/2135 so that psi is using libecpint rather than internal ecp code. That'll be a better starting point for debugging. Thanks for the report!

**Comment by andysim** [comment]
Heads-up, Lori.  I'm working on #2135 right now.  It needed a significant rebase after the Libint2 switch, but I'm getting close to having it working again.

**Comment by PeterKraus** [comment]
@robparrishqc libecpint is now used by default in Psi4 1.6 - could you check whether the issue is still present?

**Comment by robparrishqc** [comment]
Hi Peter - typically  it is the house's job to determine if a bug has been
resolved or not - did you all (1) find evidence of my reported bug and (2)
find evidence that it was fixed? I did not report that one lightly. Also
quite worried - I am seeing indications you all are switching basis
function ordering from one perfectly well-defined lexical convention which
is well documented to yet another perfectly well-defined lexical
convention. Both equally valid except that the first has been baked into a
half-million line code over more than a decade. If the switch of basis
functions is made at a similar time, this will provide additional barriers
for our staff to verify your proposed fix.

**Comment by robparrishqc** [comment]
[Uploading report.pdf…]()

**Comment by robparrishqc** [comment]
I.e., these are the notes I've used forever to explain PSI4 - now defunct

**Comment by robparrishqc** [comment]
[report.pdf](https://github.com/psi4/psi4/files/8746161/report.pdf)
^^ I.e., these are the hard-won notes I have used for years to describe PSI4 ordering (maybe not CCA, but hey, it works).

**Comment by JonathonMisiewicz** [comment]
Hi, Rob. All ECP-related issues are marked with the `ecpint-needed` tag. There are currently five open ones. I'm going to go through them and attempt to reproduce them with the v1.6 release, so we can assess if ECPs are broken.

You raise a good point: debugging ECP issues is going to be harder if we also change basis functions. @loriab, can we put a moratorium on #2537 until we've had more time to investigate the ECP issues and evaluate the performance of DDD "in the wild"? While I would not expect DDD to introduce strange correctness errors like I would expect of integral convention swaps, I am too paranoid to neglect the possibility.

Say hi to Nick Stair for me. I'll report back once I've finished my preliminary investigations.

**Comment by susilehtola** [comment]
@robparrishqc what is Tachyon? do you have a link?

**Comment by JonathonMisiewicz** [comment]
I've been able to reproduce a disagreement between Psi4 and PySCF integrals. I've reached out to the `libecpint` developer to figure out if this may be an issue of numerical tightness. As far as I can tell, there's no mechanism for Psi4 to tell `libecpint` that we want our integrals to within a certain tolerance. That may be the issue for the iron pentacarbonyl system.

The disagreement for your second system is much more disturbing, but my policy with debugging is to start with the simple cases first.

**Comment by robparrishqc** [comment]
I wouldn't worry so much about the first one - likely some threshold in what is probably the radial quadrature grid (not sure how libecpint does it, but we use a radial quadrature that converges exponentially with respect to number of points, and also has a threshold in how far out the ECP goes before vanishing). Maybe needs to be tightened, but I think you are circling the qualitative convergence well on that one. 

The second one is rough because it is silently off in the first digit - I think this means the formula is not correct. A key difference between the first and second one is that the second one goes up higher in L in the ECP.

**Comment by andysim** [comment]
I strongly suspect that this has been fixed by our switch to libECPInt (instead of the hand-rolled version).  That early code likely didn't go high enough in angular momentum (as Rob surmises) so it silently returned garbage.  If the bug can't be reproduced with v1.6, it means Rob's theory is correct and his beer debt is cancelled.

**Comment by JonathonMisiewicz** [comment]
I can at least give it a try.

What's the ligand on the second example? I've checked multiple indexes of common inorganic ligands, but I can't find any matches for `dos`.

**Comment by robparrishqc** [comment]
```

11
0 1
Fe     0.000000    0.000000    0.000000
C      0.000000    1.811939    0.000000
C      1.569185   -0.905970    0.000000
C     -1.569185   -0.905970    0.000000
C      0.000000    0.000000    1.814011
C      0.000000    0.000000   -1.814011
O      0.000000    2.977582    0.000000
O      2.578662   -1.488791    0.000000
O     -2.578662   -1.488791    0.000000
O      0.000000    0.000000    2.976843
O      0.000000    0.000000   -2.976843
```

and 

```
73

AG               0.031287668528278    -0.205915953679435     0.128067261599448
S                1.823387668528279    -2.301515953679435     0.052467261599449
S               -2.255812331471722    -3.420515953679435    -4.418832738400551
S               -1.377912331471722    -1.275915953679435     2.212867261599449
S                2.257287668528280     2.977284046320565     4.731867261599449
N                1.731987668528279     0.506484046320565    -1.678332738400552
N               -1.239312331471722    -0.097815953679435    -2.137532738400552
N               -1.950512331471721     1.438084046320565     0.436367261599448
N                1.013987668528279     2.082584046320565     0.869667261599449
C                1.088587668528278     0.332884046320565    -2.981732738400551
H                1.206987668528279    -0.710315953679435    -3.288432738400552
H                1.599287668528278     0.932284046320565    -3.761032738400552
C               -0.389912331471721     0.696384046320565    -3.019232738400552
H               -0.507812331471722     1.747184046320565    -2.738332738400551
H               -0.712512331471722     0.642984046320565    -4.074732738400551
C               -2.513712331471722     0.563484046320565    -1.868332738400552
H               -3.196212331471722    -0.195515953679435    -1.467932738400552
H               -2.991812331471722     0.942884046320565    -2.791232738400552
C               -2.443712331471721     1.743684046320565    -0.905632738400551
H               -1.801812331471721     2.519684046320565    -1.333232738400551
H               -3.456212331471721     2.192384046320565    -0.865132738400551
C               -1.427112331471722     2.642584046320565     1.081467261599449
H               -1.407712331471722     2.474684046320565     2.162167261599449
H               -2.105012331471721     3.505084046320565     0.926567261599449
C               -0.038112331471721     3.062184046320565     0.618567261599448
H               -0.063112331471722     3.256884046320565    -0.457732738400551
H                0.178687668528279     4.041184046320565     1.082867261599449
C                2.186687668528279     2.315184046320565     0.030367261599449
H                3.019687668528279     1.755884046320565     0.472567261599448
H                2.499987668528278     3.376284046320565     0.033167261599448
C                2.026987668528278     1.918084046320565    -1.433132738400551
H                1.227387668528279     2.514084046320565    -1.882932738400552
H                2.952387668528280     2.227184046320565    -1.958432738400552
C                2.953287668528279    -0.288315953679435    -1.590032738400551
H                3.541787668528279     0.081784046320565    -0.744332738400551
H                3.584887668528278    -0.149615953679435    -2.491532738400551
C                2.742387668528278    -1.784615953679435    -1.408532738400552
H                2.200887668528279    -2.228415953679435    -2.253532738400551
H                3.723887668528279    -2.280815953679435    -1.394932738400551
C                3.077287668528278    -2.172715953679435     1.333267261599449
H                3.891987668528278    -2.880415953679435     1.136967261599449
H                2.591187668528279    -2.459215953679435     2.273067261599448
H                3.474787668528279    -1.159815953679435     1.437867261599449
C               -1.436112331471721    -1.477215953679435    -2.605332738400552
H               -1.954512331471722    -2.013415953679435    -1.803032738400552
H               -0.457512331471722    -1.958515953679435    -2.699832738400552
C               -2.196312331471721    -1.689015953679435    -3.915432738400551
H               -3.220012331471722    -1.293615953679435    -3.872732738400551
H               -1.694812331471721    -1.189515953679435    -4.754632738400550
C               -3.527112331471721    -4.072015953679434    -3.329932738400551
H               -3.218612331471721    -4.104115953679435    -2.279532738400551
H               -3.703112331471722    -5.102915953679435    -3.660232738400552
H               -4.467112331471721    -3.517515953679434    -3.439432738400551
C               -3.004412331471721     0.830684046320565     1.241967261599449
H               -3.556512331471721     0.127284046320565     0.610267261599449
H               -3.740712331471721     1.590484046320565     1.575867261599448
C               -2.524712331471722     0.087884046320565     2.480767261599448
H               -2.010312331471722     0.753784046320565     3.185067261599449
H               -3.399912331471721    -0.296615953679435     3.024667261599449
C               -2.489112331471721    -2.582315953679435     1.676767261599449
H               -1.861712331471721    -3.454515953679435     1.459567261599449
H               -3.048712331471722    -2.318615953679435     0.775667261599449
H               -3.179612331471722    -2.846715953679435     2.486867261599448
C                1.378987668528278     1.974484046320565     2.289267261599448
H                2.050087668528279     1.113584046320565     2.380467261599449
H                0.482987668528278     1.715784046320565     2.862167261599448
C                2.032587668528279     3.186284046320565     2.954567261599449
H                2.998187668528279     3.441984046320565     2.497867261599449
H                1.395687668528278     4.077284046320565     2.877167261599449
C                3.658087668528278     1.854484046320565     4.791167261599449
H                3.934687668528278     1.777384046320565     5.849667261599449
H                4.518387668528278     2.262684046320565     4.246667261599448
H                3.417287668528278     0.847784046320565     4.432767261599449
```

**Comment by robparrishqc** [comment]
Really sorry guys, this one is our PICNIC. We realized that we forgot to include the S atom ECP (thought it was too high for an ECP, but nontheless LANL2DZ wants one) in the second case. So now the codes agree reasonably well - some moderate numerical differences which are likely quadratures or fundamental integrals, but otherwise good. 

Where do you want the beer sent?
