### ISSUE TITLE
Difficulty building release 1.6 with MAX_AM_ERI=7

### ISSUE THREAD

**Issue by tallakahath** [psi4/psi4#2586]
I've been trying to build a version of psi4 1.6 (based on the release from a day or so ago) with MAX_AM_ERI=7, and run into various issues. I think at this point I've solved all my issues, but wanted to document my steps here in case any of these can help others.

**Overall**: Is MAX_AM_ERI=7 meant for use on 1.6? Is https://github.com/loriab/libint/releases/download/v0.1/Libint2-export-7-7-4-8-8-5_mm4f12ob2.tgz the right file to use (with patches described below)?

**Problem 1**: psi4/external/upstream/libint2/CMakeLists.txt refers to a single libint2 file regardless of MAX_AM_ERI (https://github.com/psi4/psi4/blob/1.6.x/external/upstream/libint2/CMakeLists.txt#L63) 

**Solution 1**: Grab https://github.com/loriab/libint/releases/download/v0.1/Libint2-export-7-7-4-8-8-5_mm4f12ob2.tgz instead

**Problem 2**: The CMakeLists.txt in Libint2-export-7-7-4-8-8-5_mm4f12ob2.tgz has an incorrectly quoted macro, which results in a build error when trying to compile using header files from libint2. The original correct quoting appears commented out? Which makes me worried maybe it was that way for a Reason, but it would not build that way.

**Solution 2**: Uncomment line 303 and remove line 304 of libint-2.7.1/CMakeLists.txt, then (re)build. (this makes it look like the CMakeLists.txt in the default https://github.com/loriab/libint/releases/download/v0.1/Libint2-export-5-4-3-6-5-4_mm4f12ob2.tgz).

**Comment by loriab** [comment]
I should have read this first before replying on twitter. That 7-7-4-8-8-5 file was a trial I was making (https://github.com/psi4/psi4/issues/1341#issuecomment-1130271539). And in generating the tarball, I caught some uncommitted local changes that I was trying to fix a separate issue of paths in Windows.

Thanks for the report, and I'm sorry for the trouble. I'll certainly patch it up before officially recommending that larger AM tarball.

Out of curiosity, what architecture/threads were you using that you got that tarball to build in 3 hours?

**Comment by tallakahath** [comment]
Three hours and nine minutes, according to the timestamps I have for relevant events.  I _believe_ the build ran on a 32-thread (16-core) intel broadwell (with ample memory to avoid paging, for however much that helps), and the build was the only event happening on the machine at that time. (I am a little unsure, though, as it's a build-server, and I don't have any way of telling who else might've submitted a build job to the machine at that time. It was ~1AM on a Saturday, though, so probably just me). Also, the .so file generated was 925MB, if that's of any interest.

Should I worry at all that the tarball represents a WIP in terms of the actual integral files? Or does the trial status only regard the  configuration?

**Comment by loriab** [comment]
> Three hours and nine minutes, according to the timestamps I have for relevant events. I believe the build ran on a 32-thread (16-core) intel broadwell (with ample memory to avoid paging, for however much that helps), and the build was the only event happening on the machine at that time. (I am a little unsure, though, as it's a build-server, and I don't have any way of telling who else might've submitted a build job to the machine at that time. It was ~1AM on a Saturday, though, so probably just me). Also, the .so file generated was 925MB, if that's of any interest.

Thanks for the info. It must be the Intel compiler and multiarch flags that lengthen my builds by an order of magnitude.

> Should I worry at all that the tarball represents a WIP in terms of the actual integral files? Or does the trial status only regard the configuration?

I expect the integral files in that tarball to be perfectly good. I've checked my local diff again, and nothing else should be harmful. One caveat is that the integrals author generally dissuades building AM>7, so I had to defeat those checks, but I know people who have built higher than that tarball (albeit different versions of the code) without known ill effects. If you've got an `.so`, and psi4 passes a few tests, I think you're good to go.

**Comment by JonathonMisiewicz** [comment]
It doesn't look like there's anything for developers to do here, so I'm marking the issue closed.

There are quite a few reports of build issues lately, so let's clean up the one that are already solved.
