### ISSUE TITLE
Wavefunction pass issues for 1.0 release

### ISSUE THREAD

**Issue by dgasmith** [psi4/psi4#259]
This is the list of issues tied into wavefunction_pass that should be cleared up before the 1.0 release.

* [x] Methods also take the `molecule` kwarg, it is not clear if `ref_wfn` or `molecule` should supersede the other yet (SCF methods can only take a molecule at the moment. `ref_wfn` supersedes `molecule` in all other methods.).
* [x] Not all methods return wavefunctions yet. For example what does a SAPT wavefunction look like?
    * [x] psimrcc Wavefunction
    * [x] SAPT Wavefunction
    * [x] EFP Wavefunction
    * [x] Will just pass through the reference wavefunction with a warning
* [x] If I pass SCF a `ref_wfn` with orbitals, the `ref_wfn` orbitals are not used (Thats fine, see above).
* [ ] We would like a SCF level wavefunction to be able to cast itself back C1 symmetry so that we can run symmetry-based SCF and then use this wavefunction in symmetry intolerant code. These transforms are reimplemented in every symmetry tolerant code. (Moved to another ticket)
* [ ] Saving of binary `optking` information may break for very complex optimizations (database, cbs wrapper, etc). Optimization proceeds, but always restarts at the first iteration so convergence is slow. (Moved to another ticket)
* [x] Plugin examples are starting to show their age. We probably need to overhaul these.
* [x] The documentation needs to reflect the above changes (see #249).
* [x] DF and RI calls should soft fail with a proper error message.
* [x] Cubeprop, Molden, OEProp etc functions should fail better when not passed a wavefunction.

**Comment by jgonthier** [comment]
On the SAPT wavefunction: right now, we do not know what SAPT should return. I see that you have added an error message reading "SAPT incomplete wavefunction is only dimer SCF", which is a bit confusing because at first I thought SAPT had a problem *reading* the wavefunction in. Maybe a message reading "SAPT returns incomplete wavefunction, only dimer SCF" would be better.

Also, I don't think SAPT can meaningfully return a wavefunction, at least not in its current state... Do you think it would be better if methods like that just returned an empty structure or the equivalent of a NULL pointer in Python ?

**Comment by dgasmith** [comment]
@jgonthier We could return a `None` object in python, but with the way wavefunction passing works its probably best to return _something_. We could also return a blank wavefunction, but the SCF does have meaningful information. Its a hard call and part of the reason why we didnt solve it during the wavefunction_pass work. Any opinions are greatly appreciated!

The comments do need an overhaul. We would like the message to print only if `return_wfn=True`, but we have not yet figured out the mechanics to do that cleanly.

**Comment by jgonthier** [comment]
@dgasmith I think right now returning the dimer SCF wavefunction is fine. It gives the user easy access to it in case more computations are required. If there are other requests from users/developers in the future we could consider it.

**Comment by lothian** [comment]
Are all of these really necessary for a 1.0 release?  Some of them seem to me to be design-/feature-related issues that could wait until 1.X or 1.0.X.   For example, are we worried at this point that general users are going to run EFP calculations?

**Comment by fevangelista** [comment]
I'll work on psimrcc.

**Comment by dgasmith** [comment]
@lothian For EFP I would argue that we should figure out the corner case now while were thinking about it as they are likely to come up again in the future. If we simple pass through the SCF Wavefunction or a blank Wavefunction for these, thats fine. But we need to make it a rule.

@fevangelista By the same token psimrcc doesn't need a Wavefunction if you are ok with the default behavior for Wavefunction-less methods.

I could see moving the C1 symmetry conversion to a later date (David has already strongly encouraged me to think about overhauling the Wavefunction class). Everything else I would want in a 1.0 release as they are enhancements that will prevent additional forum posts (documentation, softer fails, and plugins using modern Psi programming practice) or what I would call logical flow* issues (passing orbitals to SCF, what wavefunction is returned).

*Logical flow: If an advanced user is used to certain mechanics working it is quite jarring when a conventional call suddenly does not work for no apparent reason.

**Comment by loriab** [comment]
On the wavefunction return for efp, psimrcc, sapt issue, it's not going to matter much to the simple operation of these methods. But now `gradient()`, `hessian()`, etc. rely on functions from proc.py to return a Wavefunction, so the generic driver machinery of analytic vs. findif derivatives is going to be broken. Hence the case for deciding/agreeing now what to do about these corner cases. I think a sensible thing is just to return the scf Wfn (I already did that for MRCC, which should be in that discussion list, too), leaving pure EFP as still an oddity.

**Comment by fevangelista** [comment]
@dgasmith: psimrcc does not compute NOs or change orbitals/integrals/etc so I am fine with both solutions.  I prefer to pass back the RHF wfn or whatever alternative solution that does not to break the ability to do numerical optimization, since we actually use this feature.  I'll be glad to work on psimrcc once we settle on a solution.
