### ISSUE TITLE
New Conda environment is failing with version 1.5

### ISSUE THREAD

**Issue by bannanc** [psi4/psi4#2593]
Hello, 
I work at OpenEye Scientific Software where we use psi4 in a couple of our products. This week one of our development packages started failing for no reason I could identify. We have been working with version 1.5, planning to deploy our packages with that next week (upgrading to 1.6 next time). Despite no changes I can find on your end something in the last week seems to make it impossible to build a conda environment with psi4 1.5 anymore. 

I get the same failures with a very minimal conda environment that we do on our more complex cloud platform. @zachglick is interning with my team this summer and was also able to replicate this. 
Below is the commands we used to build a new conda enviroment:
`conda create -n test_env -c conda-forge -c psi4 -c psi4 python=3.7 psi4==1.5+e9f4d6d dftd3==3.2.1 --yes`
(note, I've tried python 3.7, 3.7.12, and 3.8 on my mac)

This script results in a segmentation fault 
```
import psi4

# make output file
psi4_output = "minimal_env.dat"
print("set output file path")
psi4.set_output_file(psi4_output)

# make molecule
print("create molecule...")
molecule = psi4.geometry("""O 1.6406245231628418 2.186539888381958 0.3502783477306366
C 0.8303495645523071 1.106687068939209 0.17728924751281738
C 0.26523858308792114 0.47432053089141846 1.2845896482467651
C -0.5650492906570435 -0.6324407458305359 1.1073246002197266
C -0.8302973508834839 -1.1067066192626953 -0.17723894119262695
N -1.6608778238296509 -2.2135820388793945 -0.3546023368835449
C -2.3128416538238525 -2.9721903800964355 0.626854419708252
O -2.283581256866455 -2.8034048080444336 1.8416125774383545
C -3.1216139793395996 -4.092474460601807 0.022369852289557457
H -2.5071558952331543 -4.992997646331787 -0.06683211773633957
H -3.9806551933288574 -4.315130233764648 0.6616312265396118
H -3.4815473556518555 -3.7952513694763184 -0.9667707681655884
H -1.818267822265625 -2.5147225856781006 -1.3233563899993896
C -0.2652755677700043 -0.47430306673049927 -1.2846300601959229
C 0.5650341510772705 0.6324429512023926 -1.1073341369628906
H 1.0022953748703003 1.1210383176803589 -1.9738258123397827
H -0.46503451466560364 -0.8350303173065186 -2.2904675006866455
H -0.9999359846115112 -1.117483139038086 1.977584958076477
H 0.46812179684638977 0.8390328884124756 2.2878639698028564
H 1.9390827417373657 2.4920878410339355 -0.5236388444900513""")
molecule.set_molecular_charge(0)
molecule.set_multiplicity(1)
psi4.set_options({"reference":"uhf"})

print("calculate energy...")
energy, wfn = psi4.energy("HF3c/", return_wfn=True)
print("converting energy ...")
kcal_energy = energy * psi4.constants.hartree2kcalmol
print("energy {:.2f} kcal/mol".format(kcal_energy))
```
Specifically the output I get is 
```
set output file path
create molecule...
calculate energy...
Segmentation fault: 11
```
I tried to attach the .dat file, but github wouldn't let me, but this is end of it:
```
  ==> Algorithm <==

  SCF Algorithm Type is DF.
  DIIS enabled.
  MOM disabled.
  Fractional occupation disabled.
  Guess Type is SAD.
  Energy threshold   = 1.00e-06
  Density threshold  = 1.00e-06
  Integral threshold = 1.00e-12

  ==> Primary Basis <==

  Basis Set: MINIX
    Blend: MINIX
    Number of shells: 42
    Number of basis functions: 64
    Number of Cartesian functions: 64
    Spherical Harmonics?: true
    Max angular momentum: 1

   => Loading Basis Set <=

    Name: (MINIX AUX)
    Role: JKFIT
    Keyword: DF_BASIS_SCF
    atoms 1, 8             entry O          line   318 file /Users/cbannan/miniconda3/envs/baby_env/share/psi4/basis/def2-universal-jkfit.gbs
    atoms 2-5, 7, 9, 14-15 entry C          line   198 file /Users/cbannan/miniconda3/envs/baby_env/share/psi4/basis/def2-universal-jkfit.gbs
    atoms 6                entry N          line   258 file /Users/cbannan/miniconda3/envs/baby_env/share/psi4/basis/def2-universal-jkfit.gbs
    atoms 10-13, 16-20     entry H          line    18 file /Users/cbannan/miniconda3/envs/baby_env/share/psi4/basis/def2-universal-jkfit.gbs
```

If I use a conda environment I built a few weeks ago the script runs fine. This is the same as we are seeing on our cloud platform on AWS. Docker images built 2 weeks ago (on May 23) are running fine. But the ones we make this week (on May 31) are failing with seg faults. 

Now, I realize you all have moved on to 1.6, but we are too late in our development cycle to upgrade a dependency and our last package was built around psi4 1.3 so that is the only other version we've validated. So unfortunately if I can't track this down ASAP we will have to downgrade (even though we've seen performance improvement with the new version)

**Comment by VHchavez** [comment]
@bannanc selecting the libint2 worked for me.

**Comment by bannanc** [comment]
Thank you @loriab!!! 

I can validate that pinning libint2 fixes this on our Cloud platform as well, I'll close this case. 
Thanks again for addressing this so quickly!

**Comment by loriab** [comment]
> I can validate that pinning libint2 fixes this on our Cloud platform as well, I'll close this case.
Thanks again for addressing this so quickly!

Glad it's fixed. The Libint2 migration was bound to cause problems, so I'm glad you reported it. We started pinning psi4 conda packages to specific Libint2 builds earlier this year, so hopefully smoother future migrations.

**Comment by loriab** [comment]
@bannanc, note that the above solution only turns out to be sufficient for python 3.7. For 3.8 and 3.9, see additional packages in #2596.
