### ISSUE TITLE
Import error in Google Colab

### ISSUE THREAD

**Issue by 1heman** [psi4/psi4#2598]
Hi, 
I am trying to install and use Psi4 on Google colab but unable to do so.

Here is what I've been trying:
```
#Installing conda 
 !wget -c https://repo.anaconda.com/miniconda/Miniconda3-py37_4.12.0-Linux-x86_64.sh
!chmod +x Miniconda3-py37_4.12.0-Linux-x86_64.sh
!bash /content/Miniconda3-py37_4.12.0-Linux-x86_64.sh -bfp /usr/local

!conda install --channel defaults conda python=3.8 --yes
!conda update --channel defaults --all --yes

#Installing Psi4
!conda install psi4 python=3.8 -c psi4

import psi4
```
Error:
```
ImportError                               Traceback (most recent call last)
[<ipython-input-18-ae2916a96900>](https://localhost:8080/#) in <module>()
----> 1 import psi4

[/usr/local/lib/python3.8/site-packages/psi4/__init__.py](https://localhost:8080/#) in <module>()
     52 
     53 # Init core
---> 54 from . import core
     55 
     56 from psi4.core import get_num_threads, set_num_threads

ImportError: cannot import name 'core' from 'psi4' (/usr/local/lib/python3.8/site-packages/psi4/__init__.py)
```
[Here](https://github.com/psi4/psi4/files/8878265/conda_list.txt) is a text file that contains the results of  `conda list`

Versions in use:
Psi4: v1.6
Python: v3.8.13
conda: v4.13.0

```
which conda python psi4
/usr/local/bin/conda
/usr/local/bin/python
/usr/local/bin/psi4
```

Please suggest where I might be going wrong.

Regards,
Hemant

**Comment by loriab** [comment]
Hi, Sorry for your trouble. I haven't used Colab myself, but your commands look reasonable, and I don't see any red flags in your `conda list` (thanks for including that). Since you're seeing trouble, here's a few suggestions:
* I would ordinarily advise putting psi4 is a separate conda env, not the base one. That seems awkward in colab (has to be activated per cell!) but is a possibility, https://stackoverflow.com/questions/53031430/conda-environment-in-google-colab-google-colaboratory
* You're pulling a py37 miniconda, then updating everything, then installing a py38 psi4 into its base environment. That's not the smoothest path. I'd choose a py38 or py39 installer https://docs.conda.io/en/latest/miniconda.html#linux-installers, then don't update all the packages, and do install the psi4 of matching python.

**Comment by 1heman** [comment]
Hi, thank you very much for your response.

> I would ordinarily advise putting psi4 is a separate conda env, not the base one. That seems awkward in colab (has to be activated per cell!) but is a possibility, https://stackoverflow.com/questions/53031430/conda-environment-in-google-colab-google-colaboratory

I tried this and am able to install psi4 and even import it without any errors.

[psi4-test.txt](https://github.com/psi4/psi4/files/8883628/psi4-test.txt) contains the results of `psi4 --test`
kindly let me know if this mean that psi4 is in functional state.
Here is the `conda list` output in case it is needed.
[psi4-env_conda-list.txt](https://github.com/psi4/psi4/files/8883643/psi4-env_conda-list.txt)

Now I have some compatibility issues against python3.8 but that's with other packages I am trying to use.

Just to make sure, psi4 is no longer supported on python3.7, right?

**Comment by JonathonMisiewicz** [comment]
> [psi4-test.txt](https://github.com/psi4/psi4/files/8883628/psi4-test.txt) contains the results of `psi4 --test` kindly let me know if this mean that psi4 is in functional state. Here is the `conda list` output in case it is needed. [psi4-env_conda-list.txt](https://github.com/psi4/psi4/files/8883643/psi4-env_conda-list.txt)

Yes, the base Psi4 is functional. All the messages about skipped tests indicate that there are addons that Psi4 _has_ but that your Psi4 installation isn't detecting as installed. Based on your conda list, these are probably not installed, so this behavior is expected.

Let us know if there are addons that you need but don't know how to get. (Examples: `dftd4` for DFT dispersion corrections, `cct3` for some exotic coupled cluster variants, `cppe` for polarizable embedding.)

> Now I have some compatibility issues against python3.8 but that's with other packages I am trying to use.
> 
> Just to make sure, psi4 is no longer supported on python3.7, right?

The latest Psi4 is no longer supported on Python 3.7, correct. If you need 3.7 support, dropping down to Psi4 1.5 is technically an option.

**Comment by 1heman** [comment]
Hi @JonathonMisiewicz 
Thank you for your response

> Let us know if there are addons that you need but don't know how to get. (Examples: dftd4 for DFT dispersion corrections, cct3 for some exotic coupled cluster variants, cppe for polarizable embedding.)

I am using psi4 through geomeTRIC to minimize the structures of small molecules.
The other dependencies which I had mentioned earlier was to generate the input file (.in file) for the minimization
`geometric-optimize --psi4 <input.in>`

I am able to do this as long as I provide the `input.in` file, i.e. psi4 is working just fine for me.

So thanks a lot @loriab and @JonathonMisiewicz
