### ISSUE TITLE
OEProp error on Mac

### ISSUE THREAD

**Issue by dr-nate** [psi4/psi4#260]
Hi all,

I just built Psi4 on mac os x, and everything seem to build and test fine. However, in doing a calculation I received the following error: 

```
An error has occurred Py-side
Traceback:
<class 'Boost.Python.ArgumentError'>: Python argument types in
    OEProp.__init__(OEProp, str)
did not match C++ signature:
    __init__(_object*, boost::shared_ptr<psi::Wavefunction>):   File "<string>", line 28, in <module>

  File "/usr/local/psi4/share/psi4/python/p4util/util.py", line 41, in oeprop
    oe = psi4.OEProp(wfn)
```

Input was:
```
import psi4

molecule {
  C            0.012220093121    -0.717626540721     0.000000000000
  O           -0.062545506204     0.679938040344     0.000000000000
  H            0.518735639503    -1.098516178616     0.883563931671
  H            0.518735639503    -1.098516178616    -0.883563931671
  H           -1.002097021106    -1.091505681690     0.000000000000
  H            0.811765758420     1.042084199023     0.000000000000
}

set globals {
  basis 6-31g*
}

energy('scf')
oeprop("MULLIKEN_CHARGES")
```
Commenting out the `oeprop` line not surprisingly gets rid of the error. 

I doubt any of the rest of this matters, but...

I did get two errors building, in case they're relevant, but I've seen them in other open issues:
```
The following tests FAILED:
	254 - pywrap-opt-sowreap (Failed)
	263 - sapt4 (Failed)
Errors while running CTest
make: *** [test] Error 8
```
Command used to configure: `./setup -DBUILD_CUSTOM_BOOST=TRUE --python /usr/bin/python objdir`
Compiler: gcc/g++/gfortran from hpc.sourceforge.net
OS: OS  X 10.10.5

**Comment by dgasmith** [comment]
Yes, we have recently pushed a very large update to how data handling is passed in Psi4. Please change you output to the following:

```python
scf_e, scf_wfn = energy('scf', return_wfn=True)
oeprop(scf_wfn, "MULLIKEN_CHARGES")
```

Effectively, there is no longer a global wavefunction and you must explicitly pass wavefunctions around. Sowreap should fail at the moment (has not had a wavefunction_pass update yet). Can you please post the sapt4 error and the git reference hash?

**Comment by dr-nate** [comment]
Ok, thanks. Should I open a different issue for the sapt4 error?

**Comment by dgasmith** [comment]
I think we have fixed this already, but I just want to double check. Please post everything here.

**Comment by dr-nate** [comment]
```
sapt4
2016-02-16 10:46
SAPT incomplete wavefunction is only dimer SCF
        SAPT Elst: computed value (-0.0407577) does not match (-0.0407606) to 6 decimal places.

An error has occurred Py-side
Traceback:
<class 'p4xcpt.TestComparisonError'>:   SAPT Elst: computed value (-0.0407577) does not match (-0.0407606) to 6 decimal places.:   File "<string>", line 67, in <module>

  File "/Users/stanlen1/gitrepos/psi4/share/python/p4util/util.py", line 100, in compare_values
    raise TestComparisonError(message)
```

**Comment by dgasmith** [comment]
Great, thanks for this. I just pushed a change that will fix this test case.

@jgonthier We both attempted to fix sapt4 in two different ways, the merge accepted both fixes which consequently broke the test case again. I reverted to your way of doing this.

**Comment by jgonthier** [comment]
Ahah, indeed. Thanks for fixing it. I will not attempt to un-fix it again.
