### ISSUE TITLE
[QUESTION] No concurrency when running psi4 from command line?

### ISSUE THREAD

**Issue by coltonbh** [psi4/psi4#2600]
This is more of a discussion than an issue, but posting here in case this is considered a bug.

Issue: Running `psi4` from the command line results in dramatically different performance than calling it from the command line with `qcengine`. Why is that? Is this intended?

`psi4` was installed via `conda`, note the results below. They suggest that `psi4` runs on a single core when called from the command line, yet multiple cores when called from `qcengine`. Is this intended? A bug? The `qcengine` call is ~3.5x faster.

```sh
time qcengine run psi4 caffeine.json > qcng_out.json
qcengine run psi4 caffeine.json > qcng_out.json  44.65s user 1.51s system 574% cpu 8.041 total
time psi4 --qcschema -i caffeine.json -o psi4_out.json                 
psi4 --qcschema -i caffeine.json -o psi4_out.json  29.30s user 0.63s system 99% cpu 29.952 total
```

The outfiles are attached in case helpful. They are .json files, but had to name them .txt so GitHub would allow an upload.

[qcng_out.txt](https://github.com/psi4/psi4/files/8880533/qcng_out.txt)
[psi4_out.txt](https://github.com/psi4/psi4/files/8880534/psi4_out.txt)

Thanks!

**Comment by loriab** [comment]
From psi4 command-line, default cores is 1 and more added by `-n <cores>`. From qcengine, default is all-the-machine-has and user adjusted by `local_options` (maybe name changed).

The former is a traditional research code expectation and reasoning -- this is a cutting-edge and semistable code that I'm going to run cautiously at first before trying for speed. The latter is more consumer software expectation -- do your fastest on the resources available.

Would that explain what you're seeing?

**Comment by coltonbh** [comment]
Can confirm `qcengine` uses the number of physical cores on a machine by default, as seen [here](https://github.com/MolSSI/QCEngine/blob/c171e80c51afc5bc08ac8a84971b526fd33671d3/qcengine/config.py#L43-L46).

Running psi4 with `8` threads (I have 8 logical CPU cores) produces similar performance:

```sh
time qcengine run psi4 caffeine.json > qcng_out.json                                                                         
qcengine run psi4 caffeine.json > qcng_out.json  45.94s user 1.78s system 578% cpu 8.249 total
time psi4 -n 8 --qcschema -i caffeine.json -o psi4_out.json                                                      
psi4 -n 8 --qcschema -i caffeine.json -o psi4_out.json  67.32s user 1.73s system 680% cpu 10.142 total
time psi4 -n 8 --qcschema -i caffeine.json -o psi4_out.json                                              
psi4 -n 8 --qcschema -i caffeine.json -o psi4_out.json  53.52s user 1.06s system 701% cpu 7.781 total
```
