### ISSUE TITLE
PsiException: Could not converge geometry optimization in 50 iterations.

### ISSUE THREAD

**Issue by hima111997** [psi4/psi4#2604]
i was trying to run this .py file https://drive.google.com/file/d/1ANj_pWq6d2fDPu9p-SiASfDNyfhjBsBc/view?usp=sharing to optimize a structure, but in the .out file it said:
PsiException: Could not converge geometry optimization in 50 iterations.

this is the .out file: https://drive.google.com/file/d/1bCCWFvOhAA1z6tezxysS-ktDSD0_88UC/view?usp=sharing
how can i solve this?

**Comment by JonathonMisiewicz** [comment]
We discuss this in the "geometry optimization" [page of the documentation](https://psicode.org/psi4manual/master/optking.html). Please check the documentation before filing issues.
