### ISSUE TITLE
ADIIS Minimization Fail

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#2609]
We have an [example](http://forum.psicode.org/t/adiis-minimization-failed-file-a-bug/2524/4) of an ADIIS failure. Based on how _early_ minimization is failing, this looks like something other than numerical finickiness of the underlying numpy algorithm. The ADIIS problem is either 1-by-1 or 2-by-2 (I'd need to check which), and surely we can handle a 2D constrained optimization.

```
memory 5 gb

molecule dimer {
 O   -2.37598501   -5.25644515    4.84543259
 H   -2.38171765   -4.38257907    4.44628561
 H   -2.48821382   -4.94837176    5.80344789
--
 @Br   2.24215713   -6.77867982    5.71107037
 @Br   0.05511550   -6.05660413    5.30313985
   units angstrom
}

set {
    basis         aug-cc-pvdz
    scf_type      pk  
    sapt_dft_grac_shift_a 0.05731
    sapt_dft_grac_shift_b 0.01680
    SAPT_DFT_FUNCTIONAL REVSCAN
}

energy('revscan')
```

```
  ==> Pre-Iterations <==

  SCF Guess: Superposition of Atomic Densities via on-the-fly atomic UHF (no occupation information).

   -------------------------
    Irrep   Nso     Nmo
   -------------------------
     A        113     113
   -------------------------
    Total     113     113
   -------------------------

  ==> Iterations <==

                        Total Energy        Delta E     RMS |[F,P]|

   @RKS iter SAD:   -76.04124004396280   -7.60412e+01   0.00000e+00

Traceback (most recent call last):
  File "/Users/jonathonmisiewicz/psi4/objdir/stage/bin//psi4", line 338, in <module>
    exec(content)
  File "<string>", line 35, in <module>
  File "/Users/jonathonmisiewicz/psi4/objdir/stage/lib/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/Users/jonathonmisiewicz/psi4/objdir/stage/lib/psi4/driver/procrouting/proc.py", line 2455, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/Users/jonathonmisiewicz/psi4/objdir/stage/lib/psi4/driver/procrouting/proc.py", line 1670, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/Users/jonathonmisiewicz/psi4/objdir/stage/lib/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 86, in scf_compute_energy
    self.iterations()
  File "/Users/jonathonmisiewicz/psi4/objdir/stage/lib/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 412, in scf_iterate
    for engine_used in self.diis(Dnorm):
  File "/Users/jonathonmisiewicz/psi4/objdir/stage/lib/psi4/driver/procrouting/scf_proc/subclass_methods.py", line 111, in _RHF_diis
    return self.diis_manager_.extrapolate(self.Fa(), Dnorm=Dnorm)
  File "/Users/jonathonmisiewicz/psi4/objdir/stage/lib/psi4/driver/procrouting/diis.py", line 407, in extrapolate
    coeffs = m * initial_coefficient_function() + (1 - m) * self.diis_coefficients()
  File "/Users/jonathonmisiewicz/psi4/objdir/stage/lib/psi4/driver/procrouting/diis.py", line 288, in adiis_coefficients
    raise Exception("ADIIS minimization failed. File a bug, and include your entire input and output files.")

Exception: ADIIS minimization failed. File a bug, and include your entire input and output files.
```

**Comment by JonathonMisiewicz** [comment]
Upon further investigation, the combination of `revSCAN` and ghost atoms is causing the Fock matrix to be filled with `NaN`. ADIIS is innocent. _Why_ this specific combination is a problem isn't obvious.

**Comment by susilehtola** [comment]
> Upon further investigation, the combination of `revSCAN` and ghost atoms is causing the Fock matrix to be filled with `NaN`. ADIIS is innocent. _Why_ this specific combination is a problem isn't obvious.

SCAN (and thereby revSCAN) is a famously horrendous functional from the point of view of numerical stability. I bet it has something to do with the ghost atoms that result in the inclusion of lots of far-lying points with low density.

I am not sure why revSCAN would give out NaNs, though; I thought we had sorted out NaN issues with most of our functionals, including the SCAN family.

**Comment by JonathonMisiewicz** [comment]
I indeed found that removing the augmented basis functions or turning ghost atoms to regular atoms cured the NaN, both of which support "lots of far-lying points with low density" as being the problem.

**Comment by susilehtola** [comment]
> I indeed found that removing the augmented basis functions or turning ghost atoms to regular atoms cured the NaN, both of which support "lots of far-lying points with low density" as being the problem.

The first thing you might try in this case is overriding the default density threshold in Libxc, which is set to `1e-15` for revSCAN.

I believe the DFT grid code in Psi4 has its own screening thresholds; ideally, the thresholds should go hand in hand with Psi4 and Libxc. Typical quantum chemistry codes threshold densities smaller than `1e-10` or `1e-11`; Libxc uses very conservative thresholds since it's supposed to work with all kinds of  numerical approaches...

**Comment by JonathonMisiewicz** [comment]
As in, tell LibXC to use a _larger_ threshhold, so it screens more points? Where exactly do I do that? Again, I'm not familiar with the DFT part of the codebase.

**Comment by hokru** [comment]
Use `DFT_DENSITY_TOLERANCE` to overwrite the LibXC defaults, psi4 itself does not screen out small densities right now.
