### ISSUE TITLE
Psi4 v1.6 installation issue Windows, conda, Python 3.8

### ISSUE THREAD

**Issue by cheekyleo** [psi4/psi4#2614]
When following the suggested path for installation on Windows using conda and Python 3.8, even setting up a new environment on version 3.8, I cannot get it to run, as the "psi4 --test" command gives an error.

On WSL using either conda or the installer I also cannot get it to work.
I create a new environment with: 
```
conda create -n psi16 python=3.8
conda activate psi16
conda update --all
conda install psi4 python=3.8 -c psi4 -c conda-forge
psi4 --test
```

This error was encountered on two separate machines running up to date Windows 10 Pro.

Running the test gives me the following error: 
Traceback (most recent call last):
  File "Path\psi4conda\envs\psi16\Scripts\psi4-script.py", line 187, in <module>
    import psi4  # isort:skip
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\__init__.py", line 76, in <module>
    from .driver import endorsed_plugins
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\__init__.py", line 46, in <module>
    from psi4.driver.molutil import *
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\molutil.py", line 36, in <module>
    from psi4.driver.p4util import temp_circular_import_blocker
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\p4util\__init__.py", line 32, in <module>
    from .util import *
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\p4util\util.py", line 37, in <module>
    from psi4.driver.procrouting import *
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\procrouting\__init__.py", line 29, in <module>
    from .proc_table import procedures, hooks, energy_only_methods, integrated_basis_methods
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\procrouting\proc_table.py", line 32, in <module>
    from . import sapt
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\procrouting\sapt\__init__.py", line 29, in <module>
    from .sapt_proc import run_sapt_dft, sapt_dft, run_sf_sapt
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\procrouting\sapt\sapt_proc.py", line 36, in <module>
    from psi4.driver.procrouting.proc import scf_helper
  File "Pathpsi4conda\envs\psi16\lib\site-packages\psi4\driver\procrouting\proc.py", line 55, in <module>
    from . import proc_util
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\procrouting\proc_util.py", line 38, in <module>
    from psi4.driver.procrouting.sapt import fisapt_proc
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\procrouting\sapt\fisapt_proc.py", line 34, in <module>
    from .. import empirical_dispersion
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\procrouting\empirical_dispersion.py", line 38, in <module>
    from psi4.driver import driver_findif
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\driver_findif.py", line 153, in <module>
    from psi4.driver.task_base import AtomicComputer, BaseComputer, EnergyGradientHessianWfnReturn
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\task_base.py", line 67, in <module>
    class AtomicComputer(BaseComputer):
  File "Path\psi4conda\envs\psi16\lib\site-packages\psi4\driver\task_base.py", line 75, in AtomicComputer
    keywords: Dict[str, Any] = Field(default_factory=dict, description="The keywords to use in the computation.")
TypeError: Field() missing 1 required positional argument: 'default'

**Comment by JonathonMisiewicz** [comment]
Post the results of `conda list`. I suspect your version of `pydantic` is severely outdated.

**Comment by cheekyleo** [comment]
This is the output and pydantic has version 1.3. How can it be that "conda update --all", or a fresh install for that matter, would not give me the up-to-date version?
 
# Name                    Version                   Build  Channel
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.6.15            h5b45459_0    conda-forge
certifi                   2022.6.15        py38haa244fe_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
dftd3                     3.2.1                         1    psi4
gau2grid                  2.0.7                hcb41399_1    conda-forge
gcp                       2.0.2                         0    psi4
importlib-metadata        4.11.4           py38haa244fe_0    conda-forge
importlib_metadata        4.11.4               hd8ed1ab_0    conda-forge
importlib_resources       5.8.0              pyhd8ed1ab_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
intel-openmp              2019.1                      144
libblas                   3.8.0                     8_mkl    conda-forge
libcblas                  3.8.0                     8_mkl    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libint2                   2.6.0                h2e52968_4    psi4
liblapack                 3.8.0                     8_mkl    conda-forge
libxc                     5.2.3            py38h294d835_1    conda-forge
libzlib                   1.2.12               h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mkl                       2019.1                      144
msgpack-python            1.0.4            py38hbd9d945_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
networkx                  2.8.4              pyhd8ed1ab_0    conda-forge
numpy                     1.22.4           py38h1d2777f_0    conda-forge
openssl                   3.0.3                h8ffe710_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pint                      0.17               pyhd8ed1ab_0    psi4
pip                       21.2.2           py38haa95532_0
pluggy                    1.0.0            py38haa244fe_3    conda-forge
psi4                      1.6+77475b5              py38_0    psi4
psutil                    5.9.1            py38h294d835_0    conda-forge
py                        1.11.0             pyh6c4a22f_0    conda-forge
py-cpuinfo                8.0.0              pyhd8ed1ab_0    conda-forge
pydantic                  1.3              py38hfa6e2cd_0    psi4
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pytest                    7.1.2            py38haa244fe_0    conda-forge
python                    3.8.13          hcf16a7b_0_cpython    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pyyaml                    6.0              py38h294d835_4    conda-forge
qcelemental               0.17.0                     py_0    psi4
qcengine                  0.19.0             pyhd8ed1ab_0    psi4
scipy                     1.8.1            py38h9bf8e03_0    conda-forge
setuptools                61.2.0           py38haa95532_0
sqlite                    3.38.3               h2bbff1b_0
tk                        8.6.12               h8ffe710_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.37.1             pyhd3eb1b0_0
wincertstore              0.2              py38haa95532_2
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge

**Comment by JonathonMisiewicz** [comment]
At this point, the issue needs @loriab attention.

**Comment by cheekyleo** [comment]
@JonathonMisiewicz I now edited the post before and added what doing psi4 --test and running a job outputs for me.

**Comment by loriab** [comment]
It can help to let conda know all at once what you need the environment to solve for by `conda create -n psi16 psi4 python=3.8 -c psi4 -c conda-forge` (delete existing env when prompted). Please give that a try and post `conda list` again.

**Comment by cheekyleo** [comment]
I ran your command but I get pydantic v1.3 again by default. Here is the output of `conda list`:

```
# Name                    Version                   Build  Channel
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.6.15            h5b45459_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
dftd3                     3.2.1                         1    psi4
gau2grid                  2.0.7                hcb41399_1    conda-forge
gcp                       2.0.2                         0    psi4
importlib-metadata        4.11.4           py38haa244fe_0    conda-forge
importlib_metadata        4.11.4               hd8ed1ab_0    conda-forge
importlib_resources       5.8.0              pyhd8ed1ab_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
intel-openmp              2019.1                      144
libblas                   3.8.0                     8_mkl    conda-forge
libcblas                  3.8.0                     8_mkl    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libint2                   2.6.0                h2e52968_4    psi4
liblapack                 3.8.0                     8_mkl    conda-forge
libxc                     5.2.3            py38h294d835_1    conda-forge
libzlib                   1.2.12               h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mkl                       2019.1                      144
msgpack-python            1.0.4            py38hbd9d945_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
networkx                  2.8.4              pyhd8ed1ab_0    conda-forge
numpy                     1.22.4           py38h1d2777f_0    conda-forge
openssl                   3.0.3                h8ffe710_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pint                      0.17               pyhd8ed1ab_0    psi4
pip                       22.1.2             pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0            py38haa244fe_3    conda-forge
psi4                      1.6+77475b5              py38_0    psi4
psutil                    5.9.1            py38h294d835_0    conda-forge
py                        1.11.0             pyh6c4a22f_0    conda-forge
py-cpuinfo                8.0.0              pyhd8ed1ab_0    conda-forge
pydantic                  1.3              py38hfa6e2cd_0    psi4
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pytest                    7.1.2            py38haa244fe_0    conda-forge
python                    3.8.13          hcf16a7b_0_cpython    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pyyaml                    6.0              py38h294d835_4    conda-forge
qcelemental               0.17.0                     py_0    psi4
qcengine                  0.19.0             pyhd8ed1ab_0    psi4
scipy                     1.8.1            py38h9bf8e03_0    conda-forge
setuptools                62.6.0           py38haa244fe_0    conda-forge
sqlite                    3.38.5               h8ffe710_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
```

**Comment by cheekyleo** [comment]
Awesome, thanks for finding that out! I will then set up a new environment and hopefully all will run fine from then

**Comment by imreal0419** [comment]
hi!! i'm still stuck in this. what did you guys do? thanks

**Comment by loriab** [comment]
Can you clarify what you're stuck at? For the old qcelemental/pydantic problem, the solution is channel order `-c conda-forge -c psi4`. I have noticed today some problems with the newest NumPy 1.23. Personal-scope solution there is to request 1.22.

**Comment by imreal0419** [comment]
still getting the same error after running the following:

conda create -n psi16 python=3.8
conda activate psi16
conda update --all
conda install psi4 python=3.8 -c psi4 -c conda-forge -c psi4
psi4 --test

:(

**Comment by imreal0419** [comment]
also do we have to do the scratch step? or if this works already we can run simulation? 

like 

psi4 input.dat output.dat in anaconda?

**Comment by imreal0419** [comment]
sorry i'm new to this and i've been having trouble with installing and running psi4 on Windows

**Comment by loriab** [comment]
Showing conda your priorities by creating and solving in one cmd is always preferred, like in https://github.com/psi4/psi4/issues/2614#issuecomment-1160572820 only with channel order reversed. I'd need `conda list` to comment further.

Yes, you can run calcs before setting `PSI_SCRATCH`. But it's strongly recommended be fore running serious jobs, _especially_ if any networked filesystems are involved.

**Comment by imreal0419** [comment]
![conda_list](https://user-images.githubusercontent.com/108773955/177454432-ca60b4b3-00bd-4d21-9b55-d669c6872900.jpg)
![conda_list2](https://user-images.githubusercontent.com/108773955/177454438-4b95c12d-c119-4f8c-937e-694432be1cc4.jpg)
![conda_list3](https://user-images.githubusercontent.com/108773955/177454470-413f6064-bccf-4a59-aded-27ad5d2ba971.jpg)

**Comment by imreal0419** [comment]
how do you mean channel order reversed? :((

**Comment by loriab** [comment]
At a glance, your `conda list` is fine, though you should always copy the text from screen and paste within triple backticks for formatting rather than post screenshots.

> how do you mean channel order reversed? :((

`conda create -n psi16 psi4 python=3.8 -c psi4 -c conda-forge` with "channel order reversed" makes `conda create -n psi16 psi4 python=3.8 -c conda-forge -c psi4`.

"same error" is hard to diagnose -- you'd have to post the solve-time or run-time error.

**Comment by imreal0419** [comment]
heya it says 40 passed, 51 skipped, 4026 deselected, 1x failed in 283.19s (0:04:43)

also how do you copy paste i try the ctrl+shift+c but it doesn't look as it should

thanks :D

**Comment by loriab** [comment]
> heya it says 40 passed, 51 skipped, 4026 deselected, 1x failed in 283.19s (0:04:43)

no failed or errors, so it seems to be working fine. https://docs.pytest.org/en/7.1.x/how-to/output.html?highlight=xpass#producing-a-detailed-summary-report

> also how do you copy paste i try the ctrl+shift+c but it doesn't look as it should

you'd have to look that up for your OS and terminal
