### ISSUE TITLE
psi4-0.5 & the intel compiler

### ISSUE THREAD

**Issue by SebWouters** [psi4/psi4#262]
Hi all,

I've tried to build psi4-0.5 with the intel compiler but it fails.

Config:

     CXX=icpc CC=icc cmake .. -DENABLE_PLUGINS=ON -DENABLE_CHEMPS2=ON
     -- The CXX compiler identification is Intel 16.0.0.20150815
     -- The C compiler identification is Intel 16.0.0.20150815
     -- Check for working CXX compiler: /opt/intel/compilers_and_libraries_2016.0.109/linux/bin/intel64/icpc
     -- Check for working CXX compiler: /opt/intel/compilers_and_libraries_2016.0.109/linux/bin/intel64/icpc -- works
     -- Detecting CXX compiler ABI info
     -- Detecting CXX compiler ABI info - done
     -- Check for working C compiler: /opt/intel/compilers_and_libraries_2016.0.109/linux/bin/intel64/icc
     -- Check for working C compiler: /opt/intel/compilers_and_libraries_2016.0.109/linux/bin/intel64/icc -- works
     -- Detecting C compiler ABI info
     -- Detecting C compiler ABI info - done
     -- Performing Test _HAS_CXX11_FLAG
     -- Performing Test _HAS_CXX11_FLAG - Success
     -- Found following supported C++11 features:
     --   __func__
     --   auto
     --   auto_ret_type
     --   constexpr
     --   cstdint
     --   decltype
     --   initializer_list
     --   lambda
     --   long_long
     --   nullptr
     --   rvalue-references
     --   sizeof_member
     --   static_assert
     --   variadic_templates
     -- Checking for restrict keyword
     --    keyword found : __restrict__
     -- Performing Test has_xHost
     -- Performing Test has_xHost - Success
     -- Try OpenMP C flag = [-qopenmp]
     -- Performing Test OpenMP_FLAG_DETECTED
     -- Performing Test OpenMP_FLAG_DETECTED - Success
     -- Try OpenMP CXX flag = [-qopenmp]
     -- Performing Test OpenMP_FLAG_DETECTED
     -- Performing Test OpenMP_FLAG_DETECTED - Success
     -- Found OpenMP: -qopenmp  
     -- Math lib search order is MKL;ESSL;ATLAS;ACML;SYSTEM_NATIVE
     -- You can select a specific type by defining for instance -D BLAS_TYPE=ATLAS or -D LAPACK_TYPE=ACML
     -- or by redefining MATH_LIB_SEARCH_ORDER
     -- BLAS will be searched for based on MKLROOT=/opt/intel/compilers_and_libraries_2016.0.109/linux/mkl
     -- Found BLAS: MKL (-Wl,--start-group;/opt/intel/compilers_and_libraries_2016.0.109/linux/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/compilers_and_libraries_2016.0.109/linux/mkl/lib/intel64/libmkl_intel_thread.so;/opt/intel/compilers_and_libraries_2016.0.109/linux/mkl/lib/intel64/libmkl_core.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libm.so;-openmp;-Wl,--end-group)
     -- LAPACK will be searched for based on MKLROOT=/opt/intel/compilers_and_libraries_2016.0.109/linux/mkl
     -- Found LAPACK: MKL (-Wl,--start-group;/opt/intel/compilers_and_libraries_2016.0.109/linux/mkl/lib/intel64/libmkl_lapack95_lp64.a;/opt/intel/compilers_and_libraries_2016.0.109/linux/mkl/lib/intel64/libmkl_intel_lp64.so;-openmp;-Wl,--end-group)
     INFO: build type was not defined, using type "Debug".
     -- Found libutil: /usr/lib/x86_64-linux-gnu/libutil.so  
     -- Found libm: /usr/lib/x86_64-linux-gnu/libm.so  
     -- Found librt: /usr/lib/x86_64-linux-gnu/librt.so  
     -- Found libdl: /usr/lib/x86_64-linux-gnu/libdl.so  
     -- Looking for include file pthread.h
     -- Looking for include file pthread.h - found
     -- Looking for pthread_create
     -- Looking for pthread_create - found
     -- Found Threads: TRUE  
     -- Found PythonInterp: /usr/bin/python (found version "2.7.10") 
     -- Found Python: /usr/lib/x86_64-linux-gnu/libpython2.7.so  
     -- Could NOT find Boost
     -- Boost 1.55.0 not found. The pre-packaged version will be built.
     --   Libraries to be built: filesystem, python, regex, serialization, system, timer, chrono, thread
     --   Toolset to be used: intel-linux
     -- CheMPS2 not found. The pre-packaged version will be built.
     -- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
     -- Plugins support ENABLED
     -- Looking for MKL_Free_Buffers
     -- Looking for MKL_Free_Buffers - not found
     -- Looking for include file mm_malloc.h
     -- Looking for include file mm_malloc.h - found
     -- Looking for __builtin_expect
     -- Looking for __builtin_expect - not found
     -- Looking for __builtin_prefetch
     -- Looking for __builtin_prefetch - not found
     -- Looking for __builtin_constant_p
     -- Looking for __builtin_constant_p - found
     -- Looking for erf
     -- Looking for erf - found
     -- Documentation targets available: sphinxman (html), sphinxmini (quick html), sphinxpdf (LaTeX --> PDF)
     -- Use the commands in setup_command to reproduce this build
     -- System                : Linux
     -- Processor type        : x86_64
     -- C++ compiler flags    : -DRESTRICT=__restrict__ -Xlinker -export-dynamic -fPIC -std=c++11 -qopenmp -g -O0 -debug -DDEBUG -Wall -Wuninitialized -Wno-unknown-pragmas
     -- C compiler flags      : -restrict -DRESTRICT=__restrict__ -std=c99 -fPIC -qopenmp -O0 -g -w3 -vec-report -Wall -Wuninitialized 
     -- Libraries             : -Wl,--start-group;/opt/intel/compilers_and_libraries_2016.0.109/linux/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/compilers_and_libraries_2016.0.109/linux/mkl/lib/intel64/libmkl_intel_thread.so;/opt/intel/compilers_and_libraries_2016.0.109/linux/mkl/lib/intel64/libmkl_core.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libm.so;-openmp;-Wl,--end-group;-Wl,--start-group;/opt/intel/compilers_and_libraries_2016.0.109/linux/mkl/lib/intel64/libmkl_lapack95_lp64.a;/opt/intel/compilers_and_libraries_2016.0.109/linux/mkl/lib/intel64/libmkl_intel_lp64.so;-openmp;-Wl,--end-group
     -- Definitions           : SYS_LINUX;HAS_CXX11;HAS_CXX11_FUNC;HAS_CXX11_AUTO;HAS_CXX11_AUTO_RET_TYPE;HAS_CXX11_CONSTEXPR;HAS_CXX11_CSTDINT_H;HAS_CXX11_DECLTYPE;HAS_CXX11_INITIALIZER_LIST;HAS_CXX11_LAMBDA;HAS_CXX11_LONG_LONG;HAS_CXX11_NULLPTR;HAS_CXX11_RVALUE_REFERENCES;HAS_CXX11_SIZEOF_MEMBER;HAS_CXX11_STATIC_ASSERT;HAS_CXX11_VARIADIC_TEMPLATES;HAVE_MKL_BLAS;HAVE_MKL_LAPACK;FC_SYMBOL=2;ENABLE_CHEMPS2=1;HAVE_MM_MALLOC_H
     -- Configuring done
     -- Generating done
     -- Build files have been written to: /home/seba/software/psi4-0.5/objects

Point where it fails:

     [ 45%] Building CXX object src/lib/libmints/CMakeFiles/mints.dir/basisset.cc.o
     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):
     /usr/include/c++/5/bits/stl_iterator_base_types.h(154): error: name followed by "::" must be a class or namespace name
        typedef typename _Iterator::iterator_category iterator_category;
                         ^
     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):
          detected during:
     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):
            instantiation of class "std::__iterator_traits<_Iterator, void> [with _Iterator=int]" at line 163
     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):
            instantiation of class "std::iterator_traits<_Iterator> [with _Iterator=int]" at line 98 of "/home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/regex_token_iterator.hpp"
     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):

     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):
     /usr/include/c++/5/bits/stl_iterator_base_types.h(155): error: name followed by "::" must be a class or namespace name
        typedef typename _Iterator::value_type        value_type;
                         ^
     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):
          detected during:
     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):
            instantiation of class "std::__iterator_traits<_Iterator, void> [with _Iterator=int]" at line 163
     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):
            instantiation of class "std::iterator_traits<_Iterator> [with _Iterator=int]" at line 98 of "/home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/regex_token_iterator.hpp"
     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):

     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):
     /usr/include/c++/5/bits/stl_iterator_base_types.h(156): error: name followed by "::" must be a class or namespace name
        typedef typename _Iterator::difference_type   difference_type;
                         ^
     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):
          detected during:
     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):
            instantiation of class "std::__iterator_traits<_Iterator, void> [with _Iterator=int]" at line 163
     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):
            instantiation of class "std::iterator_traits<_Iterator> [with _Iterator=int]" at line 98 of "/home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/regex_token_iterator.hpp"
     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):

     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):
     /usr/include/c++/5/bits/stl_iterator_base_types.h(157): error: name followed by "::" must be a class or namespace name
        typedef typename _Iterator::pointer           pointer;
                         ^
     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):
          detected during:
     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):
            instantiation of class "std::__iterator_traits<_Iterator, void> [with _Iterator=int]" at line 163
     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):
            instantiation of class "std::iterator_traits<_Iterator> [with _Iterator=int]" at line 98 of "/home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/regex_token_iterator.hpp"
     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):

     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):
     /usr/include/c++/5/bits/stl_iterator_base_types.h(158): error: name followed by "::" must be a class or namespace name
        typedef typename _Iterator::reference         reference;
                         ^
     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):
          detected during:
     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):
            instantiation of class "std::__iterator_traits<_Iterator, void> [with _Iterator=int]" at line 163
     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):
            instantiation of class "std::iterator_traits<_Iterator> [with _Iterator=int]" at line 98 of "/home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/regex_token_iterator.hpp"
     In file included from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive_static.hpp(30),
                 from /home/seba/software/psi4-0.5/objects/boost/include/boost/xpressive/xpressive.hpp(18),
                 from /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc(29):

     compilation aborted for /home/seba/software/psi4-0.5/src/lib/libmints/basisset.cc (code 2)
     src/lib/libmints/CMakeFiles/mints.dir/build.make:583: recipe for target 'src/lib/libmints/CMakeFiles/mints.dir/basisset.cc.o' failed
     make[2]: *** [src/lib/libmints/CMakeFiles/mints.dir/basisset.cc.o] Error 2
     CMakeFiles/Makefile2:1861: recipe for target 'src/lib/libmints/CMakeFiles/mints.dir/all' failed
     make[1]: *** [src/lib/libmints/CMakeFiles/mints.dir/all] Error 2
     Makefile:126: recipe for target 'all' failed
     make: *** [all] Error 2

With the GNU compiler (g++ (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010) it works fine. I'm just warning because many HPCs prefer the intel compiler and you might want to provide support.

Best wishes,
Sebastian

**Comment by jturney** [comment]
Thanks for the report! I happen to have an Ubuntu box with Intel and for some reason I haven't tried this yet. I'll see what I can figure out.

**Comment by jturney** [comment]
This is a known issue with the Intel compiler and gcc 5+ header files.  Even the latest Intel version 16.0.1 is affected. NERSC advises loading in gcc 4.9.x series.

References:
[Intel Forum](https://software.intel.com/en-us/forums/intel-c-compiler/topic/565143)
[Intel Fourm](https://software.intel.com/en-us/forums/intel-c-compiler/topic/591174)
[NERSC](https://www.nersc.gov/users/software/compilers/intel-fortran-c-and-c/intel-bug-reports/intel-c-compiler-error-stl-iterator-base-types-h/)

**Comment by jturney** [comment]
Intel released 2016 update 2 today (16.0.2) and it resolves this header file issue.

We may need to note this someplace for others to find: Intel C++ version 16.0.0 and 16.0.1 with GCC 5 C++ standard library has problems. Either use Intel 16.0.0 and 16.0.1 with pre-GCC 5 or update your Intel compiler to 16.0.2.

Closing the issue as it was a compiler and not a Psi4 bug.
