### ISSUE TITLE
chemps2 1.6

### ISSUE THREAD

**Issue by SebWouters** [psi4/psi4#263]
Hello,

You should be able to bump up the version of chemps2 used in psi4 to 1.6 without any other modifications. It contains many performance improvements.

In 1.7 (not released yet) there will be API changes. So the dmrgscf/dmrgci routine will need to be adapted simultaneously with the version tag. And it will also contain DMRG-CASPT2!

Best wishes,
Sebastian

**Comment by jturney** [comment]
Nice, thanks for the heads up! I'll give it a test and then get it in.
