### ISSUE TITLE
Minor docs inconsistency at MCSCF_ALGORITHM

### ISSUE THREAD

**Issue by TiborGY** [psi4/psi4#2635]
The text says

> Convergence algorithm to utilize. Two-Step, Augmented Hessian, or One-Step.

but then also

> Possible Values: TS, AH

Either "One-Step" is not implemented, in which case it should not be mentioned, or if it is, then its shorthand should be listed in the possible values.

https://psicode.org/psi4manual/master/autodoc_glossary_options_c.html#term-MCSCF_ALGORITHM-DETCI

**Comment by dgasmith** [comment]
`OS` is for one-step which I couldn't get to work in a robust manner. Please simply remove.
