### ISSUE TITLE
Numpy scipy version mismatch on default conda executable install of psi4

### ISSUE THREAD

**Issue by Ecaloota** [psi4/psi4#2661]
Hi all,

Running the following per the docs works as expected:
```
>>> conda create -n p4env psi4 -c psi4
>>> conda activate p4env
>>> psi4 --version
1.6.1
```

And I'm able to use psi4 in PsiAPI mode as expected (can run the h2o geometry opt and freq calcs) after entering a python shell. However, when I try to use Psi4 in Psithon mode like so, I obtain an error:

```
>>> psi4 -i input.dat -o output.dat
A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
```

Is this a compile issue in the Psi4 executable on conda?

In case it's helpful, I'm using a Mac (v.11.3.1) and running conda (4.12.0) with python 3.9.13. The input file I was trying to use contains:

```
memory 600 mb

molecule h2o {
  O
  H 1 0.96
  H 1 0.96 2 104.5
}

set basis cc-pVDZ
energy('scf')
```

The tests module ran 92 / 4121 tests, and two failed (test_gdma and test_psi4_cc), but these seem unrelated to the current issue.

**Comment by loriab** [comment]
Thanks for the report. I have been warned about a numpy version issue on Mac. If you haven't already, do try a `conda install numpy=1.22` in your environment and try Psi4 again.

I'd have to rebuild the Psiv 1.6.1 packages or rewrite their metadata to fix this at `conda create -n p4env psi4 -c psi4` -time. Hopefully, SciPy and Numpy will have reconciled before I get around to that.

**Comment by Ecaloota** [comment]
Thanks for the prompt reply. That fixed it!
