### ISSUE TITLE
psi4_io not defined

### ISSUE THREAD

**Issue by MiloszGrabski** [psi4/psi4#2668]
Hi,
I have created a brand new environment with psi4 1.6.1 on windows10 machine using:
```
conda create -n psi4 python=3.8
activate psi4
conda install psi4 -c conda-forge -c psi4
```
I had problems with psi4.core.be_quiet(), so I thought that maybe I need to set paths.
I tried to use psi4_io to set paths, but get an error:
```
>>>import psi4
>>>import os
>>> psi4_io.set_default_path
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'psi4_io' is not defined
```
Cheers,
M

**Comment by hokru** [comment]
It's not an exported variable. Not sure where you got it from, but internally it is:
`psi4_io = psi4.core.IOManager.shared_object()`

**Comment by MiloszGrabski** [comment]
Hi,
I cannot remember correctly as I have been digging through net in search of a [different issues](http://forum.psicode.org/t/fatal-error-psioutstream-failed-to-open-file/2572) and I came across this.
It worked your way, thanks for helping me out.
M
