### ISSUE TITLE
VERSION file contents

### ISSUE THREAD

**Issue by andysim** [psi4/psi4#271]
I just noticed that the VERSION file in the root directory contains "4.0", which is not consistent with @loriab's proposed version number system.  It looks like @robertodr added it when he did all that great work with CMake, so perhaps it's used to generate some info for the dashboard?  Either way, I think it should probably be brought into line with the new versioning scheme.

**Comment by robertodr** [comment]
Seems to be used to define `PSI_VERSION` in `cmake/ConfigVersion.cmake` @loriab is `PSI_VERSION` redefined somewhere else afterwards or is that an unused variable?

**Comment by loriab** [comment]
At _every_ recompile, `$objdir/src/bin/psi4/gitversion.h` is generated with contents below that get used in defining the output file header.

```
#define GIT_VERSION "{master} b04cdf9 "
#define PSI_VERSION "0.4.90"
```

Then either `$objdir/bin/psi4-config --version` or `$objdir/bin/psi4 --version` will yield the version.

So I don't use the `VERSION` file at all for versioning. But I haven't gotten rid of it either b/c of dashboard suspicions.

**Comment by robertodr** [comment]
Well, it's not used there either. You can safely remove that file :wink:

**Comment by andysim** [comment]
Great, thanks for the rapid feedback, Roberto.  I'll nuke the file.
