### ISSUE TITLE
quadrature grid pruning with functions broken

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#2754]
It appears that the (experimental) prune functions break the recently (PR #2743) introduced/re-activated lebedev_mapping:
https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libfock/cubature.cc#L5112 

The pruning with functions reduces the number of points arbitrarily and then the attempt to infer the order from the number of points fails. Technically no entry is found in the std::map and an error or segfault occurs.

This does **not** happen with the 'TREUTLER' or 'ROBUST' pruning as these reduce use well-defined orders for different regions.

**Comment by tallakahath** [comment]
I don't think the inferring of grid order from `lebedev_mapping` was *ever* correct, to be clear. I believe (but am not 100% sure) that the new way of gaining the information (using information from `LebedevGridMgr`) proposed in #2736 works?

I can test -- do you have a simple input I can test with my build of that patch?

**Comment by hokru** [comment]
The failing test is https://github.com/psi4/psi4/tree/master/tests/dft-pruning but also your changes won't help, the modified `npoints` do not fit any order since they were modified. One would need to try to find the closest order in the spirit of https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libfock/cubature.cc#L3645, which I do not find really helpful however.
