### ISSUE TITLE
Making DF default for OO methods

### ISSUE THREAD

**Issue by bozkaya** [psi4/psi4#279]
DF used to default for OMP2/OMP3/OMP2.5/OCEPA(0). However, CONV is default for them now due to default mp2_type/mp_type/cepa_type options. I think it would be better to choose DF as default for OO methods since all DF-OO methods have both energy and gradients (RHF and UHF) and significantly faster than conventional ones. @loriab @CDSherrill

**Comment by loriab** [comment]
The attempt at a coherent decision put basic methods `SCF_TYPE` and `MP2_TYPE` at `DF` among conv/df/cd-ness. And higher-order methods `MP_TYPE`, `CC_TYPE`, `CEPA_TYPE` at `CONV`.

OMP2 is controlled by `MP2_TYPE`, so it should still be defaulting to density-fitted. Let me know if it's not. For the higher-order OMP3/OMP2.5/OCEPA(0), CONV and DF have the same reference and gradient capabilities. For higher-order non-oo, CONV tends to be more supported.

If we set `MP_TYPE` or `CEPA_TYPE` at `DF`, then, at best, users will get different CONV or DF depending on mp2 vs. mp4 or cepa(0) vs cepa(3). Other route is to split off more `*_TYPE` options for the oo methods, whereupon they really start to proliferate.

I rather prefer to keep the defaults as they are at present (omp2 df, others conv). But will go with consensus. This message is just the background info of implications.

**Comment by bozkaya** [comment]
Thank you very much for clarifying the situation. The present convention is fine for me. My concern was for user. They may miss that we have df versions for OO methods. As you know, they generally run jobs with default options. @loriab

**Comment by loriab** [comment]
We're going to go with no change here, and people will have to do the below to get df-omp3. Can revisit as density-fitting for >mp2 becomes more generally accepted and as other modules include more df algorithms alongside conv.

```
set mp_type df
energy('omp3')
```
