### ISSUE TITLE
MP4 open-shell method not available

### ISSUE THREAD

**Issue by jturney** [psi4/psi4#282]
One of our students has been working through the Psi4Education site and one of the labs requires the user to run MP4 on boron.

If I'm reading the [managed method matrix](http://psicode.org/psi4manual/master/proc_py.html#table-managedmethods) correctly then the user should specify an ROHF reference and Psi4 will use DETCI. However we receive the following error:

Input file: [h2o_mp4.txt](https://github.com/psi4/psi4/files/148253/h2o_mp4.txt)

```
An error has occurred Py-side
Traceback:
<class 'p4xcpt.ManagedMethodError'>: select_mp4: Method 'mp4' with MP_TYPE 'CONV' and REFERENCE 'ROHF' not available:   File "<string>", line 27, in <module>

  File "/Users/jturney/Code/Chemistry/psi4/source/share/python/driver.py", line 586, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)

  File "/Users/jturney/Code/Chemistry/psi4/source/share/python/proc.py", line 831, in select_mp4
    raise ManagedMethodError(['select_mp4', name, 'MP_TYPE', mtd_type, reference, module])
```

**Comment by CDSherrill** [comment]
Lori and I had a discussion about this a while back.  I *think* my
conclusion was to remove ROHF MP4 as a listed capability.  *Technically*
DETCI can run it, but it will fail for any but the very tiniest of systems,
and in my opinion this will cause more user grief than it would to say we
can't do it.  I think the correct solution is to get rid of MP4 in the
Psi4Education module... which one was it?

David

**Comment by jturney** [comment]
The first one under "Advanced": [Lab Handout](https://docs.google.com/document/d/1mkOB6jlFiELdhR12zinu3aIwkMJauOjE4tgMBk6ZXc8/edit?usp=sharing)

**Comment by jturney** [comment]
Sorry, wrong link: [Lab Handout](https://docs.google.com/document/d/1cpQ_kJyAcF4DkXdGXLUt2ZbaBsNgseCbs0CFgKrNrG4/edit)

**Comment by loriab** [comment]
You can get it if you specify explicitly "set qc_module detci"

**Comment by loriab** [comment]
If the above works, and you think it'd be helpful, I can edit https://github.com/psi4/psi4/blob/master/share/python/proc.py#L825 to something like

```python
    elif reference == 'ROHF':
        if mtd_type == 'CONV':
            if module == 'DETCI':  # no default for this case
                func = run_detci
            elif module in ['']:
                psi4.print_out("""This method is available inefficiently as a byproduct of a CISDT computation. Add "set qc_module detci" to input to access this route.""")
```

**Comment by CDSherrill** [comment]
Sure, I'm ok with that modification
