### ISSUE TITLE
remaining BasisSet::construct

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#285]
How did these evade me? Everything should be calling ``BasisSet::pyconstruct``.

* [x] @fevangelista There's one in cubeprop (https://github.com/psi4/psi4/blob/master/src/lib/libcubeprop/csg.cc#L321). Does it need to endure? And is it related to the "ESP task requires" note in file:///Users/loriab/linux/psihub/publicface/psi4/objdir/doc/sphinxman/html/cubeprop.html .
* [x] hf.cc I don't think https://github.com/psi4/psi4/blob/master/src/lib/libscf_solver/hf.cc#L1529 ever gets called, but I should test. This one actually is still active, but I switched it over in 58db333
* [x] dftensor.cc Anyone know if this gets called regularly? at all? https://github.com/psi4/psi4/blob/master/src/lib/lib3index/dftensor.cc#L78

**Comment by jgonthier** [comment]
@loriab : From what I see in the code, https://github.com/psi4/psi4/blob/master/src/lib/lib3index/dftensor.cc#L78 is never called, because the constructor around it is never called.

**Comment by loriab** [comment]
Excellent, I'll mark that one off. And I think I know how to test for the last one. Thanks, @jgonthier .
