### ISSUE TITLE
Implement wB97X-3c

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#2850]
Gotta catch them all! :-)
https://aip.scitation.org/doi/full/10.1063/5.0133026

Requires new vDZP basis set (with ECPs) and a custom functional dictionary entry from a quick look. No gCP, underlying functional (wB97X-V) unchanged.

I will get to it, but open to help a new dev if there is interest.

**Comment by hmacdope** [comment]
I'd love to give it a crack if you can give me a hand?

**Comment by hokru** [comment]
@hmacdope happy to. I am currently working on a similar PR for r2scan-3c and others: https://github.com/psi4/psi4/pull/2842 you can have a look to get an idea what would be needed.

Until the new ORCA is released we don't have good reference values for tests, but I was planning to write to the Grimme group.

**Comment by annulen** [comment]
You don't actually need new ORCA to use ωB97X-3c. Paper contains all needed coefficients, and its supplementary material provides sample ORCA input file which can be used with 5.0.x

All you have to do is activate built-in `wB97X-D4` method with following addition:
```
%method
D4A1 0.2464
D4A2 4.737
D4S6 1.0
D4S8 0.0
D4S9 1.0
end
```

**Comment by loriab** [comment]
Do you happen to have access to v5 ORCA, @annulen? My orca is quite old -- v3.6. If you could generate ref values for this system perhaps https://github.com/psi4/psi4/blob/master/psi4/share/psi4/databases/S22.py#L695-L708 (monoA, monoB, dimer), that'd be a great help.
