### ISSUE TITLE
Fail in Psi4 energy decomposition analysis

### ISSUE THREAD

**Issue by mars303** [psi4/psi4#2866]
When I was doing energy decomposition analysis with Bronze standard of a transition state involving a 3d metal Ni, the following error comes up. I wonder how to solve such a problem? Thanks

```
 BasisSet::construct: Unable to find a basis set for atom 24 for key BASIS       
     among:                                                                       
   Shell Entries: ['NI']                                                          
   Basis Sets: [('JUN-CC-PVDZ', 'JUN-CC-PVDZ', None)]                             
   File Path: /gpfs/home/scms/zz/SAPT, /gpfs/home/scms/zz/SAPT,       
    /gpfs/home/scms/zz/psi4conda/share/psi4/basis                         !
  Input Blocks:                  
```

**Comment by loriab** [comment]
The Dunning basis sets aren't going to cover transition metals. You can look at https://psicode.org/psi4manual/master/basissets_byelement.html . Since SAPT also needs jkfit and ri auxiliary basis sets, a Karlsruhe might be worth trying.

**Comment by mars303** [comment]
Thanks very much for your help! I have tried to use def2-tzvp instead.

**Comment by mars303** [comment]
Thanks for your response. You are right. But I guess we need to download and use the basis for transition metal manually.
