### ISSUE TITLE
Libxc reference is not printed out

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#2867]
Psi4 is supposed to be printing out Libxc version information and the reference to Libxc. However, this is not happening for some reason at the moment.

Test inputs and outputs attached.
[test_composite.out.txt](https://github.com/psi4/psi4/files/10545133/test_composite.out.txt)
[test_composite.in.txt](https://github.com/psi4/psi4/files/10545134/test_composite.in.txt)
[test_builtin.out.txt](https://github.com/psi4/psi4/files/10545136/test_builtin.out.txt)
[test_builtin.in.txt](https://github.com/psi4/psi4/files/10545138/test_builtin.in.txt)

**Comment by JonathonMisiewicz** [comment]
I'm not seeing Libxc version information/references in either file, even though the `builtin` is commented as, "# Reference is printed out properly". What am I missing?

**Comment by loriab** [comment]
I remember this being added, and I've gotten as far as `xclib_description_`, then L2 started segfaulting again. I think this'll be a nice group programming target once I've hunted further.

**Comment by loriab** [comment]
solved. should get the PR up tomorrow.
