### ISSUE TITLE
large differences between ssapt0 and sapt0

### ISSUE THREAD

**Issue by mars303** [psi4/psi4#2869]
I have carried out an eda by psi4 with Bronze standard except that def2-tzvp was used instead of jun-cc-pvdz. However, the results of induction term between ssapt0 and sapt0 vary greatly (please see below).  Why is that and which one should I use? Thanks a lot

    SAPT Results 
  --------------------------------------------------------------------------------------------------------
    Electrostatics               -309.51816277 [mEh]    -194.22557944 [kcal/mol]    -812.63982439 [kJ/mol]
      Elst10,r                   -309.51816277 [mEh]    -194.22557944 [kcal/mol]    -812.63982439 [kJ/mol]

    Exchange                      489.56243374 [mEh]     307.20506518 [kcal/mol]    1285.34599270 [kJ/mol]
      Exch10                      489.56243374 [mEh]     307.20506518 [kcal/mol]    1285.34599270 [kJ/mol]
      Exch10(S^2)                 426.65840286 [mEh]     267.73218986 [kcal/mol]    1120.19148239 [kJ/mol]

    Induction                    -183.56373653 [mEh]    -115.18798371 [kcal/mol]    -481.94652386 [kJ/mol]
      Ind20,r                   -1352.55128018 [mEh]    -848.73874209 [kcal/mol]   -3551.12289689 [kJ/mol]
      Exch-Ind20,r               1030.31913785 [mEh]     646.53502001 [kcal/mol]    2705.10252373 [kJ/mol]
      delta HF,r (2)              138.66840581 [mEh]      87.01573836 [kcal/mol]     364.07384929 [kJ/mol]

    Dispersion                   -109.22158417 [mEh]     -68.53757881 [kcal/mol]    -286.76122973 [kJ/mol]
      Disp20                     -147.65080443 [mEh]     -92.65227859 [kcal/mol]    -387.65713362 [kJ/mol]
      Exch-Disp20                  38.42922026 [mEh]      24.11469978 [kcal/mol]     100.89590389 [kJ/mol]
      Disp20 (SS)                 -73.82540221 [mEh]     -46.32613929 [kcal/mol]    -193.82856681 [kJ/mol]
      Disp20 (OS)                 -73.82540221 [mEh]     -46.32613929 [kcal/mol]    -193.82856681 [kJ/mol]
      Exch-Disp20 (SS)             21.96541679 [mEh]      13.78350713 [kcal/mol]      57.67019385 [kJ/mol]
      Exch-Disp20 (OS)             16.46380346 [mEh]      10.33119265 [kcal/mol]      43.22571004 [kJ/mol]

  Total HF                         -3.51946556 [mEh]      -2.20849798 [kcal/mol]      -9.24035555 [kJ/mol]
  Total SAPT0                    -112.74104973 [mEh]     -70.74607679 [kcal/mol]    -296.00158529 [kJ/mol]

  Special recipe for scaled SAPT0 (see Manual):
    Electrostatics sSAPT0        -309.51816277 [mEh]    -194.22557944 [kcal/mol]    -812.63982439 [kJ/mol]
    Exchange sSAPT0               489.56243374 [mEh]     307.20506518 [kcal/mol]    1285.34599270 [kJ/mol]
    Induction sSAPT0              342.63858362 [mEh]     215.00895730 [kcal/mol]     899.59747735 [kJ/mol]
    Dispersion sSAPT0             -89.59509747 [mEh]     -56.22177246 [kcal/mol]    -235.23189599 [kJ/mol]
  Total sSAPT0                    433.08775712 [mEh]     271.76667057 [kcal/mol]    1137.07174967 [kJ/mol]

**Comment by loriab** [comment]
I'd trust sapt0 over ssapt0 in general. But the large difference btwn them and even btwn sapt0 and HF raises suspicion that the molecule or the distances involved aren't in the perturbation theory regime. SAPT0 should be around the HF and MP2 supermolecular interaction energies. Also, sapt0 is going to have better error cancelation with smaller double-zeta (like jun-cc-pvdz) so maybe svp.

**Comment by mars303** [comment]
Thanks, it's very helpful. I will try double-zeta as a comparison.

**Comment by JonathonMisiewicz** [comment]
@mars303 Is there still an issue here, or can we close this?

**Comment by mars303** [comment]
ok，thanks.在 2023年2月14日，上午6:34，Jonathon Misiewicz ***@***.***> 写道：﻿
@mars303 Is there still an issue here, or can we close this?
