### ISSUE TITLE
QCFractal Causes Test Suite Failure

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#2873]
[The test suite refuses to pass, even after multiple restarts, due to a test involving QCFractal.
](https://github.com/psi4/psi4/actions/runs/4140446911/jobs/7166134575) Some sqalchemy function is unhappy to be receiving a string, but the traceback isn't clear enough for me to interpret further.

@loriab

**Comment by loriab** [comment]
Determined with Ben Pritchard that this problem arises with the new v2 sqlalchemy. He has already fixed it in upstream QCFractal in https://github.com/MolSSI/QCFractal/commit/fc304740ea12f1b4b86b7a1a879aff657755fc7b and others. New conda packages are in progress (that will work with sqlalchemy v1.4 and v2), whereupon re-running our CI should be fixed.

**Comment by loriab** [comment]
b7 qca packages fixed this
