### ISSUE TITLE
Compute both gradient and energy

### ISSUE THREAD

**Issue by peastman** [psi4/psi4#2878]
I'm using psi4 through the Python API.  I want to compute both the energy and the gradient for a molecule.  I can do that by calling `psi4.energy()` and `psi4.gradient()`, but that repeats the entire calculation and takes twice as long as it needs to.  How can I retrieve both of them without having to repeat the calculation?

**Comment by JonathonMisiewicz** [comment]
Very easily.

```
wfn, grad = psi4.gradient(method, return_wfn=True)
en = wfn.variable("CURRENT ENERGY")
```

**Comment by peastman** [comment]
Perfect, thanks!
