### ISSUE TITLE
Conda install not work

### ISSUE THREAD

**Issue by BIRD-TAO** [psi4/psi4#2894]
When using conda install in Linux, it cannot install the linux version, and the following error occurs:
'''
conda install psi4 python=3.8 -c psi4
Collecting package metadata (current_repodata.json): done
Solving environment: /
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  -<unknown>/win-64::psi4==1.8a1.dev32+663453e=py38_0  
 
'''

**Comment by loriab** [comment]
Something's very peculiar with the setup if you're getting windows conflicts on a linux install. If it's windows you're targeting, the c-f channel is needed (Win;conda;3.8;stable from https://psicode.org/installs/v17/).

**Comment by JonathonMisiewicz** [comment]
Closing issue, due to a dubious initial report and the lack of response over the last... seven months.
