### ISSUE TITLE
The calculation does not run, but it does not report an error

### ISSUE THREAD

**Issue by meng1027-wang** [psi4/psi4#2900]
After installing the psi4, I ran a simple test. By looking at the output file, I found that the program seemed to stop after reading the contents of the input file, the program did not stop, but it did not continue and did not report an error. Also, there were no errors during the compilation of psi4, and it's not clear to me what went wrong.
![1678955019941](https://user-images.githubusercontent.com/99332231/225558169-d53d12b0-5c8b-4f6e-86e7-bb18e630ec4e.jpg)

**Comment by loriab** [comment]
Only things that come to mind are comment out `import forte` as unneeded and fix the quotes around `scf` (may just be font). Posting code by triple backtick rather than screenshot makes it possible to copy.

**Comment by meng1027-wang** [comment]
> Only things that come to mind are comment out `import forte` as unneeded and fix the quotes around `scf` (may just be font). Posting code by triple backtick rather than screenshot makes it possible to copy.

Thank you. I tried what you suggested, but the result is still the same. Also, I ran the example that came with the psi4/tests folder, and it turned out to be the same, so I thought it might be something wrong with my installation.
