### ISSUE TITLE
Incorrect energies or incorrect script?

### ISSUE THREAD

**Issue by dspoel** [psi4/psi4#2901]
Hi, I am trying to compute energy and force scans for some diatomic compounds using psi4.gradeint. In this case, a NO radical is used, with MP2 and the aug-cc-pvtz basis. The energy is not a smooth function of the distance, however all the calculations have converged SCF. Complete input script which takes a few minutes to run is attached as well as output. There are more examples. Am I missing something in checking for convergence? The main part of the script is here:
```
    converged = True
    try:
        grad, wfn = psi4.gradient("MP2", molecule=geom, return_wfn=True)
    except psi4.driver.SCFConvergenceError as ex:
        converged = False
        print("SCF convergence error at r = %g converged = %s" % (r, str(converged)))
    if converged:
        myener    = wfn.energy()
        forces    = grad.to_array()
        table.append([r, myener, -forces[0][2]])
```

I would be thankful for any input!

![energy](https://user-images.githubusercontent.com/3735358/225842500-985ebc66-c219-455b-8ada-39eba9729b88.png)
[psi4energy.zip](https://github.com/psi4/psi4/files/10998961/psi4energy.zip)

**Comment by dspoel** [comment]
Distance on x-axis, energy on y-axis. Calculations done using Psi4 1.7.

**Comment by hokru** [comment]
If you examine `Final Occupation by Irrep` you can see it changes eventually, causing a drastic change in the SCF energy.
It's not a technically issue but an electronic one.

What you can try is set `psi4.set_options({'reference': 'uhf', 'guess':'read'})` after the first SCF is done and check if the state still changes. It should help a lot. (And think about which state you want, and/or check which is lower in energy).
Sometimes bond scans are more stable going from long to short distances.

**Comment by dspoel** [comment]
Doing as you suggest indeed improves the results to something reasonable. Just wondering
 whether this is like a systematic solution.
 ![energy2](https://user-images.githubusercontent.com/3735358/225860444-c267f433-cc0c-4d06-84d0-84b5feda6f99.png)

**Comment by TiborGY** [comment]
> The energy is not a smooth function of the distance, however all the calculations have converged SCF. Complete input script which takes a few minutes to run is attached as well as output. There are more examples. Am I missing something in checking for convergence? 

Sort of. There is no guarantee that an SCF solution for a particular geometry is unique. The SCF iterations may converge to an ustable HF solution, you can check for this by running the stability analysis. But even if you find a stable HF solution, it is usually impossible to prove that you have found the global minimum.

If you are using UHF, you may also want to look into the various forms of symmetry breaking, it is possible that you actually do not want the global minimum UHF solution if it is too spin-symmetry-broken. But if you _are_ looking to find the global minimum for every point of your scan, you are going to have to employ some sort of nonlinear global optimization strategy, the simplest of which is to try a bunch of guesses for every point and use the lowest solution found.
You may get some ideas you could adapt to Psi4 from [this paper of mine.](https://doi.org/10.1063/5.0080817)

**Comment by JonathonMisiewicz** [comment]
> Doing as you suggest indeed improves the results to something reasonable. Just wondering whether this is like a systematic solution.

For the specific problem of obtaining a smooth curve that continues a particular SCF energy, using guess read is about as much of a systematic solution as you can have.

There are cases where an SCF solution simply ceases to exist along a potential energy curve, associated with near-singularities in the MO hessian. In such a case, no convergence trick can help you. If the "guess read" technique doesn't work, try adding `set soscf true`. If that still doesn't work, odds are that the solution ceases to exist. (Note: SOSCF is not implemented for DFT functionals with meta or iterative VV10 components.)

**Comment by dspoel** [comment]
Thanks for the background information - I appreciate it since 'm not a real quantum chemist, just a user.

**Comment by JonathonMisiewicz** [comment]
Is there a reason for the issue to remain open?
