### ISSUE TITLE
How to get the one-electron integrals with the molecular orbital (MO) basis in psi4?

### ISSUE THREAD

**Issue by meng1027-wang** [psi4/psi4#2904]
I try to find the way to get the one-electron integrals with the MO basis in psi4, such as directly by a function or indirectly by other ways. By looking for the introduction of "class psi4.core.MintsHelper[¶](https://psicode.org/psi4manual/master/api/psi4.core.MintsHelper.html#psi4.core.MintsHelper)" in the manual, i know i can get 2-electron integrals with MO basis by "mo_eri", but i don't know how to get 1-electron integrals with MO basis. And i don't know what some functions do, like "mo_f12", and what the arguments in them represent, such as "corr: List[Tuple[[float](https://docs.python.org/3.10/library/functions.html#float), [float](https://docs.python.org/3.10/library/functions.html#float)]]".
Can someone help me? Thank you very much!

**Comment by JonathonMisiewicz** [comment]
Before posting issues here, please ask your research group or see if you can figure out an answer from the [Psi4Numpy examples](https://github.com/psi4/psi4numpy). I guarantee that you could have found the issue from either of those.

**Comment by meng1027-wang** [comment]
> Before posting issues here, please ask your research group or see if you can figure out an answer from the [Psi4Numpy examples](https://github.com/psi4/psi4numpy). I guarantee that you could have found the answer from either of those.
> 
> (For the benefit of other Psi developers, I suspect this is one of Prof. Chenyang "York" Li's students.)

Ok, thanks. I think I found some useful tips from the examples mentioned in your answer, and I will try to solve my problem
