### ISSUE TITLE
installing psi4 into existing env with rdkit

### ISSUE THREAD

**Issue by ErikCVik** [psi4/psi4#2912]
I think this may be similar to a recent issue.

I can install psi4 into a new environment, but I would like to have rdkit available in the same env too. Is it possible to do a conda or mamba install psi4?

I obviously tried this and I am running into many conflicts. not sure if conda-forge or conda in general is getting tripped up because in the past I was able to install rdkit into a env with psi4 but not now apparently.

from `mamba install psi4 psi4-rt python=3.6 -c psi4'
`

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Looking for: ['psi4', 'psi4-rt', 'python=3.6']

pkgs/main/linux-64                                          Using cache
pkgs/main/noarch                                            Using cache
pkgs/r/linux-64                                             Using cache
pkgs/r/noarch                                               Using cache
psi4/linux-64                                                 No change
psi4/noarch                                                   No change
Could not solve for environment specs
The following packages are incompatible
├─ psi4   is installable with the potential options
│  ├─ psi4 [1.0.0|1.0.24|...|1.0rc216] would require
│  │  └─ pychemps2 >=1.7.1  with the potential options
│  │     ├─ pychemps2 [1.8.10|1.8.11|1.8.9] would require
│  │     │  └─ chemps2 [1.8.10 hbe8a562_0|1.8.11 hbe8a562_0|1.8.9 h8c3debe_0], which requires
│  │     │     └─ blas 1.0 mkl, which can be installed;
│  │     ├─ pychemps2 1.7.1 would require
│  │     │  └─ chemps2 1.7.1 , which requires
│  │     │     └─ hdf5 1.8.16 , which does not exist (perhaps a missing channel);
│  │     └─ pychemps2 1.8.3 would require
│  │        └─ chemps2 1.8.3 , which requires
│  │           └─ hdf5 1.8.17 , which does not exist (perhaps a missing channel);
│  ├─ psi4 [0.0.10|0.1.100|...|0.5.0] would require
│  │  └─ python 2.7* , which can be installed;
│  ├─ psi4 1.1+add49b9 would require
│  │  └─ gcc-5-mp  , which requires
│  │     └─ mpc 1.0.1 , which does not exist (perhaps a missing channel);
│  ├─ psi4 [1.2+9d4a61c|1.2.1+406f4de|...|1.7+6ce35a5] would require
│  │  └─ blas 1.0 mkl, which can be installed;
│  └─ psi4 [0.5.360|1.0rc0|1.0rc213] would require
│     ├─ hdf5 1.8.16 , which does not exist (perhaps a missing channel);
│     └─ pychemps2 1.7.1 , which cannot be installed (as previously explained);
├─ psi4-rt   is installable with the potential options
│  ├─ psi4-rt [1.2|1.3|...|1.7] would require
│  │  └─ v2rdm_casscf [0.8 py27hbddea90_0|0.8 py35hbddea90_0|...|0.9 py39hf915834_9], which requires
│  │     └─ blas 1.0 mkl, which can be installed;
│  ├─ psi4-rt 1.1 would require
│  │  └─ python 3.5* , which can be installed;
│  ├─ psi4-rt 1.1 would require
│  │  └─ python 3.6*  with the potential options
│  │     ├─ python 3.6.10 would require
│  │     │  └─ openssl >=1.1.1d,<1.1.2a , which can be installed;
│  │     ├─ python 3.6.10 would require
│  │     │  └─ openssl >=1.1.1e,<1.1.2a , which can be installed;
│  │     ├─ python [3.6.10|3.6.12] would require
│  │     │  └─ openssl >=1.1.1g,<1.1.2a , which can be installed;
│  │     ├─ python 3.6.13 would require
│  │     │  └─ openssl >=1.1.1k,<1.1.2a , which can be installed;
│  │     ├─ python 3.6.13 would require
│  │     │  └─ openssl >=1.1.1j,<1.1.2a , which can be installed;
│  │     ├─ python [3.6.2|3.6.3] would require
│  │     │  └─ openssl 1.0.* , which can be installed;
│  │     ├─ python 3.6.3 would require
│  │     │  └─ openssl >=1.0.2m,<1.0.3a , which can be installed;
│  │     ├─ python 3.6.4 would require
│  │     │  └─ openssl >=1.0.2n,<1.0.3a , which can be installed;
│  │     ├─ python [3.6.5|3.6.6] would require
│  │     │  └─ openssl >=1.0.2o,<1.0.3a , which can be installed;
│  │     ├─ python 3.6.6 would require
│  │     │  └─ openssl >=1.0.2p,<1.0.3a , which can be installed;
│  │     ├─ python [3.6.7|3.6.8] would require
│  │     │  └─ openssl >=1.1.1a,<1.1.2a , which can be installed;
│  │     └─ python 3.6.9 would require
│  │        └─ openssl >=1.1.1c,<1.1.2a , which can be installed;
│  └─ psi4-rt 1.1 would require
│     └─ python 2.7* , which can be installed;
└─ python 3.6** , which can be installed (as previously explained).
`

From `conda install psi4 psi4-rt python=3.6 -c psi4`

not going to post b/c it seems like every package has a conflict

**Comment by loriab** [comment]
It could be a little tricky b/c psi4 is generally defaults-based and rdkit is c-f-based. Working on that. But I suspect your immediate problem is because py36 is pretty old. I'd try py38 or newer, and it's unlikely you need `psi4-rt`.

**Comment by ErikCVik** [comment]
Got it!

I created the p4env via `conda create -n p4env psi4 -c psi4' and then used pip to install rdkit via `pip install rdkit`

closing issue

**Comment by loriab** [comment]
Glad you got it solved -- should be easier soon. fwiw, mamba was reaching back and finding psi4 v1.0, which is about 7yo and only worked on Py27. I'm not sure what it's reasoning was (besides that packages in those days didn't have many constraints), but I wonder if `-c defaults` wasn't in your implicit list. Anyways, you're working now, whew.
