### ISSUE TITLE
Out of memory running CCSD(T) on HCl dimer

### ISSUE THREAD

**Issue by dspoel** [psi4/psi4#2913]
Running a single point calc on a HCl dimer
[hcl2.zip](https://github.com/psi4/psi4/files/11093879/hcl2.zip)
 at the  CCSD(T)/aug-cc-pvtz level of theory crashes with
```
Total cached: 139345.9 kB; MRU =     31; LRU =     32
#LRU deletions =      0; #Low-priority deletions =      0
Core max size:  48000000.0 kB
Core used:      47999971.9 kB
Core available:      28.1 kB
Core cached:     139345.9 kB
Locked cached:   139345.9 kB
Most recent entry  = 31
Least recent entry = 32
dpd_block_matrix: n = 18  m = 324
Error in: dpd_block_matrix: No memory left.
```
The program gets allocated 48 Gb of memory and 16 cores. Cache level was set to 1. Any other suggestions?
Script is attached as a zip file.

**Comment by loriab** [comment]
Should there be an output in the zip? You might try first w/o altering cache settings.

**Comment by dspoel** [comment]
[hcl2.zip](https://github.com/psi4/psi4/files/11093961/hcl2.zip)
Good point, here is another input with corresponding output with the same problem.

**Comment by loriab** [comment]
Thanks. Your input looks reasonable to me. You could add `freeze_core="true"`, if appealing, for some cost savings. TDC could diagnose more fully. In the meantime, is there any chance you're interested in trying density-fitted `gradient("df-ccsd(t)")` instead? https://psicode.org/psi4manual/master/occ.html#id73 That's analytic, or `gradient("ccsd(t)", dertype=0)` would do finite difference of the implementation you're running.

Once-upon-a-time, UHF-CC(T)-gradients-are-N^8 and/or RHF-CC(T)-gradients-not-specialized-from-UHF was true. I now suspect that when I redid the capabilities tables last year that my test cases were too small to detect over-steep scaling.

**Comment by dspoel** [comment]
Using finite difference solves the problem and my calculation converged without problems, thanks!
