### ISSUE TITLE
Link s-dftd3 with psi4 

### ISSUE THREAD

**Issue by ahmedusm** [psi4/psi4#2936]
I compiled both psi4 and s-dftd3. Now I can not figure out how to link s-dftd3 with psi4.
I have defined PYTHONPATH for the s-dftd3 module, however, it still does not work as it complains
that QCEnigne can not find the program s-dftd3.
None of the following work.

`export PYTHONPATH=/path/to/s-dftd3/module:$PYTHONPATH

sys.path.insert(0, '/path/to/s-dftd3/module')`

**Comment by loriab** [comment]
you want the dftd3-python pkg from conda-forge. I think you've got the executable/lib, but the qcengine interface uses the python bindings which are in a different package.

**Comment by ahmedusm** [comment]
We intend to avoid conda as it would make the application run slower. Do you
mean dftd3-python pkg from conda forge is the only option at the moment?
I was able to use the interface to grimme's dftd3 compiled through the source, 
however, to use the three-body becke johnson damping it is the simple dftd3 we need.

**Comment by susilehtola** [comment]
For clarity, we are running on the Finnish supercomputing center which strongly advises not to use conda since it is extremely slow on network disk due to the bazillion files it creates and uses. (It is also slow on my laptop!)

@ahmedusm already was successful in compiling Psi4 from source, while I have been hopefully waiting on official Psi4 containers to come out. The supercomputers use Apptainer containers.

**Comment by hokru** [comment]
PSI4 uses the Python API of `s-dftd3` while for the old `dftd3` it uses the binary.
Just to be sure, did you turned on the python API when compiling `s-dftd3`? https://github.com/dftd3/simple-dftd3#python-api

And if so can you `import dftd3` after setting `psi4 --psiapi-path`?

**Comment by ahmedusm** [comment]
@hokru Yes the s-dftd3 module is compiled while Python API was turned on. `import dftd3` does not work as the Python interpreter throws `ModuleNotFoundError` even after setting `psi4 --psiapi-path`.

**Comment by susilehtola** [comment]
> @hokru Yes the s-dftd3 module is compiled while Python API was turned on. `import dftd3` does not work as the Python interpreter throws `ModuleNotFoundError` even after setting `psi4 --psiapi-path`.

Sounds like `PYTHONPATH` isn't set properly

**Comment by hokru** [comment]
I had to set `export PYTHONPATH=$PYTHONPATH:<path_to_s-dftd3_install_dir>/lib/python3.10/site-packages/`

For QCEngine to recognize `s-dftd3` as an engine the import needs to work. That's the internal test.

**Comment by ahmedusm** [comment]
Thanks @hokru it works now.
