### ISSUE TITLE
update to pyddx 0.4

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#2940]
Reminder to finish pinning to 0.3 or resolve tests to allow 0.4 before v1.8. Just making an issue so it's tracked. @mfherbst

**Comment by mfherbst** [comment]
Sorry about my silence. I've been in proposal writing mode lately. I'll take a look at this over the weekend.

**Comment by loriab** [comment]
No problem. Thanks for taking a look, @mfherbst.
