### ISSUE TITLE
cross-vendor compilation

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#297]
We tend to build with all Gnu compilers or all Intel compilers or maybe icpc/gfortran? Sometime, give the other combinations a spin to make sure our CMake config system can handle them. There's evidence (http://forum.psicode.org/t/gcc-and-fort-on-an-el-capitan-mac/165) that it can't. 
- [x] icpc & gfortran on linux
- [ ] g++ & ifort on linux
- [ ] icpc & gfortran on mac
- [ ] g++ & ifort on mac

**Comment by jturney** [comment]
- g++ & ifort on linux: there was an undefined reference to ```__must_be_linked_with_icc_or_xild``` this was with Intel 16.0.2 / gcc 5.2 on Ubuntu 15.10
- icpc & gfortran on linux: success with Intel 16.0.2 / gcc5.2 on Ubuntu 15.10

**Comment by loriab** [comment]
Looks like Peterson makes g++/ifort [work](http://forum.psicode.org/t/problems-enabling-dkh/388?u=loriab) on Linux.

And I've mixed clang and gfortran-compiled parts on Mac.

And we've no prospect of Intel compilers on Mac

So, I propose we close this.
