### ISSUE TITLE
Numerical (?) noise in SCF gradient 

### ISSUE THREAD

**Issue by psi-rking** [psi4/psi4#298]
Disilylether with scf_type=pk is fine.  Without it, the gradients are only c2v-symmetric to 9 decimal places, and after some geometry steps an optimization will fail due to change in point group.  Is this noise an inevitable consequence of density-fitting or some other approximation?  If so, can we symmetrize the gradient after it is produced?  I haven't confirmed this result yet with the very latest psi4.

```python
memory 2 gb
set {
  basis 6-31G*
  reference RHF
  guess gwh
}

molecule {
 0 1
 SI          0.0        -3.03636189    0.1503967744
 SI          0.0         3.03636189    0.1503967744
 O           0.0         0.00000000   -0.6720662056
 H           0.0        -4.54756839   -1.9795468656
 H           0.0         4.54756839   -1.9795468656
 H           2.12290049 -3.58475023    1.5688329144
 H          -2.12290049 -3.58475023    1.5688329144
 H           2.12290049  3.58475023    1.5688329144
 H          -2.12290049  3.58475023    1.5688329144
}
gradient('scf')
```

**Comment by dgasmith** [comment]
Im guessing this is due to the fact that the DF JK algorithm runs in C1 symmetry. 

It looks like the errors are exceedingly small, can we just resymmetrize the molecule using built in functions after a optking step to retain the symmetry?

**Comment by robparrish** [comment]
Yeah, this is likely numerical noise in the eigendecomposition stages of
DF-SCF. As the errors are exceedingly small, I'd recommend just explicitly
symmetrizing the gradient to the desired point group externally.

-Rob

**Comment by psi-rking** [comment]
Yes, the gradient itself should get symmetrized.  So I know any deviations
that occur from a symmetric structure within optking are optking's fault
not simply amplification of an input asymmetry.

**Comment by andysim** [comment]
It should be as simple as calling code like [this](https://github.com/psi4/psi4/blob/master/src/lib/libmints/deriv.cc#L753-L782).

**Comment by robparrish** [comment]
Nice one Andy!

-Rob

**Comment by dgasmith** [comment]
Well, at least our post-SCF gradients have the right symmetry. SCF is its own module... Making a new Deriv object seems a bit of waste so I think the simplest thing to do is just to duplicate the function in `src/scfgrad`. Duplication is not my favorite thing, but certainly the simplest.

I guess we are guaranteed to be in standard orientation unlike the [molecule](https://github.com/psi4/psi4/blob/master/src/lib/libmints/molecule.cc#L2787) version? Seems like yes, but good to be sure while were looking at it.

**Comment by loriab** [comment]
@dgasmith and I were discussing this and realizing that if we start guaranteeing symmetrized output that there are many arrays as plausible targets: Hessian, components of gradient, MOs, properties. That is, every symmetry tolerant code is going to have to shove its output through a symmetrizer, or parts that need symmetrized input (e.g., optking) could it into targeted (e.g., gradient-only) symmetrizers.

For general planning, functions like these probably belong in the driver alongside functions (various of which I have) for manipulating mol, dipole, grad, hess by translation, rotation, atom-exchange, etc.

**Comment by loriab** [comment]
For future reference and for the robustness of https://github.com/psi4/psi4/pull/301, I'd like to know the answer to the standard orientation question in https://github.com/psi4/psi4/issues/298#issuecomment-191476636, if anyone in the know can supply it.

**Comment by andysim** [comment]
I didn't know about the molecule member, but I vote that we go with the algorithm that assumes nothing about the orientation.  We don't use symmetry unless the molecule is in the standard orientation, but I still think it's best to be safe.  Especially when that safety comes without any extra computational cost.  I think you're right about having a central location to handle this for gradients, hessians, etc.

**Comment by jturney** [comment]
Yeah, the one in molecule used to be like the one in deriv when I originally wrote it 5 years ago. Then @psi-rking expanded on it to assume non-standard orientation. A centralized one sounds good since I just found another on in matrix.cc.

**Comment by psi-rking** [comment]
I think "symmetry tolerant" is an odd description to apply to a method that
takes a symmetrical input and produces an asymmetrical output (e.g., the
DF-SCF gradient generating asymmetrical noise in the 9th decimal).  If
numerical approximation is introducing the asymmetry, isn't the
symmetrization, if done evenly, likely to improve the accuracy of the
result, besides avoiding the risk of collateral damage?  I appreciate
symmetrizing other types of objects may not be as simple.

**Comment by loriab** [comment]
It's a technical term :-) (http://forum.psicode.org/t/managed-methods-feedback-required/130/4?u=loriab), @psi-rking . Thanks for the answers, @jturney and @andysim, I'd feel better, too, if we assume less about the orientation, so long as there's no reason to the contrary. I believe @dgasmith is already adding the off-diagonals to #301, so that should wrap up this issue. And we're agreed on where such function should live in future, as they materialize.
