### ISSUE TITLE
Unexpected error when using  basis set aug-cc-pv5z for He-NH3 interaction.

### ISSUE THREAD

**Issue by brittosandro** [psi4/psi4#2989]
I'm trying to perform SAPT calculations with the aug-cc-PV5Z bases set for the interaction between helium gas and ammonia. However, getting the error describe below.

 Memory set to  26.077 GiB by Python driver.
  Threads set to 12 by Python driver.

QcdbException BasisSetNotFound: BasisSet::construct: Unable to find a basis set for atom 5 for key JKFIT among:
  Shell Entries: ['HE']
  Basis Sets: [('aug-cc-pv5z-jkfit', 'aug-cc-pv5z-jkfit', None)]
  File Path: /home/sandro/Desktop/teste_He-aug-cc-pv5z, /home/sandro/Desktop/teste_He-aug-cc-pv5z, /home/sandro/miniconda3/envs/venv_psi4/share/psi4/basis
  Input Blocks: 

Traceback (most recent call last):
  File "run_GN_NH3_inter_var.py", line 402, in <module>
    eel = calcula_energia(metodo, base, dimero, fator_conv)[0]
  File "run_GN_NH3_inter_var.py", line 73, in calcula_energia
    psi4.energy(f'{metodo}/{base}')
  File "/home/sandro/miniconda3/envs/venv_psi4/lib/python3.8/site-packages/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/sandro/miniconda3/envs/venv_psi4/lib/python3.8/site-packages/psi4/driver/procrouting/proc.py", line 4394, in run_sapt
    dimer_wfn = scf_helper('RHF', molecule=sapt_dimer, **kwargs)
  File "/home/sandro/miniconda3/envs/venv_psi4/lib/python3.8/site-packages/psi4/driver/procrouting/proc.py", line 1576, in scf_helper
    scf_wfn = scf_wavefunction_factory(name, base_wfn, core.get_option('SCF', 'REFERENCE'), **kwargs)
  File "/home/sandro/miniconda3/envs/venv_psi4/lib/python3.8/site-packages/psi4/driver/procrouting/proc.py", line 1231, in scf_wavefunction_factory
    aux_basis = core.BasisSet.build(wfn.molecule(), "DF_BASIS_SCF",
  File "/home/sandro/miniconda3/envs/venv_psi4/lib/python3.8/site-packages/psi4/driver/p4util/python_helpers.py", line 85, in _pybuild_basis
    bs, basisdict = qcdb.BasisSet.pyconstruct(mol.to_dict(),
  File "/home/sandro/miniconda3/envs/venv_psi4/lib/python3.8/site-packages/psi4/driver/qcdb/libmintsbasisset.py", line 696, in pyconstruct
    bs, msg, ecp = BasisSet.construct(parser, mol,
  File "/home/sandro/miniconda3/envs/venv_psi4/lib/python3.8/site-packages/psi4/driver/qcdb/libmintsbasisset.py", line 918, in construct
    raise BasisSetNotFound(f'BasisSet::construct: Unable to find a basis set for atom {at + 1} for key {key} among:\n{text2}')
psi4.driver.qcdb.exceptions.BasisSetNotFound: BasisSet::construct: Unable to find a basis set for atom 5 for key JKFIT among:
  Shell Entries: ['HE']
  Basis Sets: [('aug-cc-pv5z-jkfit', 'aug-cc-pv5z-jkfit', None)]
  File Path: /home/sandro/Desktop/teste_He-aug-cc-pv5z, /home/sandro/Desktop/teste_He-aug-cc-pv5z, /home/sandro/miniconda3/envs/venv_psi4/share/psi4/basis
  Input Blocks:

 

I've been using versions 1.6.0 and 1.8.0. The files are listed in 
[He.zip](https://github.com/psi4/psi4/files/11860037/He.zip)

**Comment by loriab** [comment]
Regrettably, this is expected. From https://www.basissetexchange.org/ (choose role: JK-fitting and element He), you can see that there isn't a Dunning cc-pVNZ basis defined for Helium. Usually what psi4 does is use the universal def2-universal-JKFIT when there isn't a JKfit designed for the orbital basis. But this is turned off above quad-zeta b/c (1) the universal basis is quad-zeta itself and (2) if you're in 5-zeta territory you might not appreciate the density-fitting error anyways.

You'll have to decide if you want the quad-zeta fitting basis anyways or want to turn off DF or downgrade the basis for He, etc.

**Comment by PhillCli** [comment]
For SAPT you can try running `scf_type=direct` for all corrections except dispersion-ones, which require RI fitting basis set.
It will converge SCF using exact (direct) integrals, and the same JK builders should re-be used for all induction/electrostatics exchange corrections computation. 

I've played with a meta-stable Helium dimer before, which is lacking aux-basis for JKfit, and what I've used is direct JK for everything except dispersion, with aux from av6z-ri.


```python
import psi4
import time

start = time.time()
psi4.set_num_threads(4)
psi4.set_memory("30000 MB")
psi4.core.set_output_file("sapt0_uhf_1.0.dat", False)

psi4.set_options(
    {
        "reference": "uhf",
        "scf_type": "direct",
        "df_basis_scf": "def2-universal-JKFIT",
        "df_basis_sapt": "aug-cc-pv6z-ri",
        "basis_guess": "aug-cc-pvdz",
        "basis": "d-aug-cc-pv5z",
        "guess": "sad",
        "maxiter": 300,
        "e_convergence": 1e-10,
        "d_convergence": 1e-10,
    }
)

```

**Comment by brittosandro** [comment]
Even when using all the parameters suggested by @PhillCli in a test script, the calculation does not complete. The SCF part is executed, but it seems that there is a problem when building the basis set for the SAPT calculation. 

Calculation stops at this point

Module time:
	user time   =      65.52 seconds =       1.09 minutes
	system time =       0.53 seconds =       0.01 minutes
	total time  =         18 seconds =       0.30 minutes
Total time:
	user time   =     208.45 seconds =       3.47 minutes
	system time =       1.55 seconds =       0.03 minutes
	total time  =         56 seconds =       0.93 minutes
  Constructing Basis Sets for SAPT...

   => Loading Basis Set <=

    Name: AUG-CC-PV6Z-RI
    Role: RIFIT
    Keyword: DF_BASIS_SAPT
    atoms 1-2 entry HE         line    95 file /home/sandro/miniconda3/envs/venv_psi4/share/psi4/basis/aug-cc-pv6z-ri.gbs 

**Displaying the following message in the execution termina**l

QcdbException BasisSetNotFound: BasisSet::construct: Unable to find a basis set for atom 1 for key JKFIT among:
  Shell Entries: ['HE']
  Basis Sets: []
  File Path: /home/sandro/Desktop/teste, /home/sandro/Desktop/teste, /home/sandro/miniconda3/envs/venv_psi4/share/psi4/basis
  Input Blocks: 



Traceback (most recent call last):
  File "teste.py", line 37, in <module>
    ecp[R] = psi4.energy('sapt0', molecule=he2)
  File "/home/sandro/miniconda3/envs/venv_psi4/lib/python3.8/site-packages/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/sandro/miniconda3/envs/venv_psi4/lib/python3.8/site-packages/psi4/driver/procrouting/proc.py", line 4487, in run_sapt
    aux_basis = core.BasisSet.build(dimer_wfn.molecule(), "DF_BASIS_ELST", core.get_global_option("DF_BASIS_ELST"),
  File "/home/sandro/miniconda3/envs/venv_psi4/lib/python3.8/site-packages/psi4/driver/p4util/python_helpers.py", line 85, in _pybuild_basis
    bs, basisdict = qcdb.BasisSet.pyconstruct(mol.to_dict(),
  File "/home/sandro/miniconda3/envs/venv_psi4/lib/python3.8/site-packages/psi4/driver/qcdb/libmintsbasisset.py", line 696, in pyconstruct
    bs, msg, ecp = BasisSet.construct(parser, mol,
  File "/home/sandro/miniconda3/envs/venv_psi4/lib/python3.8/site-packages/psi4/driver/qcdb/libmintsbasisset.py", line 918, in construct
    raise BasisSetNotFound(f'BasisSet::construct: Unable to find a basis set for atom {at + 1} for key {key} among:\n{text2}')
psi4.driver.qcdb.exceptions.BasisSetNotFound: BasisSet::construct: Unable to find a basis set for atom 1 for key JKFIT among:
  Shell Entries: ['HE']
  Basis Sets: []
  File Path: /home/sandro/Desktop/teste, /home/sandro/Desktop/teste, /home/sandro/miniconda3/envs/venv_psi4/share/psi4/basis
  Input Blocks:

**The script I am using for the test is** 

`import psi4
import time
psi4.core.set_output_file('output.dat', False)

he2_geometry = """
He
--
He 1 {0}
"""

Rvals = [2.5, 3.0,]

start = time.time()
psi4.set_num_threads(4)
psi4.set_memory("30000 MB")


psi4.set_options(
    {
        "reference": "uhf",
        "scf_type": "direct",
        "df_basis_scf": "def2-universal-JKFIT",
        "df_basis_sapt": "aug-cc-pv6z-ri",
        "basis_guess": "aug-cc-pvdz",
        "basis": "d-aug-cc-pv5z",
        "guess": "sad",
        "maxiter": 300,
        "e_convergence": 1e-10,
        "d_convergence": 1e-10,
    }
)

ecp = {}

for R in Rvals:
    he2 = psi4.geometry(he2_geometry.format(R))
    ecp[R] = psi4.energy('sapt0', molecule=he2)

# Prints to screen
print("Interaction Energies\n\n")
print("                   R                 E_int        ")
print("---------------------------------------------------------")
for R in Rvals:
    e = ecp[R] 
    print("            {:3.1f}                        {:1.6f}".format(R, e))`

**Comment by brittosandro** [comment]
Even when using all the parameters suggested by @PhillCli in a test sript, the calculation does not complete. The SCF part is executed, but it seems that there is a problem when building the basis set for the SAPT calculation.

Calculation stops at this point

![Screenshot from 2023-06-27 09-54-28](https://github.com/psi4/psi4/assets/17604953/24f20f18-3708-46dc-b80b-681a98083799)

Displaying the following message in the executation terminal

![Screenshot from 2023-06-27 09-57-24](https://github.com/psi4/psi4/assets/17604953/6fdd54b8-3210-4b4e-a000-ed640f187e7c)

The script I am using for the test 

```
import psi4
import time
psi4.core.set_output_file('output.dat', False)

he2_geometry = """
He
--
He 1 {0}
"""

Rvals = [2.5, 3.0,]

start = time.time()
psi4.set_num_threads(4)
psi4.set_memory("30000 MB")


psi4.set_options(
    {
        "reference": "uhf",
        "scf_type": "direct",
        "df_basis_scf": "def2-universal-JKFIT",
        "df_basis_sapt": "aug-cc-pv6z-ri",
        "basis_guess": "aug-cc-pvdz",
        "basis": "d-aug-cc-pv5z",
        "guess": "sad",
        "maxiter": 300,
        "e_convergence": 1e-10,
        "d_convergence": 1e-10,
    }
)

ecp = {}

for R in Rvals:
    he2 = psi4.geometry(he2_geometry.format(R))
    ecp[R] = psi4.energy('sapt0', molecule=he2)

# Prints to screen
print("Interaction Energies\n\n")
print("                   R                 E_int        ")
print("---------------------------------------------------------")
for R in Rvals:
    e = ecp[R] 
    print("            {:3.1f}                        {:1.6f}".format(R, e))
```

**Comment by brittosandro** [comment]
I was able to solve the problem by adding the following keyword "df_basis_elst": "def2-universal-JKFIT" to the script. We believe that psi4 does not declare the electrostatic component by default for bases above QZ.

**Comment by loriab** [comment]
> I was able to solve the problem by adding the following keyword "df_basis_elst": "def2-universal-JKFIT" to the script. We believe that psi4 does not declare the electrostatic component by default for bases above QZ.

Especially if you're filling in one number in a basis trend, sounds fine, just so long as you're aware that you're fitting a 5-zeta orbital basis with a 4-zeta aux basis.

**Comment by brittosandro** [comment]
Thank you very much for the contributions.
