### ISSUE TITLE
How to change the convergence threshold for HF?

### ISSUE THREAD

**Issue by frankwswang** [psi4/psi4#2990]
Hi! I'm following the [official tutorial](https://psicode.org/psi4manual/master/psiapi.html) to run a simple HF computation using Psi4:
```
H2 = psi4.geometry("""
units au
H 0 0 0
H 1.4 0 0
"""
)

psi4.set_module_options('scf', {'e_convergence': '1e-3'})

psi4.energy('scf/cc-pvdz')
```

However, it seems that after I manually set the energy convergence threshold to `1e-3`, the program still used the default value `1e-6` for the computation based on its output log: 
```
==> Algorithm <==

  SCF Algorithm Type is DF.
  DIIS enabled.
  MOM disabled.
  Fractional occupation disabled.
  Guess Type is SAD.
  Energy threshold   = 1.00e-06
  Density threshold  = 1.00e-06
  Integral threshold = 1.00e-12
```

Did I use the wrong method to change the option (even though it's recommended in the same tutorial)? If so, what is the correct way to do it in Python? Thank you!

**Comment by philipmnel** [comment]
The value should be a float `1e-3` or an int `3` not a string, `'1e-3'`.

It's  fine to just set the option globally as well,
```
psi4.set_options({'e_convergence': 1e-3})
```
unless you need different modules to have different options set.

This part of the tutorial should be updated.

**Comment by frankwswang** [comment]
It works now. Thanks so much!
