### ISSUE TITLE
"sort mrpt2 out of core" request

### ISSUE THREAD

**Issue by Konjkov** [psi4/psi4#30]
Dear psi4 developer.
I found out that the MRMP2 method doesn't use out_of_core algorithm like MKCCSD and MRCCSD(T) does for sorting (src/bin/psimrcc/sort_out_of_core.cc).
MRPT2 incore algorithm uses large amounts of memory, for example 31Gb for C8H8 molecule, C2V symmetry, in cc-pVTZ basis, instead of ~11GB for MRCCSD with same options.
I not completely understand algorithm of sorting, but is there an opportunity to use  sort_out_of_core.cc algorithm for MRPT2, may be with some simplifications or modification?
Any comments are welcomed.

**Comment by amjames** [comment]
@andysim what is the status of this issue?

**Comment by dgasmith** [comment]
@andysim @fevangelista Is this currently planned in any way?

**Comment by loriab** [comment]
referenced and closed in  5363f82
