### ISSUE TITLE
module 'forte' has no attribute 'ForteOptions'

### ISSUE THREAD

**Issue by gpwood** [psi4/psi4#3010]
Hi,

I just updated my psi4 conda installation using:

`conda install psi4 python=3.10 -c conda-forge/label/libint_dev -c conda-forge `

imports seem to work fine:

```
import psi4
import forte
```
however, when I run the following:

```
psi4.set_memory('500 MB')
numpy_memory = 2 # No NumPy array can exceed 2 MB in size
psi4.core.set_output_file('output.dat', False)
# specify the basis
basis = 'cc-pVTZ'
# Set computation options
psi4.set_options({'basis': basis,
                  'scf_type': 'pk',
                  'save_jk': 'true',
                  'guess': 'core',
                  'print' : 5,
                  'FREEZE_CORE' : 'True',
                  'e_convergence': 1e-8,
                  'd_convergence': 1e-10,
                 'LOCAL_MAXITER':10000})
geometry = '''
O -4.6674893014 0.2942847846 3.0623807031
H -3.892960984 0.903739148 3.0964143699
H -4.4005368234 -0.1221007613 2.241525046
'''
mol = psi4.geometry(geometry+"symmetry c1")
SCF_E_psi = psi4.energy('scf')
```
it fails with:

```
File ~/opt/miniconda3/envs/psi4/lib/python3.10/site-packages/psi4/driver/p4util/procutil.py:531, in prepare_options_for_set_options()
    529 current_module = psi_options.get_current_module()
    530 # Get the current Forte options from Forte
--> 531 forte_options = forte.ForteOptions()
    532 forte.register_forte_options(forte_options)
    533 psi_options.set_current_module("FORTE")

AttributeError: module 'forte' has no attribute 'ForteOptions'
```

I can minimally reproduce the error with:

```
mport forte
forte_options = forte.ForteOptions()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[7], line 2
      1 import forte
----> 2 forte_options = forte.ForteOptions()
AttributeError: module 'forte' has no attribute 'ForteOptions'
```

**Comment by JonathonMisiewicz** [comment]
`forte.ForteOptions()` works for mine. I suspect a severely outdated version of `forte`.

**Comment by loriab** [comment]
There's no `forte` on conda to my knowledge. You do _want_ to use forte from FAE group, right? Otherwise (if you just have a stray `forte.py` or old toy forte lying around, this is a quick comment-out-a-line fix.

**Comment by gpwood** [comment]
I suspect it's a stray forte somewhere. However, I have not installed forte as part of this separate environment, I do have a failed compilation of it around so that could be the reason. The call  appears to be coming from this function in psi4:
`PSI4.DRIVER.P4UTIL.PROCUTIL`

**Comment by loriab** [comment]
So long as you're not wanting to use forte, either get it out of sight of `PYTHONPATH` envvar (so `import forte` doesn't work) or comment out the couple "hooks" psi4 has for it -- that is, turn that `try: import forte` into `try: import fakeforte`.

**Comment by gpwood** [comment]
OK, thanks I tracked it down it was a stray copy of forte. Thanks for the replies, appreciate it.
