### ISSUE TITLE
Electric field

### ISSUE THREAD

**Issue by SebWouters** [psi4/psi4#302]
Hi everyone,

Two short questions regarding https://github.com/psi4/psi4/blob/a5f51268e0385916830a2065ed34052cf1fab647/tests/props1/input.dat:

Q1: Is there a generalization of

```
set scf perturb_h true
set scf perturb_with dipole_z
set scf perturb_magnitude 0.001
```

to specific unit vectors? Or alternatively, can one specify a dipole perturbation as follows

```
set scf perturb_with dipole_vec
set scf perturb_magnitude [ 0.001 * cos_theta, 0.001 * sin_theta, 0.0 ]
```

in which a vector can be placed? I do understand that as an alternative I can rotate the geometry, but I'm just wondering.

Q2: Are those integrals ( i | T + V_nuc + field . dipole | j ) also present in subsequent calculations (mp2, ccsd, dmrg)?

Thanks!
Seb

**Comment by jturney** [comment]
Hey,

Q1: The current code can only perturb along the specified axis. We could adapt it to handle rotations we'd just have to be careful with symmetry; it shouldn't be difficult.

Q2: Any code that uses the ```MintsHelper::so_potential``` (not ```MintsHelper::ao_potential```) will have the perturbation applied. I had tested this a few years ago for MP2 and CCSD. Might be a good idea to make sure there's a test included for it.

**Comment by dgasmith** [comment]
@SebWouters Any comments on this? Otherwise we will probably close.

**Comment by SebWouters** [comment]
No comments.
