### ISSUE TITLE
No Python 3.11 Conda build for Psi4

### ISSUE THREAD

**Issue by arosen93** [psi4/psi4#3031]
I am trying to install Psi4 with Conda on a Linux machine with Python 3.11. However, it does not seem like Python 3.11 is supported at this time despite the README badge showing 3.11.

Are there plans to add a Python 3.11 Conda build in the near future?
 
```
conda create --name psi4 python=3.11
conda activate psi4
conda install psi4 -c psi4
```

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - psi4 -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0']

Your python: python=3.11

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.35=0
  - psi4 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - python=3.11 -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.35
```

**Comment by loriab** [comment]
Ah, recent releases are now on c-f, including through py311. please use ` conda install psi4 python=3.11 -c conda-forge/label/libint_dev -c conda-forge` from https://psicode.org/installs/v18/ with choices conda/3.11/stable.

**Comment by arosen93** [comment]
@loriab: Ah, thanks so much! I didn't see that install page. Very helpful! I'll close this issue.

**Comment by loriab** [comment]
Yes, psi4 -> c-f channels has been a tricky-to-communicate transition. Let me know if it gives further problems.

**Comment by arosen93** [comment]
Thanks! Got it to work. The only sad part is the environment solve went from ~3 min with Python 3.10 and the psi4 channel to ~10 min with Python 3.10 or 3.11 and the c-f channel... but a price I shall have to pay! 🥲

**Comment by loriab** [comment]
Great! If you're not already, adding `--solver libmamba` to the solve can improve the speed considerably. (You may need to install `conda-libmamba-solver` to base env https://conda.github.io/conda-libmamba-solver/getting-started/ .)

**Comment by arosen93** [comment]
That was magical. Thank you so much! It's back down to 3 minutes now 😄
