### ISSUE TITLE
Documentation links don't work

### ISSUE THREAD

**Issue by ntBre** [psi4/psi4#3042]
Every link I've tried on the [home page](https://psicode.org/psi4manual/master/index.html) gives me a "Page Not Found" error. Here's just one example: https://psicode.org/introduction

If I add /psi4manual/master between psicode.org and /introduction, I can get the correct page: https://psicode.org/psi4manual/master/introduction

I also tried the links in the releases page, and all of them also gave "Page Not Found" errors:
- https://psicode.org/psi4manual/1.8.1/
- https://psicode.org/psi4manual/1.7.0/
- https://psicode.org/psi4manual/1.6.1/
- https://psicode.org/psi4manual/1.6.0/

The links for 1.4 and 1.5 actually do work, so maybe everything before that does too.

**Comment by JonathonMisiewicz** [comment]
Though even that doesn't have the search working, for some reason...

**Comment by loriab** [comment]
Yes, search is my other headline TODO for the docs and why I didn't put up the snapshots for v1.8.x . _That_ is likely a bad reaction between the sphinx version and maybe the now-minimally-maintained cloud sphinx theme. I need a day of trying out software versions.

**Comment by JonathonMisiewicz** [comment]
Issue fixed by @loriab.
