### ISSUE TITLE
Installing psi4 on an openff environment - 'blas * mkl' and 'mkl >=2022.2.1,<2023.0a0' conflicts. 

### ISSUE THREAD

**Issue by bismuthadams1** [psi4/psi4#3046]
I want to install psi4 on my openff environment since OpenFF Recharge requires it to generate electrostatic charges (https://docs.openforcefield.org/projects/recharge/en/stable/getting-started/installation.html). 

I have used mamba to install openff, following steps 3 and 4 [https://docs.openforcefield.org/en/latest/install.html](here).

I tried to install psi4 via mamba with the following commad:
`mamba install psi4=1.8.1 -c conda-forge/label/libint_dev -c conda-forge`

However, I got several warnings about incompatible packages:

`blas [2.4|2.5|2.6|2.7] would require
│  │        └─ libblas [3.8.0 4_openblas|3.8.0 5_openblas|3.8.0 6_openblas|3.8.0 7_openblas], which requires
│  │           └─ openblas 0.3.5.* , which does not exist (perhaps a missing channel);
`
and
` psi4 1.8.1 would require
   │  ├─ libblas * *mkl, which requires
   │  │  └─ blas * mkl, which conflicts with any installable versions previously reported;
   │  └─ mkl >=2022.2.1,<2023.0a0 , which conflicts with any installable versions previously reported;
`

I also attempted to install psi4=1.7, but this also led to a similar conflicts issue:

`psi4 1.7**  is not installable because it requires
   └─ blas 1.0 mkl, which conflicts with any installable versions previously reported.
`
I believe I need psi4 installed on my openff environment for it to be usable for openff's wrappers.

I've tried installing the blas dependencies explicitly:

`mamba conda install -c conda-forge openblas` 
but this tells me the package is already installed. 

and:

`mamba install 'libblas * *mkl' -c conda-forge -c defaults` which results in the same `openblas 0.3.5.* , which does not exist (perhaps a missing channel);` error. 

Any ideas? I must admit I am relatively new to using mamba + managing environments, but I believe it is just a reimplementation of conda.

**Comment by bismuthadams1** [comment]
I managed to solve the issue by installing psi4 first using only conda channels

`mamba install psi4 -c conda-forge/label/libint_dev -c conda-forge`

and then installing open-ff with

`mamba install -c conda-forge openff-toolkit`

**Comment by loriab** [comment]
Probably what's happening is that psi4 is packaged only with MKL (except for Apple Silicon) and OpenFF is flexible in BLAS, but conda-forge defaults to OpenBLAS. So one needs to install both together or install psi4 and then openff, as you worked out.

**Comment by mattwthompson** [comment]
+1 to installing both at the same time, ideally just at environment creation
