### ISSUE TITLE
How to access density matrix history in SCF iterations

### ISSUE THREAD

**Issue by ftsong22** [psi4/psi4#3065]
Lets denote in the t-th SCF iteration, the density matrix that goes in the Kohn-Sham equation D_in^(t), and the solution is D_out^(t). Then we do density mixing to form the next input D_in^(t+1). Now I am trying to add custom code to save all D_in and D_out history in `scf_iterators.py`, but it seems that the `self.Da()` & `self.Db()` always represents D_in^(t), and will be updated by `self.form_D()` (I'm not sure about this)? If so, where can I find the D_out^(t)?

Thanks!

**Comment by JonathonMisiewicz** [comment]
There are multiple issues here, and the first one is to make sure that we're using the same definitions. Your vocabulary makes me suspect that you're more used to plane wave methods.

In Psi4, SCF works by having an initial density matrix, constructing a Fock matrix, modifying the Fock matrix using optional DIIS (default) and level shift (not default), solving the generalized eigenvalue problem to get new orbitals, constructing a new density matrix from those orbitals (normally aufbau), and then mixing that with the previous density (optional, called update damping). None of this applies to our second-order algorithms, which I assume are irrelevant in your context.

How _exactly_ do you want to define `D_in` and `D_out`?

**Comment by ftsong22** [comment]
Thanks for your reply, and sorry for the confusion. By D_out I mean the new density matrix formed by solving the eigenvalue problem, i.e. “constructing a new density matrix from those orbitals”. And D_in means the density matrix after mixing, which I assume will serve as the initial density for the next iteration? (For the first iteration D_in should just be the initial guess like SAD )

Is this definition consistent? And how is the process you describe different from those plane wave methods? Is it because there is no such thing as DIIS for the fock matrix in plane wave methods?

**Comment by JonathonMisiewicz** [comment]
I'm still confused. You say that `D_in` is the density matrix "after mixing". What exactly is "mixing"? My best guess is that this is related to what we call "update damping", but I don't know.

I'm only vaguely familiar with plane wave methods, so I'm not qualified to explain what exactly the differences are. What I meant was that "ten minutes of Google reading has me convinced that the approach to mixing there is very different from quantum chemistry."

**Comment by ftsong22** [comment]
Thank you! I see the confusion. In plane wave methods and DFT textbooks, the DIIS (also known as density mixing) is performed on electron density for faster convergence. But it seems that in quantum chemistry the DIIS is performed on the Hamiltonian, and thus the density mixing (or update damping you mentioned) becomes optional?

In this case, my definition makes little sense, and I might need some reconsideration.

**Comment by JonathonMisiewicz** [comment]
Right. In quantum chemistry, given a density, we construct an _effective_ one-electron Hamiltonian called the Fock matrix. DIIS is an extrapolation on previous Fock matrices, not previous densities.

**Comment by susilehtola** [comment]
The big difference between AO and plane wave methods is that plane-wave bases are **verbose**. The reason why plane-wave methods don't accelerate convergence using the Fock matrix is that **it is typically never built** since it could not be stored. Instead, it is always contracted right away with trial vectors, as in traditional configuration interaction approaches, for example. The acceleration based on Fock matrix extrapolation is much more efficient than one based on the electron density.

**Comment by JonathonMisiewicz** [comment]
This issue doesn't make sense as written, given that Psi is not a plane wave code.
