### ISSUE TITLE
plug-in compilation problem

### ISSUE THREAD

**Issue by hernan3009** [psi4/psi4#308]
Hello,

I am trying to compile a plug-in as described in http://www.psicode.org/psi4manual/master/plugins.html .
The plug-in is one of those used as example (https://github.com/psi4/psi4/tree/master/plugins/mointegrals).

All I did is: 
 1. Create a directory. 
 2. Copy into it the files from the last link.
 3. Execute: `psi4 --new-plugin myplugin +mointegrals`
 3''. Alternatively I tried `psi4 --new-plugin myplugin mointegrals`
 4. Change dir to the new directory and execute `make`.

It returns:
`Makefile:15: /build/buildd/psi4-4.0~beta5+dfsg/builddir/src/bin/MakeVars: No existe el archivo o el directorio
make: *** No hay ninguna regla para construir el objetivo «/build/buildd/psi4-4.0~beta5+dfsg/builddir/src/bin/MakeVars».  Alto.`
(The file or directory doesn't exist.  There is no rule to build the target. Stop.)

What I'm doing wrong?

My work station is running linux Ubuntu LTS 14.04. The psi4 version is the last stable release. 

I'm trying to compile the plug-in with the hope it helps me to build the full CI matrix. If Psi4 provides a simple way to generate the Hamiltonian matrix elements it would be even more useful to me.

Thank you very much for your time and the opportunity of using your software.

**Comment by loriab** [comment]
I'm troubled by your steps 1 & 2. The command ``psi4 --new-plugin myplugin +mointegrals`` (which can be executed anywhere in your filesystem– in or out of the psi4 repo clone doesn't matter) _creates_ a new directory `myplugin` already populated by various files, which you should be able to cd into and execute `make` within. Steps 1 & 2 shouldn't be necessary. They might be interfering b/c the name of the directory is bound up in the name of the plugin, which requirement the ``--new-plugin`` automatically satisfies. That is, once you're done with the experimentation stage, choose your name `myplugin` carefully, because it's a bother to switch out later.

Or are you generating a plugin from the conda binary? That requires a little different procedure.

**Comment by hernan3009** [comment]
Thank you for answer. 
"Or are you generating a plugin from the conda binary?". I am unsure about that but I bet no. I get the plug-in from https://github.com/psi4/psi4/tree/master/plugins/mointegrals , my psi4 version is packaged in the official Ubuntu repository (in a .deb file).
The command `psi4 --new-plugin myplugin +mointegrals` created the new directory. This is the new directory where I tried the `make` command without success.
For clarity it is the complete steps please see this PasteBin link http://pastebin.com/qMSc8yq4

**Comment by loriab** [comment]
I see. Yes, you can forget the conda binary question. Interesting that you're using psi4 from the Ubuntu repository. I think you're the first report we've had of someone actually doing that. Unfortunately, it means you're using the beta5 version that's two years old and  pre GnuMake --> CMake transition. And the plugin system I wouldn't expect to work from the Ubuntu repo. You see, the plugin Makefile relies on info about the build conditions and unless whoever packaged psi up for Ubuntu/Debian (not us) knew about that aspect and planned for it, that build condition info is not going to be in the distribution you've got. Your error involving "MakeVars" reflects this.

I'd strongly recommend cloning from GitHub (you'll get a far newer version of the code), building psi4, and _then_ creating a new plugin. https://github.com/psi4/psi4/wiki/1_Obtaining#clone-from-public-github-repository

If you're not comfortable with compiling, there's another way that I know to work, but its a bit experimental.

**Comment by hernan3009** [comment]
Thank you very much loriab. I will try to compile it and I'll tell you how it go.

Regards

**Comment by hernan3009** [comment]
It was possible to compile and install psi4 without problems, but the `make` command returned

`hernan@carlos:~/Power Method/Psi4/pluginintegrales$ make
/usr/bin/g++ -DHAVE_MM_MALLOC_H -DENABLE_CHEMPS2=1 -DFC_SYMBOL=2 -DHAVE_SYSTEM_NATIVE_LAPACK -DHAVE_SYSTEM_NATIVE_BLAS -DHAS_CXX11_VARIADIC_TEMPLATES -DHAS_CXX11_STATIC_ASSERT -DHAS_CXX11_SIZEOF_MEMBER -DHAS_CXX11_RVALUE_REFERENCES -DHAS_CXX11_NULLPTR -DHAS_CXX11_LONG_LONG -DHAS_CXX11_LAMBDA -DHAS_CXX11_INITIALIZER_LIST -DHAS_CXX11_DECLTYPE -DHAS_CXX11_CSTDINT_H -DHAS_CXX11_CONSTEXPR -DHAS_CXX11_AUTO_RET_TYPE -DHAS_CXX11_AUTO -DHAS_CXX11_FUNC -DHAS_CXX11 -DSYS_LINUX -DRESTRICT=__restrict__ -Xlinker -export-dynamic -fPIC -std=c++11 -fopenmp -O3 -DNDEBUG -Wno-unused -I/home/hernan/Programas/psi4/instalacion/interfaces/include -I/home/hernan/Programas/psi4/instalacion/src/lib -I/home/hernan/Programas/psi4/psi4/src/lib -I/home/hernan/Programas/psi4/psi4/include -I/home/hernan/Programas/psi4/instalacion/include -I/home/hernan/Programas/psi4/instalacion/boost/include -I/usr/include/python2.7 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -c pluginintegrales.cc
pluginintegrales.cc: In function ‘psi::PsiReturnType psi::pluginintegrales::pluginintegrales(psi::Options&)’:
pluginintegrales.cc:63:64: error: ‘class psi::Process::Environment’ has no member named ‘wavefunction’
     boost::shared_ptr<Wavefunction> wfn = Process::environment.wavefunction();
                                                                ^
make: *** [pluginintegrales.o] Error 1`

**Comment by dgasmith** [comment]
Ah, we recently changed some Psi4 infrastructure and there is no longer a global wavefunction as the error mentions. This is either occurring because:
1) Your PSIDATADIR path is pointing to an older library version
2) You wrote a custom plugin that still uses this functionality. Please view the following topic: http://forum.psicode.org/t/wavefunction-passing-update/139

Cheers,
Daniel Smith

**Comment by hernan3009** [comment]
Thank you dgasmith. I've just seen that loriab fixed some plugins including the one I need (https://github.com/loriab/psi4/commit/1b6328cdae9895ca1cabfb31656710fa8f00e30c), so thank you very much again loriab.

I will try this new version soon, when I have access to my office PC.

Cheers,

Hernán

**Comment by loriab** [comment]
Yes, sorry, we've been doing a lot of infrastructure changes lately related to that `Wavefunction` object you saw in the `make` error message, and that mointegrals plugin template had escaped updating.

I don't know how familiar you are with GitHub, so I'll warn you that that commit with the fixes is in a pull request to my forked repository. Right now tests are running to check if that commit is safe to merge into this main repository. The only impact that this has on you is that `git pull`ing _this_ repository won't get that new commit at this moment. So if you want to try it out on your plugin before the commit gets merged, just edit the file by hand according to the pattern you see in the commit.

**Comment by hernan3009** [comment]
Hello.  Thank you for explain me. I still have some problems with this plug-in, it seems like I am doing something wrong or the plugin does not work yet.

I make a complete pastebin to make it simpler to analyze: http://pastebin.com/4EAjU7CC

Cheers,

Hernán

**Comment by loriab** [comment]
I don't think you've pulled from github since the plugin fix was added. As long as your `printmo.cc` has `Process::environment.wavefunction();` in it, you'll keep getting this error. This (https://github.com/psi4/psi4/blob/master/share/plugin/mointegrals.cc.template) is the corrected template.

**Comment by hernan3009** [comment]
Thank you again loriab. Finally it was possible to me compile the plugin . I had some issues. After your last comment I get insecure about if I used the corrected code previously (before I tried from the link (https://github.com/loriab/psi4/commit/1b6328cdae9895ca1cabfb31656710fa8f00e30c), so I used the link you shared in the last message. I clean the directory and started again with the new code. The `make` command gave again the same error message. `grep` does not return matches in the original `.cc` file so I inspected the automatically generated `.cc` file.  I noticed some differences (many of them seems to be intentionally changed) but not all of them. In essence, by comparing with the file you edited,  I replaced in the new `.cc` file `wfn` with `ref_wfn`few times and add `SharedWavefunction ref_wfn` as the first argument of the function `printmo` (the name of my plugin). The final result is: http://pastebin.com/bX9jDxi5 .
I do not know if the above is because a bug of the generator of files for the plugin or just me, as I found very extraneous the changes between files, but inspecting the files I really do not find in the original `cc` file what appeared in the generated one, and I cleaned everything to avoid versions problems . The original is: http://pastebin.com/Yb4pLq6j .
Excuse because of the long message but I tried to put my grain of sand.

Now I'll try the plugin :-) , thank you very much again

**Comment by loriab** [comment]
All the plugin templates are working now (I tried them myself last week). I think those last issues you had were from lingering files or mixing plugins/mointegrals/ with share/plugins/mointegrals.cc_template . If you have more code concerns repost here or for general questions, please try the forum (http://forum.psicode.org/)
