### ISSUE TITLE
`psi4` installed via `conda` fails to run when installed in symlinked directory

### ISSUE THREAD

**Issue by dotsdl** [psi4/psi4#3084]
Installing `psi4` via `conda`/`mamba` with:

```
$ mamba create -n psi4-env -c conda-forge -c conda-forge/label/libint_dev psi4
```
when the env directory is in a symlinked directory, such as on an HPC cluster where `/home` is a symlink, gives something like the following when attempting to run `psi4`:

```
$ mamba activate psi4-env
$ psi4 --version
Traceback (most recent call last):
  File "/lila/home/dotson/mambaforge/envs/psi4-env/bin/psi4", line 205, in <module>
    with (psi4_module_loc / "metadata.py").open() as fp: verline = fp.readline()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lila/home/dotson/mambaforge/envs/psi4-env/lib/python3.12/pathlib.py", line 1014, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/lila/home/conda/feedstock_root/build_artifacts/psi4_1698452227439/work/build/stage/lib/python3.12/site-packages/psi4/metadata.py'
```

Working with @bennybp to troubleshoot, it appears that adding use of `.resolve()` to [these Path constructions](https://github.com/psi4/psi4/blob/e3d46319d3a11d571c1c362eeaf7f6641978515c/psi4/run_psi4.py#L129-L131) solves this issue. This resolves (heh) the mismatch that otherwise happens between the paths that were `.resolve()`ed and these that weren't, which causes problems further down.

**Comment by loriab** [comment]
Thanks, added in #3021
