### ISSUE TITLE
MBIS_VOLUME_RATIOS behaviour

### ISSUE THREAD

**Issue by q-posev** [psi4/psi4#3085]
Hello Psi4.

I have been doing some `oeprop` calculations and noticed that the `oeprop` module is case-sensitive, meaning some properties are not computed if requested from `oeprop` in lower case. Perhaps it is a common knowledge, but since this was not mentioned in the `oeprop` documentation - I bring it here.

However, my issue is related to `MBIS_VOLUME_RATIOS`. When given in lower case to `oeprop` - Psi4 performs free-atom calculations for each atom type in the molecule (confirmed by `.log` file contents too), but does not perform (or at least does not print) the MBIS volume ratios. Thus, it seems like it does some premilinary MBIS calculations to get free-atom volumes, which is a bit surprising since I would expect it to ignore the `mbis_volume_ratios` option whatsoever (since it's lower-case). When given in upper case - Psi4 runs and prints as expected. The issue is really when the option is given in lower case.

Observed with both Psi4 v.1.8 and 1.8.2 installed via `conda-forge`

Code to reproduce:

```python
molecule lig {
0 1
O   0.0  0.5  0.0
H   0.5  0.0  0.0
H  -0.5  0.0  0.0

no_reorient
symmetry c1
}

set basis def2-TZVPPD
set print 2

grad, wfn = gradient('wb97m-d3bj', return_wfn=True)
oeprop(wfn, 'dipole',  'quadrupole', 'mbis_volume_ratios')
```

**Comment by philipmnel** [comment]
Thanks for the bug report. This should be fixed by #3086.
