### ISSUE TITLE
Psi4 fails to configure

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#3092]
The up-to-date master branch fails to configure in Fedora
```
$ cmake ..
CMake Error at CMakeLists.txt:5 (cmake_policy):
  Policy "CMP0144" is not known to this version of CMake.
$ rpm -q cmake
cmake-3.27.7-1.fc39.x86_64
```

**Comment by loriab** [comment]
Yes, FAE alerted to that, too. It's fixed in https://github.com/psi4/psi4/pull/3090, if you want to approve that. Or comment out the CMP0144 for now.
