### ISSUE TITLE
detci rohf mp2

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#311]
@CDSherrill, here's the rohf mp2 results from a few programs. Ugur matches Q-Chem. Molpro is fairly close to Q-Chem, though I'm really not sure about that input. "rccsd" "calls spin-restricted open-shell coupled cluster program" according to the manual, but this route through the code is not labeled enough for me to be confident of it. So detci is the odd one out, but good news is that its reference is sound.

| program | fc | scf | singles | mp2corl | mp2tot |
| --- | --- | --- | --- | --- | --- |
| occ | fc | -25.94361432 | -0.00068837 | -0.05940725 | -26.00302157 |
| detci | fc | -25.94361432 |  | -0.06094168 | -26.00455600 |
| qchem | fc | -25.94361432 | -0.00068837 | -0.05940725 | -26.00302157 |
| molpro | fc | -25.94361432 | -0.00054735 | -0.05936497 | -26.00297929 |

```
$molecule
1 2
B     0.10369114     0.00000000     0.00000000
H    -1.13269886     0.00000000     0.00000000
H     3.00000000     0.37149000     0.00000000
H     3.00000000    -0.37149000     0.00000000
$end

$rem
JOBTYPE            sp
unrestricted       false
n_frozen_core        fc
scf_guess sad
BASIS              cc-pVdZ
basis2 6-31g
correlation        mp2
THRESH             12
SCF_CONVERGENCE    8
SYM_IGNORE         TRUE
SYMMETRY           FALSE
MEM_TOTAL          1600
MEM_STATIC         512
INTEGRALS_BUFFER   512
MAX_SCF_CYCLES     200
$end
```

```
molecule bh_h2p {
1 2
B     0.10369114     0.00000000     0.00000000
H    -1.13269886     0.00000000     0.00000000
H     3.00000000     0.37149000     0.00000000
H     3.00000000    -0.37149000     0.00000000
}

set basis cc-pvdz
set scf_type pk
set mp2_type conv
set guess sad
set freeze_core true
set e_convergence 8
set d_convergence 7
set reference rohf

set qc_module detci  # toggle detci/occ
energy('mp2')
```

```
memory,200,m
nosym
noorient
angstrom
geometry={
B     0.10369114     0.00000000     0.00000000
H    -1.13269886     0.00000000     0.00000000
H     3.00000000     0.37149000     0.00000000
H     3.00000000    -0.37149000     0.00000000
}

GTHRESH,ZERO=1.e-14,ONEINT=1.e-14,TWOINT=1.e-14,ENERGY=1.e-9

SET,CHARGE=1
SET,SPIN=1

basis=cc-pVDZ

rhf
rccsd
```

**Comment by dgasmith** [comment]
How far back can you run the ROHF MP2 code with DETCI? It might be good to double check that I have not broken anything in the past 6 months+

Cheers,
Daniel Smith

**Comment by loriab** [comment]
With some python-wrangling, I revived a beta5 (c. mid 2013), and detci is the same. You're exonerated, @dgasmith . (Note to anyone trying this, you'll have to run a mp4 to secure access to detci, since this was way before `qc_module`.)

**Comment by loriab** [comment]
Cfour has joined occ & qchem in disagreeing with detci rohf mp2. I'm thinking detci rohf should be retired.

**Comment by andysim** [comment]
I think the difference is likely due to the frozen core.  If the problem disappears when all electrons are correlated, I have an explanation.  For ROMP calculations, the Fock matrix isn't diagonalized, so needs to be semicanonicalized.  This involves separately diagonalizing the occ-occ block of alpha and beta spaces separately, thus breaking the alpha-beta symmetry and making the next step look a little more like UMP2.  Some codes just diagonalize the full occ-occ space during this process.  Others don't want to mix frozen core and active occ, so they only diagonalize the active occ - active occ subblock.  My very hazy memory is that CFOUR and Psi4 did the same thing waaaay back in the day, while Molpro took the other approach.  I don't think either is correct or incorrect - it's just a choice that is to be made.

**Comment by Diazonium** [comment]
@andysim The Molpro devs claim their choice is more computationally efficient, see the bottom of this page: [https://www.molpro.net/info/2015.1/doc/manual/node374.html](url)

**Comment by loriab** [comment]
detci is the odd one out for all-electron, too.

`detci`:
```
   ==> Starting MPn CI Computation <==

   CalcInfo_->escf =       -25.943614318544544
   CalcInfo_->e0   =       -20.206929918475634
   CalcInfo_->enuc =         4.919538206883576
   CalcInfo_->e1   =       -10.656222606952486

   n         Corr. Energy                  E(MPn)               n         Corr. Energy                  E(MPn)

   0          0.000000000000000       -15.287391711592058
   1        -10.656222606952486       -25.943614318544544
   1        -10.656222606954266       -25.943614318546324
   2         -0.062024390690629       -26.005638709235175       2        -0.062024390690629       -26.005638709235175
                                                                3        -0.014835841878215       -26.020474551113388

    MP2 energy saved

    EMPn = -26.0056387092352


   ==> Energetics <==

    SCF energy =          -25.943614318544544
    Total MP energy =     -26.005638709235175
```

`CFOUR` (semicanonical default):
```
           '            ------------------------------------------------\n'
           '            E(SCF)                  =    -25.943614318546 a.u.\n'
           '            E2(AA)                  =     -0.001912085148 a.u.\n'
           '            E2(BB)                  =     -0.000092824531 a.u.\n'
           '            E2(AB)                  =     -0.057779155613 a.u.\n'
           '            E2(SINGLE)              =     -0.000694049865 a.u.\n'
           '            E2(TOT)                 =     -0.059784065292 a.u.\n'
           '            Total MP2 energy        =    -26.004092433703 a.u.\n'
           '            ------------------------------------------------\n'
```

`CFOUR` (forced standard orbitals):
```
           '            ------------------------------------------------\n'
           '            E(SCF)                  =    -25.943614318546 a.u.\n'
           '            E2(AA)                  =     -0.001908947129 a.u.\n'
           '            E2(BB)                  =     -0.000092848566 a.u.\n'
           '            E2(AB)                  =     -0.057404620910 a.u.\n'
           '            E2(SINGLE)              =     -0.000687431838 a.u.\n'
           '            E2(TOT)                 =     -0.059406416605 a.u.\n'
           '            Total MP2 energy        =    -26.003708166988 a.u.\n'
           '            ------------------------------------------------\n'
```

**Comment by andysim** [comment]
Interesting find, @Diazonium.  I'm probably being very slow here, but it's not clear to me why the core orbitals will need to be transformed in either version of the algorithm.  *If* they are neglected in both algorithm, the only efficiency gain would be the neglect of the frozen orbitals in the diagonalization, which would be negligible.

@loriab Steven Wheeler wrote an arbitrary order ZAPT (z averaged perturbation theory) implementation for DETCI back in the day.  I wonder if that's what's being activated?  That method doesn't break the alpha-beta symmetry and is quite different to semicanonical ROMP theory.

**Comment by loriab** [comment]
Yes, that's a handy Molpro page to keep bookmarked, thanks!

sadly, `energy('zapt2')` is a different call with a different answer. 

```   ==> Starting MPn CI Computation <==

   CalcInfo_->escf =       -25.943614318544558
   CalcInfo_->e0   =       -20.492192306874799
   CalcInfo_->enuc =         4.919538206883576
   CalcInfo_->e1   =       -10.370960218553336

   n         Corr. Energy                  E(ZAPTn)             n         Corr. Energy                  E(ZAPTn)

   0          0.000000000000000       -15.572654099991222
   1        -10.370960218553336       -25.943614318544558
   1        -10.370960218555073       -25.943614318546295
   2         -0.059970897144711       -26.003585215689270       2        -0.059970897144711       -26.003585215689270
                                                                3        -0.015564779310290       -26.019149994999559

    ZAPT2 energy saved

    EZAPTn = -26.0035852156893
```
