### ISSUE TITLE
DDX_SOLVENT_EPSILON ignored over DDX_SOLVENT

### ISSUE THREAD

**Issue by bismuthadams1** [psi4/psi4#3119]
I am currently testing out the ddx solvent model implementation (https://psicode.org/psi4manual/master/ddx.html) in my high throughput script. However, currently the DDX_SOLVENT_EPSILON option being ignored in favor of DDX_SOLVENT. 

According to the manual, DDX_SOLVENT is ignored if DDX_SOLVENT_EPSILON is supplied. Initially I took this as meaning one could *just* supply the DDX_SOLVENT_EPSILON value directly. However, without supplying the DDX_SOLVENT field too, the calculation fails with `psi4.driver.p4util.exceptions.ValidationError: Required option 'DDX_SOLVENT' is missing.`. Hence, in my high throughput script I provided a placeholder in this field if the DDX_SOLVENT_EPSILON option is selected:

```
  #check if dialetric constant is specified or not
                    if settings.ddx_settings.epsilon is not None:
                        print('ddx numeric option')
                        psi4.set_options({"ddx": "true", #supply a solvent here to see if epsilon then gets picked up
                        "DDX_SOLVENT_EPSILON": settings.ddx_settings.epsilon,
                        "DDX_RADII_SET": settings.ddx_settings.radii_set,
                        "DDX_MODEL": settings.ddx_settings.ddx_model,
                        "DDX_SOLVENT":"water"})  #without this calculation fails with psi4.driver.p4util.exceptions.ValidationError: Required option 'DDX_SOLVENT' is missing.
                    else:
                        print('ddx solvent option')
                        psi4.set_options({"ddx": "true",
                        "DDX_SOLVENT": settings.ddx_settings.solvent,
                        "DDX_RADII_SET": settings.ddx_settings.radii_set,
                        "DDX_MODEL": settings.ddx_settings.ddx_model})
```
However, when I run a testcase  when inspecting the output file, the solvent_epsilon is printed out as 78.3553 not the test value 4 which I used in my test run. 

It appears the issue lies in the if else statement in psi4/driver/procrouting/solvent/ddx.py, where the if statement core.has_option_changed("DDX", "DDX_SOLVENT_EPSILON") is not assigned as true (I added print statements to validate this):
```
 solvent = core.get_option("DDX", "DDX_SOLVENT").lower()
    print(f'solvent option chosen is {solvent}') 
    if core.has_option_changed("DDX", "DDX_SOLVENT_EPSILON"):  #this given as false
        solvent_epsilon = core.get_option("DDX", "DDX_SOLVENT_EPSILON")
        print(f'epsilon option {solvent_epsilon}')
    elif solvent == "":
        raise ValidationError("Required option 'DDX_SOLVENT' is missing.")
    elif solvent not in pyddx.data.solvent_epsilon:
        raise ValidationError("Unknown solvent {solvent}.")
    else:
        solvent_epsilon = pyddx.data.solvent_epsilon[solvent]
```
I have built a minimal worked example of the problem below where the issue is again replicated where the solvent_epsilon is set to that of water, and the DDX_SOLVENT_EPSILON option is ignored: 
```
import psi4

h2o = psi4.geometry("""
O
H 1 0.96
H 1 0.96 2 104.5
""")

psi4.set_options({"ddx": "true", #supply a solvent here to see if epsilon then gets picked up
                "DDX_SOLVENT_EPSILON":'5',
                "DDX_RADII_SET": 'uff',
                "DDX_MODEL": 'PCM',
                "DDX_SOLVENT":"water"})  #without this calculation fails with psi4.driver.p4util.exceptions.ValidationError: Required option 'DDX_SOLVENT' is missing.

psi4.set_memory('500mb')

psi4.energy('scf/sto-3g')
```

**Comment by mfherbst** [comment]
Thanks for reaching out.

> According to the manual, DDX_SOLVENT is ignored if DDX_SOLVENT_EPSILON is supplied. Initially I took this as meaning one could just supply the DDX_SOLVENT_EPSILON value directly.

This is indeed the intended behaviour and I am indeed surprised why our implementation does not reach this result. From my understanding this is what should happen in the current implementation due to the  `has_option_changed`. Also this behaviour (changing epsilon without providing a solvent) is used in the unit tests, so I'm surprised they don't fail.

Maybe somebody else has an idea ?

**Comment by bismuthadams1** [comment]
I just had a look at the tests, I realise I had been using a string as the input for the solvent, but it should be float/int type! So this was indeed user error.
