### ISSUE TITLE
Problem with linking boost::regex 1.60.0

### ISSUE THREAD

**Issue by aoleynichenko** [psi4/psi4#312]
Hello!

I'm trying to compile Psi4 on my laptop and I have a problem. As described here [https://github.com/psi4/psi4/wiki/3_Building#builddetailed], I've run setup script, then I've entered $top/objdir and typed 'make -j8'. Compilation was successful, but I've got a linking error.

Operating system is ArchLinux 4.2.5. I have Python2.7 and Python3.5 both installed on my computer, LAPACK, BLAS, boost, perl are also installed. It seems like ld cannot link psi4 with boost::regex. When I didn't specified usage of Python2 in the setup script command line, there were linking errors due to different versions of python in Psi (python3) and python in boost (python2). Without specifying '--chemps2 off' the compilation also fails to start.

To help setup script in detecting boost libraries on my computer, I've tried to run setup with '--boost-incdir=/usr/include --boost-libdir=/usr/lib' options. I've also tried to find in automatically generated makefiles the invocation of ld (I wanted to add option '-lboost_regex' to linker), but I have not found.
Could you tell me, please, what is wrong? How can I fix this problem?

Thank you very much!
Alexander

Output of the 'setup' script:
[piton@avo psi4]$ ./setup --chemps2 off --python=/usr/bin/python2
 cmake  -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DENABLE_MPI=OFF -DENABLE_SGI_MPT=OFF -DENABLE_OMP=ON -DENABLE_VECTORIZATION=OFF -DENABLE_CSR=OFF -DENABLE_SCALAPACK=OFF -DENABLE_SCALASCA=OFF -DENABLE_UNIT_TESTS=OFF -DENABLE_STATIC_LINKING=OFF -DENABLE_PLUGINS=OFF -DENABLE_CHEMPS2=OFF -DENABLE_CXX11_SUPPORT=ON -DLIBINT_OPT_AM=5 -DEXECUTABLE_SUFFIX= -DPYTHON_INTERPRETER=/usr/bin/python2 -DCMAKE_INSTALL_PREFIX=/usr/local/psi4 -DCMAKE_BUILD_TYPE=release /home/piton/gitdir/psi4

-- System                : Linux
-- Processor type        : x86_64
-- C++ compiler flags    : -DRESTRICT=__restrict__ -Xlinker -export-dynamic -fPIC -std=c++11 -fopenmp -O3 -DNDEBUG -Wno-unused
-- C compiler flags      : -std=c99 -DRESTRICT=__restrict__ -DFUNDERSCORE=1 -fPIC -fopenmp -O3
-- Libraries             : /lib64/libblas.so;/lib64/liblapack.so
-- Definitions           : SYS_LINUX;HAS_CXX11;HAS_CXX11_FUNC;HAS_CXX11_AUTO;HAS_CXX11_AUTO_RET_TYPE;HAS_CXX11_CONSTEXPR;HAS_CXX11_CSTDINT_H;HAS_CXX11_DECLTYPE;HAS_CXX11_INITIALIZER_LIST;HAS_CXX11_LAMBDA;HAS_CXX11_LONG_LONG;HAS_CXX11_NULLPTR;HAS_CXX11_LIB_REGEX;HAS_CXX11_RVALUE_REFERENCES;HAS_CXX11_SIZEOF_MEMBER;HAS_CXX11_STATIC_ASSERT;HAS_CXX11_VARIADIC_TEMPLATES;HAVE_SYSTEM_NATIVE_BLAS;HAVE_SYSTEM_NATIVE_LAPACK;FC_SYMBOL=2;HAVE_MM_MALLOC_H
WARNING: Target "psi4so" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
-- The CXX compiler identification is GNU 5.2.0
-- The C compiler identification is GNU 5.2.0
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test _HAS_CXX11_FLAG
-- Performing Test _HAS_CXX11_FLAG - Success
-- Found following supported C++11 features:
--   __func__
--   auto
--   auto_ret_type
--   constexpr
--   cstdint
--   decltype
--   initializer_list
--   lambda
--   long_long
--   nullptr
--   regex
--   rvalue-references
--   sizeof_member
--   static_assert
--   variadic_templates
-- Checking for restrict keyword
--    keyword found : __restrict__
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Math lib search order is MKL;ESSL;ATLAS;ACML;SYSTEM_NATIVE
-- You can select a specific type by defining for instance -D BLAS_TYPE=ATLAS or -D LAPACK_TYPE=ACML
-- or by redefining MATH_LIB_SEARCH_ORDER
-- Found BLAS: SYSTEM_NATIVE (/lib64/libblas.so)
-- Found LAPACK: SYSTEM_NATIVE (/lib64/liblapack.so)
-- No Sphinx, no docs. Pre-built documentation at http://sirius.chem.vt.edu/psi4manual/latest/index.html
-- Found libutil: /usr/lib64/libutil.so  
-- Found libm: /usr/lib64/libm.so  
-- Found librt: /usr/lib64/librt.so  
-- Found libdl: /usr/lib64/libdl.so  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.11") 
-- Found Python: /usr/lib64/libpython2.7.so  
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   filesystem
--   python
--   regex
--   serialization
--   system
--   timer
--   chrono
--   thread
-- Looking for MKL_Free_Buffers
-- Looking for MKL_Free_Buffers - not found
-- Looking for include file mm_malloc.h
-- Looking for include file mm_malloc.h - found
-- Use the commands in setup_command to reproduce this build
-- Configuring done
-- Generating done
-- Build files have been written to: /home/piton/gitdir/psi4/objdir

   configure step is done
   now you need to compile the sources:
   >>> cd objdir
   >>> make

Error message:

[100%] Linking CXX executable ../../../bin/psi4
CMakeFiles/psi4_objlib.dir/create_new_plugin.cc.o: In function `boost::re_detail_106000::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_imp()':
create_new_plugin.cc:(.text._ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE9match_impEv[_ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE9match_impEv]+0x42d): undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&)'
CMakeFiles/psi4_objlib.dir/create_new_plugin.cc.o: In function `bool boost::regex_match<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > >&, boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)':
create_new_plugin.cc:(.text._ZN5boost11regex_matchIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS5_EEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEEEbT_SD_RNS_13match_resultsISD_T0_EERKNS_11basic_regexIT1_T2_EENS_15regex_constants12_match_flagsE[_ZN5boost11regex_matchIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS5_EEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEEEbT_SD_RNS_13match_resultsISD_T0_EERKNS_11basic_regexIT1_T2_EENS_15regex_constants12_match_flagsE]+0xd6): undefined reference to `boost::re_detail_106000::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
CMakeFiles/psi4_objlib.dir/create_new_plugin.cc.o: In function `boost::re_detail_106000::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_match()':
create_new_plugin.cc:(.text._ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE11match_matchEv[_ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE11match_matchEv]+0x1a0): undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&)'
../../../lib/lib3index.a(denominator.cc.o): In function `bool boost::regex_match<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > >&, boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags) [clone .constprop.286]':
denominator.cc:(.text+0x8db7): undefined reference to `boost::re_detail_106000::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
../../../lib/libefp_solver.a(efp_solver.cc.o): In function `psi::efp::EFP::print_efp_geometry()':
efp_solver.cc:(.text+0x7c70): undefined reference to `boost::re_detail_106000::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
../../../lib/libmints.a(oeprop.cc.o): In function `psi::OEProp::compute()':
oeprop.cc:(.text+0x1d8c2): undefined reference to `boost::re_detail_106000::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
../../../lib/libmints.a(basisset_parser.cc.o): In function `bool boost::regex_match<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > >&, boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags) [clone .constprop.303]':
basisset_parser.cc:(.text+0xf55): undefined reference to `boost::re_detail_106000::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
../../../lib/libmints.a(basisset_parser.cc.o): In function `psi::BasisSetParser::load_file(std::string const&, std::string const&)':
basisset_parser.cc:(.text+0x35e6): undefined reference to `boost::re_detail_106000::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
../../../lib/libmints.a(basisset_parser.cc.o):basisset_parser.cc:(.text+0x3948): more undefined references to `boost::re_detail_106000::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)' follow
../../../lib/libmints.a(molecule.cc.o): In function `boost::re_detail_106000::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_prefix()':
molecule.cc:(.text._ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE12match_prefixEv[_ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcSsEESaINS_9sub_matchIS6_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE12match_prefixEv]+0x14c): undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&)'
../../../lib/libmints.a(matrix.cc.o): In function `bool boost::regex_match<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > >&, boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags) [clone .constprop.319]':
matrix.cc:(.text+0x14f47): undefined reference to `boost::re_detail_106000::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
collect2: ошибка: выполнение ld завершилось с кодом возврата 1
src/bin/psi4/CMakeFiles/psi4.dir/build.make:192: ошибка выполнения рецепта для цели «bin/psi4»
make[2]: *** [bin/psi4] Ошибка 1
CMakeFiles/Makefile2:4722: ошибка выполнения рецепта для цели «src/bin/psi4/CMakeFiles/psi4.dir/all»
make[1]: *** [src/bin/psi4/CMakeFiles/psi4.dir/all] Ошибка 2
Makefile:138: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2

**Comment by jturney** [comment]
I do know there is a bug in Boost 1.60.0 that prevents Psi4 from working. It's been documented here #243 and with the Boost people.

Could you try passing ```-DBUILD_CUSTOM_BOOST=ON``` to the ```setup``` script?

**Comment by aoleynichenko** [comment]
Thank you very much! I've passed -DBUILD_CUSTOM_BOOST=ON to the setup script, and compilation and linking were completed successfully! However, one of 299 tests was failed.

Regards,
Alexander

`99% tests passed, 1 tests failed out of 299

Label Time Summary:
adc            =  34.90 sec (2 tests)
autotest       = 175.66 sec (26 tests)
casscf         =   8.94 sec (8 tests)
cc             = 402.14 sec (59 tests)
cdomp2         =   1.93 sec (2 tests)
cepa           =   2.56 sec (5 tests)
ci             =   0.76 sec (1 test)
cisd           =  13.09 sec (7 tests)
cubeprop       =   1.58 sec (1 test)
dcft           = 237.84 sec (13 tests)
df             = 162.69 sec (32 tests)
dfccd          =   0.38 sec (1 test)
dfccd-grad     =   1.05 sec (1 test)
dfccdl         =   0.39 sec (1 test)
dfccsd         =   0.46 sec (1 test)
dfccsd-grad    =   1.40 sec (1 test)
dfccsdat       =   0.82 sec (1 test)
dfccsdl        =   0.48 sec (1 test)
dfccsdt        =   0.63 sec (1 test)
dfmp2          =  50.96 sec (8 tests)
dfomp2         =   8.14 sec (6 tests)
dfomp2.5       =   6.34 sec (4 tests)
dfomp3         =   6.42 sec (4 tests)
dfscf          =  77.65 sec (1 test)
dft            = 549.70 sec (10 tests)
docs           =   0.49 sec (3 tests)
fci            =  18.26 sec (6 tests)
findif         = 360.17 sec (5 tests)
fnocc          =  12.59 sec (4 tests)
freq           =   2.36 sec (1 test)
gradient       =  19.53 sec (13 tests)
libefp         =   4.24 sec (5 tests)
longtests      = 2490.57 sec (5 tests)
mcscf          =   0.79 sec (3 tests)
mints          =  20.27 sec (8 tests)
misc           = 125.96 sec (14 tests)
mp2            = 240.79 sec (10 tests)
ocepa          =  31.90 sec (6 tests)
omp            =  35.55 sec (18 tests)
opt            = 911.35 sec (19 tests)
properties     =  13.38 sec (3 tests)
psi            = 5265.29 sec (299 tests)
psimrcc        =  44.08 sec (8 tests)
pywrap         =  98.47 sec (14 tests)
quicktests     = 348.61 sec (87 tests)
rasci          =  28.47 sec (3 tests)
sapt           = 1698.31 sec (7 tests)
scf            = 751.84 sec (29 tests)
shorttests     = 2425.46 sec (206 tests)
sowreap        =   1.22 sec (3 tests)
stability      =   2.04 sec (2 tests)
tutorial       =  23.38 sec (6 tests)
x2c            =   0.96 sec (3 tests)

Total Test time (real) = 5267.01 sec

The following tests FAILED:
	259 - pywrap-opt-sowreap (Failed)
Errors while running CTest`

**Comment by dgasmith** [comment]
We recently overhauled large tracks of Psi4, this test should fail at the moment as we have not yet updated it to align with the new changes. Glad everything compiles now.
