### ISSUE TITLE
Density fiiting question

### ISSUE THREAD

**Issue by hypefolder** [psi4/psi4#3124]
Hello,

Thank you for providing this amazing tool!

I have a question regarding the possibility of using psi4 to project the electron density of a system sampled on a uniform 3D grid to an auxiliary basis. Specifically, if given the atomic positions and values of the electron density of a system on a uniform Cartesian grid is there a method to fit/project this density onto an atom-centered auxiliary basis?

Thanks for your help in advance.

**Comment by PhillCli** [comment]
AFAIK, SAPT(DFT) uses [here](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libsapt_solver/fdds_disp.cc#L245) something similar based on [Almhof (1993)](https://www.sciencedirect.com/science/article/abs/pii/S0166128096800406) section 2.1 `General grid-free DFT`, C++ code is called [here](https://github.com/psi4/psi4/blob/master/psi4/driver/procrouting/sapt/sapt_mp2_terms.py#L111) from Python's driver. Mind it's not exactly what you're looking for, but that should get you started.

Maybe Psi4Numpy has some examples in the DFT tutorial section.

**Comment by hypefolder** [comment]
@PhillCli thank you very much for your detailed answer. The material you pointed me to is exactly what I needed and it's leading to good results. I will provide an update with the details of my implementation for anyone who might find it useful later, but I will close the issue for now.

Thanks again from a new grad student!

Best, 

hypefolder

**Comment by PhillCli** [comment]
> Thanks again from a new grad student!

You're welcome, good luck!
