### ISSUE TITLE
psi4 fails when conda installed in symlinked directory

### ISSUE THREAD

**Issue by chrisiacovella** [psi4/psi4#3126]
This issue is similar to #3084.  For psi4 installed via conda/mamba (both 4.18.2 and 4.19) on an hpc system that has a symlink for the /home directory (the same hpc system in the prior issue), psi4 has trouble resolving paths that don't call `.resolve()`.  while the changes made in response to #3084 mostly fix the issue, there appears to be two other places `.resolve()` should be added:

https://github.com/psi4/psi4/blob/e105cc2346fba36ccacb77bf8944a3dcf6c097f2/psi4/__init__.py#L47-L48

The full error is below:
```
[2024-01-25 07:17:41 EST]     INFO: qcfractalcompute.config: Reading configuration data from configs/config.3049902-1.yaml
Traceback (most recent call last):
  File "/lila/home/iacovec/miniforge3/envs/qcfractalcompute/lib/python3.12/site-packages/qcfractalcompute/run_scripts/qcengine_list.py", line 12, in <module>
    progs = {x: qcengine.get_program(x).get_version() for x in qcengine.list_available_programs()}
  File "/lila/home/iacovec/miniforge3/envs/qcfractalcompute/lib/python3.12/site-packages/qcfractalcompute/run_scripts/qcengine_list.py", line 12, in <dictcomp>
    progs = {x: qcengine.get_program(x).get_version() for x in qcengine.list_available_programs()}
  File "/home/iacovec/miniforge3/envs/qcfractal-worker-psi4-18.2/lib/python3.10/site-packages/qcengine/programs/psi4.py", line 111, in get_version
    raise TypeError(f"Error {rc} retrieving Psi4 version: stdout: {so}, stderr: {se}")
TypeError: Error 1 retrieving Psi4 version: stdout: , stderr: Traceback (most recent call last):
  File "/home/iacovec/miniforge3/envs/qcfractal-worker-psi4-18.2/bin/psi4", line 213, in <module>
    import psi4  # isort:skip
  File "/lila/home/iacovec/miniforge3/envs/qcfractal-worker-psi4-18.2/lib/python3.10/site-packages/psi4/__init__.py", line 64, in <module>
    raise KeyError(f"Unable to read the Psi4 Python folder - check the PSIDATADIR environmental variable - current value is {str(data_dir)}")
KeyError: 'Unable to read the Psi4 Python folder - check the PSIDATADIR environmental variable - current value is /lila/home/conda/feedstock_root/build_artifacts/psi4_1696426865911/work/build/stage/share/psi4'
``` 

To decode this output a little, the failure results from qcarchive trying to get the version of psi4. The specific qcarchive code is here: https://github.com/MolSSI/QCFractal/blob/32a29a86d6673b0ea1a743b02d3af314c2fd164c/qcfractalcompute/qcfractalcompute/run_scripts/qcengine_list.py#L12

The code to query the version in qcarchive  is newer than issue #3084, which is why it probably was not caught at the time.

**Comment by loriab** [comment]
Thanks very much for the report and problem localization. Were you able to test that editing those two lines led to a running psi4 (as opposed to revealing the next problem :-) )? I can understand if permissions on the hpc system don't allow editing.

If those two lines are it, I can work on a v1.9.1 release. @coltonbh, I wonder if this is related to the psi4-in-docker error you were getting.

**Comment by chrisiacovella** [comment]
It was in a local install, so I was able to modify that file; the code is now running as expected on this finicky system.

**Comment by coltonbh** [comment]
My issue was trying to use a `psi4` executable built inside a container from the `psi4` python client from my host machine--i.e., to treat the `psi4` executable as an external executable I could call from `python`; however, the `psi4` python client requires close coupling to the executable (access to shared files) so this separation was not possible because the client has to access files shared with the executable, which are only available inside the container :)

**Comment by loriab** [comment]
v1.9.1 is minted which should fix this.
