### ISSUE TITLE
psi4 1.9.1 is currently incompatible with `main` version of libint (2.9.0)

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [psi4/psi4#3144]
On the [install page](https://psicode.org/installs/v191/), for Linux > Conda > 3.11 > Stable, it returns

```
conda install psi4 python=3.11 -c conda-forge 
```

Should it not be using the conda-forge/label/libint_dev?

I should note that libint main just updated 12 hrs ago and seems to cause some seg faults in psi4 1.91.

**Comment by Andrew-S-Rosen** [comment]
Thanks, just wanted to confirm! I switched to libint==2.8.2 in the meantime but look forward to a new release 👍 Feel free to close when you see fit. I'll update the title.

**Comment by loriab** [comment]
All the new packages are available. No further problems are anticipated, so lmk if there's further trouble. I'll leave this open for a few days for information.

**Comment by j-wags** [comment]
Just reporting that updating to the latest 1.9.1 package shows all green for me :-)

**Comment by JonathonMisiewicz** [comment]
Seeing as there have been no further troubles, closing.
