### ISSUE TITLE
update sapt fitting basis sets

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#317]
For fitting basis sets, SAPT mostly uses `DF_BASIS_SAPT`, which defaults to RI (http://psicode.org/psi4manual/master/sapt.html#df-basis-sapt). The Elst10 and Exch10 are governed by `DF_BASIS_ELST`, which defaults to `DF_BASIS_SAPT` (which defaults to RI). However, this can go awry for heavy elements, whereupon it is recommended to use JK for `DF_BASIS_ELST`. An important bit of the reasoning behind this is that for the small basis sets used for SAPT0, RI is smaller than JK (for cc-pVDZ, 28 to 46). If we're going to change the defaults so that everything works at its best without intervention, now is the time to do it.

* [ ] Run a A·T 0/jadz with SAPT/ELST RI/RI, RI/JK, JK/JK to see if there's significant time penalties
* [ ] If that's not significant, should ELST always be JK to suppress failure mode?
* [ ] Do we want consistent fitting basis used across all terms?
* [ ] If any changes made, update Note in docs about changes in Spring 2016.

sapt2 is the most relevant test case

**Comment by jgonthier** [comment]
So, I had a look in the code. From what I see, `DF_BASIS_ELST` is only ever used in SAPT0. For all higher terms, DF integrals are pre-computed with the `DF_BASIS_SAPT` and then used for everything.

**Comment by loriab** [comment]
Hmm, so either
* the case of running higher-order SAPT on heavy atoms was never considered, in which case the `DF_BASIS_ELST` code needs copying over
* the heavy atom failure mode doesn't appear in higher-order SAPT b/c higher-order terms compensate or because the larger basis-sets targeted do their job (RI > JK for higher-zeta basis sets). Actually, this may have been what @tparker36 was recalling.

**Comment by CDSherrill** [comment]
Hm, this is probably not good for heavy elements and SAPT beyond SAPT0...

**Comment by CDSherrill** [comment]
I suspect we just never got around to adapting the higher order codes.  But
maybe @tparker36 has numerical evidence that it's not as big a deal as we
thought?

**Comment by robparrish** [comment]
I think by the time the JK problem was discovered in SAPT0, the
higher-order SAPT code was already written. So, it remains a problem - even
TZ-RI does not have the needed flexibility for deep stuff.

-Rob

**Comment by jgonthier** [comment]
Does the problem appear for all (oo| type terms ? Induction contains some (oo|ov) terms as well.

**Comment by robparrish** [comment]
Yes, Elst, Exch, and Ind are affected directly. Also, core Fock-terms
appear in Exch-Disp, and those are also affected.

-Rob

**Comment by jgonthier** [comment]
Ew. Does someone have an example case of the failure?

**Comment by loriab** [comment]
Sounds like JK for `DF_BASIS_ELST` in SAPT0 is not so much a _solution_ to the problem (in which case I'd want it implemented in the defaults since now is a good window for tweaking compute details) as a handle so that one can _ameliorate_ the problem. In the absence of a quantitative study to see if there's a real solution among existing fitting basis sets, I'm thinking just implement `DF_BASIS_ELST` for higher-order so it's a handle everywhere.

@jgonthier , Trent was saying argon dimer showed the problem.

**Comment by jgonthier** [comment]
@loriab: `DF_BASIS_ELST` only corrects first-order electrostatics and exchange for now. We can implement this correction for higher-order SAPT pretty easily, but the other terms will not be corrected.

**Comment by robparrish** [comment]
A solution would be to always use Cholesky in higher-order SAPT.

-Rob

**Comment by loriab** [comment]
I'm adding the caution below to the SAPT docs. Together with the caution @robparrish included at the end of the FISAPT docs, it should clarify the situation, as well as summarize this thread. I'm going to close this ticket and add higher-order SAPT to a general Cholesky wishlist ticket. Speak up if there are any objections.

```
.. caution:: To density fit the dispersion terms in SAPT, the RI auxiliary basis 
   controlled through |sapt__df_basis_sapt| set performs well. For Fock-type
   terms (*i.e.*, electrostatics, exchange, induction, and core Fock matrix
   elements in exchange-dispersion), the density-fitting auxiliary basis in
   the :ref:`SAPT module<sec:sapt>` (both SAPT0 and higher-order) is RI (more
   efficient for the small basis sets at which SAPT0 performs best) while the
   :ref:`FISAPT module<sec:fisapt>` uses the more appropriate JKFIT. For
   heavier elements (*i.e.*, second-row and beyond), the RI is unsound
   (insufficiently flexible). For SAPT0 in the :ref:`SAPT module<sec:sapt>`,
   a workaround is to set |sapt__df_basis_elst| (which controls Elst10 and
   Exch10 terms) to a JKFIT basis. For higher-order methods in :ref:`SAPT
   module<sec:sapt>`, there is no workaround; on-the-fly construction of an
   auxiliary basis through Cholesky decomposition (not implemented) is the
   long-term solution.
```
