### ISSUE TITLE
maybe missing "}"

### ISSUE THREAD

**Issue by wszs** [psi4/psi4#3185]
hi friends,did you change the code recently?
libscf_solver/hf.cc:772:22: error: qualified-id in declaration before ‘(’ token
  772 | void HF::compute_fcpi() {
      |                      ^

i think that cause of missing "}" after line 770 in this file, it is right?

**Comment by loriab** [comment]
I'm not seeing any change in `compute_fcpi()` in 6 years -- https://github.com/psi4/psi4/blame/master/psi4/src/psi4/libscf_solver/hf.cc#L772-L801 . I also did a fresh clone and compile of master earlier today, and it was fine, so I'm not sure what circumstances could lead to your error. If you're rebuilding psi4 after a long interval, I'd suggest a new objdir.

**Comment by wszs** [comment]
> I'm not seeing any change in in 6 years -- https://github.com/psi4/psi4/blame/master/psi4/src/psi4/libscf_solver/hf.cc#L772-L801 . I also did a fresh clone and compile of master earlier today, and it was fine, so I'm not sure what circumstances could lead to your error. If you're rebuilding psi4 after a long interval, I'd suggest a new objdir.`compute_fcpi()`

maybe because i enable brianqc? my compile being corrected after I add "}"
btw , my link is [https://github.com/psi4/psi4/tree/master/psi4/src/psi4/libscf_solver](url)

**Comment by loriab** [comment]
Aha, that makes perfect sense -- none of the Psi4 developers have access to BrianQC anymore. Lmk if the fix in #3186 isn't what you were suggesting.

**Comment by loriab** [comment]
closed by #3186
