### ISSUE TITLE
Trouble with installation of Psi4 on Ubuntu

### ISSUE THREAD

**Issue by emkal073** [psi4/psi4#3188]
Hello, I've downloaded conda and Psi4 into my Ubuntu, along with Jupyter Notebook, but when I go to run the following code into my jupyter-notebook:

```
import psi4
psi4.__version__

I receive this error:

ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_2200/2591947057.py in <module>
----> 1 import psi4
      2 psi4.__version__

ModuleNotFoundError: No module named 'psi4'
```
I have conda installed psi4 and conda -V works properly. When I do Psi4 test I recieve: "64 passed, 39 skipped, 7746 deselected, 2 xfailed"

The two that have failed are: 

psi4conda/lib/python3.10/site-packages/psi4/tests/test_addons_qcschema.py::test_libefp XFAIL (EFP not transm...) [ 32%]
psi4conda/lib/python3.10/site-packages/psi4/tests/test_psi4_qcschema.py::test_psi4_cc XFAIL (no AtomicInput ...) [ 58%]

Any recommendations on what I can do to resolve these issue(s) or what I can check would be very helpful, thank you!

**Comment by loriab** [comment]
XFAIL is not an issue -- it means "expected fail".

Since tests are passing, psi4 is probably correctly installed ... somewhere. :-) I'd check things like is Jupyter installed in the same conda env as psi4, did the correct conda env get activated (or selected from the jupy drop-down) _before_ starting the jupy kernel, are other packages near to psi4 importable, etc. 

As you suggested, commands like `python -c "import psi4 as q;print(q.__file__, q.__version__)"`, `python -c "import qcelemental as q ...` can be helpful. If you paste your `conda list`, I can look for red flags.

**Comment by emkal073** [comment]
I typed conda list into my Ubuntu terminal and got the following return(s):

# packages in environment at /home/emkal/psi4conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
adcc                      0.15.17         py310hc6cd4ac_2    conda-forge
annotated-types           0.6.0              pyhd8ed1ab_0    conda-forge
archspec                  0.2.3              pyhd8ed1ab_0    conda-forge
boltons                   23.1.1             pyhd8ed1ab_0    conda-forge
brotli-python             1.1.0           py310hc6cd4ac_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.26.0               hd590300_0    conda-forge
ca-certificates           2024.6.2             hbcca054_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2024.6.2           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py310h2fee648_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     24.5.0          py310hff52083_0    conda-forge
conda-libmamba-solver     24.1.0             pyhd8ed1ab_0    conda-forge
conda-package-handling    2.2.0              pyh38be061_0    conda-forge
conda-package-streaming   0.9.0              pyhd8ed1ab_0    conda-forge
cppe                      0.3.1           py310h7c63755_9    conda-forge
dftd3-python              1.0.0           py310hdbe52f6_2    conda-forge
dftd4                     3.6.0                hf49bc11_0    conda-forge
dftd4-python              3.6.0           py310hc409063_1    conda-forge
distro                    1.9.0              pyhd8ed1ab_0    conda-forge
dkh                       1.2                  hd59d2e7_0    conda-forge
exceptiongroup            1.2.0              pyhd8ed1ab_2    conda-forge
execnet                   2.0.2              pyhd8ed1ab_0    conda-forge
fmt                       10.2.1               h00ab1b0_0    conda-forge
frozendict                2.4.4           py310hc51659f_0    conda-forge
gau2grid                  2.0.7                h0b41bf4_2    conda-forge
gcp-correction            2.3.1                h1990efc_2    conda-forge
geometric                 1.0                pyhd8ed1ab_1    conda-forge
gtest                     1.14.0               h00ab1b0_1    conda-forge
h5py                      3.11.0          nompi_py310hf054cd7_102    conda-forge
hdf5                      1.14.3          nompi_h4f84152_100    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
jsonpatch                 1.33               pyhd8ed1ab_0    conda-forge
jsonpointer               3.0.0           py310hff52083_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libaec                    1.1.2                h59595ed_1    conda-forge
libarchive                3.7.4                hfca40fe_0    conda-forge
libblas                   3.9.0            20_linux64_mkl    conda-forge
libcblas                  3.9.0            20_linux64_mkl    conda-forge
libcurl                   8.8.0                hca28451_0    conda-forge
libecpint                 1.0.7               h3ecfda7_10    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libefp                    1.5.0                h771fd35_4    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_5    conda-forge
libgfortran-ng            13.2.0               h69a702a_5    conda-forge
libgfortran5              13.2.0               ha4646dd_5    conda-forge
libhwloc                  2.9.3           default_h554bfaf_1009    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libint                    2.9.0                h9bbc0ff_0    conda-forge
liblapack                 3.9.0            20_linux64_mkl    conda-forge
libmamba                  1.5.8                had39da4_0    conda-forge
libmambapy                1.5.8           py310h39ff949_0    conda-forge
libnghttp2                1.58.0               h47da74e_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libpcm                    1.2.3                h4175798_7    conda-forge
libsolv                   0.7.29               ha6fb4c9_0    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_5    conda-forge
libtensorlight            3.0.1                hb9c973b_5    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxc-c                   6.2.2            cpu_h1b64f48_4    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.12.7               hc051c1a_1    conda-forge
libzlib                   1.3.1                h4ab18f5_1    conda-forge
llvm-openmp               18.1.8               hf5423f3_0    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mctc-lib                  0.3.1                h74f4db8_0    conda-forge
menuinst                  2.1.1           py310hff52083_0    conda-forge
mkl                       2023.2.0         h84fe81f_50496    conda-forge
msgpack-python            1.0.8           py310h25c7140_0    conda-forge
ncurses                   6.5                  h59595ed_0    conda-forge
networkx                  3.2.1              pyhd8ed1ab_0    conda-forge
numpy                     1.26.4          py310hb13e2d6_0    conda-forge
openssl                   3.3.1                h4ab18f5_1    conda-forge
opt_einsum                3.3.0              pyhc1e730c_2    conda-forge
optking                   0.2.1              pyhd8ed1ab_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pcmsolver                 1.2.3                      py_8    conda-forge
pint                      0.23               pyhd8ed1ab_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
platformdirs              4.2.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.4.0              pyhd8ed1ab_0    conda-forge
psi4                      1.9.1           py310h2a5c594_2    conda-forge
psutil                    6.0.0           py310hc51659f_0    conda-forge
pugixml                   1.14                 h59595ed_0    conda-forge
py-cpuinfo                9.0.0              pyhd8ed1ab_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.6           py310h2372a71_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  2.6.1              pyhd8ed1ab_0    conda-forge
pydantic-core             2.16.2          py310hcb5633a_1    conda-forge
pyddx                     0.6.0           py310h328bd66_2    conda-forge
pylibefp                  0.6.2           py310he0c9aae_4    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytest                    7.4.4              pyhd8ed1ab_0    conda-forge
pytest-xdist              3.5.0              pyhd8ed1ab_0    conda-forge
python                    3.10.14         hd12c33a_0_cpython    conda-forge
python_abi                3.10                    4_cp310    conda-forge
pyyaml                    6.0.1           py310h2372a71_1    conda-forge
qcelemental               0.28.0             pyhd8ed1ab_0    conda-forge
qcengine                  0.30.0             pyhd8ed1ab_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
reproc                    14.2.4.post0         hd590300_1    conda-forge
reproc-cpp                14.2.4.post0         h59595ed_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.18.6          py310h2372a71_0    conda-forge
ruamel.yaml.clib          0.2.8           py310h2372a71_0    conda-forge
scipy                     1.14.0          py310h93e2701_0    conda-forge
setuptools                69.0.3             pyhd8ed1ab_0    conda-forge
simple-dftd3              1.0.0                hd59d2e7_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
tbb                       2021.11.0            h00ab1b0_1    conda-forge
tk                        8.6.13               h2797004_0    conda-forge
toml-f                    0.4.2                hd8f1df9_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
truststore                0.8.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.9.0                hd8ed1ab_0    conda-forge
typing_extensions         4.9.0              pyha770c72_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
urllib3                   2.2.0              pyhd8ed1ab_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yaml-cpp                  0.8.0                h59595ed_0    conda-forge
zstandard                 0.22.0          py310hab88d88_1    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge

**Comment by emkal073** [comment]
Thanks for getting back by the way!
I'm also unsure if I need to create a new conda environment and reinstall Psi4 into there?

**Comment by loriab** [comment]
Ok, that looks fine for psi4 in its own right. Jupyter must be in a separate environment. That can also work, but it'll need a little configuration -- I'm not surprised the initial jupy couldn't find it. Pretty much `export PYTHONPATH <conda-env-prefix-with-psi4>/lib/python3.10/site-packages/` or `sys.path.append(<same>)` from the jupy env should make the connection. `psi4 --psiapi` gives the exact values. https://psicode.org/psi4manual/master/build_planning.html#how-to-run-psi4-as-executable-or-python-module-from-conda-installation may also be helpful (do set scratch if running anything non-trivial).

**Comment by emkal073** [comment]
I went to the link and typed "which psi4" in my terminal and got a return synonymous with the path being correct, I believe (so it said the code for the path should be redundant): [If you installed the Psi4conda distribution or installed the PSI4 conda package into the main environment of an Anaconda or Miniconda distribution and added that to your [PATH](https://psicode.org/psi4manual/master/external.html#envvar-PATH), as prompted, then which psi4 likely yields condadist/bin/psi4 and the PATH setting lines below are redundant.] 

which psi4
/home/emkal/psi4conda/bin/psi4

Additionally, trying the two commands suggested also had errors in syntax I believe? I also tried psi4 --psiapi which gave me the path and pythonpath; I tried copying the output in substitution of the "PYTHONPATH" but it didn't make a difference.

[1] export PYTHONPATH <conda-env-prefix-with-psi4>/lib/python3.10/site-packages/
 File "/tmp/ipykernel_10582/3886179417.py", line 1
    export PYTHONPATH <conda-env-prefix-with-psi4>/lib/python3.10/site-packages/
           ^
SyntaxError: invalid syntax

[2] sys.path.append(<same>)
 File "/tmp/ipykernel_10582/3391378744.py", line 1
    sys.path.append(<same>)
                    ^
SyntaxError: invalid syntax

**Comment by emkal073** [comment]
![image](https://github.com/psi4/psi4/assets/174042911/4ecd3a4a-19a1-48a3-af1e-5c1c787756ff)

**Comment by TiborGY** [comment]
> ![image](https://private-user-images.githubusercontent.com/174042911/343890176-4ecd3a4a-19a1-48a3-af1e-5c1c787756ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MTE3NDksIm5iZiI6MTcxOTUxMTQ0OSwicGF0aCI6Ii8xNzQwNDI5MTEvMzQzODkwMTc2LTRlY2QzYTRhLTE5YTEtNDhhMy1hZjFlLTVjMWM3ODc3NTZmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QxODA0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjhjNjNlMDljZWY3MDZiMTgwY2NmMDI0MzM4NzQyYjEyOTRkYjAzNGQ1YWNkMjBlNmIwMTk3YjM5NjYzYmI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lrgh8Wm-ActfzXx9w5DLSgo9D-Bnf-eOKrQ1te9qJj8)

The first one gives you a syntax error because it was meant to be executed in Bash, not Python, so naturally it does not have the correct syntax according to Python.
The second syntax error is because `sys.path.append` expects a string, and in Python you need to enclose string literals in quote characters.
Plus of course both of the paths you have tried to use were invalid, because the `<whatever>`  notation generally means you are supposed to replace `<whatever>` with something before use.

**Comment by emkal073** [comment]
![image](https://github.com/psi4/psi4/assets/174042911/3ee44192-8247-4dbc-b690-ff26a4c80efc)

So, I've been able to resolve the issue!

First thing I had to was use: 
conda create -n p4 psi4 -c psi4
to create a new environment in conda which started with Psi4

Then, in that new environment's bash, I had to run: 
PYTHONPATH="/home/emkal/psi4conda/envs/p4/lib//python3.10/site-packages:$PYTHONPATH"
(got this by doing psi4 --psiapi)

Finally, I was able to open jupyter notebook and run the following:

import sys
sys.path.append("/home/emkal/psi4conda/lib/python3.10/site-packages/")
import psi4
psi4.__version__

And it worked! Thanks for the help guys!
