### ISSUE TITLE
2016 compilers break psi4

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#321]
What single function in psi4 would you wish compiler optimization not to break? At first testing, it seems that the latest (release 2, Feb 2016) Intel compilers break `C_DGEMM`. The code compiles fine, but not much runs. Below are three dgemm calls that break. Not all dgemm calls break. Possibly 'N'/'T' are fine but 'N'/'N' break. If anyone wants to investigate, you can start with my "dftfix" branch (https://github.com/loriab/psi4/tree/dftfix). By commenting out Mulliken analysis and File 180 printing, I've gotten the jk & out_of_core algorithms in test case scf5 working on that branch.

https://github.com/loriab/psi4/commit/9bcd03959d1901e89ecea0274e0c086b0da397fa#diff-e30bd7727a15aa5a70e322a84a385291R2903

https://github.com/loriab/psi4/commit/9bcd03959d1901e89ecea0274e0c086b0da397fa#diff-ada70c1f1cf0a80abbdbacbfb7716abbR690

https://github.com/loriab/psi4/commit/9bcd03959d1901e89ecea0274e0c086b0da397fa#diff-be25444186a5073fb47c3ac4667533baR473

**Comment by dgasmith** [comment]
Awesome. Does turning off XHOST and compiler optimization help?

**Comment by lothian** [comment]
Holy cow.  I wonder if there's some problem with the passing of character
references between C++ and Fortran in the new compilers that could explain
why some DGEMM cases work and others don't.

-TDC

--
Prof. T. Daniel Crawford
crawdad@vt.edu

**Comment by bennybp** [comment]
Well that's not good. I've been compiling psi4 with 2016 for a while with no issues, but I haven't been using xHost and it tend to run single core. I'll see if I can reproduce, but a few things to look at would be
  * serial vs. parallel
  * xHosts vs no xHosts
  * mkl vs system blas/lapack.

Also, what processor microarchitecture is this? (Haswell?).

**Comment by loriab** [comment]
This was on a i7-4790 Haswell-DT. And it's an architecture we've seen some anomalies on. I'll try a 3930 and toggling xHost next. Good to know you've been building psi4 w/2016 compilers w/o disaster, @bennybp. release 1 or 2? This is with 16.0.2 20160204 .

**Comment by bennybp** [comment]
This is with release 2, mkl 11.3 update 2.

**Comment by CDSherrill** [comment]
Wonder if it matters to this behavior what gcc is installed

**Comment by loriab** [comment]
all are with mkl 11.3 update 2
all tests run in serial
all with gcc (GCC) 4.8.5 20150623

* i7-3930K, Sandy Bridge-E
   * xhost on (default), release: **Good**
* i7-4790K, Haswell-DT
   * xhost on (default), release: **Bad**
   * xhost off, release: **Bad**
   * xhost on (default), debug: **Bad**

**Comment by bennybp** [comment]
Is there a specific test that fails? It seems ok on my test machine
(Intel Xeon E5-2698 v3 Haswell) with GCC 4.8.5

**Comment by loriab** [comment]
Most (83%) fail. I've been using tu1 and scf5 in particular. Of all the test cases, only mrcc-ccsdt, mrcc-ccsdt_q_, psimrcc-pt2, cc36, cc55, dcft[12348], docs-*, fd-freq-energy, fd-freq-gradient, matrix1, mints[23459], mcscf1, mcscf3, mom, mp2-grad1, omp2-1, omp2-grad1, props1, psithon1, various pywraps, rasci-h2o, rasscf-sp, pubchem1, scf[34], zaptn-nh2 _do_ pass. And that's _with_ the aforementioned commenting.

**Comment by bennybp** [comment]
Last request for the night: Can you take scf5 and run it a bunch of times in a row (maybe 20 times)? On my Ivy Bridge machine, it will sometimes pass, sometimes fail....

    Singlet PK UHF energy: computed value (-149.6484410) does not match (-149.5905972) to 6 decimal places

Is this what you're seeing? Or is this an unrelated problem?

**Comment by jturney** [comment]
I'm using 16.0.2 with no problems on my workstation. Didn't know about the ```ENABLE_XHOST``` configure option but I routinely use ```setup --vectorization``` with no issues.  I'll give xhost a try shortly.

Though I'm having trouble getting cfour running on my new cluster using 16.0.2 with my flags from the old cluster (with older Intel compiler). I'm wondering now if this is related.

**Comment by dgasmith** [comment]
@bennybp This is something we have seen before for this test case (I think its in an issue somewhere). Not entirely sure why this happens yet.

**Comment by loriab** [comment]
@bennybp , I ran it 40 times today, and it passed consistently. But @dgasmith is right that I've seen it before. Now that it's not just me, I've made a ticket #322. But that was with 2015 compilers, so it is an unrelated issue.

@jturney, usually I only alter `xHost` for the generic linux binary, but yes, I can see it being necessary for deploying to a heterogenous cluster when not compiling on the oldest machine.

I admit it's suspicious that no matter how I back down optimization on the Haswell box, nothing helps the situation.

**Comment by bennybp** [comment]
If that's the case, everything looks ok on my Haswell machine. Would it be possible for me to get access to problematic box sometime next week?

**Comment by loriab** [comment]
Sure thing, Ryan can get you access next week.

**Comment by loriab** [comment]
Culprit identified: Boost. So _some_ non-custom-install boost libraries on _some_ architectures go haywire on _some_ DGEMMs. I'd feel better if such things announced themselves at link-time rather than run-time. My apologies for raising an overly general alarm.

**Comment by andysim** [comment]
Outstanding detective work.  I bet that was a nightmare to figure out.  It's not obvious to me how Boost is related to DGEMMs; what am I overlooking?

**Comment by loriab** [comment]
Wasn't so bad once I remembered, "I didn't try _that_". I'm not sure what the connection is either. DGEMM gets exported at https://github.com/psi4/psi4/blob/master/src/bin/psi4/export_blas_lapack.cc#L32 , but it's not as if the troublesome lines were getting called py-side.

**Comment by bennybp** [comment]
That's still unsettling, since boost should have nothing to do with DGEMM (except shared_ptr?). What version of the system boost were you having problems with? And what was the setup line?

**Comment by loriab** [comment]
The DGEMM-killing Boost is a Continuum/default channel conda package 1.57 that had been serving me well for months. It can be found in the lib subdir of the metapackage-dir in the setup line below. (metapackage-dir specifies location of python, boost, chemps2, pcmsolver, zlib, hdf5, gsl.)
```
../setup --cc icc --cxx icpc --fc ifort --type release --plugins on --prefix $INSTALL --max-am-eri 5 --metapackage-dir /theoryfs2/ds/cdsgroup/miniconda/envs/p4buildenv --cmake /theoryfs2/ds/cdsgroup/miniconda/bin/cmake -DSPHINX_ROOT=/theoryfs2/ds/cdsgroup/miniconda/envs/p4buildenv #-DENABLE_XHOST=OFF
```

**Comment by dgasmith** [comment]
Well, this is a boost issue. I don't think anyone is actually going to hunt down why this particular pre-compiled boost is killing DGEMM. Probably something very strange. Anyhow, we can change our build strategy for now and link to an updated boost in the future.

Let this be a warning when using pre-compiled boost.
