### ISSUE TITLE
The Default Unit of Mintshelper integrals

### ISSUE THREAD

**Issue by Chikakoyanagida** [psi4/psi4#3255]
Hello all,

My current research requires me to get hold of AO integrals, so I turn to mintshelper. However, I am not entirely sure what units are the integrals in. I think it is in au, but comparing it with the semi-empirical parameters counterparts seems quite confusing.

Thank you!

**Comment by lothian** [comment]
All Psi4 integrals are in au, though the specific integral type carries the appropriate unit for the corresponding operator.

**Comment by Chikakoyanagida** [comment]
> All Psi4 integrals are in au, though the specific integral type carries the appropriate unit for the corresponding operator.

Hello Lothian,

many thanks!
