### ISSUE TITLE
thermo fails on atoms

### ISSUE THREAD

**Issue by drhaney** [psi4/psi4#332]
Attempting frequency() for atomic species fails irrespective of charge, multiplicity, and reference type.

Typical error message:

>  1 displacements needed.
>  1
> 
> An error has occurred. Traceback:
> <type 'exceptions.IndexError'>: basic_string::replace:   File "<string>", line 26, in <module>
> 
>   File "/home/drhaney/miniconda/share/psi4/python/driver.py", line 1840, in frequency
>     psi4.thermo(wfn, wfn.frequencies())

Thanks,
-drhaney, -- that's "D. R.", not Doctor.

Typical input file attached (C atom, neutral triplet).
[C.txt](https://github.com/psi4/psi4/files/198782/C.txt)

**Comment by ryanmrichard** [comment]
Admittedly the error message should be updated to be more informative, but
the short answer is a single atom doesn't have a vibrational frequency.

More generally any molecular system has 3 times the number of atoms, total
degrees of freedom; the difference between that and the number of external
degrees of freedom is the internal degrees of freedom, i.e. the
vibrations.  An atom has three external degrees of freedom and thus in turn
has 0 internal degrees of freedom.

Hope that helps.

**Comment by CDSherrill** [comment]
Yeah, we should put a catch in the code to not allow frequency() on an atom.

**Comment by loriab** [comment]
If it doesn't give the vib/thermo code a fit, it'd be better to let an atom pass through and return zeros, as appropriate, so that database and presumably the compound methods that @drhaney is writing can proceed even if atoms involved.

**Comment by lothian** [comment]
Yes, that seems the wiser approach.

--
Prof. T. Daniel Crawford
crawdad@vt.edu

**Comment by CDSherrill** [comment]
I agree with the point that the code should go through and report zeros, so
we can do database stuff, etc.

I think the thermo code can easily be fixed for this (in fact Brandon has a
new version that has already been tested for atoms).  Looks like the first
failure we're hitting is in finite differences.  @psi-rking should give
that some thought.

David

**Comment by psi-rking** [comment]
Sounds good.  Check for natom==1, and if true assume for rovibrations only 1 state/no energy or entropy.

**Comment by drhaney** [comment]
Returning 0.0 works fine for the interrim, however the issue will need to be revisited at some later  point.

The following are excerpts from Hessian runs from two other QM apps.

**Nwchem**  reports the following for atomic Boron as a neutral doublet:
>  Zero-Point correction to Energy  =    0.000 kcal/mol  (  0.000000 au)
>  Thermal correction to Energy     =    0.888 kcal/mol  (  0.001416 au)
>  Thermal correction to Enthalpy   =    1.481 kcal/mol  (  0.002359 au)
> 
>  Total Entropy                    =   33.126 cal/mol-K
>    - Translational                =   33.126 cal/mol-K (mol. weight =  11.0093)
>    - Rotational                   =    0.000 cal/mol-K (symmetry #  =        1)
>    - Vibrational                  =    0.000 cal/mol-K
> 
> Cv (constant volume heat capacity) =     2.979 cal/mol-K
>    - Translational                 =    2.979 cal/mol-K
>    - Rotational                     =    0.000 cal/mol-K
>    - Vibrational                    =    0.000 cal/mol-K

**GAMESS'** authors include electronic properties.  Kcal and cal/mol-K units are omitted since the markdown can't handle them easily. 

  |   E     |   H    |    G    |   CV    |  CP    |    S 
---------- | ------- | ------ | ------- | ------- | ------ | -----
 ELEC.     | 0.000   |  0.000 | -0.411  | 0.000   |  0.000 |  1.377
 TRANS.    | 0.889   |  1.481 | -8.400  | 2.981   |  4.968 | 33.141
 ROT.      | 0.000   |  0.000 |  0.000  | 0.000   |  0.000 |  0.000
 VIB.      | 0.000   |  0.000 |  0.000  | 0.000   |  0.000 |  0.000
 TOTAL     | 0.889   |  1.481 | -8.810  | 2.981   |  4.968 | 34.518

**Comment by bwb314** [comment]
I have just made a pull request (#333) that will fix this issue. It turns out that Psi4 was crashing because the point group "ATOM" was being mishandled by the molecule class. At the moment, the thermo code does not return any vibrational frequencies or rotational constants for a single atom.

**Comment by dgasmith** [comment]
@bwb314 Confirmed this is fixed, I was being a separate error.
