### ISSUE TITLE
RHF fails to converge using 3df-polarized basis sets on CH3Cl

### ISSUE THREAD

**Issue by drhaney** [psi4/psi4#340]
Fails on methyl chloride, succeeds on diatomic chlorine.
Did not test larger alkyl groups.
CH3Cl was pre-optimized at HF/6-31G(d). 
Attempted RHF single point energy failed to converge with these basis sets:

> 6-311g(3df)
> 6-311g(3df,p)
> 6-311g(3df,2p)
> 6-311g(3df,2pd)
> 6-311g(3df,3pd)
> aug-cc-pV(D+d)Z
> aug-cc-pV(Q+d)Z
> aug-cc-pV(T+d)Z
> g3mp2large

They all have at least 3df polarization, some more.  Not all heavily polarized 6-311G(*) basis sets contain both C, Cl so these basis sets are only 5 of the 51 6-311?G(etc) sets.  Doubtless, the other 10 sets with diffuse functions (e.g., 6-311++G(3df)) will fail but take longer at it.

Though large, the 7152 Mb memory allocation requirement did not exhaust available shared memory.

G3(MP2) method requires the g3mp2large basis set and the Wilson Group's cc-CA methods require the aug-cc-pV([DQT]+d)Z basis sets.

Minimal test case attached.
[CH3Cl-3df-fail.zip](https://github.com/psi4/psi4/files/214171/CH3Cl-3df-fail.zip)

**Comment by loriab** [comment]
All converge in about 8 iterations with `set guess sad`. SAD is generally the best guess. Were it not for awkward performance issues with really large basis sets, it would be the default. Someday we'll fix those performance issues and make it the default.

**Comment by drhaney** [comment]
Thank you very much.
This is a n00b mistake so I close it with extreme prejudice.

Sorry for the bother.
