### ISSUE TITLE
Could not find QM/MM examples

### ISSUE THREAD

**Issue by zhengmin317** [psi4/psi4#341]
I could not find qm/mm tutorial or documentation
Are there qm/mm examples?
What MM software does psi4 support?

**Comment by loriab** [comment]
Psi4 is primarily a QM program. We have a "qmmm" module for adding external charges into a QM calc, http://psicode.org/psi4manual/master/scf.html#external-potentials-and-qm-mm . There's support for single-point calculations of EFP fragments alone or embedded into QM calcs, http://psicode.org/psi4manual/master/libefp.html . And there are a couple pure-MM projects simmering. But right now we don't support any particular MM software packages.

**Comment by CDSherrill** [comment]
As mentioned in the documentation @loriab quotes above, there is also a test case available of a QM computation in an MM point-charge field, the extern1 test case (psi4/tests/extern1).
