### ISSUE TITLE
reorganize Hessian, vib, thermo analysis

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#347]
### Current

Presently the `psi4.fd_freq_1()` and `psi4.fd_freq_0()` calls from `driver.hessian()`
- take in a Molecule and list of G or E, respectively
- stitch together the mass-weighted (mw) Hessian and compute freqs & normco
- pass vibs to the infamous `// This print function also saves frequencies in wavefunction.\n print_vibrations(mol, modes);`
- form the nmw Hessian and returns it

Then `driver.hessian()`
- initializes a new Wavefunction
- grabs from globals the frequencies that findif has stuffed there and puts them in Wfn
- takes the returned H matrix and puts it in Wfn

Then `driver.frequency()`
- extracts the frequencies from Wfn
- passes Wfn and Wfn.frequencies into thermo

Then `psi4.thermo()`
- extracts Molecule and E0 from Wfn
- uses those and frequencies to do the thermodynamic analysis

Key lines from driver below (note order of execution)

```
1 frequency(name):
2    H, wfn = hessian(name, return_wfn=True, molecule=molecule, **kwargs)  # send away for hessian
7    psi4.thermo(wfn, wfn.frequencies())  # pass frequencies into thermo analysis

3  hessian(name):   
4    H = psi4.fd_freq_1(molecule, gradients, irrep)  # stores freq in global psi4.frequencies(), returns H
5    wfn.set_hessian(H)  # store H in fresh wfn
6    wfn.set_frequencies(psi4.get_frequencies())  # store freq in fresh wfn
```

So there are three stages: "assemble H", "vibrational analysis", & "thermo analysis". Keeping in mind that the nmw Hessian is isotope-independent while freqs are isotope-dependent, you'll notice that the present arrangement of groups (1, 2) and (3) with frequencies as intermediate are such that can't reuse H for vibrational analysis of different isotopes (though it does allow for reuse of freq for thermo analysis at diff T, P).
### Future

assemble H
- this is doing just fine c-side in `psi4.fd_freq_0/1`
- should focus on returning nmw Hessian (as currently) does and trim out the vibrational analysis part
- @psi-rking, I don't remember seeing any projection of rot/trans out of Hessian. Is this just because by using SALCs you're assured of only displacements in vib-active directions? Assuming we someday get an analytic Hessian mtd, projection would be needed, right? I'm inclined to group projection with the vib analysis for comparison of proj and unproj freqs, so psi4.fd module needn't be involved.
- [ ] signature `SharedMatrix fd_freq_1(boost::shared_ptr<Molecule> mol, Options &options, const boost::python::list& grad_list, int freq_irrep_only)` (just like at present)
- [ ] remove communication with globals (`Process`)
- [ ] return nmw H (just like at present)

vibrational analysis
- should move to python
- possibly already drafted/ready by Addison/Brandon
- [ ] tentative signature `normalmode(molecule, hessian, gradient=None, **kwargs)` where the arrays are `psi4.Matrix` or numpy arrays, gradient defaults to None (just there to project out of Hessian), and I don't care about the function name
- [ ] mass-weights by masses in molecule
- [ ] does H = 1 – R – T projection
- should dress up printing w/reduced masses IR intensities (if get dipder) someday but that's beyond the scope of this issue
- [ ] returns freq & normco arrays (or OrderedDict w/symm, force constant, etc. info)

thermo analysis
- should move to python
- already ready by Addison/Brandon
- [ ] needs printing and Cp additions backported from forthcoming C++ version
- [ ] tentative signature `thermo(molecule, frequencies, E0=None, **kwargs)
- [ ] stash all those energy pieces in a dict or psivars
- should review anharm analysis so harm readily subcases it
- [ ] tentatively returns Total Gibbs Energy in E_h

application
- [ ] take freq-isotope test case (not checked in yet) and rewrite it (and the `driver.frequency()` fn) so that wfn (containing mol & H) from first H2O 2nd deriv calc can be passed into vib and thermo analyses w/o ever recomputing H. All the compare_values should still pass.

**Comment by psi-rking** [comment]
Yes, the SALCs we are using now for displacements already have rotations and translations projected out, so the Hessian is internal naturally so to speak.  In the event of a full cartesian Hessian, the simplest thing to do would be to carry out the vibrational analysis directly in cartesians.

**Comment by psi-rking** [comment]
FYI for anyone working on properties.  The attached input uses finite-differences of MP2 geometricial gradients computed with applied electric fields to produce an old psi3-style file17 (without the first line).  I wanted to document somewhere that using this file17, along with @lothian TDC's properties=['roa'] driver script produces IR intensities which match those from Spartan.  If noone has yet tacked the problem, mimicking the code that's already in there would give us IR intensities.  I suggest noone takes the absolute values very seriously and a default behavior for the intensities like MP2 might be welcome.  (Now we've got CCSD gradients with fields checked in too, I'll try these out too.)

[file17-mp2-input.txt](https://github.com/psi4/psi4/files/1506216/file17-mp2-input.txt)

**Comment by loriab** [comment]
@psi-rking, great, thanks for the prototype. Maybe put your post at https://github.com/psi4/psi4/issues/402 and mention it in the newdev slack channel. Also,
* is there anything particular to MP2 or is that just what you tested against?
* general fyi is that there's multi-QC-package vib outputs in the isotope-1 test cases that also may have some intensities
* how rigorous is that c1/no_com/no_reorient req. in your input file. Absolutely required to get the right charge origin? Or could we run with symmetry if we knew how to transform the Hessian or perturbation vectors into better frame? Is it different for charged species?
* why "roa"? Just because it brings dipole derivatives for free?

**Comment by psi-rking** [comment]
No reason it needs to be 'roa'.  The point is that the code which executes
right now when one selects 'roa' is already doing the IR intensities
correctly.  If we otherwise have IR intensities working, then just ignore
this post.  I did MP2 because Spartan and Psi could.  Presumably with the
new CCSD gradient with fields check-in last weekend, the CCSD intensities
would work too, but I haven't checked that.  The input file could certainly
be simplified, including trying to eliminate some of the restrictions and
seeing if there is any impact on the IR intensities.  I thought it might be
helpful if someone else would like to start from that point.
