### ISSUE TITLE
bypass scf

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#353]
* [ ] Strongly suspect "def energy" examples 4 & 5 in share/python/driver.py don't work or don't work as advertized. test. if fail, see if can get working by wfn-passing

* [ ] depending on previous findings, either document (example in previous would do) what used to be "bypass_scf" in action or purge it from docs and driver and create new ticket to make it work again.

**Comment by dgasmith** [comment]
`bypass_scf` *should* not work as there is no longer a global wavefunction. So this simply need to be purged from docs/driver/etc and replaced with:

```python
scf_e, scf_wfn = energy('SCF',  return_wfn = True)
energy('other_method', ref_wfn=scf_wfn)
```

**Comment by bwb314** [comment]
PR #359 should fix this.
