### ISSUE TITLE
libint as ExternalProject

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#355]
It would be valuable to developers, nightly builds, and CI testing if libint could be compiled once, then linked in as needed, like we can do for Boost. Much developer anger when CMake spontaneously decides the integrals need recompiling could be soothed! We could test molecules larger than He with density-fitted quad-zeta! The next NSF green initiative could applaud our energy savings!

Who dares to decouple libint from our build system such that it could become a detectable `ExternalProject_Add` CMake module? I think we need to be able to pass in MAX_AM, and it would be nice to have it build both static and shared libraries.

**Comment by dgasmith** [comment]
I compiled psi4, got coffee, and cmake decided it was time to recompile from scratch in case someone ninja edited my build. Cmake always has your back. 

-Daniel Smith

**Comment by susilehtola** [comment]
This would also make it easier for linux distributions...

**Comment by jturney** [comment]
This is my task for today.

**Comment by mbanck** [comment]
FWIW, I'm crudely patching out the internal libint on Debian/Ubuntu: http://anonscm.debian.org/viewvc/debichem/unstable/psi4/debian/patches/system_libint.patch?view=markup

I wasn't 100% sure this was kosher, but am glad it's going to (properly) happen upstream as well.

**Comment by andysim** [comment]
Any progress on this?  We're hitting some problems in tests, because the analytic Hessians require higher angular momentum.  Rather than recompile a large libint for every travis run, it'd be good to pull it in as a precompiled package.

**Comment by ryanmrichard** [comment]
@andysim #442 has it finished for both libint and libderiv.  Also included are `libintConfig.cmake` and `libderivConfig.cmake` files needed for `find_package`.  That obviously won't help you until the rewrite is accepted though....

**Comment by andysim** [comment]
Excellent!  I'll hang tight.  In the mean time, I can just use finite differences for that test, as we used to.

**Comment by mbanck** [comment]
If the cmake rewrite won't land for 1.0 (will it?), it might make sense to cherry-pick/backport the parts that add support for libint as an external project.

**Comment by ryanmrichard** [comment]
@mbanck correct it is not in 1.0.  Unfortunately, I don't think it will be easy to cherry-pick the external project support.

**Comment by dgasmith** [comment]
For what its worth 1.1 shouldn't be too far down the pipeline. This year at the very latest, but hopefully 2-3 months.

**Comment by mbanck** [comment]
Then again, assuming ERD is taken from AcesIII (is it?), it could be an external project as well...

**Comment by ryanmrichard** [comment]
@bennybp thanks for confirming that.  I was literally just working on putting ERD as an external project and couldn't figure out how to specify the max angular momentum....
