### ISSUE TITLE
test properties

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#356]
This attractive table of properties, https://github.com/psi4/psi4/blob/master/share/python/driver.py#L847, give them a try and see if they
  * [x] all actually run
  * [x] give dipole moments that aren't the HF ones (check printout and `psi4.get_variable('CURRENT DIPOLE X')` for X, Y, Z)
  * [x] `property('mp2')` through dfmp2 and `set qc_module occ\n property('mp2')` give same dipole

**Comment by dgasmith** [comment]
Got this one too.
