### ISSUE TITLE
units labeling

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#357]
Search the code for units. Modify as needed accordint to principles below. Don't forget to extend table lines if needed
* [x] `[Eh]` _may_ go unlabeled, but not recommended (future pass).
* [x] If more than one units is printed or unit is _not_ `[Eh]` it must have a label.
* [x] `[Eh]`, not `[Ha]` or `[H]`
* [x] all units in square brackets
* [x] use parentheses if needed and space for multiplication, e.g., `[kJ/(mol K)]`

**Comment by dgasmith** [comment]
Taking this one.
