### ISSUE TITLE
NaN energy for a reasonable sized DF-SCF computation

### ISSUE THREAD

**Issue by dgasmith** [psi4/psi4#371]
The following either gives `NaN` energy or (positive) 60,000 [Eh] depending on MKL version and compile options. All basis sets smaller than aug-cc-pVQZ seem to check out, did not try larger. Other guesses, `s_tolerence`, or fitting basis appear to have no effect on this error. UHF works fine.

```
molecule mol {
0 2
C  -2.83891  -0.84747  -0.20778
N  -2.06959  -0.27604   0.77905
C  -0.85937  -0.82512   0.74757
N  -0.82980  -1.74677  -0.21226
C  -2.05910  -1.77487  -0.83179
C  -2.45490   0.86620   1.59959
C   0.35903  -2.49473  -0.61265
F  -1.01767   1.46174  -1.11980
B   0.28985   1.63764  -0.63648
F   0.23738   1.82826   0.77419
F   0.89453   2.73957  -1.24020
F   1.05039   0.46734  -0.88673
H  -0.02604  -0.54755   1.38339
H  -2.27287  -2.45330  -1.64959
H  -3.86751  -0.55086  -0.37733
H  -3.45079   0.68580   2.01748
H  -1.72185   0.98138   2.40249
H  -2.44673   1.75972   0.96603
H   0.98379  -1.85263  -1.24323
H   0.91655  -2.78676   0.28358
H   0.03922  -3.39046  -1.15377
C   2.81822   0.12352   1.52490
C   3.26768  -0.78277   0.56145
H   3.28632   0.11977   2.50813
H   2.01109   0.81253   1.27433
N   3.64537  -1.55240  -0.23308
}

set {
    basis       aug-cc-pVQZ
    scf_type    df
    guess       gwh
    reference   rohf
}

energy('SCF')
```

An example of initial convergence can be seen for UHF/aQZ:
```
                           Total Energy        Delta E     RMS |[F,P]|

   @DF-UHF iter   1:  -716.29320215568873   -7.16293e+02   1.25967e-02
   @DF-UHF iter   2:    27.48017620380119    7.43773e+02   1.97120e-02 DIIS
   @DF-UHF iter   3:  -561.81810445462588   -5.89298e+02   9.53326e-03 DIIS
```

**Comment by robparrish** [comment]
Does the singlet cation exhibit the same failure with RHF/SAD? Could be a
bad eigenvalue in the DF metric, though I have traps in for this. Compiling
a fork to check this out.

-Rob

**Comment by robparrish** [comment]
Cannot replicate this bug. Iterations are oscillating like crazy, but no
singularity. I get similar oscillations for singlet cation in cc-pVDZ
(eventually converges) with both DF and ID.

-Rob

**Comment by loriab** [comment]
Are you using 2015 or 2016 Intel compilers/mkl, @robparrish ? Ours are w/2015; haven't tried the 2016.

**Comment by robparrish** [comment]
icpc 15.0.0 20140723.

-Rob

**Comment by loriab** [comment]
Ok, curious. Ours are 15.0.3. @dgasmith tried it on a couple architectures and executables, but good to know the error isn't seen everywhere. May have to wait for a calmer development environment here to examine again.

**Comment by robparrish** [comment]
Lovely. @dgasmith do you have an outfile? Would be also interested to see
the eigenspectrum of the DF metric from the failing case.

-Rob

**Comment by dgasmith** [comment]
@robparrish I can no longer reproduce this on any hardware and with any combinations of keywords. Sent you the results of the only failed test case results that I saved.

@loriab Can you run this on your box again? Located in `dsmith/TEST`.

**Comment by dgasmith** [comment]
Well, still cannot reproduce this. Closing this out.
