### ISSUE TITLE
DMRG-CASPT2

### ISSUE THREAD

**Issue by SebWouters** [psi4/psi4#384]
Are you interested in having DMRG-CASPT2 in the 1.0 release or do you want to stick to DMRG-SCF?

If you would like to, I can release an intermediate version v1.7, and you can use the plugin (or copy parts of) https://github.com/SebWouters/CheMPS2/blob/master/integrals/psi4plugins/dmrg.cc to run the CASPT2 calculations...

**Comment by CDSherrill** [comment]
From a strategic point of view, the answer is yes, it would be a great
addition.

However, it would depend on the technical details ... how much work it
would be to get this working, how soon we could do it, etc.  I'll try to
discuss with Lori and Daniel S.

We've already done a "soft" 1.0 release (not heavily advertized yet).


On Fri, May 20, 2016 at 6:46 AM, Sebastian Wouters <notifications@github.com

**Comment by SebWouters** [comment]
Hi David,

My CASPT2 plugin works on psi4-0.5, so I can do it on Monday in an hour, if
jet or lori are available on skype for questions. The actual core code
won't be that hard, it's mainly the changes in the periphery.

Best wishes,
Sebastian

**Comment by SebWouters** [comment]
By the way: chemps2 v1.7-rc3 doesn't depend on GSL anymore. I have my own Wigner-nj generator now.

**Comment by mbanck** [comment]
It seems to work fine with the chemps-1.7 in debian, all three tests pass.

One thing I noticed is that the ```dmrg-caspt2-n2``` test case takes a long time to run - can it be scaled down a bit?

```
Test project /«PKGBUILDDIR»/builddir/tests
    Start 319: dmrg-scf-n2
1/3 Test #319: dmrg-scf-n2 ......................   Passed    9.36 sec
    Start 320: dmrg-ci-h2o
2/3 Test #320: dmrg-ci-h2o ......................   Passed   15.42 sec
    Start 321: dmrg-caspt2-n2
3/3 Test #321: dmrg-caspt2-n2 ...................   Passed  594.31 sec

100% tests passed, 0 tests failed out of 3
```

**Comment by mbanck** [comment]
I reduced the active space of the ```dmrg-caspt2-n2``` testcase (see http://anonscm.debian.org/viewvc/debichem/unstable/psi4/debian/patches/relax_dmrg_caspt2_test.patch?view=markup), and (now?) some architectures show slightly different results, e.g. powerpc:

```
	DMRG-SCF Energy...................................................PASSED
	DMRG-CASPT2 Energy: computed value (-107.5036885) does not match (-107.5036855) to 6 decimal places.
```
See https://buildd.debian.org/status/fetch.php?pkg=psi4&arch=powerpc&ver=1%3A1.0~rc-2&stamp=1464563141 for the full log. This also happened on arm64, i386 (x86-32) and ppc64.

The differences are quite small, but mentioning here nevertheless.

**Comment by Hassenky** [comment]
I installed Psi4 and chemps2 from Miniconda. How can I interface Chemps2 with Psi4? Thanks in advance.

**Comment by SebWouters** [comment]
Hi @Hassenky

You should be able to use (and modify) the test files

https://github.com/psi4/psi4/blob/5801071a3b022497b8ae6bd157d9669f11c3b6d3/tests/dmrg/natural-orbital/input.dat
https://github.com/psi4/psi4/blob/5801071a3b022497b8ae6bd157d9669f11c3b6d3/tests/dmrg/scf-n2/input.dat
https://github.com/psi4/psi4/blob/5801071a3b022497b8ae6bd157d9669f11c3b6d3/tests/dmrg/ci-h2o/input.dat

Just leave out the last two lines from these files and give it try?

Once Daniel's pull request to chemps v1.7 is also accepted, you should be able to use dmrg-caspt2:

https://github.com/dgasmith/psi4/blob/13b56a618a17f57eeeacf66ef0a2a020daacdbb9/tests/dmrg/caspt2-n2/input.dat

Best wishes,
Sebastian

**Comment by Hassenky** [comment]
Hi Sebastian,

Something is wrong with my DMRG-CASPT2 calculattion. I run the caspt2-n2 test. This the error

Error: option WFN_IRREP is not contained in the list of available options.

Did you mean? 

An error has occurred python-side. Traceback (most recent call last):

  File "<string>", line 33, in <module>

RuntimeError: 
Fatal Error: WFN_IRREP is not a valid option.
Error occurred in file: /scratch/cdsgroup/conda-builds/work/src/lib/liboptions/liboptions.h on line: 59
The most recent 5 function calls were:

psi::PsiException::PsiException(std::string, char const*, int)
psi::Options::use(std::string&)
py_psi_set_local_option_int(std::string const&, std::string const&, int)
boost::python::objects::caller_py_function_impl<boost::python::detail::caller<bool (*)(std::string const&, std::string const&, int), boost::python::default_call_policies, boost::mpl::vector4<bool, std::string const&, std::string const&, int> > >::operator()(_object*, _object*)
boost::python::objects::function::call(_object*, _object*) const

Best regards,

**Comment by SebWouters** [comment]
Are the other tests fine?

If so, then, as said, the caspt2 calculations will work once Daniel's pull request is also incorporated. You will have to wait until then...

**Comment by Hassenky** [comment]
The DMRG-natural-orbital calculation also has the same error.

**Comment by dgasmith** [comment]
It should be noted that the keywords did change slightly and all tests had to be tweaked. I am guessing that the Psi4 and ChemPS2 binary versions are out of sync at the moment.

Ill look into this today.

Cheers,
Daniel Smith

**Comment by Hassenky** [comment]
Thanks. I would be waiting for the new binary version.

**Comment by loriab** [comment]
I'm having some trouble with chemps2 1.6 or 1.7 and the psi4 binary version. But there's a fallback so should get the new chemps2 into both source and binary versions this week.

**Comment by dgasmith** [comment]
Now works!

**Comment by loriab** [comment]
@Hassenky , I now have considerable confidence that a `conda update/install psi4 pychemps2 hdf5=1.8.16` will work.

**Comment by Hassenky** [comment]
Thanks @loriab. I have updated both PSI4 and Chemps2. Everything is working well.
