### ISSUE TITLE
stability2 intermittently fails

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#385]
We've seen this a couple times on TravisCI, then I got it last night on psinet (unreproducible, of course), now @polikw reports it with the binary 1.0rc3 . No rush, just someone should get to cross a ticket off when tracked down.

**Comment by jgonthier** [comment]
Oh, that is stability2, so the stability analysis for the ROHF code... The whole code should be modernized to use the JK object and do Davidson instead of a full diagonalization. Unfortunately I don't have time for that right now...

**Comment by loriab** [comment]
Yes, no pressure, @jgonthier , I just wanted to get it documented so people could find that it's a known problem.

**Comment by dgasmith** [comment]
@jgonthier In the latest SAD PR I reduced the tolerance to `1.e-2` up from `1.e-4`. "Failing" is a strong word here as the eigenvalue is still positive. Im guessing this is just small flutter in the Davidson iterations which are not converged strongly to begin with.

**Comment by dgasmith** [comment]
This is #222 related, and should be "fixed" for now. Closing.
