### ISSUE TITLE
Check convergence of FCI energy/residual

### ISSUE THREAD

**Issue by fevangelista** [psi4/psi4#394]
The following input file for H10 runs but gives an energy that is not converged:

```
molecule {
0 1
H   0.000   0.000   0.0000
H   0.000   0.000   2.5001
H   0.000   0.000   5.0003
H   0.000   0.000   7.5006
H   0.000   0.000  10.0011
H   0.000   0.000  12.5015
H   0.000   0.000  15.0021
H   0.000   0.000  17.5023
H   0.000   0.000  20.0030
H   0.000   0.000  22.5040
symmetry c1
}

set globals {
    reference rhf
    basis     sto-3g
}

energy('fci')
```

with output

```
Find the roots by the Simultaneous Expansion Method (Block Davidson Method)
Using 1 initial trial vectors
Iter  0  Root  1 =  -4.093847469   Delta_E -8.176E+00   Delta_C  5.250E-01
...
Iter 10  Root  1 =  -4.680023014   Delta_E -1.423E-05   Delta_C  4.880E-03
Iter 11  Root  1 =  -4.680047623   Delta_E -2.461E-05   Delta_C  7.532E-03
Iter 12  Root  1 =  -4.680121394   Delta_E -7.377E-05   Delta_C  1.166E-02

Maximum number of CI iterations reached

* ROOT 1 CI total energy =  -4.6801213940684
```

**Problem:**

The final energy is far from being converged but the user is not warned.

The correct converged energy is about 0.0007 Eh below (-4.680868674 Eh).  This value can be obtain by adding `set detci maxiter 100` to the input file. 

**Feature requested:**

- [ ]  Increase the maximum number of iterations in DETCI (currently 12)
- [ ]  Warn the user/do not print final energy if DETCI does not converge
- [ ]  Confirm that failure to converge DETCI does not affect CASSCF computations

**Comment by dgasmith** [comment]
Sure, we can add a failure just like SCF if DETCI does not converge. We can also increase the number of default iterations. At the same time, this is a fairly difficult CI case with the hydrogens very extended, I'm not sure we want defaults to cover this area as in many other cases 100 CI iterations would indicate some sort of failure. 

In two-step MCSCF exact CI iterations are not really all that desirable. Unless a user loosens the MCSCF gradient threshold significantly this likely has no bearing on MCSCF computations as the previous guess CI vector is nearly exact with respect to energy near solution. Even then, delta energy convergence conditions should pick this up.
