### ISSUE TITLE
Error with make -j on MacBook Air

### ISSUE THREAD

**Issue by ilfreddy** [psi4/psi4#396]
I have recently bought a new MacBook Air, and I have homebrew for my developing environment (on my old mac I had MacPorts: I never managed to compile and I finally gave up)

I cloned the psi4 repo and went for the simplest build (./setup build; cd build; make -j)

Once I had all required packages the setup worked smoothly.
Unfortunately, "make -j" gives me the following error:

> clang: error: unable to execute command: posix_spawn failed: Resource temporarily unavailable

which from a simple minded "LMGTFY" search seems to be a problem with too many child processes spawned by make.

removing the "-j" seems to work: 70% done and running so far...

**Comment by dgasmith** [comment]
@ilfreddy `make -j` will spawn an unlimited number of jobs. Please limit limit this to `make -j4` to limit your build to 4 threads.

**Comment by ilfreddy** [comment]
I see! I thought the limit would determined by make based on the machine. 

Thanks for the quick answer @dgasmith !

**Comment by dgasmith** [comment]
@ilfreddy Yup, kind of a qwerk of `make`. For some programs `make -j` will be fine, but Psi has a lot of sections that be built in parallel. Im guessing it tried to spawn the POSIX cap of 256 threads which quickly killed your laptop.
