### ISSUE TITLE
Compiler error PK_workers.cc file with the Intel 14 compiler

### ISSUE THREAD

**Issue by hpourreza** [psi4/psi4#398]
I was trying to compile psi4 using the Intel 14 compiler and I got an error:
PK_workers.cc(755): error: no instance of constructor "psi::pk::PKWorker::PKWorker" matches the argument list
            argument types are: (boost::shared_ptr<psi::BasisSet>, psi::pk::SharedSieve, long, int, size_t)
      PKWorker(primary,sieve, NULL,0,buf_size) {
              
I changed NULL to std:shared_ptr<AIOHandler>() and it fixed the compiler error. Do you think this may have a side effect?

**Comment by dgasmith** [comment]
@hpourreza Should be fine, we will drop a change in soon.
