### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by bozkaya** [psi4/psi4#404]
I try to compile psi4 with gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) compiler. I got the following error:

Scanning dependencies of target mints
[ 59%] Building Fortran object src/lib/libmints/CMakeFiles/mints.dir/dkh2-dkh4_main.F90.o
[ 59%] Building CXX object src/lib/libmints/CMakeFiles/mints.dir/local.cc.o
In file included from /home/ubgroup/psi4/src/lib/libmints/mints.h:70,
                 from /home/ubgroup/psi4/src/lib/libmints/potentialint.h:31,
                 from /home/ubgroup/psi4/src/lib/libmints/mints.h:44,
                 from /home/ubgroup/psi4/src/lib/libmints/local.cc:30:
/home/ubgroup/psi4/src/lib/libmints/oeprop.h:121: error: ISO C++ forbids initialization of member ‘max_noon_’
/home/ubgroup/psi4/src/lib/libmints/oeprop.h:121: error: making ‘max_noon_’ static
/home/ubgroup/psi4/src/lib/libmints/oeprop.h:121: error: ISO C++ forbids in-class initialization of non-const static member ‘max_noon_’
make[2]: *** [src/lib/libmints/CMakeFiles/mints.dir/local.cc.o] Error 1
make[1]: *** [src/lib/libmints/CMakeFiles/mints.dir/all] Error 2
make: *** [all] Error 2

@jturney

**Comment by bozkaya** [comment]
More errors if I continue.

In file included from /home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/Timer.cc:29:
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h:147: sorry, unimplemented: cannot expand ‘Args ...’ into a fixed-length argument list
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h: In constructor ‘psi::Table<T, Args>::Table(int, int, int, const T&, Args& ...)’:
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h:221: sorry, unimplemented: cannot expand ‘Args ...’ into a fixed-length argument list
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h:221: error: expected ‘{’ before ‘(’ token
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h: At global scope:
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h:221: error: expected ‘)’ before ‘,’ token
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h:221: error: expected constructor, destructor, or type conversion before ‘,’ token
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h:221: error: expected constructor, destructor, or type conversion before ‘+’ token
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h: In member function ‘std::string psi::Table<T, Args>::PrintOut(int) const’:
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h:228: sorry, unimplemented: cannot expand ‘Args ...’ into a fixed-length argument list
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h: In constructor ‘psi::Table<T, Args>::Table(int, const T&, Args& ...)’:
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h:235: sorry, unimplemented: cannot expand ‘Args ...’ into a fixed-length argument list
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h:235: error: expected ‘{’ before ‘(’ token
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h: At global scope:
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h:235: error: expected unqualified-id before numeric constant
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h:235: error: expected ‘)’ before numeric constant
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h: In member function ‘void psi::Table<T, Args>::SetBorder(psi::TableSide, char)’:
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h:251: sorry, unimplemented: cannot expand ‘Args ...’ into a fixed-length argument list
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h:251: error: invalid type in declaration before ‘(’ token
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h: In constructor ‘psi::Table<T, Args>::Table(int, const T&, Args& ...) [with T = psi::TableColumn<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, Args = psi::TableColumn<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, psi::TableColumn<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, psi::TableColumn<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >]’:
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/Timer.cc:173:   instantiated from here
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h:235: error: no matching function for call to ‘psi::TableData<psi::TableColumn<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::TableData()’
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h:279: note: candidates are: psi::TableData<T>::TableData(const T&, int, int, int, char, char, char, char) [with T = psi::TableColumn<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >]
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h:189: note:                 psi::TableData<psi::TableColumn<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::TableData(const psi::TableData<psi::TableColumn<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h: In member function ‘void psi::Table<T, Args>::SetBorder(psi::TableSide, char) [with T = psi::TableColumn<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, Args = psi::TableColumn<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, psi::TableColumn<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, psi::TableColumn<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >]’:
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/Timer.cc:174:   instantiated from here
/home/ubgroup/psi4/src/lib/libPsiUtil/Implementations/../Table.h:251: error: initializer expression list treated as compound expression
make[2]: *** [src/lib/libPsiUtil/CMakeFiles/PsiUtil.dir/Implementations/Timer.cc.o] Error 1
make[1]: *** [src/lib/libPsiUtil/CMakeFiles/PsiUtil.dir/all] Error 2
make: *** [all] Error 2

**Comment by jturney** [comment]
Your GCC compiler is too old for the C++11 support that we require. I refer you to #238 and [here](http://forum.psicode.org/t/c-11-is-it-time/43).

**Comment by bozkaya** [comment]
Thank you for your help. I was using intel compiler but its license expired, hence I tried GCC. Now, I see that Intel provides free compilers for open-source developers. I will update my system.
