### ISSUE TITLE
PsiUtil error

### ISSUE THREAD

**Issue by bozkaya** [psi4/psi4#407]
When I run psi4 I got the following error (I have Python 2.7):

Traceback (most recent call last):
  File "/truba/home/tbag24/programs/psi4intel/share/psi4/python/inputparser.py", line 43, in <module>
    import pubchem
  File "/truba/home/tbag24/programs/psi4intel/share/psi4/python/pubchem.py", line 61, in <module>
    from p4util.exceptions import *
  File "/truba/home/tbag24/programs/psi4intel/share/psi4/python/p4util/__init__.py", line 32, in <module>
    from .util import *
  File "/truba/home/tbag24/programs/psi4intel/share/psi4/python/p4util/util.py", line 32, in <module>
    import numpy as np
ImportError: No module named numpy

@loriab

**Comment by jturney** [comment]
Per this [discussion](http://forum.psicode.org/t/numpy-psi4-dependency/199), there was talk of requiring numpy. However, I can't seem to find the announcement of it.

**Comment by bozkaya** [comment]
Many thanks! I do not remember any announcement. Perhaps, I missed it. I have install numpy and psi4 works now.

**Comment by amjames** [comment]
Is NumPy an official requirement now? I was under the impression it was not, but I guess I always have it so I haven't noticed this yet. 

If it is would we be accepting PR's with python code that relies on NumPy? Some of the things I am currently working on could use NumPy as an alternative to adding code to the ccresponse module. I have some manipulation of small matrices to do, and it seems like overkill to pass data into ccresponse create matrix objects, and manipulate there.

**Comment by jturney** [comment]
Yes, NumPy is officially required at runtime see [here](https://github.com/psi4/psi4/wiki/2_Planning#-what-are-the-tools-and-dependencies-strictly-required-for-building-psi4) for requirement list.

We'll accept PRs that rely on NumPy.

**Comment by dgasmith** [comment]
The new NBody and CBS codes rely on NumPy and we officially brought it in then. Guess there wasn't enough fanfare. If you want to use NumPy and Psi4 together you can view the current range of helper functions [here](https://github.com/psi4/psi4/pull/373/files).

**Comment by andysim** [comment]
Maybe we should catch the ImportError and print out a detailed description of what the user needs to do to obtain numpy?

**Comment by amjames** [comment]
I think that would be a great idea.

**Comment by jturney** [comment]
And/or add to our cmake scripts a check for numpy. 

It would also be useful to add cmake checks for the C++11 specific features we use and error out at configuration time. I think it tests for some but doesn't error out.
