### ISSUE TITLE
Trunk does not build with CheMPS2

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#414]
I just tried to build the present trunk using the instructions in the wiki
https://github.com/psi4/psi4/wiki/1_Obtaining#clonepsi4public

but the compilation fails in a bunch of unresolved symbols

/tmp/ccVe3Y02.ltrans0.ltrans.o: In function `main':
/home/work/psi4/psi4/objdir/interfaces/chemps2/src/interface_chemps2/CheMPS2/executable.cpp:512: undefined reference to `CheMPS2::Irreps::Irreps(int)'
/home/work/psi4/psi4/objdir/interfaces/chemps2/src/interface_chemps2/CheMPS2/executable.cpp:513: undefined reference to `CheMPS2::Irreps::getNumberOfIrreps() const'
/home/work/psi4/psi4/objdir/interfaces/chemps2/src/interface_chemps2/CheMPS2/executable.cpp:541: undefined reference to `CheMPS2::Irreps::symm_psi2molpro(int*) const'
/home/work/psi4/psi4/objdir/interfaces/chemps2/src/interface_chemps2/CheMPS2/executable.cpp:512: undefined reference to `CheMPS2::Irreps::~Irreps()'
/home/work/psi4/psi4/objdir/interfaces/chemps2/src/interface_chemps2/CheMPS2/executable.cpp:611: undefined reference to `CheMPS2::Irreps::getGroupName[abi:cxx11]() const'
/home/work/psi4/psi4/objdir/interfaces/chemps2/src/interface_chemps2/CheMPS2/executable.cpp:614: undefined reference to `CheMPS2::Irreps::getIrrepName[abi:cxx11](int) const'
/home/work/psi4/psi4/objdir/interfaces/chemps2/src/interface_chemps2/CheMPS2/executable.cpp:646: undefined reference to `CheMPS2::Initialize::Init()'

When I look at the log file, it looks like the addition of the -flto flag in the CheMPS2 makefile breaks the CheMPS2 compile, in that when CMake creates the static archive there's a big bunch of messages like

[ 96%] Linking CXX static library libchemps2.a
BFD: CMakeFiles/chemps2-base.dir/CASPT2.cpp.o: plugin needed to handle lto object
BFD: CMakeFiles/chemps2-base.dir/CASSCF.cpp.o: plugin needed to handle lto object
BFD: CMakeFiles/chemps2-base.dir/CASSCFdebug.cpp.o: plugin needed to handle lto object
BFD: CMakeFiles/chemps2-base.dir/CASSCFnewtonraphson.cpp.o: plugin needed to handle lto object
BFD: CMakeFiles/chemps2-base.dir/CASSCFpt2.cpp.o: plugin needed to handle lto object

Commenting out the FLTO stuff in the CheMPS2 CMakeLists.txt results in a succesful compile.

$ gcc --version
gcc (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)
$ cmake --version
cmake version 3.4.3
$ git rev-parse --verify HEAD
b162ed15fcf1bfbc40b99bcc3a9ea7b812760033

**Comment by loriab** [comment]
[Sounds like](http://stackoverflow.com/questions/25878407/how-can-i-use-lto-with-static-libraries) `gcc-ar` and `gcc-ranlib` are needed instead of the usual `ar` and `ranlib`. Either the `flto` needs to be specified in CMake by `INTERPROCEDURAL_OPTIMIZATION` property or CMake just [isn't fully ready](https://cmake.org/Bug/view.php?id=15939) to support it for Gnu compilers. Do you wan't to try adding `CMAKE_RANLIB` and `CMAKE_AR` around [here](https://github.com/psi4/psi4/blob/master/cmake/ConfigChemps2.cmake#L34) and if that works, we'll get @SebWouters to alter CheMPS2's CMake accordingly?

**Comment by susilehtola** [comment]
As directed, I added
                   -DCMAKE_RANLIB=${CMAKE_RANLIB}
                   -DCMAKE_AR=${CMAKE_AR}
to ConfigChemps2.cmake, and added -DCMAKE_AR=/usr/bin/gcc-ar -D CMAKE_RANLIB=/usr/bin/gcc-ranlib to the setup command. Now it builds with the -flto flag in the CheMPS2 CMakeLists.txt.

**Comment by loriab** [comment]
I couldn't find a settled CMake way to handle this, so just noted the problem in the forthcoming CheMPS2 docs, added a FAQ in the Psi4 docs (https://github.com/psi4/psi4/wiki/9_CheMPS2#chemps2gccflto), and the changes to ConfigChemps2 will go in later today.
