### ISSUE TITLE
psi4so has install rule even when it's not built

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#415]
Configuring my psi4 I get the warning message

WARNING: Target "psi4so" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.

Looks like the install command for the psi4so target should be within an if clause checking if it's built or not.

**Comment by loriab** [comment]
Aside from the warning, the install is working properly whether one builds psi4so or not. The incompatibility of exclude_from_all and install seems well known, and I've only seen a rather complicated procedure to handle this w/o the warning. Whether psi4so gets built is not known at configure time, and I haven't seen a cmake check dependent on whether a make target was executed. I agree the warning is annoying, but is it really a problem for anything?

**Comment by susilehtola** [comment]
Not a problem, just annoying.
