### ISSUE TITLE
xyz format molecule parser does not accept atomic numbers instead of symbols

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#418]
The xyz format sometimes specifies atomic charges instead of atomic symbols, e.g.

6 0.0 0.0 0.0

instead of

C 0.0 0.0 0.0

If possible, it would be nice for the parser to be able to cope with this kind of a definition.

**Comment by loriab** [comment]
That would be nice. We're contemplating whether such capability can be added without making things like ghost labeling (`@H`, `Gh(H)`), atom labeling (`H5`, `H_special`), and mass labeling (`H@2.014`) ambiguous.

It's a touch convoluted, but in the meantime, you can get what you want with:

```
molxyz = """ 7
ang
8          0.00000000      -0.05786571      -1.47979303
7          0.00000000       0.01436394       1.46454628
1          0.00000000       0.82293384      -1.85541474
1          0.81348351       0.39876776       1.92934049
1          0.00000000       0.07949567      -0.51934253
1          0.00000000      -0.98104857       1.65344779
1         -0.81348351       0.39876776       1.92934049
"""

qmol = qcdb.Molecule.init_with_xyz(molxyz, contentsNotFilename=True)

pmol = geometry(qmol.create_psi4_string_from_molecule(), name='mymol')
pmol.update_geometry()
pmol.print_out()

compare_values(38.8138764635, pmol.nuclear_repulsion_energy(), 5, 'NRE')
```

**Comment by dgasmith** [comment]
Added to the developer wishlist. However, I lean towards Lori's comment where we dont want this to become too complex. In the future we may have something like `core.Molecule.build(input, input_type='numpy/Psi4/pdb/etc')`.
