### ISSUE TITLE
PSI4/WebMO coordinate scan compatibility

### ISSUE THREAD

**Issue by CDSherrill** [psi4/psi4#42]
WebMO can do nice coordinate scans but PSI4 can't parse the corresponding output.  Matt said he could look at this and that JR might have put in an update to WebMO to make it easier for us to handle.

**Comment by loriab** [comment]
I think @matthewkennedy6 fixed this for frozen scans. It's just relaxed scans that still need an interface.

**Comment by dgasmith** [comment]
@bwb314 @matthewkennedy6 I think this has been fixed? Please confirm.

**Comment by loriab** [comment]
I suspect this isn't implemented b/c it's a great bother expressing a ZMAT with proper DOF. If Brandon and Matt report fixed, all well and good. If not, I've moved the text to the psi4webmo issue, and this one can be closed anyway.

**Comment by dgasmith** [comment]
Signs point towards no. Regardless, this has been moved to https://github.com/psi4/psi4webmo/issues/9.

**Comment by bwb314** [comment]
@dgasmith This issue has not been resolved. I believe this is a WebMO issue as opposed to a Psi4 issue at this point.
