### ISSUE TITLE
SAD guess loses singly occupied orbitals

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#420]
Psi4 forgets socc when guess=core. Reduced test case

molecule {
0 2
Li
}

set basis STO-3G
set reference rohf
set guess sad
set docc [     1,    0,    0,    0,    0,    0,    0,    0 ]
set socc [     1,    0,    0,    0,    0,    0,    0,    0 ]
energy('scf')

With SAD guess, one gets

    Final Occupation by Irrep:
             Ag   B1g   B2g   B3g    Au   B1u   B2u   B3u 
    DOCC [     1,    0,    0,    0,    0,    0,    0,    0 ]
    SOCC [     0,    0,    0,    0,    0,    0,    0,    0 ]
  Energy converged.

  @DF-ROHF Final Energy:    -7.13546721504551

With core guess, one gets

    Final Occupation by Irrep:
             Ag   B1g   B2g   B3g    Au   B1u   B2u   B3u 
    DOCC [     1,    0,    0,    0,    0,    0,    0,    0 ]
    SOCC [     1,    0,    0,    0,    0,    0,    0,    0 ]

  Energy converged.

  @DF-ROHF Final Energy:    -7.31554523444454

**Comment by susilehtola** [comment]
There's a similar problem with guess=read: the DOCC and SOCC arguments are ignored.

**Comment by loriab** [comment]
In general, psi4 is `DOCC`/`SOCC` _or_ `guess`. That is, guess won't respect DOCC/SOCC. Good point that this could be better documented. Actually fixing this is scheduled for further development of the Wavefunction object.

**Comment by susilehtola** [comment]
OK, thanks for the info. Do you have any suggestions on how to get oscillatory ROHF calculations to converge when I know what the final occupations should be...? Damping doesn't seem to be implemented for ROHF.

**Comment by loriab** [comment]
Maybe soscf (http://psicode.org/psi4manual/master/autodir_options_c/module__scf.html#soscf) as in https://github.com/psi4/psi4/blob/master/samples/soscf2/test.in

**Comment by susilehtola** [comment]
Thanks for the pointer, I did realize it myself as well in the meantime - I didn't think you'd have such fancy stuff for ROHF. Anyways, I implemented the missing damping functions for ROHF, CUHF and UHF in #422.

**Comment by loriab** [comment]
soscf is new tech this spring from @dgasmith (apart from a specialization hidden away in a module). Thanks for the PR!

**Comment by dgasmith** [comment]
Fixed in #481.
