### ISSUE TITLE
Read guess ignores socc and docc

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#421]
This may be related to issue #420, but the read guess also behaves in a crazy fashion if you try to set docc and socc. Test case:

molecule neutral{
0 2
Na
}

molecule cation {
1 1
Na
}

activate(cation)
set basis STO-3G
set reference rhf
set guess core
energy('scf')

activate(neutral)
set basis STO-3G
set reference rohf
set guess read
set docc [     2,    0,    0,    0,    0,    1,    1,    1 ]
set socc [     1,    0,    0,    0,    0,    0,    0,    0 ]
energy('scf')

If one does not supply the latter step with the docc/socc specification, the result is

    Final Occupation by Irrep:
             Ag   B1g   B2g   B3g    Au   B1u   B2u   B3u 
    DOCC [     2,    0,    0,    0,    0,    1,    1,    1 ]
    SOCC [     1,    0,    0,    0,    0,    0,    0,    0 ]

  Energy converged.

  @DF-ROHF Final Energy:  -159.66461226804716

If one does include the specification, the result is

    Final Occupation by Irrep:
             Ag   B1g   B2g   B3g    Au   B1u   B2u   B3u 
    DOCC [     2,    0,    0,    0,    0,    1,    1,    1 ]
    SOCC [     0,    0,    0,    0,    0,    0,    0,    0 ]

  Energy converged.

  @DF-ROHF Final Energy:  -159.78073099020281

so the odd electron vanishes.

**Comment by dgasmith** [comment]
Fixed in #481, note that both molecules must of the same name or the previous orbitals will not be read.
