### ISSUE TITLE
detci 

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#423]
The documentation in the manual for detci
http://www.psicode.org/psi4manual/master/detci.html

states that the maximum number of iterations to diagonalize the Hamiltonian is set by MAXITER, the default of which is 12.

However, if one sets maxiter to 5 in the runfile, psi4 crashes because SCF convergence wasn't attained in 5 iterations, and if one sets maxiter to 50, detci crashes due to non-convergence after 25 iterations.

So, there are two problems:

1) I think the keyword specified in the manual is incorrect, because plain MAXITER does not control DETCI but rather the SCF parameter. Increasing the value of CI_MAXITER (which I found by trial and error) I was able to get FCI to converge.
2) The default value is not 12, but 25, as demonstrated by the trial.

**Comment by susilehtola** [comment]
A test case is attached.

[input.txt](https://github.com/psi4/psi4/files/331251/input.txt)

**Comment by loriab** [comment]
This one's easily explained. The renaming of `MAXITER` to `CI_MAXITER` and the bump from 12 to 24 was in 9af83964be3fab03d77216c68e829270fef55d48 a few days ago. I'm working on redoing the binary packaging, so the docs just haven't been rebuilt to reflect the new options status. Before the renaming, you could have gotten the desired behavior by setting the scope, e.g., `set detci maxiter 5`.

**Comment by loriab** [comment]
code and docs reconciled (http://psicode.org/psi4manual/master/detci.html?highlight=ci_maxiter#ci-maxiter) by ec674458351f393db94fed4b7c37693e5639e67f
