### ISSUE TITLE
Compiling error: lib/libmints/matrix.cc (icpc 16.0.3)

### ISSUE THREAD

**Issue by edeustua** [psi4/psi4#444]
The Intel C++ compiler (16.0.3 20160415) is complaining about line 2474 during the compilation of matrix.cc.

```cpp
2474                 if (std::isfinite(a[i])) {
2475                     remain++;
2476                 } else {
2477                     a[i] = 0.0;
2478                 }
```

Apparently there is a namespace conflict due to the `using namespace std`. Dropping the `std::` in line   2474 fixes the problem.

**Comment by dgasmith** [comment]
@edeustua Good to know. I think #442 should fix this, but we can certainly test it out after that patch drops.

**Comment by edeustua** [comment]
The following files:

lib/libfock/solver.cc
lib/libscf_solver/uhf.cc
lib/libscf_solver/rhf.cc
lib/libscf_solver/rohf.cc

have the same problem.

**Comment by ryanmrichard** [comment]
My apologies on the late reply.  I am unable to replicate this problem with icpc 16.0.2.  Admittedly I used the version of Psi4 in #442.  That being said, I am skeptical that fully scoping the function is actually causing @edeustua's compile error (I am fairly certain that you can always fully scope a function/type in C++).  @edeustua, can you post the actual error log, as well as the configure command you used?

**Comment by jturney** [comment]
Yeah I can't reproduce with 16.0.2 either. What version of gcc is the Intel compiler using?

**Comment by kannon92** [comment]
I have also had trouble with intel 16.0.3 on my mac.  I have not been able to compile PSI4 with intel. 

Here is what appears if I do, icpc -v

    icpc version 16.0.3 (gcc version 4.9.0 compatibility) 

I got a bunch of errors in dcft/dcft_df_tensor.cc about how the compiler can't recognize ">>", so I changed all instances of ">>" to "> >".  This seems to work, but I get another error in detci/ciwave.h.  

    In file included from /Users/kevinhannon/Programs/psi4/psi4src/src/bin/detci/params.cc(49):
    /Users/kevinhannon/Programs/psi4/psi4src/src/bin/detci/ciwave.h(414): error: namespace "std"     has no member "tuple"
                                                  std::vector<std::tuple<int, int> > states_vec);
                                                                   ^

    In file included from /Users/kevinhannon/Programs/psi4/psi4src/src/bin/detci/params.cc(49):
    /Users/kevinhannon/Programs/psi4/psi4src/src/bin/detci/ciwave.h(414): error: expected a ">"
                                                  std::vector<std::tuple<int, int> > states_vec);
                                                                        ^

    In file included from /Users/kevinhannon/Programs/psi4/psi4src/src/bin/detci/params.cc(49):
    /Users/kevinhannon/Programs/psi4/psi4src/src/bin/detci/ciwave.h(414): error: expected a ")"
                                                  std::vector<std::tuple<int, int> > states_vec);
                                                                                 ^

    In file included from /Users/kevinhannon/Programs/psi4/psi4src/src/bin/detci/params.cc(49):
    /Users/kevinhannon/Programs/psi4/psi4src/src/bin/detci/ciwave.h(434): error: namespace "std"    has no member "tuple"
                                     std::vector<std::tuple<int, int, double> > states_vec);
                                                      ^

     In file included from /Users/kevinhannon/Programs/psi4/psi4src/src/bin/detci/params.cc(49):
     /Users/kevinhannon/Programs/psi4/psi4src/src/bin/detci/ciwave.h(434): error: expected a ">"
                                     std::vector<std::tuple<int, int, double> > states_vec);
                                                           ^

     In file included from /Users/kevinhannon/Programs/psi4/psi4src/src/bin/detci/params.cc(49):
     /Users/kevinhannon/Programs/psi4/psi4src/src/bin/detci/ciwave.h(434): error: expected a ")"
                                     std::vector<std::tuple<int, int, double> > states_vec);
                                                                            ^

     compilation aborted for /Users/kevinhannon/Programs/psi4/psi4src/src/bin/detci/params.cc (code 2)

**Comment by ryanmrichard** [comment]
@kannon92 somehow your C++11 is not activating.

**Comment by kannon92** [comment]
I am able to compile ambit separately from PSI4 with the intel compilers.  I also get to around 50-60 percent of the compilation before the code fails.  This makes me think that my C++11 is working fine.  

Do you have any idea of what I can do to fix this problem?

**Comment by andysim** [comment]
Does adding `#include <tuple>` to `src/bin/detci/params.cc` fix it?

**Comment by kannon92** [comment]
If only.  I added #include <tuple> to src/bin/detci/ciwave.h (and params), but I still get the error.

**Comment by andysim** [comment]
How about adding `-std=c++11` to the `--extra-cxx-flags` argument to `setup` (or `-DEXTRA_CXX_FLAGS` if you're calling CMake directly)?

**Comment by ryanmrichard** [comment]
The not recognizing template brackets is a language feature, not part of
the library like the tuple.  I bet if you print the compile command the
flag Andy told you to add is missing.  Assuming that is the case, the
million dollar question is why?  I have guesses from insight learned in the
CMake rewrite.   Assuming it is one of those guesses, the problem should go
away with the rewrite.

**Comment by kannon92** [comment]
Everything works fine for me on my end.  It seems that I forgot to include those c++ flags.

**Comment by dgasmith** [comment]
I think this can be closed. Is this still showing up as an issue for anyone?
