### ISSUE TITLE
Full CI diverge on some calculation

### ISSUE THREAD

**Issue by tyzhang1993** [psi4/psi4#448]
==> Input File <==

--------------------------------------------------------------------------
molecule N2{
N
N 1 2.58
units bohr
}
set {
  basis cc-pVDZ
  scf_type pk
  DOCC [3,0,0,0,0,2,1,1]
  e_convergence 10
  d_convergence 10
  r_convergence 10
  FROZEN_DOCC [1,0,0,0,0,1,0,0]
  Maxiter 100
  Num_roots 1
}

energy('fci')

--------------------------------------------------------------------------

This calculation diverge after iteration 50

  ==> End Of Output File <==
Iter 41  Root  1 = -109.192522175   Delta_E -1.929E-12   Delta_C  4.066E-06
Iter 42  Root  1 = -109.192522175   Delta_E -9.223E-12   Delta_C  8.618E-06
Iter 43  Root  1 = -109.192522175   Delta_E -4.168E-11   Delta_C  1.799E-05
Iter 44  Root  1 = -109.192522175   Delta_E -1.870E-10   Delta_C  3.800E-05
Iter 45  Root  1 = -109.192522176   Delta_E -8.855E-10   Delta_C  8.431E-05
Iter 46  Root  1 = -109.192522181   Delta_E -4.538E-09   Delta_C  1.955E-04
Iter 47  Root  1 = -109.192522205   Delta_E -2.466E-08   Delta_C  4.665E-04
Iter 48  Root  1 = -109.192522355   Delta_E -1.496E-07   Delta_C  1.179E-03
Iter 49  Root  1 = -109.192523753   Delta_E -1.398E-06   Delta_C  4.152E-03
Iter 50  Root  1 = -109.968750624   Delta_E -7.762E-01   Delta_C  3.339E+00
Iter 51  Root  1 = -118.722003520   Delta_E -8.753E+00   Delta_C  1.458E+01
Iter 52  Root  1 = -145.122489317   Delta_E -2.640E+01   Delta_C  5.957E+01
Iter 53  Root  1 = -172.017439239   Delta_E -2.689E+01   Delta_C  1.206E+02
Iter 54  Root  1 = -198.930392334   Delta_E -2.691E+01   Delta_C  1.936E+02
Iter 55  Root  1 = -225.849104619   Delta_E -2.692E+01   Delta_C  2.771E+02
Iter 56  Root  1 = -252.770463097   Delta_E -2.692E+01   Delta_C  3.698E+02
Iter 57  Root  1 = -279.693265542   Delta_E -2.692E+01   Delta_C  4.709E+02
Iter 58  Root  1 = -306.616944155   Delta_E -2.692E+01   Delta_C  5.797E+02
Iter 59  Root  1 = -333.541194861   Delta_E -2.692E+01   Delta_C  6.958E+02
Iter 60  Root  1 = -360.465839881   Delta_E -2.692E+01   Delta_C  8.188E+02
Iter 61  Root  1 = -387.390768249   Delta_E -2.692E+01   Delta_C  9.481E+02
Iter 62  Root  1 = -414.315907096   Delta_E -2.693E+01   Delta_C  1.084E+03
Iter 63  Root  1 = -441.241206582   Delta_E -2.693E+01   Delta_C  1.225E+03
Iter 64  Root  1 = -468.166631458   Delta_E -2.693E+01   Delta_C  1.372E+03
Iter 65  Root  1 = -495.092156090   Delta_E -2.693E+01   Delta_C  1.525E+03
Iter 66  Root  1 = -522.017761386   Delta_E -2.693E+01   Delta_C  1.682E+03
Iter 67  Root  1 = -548.943432837   Delta_E -2.693E+01   Delta_C  1.845E+03
Iter 68  Root  1 = -575.869159217   Delta_E -2.693E+01   Delta_C  2.013E+03
Iter 69  Root  1 = -602.794931704   Delta_E -2.693E+01   Delta_C  2.186E+03

Similar phenomenon happened when bond length is 1.8 bohr.
Can anyone check why this happen please?

**Comment by kannon92** [comment]
Could you try running these with CALC_S_SQUARED true?  I usually use this key word when I converge on a wrong root, but it is possible that you are exhibiting convergence problems because you are converging on a wrong root.

**Comment by dgasmith** [comment]
This is a Davidson error. Looks like as soon as the norm of the correction vector gets small enough an instability occurs causing a non-variational energy. Very hard to debug and/or fix. Dividing small numbers by small numbers is always tricky.

If you are just after the energy (the only things the current CI code can do) the simplest option is to reduce your CI convergence threshold to something reasonable like `r_convergence 1.e-4` . You can also try setting `hd_avg hd_exact` in your settings.

**Comment by tyzhang1993** [comment]
Thank you for your comments. I will move it to Psi forums.
