### ISSUE TITLE
Boost removal

### ISSUE THREAD

**Issue by dgasmith** [psi4/psi4#450]
Greetings friends,
As per the developer wish list ( #402) it was decided that boost should be removed from Psi4 as there is little point in keeping it around when all the needed features are in C++11. When removing boost we gain:
 - Fewer dependencies
 - More canonical operations through C++ standards
 - Simpler and more expressive python bindings
 - Fewer python lib issues (in theory)
 - You will no longer get six pages of error messages when boost templates fail in some way
 - Build simplification and faster compiler time
 - Fewer compiler warning (lots from boost)
 - Less CI hassle
 - There will be a party with cake and burning of a boost effigy (streamed and tweeted)

--

My primary goal is to tackle boost python and convert all existing code to PyBind11. Through this I will tackle the following boost libraries: python, tuple, lexical, shared_ptr, and math. I have a reasonable plan to accomplish this and initial tests show that I should be able to pull it off.

--

However, there are other libraries that I could use help converting either in the form ideas or some of the grunt work. These are:

Boost filesystem:
* [x] ```bin/fisapt/fisapt.cc:#include <boost/filesystem.hpp>```
* [x] ```bin/psi4/create_new_plugin.cc:#include <boost/filesystem.hpp>```
* [x] ```bin/psi4/create_new_plugin.cc:#include <boost/filesystem/operations.hpp>```
* [x] ```bin/psi4/export_plugins.cc:#include <boost/filesystem.hpp>```
* [x] ```bin/psi4/psi_start.cc:#include <boost/filesystem.hpp>```
* [x] ```bin/psi4/python.cc:#include <boost/filesystem.hpp>```
* [x] ```lib/libcubeprop/csg.cc:#include <boost/filesystem.hpp>```
* [x] ```lib/libcubeprop/cubeprop.cc:#include <boost/filesystem.hpp>```
* [x] ```lib/libefp_solver/efp_solver.cc:#include <boost/filesystem.hpp>```
* [x] ```lib/libmints/basisset.cc:#include <boost/filesystem.hpp>```
* [x] ```lib/libplugin/load_plugin.cc:#include <boost/filesystem.hpp>```

For most of these we would likely let Python handle the filesystem paths and just pass them into C-side as a `std::string`.

--
Boost thread:
* [x] ```lib/libpsio/aio_handler.cc:#include <boost/thread/thread.hpp>```
* [x] ```lib/libpsio/aiohandler.h:#include <boost/thread/thread.hpp>```
* [x] ```lib/libpsio/filemanager.cc:#include <boost/thread.hpp>```
* [x] ```lib/libpsio/psio.hpp://#include <boost/thread/thread.hpp>```

`std::thread` is a drop in replacement here for our uses.

--
Boost regex:
* [x] ```bin/psi4/create_new_plugin.cc:#include <boost/regex.hpp>```
* [x] ```lib/lib3index/denominator.cc:#include <boost/regex.hpp>```
* [x] ```lib/libefp_solver/efp_solver.cc:#include <boost/regex.hpp>```
* [x] ```lib/libmints/basisset.cc:#include <boost/regex.hpp>```
* [x] ```lib/libmints/basisset_parser.cc:#include <boost/regex.hpp>```
* [x] ```lib/libmints/get_writer_file_prefix.cc:#include <boost/regex.hpp>```
* [x] ```lib/libmints/matrix.cc:#include <boost/regex.hpp>```
* [x] ```lib/libmints/molecule.cc:#include <boost/regex.hpp>```
* [x] ```lib/libmints/oeprop.cc:#include <boost/regex.hpp>```
* [x] ```lib/libplugin/load_plugin.cc:#include <boost/regex.hpp>```
* [x] ```lib/libthce/laplace.cc:#include <boost/regex.hpp>```

`std::regex` is a drop in replacement **except** no more pearl syntax support. Not sure how much pearl we use, I think its all python based so we *should* be fine.

--
Boost serial:
* [x] ```lib/libmints/serializers.h:#include <boost/serialization/serialization.hpp>```

No idea here, do we actually use our serialization capability?

--
Boost xpressive(??):
* [x] ```bin/psi4/create_new_plugin.cc:#include <boost/xpressive/xpressive.hpp>```
* [x] ```lib/lib3index/denominator.cc:#include <boost/xpressive/xpressive.hpp>```
* [x] ```lib/libmints/basisset.cc:#include <boost/xpressive/xpressive.hpp>```
* [x] ```lib/libmints/basisset_parser.cc:#include <boost/xpressive/xpressive.hpp>```
* [x] ```lib/libmints/matrix.cc:#include <boost/xpressive/xpressive.hpp>```
* [x] ```lib/libplugin/load_plugin.cc:#include <boost/xpressive/xpressive.hpp>```
* [x] ```lib/libthce/laplace.cc:#include <boost/xpressive/xpressive.hpp>```

Since Xpressive is based off boost spirit it scares me a bit. Not sure what this does exactly.

--
Also, @andysim I still have no idea on EFP. I would need your help to remove boost from that.

I will be traveling until August 10th at which point ill start ripping this out provided we have a path forward for the remaining issues.

-- 
### LAB edit, 4 Aug

big ticket items/dependencies:
* [x] `add_custom_target(BoostPy)` convert Boost Python to Pybind11
* [x] `add_custom_target(BoostNonPy)` evict all the other Boost libraries we depend on (checkboxed above)
* [x] `add_custom_target(FilterBranch DEPENDS BoostPy BoostNonPy)` remove all Boost tarballs and other large files from repo

**Comment by kannon92** [comment]
For std::regex, I just found out that regex is not supported on gcc 4.8.  You won't get any compile errors, but we get some runtime errors.  All of this goes away if you use GCC 4.9 or GCC 5.2.0.  

Just a heads up.  Looking forward to these changes.

**Comment by loriab** [comment]
The efp boost::filesystem and boost::regex issues I think I know my way around. boost::filesystem in general will probably be tied to The Flip, and I can try to work on these en masse.

**Comment by dgasmith** [comment]
@kannon92 GCC 4.8 is feature complete on the compiler side; however, is not a fully compliant C++11 compiler. GCC 4.9 will be the first GCC that we will support.

**Comment by andysim** [comment]
@kannon92 and @dgasmith.  It's great to be aware of issues like this.  We've been supporting GCC 5 for a long time on Travis, so demanding 4.9 (circa April 2014) is not much of a restriction.

**Comment by andysim** [comment]
@dgasmith LibEFP is pure C, so there's no Boost in there (at least that I'm aware of).  I think that means I'm off the hook!  A lot of the work can be done using the refactoring tools in Qt Creator and/or a Python script, I hope.

**Comment by jturney** [comment]
The libmints stuff should be easy to resolve.

Maybe we can look to move the create plugin code to Python.

**Comment by dgasmith** [comment]
@andysim To be clear I meant the libefp_solver interface, still not quite sure what tokenizer is doing for you in there.

**Comment by andysim** [comment]
I'm absolved, according to `git blame`:
```
79b7ae38 (Lori Burns      2014-12-05 00:12:31 -0500  38) boost::regex efpAtomSymbol("A\\d*([A-Z]{1,2})\\d*", boost::regbase::normal | boost::regbase::icase);
79b7ae38 (Lori Burns      2014-12-05 00:12:31 -0500  39) boost::smatch reMatches;
```

Over to you, @loriab!

**Comment by loriab** [comment]
Yes @andysim, I'm definitely responsible for the crazy path that EFPs take through psi4. Without the boost registration restrictions on the efp class and the general c-side focus, perhaps I can find a better way. I'll take on the efp and filesystem aspects of The Inversion.

I agree @jturney on moving plugin-writing to python. In fact, that may get done in the CMake rewrite, just to avoid having to get things working again _twice_.

**Comment by loriab** [comment]
Greetings, all. It's time to schedule Kill the Boost week! There are three major parts of this, as I see it: BoostPy, BoostNonPy, and FilterBranch. These are defined in the addendum to the top post of this ticket. I imagine the in-person and through-hangout times will be focused on the BoostPy target, though we should all be working on the BoostNonPy as convenient.

So, please to add your availability to the weeks below. Reply or feel free to edit this comment.

**Aug 15:** LAB-ok
**Aug 22 (ACS Nat'l Mtg):** LAB-ok
**Aug 29:** LAB-ok

**Comment by dgasmith** [comment]
Completed in #442!
