### ISSUE TITLE
OpenMP linking problem with CheMPS2

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#452]
Trying to compile current trunk with

```
./setup --max-am-eri 7 --cc gcc --cxx g++ --fc gfortran --prefix /global/home/groups-sw/mhg/psi4/install  --plugins --gdma on --pcmsolver on --chemps2 on --ambit on objdir -DPYTHON_INTERPRETER=${PYTHON_DIR}/bin/python -DENABLE_XHOST=OFF
```

fails with an OpenMP linking error in CheMPS2

../../../interfaces/chemps2/install/lib/libchemps2.a(CASPT2.cpp.o): In function `_ZN7CheMPS26CASPT210make_AA_CCEbd._omp_fn.29':
/global/home/groups-sw/mhg/psi4/psi4.git/objdir/interfaces/chemps2/src/interface_chemps2/CheMPS2/CASPT2.cpp:5457: undefined reference to`omp_get_num_threads'
/global/home/groups-sw/mhg/psi4/psi4.git/objdir/interfaces/chemps2/src/interface_chemps2/CheMPS2/CASPT2.cpp:5457: undefined reference to `omp_get_thread_num'
../../../interfaces/chemps2/install/lib/libchemps2.a(CASPT2.cpp.o): In function`_ZN7CheMPS26CASPT210make_AA_CCEbd._omp_fn.30':
/global/home/groups-sw/mhg/psi4/psi4.git/objdir/interfaces/chemps2/src/interface_chemps2/CheMPS2/CASPT2.cpp:5473: undefined reference to `omp_get_num_threads'
/global/home/groups-sw/mhg/psi4/psi4.git/objdir/interfaces/chemps2/src/interface_chemps2/CheMPS2/CASPT2.cpp:5473: undefined reference to`omp_get_thread_num'
../../../interfaces/chemps2/install/lib/libchemps2.a(CASPT2.cpp.o): In function `_ZN7CheMPS26CASPT210make_AA_CCEbd._omp_fn.31':

and a bunch of other missing OpenMP symbol errors from libchemps2.a.

**Comment by loriab** [comment]
I'm not ignoring this issue so much as I hadn't gotten to CheMPS2 in the cmake rewrite until yesterday. I'll be sure to check it with g++. It's conceivable that it was only working with intel compilers.

**Comment by ryanmrichard** [comment]
I compiled everything (including Chemps2) in the CMakeRewrite with gcc.
For the most gcc tends to be one of the more strict compilers so if you can
compile with it, you can compile with anything.  Although this doesn't help
on the old build it does hopefully provide some solace....

**Comment by loriab** [comment]
Quite, I meant the pre-CMakeRewrite I wouldn't have been surprised if only intel+mkl or Kevin's gcc+mkl worked.

**Comment by dgasmith** [comment]
The make system has been overhauled since this PR was opened and this is not likely to be applicable any longer. @susilehtola please confirm.

**Comment by susilehtola** [comment]
Yes, PSI4 compiles with CheMPS2. However, it still needs explicit definitions for
-DCMAKE_AR="/usr/bin/gcc-ar" -DCMAKE_RANLIB="/usr/bin/gcc-ranlib"

**Comment by loriab** [comment]
Yes, I expect so. CMake just doesn't know how to fully handle `lto` yet. I don't know that there's a workaround besides what you mentioned, which is [in the CheMPS2 manual](http://sebwouters.github.io/CheMPS2/sourcecode.html#build-the-chemps2-library-and-binary) now. I suspect I don't notice it because I `BUILD_SHARED_LIBS=ON` or link to pre-built. I'm satisfied with the situation, but I'd be glad to improve it if you've any suggestions.

**Comment by dgasmith** [comment]
Closing this out unless further suggestions are offered.
