### ISSUE TITLE
composite method wrapper error

### ISSUE THREAD

**Issue by wardence** [psi4/psi4#455]
I was trying to run a calculation using the following composite method:

energy('MP2/aug-cc-pV([T, Q]+d)Z + D:FNO-CCSD(T)/aug-cc-pV(T+d)Z', bsse_type = 'cp') 

The calculation seems to run fine, but the final energy table looks wrong.

  -------------------------------------------------------------------------------
                          Method / Basis                      Rqd      Energy [Eh]   Variable
  -------------------------------------------------------------------------------
                  mp2 / aug-cc-pv(q+d)z                 *    -709.56313021   MP2 TOTAL ENERGY
                  hf / aug-cc-pv(q+d)z                     *    -707.60123747   HF TOTAL ENERGY
                  scf / aug-cc-pv(t+d)z                           -707.58023768   SCF TOTAL ENERGY
                  mp2 / aug-cc-pv(t+d)z                   *    -709.35534062   MP2 TOTAL ENERGY
                fno-ccsd(t) / aug-cc-pv(t+d)z           *    -709.50405507   CCSD(T) TOTAL ENERGY
                 ccsd / aug-cc-pv(t+d)z                          -709.42134394   CCSD TOTAL ENERGY
  -------------------------------------------------------------------------------

   ==> Stages <==

  ---------------------------------------------------------------------------------------------------------
      Stage               Method / Basis                       Wt      Energy [Eh]   Scheme
  ---------------------------------------------------------------------------------------------------------
        scf                   hf / aug-cc-pv(q+d)z             1    -707.60123747   xtpl_highest_1
      corl                  mp2 / aug-cc-pv([tq]+d)z        1    -709.71476045   corl_xtpl_helgaker_2
       corl                   hf / aug-cc-pv([tq]+d)z        -1   -1223.95889724   corl_xtpl_helgaker_2
      delta          fno-ccsd(t) / aug-cc-pv(t+d)z         1    -709.50405507   xtpl_highest_1
      delta                  mp2 / aug-cc-pv(t+d)z         -1    -709.35534062   xtpl_highest_1
  ---------------------------------------------------------------------------------------------------------

   ==> CBS <==

  -------------------------------------------------------------------------------
      Stage               Method / Basis                               Energy [Eh]             Scheme
  -------------------------------------------------------------------------------
        scf                   hf / aug-cc-pv(q+d)z                   -707.60123747   xtpl_highest_1
       corl                  mp2 / aug-cc-pv([tq]+d)z              514.24413679   corl_xtpl_helgaker_2
      delta    fno-ccsd(t) - mp2 / aug-cc-pv(t+d)z         -0.14871446       xtpl_highest_1
      total                  CBS                                                -193.50581514
  -------------------------------------------------------------------------------

[363_2_in.txt](https://github.com/psi4/psi4/files/404462/363_2_in.txt)
[363_2_out.txt](https://github.com/psi4/psi4/files/404463/363_2_out.txt)

**Comment by loriab** [comment]
Anyone getting this should change the `SCF` and `SCF TOTAL ENERGY` in https://github.com/psi4/psi4/blob/master/share/python/driver_cbs.py#L430 to `HF` and `HF TOTAL ENERGY` like in the "ccsd" entry just below. I'll prepare a PR fix.
