### ISSUE TITLE
fcidump file generation

### ISSUE THREAD

**Issue by lucamontana** [psi4/psi4#458]
Dear Developers, 

I like to know (before doing a full installation of the code) whether the new PSI4 for generation of FCIDUMP file for a subsequent dmrg calculation takes advantage of density fitting or not ?

I remember it performed a full 2-electron integral calculation in serial before entering dmrg calculation in the older version of the code. 

Bests
LUCA

**Comment by loriab** [comment]
As far as I know, the only code for generating FCIDUMP through Psi4 is in one of my branches: https://github.com/loriab/psi4/commits/fcidump . I don't suspect it of being wrong, but it's not yet verified. You're welcome to try it with `set DMRG_FCIDUMP_EXIT true`. Whatever the Hamiltonian object possesses is what gets dumped. [This](https://github.com/loriab/psi4/commit/4a1d05be7ed592cd15407bf8ac416624366c825e) is the primary change in Psi4's CheMPS2 from 1.5 to 1.7. I don't recall any deliberate DF changes.
