### ISSUE TITLE
looks good to me

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#459]
There is a service, LGTM, that will (like Travis and Distelli) place a block on merging PRs until at least a specified number of core developers in a list indicate their approval by replying "LGTM" (looks good to me). This could be a way of checking that multiple pairs of eyes have looked over PRs and ensuring that decisions have a broad approval base. Any comments or willingness to participate?

Read more at https://lgtm.co/docs/overview/

**Comment by andysim** [comment]
It was something like this that I had in mind when I added checkboxes to the PR template.  I figured that we could have a list of people to sign of, but LGTM does it in a much cleaner way.  I think it's a very good idea.

**Comment by jturney** [comment]
Looks good to me. 👍

**Comment by loriab** [comment]
I think the "Ready to go" checkbox is very useful even with LGTM, as it can signal when the submitter is ready for final review.

**Comment by andysim** [comment]
Oh, yes, I agree with keeping the submitter's RTG box.  I had originally planned to also add some LGTM-like checkboxes for reviewers.

**Comment by dgasmith** [comment]
LGTM

**Comment by loriab** [comment]
Ok, yes, I see what you mean, @andysim.

Any thoughts on number? Two is the default, but three would pretty much ensure non-GT-centricity.

**Comment by andysim** [comment]
Apart from #442, the PRs are normally quite small so it's not much work to review them.  I think we should have at least three or four signees, especially given that most of the recent PRs have had feedback from many developers anyway.  If we start high, we can reduce the demands if it becomes too burdensome.

**Comment by loriab** [comment]
LGTM

**Comment by jturney** [comment]
I think at least three; or up to four as @andysim suggests.

**Comment by loriab** [comment]
The more the better, in my opinion, as long as ppl are willing to look them over.

I think we always have the option to merge w/o checks or do direct commits, just as we do now, in time-constrained situations. I haven't noticed anyone doing that too liberally, and if anyone objects to my practices of it (besides the week-ago-Friday Hessian driver tweak), please let me know.

**Comment by loriab** [comment]
Looks like one either has a maintainers file (awkward at the moment b/c we don't want to rebase CMakeRewrite again) or it falls back on the maintainers team (https://github.com/orgs/psi4/teams/maintainers). Add or suggest, as you like.

**Comment by andysim** [comment]
I vote for the maintainers team; I can't think of a case where we'd want somebody on the maintainers list but not approving PRs.

**Comment by loriab** [comment]
Agree with favoring team. It won't require a commit and is less political.

**Comment by loriab** [comment]
It's enabled and looks to be active. I haven't defined a `.lgtm` file (https://lgtm.co/docs/customize/) to set it at 4 or 3 because of the CMakeRewrite freeze, so it's probably at 2 for now.

**Comment by robertodr** [comment]
This looks cool! :+1: And I can also lend a hand with looking over PRs, if that's OK for you.

**Comment by loriab** [comment]
Great, thanks @robertodr . Anyone thinking of implementing this on their own repos should be aware of https://github.com/lgtmco/lgtm/issues/10 . All it means in practice is you have to redo the checkboxes of required checks on your protected branches (i.e., I had to re-checkmark Travis as required for psi4/psi4).
