### ISSUE TITLE
Parallelization

### ISSUE THREAD

**Issue by lucamontana** [psi4/psi4#461]
Dear all, 

is the 2e integral calculation meanwhile parallelized in PSI4 ?
Bests
LUCA

**Comment by loriab** [comment]
Wasn't this issue completely different a couple minutes ago? https://github.com/psi4/psi4/blob/master/samples/cc46/input.dat is the answer to that question.

**Comment by lucamontana** [comment]
Thanks Lori, i instantly found the answer and was unable to delete my post.
However how can i set the convergence threshold (rms) in eom-CC2 to what i like ?
What is the CC2 specific keyword for it ? 

Is in the new version of ps4 the 2electron integral still in serial ?

many thanks.
LUCA

**Comment by lucamontana** [comment]
many thanks Lori. I instantly found the answer and was unable to delete my post.
Best
LUCA
