### ISSUE TITLE
Frozen Virtual Orbital Approximation

### ISSUE THREAD

**Issue by lucamontana** [psi4/psi4#462]
Dear all, 

I try to freeze some virtual orbitals in eom-CC3 calculation with set frozen_uocc [...], however
PSI4 crashes. Any way how to freeze virtual orbitals in eom-CC3 run ?

set frozen_uocc [15] works for eom-ccsd but not for eom-cc3!

Best
LUCA

**Comment by lothian** [comment]
We often freeze virtual orbitals in our CC calculations.  A sample input
and output would be helpful here.

-TDC

--
Prof. T. Daniel Crawford
crawdad@vt.edu

**Comment by lucamontana** [comment]
Here an input file : it simply crashes with no specific error.
molecule c2h3 {
C            .049798    -.576272     .000000
C            .049798     .710988     .000000
H           -.876750   -1.151844     .000000
H            .969183   -1.154639     .000000
H           -.690013    1.498185     .000000
units ang
symmetry c1
}
set basis  cc-pvdz          
set scf_type df
set cc_type  df

set guess GWH
set reference rohf
set MAXITER  1000

set e_convergence  1e-6
set d_convergence  1e-6
set ints_tolerance 1e-8

set FROZEN_DOCC [2]
set frozen_uocc [10]
set roots_per_irrep [4]
energy('eom-cc3')

**Comment by lucamontana** [comment]
One further question : does n't CC use density fitting ?
I set CC_type to DF, however 2 electron integral calculation seems not to use DF !!!

**Comment by jturney** [comment]
The EOM code predates our density fitting effort and still uses conventional 4-center integrals.

**Comment by andysim** [comment]
I just ran the input, and it produces (admittedly unhelpful) error message `Fatal Error: UHF Density fitting NYI`.  The CC3 code is not set up to use density fitting yet, unfortunately.  If you remove the `cc_type` keyword, it runs correctly.

**Comment by lucamontana** [comment]
For me even without cc_type does n't work ! I am not using the last version of PSI4.
ok, any remedy to use DF in CC calculations or absolutely no way ?

**Comment by andysim** [comment]
We have a number of density fitted [CC features](http://www.psicode.org/psi4manual/master/introduction.html#capabilities), but not EOM yet, I'm afraid.

**Comment by loriab** [comment]
This chart is even more fine-grained: http://psicode.org/psi4manual/master/notes_c.html#alternate-implementations . No DF for excited states, though.

**Comment by lucamontana** [comment]
ok, do you know of any code capable of performing calculations with DF for excited states + frozen core and orbital virtual approximation for both closed and open shell molecules  ?

**Comment by loriab** [comment]
None that I know of, though admittedly the period when I was conversant with package capabilities for excited states did not overlap the period when conversant with DF. Maybe investigate Molpro?

**Comment by andysim** [comment]
Maybe [Q-Chem](http://www.q-chem.com/qchem-website/features4.htm#coupled)?

**Comment by lucamontana** [comment]
Too expensive, maybe an open source code ?

**Comment by lucamontana** [comment]
Do you have any experiences with ACE III ?

**Comment by lucamontana** [comment]
Ok, guys many thanks for your helps and time.
