### ISSUE TITLE
Cholesky decomposition wishlist

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#476]
Here lie uses for general Cholesky machinery.

* Fock-type terms in DF-SAPT, particularly higher-order, see #317 
* If you care about 6-zeta accuracy, you probably oughtn't to be using density fitting. Nevertheless, having orbital basis sets for which _no_ auxiliary is appropriate (even as overkill, like QZ for sto-3g) is troubling for the auxiliary defaulting machinery. On-the-fly construction could help. Maybe a more plausible case is when auxiliary basis sets aren't available for a particular element or for tight functions.

**Comment by susilehtola** [comment]
Well, you could do compact atomic Cholesky to construct a fitting basis for an arbitrary orbital basis set on-the-fly. [doi 10.1063/1.3116784]
