### ISSUE TITLE
OPDM and TPDM not written

### ISSUE THREAD

**Issue by ravenschade** [psi4/psi4#477]
When running psi4 with the input file, i.e. psi4 h2.in h2.out

>memory 2500 mb
>
>molecule h2 {
>   H 
>    H 1 0.75
>}
>
>set basis def2-QZVPP
>set FCI true
>set OPDM true
>set OPDM_PRINT true
>set TPDM true
>set TPDM_PRINT true
>energy('detci')

no one-particle density matrix or two-particle density matrix is written to the output file h2.out and other files except the output file h2.out and timer.dat are created.
See also: http://www.psicode.org/psi4manual/master/autodoc_glossary_options_c.html#term-opdm-print-detci

**Comment by dgasmith** [comment]
Hmm, looks like I missed this option. Ill create a patch for it.

For now you can do the following:

```python
e, wfn = energy('detci', return_wfn=True)
wfn.get_opdm(-1, -1, "SUM", False).print_out()
wfn.get_tpdm("SUM",  False).print_out()
```

OPDM signature is as follows:
```
    /**!
     * Obtains the OPDM <Iroot| Epq |Jroot> from the ciwave object. If Jroot is
     * negative then Iroot == Jroot, if both roots are -1 then the "special" CI
     * OPDM is returned.
     * @param Iroot      Left root
     * @param Jroot      Right root
     * @param spin       Selects which spin to return: A, B, or SUM
     * @param full_space If false return only the active OPDM else return full OPDM
     * @return OPDM or TDM shared matrix
     **/
    SharedMatrix get_opdm(int Iroot=-1, int Jroot=-1, const std::string& spin="SUM",
                           bool full_space=false);
```

**Comment by ravenschade** [comment]
Works, many Thanks!
