### ISSUE TITLE
Problem with curl flag in installation instructions

### ISSUE THREAD

**Issue by berquist** [psi4/psi4#487]
On the semi-manual `psi4conda` [instructions](http://psicode.org/psi4manual/master/conda.html#psi4conda-installer), for both Linux and Mac, the `curl` flag should be changed from `-o` to `-O`.

**Comment by loriab** [comment]
You're right, the place I usually copy it from has the proper `-O`, so I never noticed. Docs aren't being built nightly just now, so I'll leave this open for our docs bug fixing contest Friday. Thanks for the report.

**Comment by bwb314** [comment]
This problem has been fixed with PR #498.

**Comment by amjames** [comment]
Thanks @bwb314
