### ISSUE TITLE
How to debug Psi4?

### ISSUE THREAD

**Issue by bozkaya** [psi4/psi4#491]
When I try to debug psi4 on mac with "lldb psi4" I got the following messega:

lldb psi4
(lldb) target create "psi4"
error: '/Users/ugur/psi4/objdir/stage/Users/ugur/psi4install/psi4cmake/bin/psi4' doesn't contain any 'host' platform architectures: x86_64h, x86_64, i386

How we can debug the current psi4? @loriab @dgasmith @jturney

**Comment by dgasmith** [comment]
In the latest version you need to do:

`lldb python path_to/psi4 input.dat`

**Comment by bozkaya** [comment]
I tried it, but I got the following:

Ugurs-MacBook-Pro:psijob ugur$ lldb python /Users/ugur/psi4/objdir/stage/Users/ugur/psi4install/psi4cmake/bin/psi4 input.dat 
(lldb) target create "python"
Current executable set to 'python' (x86_64).
(lldb) settings set -- target.run-args  "/Users/ugur/psi4/objdir/stage/Users/ugur/psi4install/psi4cmake/bin/psi4" "input.dat"
(lldb) r
error: process exited with status -1 (cannot attach to process due to System Integrity Protection)
(lldb) 

However, I can debug my old psi4.   @dgasmith

**Comment by dgasmith** [comment]
@bozkaya What is the commit hash for the version of Psi4 that you have?

**Comment by amjames** [comment]
>error: process exited with status -1 (cannot attach to process due to System Integrity Protection)
(lldb)

Are you using the system python? I have SIP disabled but I would not be surprised if you can't attach the debugger to an executable that falls under that protection. 


To disable SIP you need to reboot into recovery mode, then reboot again for it to take effect.

**Comment by bozkaya** [comment]
Thanks for answers! After disabling SIP in the recovery mode, I can debug the code.
