### ISSUE TITLE
Auto-generation of plugin template failing?

### ISSUE THREAD

**Issue by lothian** [psi4/psi4#503]
[draco:~/src] crawdad% psi4 --new-plugin myplugin
Traceback (most recent call last):
  File "/Users/crawdad/psi4/bin/psi4", line 110, in <module>
    raise KeyError("The file %s does not exist." % args["input"])
KeyError: 'The file input.dat does not exist.'

This suggests the input.dat template doesn't exist, but it's in the install area.  I can't find where this is implemented in the new structure, however.  Perhaps it's not implemented?

**Comment by jturney** [comment]
That error triggers when psi is trying to run an input file. The plugin code isn't getting called. Can you confirm the correct psi is being called?

**Comment by lothian** [comment]
Yes, this is from my fork generated and built yesterday.  All old versions, including the old installations were removed.

TDC

**Comment by jturney** [comment]
Not sure what's going on. In your ```/Users/crawdad/psi4/bin/psi4``` do you have lines like https://github.com/psi4/psi4/blob/master/psi4/run_psi4.py#L142-L144 in there? The ```KeyError ``` that's being raised is handled in the lines following.  Could you also add a ```print(args)``` before the error and paste the results in (from your error message above the  KeyError is raised near line 110)?

**Comment by loriab** [comment]
One other thing to possibly check is envvars. `PSI4DATADIR` is completely defunct. `PSIDATADIR` exists but shouldn't need to be set except to override behavior. If the latter is set, it could confuse psi4.

**Comment by lothian** [comment]
Apparently I'd failed to run a "git merge upstream/master" after "git fetch upstream" when I created my local fork last week, so my most recent commit on master was by @dgasmith 18 days ago.  As a result, none of the work between the Big Inversion appeared in my new fork, including the new_plugin code section in run_psi4.py.  @jturney's question revealed the discrepancy.  Plugin templates work now.

Thanks, all!

-TDC
