### ISSUE TITLE
How to write a Molden file with natural orbitals and occupation numbers from a post-SCF calculation?

### ISSUE THREAD

**Issue by tovrstra** [psi4/psi4#504]
My best guess (with the latest development version 6833bd5645022b232b82e4ffc84496e5be143506) would be as follows, for a CCSD calculation:

    molecule test {
     N   -0.0074552142    0.0447633077    0.0549133281
     H    0.7912317854    0.0113343077    0.0235803281
     H   -0.3132442140   -0.8795806918    0.2831263280
     H   -0.3744022140    0.2462893076   -1.0696916713
    units angstrom
    }
    set {
        basis cc-pVDZ
        freeze_core True
        guess sad
    }
    e, wfn = energy('CCSD', return_wfn=True)
    molden(wfn, 'ccsd_no.molden', density_a=wfn.Da())

However, the file `ccsd_no.molden` does not give reasonable charges when loaded into Molden:

                            Mulliken Charges
                            ================
     
                   N  -0.0793
                   H  -0.4048
                   H  -0.2581
                   H  -0.5537
     
    Sum of Mulliken Charges:  -1.2959

(There were no such problems with Molden files from plain SCF calculations.)

The sum of the occupation numbers in the Molden file is 6.0465. Shouldn't that sum be 10 in this example? Furthermore, with a too-low sum of occupation numbers, I would expect a positive sum of Mulliken charges, so presumably, there is something else going wrong too.

I'm not sure if `wfn.Da()` is the right way to get the density matrix? That was just a guess.

**Comment by dgasmith** [comment]
`density_a` must be the MO density while all quantities on the Wavefunction itself are in the AO basis. I can see how this could be confusing and have edited several parts of the documentation.

In addition, most post-SCF methods do not build the density by default as this can be much more costly than the energy itself. Perhaps @amjames can give hints on extracting CC densities.

**Comment by tovrstra** [comment]
Good to know. I may already be able to work with a density matrix in the AO basis, albeit not via the Molden file. Are the internal PSI4 conventions for ordering of basis functions (and sign conventions) the same as that in the Molden file?

**Comment by dgasmith** [comment]
Unfortunately we do not match MOLDEN ordering. From a Psi to molden standpoint the following mapping is used:

``` C++
    // The order Molden expects
    //     P: x, y, z
    //    5D: D 0, D+1, D-1, D+2, D-2
    //    6D: xx, yy, zz, xy, xz, yz
    //
    //    7F: F 0, F+1, F-1, F+2, F-2, F+3, F-3
    //   10F: xxx, yyy, zzz, xyy, xxy, xxz, xzz, yzz, yyz, xyz
    //
    //    9G: G 0, G+1, G-1, G+2, G-2, G+3, G-3, G+4, G-4
    //   15G: xxxx yyyy zzzz xxxy xxxz yyyx yyyz zzzx zzzy,
    //        xxyy xxzz yyzz xxyz yyxz zzxy
    // Since Molden doesn't handle higher than g we'll just leave them be.
    int molden_cartesian_order[][15] = {
        { 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },    // p
        { 0, 3, 4, 1, 5, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0 },    // d
        { 0, 4, 5, 3, 9, 6, 1, 8, 7, 2, 0, 0, 0, 0, 0 },    // f
        { 0, 3, 4, 9, 12, 10, 5, 13, 14, 7, 1, 6, 11, 8, 2} // g
    };
```

**Comment by tovrstra** [comment]
Thank you for all the insights! With this info, I should be able to get it working (at least if the density matrix is available in some form.)

**Comment by amjames** [comment]
The `wfn.Da()` will not hold the ccsd density and in fact in this calculation it will not be computed. 

To get the density would require a property calculation, and then to request the natural orbitals be printed to file. 


```
 set { 
       uhf_noons all
       write_nos   true 
} 

property("ccsd", properties=['dipole'])
```

The `ccdensity` module does not update the wavefunction after it has computed the density. The `wfn.Da()` method will get you the AO/SO basis SCF density even after the coupled cluster density has been constructed. 

I hope this is helpful

**Comment by tovrstra** [comment]
Thanks. We'll experiment with that. Would the same approach work for other post-scf methods as well?

**Comment by dgasmith** [comment]
@amjames Could you modify `ccdensity` so that it writes the AO density to `ref_wfn`'s Da/Db?

@tovrstra Creation of the OPDM is not standardized across the different modules at the moment. Typically, setting `set opdm true` will build the OPDM; however, it is not always clear if `Da` is updated. If @amjames can update the Da/Db attributes for the `cc` modules we may be able guarantee that all Wavefunctions coming from a `property` call have a Da/Db that is associated with the called method. This should be guaranteed for all valid `property` modules besides `cc`.

**Comment by tovrstra** [comment]
That would already be awesome! We'll see how far we can get in the mean time. If anything interesting comes up, I'll post it here.

**Comment by amjames** [comment]
That should not be very hard to do. 

Do we want that overwritten by default or just when the `set opdm` flag is true?

**Comment by dgasmith** [comment]
I think anytime the unrelaxed density is built we should set it to the Da/Db accessors. It would be nice to compute the density based properties using OEProp at the python level as well. Example:

https://github.com/psi4/psi4/blob/master/psi4/driver/procedures/proc.py#L2476

Perhaps a bit ambitious for this pass, but it would be nice for consistency.

**Comment by amjames** [comment]
I completely agree. Right now CC properties go through OEProp, but from within the  module.  Moving that to python has been on my list for a while. 


Setting the `ref_wfn` Da/Db in ccdensity is complicated because the `Psi::ccdensity::onepdm()` function is not a member of any class that inherits from `wavefunction`.  


So, in order to do this there needs to be some hook opened up in the base class  (ie `set_postscf_Da`). 

A cleaner solution would be to re-organize the various cc* modules into one module with the ccwavefunction playing the role the "MOinfo" and "params" structs. Though, that would be a much larger project.

**Comment by dgasmith** [comment]
@amjames You can probably get around the constness of the `Da` attribute. Or easier, if slightly annoying, you can use the Wavefunction `set_array("OPDM", opdm_)` function which will set the Matrix which can then be accessed Python side through `get_array("OPDM")` and then use numpy functions to to set it back to Da.

```python
opdm = ...
ref_wfn = ..
for h in range(nirrep):
     ref_wfn.Da().nph[h][:] = opdm.nph[h][:]
```

**Comment by CDSherrill** [comment]
One of the comments in this chain referred to unrelaxed densities.  We should check with @lothian, but I think typically we want relaxed densities (where available) for the purposes of computing properties.... dipole moments, for example, should be more accurate when computed using relaxed densities.  (There's an old Bartlett paper that does this comparison for CCSD, as I recall).

On the other hand, I do not know that relaxed densities are the appropriate ones if we want to compute natural orbitals (which is more the context of the current discussion).  For example, I'm not sure if relaxed densities satisfy Tr(\gamma) = N.

Will we wind up needing to keep both relaxed and unrelaxed densities in wfn?

**Comment by dgasmith** [comment]
Thats a good point, I try to only store the unrelaxed density on the Wavefunction so that it is valid for other uses. We do have the `array` attribute on Wavefunctions to store extra densities now.

**Comment by tovrstra** [comment]
Small question: would it be possible to select relaxed or unrelaxed? My
only motivation for using natural orbitals is that these can be stored in a
Molden file. I would like to postprocess the 1RDM with our recent variant
of the iterative stockholder method. For that I need to get the be able to
read in the 1RDM in some form. Our code can read Molden files with
fractional occupations.

Ideally, there would be a standard file format for exchanging wavefunctions
between different codes, which can directly store the 1RDM, the basis set,
etc. I believe there is currently no such thing.

**Comment by CDSherrill** [comment]
In principle you should be able to get / print it from Python (maybe
unrelaxed only for right now)...what basis do you want it in?   We could
add a feature to deliver it as it's wanted, instead of having to use Molden
as a work around.

**Comment by tovrstra** [comment]
Eventually, I would need it in the AO basis. If it is possible to access all information (contractions, etc.) of the basis set and the matrix elements, I should be able to extract the required data, which would be great. I would already be happy to try this with the unrelaxed dm, to get things working, and then switch to the relaxed on, once it is available.

**Comment by tovrstra** [comment]
P.S. I would need it in the AO basis to compute densities and other properties on a grid.

**Comment by dgasmith** [comment]
Try out the following:

```python
molecule mol {
He
He 1 3.0
symmetry c1
}

scf_e, scf_wfn = energy('SCF/sto-3g', return_wfn=True)

scf_wfn.Da().print_out()
scf_wfn.basisset().print_detail_out()

# Accessors for Da
print scf_wfn.Da().get(0, 0)   # Python to C++ accessor
print scf_wfn.Da().np             # Numpy accessor
```

Using `C1` so that we get the AO basis set, SO->AO transformations are pretty simple as well. You can also run python-based help on a BasisSet object (`help(scf_wfn.basisset())`) to get a better idea of how to access it. The docs are pretty limited, but hopefully that function names are somewhat self explanatory.

**Comment by CDSherrill** [comment]
I can see how the Molden format is perhaps a good fit for this, as it
presents not only the desired quantity (AO basis density matrix) but also
the associated data required to interpret it (basis set ordering,
exponents, contractions).  Of course, even then, some assumptions/standards
have to be in place, like normalization conventions for the basis
functions, etc.  Indeed, we already had a discussion about normalization
conventions in https://github.com/psi4/psi4/issues/60 .  One would also in
principle have to assume some standard for how to define the pure angular
momentum functions from the Cartesian functions, etc.  Still, with some
choices made and documented to set a convention for all this (which is
presumably available), Molden format could be ok to pass along
self-contained one-electron properties between programs that might have
different conventions.

On the other hand, I think it remains useful to be able to get at
this/similar info without having to literally write out a Molden file.
Perhaps the example from @dgasmith will work or could be built upon.

**Comment by kannon92** [comment]
I would think that we should get away from using molden files for interfacing.  Molden does not support either g or h functions (can't remember which) and higher.  This is not a huge problem now, but it may be better to find an alternative way of passing information.

**Comment by CDSherrill** [comment]
Ooh, if there is no g or h support, then that's definitely not good.
Although a possibility would be a "Molden+" format that would be backwards
compatible with Molden for L<=2, and also capable of handling L>=3.

Yeah, I tend to agree that we also need a diskless way to pass this kind of
info between programs that might have different ordering/normalization
conventions.

**Comment by amjames** [comment]
It looks like this problem has been resolved, can we close this issue  @tovrstra ?

**Comment by susilehtola** [comment]
@kannon92 yes, I'd suggest formatted checkpoints, which is an OK format for passing around data, and which is supported by a number of different visualization programs.

**Comment by tovrstra** [comment]
Sorry that I did not have much time to look into this yet. (Teaching, exams, grrr.)

My original questions is probably solved but the rest of the discussion on container formats is not. (I'll try to test soon.)
I'm opening a new issue for the data format discussion (#562), so we can close this one soon(er).

**Comment by susilehtola** [comment]
The sum of Mulliken charges should not be positive or negative, it should be zero for a charge neutral system.
