### ISSUE TITLE
CMake Documentation Clarification 

### ISSUE THREAD

**Issue by amjames** [psi4/psi4#516]
The new CMake system documentation is primarily in the comments within the top level CMakeLists.txt. I have noticed an inconsistency that should either be fixed in the build system or removed from the documentation. 

 The comment section [here](https://github.com/psi4/psi4/blob/master/CMakeLists.txt#L47) seems to imply that you can download libefp/libint, build them, and then provide the directory containing the appropriate directory containing libintConfig.cmake/libefpConfig.cmake to CMake in the following way

```shell
cmake -H. -Bobjdir … -Dlibint_DIR=/path/to/libint/share/cmake/libint -Dlibefp_DIR=/path/to/libefp/share/cmake/libefp
```

Then cmake will detect the previously installed libint/libefp and skip their building. 

However, this does not completely work. The initial cmake will indicate `found libint`, then when you go to the build directory and run `make` the `libint_DIR `and `libefp_DIR` argurments are not passed on to cmake for psi4_core and the build errors out with the following message:

```shell
Performing configure step for 'psi4_core'
loading initial cache file /home/amjames2/newriver/psi4-builds/new-debug/psi4_core-prefix/tmp/psi4_core-cache.cmake
-- The C compiler identification is GNU 5.2.0
-- The CXX compiler identification is GNU 5.2.0
-- Check for working C compiler: /home/amjames2/.conda/envs/py3/bin/gcc
-- Check for working C compiler: /home/amjames2/.conda/envs/py3/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/amjames2/.conda/envs/py3/bin/g++
-- Check for working CXX compiler: /home/amjames2/.conda/envs/py3/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Checking for restrict keyword
--    keyword found : __restrict__
-- Found PythonInterp: /home/amjames2/.conda/envs/py3/bin/python (found version "3.5.2") 
-- Found PythonLibs: /home/amjames2/.conda/envs/py3/lib/libpython3.so
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found libdl: /usr/lib64/libdl.so  
CMake Error at CMakeLists.txt:35 (find_package):
  Could not find a package configuration file provided by "libefp" with any
  of the following names:

    libefpConfig.cmake
    libefp-config.cmake

  Add the installation prefix of "libefp" to CMAKE_PREFIX_PATH or set
  "libefp_DIR" to a directory containing one of the above files.  If "libefp"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```

It seems that if I add two lines to the `CMAKE_ARGS` section of `ExternalProject_Add(psi4_core…` 

```
-Dlibint_DIR=${libint_DIR}
-Dlibefp_DIR=${libefp_DIR}
```

Then the arguments that I pass on the command line are correctly fed into the psi4_core build. Currently they are not passed in but the step that would download/build them was skipped since they were detected in the initial CMake pass.

The `CMAKE_PREFIX_PATH` option for detecting them works since that argument is currently passed through. The documentation should be edited to remove the suggestion that `-Dlibint_DIR` type options be used, or the source should be edited so that those arguments are passed through to the psi4_core build.

**Comment by loriab** [comment]
Good catch, @amjames . Yes, that was just negligence that the `AddON_DIR` weren't passed through to psi4_core. The whole lot just need to be added to the external project.

**Comment by loriab** [comment]
In case you're tempted to investigate, `CMAKE_DISABLE_FIND_PACKAGE_<PackageName>` suffers the same problem, but its fix is more complicated. Coming soon to a PR.
