### ISSUE TITLE
EOM-CCSD strange result

### ISSUE THREAD

**Issue by lucamontana** [psi4/psi4#521]
Dear Developers, 

I try to calculate excited states of H2 molecule using this input file : 

molecule H2 {   
H    -0.3836975    0.0000000    0.0000000 
H     0.3836975    0.0000000    0.0000000
   units ang
}

set basis     aug-cc-pvqz 
set scf_type  df
#set guess     sad
set reference rhf
set e_convergence   1e-06
set d_convergence   1e-06
set ints_tolerance  1e-08

set freeze_core     true
set roots_per_irrep [4,4,4,4,4,4,4,4]
set maxiter 100000

property('eom-ccsd', properties=['oscillator_strength'])
---------------------------------------------------------------------------------------------
However, for some of excited states i obtain 0 eV !

                   Excitation Energy          OS       RS        RS     Einstein A
	State   (eV)    (cm^-1)    (nm)     (au)              (l,au)   (v,au)     (s^-1)
	 1 Ag  12.964  104563.7    95.6   0.476427   0.0000   0.0000   0.0000  0.000000E+00
	 2 Ag  16.771  135268.5    73.9   0.616329   0.0000   0.0000   0.0000  0.000000E+00
	 3 Ag  18.773  151418.0    66.0   0.689911   0.0000   0.0000   0.0000  0.000000E+00
	 4 Ag  25.910  208979.2    47.9   0.952179   0.0000   0.0000   0.0000  0.000000E+00
	 1B1g  16.855  135946.4    73.6   0.619417   0.0000   0.0000   0.0000  0.000000E+00
	 2B1g  19.351  156077.5    64.1   0.711142   0.0000   0.0000   0.0000  0.000000E+00
	 3B1g  19.458  156942.8    63.7   0.715084   0.0000   0.0000   0.0000  0.000000E+00
	 4B1g  19.513  157382.5    63.5   0.717087   0.0000   0.0000   0.0000  0.000000E+00
	 1B2g   0.000       0.0 287864613790050.6   0.000000   0.0000   0.0000   0.0000  0.000000E+00
	 2B2g   0.000       0.0 168701352313695.2   0.000000   0.0000   0.0000   0.0000  0.000000E+00
	 3B2g   0.000       0.0 111616374313896.7   0.000000   0.0000   0.0000   0.0000  0.000000E+00
	 4B2g   0.000       0.0 95015600179548.7   0.000000   0.0000   0.0000   0.0000  0.000000E+00
	 1B3g   0.000       0.0 276652168953733.3   0.000000   0.0000   0.0000   0.0000  0.000000E+00
	 2B3g   0.000       0.0 202756770901990.0   0.000000   0.0000   0.0000   0.0000  0.000000E+00
	 3B3g   0.000       0.0 135821991365655.0   0.000000   0.0000   0.0000   0.0000  0.000000E+00
	 4B3g   0.000       0.0 114346140595797.4   0.000000   0.0000   0.0000   0.0000  0.000000E+00

	 1 Au   0.000       0.0 300704927659592.6   0.000000   0.0000   0.0000   0.0000  0.000000E+00
	 2 Au   0.000       0.0 215093070250438.8   0.000000   0.0000   0.0000   0.0000  0.000000E+00
	 3 Au   0.000       0.0 195838985674113.8   0.000000   0.0000   0.0000   0.0000  0.000000E+00
	 4 Au   0.000       0.0 109642937905942.0   0.000000   0.0000   0.0000   0.0000  0.000000E+00
	 1B1u  13.809  111376.5    89.8   0.507469   0.3270   0.0000   0.0000  2.705529E+09
	 2B1u  26.345  212487.0    47.1   0.968162   0.2787   0.0000   0.0000  8.394456E+09
	 3B1u  28.418  229205.9    43.6   1.044339   0.0041   0.0000   0.0000  1.426285E+08
	 4B1u  34.059  274702.3    36.4   1.251636   0.0003   0.0000   0.0000  1.669922E+07
	 1B2u  13.809  111376.5    89.8   0.507469   0.3270   0.0000   0.0000  2.705529E+09
	 2B2u  26.345  212487.0    47.1   0.968162   0.2787   0.0000   0.0000  8.394456E+09
	 3B2u  28.418  229205.9    43.6   1.044339   0.0041   0.0000   0.0000  1.426285E+08
	 4B2u  34.059  274702.3    36.4   1.251636   0.0003   0.0000   0.0000  1.669921E+07
	 1B3u  12.527  101040.9    99.0   0.460376   0.3113   0.0000   0.0000  2.120182E+09
	 2B3u  15.263  123102.4    81.2   0.560896   0.1514   0.0000   0.0000  1.530286E+09
	 3B3u  20.039  161623.3    61.9   0.736410   0.1214   0.0000   0.0000  2.114694E+09
	 4B3u  25.716  207413.7    48.2   0.945046   0.0341   0.0000   0.0000  9.772281E+08

Bests 
LUCA

**Comment by amjames** [comment]
What version of psi4 that you are using? The version info should be printed in the heading of the output file. 

I ran your input using a build from the current master and I got the following results:

```
                   Excitation Energy          OS       RS        RS     Einstein A                                                                                                 
State   (eV)    (cm^-1)    (nm)     (au)              (l,au)   (v,au)     (s^-1)
 1 Ag  12.964  104563.5    95.6   0.476427   0.0000   0.0000   0.0000  0.000000E+00
 2 Ag  16.771  135268.1    73.9   0.616327   0.0000   0.0000   0.0000  0.000000E+00
 3 Ag  18.773  151417.7    66.0   0.689910   0.0000   0.0000   0.0000  0.000000E+00
 4 Ag  25.910  208978.9    47.9   0.952178   0.0000   0.0000   0.0000  0.000000E+00
 1B1g  16.855  135946.1    73.6   0.619416   0.0000   0.0000   0.0000  0.000000E+00
 2B1g  26.177  211129.5    47.4   0.961977   0.0000   0.0000   0.0000  0.000000E+00
 3B1g  30.589  246713.1    40.5   1.124108   0.0000   0.0000   0.0000  0.000000E+00
 4B1g  36.015  290484.5    34.4   1.323545   0.0000   0.0000   0.0000  0.000000E+00
 1B2g  16.855  135946.1    73.6   0.619416   0.0000   0.0000   0.0000  0.000000E+00
 2B2g  26.177  211129.5    47.4   0.961977   0.0000   0.0000   0.0000  0.000000E+00
 3B2g  30.589  246713.1    40.5   1.124108   0.0000   0.0000   0.0000  0.000000E+00
 4B2g  36.015  290484.5    34.4   1.323545   0.0000   0.0000   0.0000  0.000000E+00
 1B3g  19.495  157235.3    63.6   0.716417   0.0000   0.0000   0.0000  0.000000E+00
 2B3g  19.585  157966.1    63.3   0.719747   0.0000   0.0000   0.0000  0.000000E+00
 3B3g  19.612  158178.3    63.2   0.720713   0.0000   0.0000   0.0000  0.000000E+00
 4B3g  19.626  158297.8    63.2   0.721258   0.0000   0.0000   0.0000  0.000000E+00
 1 Au  28.127  226859.8    44.1   1.033649   0.0000   0.0000   0.0000  0.000000E+00
 2 Au  38.607  311383.0    32.1   1.418765   0.0000   0.0000   0.0000  0.000000E+00
 3 Au  40.680  328106.5    30.5   1.494963   0.0000   0.0000   0.0000  0.000000E+00
 4 Au  46.518  375194.6    26.7   1.709513   0.0000   0.0000   0.0000  0.000000E+00
 1B1u  13.809  111376.2    89.8   0.507467   0.3270   0.0000   0.0000  2.705606E+09
 2B1u  26.345  212486.8    47.1   0.968161   0.2787   0.0000   0.0000  8.394111E+09
 3B1u  28.418  229205.6    43.6   1.044338   0.0041   0.0000   0.0000  1.426430E+08
 4B1u  34.059  274701.9    36.4   1.251634   0.0003   0.0000   0.0000  1.670003E+07
 1B2u  13.809  111376.2    89.8   0.507467   0.3270   0.0000   0.0000  2.705606E+09
 2B2u  26.345  212486.8    47.1   0.968161   0.2787   0.0000   0.0000  8.394111E+09
 3B2u  28.418  229205.6    43.6   1.044338   0.0041   0.0000   0.0000  1.426430E+08
 4B2u  34.059  274701.9    36.4   1.251634   0.0003   0.0000   0.0000  1.670003E+07
 1B3u  12.527  101040.6    99.0   0.460375   0.3114   0.0000   0.0000  2.120269E+09
 2B3u  15.263  123102.2    81.2   0.560895   0.1514   0.0000   0.0000  1.530130E+09
 3B3u  20.039  161623.1    61.9   0.736409   0.1214   0.0000   0.0000  2.114615E+09
 4B3u  25.716  207413.4    48.2   0.945045   0.0341   0.0000   0.0000  9.774464E+08
```

I do notice some nonsense is being printed in the `Excited State -> Excited State Transitions` section. Looks similar to what you have above:

```
1B1g->1B2g   0.000       0.0 86055398391528.6   0.000000   0.0000   0.0000   0.0000  0.000000E+00
```

We should probably put something in to detect degeneracy and print something that indicates that or at least gracefully handle the conversion to nm.

**Comment by lucamontana** [comment]
I was using psi4.0 version.

However i just compiled the newest verson of psi4 from github and obtain now just for one symmetry non-sense :   

	                   Excitation Energy          OS       RS        RS     Einstein A
	State   (eV)    (cm^-1)    (nm)     (au)              (l,au)   (v,au)     (s^-1)
	 1 Ag  12.964  104563.5    95.6   0.476427   0.0000   0.0000   0.0000  0.000000E+00
	 2 Ag  16.771  135268.1    73.9   0.616327   0.0000   0.0000   0.0000  0.000000E+00
	 3 Ag  18.773  151417.7    66.0   0.689910   0.0000   0.0000   0.0000  0.000000E+00
	 4 Ag  25.910  208978.9    47.9   0.952178   0.0000   0.0000   0.0000  0.000000E+00
	 1B1g  16.855  135946.1    73.6   0.619416   0.0000   0.0000   0.0000  0.000000E+00
	 2B1g  26.177  211129.5    47.4   0.961977   0.0000   0.0000   0.0000  0.000000E+00
	 3B1g  30.589  246713.1    40.5   1.124108   0.0000   0.0000   0.0000  0.000000E+00
	 4B1g  36.015  290484.5    34.4   1.323545   0.0000   0.0000   0.0000  0.000000E+00
	 1B2g  16.855  135946.1    73.6   0.619416   0.0000   0.0000   0.0000  0.000000E+00
	 2B2g  26.177  211129.5    47.4   0.961977   0.0000   0.0000   0.0000  0.000000E+00
	 3B2g  30.589  246713.1    40.5   1.124108   0.0000   0.0000   0.0000  0.000000E+00
	 4B2g  36.015  290484.5    34.4   1.323545   0.0000   0.0000   0.0000  0.000000E+00
	 1B3g   0.000       0.0 30667796364.5   0.000000   0.0000   0.0000   0.0000  0.000000E+00
	 2B3g   0.000       0.0 20136140996.1   0.000000   0.0000   0.0000   0.0000  0.000000E+00
	 3B3g   0.000       0.0 18363592897.3   0.000000   0.0000   0.0000   0.0000  0.000000E+00
	 4B3g   0.000       0.0 9232632432.8   0.000000   0.0000   0.0000   0.0000  0.000000E+00
	 1 Au  28.127  226859.8    44.1   1.033649   0.0000   0.0000   0.0000  0.000000E+00
	 2 Au  38.607  311383.0    32.1   1.418765   0.0000   0.0000   0.0000  0.000000E+00
	 3 Au  40.680  328106.5    30.5   1.494963   0.0000   0.0000   0.0000  0.000000E+00
	 4 Au  46.518  375194.6    26.7   1.709513   0.0000   0.0000   0.0000  0.000000E+00
	 1B1u  13.809  111376.2    89.8   0.507467   0.3270   0.0000   0.0000  2.705606E+09
	 2B1u  26.345  212486.8    47.1   0.968161   0.2787   0.0000   0.0000  8.394111E+09
	 3B1u  28.418  229205.6    43.6   1.044338   0.0041   0.0000   0.0000  1.426430E+08
	 4B1u  34.059  274701.9    36.4   1.251634   0.0003   0.0000   0.0000  1.670004E+07
	 1B2u  13.809  111376.2    89.8   0.507467   0.3270   0.0000   0.0000  2.705606E+09
	 2B2u  26.345  212486.8    47.1   0.968161   0.2787   0.0000   0.0000  8.394111E+09
	 3B2u  28.418  229205.6    43.6   1.044338   0.0041   0.0000   0.0000  1.426430E+08
	 4B2u  34.059  274701.9    36.4   1.251634   0.0003   0.0000   0.0000  1.670004E+07
	 1B3u  12.527  101040.6    99.0   0.460375   0.3114   0.0000   0.0000  2.120269E+09
	 2B3u  15.263  123102.2    81.2   0.560895   0.1514   0.0000   0.0000  1.530130E+09
	 3B3u  20.039  161623.1    61.9   0.736409   0.1214   0.0000   0.0000  2.114615E+09
	 4B3u  25.716  207413.4    48.2   0.945045   0.0341   0.0000   0.0000  9.774464E+08

**Comment by dgasmith** [comment]
Can confirm Psi41.1 conda builds on Mac and linux provide the correct result as well as the current master. This likely relates to a BLAS/LAPACK issue as these extremely symmetric molecule can be difficult to diagonalize both in HF and in the DL EOM iterations. As such, I'm not entirely sure there is much we can do about this particular issue.

**Comment by lucamontana** [comment]
Ok, Thanks. 
However there is no such issue in NWCHEM package, for instance.

LUCA

**Comment by fevangelista** [comment]
Can you post the output file or at least the section with the EOM-CCSD iterations for the B2g irrep?

**Comment by dgasmith** [comment]
Closing this out unless we can get an output file. Please feel free to reopen.
