### ISSUE TITLE
EOM-CCSD  error

### ISSUE THREAD

**Issue by lucamontana** [psi4/psi4#523]
Dear all, 

when using eom-ccsd module, i get the following error :  

-----------------------------------------------------------------------------------------------
Seeking states with multiplicity of 1
Obtaining initial guess from singles-singles block of Hbar...Done.

Iter=1    L=8   Out-of-core algorithm not yet coded for NN or TT DGEMM.
Error in: contract444
-----------------------------------------------------------------------------------------------

however, when i increase the number of frozen virtual orbitals, the error disappears !

here the input for which i get the error :  

molecule pentamer {   
 O                    -2.611    -0.00565   0.45789 
 O                    -1.30452   2.25724  -0.45568 
 O                    -2.611     4.51335   0.45789 
 O                     1.30257   2.25385   0.45789 
 O                    -1.301     2.2647   -3.22291 
 H                    -2.63261  -0.00107   1.44733 
 H                    -2.63261   4.51793   1.44733 
 H                     1.28096   2.25843   1.44733 
 H                    -1.31578   2.28044  -2.23347 
 H                    -1.7735    3.07887  -3.52876 
 H                     0.36131   2.25462   0.1513 
 H                    -3.55226  -0.00488   0.1513 
 H                    -3.55226   4.51412   0.1513 
 H                    -1.78841   3.05064  -0.11356 
 H                    -1.78963   1.46139  -0.12277
   units ang
SYMMETRY C1
}

set basis     aug-cc-pvdz  
set scf_type  df
set guess     sad
set reference rhf
set e_convergence   1e-05
set d_convergence   1e-05
set ints_tolerance  1e-08

set FROZEN_DOCC [10]
set frozen_uocc [15]

#set freeze_core     true
set roots_per_irrep [8]
set maxiter 100000
property('eom-ccsd', properties=['oscillator_strength'])

**Comment by andysim** [comment]
The code is probably attempting to use an out-of-core algorithm for one of the contractions, because it thinks it only has the default of 500 Mb; increasing the number of frozen virtuals probably allows it to run in core, which is why that trick is successful.  If you add `memory 10 Gb` (or however much you have available) to the top of your input, it should help.

**Comment by lucamontana** [comment]
Many thanks. 
It helped very much.
Bests

**Comment by lucamontana** [comment]
one further question : 

i like to calculate the eom-ccsd triplet states starting from the Hartree-Fock singlet ground state.
However i do not manage to set up an input file for such calculation.

with multiplicity 3, PSI4 starts from a triplet ground state that i do not want.
Any idea how to start from the HF singlet state but calculate triplet excited state energies in eom-CCSD?

**Comment by lothian** [comment]
We have not coded explicitly the spin-adapted triplet states arising from
the EOM-CC equations starting from a singlet ground state.  However, you
might be able to obtain the desired states by changing your reference to
UHF and still selecting a multiplicity of 1.  The Hartree-Fock reference
should still be the same singlet state as you get from the corresponding
RHF calculation, and the EOM-CC *should* yield both singlets and triplets.
You'll be able to sort out which is which (and make sure that everything is
running correctly) by comparing the results to the corresponding RHF-EOM-CC
calculation.

-TDC

--
Prof. T. Daniel Crawford
crawdad@vt.edu

**Comment by amjames** [comment]
It looks like this problem has been resolved, can we close this issue  @lucamontana ?

**Comment by lucamontana** [comment]
yes, of course.

**Comment by amjames** [comment]
Thanks! Closing.
