### ISSUE TITLE
cbs() wrong print out in final CBS results

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#528]
For Psi4 1.0.54 [Git: Rev {master} 8d4cec3 dirty]
Hi,

When executing `energy(cbs,...)` and `delta_basis` equals a `corl_basis`, then the final MP2/CBS value is clearly wrong, and as a result the CBS value as well. Either E(CBS) will be too large or too small.
A typical output:

```
  ---------------------------------------------------------------------------------------------------------
        scf                   hf / jun-cc-pvqz                       -152.13112737   xtpl_highest_1
       corl                  mp2 / jun-cc-pv[tq]z                     110.40871391   corl_xtpl_helgaker_2
      delta    fno-ccsd(t) - mp2 / jun-cc-pvtz                         -0.02698189   xtpl_highest_1
      total                  CBS                                      -41.74939535   
  -----------------------------------------------------------------------------------
```

The previous values ("Stages", "Components") all look ok at a glance.

```
Eg:
molecule test {
0 1
O  -1.551007  -0.114520   0.000000
H  -1.934259   0.762503   0.000000
H  -0.599677   0.040712   0.000000
O  -1.551007  -0.114520   8.000000
H  -1.934259   0.762503   8.000000
H  -0.599677   0.040712   8.000000
}

memory 55 GB

set global {
cc_type df
INTS_TOLERANCE 1e-11
freeze_core true
}

# ok
#energy(cbs,scf_basis='jun-cc-pVQZ',corl_wfn='mp2', corl_basis='jun-cc-pv[tq]z',corl_scheme=corl_xtpl_helgaker_2,delta_wfn='fno-ccsd(t)',delta_basis='jun-cc-pVDZ')

# print error
energy(cbs,scf_basis='jun-cc-pVQZ',corl_wfn='mp2',corl_basis='jun-cc-pv[tq]z',corl_scheme=corl_xtpl_helgaker_2,delta_wfn='fno-ccsd(t)',delta_basis='jun-cc-pVTZ')

# error2, although this calc makes less sense...
#energy(cbs,scf_basis='aug-cc-pVQZ',corl_wfn='mp2',corl_basis='jun-cc-pv[tq]z',corl_scheme=corl_xtpl_helgaker_2,delta_wfn='fno-ccsd(t)',delta_basis='jun-cc-pVQZ')

```

**Comment by loriab** [comment]
For the "print error" line, I get the below on a recent version.

```
  ---------------------------------------------------------------------------------------------------------
      Stage               Method / Basis                               Energy [Eh]   Scheme
  ---------------------------------------------------------------------------------------------------------
        scf                   hf / jun-cc-pvqz                       -152.13112737   xtpl_highest_1
       corl                  mp2 / jun-cc-pv[tq]z                      -0.59785921   corl_xtpl_helgaker_2
      delta    fno-ccsd(t) - mp2 / jun-cc-pvtz                         -0.02698189   xtpl_highest_1
      total                  CBS                                     -152.75596848   
  ---------------------------------------------------------------------------------------------------------
```

The above looks ok to me, so I suspect you've hit #455 . You can easily patch your installation by doing https://github.com/psi4/psi4/commit/2e6b373102294cd59faf47d68044ff2402376e73 , no recompile required.

Let me know if you think yours is a different issue.

**Comment by hokru** [comment]
Thanks! That fixes it.
I wasn't aware the conda binary is so far behind the git version.

**Comment by loriab** [comment]
Glad to hear it’s fixed. Yes, 1.0.54 is a few hundred commits ago. Currently we’re building up to a 1.1 release, but unless you need pcmsolver, ambit, or advanced plugin technology, the current development head should be perfectly useable. There is a later conda binary, but we’re keeping development snapshots under a different label, so that only releases are pulled with “conda update psi4 -c psi4”. You can get the development snapshots via “conda update psi4 -c psi4 -c psi4/label/test”. That will pull packages additionally from the “test” (name may change) label. The 1.0.54 to pre-1.1 changes are sufficiently drastic that you should probably do a fresh conda install of psi4, rather than just a conda update.
