### ISSUE TITLE
Psi4 fails on Fedora 25

### ISSUE THREAD

**Issue by LonelySpooky** [psi4/psi4#531]
A simple input fails to run:
```
# Any line starting with the # character is a comment line
#! Sample HF/cc-pVDZ H2O computation

memory 250 mb

molecule h2o {
  O 
  H 1 0.96
  H 1 0.96 2 104.5
}

set basis cc-pVDZ
energy('scf')
```
a
And here is the error message:

```
[henrique@localhost ~] $ psi4 teste.dat 
An error has occurred python-side. Traceback (most recent call last):

  File "<string>", line 7, in <module>

  File "/usr/share/psi4/python/driver.py", line 45, in <module>
    import driver_util

  File "/usr/share/psi4/python/driver_util.py", line 30, in <module>
    from procedures import *

  File "/usr/share/psi4/python/procedures/__init__.py", line 1, in <module>
    from proc_table import procedures, hooks, energy_only_methods

  File "/usr/share/psi4/python/procedures/proc_table.py", line 198, in <module>
    for ssuper in proc.superfunctional_list():

  File "/usr/share/psi4/python/procedures/functional.py", line 3605, in superfunctional_list
    sup = superfunctionals[key](key, 1, 1)

  File "/usr/share/psi4/python/procedures/functional.py", line 1953, in build_b3lypd1_superfunctional
    sup = build_b3lyp_superfunctional(name, npoints, deriv)

  File "/usr/share/psi4/python/procedures/functional.py", line 1224, in build_b3lyp_superfunctional
    sup = psi4.SuperFunctional.blank()

TypeError: No to_python (by-value) converter found for C++ type: boost::shared_ptr<psi::SuperFunctional>

```

**Comment by loriab** [comment]
That looks faintly familiar, but I've been happily forgetting all my Boost knowledge these past couple months. There was a Boost 1.60 problem #243, though that doesn't particularly match up. But if Fedora 24 & 25 link to shared Boost libs, and Boost incremented, that's maybe a clue.

@susilehtola, yes, thanks for waiting on 1.1.

**Comment by LonelySpooky** [comment]
> For future reference: since this is a bug in the Psi4 Fedora package, you should file the bug in the Fedora bug tracker.

Yeah, @susilehtola,  I'm opening the bug here and in Fedora too, of course.
@loriab if I remember correctly, Boost is a dependency in Fedora ('s psi4), so it may be the case..

**Comment by LonelySpooky** [comment]
@susilehtola This is good to know. I'll be looking forward.
Thank you.

**Comment by loriab** [comment]
Closing this as there's nothing to be done on Psi4's side, and this will resolve naturally when Fedora package updated.
