### ISSUE TITLE
Case where df-hf fails in sapt

### ISSUE THREAD

**Issue by CDSherrill** [psi4/psi4#54]
From Daniel Schofield, 2/7/14: "I have been attempting to run SAPT calculations in PSI4, but am having little success due to my inability to converge the df-hf step for one of my monomers (H2).  I think this is due to a combination of using density fitting and the size of the ghosted basis set relative to this monomer i.e. if I run in a monomer centered basis set the calculation converges and if I run direct SCF (outside of SAPT) the calculation converges."

I have the test input/output files.  Apparently the DF-HF is going non-variational on the dimer computation.

**Comment by dgasmith** [comment]
Can we get an input file where this fails?

I dont think we have seen this in quite some time, there was an issue where the molecules would be re-centered so that the DF integrals and one-electron integrals didnt have the same center which caused some issues. This was fixed however.

**Comment by dgasmith** [comment]
Closing this out, if someone has an input where this fails please post a new issue with the reproducible error.
