### ISSUE TITLE
CISD fails on water C1 sto-3g

### ISSUE THREAD

**Issue by fevangelista** [psi4/psi4#546]
The following input runs a CISD computation and crashes with the current version of psi4 (fe3ab0d).

```
molecule {
O
H 1 R
H 1 R 2 A

R = .9
A = 104.5
symmetry c1
}

set basis sto-3g
energy('cisd')
```

Here is the console output:

```
Traceback (most recent call last):
  File "/Users/francesco/Source/psi4-fork-bin-Debug/bin/psi4", line 210, in <module>
    exec(content)
  File "<string>", line 30, in <module>
  File "/Users/francesco/Source/psi4-fork-bin-Debug/bin/../lib//psi4/driver/driver.py", line 447, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/Users/francesco/Source/psi4-fork-bin-Debug/bin/../lib//psi4/driver/procedures/proc.py", line 946, in select_cisd
    return func(name, **kwargs)
  File "/Users/francesco/Source/psi4-fork-bin-Debug/bin/../lib//psi4/driver/procedures/proc.py", line 3949, in run_cepa
    fnocc_wfn = core.fnocc(ref_wfn)

RuntimeError: 
Fatal Error: ndocc must be less than nvirt
Error occurred in file: /Users/francesco/Source/psi4-fork/psi4/src/psi4/fnocc/ccsd.cc on line: 142
The most recent 5 function calls were:
```

**Comment by loriab** [comment]
It gives the diagnosis semi-gracefully, `Fatal Error: ndocc must be less than nvirt`. If you're wanting to run detci, add `set qc_module detci`. What behaviour are you looking for?

**Comment by fevangelista** [comment]
Thanks for the hint on the module to use.  I was thinking that this might be one of those classic computations that an inexperienced user might want to run.  Perhaps python should pick this up and switch to detci when ndocc < nvirt?

**Comment by loriab** [comment]
That's going to be logic on values not readily accessible at "select-function" time when scf is not yet run. If someone was running a slew of molecules with cisd/sto-3g and wanted a single serial calc of them all to continue, then I can see the benefit, but sto-3g is so tentative a calc that I'm inclined to think the existing error msg suffices. Glad to do it if the consensus is it's wanted.

**Comment by fevangelista** [comment]
Good point.  This is such a minor issue that it might not be worth fixing now, but if someone at some point in the future had a fix for the ndocc < nvirt limitation it would make psi4 better.

**Comment by CDSherrill** [comment]
Hm, this seems like a strange restriction.  I agree with Francesco, would
be nice to remove it if possible.  But, low priority as CISD computations
would not be typical uses of Psi4, except possibly in an educational
context.
