### ISSUE TITLE
Goal: Make Psi4 work under MPI (again)

### ISSUE THREAD

**Issue by ryanmrichard** [psi4/psi4#548]
This issue is intended more as a discussion, than a real issue.

At the moment it is not possible to call Psi4 under MPI with more than one process per node because of [this](https://github.com/psi4/psi4/blob/fe3ab0d351e05276185ad838f3bcf2c0321be2fe/psi4/driver/procedures/proc.py#L1340)

Basically this creates a file that has a non-unique name on each process and then when it goes to delete the file each process deletes the same file leading to an error for every process after the first one.  Although this could be fixed easily (either only write to some master process or ensure that the filename is unique.  The latter is easily done [in python](http://stackoverflow.com/questions/2961509/python-how-to-create-a-unique-file-name) and [in C++](http://en.cppreference.com/w/cpp/io/c/tmpnam), or by using the process ID) this has been a problem before and is likely to be a problem again, hence I am hoping to reach a more permanent solution.

To me the most obvious solution is to make a file writer (stream writer is even better as it then also works for printing, in turn killing two birds with one stone) object/library that handles all read/writes and does so in a way that will not interfere with MPI.  In theory `libpsio` could be used for this, but it would have to be extended to writing other types of files aside from binary (I'm under the impression that it only writes binary files).

Thoughts?

**Comment by dgasmith** [comment]
I think its this way so that people can use the `READ` keyword for failed jobs without a PID. We do have a PID restart mechanism; however, its not tested or used AFAIK. 

There are quite a few read/writes coming from Python libraries these days so a pure Psi4 C++ module would not work. You could have a unified namespace that includes the PID. This is what `core.get_writer_file_prefix(scf_molecule.name())` tries to do; however, without a PID.

**Comment by loriab** [comment]
We'll also need to consider [interface codes](https://github.com/psi4/psi4/blob/master/psi4/driver/qcdb/interface_dftd3.py#L152-L157) that do file writing, too. Is it wanted to keep only mpi process == 1 writing the files or to keep the filenames unique so it doesn't matter if N mpi processes are writing the files? Or either, depending on the situation?

**Comment by ryanmrichard** [comment]
@dgasmith 
- I don't understand what difference the PID makes in terms of a read command
     ~~~~.py
    set{
    READ "some_file_with_no_PID.input"
    READ "some_file_generated_from_process.1234"
    }
    #later...
    file2open=options.get_str("READ")
    f=open(file2open,'r')
    ~~~~
- I think the key point is that any solution has to be accessible both in C++ and in Python thus wrapped one way or the other in Pybind11.  I personally think the common API for streams in C++ makes it easier, but it makes no difference if it's written in Python just as long as all calls go through it.  
- If the Python libraries you speak of are outside of Psi4 then in an ideal world they would allow you to specify the file they are going to write to.  If they don't provide such services, Psi4 needs to intervene or ensure that the library isn't called under MPI.  If these libraries aren't providing core features then it is unlikely that they will interfere with MPI operation and they can be ignored.
- I'm currently running the test suite to ensure my changes to `get_writer_file_prefix` didn't break anything.  It now appends the PID to the string it was going to return anyways.  Once it passes I'll make a new PR for that change and submit it.

@loriab ensuring only one MPI process writes is probably a loosing battle unless you rework the infrastructure to be more like Pulsar.  People likely bypass you.  It think the best bet is to keep the files unique and to do it with a function like `get_writer_file_prefix` or a similar class/library.  For the situation you highlighted I think `get_writer_file_prefix` will suffice.

I think `get_writer_file_prefix` will work in practice as long as everyone uses it.  Moving towards HPC applications I think files really should only be used for long term storage or when something doesn't fit in RAM, not for interfacing.

**Comment by dgasmith** [comment]
The command is `set guess READ`, so nothing is passed in. You would need to change the command to accept a file line. Also, be careful as I believe other areas manually append the PID, you will have to check those as well.

You might want to check with others before changing this functionality. The trivial quick fix is to simply name your molecules something unique.

**Comment by ryanmrichard** [comment]
Shows how often I restart guesses...

Yeah, I would motion we change it to something like

~~~.py
set guess "path/to/file/with/guess"
~~~

as long as the name of the file isn't literally "core", "sad", or "gwh" that shouldn't pose an issue.

**Comment by dgasmith** [comment]
I like it, we may need to pair this with a `guess write`?

**Comment by ryanmrichard** [comment]
@dgasmith that is one possibility; however, I am inclined to believe that the usual mechanism for saving the scratch files (and/or the MO file that started this issue), would be sufficient without having to introduce additional keywords.

**Comment by ryanmrichard** [comment]
So my testing indicates that appending the PID to the name breaks full-CI (presumably in the TDM code as fci-TDM and fci-TDM-2 are failing) as well as the SAPT code (sapt2 is failing).  Any insight from those familiar with those codes would be greatly appreciated.

**Comment by dgasmith** [comment]
I think this issue can be closed?
