### ISSUE TITLE
Psi4 Run Time Error

### ISSUE THREAD

**Issue by bozkaya** [psi4/psi4#552]
I have compiled psi4 on Linux (Centos) then I got the following run time error 

"Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so."

I have already sourced MKL and intel compilers as usual, with the following lines

"source /opt/intel/parallel_studio_xe_2016.3.067/compilers_and_libraries_2016/linux/bin/compilervars.sh intel64
source /opt/intel/parallel_studio_xe_2016.3.067/compilers_and_libraries_2016/linux/mkl/bin/mklvars.sh intel64"

In old versions of psi4 I never encounter such a problem with the same intel package.

Thanks,

@loriab @dgasmith

**Comment by ashutoshvt** [comment]
A simple hack around this problem is to preload libkml_rt.so. If you are
using bash,
export LD_PRELOAD = libmkl_rt.so  should fix it. The problem comes due to
conflict between
the mkl routines with which psi4 was installed with the numpy's mkl
routines.

**Comment by bozkaya** [comment]
Thank you very much. Now it works! @ashutoshvt
