### ISSUE TITLE
Failure on compiling plugins

### ISSUE THREAD

**Issue by kannon92** [psi4/psi4#565]
Hello PSI4 Developers,

I am able to compile PSI4, but the compilation fails when it tries to build a plugin.  

Here is the error output:

    ==> Created plugin files (in skeleton as basic): 
    CMakeLists.txt, input.dat, pymodule.py, __init__.py, plugin.cc, doc.rst
    loading initial cache file     /home/kannon/src/psi4_cmake/Build_Debug/stage/home/kannon/src/psi4_cmake/Install_Debug/shar e/cmake/psi4/psi4PluginCache.cmake
     -- The CXX compiler identification is unknown
    CMake Error at CMakeLists.txt:38 (project):
    The CMAKE_CXX_COMPILER:

    @CXX@

     is not a full path and was not found in the PATH.

     Tell CMake where to find the compiler by setting either the environment
     variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
     to the compiler, or to the compiler name if it is in the PATH.

     -- Configuring incomplete, errors occurred!

The compilers are correctly identified when cmake is first called.  Do you all have any ideas how to fix this?

**Comment by dgasmith** [comment]
Please supply the git hash of your Psi4 version, plugins have changed a lot lately.

**Comment by kannon92** [comment]
146fbbc437223786b7c970b50ddd2969be80d3fd.
Sorry, this should be a fully updated psi4.  Last commit was 1/6/2017.

**Comment by loriab** [comment]
are all the test plugins building ok upon first compilation? What does your (staged or installed) [plugin cache](https://github.com/psi4/psi4/blob/master/psi4/psi4PluginCache.cmake.in) look like?

**Comment by kannon92** [comment]
Where can I find the plugin cache?

**Comment by kannon92** [comment]
NVM.  I found it.

    set(CMAKE_C_COMPILER          "/usr/bin/gcc" CACHE STRING "")
    set(CMAKE_C_FLAGS             " -march=native -fopenmp" CACHE STRING "")
    set(CMAKE_CXX_COMPILER        "/usr/bin/g++" CACHE STRING "")
    set(CMAKE_CXX_FLAGS           " -march=native -fopenmp" CACHE STRING "")
    set(CMAKE_Fortran_COMPILER    "" CACHE STRING "")
    set(CMAKE_Fortran_FLAGS       "" CACHE STRING "")

    #set(CMAKE_INSTALL_PREFIX      "/home/kannon/src/psi4_cmake/Install_Debug" CACHE PATH "")
    set(CMAKE_INSTALL_LIBDIR      "lib" CACHE STRING "")
    set(CMAKE_INSTALL_BINDIR      "bin" CACHE STRING "")
    set(CMAKE_INSTALL_DATADIR     "share" CACHE STRING "")
    set(CMAKE_INSTALL_INCLUDEDIR  "include" CACHE STRING "")
    set(PYMOD_INSTALL_LIBDIR      "/" CACHE STRING "")

    set(CMAKE_INSTALL_MESSAGE     "LAZY" CACHE STRING "")

    set(PYTHON_VERSION_MAJORMINOR "2.7" CACHE STRING "")
    set(PYTHON_EXECUTABLE         "/usr/bin/python" CACHE STRING "")

**Comment by loriab** [comment]
That's exactly the contents of `/home/kannon/src/psi4_cmake/Build_Debug/stage/home/kannon/src/psi4_cmake/Install_Debug/shar e/cmake/psi4/psi4PluginCache.cmake` (from above)? Is the space just a formatting thing? Are you trying to run `--inplace`?

**Comment by loriab** [comment]
And search your plugin for `@CXX@`. I don't know where that's coming from.

**Comment by kannon92** [comment]
Yes, that is exactly the contents of the above location.  This plugin is just the basic psi4 plugins.  All of them fail to compile/install.  If I search for @CXX, this shows up in every CMakeLists.txt in the Build/psi4 plugins directory.  

No, I have never used `--inplace`.

**Comment by loriab** [comment]
I've got no `@CXX@` anywhere, so I'd check your versions again. Maybe a fresh clone-and-build in case something lingered.

Actually, now I'm seeing your edited skeleton/CM* post and that's all wrong. Should look like https://github.com/psi4/psi4/blob/master/psi4/share/psi4/plugin/basic/CMakeLists.txt.template

**Comment by kannon92** [comment]
Yea, I really need to learn that you guys do a lot of work in a few weeks and that usually requires me to clone-and-build rather than just do git pull.

I do have a small problem now.  I am not able to call psi4.  This happens if I just run psi4 in the stage/bin directory.  

    File "../../stage/home/kannon/src/psi4_cmake/Install_Debug/bin/psi4", line 140, in <module>
    import psi4
    File    "/home/kannon/src/psi4_cmake/Build_Debug/stage/home/kannon/src/psi4_cmake/Install_Debug/lib//psi4/__init__.py", line 72, in <module>
    from .driver import endorsed_plugins
    File    "/home/kannon/src/psi4_cmake/Build_Debug/stage/home/kannon/src/psi4_cmake/Install_Debug/lib//psi4/driver/__init__.py", line 35, in <module>
    from psi4.driver.plugin import *
    File "/home/kannon/src/psi4_cmake/Build_Debug/stage/home/kannon/src/psi4_cmake/Install_Debug/lib//psi4/driver/plugin.py", line 91, in <module>
    for dir in os.listdir(plugin_path):
    OSError: [Errno 2] No such file or directory:    '/home/kannon/src/psi4_cmake/Build_Debug/plugins/skeleton/plugin'`

**Comment by loriab** [comment]
Are you setting `PSIDATADIR`? To what? I don't agree with it searching in "/home/kannon/src/psi4_cmake/Build_Debug/plugins/skeleton/plugin"

Often, just a new objdir suffices.

**Comment by kannon92** [comment]
No, I do not have PSIDATADIR set.  How do I set PSIDATADIR if psi4 isn't compiled?  

Is what I am doing to compile wrong?  

    cmake -H. -B/home/kannon/src/psi4_cmake/Build_Debug \
    -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Debug \
    -DMAX_AM_ERI=4 -DCMAKE_INSTALL_PREFIX=/home/kannon/src/psi4_cmake/Install_Debug

**Comment by kannon92** [comment]
I realized that having PSI4DATADIR set to "" causes this error.  Instead, I had to make sure that PSI4DATADIR was not set at all.

**Comment by loriab** [comment]
Ok, good, I was still trying to untangle what were your srcdirs, objdirs, installdirs, etc.

Yes, in ~1.1 and beyond you really shouldn't ever have to set PSIDATADIR. But having it set can definitely confuse everything, which you've found.

**Comment by kannon92** [comment]
If I have different compilations such as a Debug and a Release version, how do I make sure the correct PSIDATADIR is being found?

**Comment by loriab** [comment]
Firstly, PSIDATADIR points to stuff like basis sets, so it wouldn't much matter.

But to answer your question properly, all the non-compiled/share/PSIDATADIR files are copied into objdir. So the `bin/psi4` can find `lib/psi4/core.so` and `share/psi4` relative to it. PSIDATADIR or `-p` only serve to override the correct default.

Note that the driver loc is no longer managed by PSIDATADIR. And because driver is copied into objdir/stage, editing driver in source has no effect until you `make` to recopy into objdir/stage.
