### ISSUE TITLE
6-311g_2df_p_.gbs missing basis sets?

### ISSUE THREAD

**Issue by mattbernst** [psi4/psi4#58]
I was trying to run a Gaussian-2 energy calculation for hydrogen disulfide, which appears in the original G2 test set: http://scitation.aip.org/content/aip/journal/jcp/94/11/10.1063/1.460205

The job terminated after calculating the MP4(SDTQ) total energy, with message:

RuntimeError: sanity check failed! Gaussian94BasisSetParser::parser: Unable to find the basis set for S in /opt/science/psi/psi4/share/psi/basis/6-311g_2df_p_.gbs

When I examine the 6-311g_2df_p_.gbs file, I see that it only has entries for H, He, Li, Be, B,  C, N, O, F, Ne, K, Ca. According to the comment at the top of the file it's supposed to have been merged from 6-311G** and 6-311G on the EMSL Basis Set Exchange. I double checked on the BSE and these basis sets also have entries for   Na, Mg, Al, Si, P, S, Cl, Ar, Ga, Ge, As, Se, Br, Kr, I, as expected.

**Comment by kannon92** [comment]
Anybody try and work on this?

**Comment by dgasmith** [comment]
The comment is apparently incorrect (since corrected). The 6-311G(2df,p) basis set is merged from `6-311G` and `Pople (2df,2pd) Polarization`. The EMSL only contains the current set of elements, if there is a location that contains additional elements we would be happy to add them.
