### ISSUE TITLE
Source tarball with a release number

### ISSUE THREAD

**Issue by samfux84** [psi4/psi4#580]
Hi all,

I am installing software on a HPC cluster. In general, I always install from source (whenever it is possible to get source code). I would like to ask if it is possible to get PSI 4 source code tarballs with a release number, because we use environment modules to manage different versions of a software.

For a release 1.1 of PSI 4, I would for instance create a module named psi4/1.1. If I would start creating modules named after git commit tags, like

psi4/e0a3eb254d184eed69ab8f598c8601cab12c610b￼

users would not understand what version they are actually using.

Best regards

Sam

**Comment by hokru** [comment]
Guess you are looking for these: https://github.com/psi4/psi4/releases

**Comment by samfux84** [comment]
Hi hokru,

Thank you very much, this is exactly what I am looking for.

Is this documented anywhere ? Or is there a link on the main page of the psi4 github repository pointing to this release page ?

Best regards

Sam

**Comment by hokru** [comment]
yeah, you see the pink & blue line at top of the psi4 main page? Above it says commits, branches, **releases**, contributors, etc.

**Comment by samfux84** [comment]
Thank you very much. I am not very familiar with git. Initially I followed the description at

https://github.com/psi4/psi4/wiki/1_Obtaining#tarballpsi4public

Therefore I had the impression that I can only get a tar of the master branch.

**Comment by loriab** [comment]
@hokru is quite right. You can get a tarball of any commit, tag, or release of any repository through GitHub.

I'd strongly recommend doing a clone, rather than a tarball, so that you can update easily and do partial rebuilds. Even more strongly, I'd recommend you do something in the 1.1 release series, like 1.1a1 (if you really want a tag) https://github.com/psi4/psi4/tags because Psi4 has had its build system rewritten, has dumped boost, has switch from an executable to a library, and has had its git history rewritten after the 1.0 release (for all that, running it is exactly the same). Because of the history rewrite, I'm not even sure a 1.0 can be extracted from this repo (we've a plan to put up a separate 1.0 repo; Yes, there probably should be a big warning sign against trying to build 1.0 from existing repo). So, please clone and build HEAD, or clone and build 1.1a1 (if you prefer tags), or tarball and build 1.1a1 (if you must).

The wiki for building is out of date. New instructions have been moved into the main documentation. That should get posted today, it was only committed yesterday.

Even if you did just have a random git tag like e0a3ab, that gets translated into a sortable version (you can see yourself after cloning by running `python psi4/versioner.py`). So you'd still have a version like `1.1a1.dev100` to label the installation.

**Comment by samfux84** [comment]
Hi loriab,

Thank you for your reply.

On our HPC cluster, we do not update software. If there is a newer version of a software, we do an additional installation next to the existing version. For us it is important to provide continuity to the researchers. If data is published and a year or two later a researcher for some reason needs to reproduce a calculation, we would like to provide exactly the same software version that was used for the first run. Since that means that we have a lot of versions installed for a certain softwares, there needs to be a transparent way to distinguish the versions (and it should be obvious to the user, which version he is using).

Tags sounds like a good solution for the installations that I am doing. I just tried to build release 1.0 from the release tarball and encountered some problems (half a year ago I have built 1.0 rc1 and this worked well).  I just need to build a version that is newer than 1.0 rc1, because of a SAPT bug in rc1. Are tagged versions static or do they also change ?

I will try to clone and build 1.1a1.

Thank you very much for replying to my questions.

Best regards

Sam

**Comment by loriab** [comment]
Ok, I see. 1.1a1 should do nicely for you. Tagged versions _are_ static once pushed to the repo. On the main repo, we'll probably change `1.0 to 1.0approx` and clear out the old ones, since the history re-write has rendered them defunct. But the history rewrite was a once-in-many-years event that cut our download size by 90%, so tags hereafter should be stable.

**Comment by samfux84** [comment]
Hi loriab,

Sorry for asking that many questions.

v1.1a1 requires GCC 4.9 or newer. Most software on our cluster is compiled with GCC 4.8.2 and I would like to avoid recompiling Python, HDF5, GSL etc. with a newer compiler version.

The reason for compiling a newer version of psi4 is the the following post from Robert (SAPT bug in 1.0 rc1):

http://forum.psicode.org/t/problem-in-sapt2-3-dmp2-calculation/395

In your reply to the post you mentioned that there was a clean up of the SAPT code in july:

"Your input worked just fine on my current Psi4. There've been a lot of changes to Psi4 since 1.0rc, and there was a clean-up of SAPT printing in July, so I recommend you update to current Psi4 which is ~700 commits ahead of where you're at. Especially since you're running SAPT. Did you build your own or do you want to try the conda binary?"

Is there are psi4 version with the new SAPT code, which builds with GCC 4.8.2 ?

Best regards

Sam

**Comment by samfux84** [comment]
sorry, accidentally closed the issue

**Comment by loriab** [comment]
Psi4 1.0 and its successors in the 1.0 release series have the new SAPT code _and_ build with GCC 4.8. But for all the aforementioned reasons I advise building a 1.1a1 series Psi4 (and the fact that I tested the sapt2+3dmp2 forum post on a 1.1a1 series).

We can get around your problem 4.8.2 problem. You don't have to compile _everything_ with >=4.9 GCC, just Psi4. (HDF5 isn't a dependency unless you `ENABLE_CheMPS2=ON`; GSL no longer a dependency at all; Python only an interpreter and header dependency, not library). You can get a gcc 5.2 from conda vis [these instructions](https://github.com/psi4/psi4/blob/master/doc/sphinxman/source/build_planning.rst#how-to-satisfy-the-gcc--49-requirement-on-linux-without-updating-the-os) and use that to compile Psi4, without ever interfering with your system gcc.

**Comment by andysim** [comment]
I think you should be able to compile the newer code with a modern compiler, but link against the existing python; the ABI is the same between different GCC versions as far as I'm aware.  The newer compiler is needed to support C++11, which is only partially supported in 4.8.

**Comment by samfux84** [comment]
Hi loriab,

Thank you for your reply. I already have access to GCC 5.2.0 and 6.2.0 on the cluster. I currently try to compile psi4 with GCC 5.2.0.

I am currently struggling with specifying the BLAS library. I would like to use OpenBLAS 0.2.13, but somehow cmake has problems to automatically detecting it and I also don't know how I can specify the explicit path to the library (/cluster/apps/openblas/0.2.13_seq/x86_64/gcc_5.2.0/lib/libopenblas.so).

I already tried setting

export MATH_ROOT=/cluster/apps/openblas/0.2.13_seq/x86_64/gcc_5.2.0/lib

and

export MATH_ROOT=/cluster/apps/openblas/0.2.13_seq/x86_64/gcc_5.2.0

but in both cases OpenBLAS is not detected. If I disable the ENABLE_AUTO_BLAS and the ENABLE_AUTO_LAPACK settings, how can I specify the absolute path to the library ?

Thank you for your help.

@andysim:
According to https://gcc.gnu.org/projects/cxx-status.html#cxx11:

"GCC 4.8.1 was the first feature-complete implementation of the 2011 C++ standard, previously known as C++0x."

Best regards

Sam

**Comment by loriab** [comment]
I [understand](http://stackoverflow.com/a/12665408) the GCC folks selected a limited definition of "feature-complete" when they wrote that sentence about 4.8.

I use MKL so exclusively that I can only offer tentative advice on the Math detection. Check [this bit](https://github.com/psi4/psi4/blob/master/cmake/math/MathLibs.cmake#L18-L28) of code and make sure OpenBlas's headers are matching up. Then maybe change the libs from `blas` to `openblas` and try again with MATH_ROOT.

Even if it detects properly for Psi4, you may still hit a block with math libs for libefp. Been working on solving that problem this weekend.

I've no experience with the quality of OpenBLAS. But if it's not better than a system native distribution, you may prefer the binary that has high-quality math libs baked in.

**Comment by samfux84** [comment]
The quality of OpenBLAS (https://github.com/xianyi/OpenBLAS) should be fine. It is based on GotoBLAS that used to outperform ATLAS and in some cases even MKL. Kazushige Goto, the developer of GotoBLAS was then hired by Intel. 

Thank you for the hint about MathLibs.cmake. Based on https://github.com/coderefinery/autocmake/blob/master/modules/math_libs.cmake (lines 127-141) I have added support for detecting OpenBLAS (with the changes it is detected even without setting MATH_ROOT)

```
[sfux@develop01 psi4]$ cat CMakeAddOpenBLAS.patch 
diff -crB psi4_/cmake/math/ConfigMath.cmake psi4/cmake/math/ConfigMath.cmake
*** psi4_/cmake/math/ConfigMath.cmake   2017-01-20 09:35:51.000000000 +0100
--- psi4/cmake/math/ConfigMath.cmake    2017-01-24 09:52:50.074349042 +0100
***************
*** 14,20 ****
  if(ENABLE_64BIT_INTEGERS)
      set(MATH_LIB_SEARCH_ORDER MKL ACML)
  else()
!     set(MATH_LIB_SEARCH_ORDER MKL ESSL ATLAS ACML SYSTEM_NATIVE)
  endif()

  if(NOT DEFINED MKL_FLAG)
--- 14,20 ----
  if(ENABLE_64BIT_INTEGERS)
      set(MATH_LIB_SEARCH_ORDER MKL ACML)
  else()
!     set(MATH_LIB_SEARCH_ORDER MKL OPENBLAS ESSL ATLAS ACML SYSTEM_NATIVE)
  endif()

  if(NOT DEFINED MKL_FLAG)
diff -crB psi4_/cmake/math/MathLibs.cmake psi4/cmake/math/MathLibs.cmake
*** psi4_/cmake/math/MathLibs.cmake     2017-01-20 09:35:51.000000000 +0100
--- psi4/cmake/math/MathLibs.cmake      2017-01-24 09:28:13.812117187 +0100
***************
*** 73,78 ****
--- 73,93 ----
  set(ATLAS_LAPACK_LIBS atlas lapack)
  
  #-------------------------------------------------------------------------------
+ # OPENBLAS
+ 
+ set(OPENBLAS_BLAS_INCLUDE_PATH_SUFFIXES)
+ set(OPENBLAS_LAPACK_INCLUDE_PATH_SUFFIXES)
+ 
+ set(OPENBLAS_BLAS_HEADERS cblas.h openblas_config.h f77blas.h)
+ set(OPENBLAS_LAPACK_HEADERS lapacke.h lapacke_config.h lapacke_mangling.h lapacke_utils.h)
+ 
+ set(OPENBLAS_BLAS_LIBRARY_PATH_SUFFIXES openblas)
+ set(OPENBLAS_LAPACK_LIBRARY_PATH_SUFFIXES openblas)
+ 
+ set(OPENBLAS_BLAS_LIBS  openblas)
+ set(OPENBLAS_LAPACK_LIBS openblas)
+ 
+ #-------------------------------------------------------------------------------
  # MKL
  
  set(MKL_BLAS_INCLUDE_PATH_SUFFIXES)
[sfux@develop01 psi4]$ ls
cdash  CMakeAddOpenBLAS.patch  _conda_vers.py     doc       LICENSE  plugins  README.md  _setup.py
cmake  CMakeLists.txt          CTestConfig.cmake  external  media    psi4     samples    tests
[sfux@develop01 psi4_]$ patch -p1 --verbose < CMakeAddOpenBLAS.patch 
Hmm...  Looks like a new-style context diff to me...
The text leading up to this was:
--------------------------
|diff -crB psi4_/cmake/math/ConfigMath.cmake psi4/cmake/math/ConfigMath.cmake
|*** psi4_/cmake/math/ConfigMath.cmake   2017-01-20 09:35:51.000000000 +0100
|--- psi4/cmake/math/ConfigMath.cmake    2017-01-24 09:52:50.074349042 +0100
--------------------------
Patching file cmake/math/ConfigMath.cmake using Plan A...
Hunk #1 succeeded at 14.
Hmm...  The next patch looks like a new-style context diff to me...
The text leading up to this was:
--------------------------
|diff -crB psi4_/cmake/math/MathLibs.cmake psi4/cmake/math/MathLibs.cmake
|*** psi4_/cmake/math/MathLibs.cmake    2017-01-20 09:35:51.000000000 +0100
|--- psi4/cmake/math/MathLibs.cmake     2017-01-24 09:28:13.812117187 +0100
--------------------------
Patching file cmake/math/MathLibs.cmake using Plan A...
Hunk #1 succeeded at 73.
done
[sfux@develop01 psi4]$
```
The code (using OpenBLAS instead of MKL) compiles without error but fails in an installation step:

```
-- Installing: /scratch/appssf/psi4/build/stage/cluster/apps/psi4/1.1a1/x86_64/lib//psi4/driver/util/__init__.py
-- Installing: /scratch/appssf/psi4/build/stage/cluster/apps/psi4/1.1a1/x86_64/lib//psi4/driver/util/filesystem.py
-- Installing: /scratch/appssf/psi4/build/stage/cluster/apps/psi4/1.1a1/x86_64/lib//psi4/driver/util/tty
-- Installing: /scratch/appssf/psi4/build/stage/cluster/apps/psi4/1.1a1/x86_64/lib//psi4/driver/util/tty/__init__.py
-- Installing: /scratch/appssf/psi4/build/stage/cluster/apps/psi4/1.1a1/x86_64/lib//psi4/driver/util/tty/color.py
-- Installing: /scratch/appssf/psi4/build/stage/cluster/apps/psi4/1.1a1/x86_64/lib//psi4/driver/wrapper_autofrag.py
-- Installing: /scratch/appssf/psi4/build/stage/cluster/apps/psi4/1.1a1/x86_64/lib//psi4/driver/wrapper_database.py
-- Installing: /scratch/appssf/psi4/build/stage/cluster/apps/psi4/1.1a1/x86_64/lib/psi4/header.py
-- Installing: /scratch/appssf/psi4/build/stage/cluster/apps/psi4/1.1a1/x86_64/lib/psi4/extras.py
-- Installing: /scratch/appssf/psi4/build/stage/cluster/apps/psi4/1.1a1/x86_64/lib/psi4/__init__.py
-- Installing: /scratch/appssf/psi4/build/stage/cluster/apps/psi4/1.1a1/x86_64/lib/psi4/config.py
-- Installing: /scratch/appssf/psi4/build/stage/cluster/apps/psi4/1.1a1/x86_64/share/cmake/psi4/psi4Config.cmake
-- Installing: /scratch/appssf/psi4/build/stage/cluster/apps/psi4/1.1a1/x86_64/share/cmake/psi4/psi4ConfigVersion.cmake
-- Installing: /scratch/appssf/psi4/build/stage/cluster/apps/psi4/1.1a1/x86_64/lib/psi4/core.so
CMake Error at src/cmake_install.cmake:44 (file):
  file INSTALL cannot copy file
  "/scratch/appssf/psi4/build/psi4_core-prefix/src/psi4_core-build/src/core.so"
  to
  "/scratch/appssf/psi4/build/stage/cluster/apps/psi4/1.1a1/x86_64/lib/psi4/core.so".
Call Stack (most recent call first):
  cmake_install.cmake:167 (include)


gmake[3]: *** [install] Error 1
gmake[3]: Leaving directory `/scratch/appssf/psi4/build/psi4_core-prefix/src/psi4_core-build'
make[2]: *** [psi4_core-prefix/src/psi4_core-stamp/psi4_core-install] Error 2
make[2]: Leaving directory `/scratch/appssf/psi4/build'
make[1]: *** [CMakeFiles/psi4_core.dir/all] Error 2
make[1]: Leaving directory `/scratch/appssf/psi4/build'
make: *** [all] Error 2
```
For compiling, I was using "make -j 8". I will try to compile serially and see if that was the cause for the installation problem.

Best regards and thank you very much for your help

Sam

**Comment by loriab** [comment]
Thanks very much for the OpenBLAS patch. Do you want to submit it as a Pull Request so you show up as a contributor, or would you rather I just added it to the code?

That install error is bizarre. Make double sure of your permissions and disk space perhaps? We regularly build in parallel (up to `-j12`), so that shouldn't be a problem.

**Comment by samfux84** [comment]
It would be nice if you could add the code. I don't need to show up as a contributor (as the changes are based on code in the autocmake github repo). But can you please wait before adding the code, until we could verify that the compilation with OpenBLAS works.

After getting the error, I have run make a second time and then I did not get the error any more. I have therefore deleted the installation and redid it from scratch. This time, I am running make serially. The compilation is still ongoing. I will provide you an update once it finished and after having verified that the code is properly linked against OpenBLAS.

Best regards

Sam

**Comment by samfux84** [comment]
I have changed some CMake variable and now the compilation  works fine (I think it was related to having CMAKE_OLDINCLUDEDIR set to /usr/include, causing a permission problem in the installation step)

Linking with OpenBLAS also seems to have worked fine:

```
[sfux@develop01 x86_64]$ ldd lib/psi4/core.so 
        linux-vdso.so.1 =>  (0x00007ffc83bea000)
        libpython2.7.so.1.0 => /cluster/apps/python/2.7.12/x86_64/lib64/libpython2.7.so.1.0 (0x00007f1a75aa0000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f1a7588b000)
        libopenblas.so.0 => /cluster/apps/openblas/0.2.13_seq/x86_64/gcc_5.2.0/lib/libopenblas.so.0 (0x00007f1a736f5000)
        libstdc++.so.6 => /cluster/apps/gcc/5.2.0/lib64/libstdc++.so.6 (0x00007f1a73366000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f1a730e1000)
        libgomp.so.1 => /cluster/apps/gcc/5.2.0/lib64/libgomp.so.1 (0x00007f1a72ec0000)
        libgcc_s.so.1 => /cluster/apps/gcc/5.2.0/lib64/libgcc_s.so.1 (0x00007f1a72caa000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f1a72a8c000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f1a726f8000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f1a724f5000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f1a78d6a000)
        libgfortran.so.3 => /cluster/apps/gcc/5.2.0/lib64/libgfortran.so.3 (0x00007f1a721d5000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f1a71fcd000)
        libquadmath.so.0 => /cluster/apps/gcc/5.2.0/lib/../lib64/libquadmath.so.0 (0x00007f1a71d8d000)
[sfux@develop01 x86_64]$ 
```

I did a quick test with

```
#! Sample UHF/6-31G** CH2 computation

memory 250 mb

molecule ch2 {
  0 3
  C
  H 1 R
  H 1 R 2 A

  R = 1.075
  A = 133.93
}

set basis 6-31G**
set reference uhf
energy ('scf')
```
to verify that the installation does not crash on startup. So far everything looks fine.

I have a comment about the shebang line in the psi4 python script. After the installation it was set to an absolute path:

#!/cluster/apps/python/2.7.12/x86_64/bin/python

On larger clusters, there are usually multiple python versions installed in non-standard locations. Therefore when I install executable python scripts on our cluster, I usually change the shebang line to

#!/usr/bin/env python

This way, it takes the first python interpreter that is found in $PATH. This can be convenient for systems with multiple python versions. On our cluster, we use environment modules to manage different versions of the same software. If I have a python script with the generic shebang line, I can choose the Python interpreter by loading the corresponding module
```

[sfux@euler04 ~]$ module load python/2.7.6
Autoloading openblas/0.2.13_seq
[sfux@euler04 ~]$ /usr/bin/env python -V
Python 2.7.6
[sfux@euler04 ~]$ module purge
[sfux@euler04 ~]$ module load new python/2.7.9
Autoloading openblas/0.2.13_seq
[sfux@euler04 ~]$ /usr/bin/env python -V
Python 2.7.9
[sfux@euler04 ~]$ module purge
[sfux@euler04 ~]$ module load new python/2.7.12
Autoloading openblas/0.2.13_seq
[sfux@euler04 ~]$ /usr/bin/env python -V
Python 2.7.12
[sfux@euler04 ~]$
```

Best regards and thank you again for your help

**Comment by loriab** [comment]
Great, glad it's working. I'll get your OpenBLAS patch added in, and it'll make its way back upstream to autocmake one day.

Your `ldd` looks good. Only thing strikes me as odd is `libpython.so`. We stopped actually linking to this and now only require the interpreter, not the library. But maybe you're compiling 1.1a1 and the change happened afterward. In any case, when you update someday, don't be alarmed if that goes away.

On the `#!/cluster/apps/python/2.7.12/x86_64/bin/python`, we go back and forth on whether to embed the specific compile-time version or a more generic `/usr/bin/env python2` or `usr/bin/env python3`. Advantages of the former: (a) user can be oblivious to what or if python in path at all, (b) conda does it this way. Advantages of the latter: (a) it's what Linux users expect to be happening, (b) avoids trouble of psi4 still using compile environment if you have separate compile and run-time environments. We've stuck with the former since it's friendlier to the inexperienced. Go right ahead and edit that line to a `/usr/bin/env` if it's more suited to your cluster, but I do recommend doing `python2` since the python2/3 headers are used during the build.

By the way, on testing, there's `share/psi4/samples/*/test.in` files that'll print `SUCCESS`/`FAILED` to the screen and are handy for testing (or run `ctest -L quick -j4`)

**Comment by samfux84** [comment]
I think that I know where the linking against the Python library comes from. Usually when using CMake to build software, I am using the ccmake GUI and use the toggle option to show all available variables (as I usually also add compiler flags etc.). I noticed that cmake detected the correct Python interpreter (2.7.12), but it also had a variable for the Python library, which was pointing to /usr/lib64/libpython2.6.so (system Python that was installed with the operating system). In order to avoid mixing between different Python versions, I have set the CMake variable to the 2.7.12 version of the library. Maybe CMake picked it up this way and added it to the libraries that are linked.

Thank you for pointing me to the tests in the samples directory.

Best regards

**Comment by loriab** [comment]
Good move fixing the `PYTHON_LIBRARY` CMake variable; mixed detection of Python interpreter/library/headers is definitely a scourge of Psi4 compilation. But I set that variable all the time and don't get an actual link to `libpython`. So I think it is just the version you're building is before we stopped linking explicitly.
