### ISSUE TITLE
scf guess read fails when molecule is modified

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#586]
I'm trying to run some FCI calculations without symmetry to ensure I land on the ground state. However, the SCF is sometimes very hard to do without symmetry, so I'd like to run SCF with symmetry, switch symmetry off and check if I'm still at a stable solution.

However, I find I'm unable to change my molecule for symmetry constraints (or charge/multiplicity for that matter). The following input
```
molecule sym {
0 1
H  0.459619  0.000000 0.000000
H  0.000000  0.459619 0.000000
}

set basis STO-3G
energy('scf')

molecule nosym {
0 1
H  0.459619  0.000000 0.000000
H  0.000000  0.459619 0.000000
}

set scf guess read
energy('scf')
```
runs the first SCF, but crashes on the second with
```
RuntimeError: 
Fatal Error:   SCF guess was set to SAD, but sad_basissets_ was empty!


Error occurred in file: /home/work/psi4/psi4/psi4/src/psi4/libscf_solver/sad.cc on line: 659
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)
psi::scf::HF::compute_SAD_guess()
psi::scf::HF::guess()
psi::scf::HF::initialize()
psi::scf::HF::compute_energy()
```
Oddly, it appear that while in the second run
```
  ==> Algorithm <==

  SCF Algorithm Type is DF.
  DIIS enabled.
  MOM disabled.
  Fractional occupation disabled.
  Guess Type is READ.
  Energy threshold   = 1.00e-06
  Density threshold  = 1.00e-06
  Integral threshold = 0.00e+00
```
the initialization uses
```
  ==> Integral Setup <==

  ==> DFJK: Density-Fitted J/K Matrices <==

    J tasked:                  Yes
    K tasked:                  Yes
    wK tasked:                  No
    OpenMP threads:              1
    Integrals threads:           1
    Memory (MB):               375
    Algorithm:                Core
    Integral Cache:           NONE
    Schwarz Cutoff:          1E-12
    Fitting Condition:       1E-12

   => Auxiliary Basis Set <=

  Basis Set: file /home/work/psi4/install/share/psi4/basis/def2-svp-jkfit.gbs
    Number of shells: 12
    Number of basis function: 36
    Number of Cartesian functions: 40
    Spherical Harmonics?: true
    Max angular momentum: 2

  Minimum eigenvalue in the overlap matrix is 2.8114045453E-01.
  Using Symmetric Orthogonalization.

  SCF Guess: Superposition of Atomic Densities via on-the-fly atomic UHF.
```
followed by the crash.

**Comment by dgasmith** [comment]
Hi Susi,
There should be a line like: `  Unable to find file 180, defaulting to SAD guess.`. Guess read will only find a written file with the same molecule name and PID so the fact that you changed the molecule name means that it has nothing to read from.

Not setting the SAD basis is a oversight, however. I will open a PR to fix this.

As a note `GUESS READ` is not capable of casting between symmetries. This may be possible now, ill look into it.

**Comment by dgasmith** [comment]
Hi Susi, I made a new PR to fix the underlying SAD issue. However, READ casting between symmetries will need to wait for Psi4 1.2 as its fixed there.

Changing the multiplicity/charge is trickier as its not clear the priority order for occupations (read/guess/eigenvalue ordering). Please note that [this](https://github.com/psi4/psi4/issues/483) ticket attempts to address these issues.
