### ISSUE TITLE
cartesian PEC without nocom / no_reorient

### ISSUE THREAD

**Issue by edeprince3** [psi4/psi4#59]
If a user wants to make a potential energy curve or surface, it is very easy to generate nonsense when using cartesian coordinates.  Using nocom and no_reorient fixes this, so maybe the driver should be setting these options if it detects such a case.

``` python
molecule beh2 {
Be 0.0  0.0    z
H  0.0  1.0  0.0
H  0.0 -1.0  0.0
}
molecule beh2_nocom {
Be 0.0  0.0    z
H  0.0  1.0  0.0
H  0.0 -1.0  0.0
nocom
no_reorient
}
activate(beh2)
set basis sto-3g
set guess sad
for i in range (1,41):
    z = i*0.1
    beh2.z = z
    e = energy('scf')
    print z,e
    set guess read
print ''

activate(beh2_nocom)
set basis sto-3g
set guess sad
for i in range (1,41):
    z = i*0.1
    beh2_nocom.z = z
    e = energy('scf')
    print z,e
    set guess read
```

**Comment by dgasmith** [comment]
Very late to the party, but #760 will fixes this. For example in @jsspencer case the first loop will set the distance to 1.0, which will move to the COM so each atom is +/- 0.5. When the distance is set to 1.5 the `d` will indeed be set to this distance, but the other atoms are still at +/- 0.5. The distance will therefore be 2.0.
