### ISSUE TITLE
CI natural orbitals occupation numbers not printed out with nat_orbs=true

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#590]
Somewhat related to issue 556 and pull 588, if you set nat_orbs to true and run a CI calculation, you don't get the natural orbital occupations in the output, whereas if you're running CASSCF you get a nice printout. 

I'm guessing the NOONs should get printed out, since the output file does say
```
   Computing CI Natural Orbitals
   !Warning: New orbitals will be sorted by occuption number,
   orbital spaces (occ/act/vir) may change.
```

Example input
```
molecule {
0 1
symmetry c1
C
C 1 1.0
}

set basis cc-pVDZ
set scf_type pk
set nat_orbs true
set wfn detci
set restricted_docc [2]

# Run CISDT
cas_e, cas_wfn = energy('cisdt', return_wfn=True)
```

**Comment by dgasmith** [comment]
The MCSCF printing and the NO are different routines (hence why `nat_orbs` was broken for MCSCF, but not CI). What kind of printing would you want here?

**Comment by susilehtola** [comment]
It'd be nice to have the same printing as for MCSCF, since the cases where you want the NOs for further calculations I guess you're also interested in their occupation numbers.
