### ISSUE TITLE
detci expansion length for truncated CI

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#600]
It would appear that detci sets up string lengths that correspond to FCI, which makes truncated CI calculations very expensive. For example, (10e,10o) gives
    There are 252 alpha and 252 beta strings
    The CI space requires 63504 (6.35E+04) determinants and 1 blocks
regardless of the truncation level.

What's the correct way to run truncated CI with detci? Should I be assigning the states to RAS I and III and leave RAS II empty?

**Comment by dgasmith** [comment]
If you are calling `casscf` it is running FCI in the active space. To run truncated CI you need to specify `rasscf` and manipulate the `RAS` spaces to obtain the excitations that you wish.

**Comment by susilehtola** [comment]
I'm not calling 'casscf', I'm calling 'cisd' or 'cisdt'.

**Comment by susilehtola** [comment]
The question is how to run truncated CI most efficiently in detci.

**Comment by dgasmith** [comment]
For Neon aDZ I get the following number of determinants:
```
CISD:   1579
CISDT: 38375
```

**Comment by susilehtola** [comment]
```
molecule {
1 1
symmetry c1
O
O 1 R1
O 2 R2 1 A1
H 3 R3 2 A2 1 D1

R1=1.228
R2=1.587
R3=0.968
A1=109.80
A2=97.10
D1=180.0
}

set basis 6-31G
set reference rohf
set scf_type pk
set nat_orbs true
scf_e, scf_wfn = energy('scf', return_wfn=True)

set restricted_docc [7]
set active [10]
set qc_module detci
ci_e, ci_wfn = energy('cisd', return_wfn=True, ref_wfn=scf_wfn)
```
has Nmo = 29 and docc = 12, so a (10e,10o) active space.

I get with cisd
```
    There are 252 alpha and 252 beta strings
    The CI space requires 63504 (6.35E+04) determinants and 1 blocks
```
with cisdt
```
    There are 252 alpha and 252 beta strings
    The CI space requires 63504 (6.35E+04) determinants and 1 blocks
```
and with cisdtq
```
    There are 252 alpha and 252 beta strings
    The CI space requires 63504 (6.35E+04) determinants and 1 blocks
```

63504 is the dimension of the FCI space.

**Comment by dgasmith** [comment]
Ah yes, when you set `active` you are effectively setting `RAS 2`. What you really want to do is set the restricted space like so:

`restricted_uocc [12]`

From the output:

    The CI space requires 876 (8.76E+02) determinants and 6 blocks

Cheers,
Daniel Smith

**Comment by susilehtola** [comment]
Oh wow. Thanks for the tip!

**Comment by susilehtola** [comment]
Actually, if this is intended, then the manual should be adjusted. 'active' is listed as a relevant keyword for CI in the "Spaces available in the MCSCF program" section at http://www.psicode.org/psi4manual/master/detci.html

Otherwise, the behavior should be changed that when running ci(n), the code should figure out the resulting restricted spaces..

**Comment by CDSherrill** [comment]
Ah, I see the source of confusion.  I will make some edits to the docs.

Best,
David

**Comment by CDSherrill** [comment]
@dgasmith , the current docs have a section about how orbital space keywords like frozen_docc need to be visible to modules besides DETCI, because they affect integrals transformation, and (formerly) things like the Lagrangian computation, etc.  I think in the current version of the code, you have put all that under one roof in DETCI, and so in principle we no longer need this warning.  Does that sound correct?  And would these technically work if put under set detci { } instead of set { } ?

**Comment by dgasmith** [comment]
Yes, the MCSCF keywords have always fallen under the DETCI roof except for "ACTIVE" which is a global keyword. Setting `set detci ACTIVE` will work; however, "ACTIVE" will be set for all modules, not just DETCI.
