### ISSUE TITLE
convergence issue

### ISSUE THREAD

**Issue by lucamontana** [psi4/psi4#603]
Dear all, 

From time to time i have problem with convergence of roots in eom-CCSD calculations.
Here an example of non-converging 1Ag root of benzene :

```
memory 50 Gb
molecule benzene { 
H           0.000000       2.484212       0.000000
H           0.000000      -2.484212       0.000000
H           2.151390       1.242106       0.000000
H          -2.151390      -1.242106       0.000000
H          -2.151390       1.242106       0.000000
H           2.151390      -1.242106       0.000000
C           0.000000       1.396792       0.000000
C           0.000000      -1.396792       0.000000
C           1.209657       0.698396       0.000000
C          -1.209657      -0.698396       0.000000
C          -1.209657       0.698396       0.000000
C           1.209657      -0.698396       0.000000
units ang
 
}

set basis         aug-cc-pvdz 
set scf_type    df
set guess        sad
set reference  rhf
set e_convergence   1e-06
set d_convergence   1e-06
set ints_tolerance     1e-08

set freeze_core     true
set roots_per_irrep [1,0,0,0,0,0,0,0]
set maxiter 100

property('eom-ccsd', properties=['oscillator_strength'])
```

Is there any remedy to overcome convergence issue of roots ?

Bests
LUCA

**Comment by amjames** [comment]
How are you able to tell that it does not converge? I ran the input you posted and It was able to converge fine. 


You should see a section like this in the output file showing the EOM code working away at the root. 
```
Symmetry of ground state: Ag
Symmetry of excited state: Ag
Symmetry of right eigenvector: Ag
Seeking states with multiplicity of 1
Obtaining initial guess from singles-singles block of Hbar...Done.

Iter=1    L=1     Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.4128588902   4.13e-01    3.16e-01      N
Iter=2    L=2     Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3340136980  -7.88e-02    5.54e-02      N
Iter=3    L=3     Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3311169492  -2.90e-03    2.75e-02      N
Iter=4    L=4     Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3303034550  -8.13e-04    1.53e-02      N
Iter=5    L=5     Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3299847862  -3.19e-04    9.33e-03      N
Iter=6    L=6     Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3299158588  -6.89e-05    4.43e-03      N
Iter=7    L=7     Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3299119405  -3.92e-06    1.74e-03      N
Iter=8    L=8     Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3299103467  -1.59e-06    6.71e-04      N
Iter=9    L=9     Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3299072934  -3.05e-06    3.17e-04      N
Iter=10   L=10    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3299064524  -8.41e-07    1.45e-04      N
Iter=11   L=11    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3299063854  -6.69e-08    9.39e-05      Y
Collapsing to only 1 vector(s).

Procedure converged for 1 root(s).
Energy written to CC_INFO:Etot -231.2454217333
States per irrep written to CC_INFO.
EOM CCSD R0 for root 0 =  -0.03232771150

Final Energetic Summary for Converged Roots of Irrep Ag
                     Excitation Energy              Total Energy
                (eV)     (cm^-1)     (au)             (au)
EOM State 1      8.977    72406.1   0.3299063854  -231.245421733323
```

Summary at the end of the file also shows:
```
	                Excitation Energy              OS       RS        RS     Einstein A
	State   (eV)    (cm^-1)    (nm)     (au)              (l,au)   (v,au)     (s^-1)
	 1 Ag   8.977   72406.1   138.1   0.329906   0.0000   0.0000   0.0000  0.000000E+00
```

If you are seeing something different could you put your output in a gist, or pastebin?

**Comment by lucamontana** [comment]
if you calculate higher roots :  set roots_per_irrep [3,0,0,0,0,0,0,0]

you should get the followwing : 

Iter=49   L=36    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016108   3.23e-10    5.08e-07      Y
                     2   0.3299082274  -4.27e-08    2.15e-05      N
                     3   0.3364017920   3.03e-10    6.02e-07      Y
Iter=50   L=6     Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016107  -4.16e-11    5.07e-07      Y
                     2   0.3299082274   9.50e-12    2.15e-05      N
                     3   0.3364017920  -1.83e-11    6.05e-07      Y
Iter=51   L=7     Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016107  -7.15e-12    5.08e-07      Y
                     2   0.3299081111  -1.16e-07    2.65e-05      N
                     3   0.3364017920   5.08e-11    6.06e-07      Y
Iter=52   L=8     Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016109   1.66e-10    5.11e-07      Y
                     2   0.3299079665  -1.45e-07    1.51e-05      N
                     3   0.3364017922   1.60e-10    6.04e-07      Y
Iter=53   L=9     Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016134   2.49e-09    4.23e-07      Y
                     2   0.3299076116  -3.55e-07    2.15e-05      N
                     3   0.3364017922  -2.69e-11    6.01e-07      Y
Iter=54   L=10    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3031989513  -2.11e-02    2.19e-01      N
                     2   0.3243016119  -5.61e-03    4.37e-07      N
                     3   0.3299093542  -6.49e-03    4.01e-05      N
Iter=55   L=13    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.1959550539  -1.07e-01    1.77e-01      N
                     2   0.3243016120   1.51e-10    2.03e-07      Y
                     3   0.3299083008  -1.05e-06    1.35e-05      N
Iter=56   L=15    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.1704364933  -2.55e-02    7.63e-02      N
                     2   0.3243016120   2.24e-11    1.99e-07      Y
                     3   0.3299082189  -8.19e-08    1.11e-05      N
Iter=57   L=17    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.1646225593  -5.81e-03    4.39e-02      N
                     2   0.3243016115  -5.11e-10    1.86e-07      Y
                     3   0.3299081686  -5.03e-08    1.05e-05      N
Iter=58   L=19    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.1600433140  -4.58e-03    5.00e-02      N
                     2   0.2894312372  -3.49e-02    2.35e-01      N
                     3   0.3243016111  -5.61e-03    2.21e-07      N

**Comment by lucamontana** [comment]
or even with this set up : 
set roots_per_irrep [0,2,0,0,0,0,0,0]

The following result is obtained : 

Iter=23   L=18    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016057   2.09e-08    3.54e-05      N
                     2   0.3285655293  -3.33e-16    6.43e-07      Y
Iter=24   L=19    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016099   4.24e-09    2.38e-05      N
                     2   0.3285655293   5.00e-16    6.43e-07      Y
Iter=25   L=20    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016127   2.80e-09    1.56e-05      N
                     2   0.3285655293  -3.89e-16    6.43e-07      Y
Iter=26   L=21    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016234   1.06e-08    9.79e-06      N
                     2   0.3285655293  -1.11e-16    6.43e-07      Y
Iter=27   L=22    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016107  -1.26e-08    5.76e-06      N
                     2   0.3285655293   2.78e-16    6.43e-07      Y
Iter=28   L=23    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016097  -1.01e-09    3.48e-06      N
                     2   0.3285655293  -1.11e-16    6.43e-07      Y
Iter=29   L=24    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016125   2.73e-09    3.28e-06      N
                     2   0.3285655293  -5.55e-17    6.43e-07      Y
Iter=30   L=4     Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016125   8.40e-14    3.28e-06      N
                     2   0.3285655291  -2.62e-10    9.81e-06      N
Iter=31   L=6     Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243015959  -1.66e-08    3.58e-06      N
                     2   0.3285655309   1.79e-09    9.85e-06      N
Iter=32   L=8     Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016034   7.49e-09    2.77e-06      N
                     2   0.3285655292  -1.67e-09    8.87e-06      N
Iter=33   L=10    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016058   2.42e-09    1.52e-06      N
                     2   0.3285655299   6.91e-10    7.75e-06      N
Iter=34   L=12    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016030  -2.78e-09    9.27e-07      Y
                     2   0.3285655320   2.15e-09    6.23e-06      N
Iter=35   L=13    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016033   2.53e-10    9.26e-07      Y
                     2   0.3285655298  -2.26e-09    4.11e-06      N
Iter=36   L=14    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016026  -6.98e-10    9.41e-07      Y
                     2   0.3285655295  -2.30e-10    3.70e-06      N
Iter=37   L=15    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016027   1.05e-10    9.64e-07      Y
                     2   0.3285655298   2.71e-10    3.50e-06      N
Iter=38   L=16    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016031   4.09e-10    9.77e-07      Y
                     2   0.3285655296  -2.10e-10    3.48e-06      N
Iter=39   L=17    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016034   2.70e-10    8.97e-07      Y
                     2   0.3285655295  -6.61e-11    3.51e-06      N
Iter=40   L=18    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016049   1.54e-09    8.13e-07      Y
                     2   0.3285655298   2.62e-10    3.34e-06      N
Iter=41   L=19    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016050   1.05e-10    7.91e-07      Y
                     2   0.3285655298  -2.41e-11    3.31e-06      N
Iter=42   L=20    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016056   5.33e-10    7.73e-07      Y
                     2   0.3285655297  -9.36e-11    3.26e-06      N
Iter=43   L=21    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016050  -5.70e-10    7.66e-07      Y
                     2   0.3285655297   1.62e-11    3.26e-06      N
Iter=44   L=22    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016043  -7.30e-10    7.68e-07      Y
                     2   0.3285655297  -2.33e-11    3.26e-06      N
Iter=45   L=23    Root    EOM Energy     Delta E   Res. Norm    Conv?
                     1   0.3243016047   4.83e-10    7.73e-07      Y
                     2   0.3285655297  -1.39e-12    3.26e-06      N
Collapsing to only 2 vector(s).

Procedure converged for 1 root(s).

Algorithm failure: No vectors could be added, though not all roots converged!

EOM CCSD R0 for root 0 =   0.00000000000

Final Energetic Summary for Converged Roots of Irrep B1g
                     Excitation Energy              Total Energy
                (eV)     (cm^-1)     (au)             (au)
EOM State 1      8.825    71176.0   0.3243016047  -231.251027700721

Largest components of excited wave function #1:

**Comment by dgasmith** [comment]
Kind of looks like your convergence is getting tight enough that some sort of denominator is getting small enough for instabilities (not sure how this is solved, but alpha/beta in CG for examples). This is probably exacerbated by the very loose integral tolerance. @amjames Any comments?

**Comment by dgasmith** [comment]
According to @amjames much of this code will be rewritten or touched and this particular issue will not be fixed.
