### ISSUE TITLE
Ca not being set properly

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#612]
Okay, onto the next problem.

I want to run a DFT calculation on a system where converging even HF takes SOSCF to work. However, reading in the HF orbitals fails. 
```
molecule {
0 1
symmetry c1
Mn -0.0128264866 -0.0002779912 -0.1091894544
O  -1.1037647823  1.0246639195 -1.2821459116
O  -0.4319309790 -1.5910632792 -1.0423314985
N   0.7243918073  1.6205280457  0.7709992473
N   1.3008767173 -0.9287768925  1.0635839133
C  -1.2886186814  2.2834208702 -1.2181338272
C  -0.7050865946  3.1821062059 -0.3604271375
C   0.3534920334  2.8195308082  0.5207059889
C   0.2177419816 -2.6945497951 -0.9662726987
C   1.2181378357 -3.0250490115 -0.0961995911
C   1.7180430400 -2.1229929449  0.8899899444
C   1.9393113446  1.3525171542  1.5367699106
C   1.8333722479 -0.0604962603  2.1055467704
H   0.8908035853  3.6241374839  1.0039698993
H   2.5024254412 -2.4854165868  1.5399007635
H   2.7858100041  1.4098930461  0.8661311665
H   1.1490336627 -0.0652673733  2.9502674019
H   2.0638511115  2.0769335299  2.3353274192
H   2.7993768711 -0.4085469833  2.4534782102
H  -1.9892347032  2.6686747336 -1.9454961675
H  -0.0986239324 -3.4441353556 -1.6764363233
Cl  1.8821942342  0.3098852687 -1.6599082362
O  -1.1395010178 -0.1703680057  0.9263551082
H  -0.9312248148  4.2251864392 -0.4696082573
H   1.6695378989 -3.9953914470 -0.1633815245
}

# Run SCF, initialize in smaller basis
set basis 6-31G*
set basis_guess 3-21G
set scf_type pk
set soscf true
scf_e, scf_wfn = energy('scf', return_wfn=True)

# Rerun with BP86 to get better density
set scf guess read
scf_e, scf_wfn = energy('bp86', return_wfn=True)
```

outputs in the BP86 part
```
Warning! Guess was READ without Ca set, switching to CORE!
           This option should have been configured at the driver level.

  SCF Guess: Core (One-Electron) Hamiltonian.
```

**Comment by andysim** [comment]
I *think* this'll do it, but my memory can be very bad..

```
scf_e, scf_wfn = energy('bp86', guess_wfn=scf_wfn, return_wfn=True)
```

**Comment by susilehtola** [comment]
Nope, same problem.

**Comment by dgasmith** [comment]
There are a few issues here, first you set `soscf true` which will fail for the `bp86` computation so you would need to switch it off. In addition, `basis_guess` will override `guess read` so your input file should look like:

```
set basis_guess false
set soscf false
set scf guess read
scf_e, scf_wfn = energy('bp86', return_wfn=True)
```

Both SCF taking guess Wavefunctions and the combination of read options all relate to issue #483. Without some discussion there on all of the possible use cases and how these options should interact with each other I probably will not make fundamental changes to how SCF guessing works.

**Comment by susilehtola** [comment]
Oh that's right. But shouldn't psi4 throw an error if both basis_guess and guess read have been set?

**Comment by dgasmith** [comment]
Absolutely, but there are plenty of other holes in the whole SCF read/origination issue, re: #483. I don't really want to get these issues as they crop up, but get a better idea of how to do this from the ground up in the correct way. Please start compiling a list of these issues there.

**Comment by susilehtola** [comment]
OK. Defer to #483.
