### ISSUE TITLE
dmrg requires explicit specification of active space

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#614]
My dmrg calculation where I had specified only restricted_docc and restricted_uocc crashed, because I had not set the active space explicitly.

For consistency's sake with e.g. detci, the dmrg part should be able to calculate the active space from these keywords.

**Comment by dgasmith** [comment]
Hi Susi,
This is a good idea and one that we would like to do. However, it is not currently a priority. I can certainly point out how to do such an operation if you wish. 

In the meantime, I have added this to developer wish list: #402.
