### ISSUE TITLE
MP2 Gradient Incorrect with QMMM charges

### ISSUE THREAD

**Issue by masalim2** [psi4/psi4#618]
The analytic and numerical MP2 gradients disagree when a QMMM charge field is used, while the same calculation runs correctly at the HF level.  [psi4 version 1.0.0]

I found a similar issue which has already been resolved with the RKS gradient: https://github.com/psi4/psi4/issues/184 

My test case is one QM water molecule in the presence of two TIP3P-charge waters.

```
memory 400 mb

molecule water {
0 1
O    -0.167787    1.645761    0.108747
H    0.613411    1.10262    0.113724
H    -0.093821    2.20972    -0.643619
symmetry c1
no_reorient
no_com
}

chgfield = QMMM()

chgfield.extern.addCharge(-0.834, -1.350388,    -0.964879, -0.092208)
chgfield.extern.addCharge(0.417, -1.908991,    -1.211298,  0.626207)
chgfield.extern.addCharge(0.417, -1.263787,    -0.018107, -0.055536)
chgfield.extern.addCharge(-0.834, 1.517569,    -0.667424,    -0.080674)
chgfield.extern.addCharge(0.417, 1.989645,    -1.098799,    0.612047)
chgfield.extern.addCharge(0.417, 0.668397,    -1.091798,   -0.139744)
psi4.set_global_option_python('EXTERN', chgfield.extern)

set basis aug-cc-pvtz
set scf_type df
set freeze_core True

grad_fd = gradient('mp2', molecule=water, dertype=0)
grad_an = gradient('mp2', molecule=water)
compare_matrices(grad_an, grad_fd, 5, "TESTING finite-diff vs. analytic gradient")
```
The identical input file replacing "mp2" with "hf" runs successfully.  It seems strange to me, since as far as I understand the external charges should only modify the core contribution to the Fock matrix.  Is there a possibility that gradient('mp2') somehow fails to include the external potential gradients that are correctly computed in gradient('hf')?

**Comment by dgasmith** [comment]
There may be extra terms in the CPHF equations for MP2 gradients that we are missing. @andysim might know for sure.
