### ISSUE TITLE
Bug in civect.cc

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#621]
Lines 846-847 in detci/civec.cc read
```
            if (CI_Params_->Ms0 && ((int) CI_Params_->S % 2) &&
                (!neg_only)) value -= value;
```
where the `-=` should probably read `=-` as currently the statement is equivalent to `value=0`.

However, we're not sure what this code is supposed to be doing.

**Comment by dgasmith** [comment]
@cdsgroup Can you double check that the above patch would be correct? If so we can go ahead and make this change.

**Comment by loriab** [comment]
@CDSherrill, can you double-check the above?

**Comment by dgasmith** [comment]
@loriab Ha, thanks for the redirect. Ill keep that in mind for the future.
