### ISSUE TITLE
Problems defining mid-bond sets : Bug in inputparser?

### ISSUE THREAD

**Issue by ajmisquitta** [psi4/psi4#626]
Hi chaps,
I've been trying to get Psi4 (1.0.54 Git: Rev {master} 8d4cec3 dirty) to accept user-defined mid-bond sets. To do this I have placed a set of mid-bond definitions in mb-set.gbs and used the heavier rare-gas atoms (Kr, Xe, Rn) to label the mid-bond sets. Using the commands

basis {
   assign aug-cc-pVDZ
   assign Rn  mb-set  # gets the basis set for the ghost Rn atoms from mb-set.gbs
}

Psi4 is able to perform standard (non-DF) MP2 and CC calculations using mid-bond functions. However I have encountered problems getting this to work using the DF variants of these methods.

As I understand it, to get the DF-MP2, DF-CC etc to work I need to do the following:

1. Create a set of auxiliary functions for these mid-bond sets. This I have done (mb-set-ri.gbs)
2. Specify the auxiliary basis set using
    assign <aux basis> df_basis_scf/mp2

The only source of information I was able to find on the latter was at http://www.psicode.org/psi4manual/master/basissets.html#sec-basisuserdefined

Step 2 is where things fall over. First of all, the correct syntax seems to be 
   assign df_basis_scf/mp2  <aux basis>
There seems to be an error on the wiki page shown above. 

This syntax works as it allows me to define a specific auxiliary basis for *all* atoms. If I wish to define a specific aux basis for a particular atom (as needs to be done when using mid-bonds) then the command should be
  assign Rn df_basis_scf  mb-set-ri
This fails in inputparser.py with the following error:

Traceback (most recent call last):
  File "/home/alston/Psi4/psi4conda/share/psi4/python/inputparser.py", line 734, in process_input
    temp = re.sub(basis_block, process_basis_block, temp)
  File "/home/alston/Psi4/psi4conda/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/home/alston/Psi4/psi4conda/share/psi4/python/inputparser.py", line 357, in process_basis_block
    raise TestComparisonError(message)
p4util.exceptions.TestComparisonError: Conflicting basis set specification: assign lines present but shells have no [basname] label.

It seems like the line "assign Rn df_basis_scf mb-set-ri" cannot be correctly parsed by inputparser.py. It seems to think this line is part of the basis set specification. 

The complete Psi4 command file for this calculation is:
[Ar2_input.txt](https://github.com/psi4/psi4/files/787318/Ar2_input.txt)

And the two basis set files are here:
[mb-set.txt](https://github.com/psi4/psi4/files/787319/mb-set.txt)
[mb-set-ri.txt](https://github.com/psi4/psi4/files/787320/mb-set-ri.txt)

I can get this to work by including the aux basis for "Rn" in one of the fitting basis files that Psi4 would normally read. But this is not ideal and it would be great to be able to specify the fitting basis in the input file using the ''assign'' command. How can this be fixed?

Additionally, the information on the wiki dealing with user-defined basis sets may need to be corrected and augmented. 

Thanks a lot!
Alston

**Comment by loriab** [comment]
Well, you've hit upon the primary remaining reason Psi4 isn't 1.1: tweaks and documentation of user-defined basis sets (psi4/psi4#43). The good news is that doing what you want is fairly easy

```
basis {
   assign aug-cc-pVDZ
   assign Rn  mb-set
}

df_basis_scf {
   assign aug-cc-pVDZ-jkfit
   assign Rn mb-set-ri
}

df_basis_cc {
   assign aug-cc-pVDZ-RI
   assign Rn mb-set-ri
}
```

If you leave your `mb-set.gbs` and `mb-set-ri.gbs` alongside the input file, The parser will catch them. But you can also add directories to the envvar `PSIPATH` for it to look for basis set files. Please let me know if basis sets continue to give problems or confusion.

**Comment by ajmisquitta** [comment]
Thanks a million, Lori! That worked. Why not put it up on the wiki? Any chance of a community wiki?

**Comment by loriab** [comment]
There is a [forum](http://forum.psicode.org/). The [wiki itself](https://github.com/psi4/psi4/wiki) is newly defunct and needs some labels indicating this. Everything relevant to users (as opposed to some limited developer info that's still good) is now in the [build docs](http://psicode.org/psi4manual/master/build_faq.html). The docs themselves are actually user editable if you care to – there's a pencil in the upper left of the page (unless it's an autogenerated page like for options) that lets one edit, then guides into submitting the changes for review.

You're absolutely right that this should be documented somewhere – it's on my todo list for Psi4 1.1. I'm sorry for your trouble.

**Comment by loriab** [comment]
By the way, @ajmisquitta, I noticed you have a fork of psi4 from last summer. In October we re-wrote our git history to reduce the repository size by 90%. This makes pre-history-rewrite and post-history-rewrite repositories unreconcilable.

If this is the source you are compiling from and you want to continue with psi4 1.0 era code, stick with your repository. Likewise if you have local development associated with your psi4 fork. Otherwise, I strongly recommend deleting your repository and re-forking. This will give you access to 1.1 era code and can interact with the main psi4/psi4 repo. (It will cut off access to building 1.0.) There's some significant build changes with 1.1, but a lot of [good features](https://github.com/psi4/psi4/issues/485), too.

**Comment by gruckion** [comment]
Hello @loriab, I have taken what you and @ajmisquitta has said and applied it to an argon dimer which worked out fine. However when attempting to apply this to a water dimer I get the following error.

`QcdbException BasisSetNotFound: BasisSet::construct: Unable to find a basis set for atom 4 for role RIFIT among:
  Shell Entries: ['RN']
  Basis Sets: ['def2-qzvpp-ri']
  File Path: , /home/s.rayner/psi4conda/share/psi4/basis
  Input Blocks: 



Traceback (most recent call last):
  File "/home/s.rayner/psi4conda/share/psi4/python/qcdb/libmintsbasisset.py", line 599, in pyconstruct
    bs, msg = BasisSet.construct(parser, mol, fitrole, None if fitrole == 'BASIS' else fitrole, basstrings[fitrole])
  File "/home/s.rayner/psi4conda/share/psi4/python/qcdb/libmintsbasisset.py", line 748, in construct
    (at + 1, role, text2))
qcdb.exceptions.BasisSetNotFound: BasisSet::construct: Unable to find a basis set for atom 4 for role RIFIT among:
  Shell Entries: ['RN']
  Basis Sets: ['def2-qzvpp-ri']
  File Path: , /home/s.rayner/psi4conda/share/psi4/basis
  Input Blocks: 
`

The input.dat as the following [http://pastebin.com/6kRJzc9e](url). Any help on this issue would be deeply appreciated.

**Comment by loriab** [comment]
@gruckion, you're running `energy('mp2'`, so you'll need a `df_basis_mp2` block identical to the `df_basis_cc` one. With `df_basis_scf`, `df_basis_mp2`, and `df_basis_cc`, that should cover most everything.

**Comment by gruckion** [comment]
Oh dear, apologies for over looking something so simple. Thank you for getting back to me so swiftly. Let me know if there is a way to repay the favour.

All the best,
Stephen

**Comment by loriab** [comment]
No problem, it's nice to get questions I can answer easily. And your experience reminds me that I should print which keyword the basis set search is failing on, so thanks for helping out the manual.

I'm going to close this issue as answered, but feel free to reopen it or another if you've further problems or questions.
