### ISSUE TITLE
Possible g94 basis set format incompatibility

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#628]
Trying to run the calculation in http://forum.psicode.org/t/problem-with-detci-and-7z-basis-set/423, I noticed that psi4 is erroneously using the buggy convention used by the basis set exchange where angular momentum shells are S, P, D, F, G, H, I, K, ... However, in the g94 basis set format l=7 is not K, but J.

Namely, back when I was allowed to use Gaussian, I got the following info from their help:
```
Another issue which arises with these high angular momentum 
functions is an inconsistency in how they are labeled.  Gaussian
labels the L=7 functions with the letter j rather than the letter
k.  Other authors omit j so that l=7 is k.  So if your input has

K n 1.0
...

you are actually getting an L=8 basis set.  Change your input to

L=7 n 1.0

instead.
```

**Comment by jturney** [comment]
I just followed the ordering from libint. Seeing that we match the basis set exchange I'm inclined to not change it.

**Comment by susilehtola** [comment]
In any case it should be documented..

Also, the L=l format doesn't seem to be working.

**Comment by susilehtola** [comment]
The L=l format parsing can be added simply by changing libmintsbasissetparser.py to
```
                            if len(shell_type) == 1 or len(shell_type)>2:
                                if(len(shell_type) == 1):
                                    # AM defined as character                                                                                                                                 
                                    am = shell_to_am[shell_type[0]]
                                else:
                                    # AM defined explicitly with L=l                                                                                                                          
                                    if(shell_type[0:2].lower()!="l="):
                                        raise ValidationError("""Gaussian94BasisSetParser::parse: Invalid shell definition: line %d: %s""" % (lineno, line))
                                    am = int(shell_type[2:])

```

but in addition the shell regexp needs to be adapted to also accept the other format :S

**Comment by loriab** [comment]
Seems Psi4 and EMSL and libint are internally consistent, so the issue is to accept `.gbs` files that are truly Gaussian-style in AM labeling, not just Gaussian-style in format. Do you happen to know, @susilehtola, if G94 (a) does not skip any letters, such that EMSL and G94 are inconsistent for all AM >=7 or (b) skips a different letter so that EMSL and G94 are inconsistent only for AM==7? It sounds like (a), but I want to be sure. 

I was only faintly aware that there was an "L=l" gbs format. Found [this](http://www.ccl.net/chemistry/resources/messages/1996/09/12.004-dir/) on it, so will investigate, thanks.

**Comment by susilehtola** [comment]
AFAIK libint doesn't use AM characters anyow...

But yes, G94 doesn't skip letters, as was pointed out above in the email from their support.
