### ISSUE TITLE
Build error with gcc 7.0.1

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#631]
My pybind11 package was accepted in Fedora, so I started updating the psi4 package (which was at rc1!). It built fine on the released versions, but failed in the development version that has the newest GCC.

The error(s) I get is

```
cd /builddir/build/BUILD/psi4-926879e243ce44dcc0ecfe7cda680a01383982fd/objdir-x86_64-redhat-linux-gnu/psi4-core-prefix/src/psi4-core-build/src/psi4/libpsio && /usr/bin/g++    -I/builddir/build/BUILD/psi4-926879e243ce44dcc0ecfe7cda680a01383982fd/psi4/include -I/builddir/build/BUILD/psi4-926879e243ce44dcc0ecfe7cda680a01383982fd/psi4/src -isystem /usr/include/python3.6m  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -fopenmp -DUSING_CheMPS2 -O2 -DNDEBUG -fPIC   -std=c++11 -std=gnu++11 -o CMakeFiles/psio.dir/aio_handler.cc.o -c /builddir/build/BUILD/psi4-926879e243ce44dcc0ecfe7cda680a01383982fd/psi4/src/psi4/libpsio/aio_handler.cc
/builddir/build/BUILD/psi4-926879e243ce44dcc0ecfe7cda680a01383982fd/psi4/src/psi4/libpsio/aio_handler.cc: In member function 'long unsigned int psi::AIOHandler::read(unsigned int, const char*, char*, psi::ULI, psi::psio_address, psi::psio_address*)':
/builddir/build/BUILD/psi4-926879e243ce44dcc0ecfe7cda680a01383982fd/psi4/src/psi4/libpsio/aio_handler.cc:91:48: error: 'bind' is not a member of 'std'
   thread_ = std::make_shared<std::thread>(std::bind(&AIOHandler::call_aio,this));
                                                ^~~~
/builddir/build/BUILD/psi4-926879e243ce44dcc0ecfe7cda680a01383982fd/psi4/src/psi4/libpsio/aio_handler.cc:91:48: note: suggested alternative: 'find'
   thread_ = std::make_shared<std::thread>(std::bind(&AIOHandler::call_aio,this));
                                                ^~~~
                                                find
```

Note that I've defined
```
-DCUSTOM_C_FLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -std=c11 -DNDEBUG' '-DCUSTOM_CXX_FLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -std=c++11 -DNDEBUG'
```
which already includes the C++11 standard, but the build system seems to append this with -std=gnu++11 which is probably the reason why the build is broken. It's funny though, that the same flags work in earlier gcc!

**Comment by susilehtola** [comment]
Broken build
https://kojipkgs.fedoraproject.org//work/tasks/8247/18108247/build.log

A succesful build
https://kojipkgs.fedoraproject.org//packages/psi4/1.0/1.926879egit.fc25/data/logs/x86_64/build.log

**Comment by jturney** [comment]
I wonder if it's because ```#include <functional>``` isn't explicitly listed in ```aio_handler.cc``` or ```aiohandler.h```?

**Comment by loriab** [comment]
On the `-std=gnu++11`, we're scheduled to suppress that soon with [this line](https://github.com/psi4/psi4/pull/627/files#diff-af3b638bc2a3e6c650974192a53c7291R176), as the issue came up with cmake >=3.6 and Intel compilers.

I see what you mean about return type of [`std::bind`](http://en.cppreference.com/w/cpp/utility/functional/bind) being deprecated in c++17.

**Comment by susilehtola** [comment]
Well, I updated to the newest git which includes the patch that switches from -std=gnu++11 to -std=c++11 but the build still fails with the same error about `std::bind`.

**Comment by susilehtola** [comment]
I think @jturney is right, might be a header issue.

**Comment by dgasmith** [comment]
I think this was solved with #633. Feel free to reopen if this is not true.

**Comment by loriab** [comment]
Hi @susilehtola, I was looking around the Fedora packaging site to see if there was a download counter. Didn't find one but did notice a few details from your build scripts that could be updated:

* http://pkgs.fedoraproject.org/cgit/rpms/psi4.git/tree/psi4.spec#n45 actually need Py >= 2.7, as I'm not holding back from dictionary comprehensions
* http://pkgs.fedoraproject.org/cgit/rpms/psi4.git/tree/psi4.spec#n19 more simply, `psi4/psi4`, though github re-directs
* http://pkgs.fedoraproject.org/cgit/rpms/psi4.git/tree/psi4.spec#n107 It's on by default anyway, so no change, but wrong variable https://github.com/psi4/psi4/blob/master/CMakeLists.txt#L99
* http://pkgs.fedoraproject.org/cgit/rpms/psi4.git/tree/psi4.spec#n109 not sure if this is still working. May need to be `-DLAPACK_LIBRARIES=...`

Is there actually a monitor that you know of for Fedora package downloads? We like to track them for grant reviews.

**Comment by susilehtola** [comment]
@dgasmith thanks, I'm still road tripping and haven't opened my computer in a few days. Getting back home to work tomorrow evening.

@loriab okay, I'll have a look later (ping me since I'll probably forget). And no, there's no way to track package downloads, because they're mirrored to n>>>1 locations anyhow.
