### ISSUE TITLE
Inconsistency in numpy wrappers

### ISSUE THREAD

**Issue by rmcgibbo** [psi4/psi4#639]
When trying to track down some nondeterminstic behavior, I encountered the following oddity.

```
import numpy as np

molecule {
0 1
C1 0.00000000 0.00000000 0.00000000
H2 0.49111719 0.98252240 -0.05876775
H3 -0.72033644 -0.10038934 -0.82524990
H4 -0.52826663 -0.08928047 0.96070982
H5 0.75766207 -0.79379696 -0.07638440
}

set {
  basis cc-pvdz
}

e_scf, wfn = energy('hf', return_wfn=True)


print(wfn.occupation_a().np)
print(np.asarray(wfn.occupation_a()))
```

Somewhat surprisingly, this is the output I see:

```
[  0.00000000e+000   0.00000000e+000   0.00000000e+000  -7.63277803e+283
   6.91698601e-310   6.91698623e-310   0.00000000e+000   0.00000000e+000
   0.00000000e+000   0.00000000e+000   0.00000000e+000   0.00000000e+000
   1.65169957e-220   6.91698602e-310   6.91697627e-310  -3.39981117e-158
   6.91697639e-310   6.91696828e-310   5.41141341e-041   6.91697626e-310
   6.91697724e-310   0.00000000e+000   0.00000000e+000   0.00000000e+000
  -3.67112871e-197   6.91698601e-310   6.91696828e-310   2.99382801e+052
   6.91697697e-310   6.91697723e-310   0.00000000e+000   0.00000000e+000
   0.00000000e+000   4.42201243e+096]
[ 1.  1.  1.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
```

i.e., something funky is going on with `.np`.

**Comment by dgasmith** [comment]
Yes, please see the warning at the bottom of the paragraph [here](http://psicode.org/psi4manual/master/numpy.html#numpy-views). `occupation_a` always returns a new Vector and `.np` will return a view to that vector. As the new Vector no longer has a reference it is garbage collected and you get random data. Any attempts to fix this have led to cyclic references and nothing being garbage collected. The following will also work:

```
occ = wfn.occupation_a()
print(occ.np)
```

**Comment by rmcgibbo** [comment]
Hmm, okay. Thanks.

**Comment by dgasmith** [comment]
@rmcgibbo Do you have suggestions on how this could be made more obvious either in the code or docs? It seems to crop up every now and then.

**Comment by rmcgibbo** [comment]
I'm not exactly sure.

Obviously it should be possible to reference count the views properly, but I guess that probably requires a lot of pretty subtle work that you've already wasted a lot of hours on.

Otherwise, a good place to add that warning might be on the docstring for the property and the docstring for the class. That way if you look at the `help()` from an interactive shell, you'll see the warning.
