### ISSUE TITLE
Linking tempfiles

### ISSUE THREAD

**Issue by rmcgibbo** [psi4/psi4#645]
`core.IO.change_file_namespace` is very nice for reusing some of the integral files between namespaces. It would be useful to have a similar function that would (hard)link one file to another.

Also, `currently core.IO.change_file_namespace` returns `None` regardless of whether the move operation was successful or not. It might be better for it to return a `bool` indicating whether the file was successfully moved (for example if you want to make sure you're not trying to move a nonexistant file).

**Comment by dgasmith** [comment]
Thanks! I added this to the Developer Wishlist. As we have general plans to overhaul the filesystem capabilities (to something like HDF5 or BDb) it may be a bit before we get around to it.
