### ISSUE TITLE
Saving SCF npy files in a different directory

### ISSUE THREAD

**Issue by rmcgibbo** [psi4/psi4#646]
It's convenient that the orbitals are saved in [`scf_helper`](https://github.com/psi4/psi4/blob/4e8c34a1744559f7f7714c52338f3f3f430766a5/psi4/driver/procrouting/proc.py#L1361-L1381), but I think it would be convenient to be able to control the directory.

Obviously I could `cd` the whole process, but that feels a little clumsy. Potentially adding an option to scf_helper to control the directory, or adding a `set_writer_file_directory()` to  [`get_writer_file_prefix.cc`](https://github.com/psi4/psi4/blob/40e4680d55f3f342f0fc50f8146873cb3eed318d/psi4/src/psi4/libmints/get_writer_file_prefix.cc) would be cleaner (that defaults to `.`).

**Comment by dgasmith** [comment]
We have discussed this previous, but didnt find a clean way to do it. In 1.2 we have the ability to write/read Wavefunctions from disk. Would it be sufficient if you could do the following:

```
scf_e, scf_wfn = psi4.energy("SCF/cc-pVDZ", return_wfn=True)
scf_wfn.to_file("my_wave.npz")
```

**Comment by rmcgibbo** [comment]
That would be fine, if it's an alternative to the current saving of the orbitals to disk in the current directory. My concern was mostly just with not wanting to pollute the current working directory during the run.

**Comment by dgasmith** [comment]
Oh, this should have been changed at some point to correctly drop these to PSI_SCRATCH. However, it doesn't look like this is present in master. I wonder if this was overwritten at some point... ill make a patch for this sometime today.
