### ISSUE TITLE
Can no longer compile

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#648]
Hi,

it seems I'm no longer able to compile the trunk. The error I get is
```
CMake Error at src/CMakeLists.txt:90 (list):
  list sub-command FIND requires three arguments.


CMake Error at src/CMakeLists.txt:97 (if):
  if given arguments:

    "STREQUAL" "/home/work/psi4/psi4/objdir/stage/home/work/psi4/install/lib"

  Unknown arguments specified


-- Configuring incomplete, errors occurred!
```

and I get it consistently even for a clean checkout and empty installation directory.  The command I'm using is
```
cmake -DENABLE_AUTO_BLAS=OFF -DENABLE_AUTO_LAPACK=OFF -DLAPACK_LIBRARIES="-lopenblaso" -DENABLE_AMBIT=OFF -DENABLE_CheMPS2=ON -DENABLE_dkh=ON -DENABLE_PCMSolver=OFF -DCMAKE_INSTALL_PREFIX=/home/work/psi4/install -DCMAKE_AR="/usr/bin/gcc-ar" -DCMAKE_RANLIB="/usr/bin/gcc-ranlib" -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
```

**Comment by loriab** [comment]
Hard to say without printing out a lot of stuff. Is `_ald` getting formed correctly in [this line](https://github.com/psi4/psi4/blob/master/psi4/src/CMakeLists.txt#L76)? All of [this](https://github.com/psi4/psi4/blob/master/psi4/src/CMakeLists.txt#L75-L105) is just to control the rpath, so if you're ok with using `LD_LIBRARY_PATH` instead, can comment it all out. Haven't heard other reports of that code giving trouble.

**Comment by susilehtola** [comment]
Adding printouts
```
foreach(_al ${_addons})
  get_filename_component(_ald ${_al} DIRECTORY)
  message("al is \"${_al}\"")
  message("ald is \"${_ald}\"")
```
yields the following output
```
al is "-lopenblaso"
ald is ""
```

so I guess you need to add a check if ald is an empty variable..
