### ISSUE TITLE
NameError: name 'cp' is not defined

### ISSUE THREAD

**Issue by rilaklin** [psi4/psi4#653]
Hi all, 
I followed the tutorial to install the latest PSI4. However, when I used the cp command, it would show "name 'cp' is not defined". (if I use other function, such as energy, then there is no this kind of issue). could you help me solve this problem? Thank you.

**Comment by loriab** [comment]
Sounds like a version mismatch. The `cp()` function was deprecated sometime last spring in favor of a `bsse_type='cp'` argument to `energy()`, as shown in [this section of the tutorial](http://psicode.org/psi4manual/master/tutorial.html#potential-surface-scans-and-counterpoise-correction-made-easy-with-psithon). It sounds like you've got a new version of Psi4 (latest ones [here](https://github.com/psi4/psi4/issues/466#issuecomment-272589229) but an old version of the tutorial. Use the latest versions of both and all should be well. If not, tell me more about what you're running (`psi4 --version`).

**Comment by rilaklin** [comment]
Yes, I could run that successfully with the new command. Thanks for your prompt reply.

**Comment by loriab** [comment]
Glad it's working now.
