### ISSUE TITLE
preloading of external programs

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#656]
Hi,

Anyone noticed that programs like _gcp_ and _xcfour_ are getting loaded when psi4 is starting? Or is it just me? I only noticed because psi4 will stop/crash if e.g. xfcour does not find all libraries (mpi, mkl, etc.). gcp will print an error about its missing input file and be "defunc" in my bash.

Note that it happens even when none of the programs will actually be used according to the input. I am at a loss what to look at in my psi4 installation.

version: 1.1a2.dev309, gnu+mkl build

**Comment by jturney** [comment]
Someone else recently brought this to my attention, too. They were getting empty mrcc input files being generated when they weren't requesting any mrcc methods. I'll take a look and see what I can figure out.

**Comment by loriab** [comment]
I've seen this, though it hasn't been a problem. Anyone recall whether this has always (last few months) been the case or only recently? If the latter, maybe the [pytest checks](https://github.com/psi4/psi4/blob/master/tests/pytest/test_addons.py#L7-L20) are involved.

**Comment by jturney** [comment]
Last week was the first I had heard about it.

**Comment by loriab** [comment]
See if commenting out [these](https://github.com/psi4/psi4/blob/master/psi4/extras.py#L109-L112) makes it go away.

**Comment by hokru** [comment]
Yes @loriab, that fixes it. I see the program is actually being called to probe the exist code. I guess I get to see the stderr output.

I once ran into a similar question (test if a binary exist) and saved this answer: http://stackoverflow.com/a/377028 (Though in the end I just ignored it and accepted a crashing script..)

**Comment by loriab** [comment]
Is it enough to suppress the can't-find-library, etc. output from when faulty externals preload? Or is their failure actually crashing the psi4 run? I like the `subprocess` "which" b/c it's closer to what the real run does and I can modify the path, but I can switch if need be.

**Comment by hokru** [comment]
psi4 does not crash. I was at first under the impression it did because of all the errors that got thrown at me. If the stderr from the subprocess is hidden from the user (i guess it's stderr) it should be all good.

**Comment by loriab** [comment]
Give the newly committed fix a try, then if that's not satisfactory, reopen this. `psi4 --test` is what that preloading is actually affecting, so pass along any unexpected results of that. (Though I'm not sure if an error caused by a present but broken add-on should be skipped or failed.)
