### ISSUE TITLE
unnecessary(?) explicit linking of libpthread and co 

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#657]
Hi,

I am wondering why these are linked explicitly by cmake alongside the intel mkl*?:
/usr/lib/x86_64-linux-gnu/libpthread.so
/usr/lib/x86_64-linux-gnu/libm.so
/usr/lib/x86_64-linux-gnu/libdl.so

If I want to use a local gcc installation, I have to delete them from the CMakeCache.txt or else I will
have problems with missing symbols in core.so later on.

E.g. If the above libs are linked, then I end up with libstdc++.so and libgomp from /usr/lib/x86_64-linux-gnu/ instead of my local install (/home/kruse/gcc-4.9.4/lib64/). 

cheers

[*] MKL2017

**Comment by loriab** [comment]
They're linked b/c the Intel link-line advisor specifies them and b/c we do some manipulation of static/dynamic detection for the binary. I don't swear it's the best way, but it hasn't been causing problems.

Your `/home/kruse/gcc-4.9.4/bin/gcc` is what's active at build time? I'm surprised it's not picking up that `/home/kruse/gcc-4.9.4/lib64` libraries are being used, then preserving them in `rpath`. You may want to uncomment [this](https://github.com/psi4/psi4/blob/master/psi4/src/CMakeLists.txt#L94) and its friends to see what's going on with rpath.

**Comment by hokru** [comment]
My issue here seems specific to our cluster. I have no problems on my workstation or our second cluster.

Maybe the old (gcc 4.7.2) on the cluster makes troubles together with the local installation of gcc 4.9.4. But I have no real desire to dig into this...

Btw, uncommenting these cmake debug messages did produce no output at all (or I did something wrong)

**Comment by loriab** [comment]
Are you still concerned about this issue, @hokru? It sounds sporadic, and I'm not sure how to adjust the CMake for it.

**Comment by hokru** [comment]
I pulled the latest version onto the problematic cluster just now and made a fresh compilation. The issue seems to have disappeared, I have no problems running psi4. 

Closing this. Thanks @loriab.

**Comment by loriab** [comment]
Huh, I don't know what could have changed to solve it, but good!
