### ISSUE TITLE
parallel cfour with psi4

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#661]
(I feel a bit bad for opening so many issues..but here we go..)
Hi,

In order to make parallel xcfour work with psi4, I needed to remove the `env` parameter the subprocess: 
`retcode = subprocess.Popen([cfour_executable], bufsize=0,stdout=subprocess.PIPE)`
(compare with [original](https://github.com/psi4/psi4/blob/master/psi4/driver/procrouting/interface_cfour.py#L213))

Otherwise xinitenv (from cfour) would exist with exit code 265 and then psi4 is upset by the non-existing output.

Maybe is has to do with our cfour installation using "bash" and not "sh" in the various cfour init scripts? But env does not change the shell type, so I am confused.

**Comment by loriab** [comment]
No problem on all the issues. Glad you're testing the code.

The `env=lenv` is basically to fulfill the "addons may be in PSIPATH or PATH" promise and to remove envvar noise from the execution environment. [This](https://github.com/psi4/psi4/blob/master/psi4/driver/procrouting/interface_cfour.py#L142-L148) is pretty much it. My first thought is that there might be some envvar you have set that is important for `xcfour` to run correctly but is getting cut from `lenv`. Maybe `printenv` and see if anything looks likely? We can certainly pass more through if warranted.

**Comment by hokru** [comment]
ah ok, I remember that cfour needs an environmental variable to figure out the number of mpi threads. At the configure step of the source code one sets something like:
`configure [...] --with-mpirun=mpirun -np ${CFOUR_NUM_CORES}`

Not sure if this is just our configuration or if `CFOUR_NUM_CORES` is the default name described in some installation documentation.

I see that `OMP_NUM_THREADS` is handled correctly with `env=lenv`, though I don't see it is being added to `lenv`.

**Comment by loriab** [comment]
From the cfour email chain today, it sounds like `CFOUR_NUM_CORES` is widespread. I'll add it to the whitelisted envvars.

> export CFOUR_NUM_CORES=20
>
> From my experience I can say that using more than 4 processors will not increase performance and even sometimes the worse. Of course that depends also from the kind of computation (optimization, frequency, …).
> 
> Best regards,
> Alberto

**Comment by hokru** [comment]
thank you.

with SSDs 8 processors seem to do well enough with the tremendous amount of I/O in CCSD(T) gradients.

**Comment by loriab** [comment]
I think this was resolved by psi4/psi4#672
