### ISSUE TITLE
py36 + extern crash

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#666]
In Python 3.6, the extern object (keyword set to a Python object) is being double freed at end of execution, leading to a crash. Builds fine, runs fine, unless extern set, so only shows up for test cases extern1 and extern2. These have been conditionally and temporarily removed from test suite until this fixed. Can force a fix by clearing options before end of file, `psi4.core.clean_options()`.

This is a reference counting issue and will _not_ be fixed for 1.1.

**Comment by dgasmith** [comment]
Can we throw the clean into a `atext` option for now?

**Comment by loriab** [comment]
Good idea, done. Will show up in the simint PR.

**Comment by dgasmith** [comment]
Moved this to the 1.2 milestones project.
