### ISSUE TITLE
using a non-global scratch dir path causes problems with (at least) cfour

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#669]
I suspect there is something problematic in python with the use of the bash dot to specify a directory, or the use of a non-global path location. I know it is problematic with psi4+cfour.

These will **not** work for me for cfour optimizations:
`psi4 -s . opt.in` [here the gradient is not parsed]
`psi4 -s ./localdir opt.in` [does not find the (correctly created) directory]

This works:
`psi4 -s /scratch/ opt.in`

If you want to force users to always use a global path, I would be fine with it.

[ Psi4 1.1a2.dev375 (af8133b)]

**Comment by dgasmith** [comment]
Looks like we missed a `os.path.abspath` somewhere. This should be able to be patched up, ill dig through the code when I get a chance.
