### ISSUE TITLE
gcc + mkl2017 threading problems

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#671]
This is not a psi4 issue, but users are affected by it.

Something is off with the new single dynamic library from intel and gcc + mkl2017 building.

Essentially, sometimes you can get over subscription (nested OpenMP+MKL threading), and sometimes threading does not work at all.

Through trial and error I found the following env variables set the expected behavior:

```
export MKL_THREADING_LAYER=GNU
export MKL_INTERFACE_LAYER=GNU
export OMP_NESTED="FALSE"  <-- supposed to be libgomp default, but is not?
```

Maybe not all 3 are needed, or there is some other flag. I was just happy to get the proper behavior.

I tested gcc 4.9.4/6.3 and MKL2017 and MKL2017.2

**Comment by dgasmith** [comment]
Hmm, I do think we rely on `export OMP_NESTED="FALSE` in some places depending on the scheme involved. Would there be a good place to add this to the docs?

**Comment by loriab** [comment]
[Here](http://psicode.org/psi4manual/master/external.html#environment-variables) maybe (compiled)? Can edit it directly with the pencil icon.

**Comment by dgasmith** [comment]
@hokru Still hitting these issues?

**Comment by hokru** [comment]
I don't think I do. Not using MKL2017 anymore, though. Can be closed.
