### ISSUE TITLE
DFT_SPHERICAL_POINTS can take any value: 

### ISSUE THREAD

**Issue by lazaroid** [psi4/psi4#673]
Whilst digging around for why I was seeing inconsistent numbers of grid points on different machines, I've spotted what has to be a bug. Currently, DFT_SPHERICAL_POINTS can be set to any value, rather than just [a Lebedev Points number](http://psicode.org/psi4manual/master/dft.html#table-lebedevorder). If a non Lebdev number is used, then the grid is, essentially, undefined. The correct behaviour is to print the table of available values and throw an exception.

In psi4/psi4/src/psi4/libfock/cubature.cc, DFTGrid::buildGridFromOptions() calls LebedevGridMgr::findOrderByNPoints(opt.nangpts) (line 3968) which returns either the grid order or -1 if opt.nangpts doesn't match one of the defined grid sizes.

`    if (LebedevGridMgr::findOrderByNPoints(opt.nangpts) < -1) {
        LebedevGridMgr::PrintHelp(); // Tell what the admissible values are.
        throw PSIEXCEPTION("Invalid number of spherical points (not a Lebedev number)");
    }
`

The current check at line 3968 for a suitable value for DFT_SPHERICAL_POINTS is "retval < -1". Surely this should be either "retval == -1" or "retval < 0".

Currently, the test is false even when a non-Lebdev number has been chosen:
"set dft_spherical_points = 110" works as expected; "set dft_spherical_points = 109" (or any non-Lebdev number) gives a stupidly small grid.

**Comment by dgasmith** [comment]
Hmm, looks like Lebedev number's are seared into our minds which is probably not a good assumption. I agree that is the issue, could you submit a PR with a fix?

**Comment by lazaroid** [comment]
I must admit, I was a bit surprised by the effect of changing the value of dft_spherical_points by 1! Undefined behaviour is never good!

I've never submitted a pull request before but it's something i should learn to do. Are there any simple tutorials on how to do this? Should I fork my own version and do a PR from that?

I'll see if I can work it out and submit one shortly...

**Comment by loriab** [comment]
Sure, see if [this guide](http://psicode.org/psi4manual/master/build_obtaining.html#faq-githubworkflow) helps. You'll probably only need the first of the two slides. And we're glad to consult. Thanks for noticing this problem.

**Comment by lazaroid** [comment]
Thanks for the link: I did have a quick look for something like that but completely failed to! I think I worked it out (before you posted the link!). :-)

**Comment by loriab** [comment]
Fixed by psi4/psi4#674
