### ISSUE TITLE
FYI: Psi4 license change

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#688]
Since Psi4:
  * is primarily a shared library / Python module (to C++/Py folks, respectively) rather than an executable (`bin/psi4` is light script loading Python module);
  * is not necessarily at the top of the call stack, and we've heard from projects who would like to import us;
  * is benefiting from the non-attaching and permissive licenses of numerous external projects to supplement Psi4's capabilities, and we want to return the favor,

**we plan to change our license from GPL-2.0+ to LGPL-3.0+, effective by the the 1.1 release.**

EDIT: now targeting LGPL-3.0, not +, with PR psi4/psi4#690

The current and historical core developers have signed off on this. The historical peripheral developers are discussing this without any initial objections. We now want to get feedback from the GitHub contributor, user, and packaging community (or anyone not in e-mail communication with the core developers). So please reply with any concerns, constraints, preferences, etc.

##### Dependencies licensing situation
  * required library dependencies (current & anticipated): PSFL, LGPL-3.0+, BSD-3-Clause-LBNL, BSD-3-Clause 
  * optional library dependencies: BSD-2-Clause, BSD-3-Clause, GPL-2.0+, LGPL-3.0+
  * optional executable dependencies: GPL-1.0+, Custom
  * Psi4 plugins: GPL-2.0+, GPL-3.0+
  * conda-wise, we'll build an alternate conda package that doesn't link any GPL libraries or plugins

##### Queries
  * Psi4 is a Python module and hence a dynamic library. I don't know right off how to even build a `psi4.a`. With that in mind, does anyone care about license terms for static linking?
  * Any concrete problems that would be solved by a permissive license instead of LGPL?
  * Anyone care about sublicensing?

**Comment by j3mdamas** [comment]
Is there a release date for 1.1? :)

Cc @mj-harvey

**Comment by loriab** [comment]
Thanks, @j3mdamas, I had meant to cc mj-harvey and @susilehtola and forgot.

Target release is probably our regional QC conference ~May 18. We're currently sending back responses to reviewers of the accompanying paper. Todo items are: building Mac plugins from conda distribution, updating some add-on integrations we promised in the paper, paper, relicensing.

**Comment by susilehtola** [comment]
Well, I'm okay with LGPL. But I'm not 100% sure that'd be the right license for psi4, ref.
  https://www.gnu.org/licenses/why-not-lgpl.en.html
What are the other projects that would *need* psi4 to be LGPL instead of GPL?

**Comment by susilehtola** [comment]
Also, I just checked that pyscf, which is probably the biggest competitor to psi4, is BSD licensed. Which is going too far, IMNSHO.

**Comment by loriab** [comment]
By my understanding, any project that
* isn't GPL
* uses psi4 upstream
* interacts with psi4 pythonically/programatically rather than through running psi4 as an executable and parsing text output

would need Psi4 as LGPL over GPL if it didn't want to become forcibly GPL'd itself.

**Comment by j3mdamas** [comment]
Thanks for the feedback, @loriab!

LGPL is good from my perspective.

**Comment by susilehtola** [comment]
Why is there still a GPLv3 in the repo? COPYING should be replaced with COPYING.LESSER

**Comment by loriab** [comment]
We followed 
>>> If you are releasing your program under the LGPL, you should also include the text version of the LGPL, usually in a file called COPYING.LESSER. Please note that, since the LGPL is a set of additional permissions on top of the GPL, it's important to include both licenses so users have all the materials they need to understand their rights.

from https://www.gnu.org/licenses/gpl-howto.en.html and figured that if the GitHub licenser picked it up alright, add was good.

**Comment by andysim** [comment]
Not according to [this](https://www.gnu.org/licenses/gpl-howto.en.html)
"You should also include a copy of the license itself somewhere in the distribution of your program. All programs, whether they are released under the GPL or LGPL, should include the text version of the GPL. In GNU programs the license is usually in a file called COPYING.

If you are releasing your program under the LGPL, you should also include the text version of the LGPL, usually in a file called COPYING.LESSER. Please note that, since the LGPL is a set of additional permissions on top of the GPL, it's important to include both licenses so users have all the materials they need to understand their rights."

**Comment by andysim** [comment]
Ah, @loriab beat me to the reply.  Must improve typing skills!

**Comment by susilehtola** [comment]
I stand corrected.
