### ISSUE TITLE
Libint1 relicensing

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#693]
Either apply changes from evaleev/libint v1 to psi4/libint _or_ make psi4/libint a buildsystem wrapper around evaleev/libint v1 like https://github.com/python-cmake-buildsystem/python-cmake-buildsystem .

Net effect is the Libint we call must be LGPL-3.0, not GPL-2.0+ as at present.

**Comment by susilehtola** [comment]
Good, I was wondering about this!

But, libint is still GPL, right?
https://github.com/evaleev/libint/blob/v1/LICENSE

**Comment by susilehtola** [comment]
Or yeah, I guess the generator is GPL and the generated library is LGPL. But that's not so clear in v1.

**Comment by loriab** [comment]
@evaleev is kindly moving v2 from GPL/LGPL-2.1+ to GPL/LGPL-3.0 and moving v1 from GPL-2.0+ to GPL/LGPL-3.0 also. It looks like he did v2 yesterday, so I expect v1 will happen soon.

**Comment by evaleev** [comment]
@loriab I pushed a 1.2.0 release candidate with the desired license change. Please let me know if you see any additional issues. I will then tag it to release-1-2-0.

**Comment by loriab** [comment]
Thanks! It all looks good at first look-through. I'll integrate it with Psi4's build system tonight and report back any issues.

* By the way, I think if you remove the LICENSE file (naming it something else or putting the info elsewhere), GitHub will auto-detect the LGPL-3.0 license, as in [this skeleton repo](https://github.com/loriab/licensetestrepo)
* Is `Libint` the official upper/lowercasing from the project? Or just the branding casing? I'm not particular, but CMake only allows one casing, so I have to ask when I notice it changing.

**Comment by loriab** [comment]
@evaleev, are you at all interested in accepting into your repository CMake as an alternate build system? We know from @susilehtola that Psi4 can run with libint1 from either your repo with GNUMake or our repo with CMake. Looking over the directory structures (which have un-synced over the years), I _think_ I could arrange CMake alongside your existing build system (CMake files and GNUMake files would just ignore each other) at the cost of a few extra files and a [directory](https://github.com/psi4/libint/tree/master/cmake). Then psi4/libint could be deleted and there would once again be only one source of Libint truth.

So if you're interested in CMake now or one day, I'll give it a try and submit a PR. If not, that's fine, and I'll go the simple route and apply your relicensing to psi4/libint.

FYI @jturney @andysim

**Comment by evaleev** [comment]
@loriab : 
- since Libint is a multi-license project (part GPL, part LGPL) I'll just leave the LICENSE file in there to spell out what the subtleties are
- Since there is no paper there is no "official"-official lowercasing ... but that's how I've been citing Libint, so probably this is the official project name.
- I am *very much* interested in having CMake in Libint. More so in v2 than v1 (since that is used by quite a few projects including MPQCs ... v1 is used by CP2K and Psi4 (and reportedly Weitao Yang's code)). But if you are willing to PR the CMake harness I'll happily import it.

**Comment by loriab** [comment]
Completed. And Psi4 now pulls from evaleev/libint branch v1, rather than psi4/libint. The latter will be made private at some point to avoid confusion.
