### ISSUE TITLE
ciblks_print true do nothing

### ISSUE THREAD

**Issue by Konjkov** [psi4/psi4#696]
Hi psi4 developers.

I want to get amplitudes of CI after finishing CISD calculation.
My input:

    memory 2 Gb

    molecule acetaldehyde {
     0 1
     C         0.000000000000      0.000000000000      0.000000000000
     O         0.000000000000      0.000000000000      1.208802240800
     H         0.956843585468      0.000000000000     -0.556162423200
     C        -1.240787823813      0.000000000000     -0.847327118586
     H        -2.129446365838      0.000000000000     -0.220697345202
     H        -1.237161750186      0.878440322927     -1.496548823107
     H        -1.237161750186     -0.878440322927     -1.496548823107
    }

    set {
        basis cc-pVDZ
        freeze_core true
        ciblks_print true
    }
    energy('cisd')

I set an option  **ciblks_print true** but nothing has changed.
How do I get CI amplitudes (or 20 first one) properly?

Best, Vladimir.

**Comment by ashutoshvt** [comment]
It seems we don't have an option for printing CISD amplitudes explicitly. `ciblks_print` option prints only the the alpha and beta combinations used in different CI blocks. For `ciblks_print` to take effect, you will have to use `set qc_module  detci` as this option is enabled only for detci module in psi4.

**Comment by dgasmith** [comment]
As a note `ciblks_print` has been deprecated and removed. The top 20 dets are printed with the `detci` module by default.

**Comment by ashutoshvt** [comment]
You are right, I was looking at an older version of psi4.

**Comment by dgasmith** [comment]
Closing this out as this has been fixed in current master.
