### ISSUE TITLE
PCM polarization E psivar

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#697]
@robertodr, when you added the PCM POLARIZATION ENERGY psivar to Wfn, I think you removed it from `P::e.globals` (which `psi4 --test` noticed and complained about). For a transition period, I think we want storage duplicated so that P::e.globals is a full list. Could you add the variable back wherever it gets set to the Wfn value and test that `psi4 --test` works again? Thanks!

**Comment by robertodr** [comment]
Sure thing!

**Comment by robertodr** [comment]
Should I also modify `tests/pytest/test_addons.py` to mirror the contents of `pcmsolver/scf/input.dat` so that it doesn't rely on `P::e.globals`?

**Comment by loriab** [comment]
Maybe duplicate the test so that it tests `P::e.globals` and `Wfn.variables`. Or leave it as-is. It was a handy check that the globals was missing.

**Comment by robertodr** [comment]
OK, now it's such that one of the three test cases uses `Wfn.variables` while the other two still use `P::e.globals`
