### ISSUE TITLE
Formatted checkpoint files don't work

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#708]
@loriab asked me for 1.1 showstoppers. Here's one: the formatted checkpoint files don't work. 

With the input
```
molecule {
symmetry c1
H 0.0 0.0 0.0
H 0.0 1.0 0.0
H 0.0 0.0 1000.0
H 0.0 1.0 1000.0
}

set basis 6-31G
scf_e, scf_wfn = energy('s_x', return_wfn=True)

fchk(scf_wfn, "scf.fchk")
```
I get a formatted checkpoint file, which I load to IQmol or Avogardo.

The result is: I see no nuclei!

**Comment by susilehtola** [comment]
... and one second after clicking open I realized that the nuclei are so far apart that of course I won't see a thing... Duh

**Comment by loriab** [comment]
Oh, whew. Thanks for investigating.

**Comment by susilehtola** [comment]
Looks like the formatted checkpoints don't carry post-SCF densities, though, which would be nice.

Also, it looks like psi4 spits out also spin-restricted checkpoints in spin-polarized form.

For a more thorough study, I could try and check if the formatted checkpoints pass inspection through ERKALE, which I've checked in a previous life against the code that shall not be mentioned.

**Comment by loriab** [comment]
fchk in Psi4 is mainly data transfer for gdma (for which we had a few fchk from the code you allude to). The fchk enhancements are good for psi4/psi4#402 and maybe as a starter project for our developers workshop this week.

**Comment by andysim** [comment]
Yup, any additions to the FCHK functionality are welcome.  The current implementation came from a very frustrating few days of reverse engineering the GDMA parser, and looking at the example files.  If there are any fields, such as correlated densities, that are absent from those files then we won't have functionality for them but would welcome any additions.
