### ISSUE TITLE
PBE0 citation

### ISSUE THREAD

**Issue by tsexton** [psi4/psi4#713]
In /psi4//driver/procrouting/dft_funcs/hyb_superfuncs.py line 47, the function description for PBE0 is described as PBE.  The citation should also be checked.

**Comment by dgasmith** [comment]
@tsexton Would you mind doing this and submitting a PR?

**Comment by tsexton** [comment]
I'll get to work on it.  I'll also look over the other citations in this area.

**Comment by dgasmith** [comment]
@tsexton Any update on this? I can do a quick fix if you are busy.

**Comment by tsexton** [comment]
The old citation for PBE0 was the same as the one given for PBE. I have updated it and submitted a pull request.

**Comment by dgasmith** [comment]
Closed in #745.
