### ISSUE TITLE
DF-HF segfault with very large system

### ISSUE THREAD

**Issue by rmcgibbo** [psi4/psi4#716]
I see a segfault when running an SCF with some of the systems in L7 (in particular [circumcoronene](http://www.begdb.com/index.php?action=oneMolecule&state=show&id=4108)). I've traced the issue, at least in part, to integer sizing bug [in this check](https://github.com/psi4/psi4/blob/6044281f7a94c23852a4fd8291ab67dbcc3280fd/psi4/src/psi4/libfock/DFJK.cc#L699) when the user requests less than Q^2 memory. This is due to a wraparound during subtraction, which results in the error condition [here](https://github.com/psi4/psi4/blob/6044281f7a94c23852a4fd8291ab67dbcc3280fd/psi4/src/psi4/libfock/DFJK.cc#L761) erroneously evaluating to `false`.

**Comment by dgasmith** [comment]
We can probably do away with all of the ULI stuff and move to `size_t` with should correctly map to `unsigned long long int` for 64 bit systems. Let us know about tracking the seg fault further... can you make a gist that reproduces this error?

**Comment by dgasmith** [comment]
Oh responded too fast to that, I see the issue now. That would have to be a tiny amount of memory for such a system, I guess we never considered that could be an issue. Would be good to slap a check in there.

**Comment by dgasmith** [comment]
@rmcgibbo Did you track this down any further?

**Comment by rmcgibbo** [comment]
Yeah, the issue is that https://github.com/psi4/psi4/blob/6044281f7a94c23852a4fd8291ab67dbcc3280fd/psi4/src/psi4/libfock/DFJK.cc#L699` improperly wraps around when `memory_` < 2*two_memory`

**Comment by dgasmith** [comment]
Ah, so it is just that line and nothing further?

**Comment by rmcgibbo** [comment]
Yeah, just that.
