### ISSUE TITLE
Segfault  with basis projection between custom basis sets

### ISSUE THREAD

**Issue by rmcgibbo** [psi4/psi4#719]
I get a segfault when doing an upcast between custom basis sets, while everything works fine when doing an upcast between built-in basis sets. I've been poking around in GDB, but I haven't figured out the issue yet. Here's an example:

```
molecule {
  O 
  H 1 0.96
  H 1 0.96 2 104.5
}

basis low {
    assign sto-3g
}
basis high {
    assign cc-pvdz
}

core.IO.set_default_namespace("low")
set basis low
energy('hf')

core.IO.set_default_namespace('high')
core.IO.change_file_namespace(180, 'low', 'high')
set guess read
set basis high
energy('hf')

```

Merely replacing `set basis low` with `set basis sto-3g` and `set basis high` with `set basis cc-pvdz` fixes the segfault.

**Comment by rmcgibbo** [comment]
The bug is here: https://github.com/psi4/psi4/blob/master/psi4/driver/p4util/python_helpers.py#L48-L51. When called [here](https://github.com/psi4/psi4/blob/9d1564e67837bbf7f348c1600aa2c353457671ec/psi4/driver/procrouting/proc.py#L1297).

**Comment by andysim** [comment]
Wow, thanks for the very detailed report, and detective work.  Feel free to make changes if you'd like have have a shot at fixing this.  If not, I'm going to be reworking the basis set parsing within the next week, to avoid all the duplication between Python and C++, so I can make the appropriate changes then.

**Comment by rmcgibbo** [comment]
I might have the precise lines above wrong. But that's the general idea. I'll file a PR.

**Comment by andysim** [comment]
I know it takes a long time to track these things down, so thank you very much for the effort.

**Comment by rmcgibbo** [comment]
One of the root causes for this that you might be able to clean up is that there are two different "naming conventions" for custom basis sets. For this example, the names used as keys in `qcdb.libmintsbasisset.basishorde` are `LOW` and `HIGH`, but once the basis set is instantiated, the `name()` of it in C++ is more like `file /path/to/sto-3g.gbs` or `file `/path/to/cc-pvdz.gbs`. That's what's behind the trickiness here, because file 180 that we're loading back up contains the C++ name, but to retrive it from the horde, we need the other name.
