### ISSUE TITLE
Rotate only partially occupied orbitals in CIWavefunction::ci_nat_orbs()

### ISSUE THREAD

**Issue by fevangelista** [psi4/psi4#723]
`CIWavefunction::ci_nat_orbs()` (see https://github.com/psi4/psi4/blob/master/psi4/src/psi4/detci/opdm.cc#L575-L589) computes CI natural orbitals by forming the 1RDM and diagonalizing it. This could potentially scramble the position of doubly occupied and unoccupied orbitals. A better solution is to compute and diagonalize only the active block of the 1RDM. Any code change should be compatible with CASSCF/CASCI and truncated CI wave functions.

**Comment by dgasmith** [comment]
Closed by #722.
