### ISSUE TITLE
Increase the orbital limits in DETCI

### ISSUE THREAD

**Issue by lmmentel** [psi4/psi4#724]
I was trying to do a 4-electron FCI using the DETCI code with a huge valence basis set but it seems Psi4 cannot handle CI calculations with more than 255 functions. The errors that I encountered are mentioned in [this forum thread](http://forum.psicode.org/t/increase-ioff-max/531).

In short:

-  If I use more than 255 orbitals I get a memory violation error from the system and ``(subgr_lex_addr): Impossible walk!`` message from Psi4.
-  If I use 408 orbitals I get 

```
    RuntimeError:
    Fatal Error: error: IOFF_MAX not large enough!
    Error occurred in file:path/devel/psi4/psi4/src/psi4/detci/get_mo_info.cc on line: 228
```

It would be great if someone could create a patch fixing this issue, since it severely limits the capabilities of the DETCI code.

**Comment by dgasmith** [comment]
Sure, can add to a wish list. However, this isnt much of a priority at the moment and may be some time before we get to it. This isnt a normal case for the `DETCI` module as its primarily built to do `FCI` and more than 256 orbitals for 6+ electrons is typically too large to do.
