### ISSUE TITLE
Add cc-pwCVXZ for Li, Be, Na, Mg

### ISSUE THREAD

**Issue by rmcgibbo** [psi4/psi4#727]
Would there be any objection to me filing a PR to add some of the cc-pwCVXZ basis sets for alkali and alkali earth metals that are currently missing from Psi4 (i.e. https://github.com/psi4/psi4/blob/master/psi4/share/psi4/basis/cc-pwcvtz.gbs)

 As far as I can tell, they're not on the basis set exchange, but thet are available at http://tyr0.chem.wsu.edu/~kipeters/basissets/alkal-nr.html

**Comment by andysim** [comment]
Given that they're from a non-standard location, it'd be nice if you could drop a note to that effect in [this](https://github.com/psi4/psi4/blob/master/psi4/share/psi4/basis/NOTES) informal collection of developer notes.  Apart from that, I think @loriab has the user-facing documentation nicely automated.  The only other gotcha is that they'll need to have appropriate defaults set for the corresponding RI basis sets (I'm assuming that custom RI bases don't exist, so the cc-pCVXZ versions will have to be used).

**Comment by susilehtola** [comment]
It wouldn't be hard to upload them on the basis set exchange either :D

**Comment by loriab** [comment]
Thanks! Could you instead just update the files tight-cc-pwcvXz.gbs and tight-cc-pwcvXz-ri.gbs that live [here](https://github.com/psi4/psi4/tree/master/psi4/share/psi4/basis/primitives)? Those are the "w-core" and "w-core-ri" that get composed (e.g., [here](https://github.com/psi4/psi4/blob/master/psi4/share/psi4/basis/NOTES#L336-L337) and [here](https://github.com/psi4/psi4/blob/master/psi4/share/psi4/basis/NOTES#L456-L457)) into the actual basis set files to keep everything consistent. I'll run the scripts afterward to do the composing, so don't feel you need to follow the README in primitives/ . Let me know if you've any questions – I wasn't an experienced scripter when I put this together.

On Andy's comments, any comment that you add about the origin to the top of the primitives/*.gbs files will get carried through to the final basis set file. And you're not (I think) creating new basis sets, just adding elements to existing basis sets, so there shouldn't be any need to set fitting defaults for orbital bases.

@susilehtola, I am exceedingly grateful for EMSL. But if I trusted their internal consistency on basis sets that should contain the same info, I wouldn't have the crazy basis file summing scheme in Psi4. Admittedly, I haven't reexamined EMSL in a few years.

**Comment by rmcgibbo** [comment]
Awesome. Thanks for all the info. I hadn't realized the "main" user-facing basis set files were formed by scripts that composed other files, so I wouldn't have done this properly had I not asked :)

I'll do this tomorrow.

**Comment by loriab** [comment]
Sure, thanks for considering adding elements. And let me know if you run into problems.

Also, since you seem to be one with a practical interest in alkali and alkali earth (uncommon among the developers' acquaintance), if you've an opinion about whether those groups should have valence p-block in a cc-pVTZ MINAO basis set, feel free to express it. That is, Li/Be with 0 or 1 p-blocks, Na/Mg with 1 or 2, etc. (Molpro does former)

**Comment by susilehtola** [comment]
I think there *should* be a valence p block, since these elements also have atomic p-states, which are not far above the s ground state.

**Comment by rmcgibbo** [comment]
@loriab: Unfortunately, I don't think it's quite as simple as updating only the `tight-cc-pwcvXz.gbs` and `tight-cc-pwcvXz-ri.gbs` in the `primatives/`. The Psi4 `primatives/basis-cc-pvXz.gbs` files also disagree in a couple cases for these elements with the cc-pVXZ basis sets from Peterson's website. For Lithium cc-pVDZ, for example, it looks like we have basis from `T.H. Dunning, Jr. J. Chem. Phys. 90, 1007 (1989)`, but the higher angular momentum shells were updated in `Prascher, D.E. Woon, K.A. Peterson, T.H. Dunning, Jr., A.K. Wilson, Theor. Chem. Acc. 128, 69 (2011).`

So, in order to add  the cc-pwCVXZ bases for Li, Be, Na, and Mg, I'm going to need the tight functions, but also update the `primatives/basis-cc-pvXz.gbs` files, I think.

**Comment by loriab** [comment]
So the fundamental basis sets cc-pvXz need updating for those elements b/c the definitions changed (for some AM) in a later paper? So long as the `cc-pwCVXZ =  cc-pVXZ + w-core` and others arithmetic in the NOTES still holds, sounds good to me to update both sets of files. And thanks for checking consistency.

**Comment by rmcgibbo** [comment]
Right. Will do then.
