### ISSUE TITLE
Segfault on malformed molecule block

### ISSUE THREAD

**Issue by rmcgibbo** [psi4/psi4#731]
Obviously this is just me being dumb, but a malformed molecule block like the one below causes Psi to segfault in `psi::Molecule::create_molecule_from_string`.
```
molecule {
0 1
Mg 0 0
}
```

**Comment by loriab** [comment]
Another reason to move molecule parsing py side so can have nicer error messages and exceptions. Potentially also simplify efp initialization being all over the place.

**Comment by andysim** [comment]
Yeah, I +1 moving molecule parser to py-side.  These sorts of things that will catch users out eventually, so it's great to be aware of them.  I think we can do something similar to what I have in mind for basis sets; parse everything py-side and hand off a dictionary of info to the C++ c'tor.  In related news, I'm starting on the basis set rework now that I'm back from my trip.

**Comment by loriab** [comment]
After #953 and py-side molecule parsing, this magnesium returns `ValidationError: First line must be Cartesian or single atom.`
