### ISSUE TITLE
Semicanonicalization of restricted_docc/restricted_uocc CASSCF natural orbitals

### ISSUE THREAD

**Issue by fevangelista** [psi4/psi4#740]
The current procedure to obtain natural orbitals in a CASSCF calculation leads to orbitals that are not uniquely defined.

Suggestion is to:
1. form the average Fock matrix (IFock + AFock).
2. diagonalize the restricted_docc and restricted_uocc blocks of the average Fock matrix.
3. rotate restricted_docc and restricted_uocc orbitals using eigenvectors of blocks of the average Fock matrix.

I plan to address this issue.

**Comment by susilehtola** [comment]
I guess the non-uniqueness only affects the inactive blocks?

**Comment by fevangelista** [comment]
Yes. The active are uniquely defined, except if two orbitals have equal occupation number. I am not sure anyone has proposed a way to find unique orbitals if the occupation numbers are equal. I guess one could diagonalize another operator (dipole, etc.).

**Comment by dgasmith** [comment]
Closed by #741.
