### ISSUE TITLE
ERROR: ERI - Libint cannot handle angular momentum this high (6) for first derivatives.

### ISSUE THREAD

**Issue by Hassenky** [psi4/psi4#744]
Dear developers,
I am doing optimization of geometry, but I got this error

"ERROR: ERI - Libint cannot handle angular momentum this high (6) for first derivatives.
     Rebuild Libint with MAX_AM_ERI at least 7."

Could you please show me how to fix it? PSI4 1.1 was installed from miniconda.

Thank you.

Kind regards,

Hassenky

**Comment by loriab** [comment]
http://psicode.org/psi4manual/master/build_planning.html#faq-condamaxameri

**Comment by Hassenky** [comment]
Thank you @loriab.
