### ISSUE TITLE
Psi4 Style Guide

### ISSUE THREAD

**Issue by dgasmith** [psi4/psi4#752]
There was some discussion on coming up with a coding style guide for Psi4. I don't think the idea is that we reformat all of Psi, but if you are going to reformat a section you should *try* to adhere to the following.

My personal `clang-format` settings for C++ are:
```
{
    "BasedOnStyle": "Google",
    "IndentWidth": 4,
    "ColumnLimit": 120,
}
```

Personally, I feel fairly strongly about the 4 indent width, I like the Google style in general, and the column limit is sort of an arbitrary number.

My YAPF setting for Python are:
```
{
   "config": {
        "COLUMN_LIMIT": 119,
    }
}
```
I seem to recall there is a good reason that it's 119 not 120, but I cannot remember what that is for the life of me.

Personally, not a huge fan of enforced style guides through hook mechanisms, but I can go with the flow on it. I mostly feel that being a consistent style is really nice to have, but is not required. And those hook warnings like `# noflakes...` is worse than having a style thats a little off, again, IMO.

Thoughts?

**Comment by fevangelista** [comment]
I would add "SortIncludes: false"

**Comment by loriab** [comment]
If we expand this issue to best practices, then a few lessons from #736 
* Add as many headers as you like during development, but before making the PR, explicitly check if they're needed, and if so, move to source, not convenience header to minimize build impact.
* Avoid including any `py::` in `<top-lvl>/psi4/src/psi4` for the sake of build time. Instead, extend class (can't use private member data) in accompanying `<top-lvl>/psi4/src/export_<cls>.cc`. If you feel you need a `py::` in `<top-lvl>/psi4/src/psi4`, contact the core-devs to see if a work-around can be devised.

**Comment by dgasmith** [comment]
I was kind of thinking this would be purely a code style guide for now. We could break off best practices and even Psi output formatting into other areas.
