### ISSUE TITLE
cann't get atomic positions

### ISSUE THREAD

**Issue by tzyii** [psi4/psi4#765]
In [1]: import psi4

In [2]: mole = psi4.geometry('H 0.0 0.0 0.0\nH 1.5 0.0 0.0')

In [3]: atoms = mole.geometry()

In [4]: import numpy as np

In [5]: np.array(atoms)
Out[5]: array([], shape=(0, 3), dtype=float64)

**Comment by amjames** [comment]
when you use the driver function `psi4.geometry()` the `psi4.core.Molecule` object that is returned has not been completely initialized yet. To complete the initialization of the molecule you can call the the `update_geometry` method of the `psi4.core.Molecule` instance that is returned. 

In your case:

```python
>>> import psi4
>>> mol = psi4.geometry('H 0.0 0.0 0.0\nH 1.5 0.0 0.0')
>>> atoms = mol.geometry().to_array()
>>> atoms
array([], shape=(0, 3), dtype=float64)

>>> mol.update_geometry()
>>> atoms2 = mol.geometry().to_array()
>>> atoms2 
array([[ -1.41729460e+00,  -2.16960662e-17,   0.00000000e+00],
      [  1.41729460e+00,   2.16960662e-17,   0.00000000e+00]])

```

While the docstring for `psi4.geometry()` might not make this clear, and perhaps it should? The docstring for `psi4.core.Molecule.update_geometry()` does:

```python
>>> import psi4
>>> print(psi4.core.Molecule.update_geometry.__doc__)
update_geometry(self: psi4.core.Molecule) -> None

Reevaluates the geometry with current variable values, orientation directives, etc. 
Must be called after initial Molecule definition by string.
```

**Comment by dgasmith** [comment]
Hmm, wonder if we should throw a `update_geometry` at the end of `psi4.geometry`. We can do it at least for full cart molecules. Thoughts?

**Comment by andysim** [comment]
I think an auto-update is a good idea, but will need some sanity checks.  Thinking back a decade, I think the original motivation for not auto updating was to accommodate the following:
```
molecule h2 {
   H
   H 1 R
}

h2.R = 0.7
```
There were some problems caused by attempting to update in the absence of all variables, but they should be easy to overcome with the appropriate checks.

**Comment by loriab** [comment]
`Molecule.geometry()` is providing all Cart coords, so the Mol should be fully specified and this should be safe (at first appearances). If opt/findif don't protest and a trial period proves safe, then I'm good with it.

Downside is that we make `update_geometry()` even more rare and forgettable.
