### ISSUE TITLE
Passing NULL pointer to for_rtl_init_ function in core.cc makes program quit silently

### ISSUE THREAD

**Issue by zhi-wang** [psi4/psi4#771]
clang 4.0 / ifort 15.0.3 / MKL on macOS 10.12

After compiling from source code (tag v1.1), with ENABLE_gdma=ON, the following command quits without any output.
```bash
python -c 'import psi4; print(psi4.__file__)'
```
Running
```bash
python -v -c "import psi4"
```
The last few lines of output are
```bash
import psi4 # precompiled from /path/psi4-gdma/lib/psi4/__init__.pyc
dlopen("/path/psi4-gdma/lib/psi4/core.so", 2);
import psi4.core # dynamically loaded from /path/psi4-gdma/lib/psi4/core.so
```
No error message.

Modifying the following code
https://github.com/psi4/psi4/blob/master/psi4/src/core.cc#L1219-L1221
to
```cpp
#ifdef INTEL_Fortran_ENABLED
    static int argc = 1;
    static char* argv = (char*) "";
    for_rtl_init_(&argc, &argv);
#endif
```
solves the problem.

Any comments?

**Comment by loriab** [comment]
Interesting, and fine by me. @bennybp, any comments, as the `INTEL_Fortran_ENABLED` was your issue.

**Comment by andysim** [comment]
Thanks for the very detailed bug report.   The changes you suggest look harmless to me, so I'll make test them on my local machine and submit a pull request.

**Comment by dgasmith** [comment]
Hmm, should be fine @loriab @andysim Did you ever get a chance to check this?

**Comment by loriab** [comment]
Tried it out on Linux. I don't reproduce the problem (also I don't think we support that compiler), but the solution seems harmless.
