### ISSUE TITLE
Different behavior between source build and conda binary

### ISSUE THREAD

**Issue by bwb314** [psi4/psi4#773]
When performing a B3LYP-D2 single point, with custom basis sets, I am getting different behavior from the conda binary (version: 1.2a1.dev458) and the source build (version: 1.2a1.dev458) on OS X with the exact same input file. 

The conda binary produces the first few iterations and does not converge: 
```
@DF-RKS iter   0: -2879.17610215408513   -2.87918e+03   1.22721e-02     
@DF-RKS iter   1: -2858.84066999046217    2.03354e+01   1.56850e-03     
@DF-RKS iter   2: -2827.41152127256692    3.14291e+01   5.78505e-03 DIIS
``` 

My source build produces the first few iterations and does converge: 
```
@DF-RKS iter   0: -2879.11745920690237   -2.87912e+03   2.36222e-02
@DF-RKS iter   1: -2858.74896735363154    2.03685e+01   3.85843e-03
@DF-RKS iter   2: -2830.12148835513381    2.86275e+01   1.21879e-02 DIIS
```

Diffing the outputs reveals nothing unexpected other than the RKS iterations.

I have attached the input and basis sets for completeness.

[binary_vs_source.zip](https://github.com/psi4/psi4/files/1183857/binary_vs_source.zip)

**Comment by dgasmith** [comment]
If you run it with `core` do you get the same results each time?

Guessing this is in the SAD, likely a atom is not converging or something in the partial Cholesky. Can you run with a `SAD_PRINT 5` for me? Please dump this in a Gist and not a zip.

**Comment by bwb314** [comment]
Yes, when I run it with `core`, I get the same, non-converging result each time.

Here are the jobs with `SAD_PRINT 5`:
<script src="https://gist.github.com/bwb314/26fe537a4e9c8e571615c77953f2ea22.js"></script>

I'm using GCC 5.2.0 and Accelerate's BLAS/LAPACK.

**Comment by bwb314** [comment]
Tightening/loosening `SAD_CHOL_TOLERANCE` does not affect the convergence of the job when using the Conda binary.

**Comment by dgasmith** [comment]
Is the guess energy the same or does it change by a large amount?

So the SAD energies are correct which means the densities are *likely* similar, and tweaking the Cholesky doesn't help. Color me stumped.

Maybe the SAD guess is picking up a odd symmetry with different diagonalizers, can you try `set sad_frac_occ true`?

**Comment by bwb314** [comment]
The guess energy changes by 0.018 H when changing the Cholesky threshold from 1e-6 to 1e-12. 

Using `set sad_frac_occ true`, the job actually converges, and the guess energy from the source build and Conda binary are much more similar (within 0.0001 H):

Conda Binary:
`@DF-RKS iter   0: -1710.72967880925034   -1.71073e+03   1.05313e-01`

Source Build:
`@DF-RKS iter   0: -1710.72974672447867   -1.71073e+03   9.17594e-02`

**Comment by dgasmith** [comment]
That points to the diagonalizers getting stuck in a odd density symmetry for one of the atoms in your molecule. Fixing this will either require doing a SAD guess with symmetry and hand coding the occupations or always using `frac_occ` for elements past the first row or so.

Switching `frac_occ` to true in all cases is not an overall bad idea. @psi4/editors - thoughts?

**Comment by loriab** [comment]
One side effect of this issue should be to clarify what `SAD_FRAC_OCC` does. It's a bool in the driver and in [read_options](https://github.com/psi4/psi4/blob/8b41a2101e1bda59cd955361648abb8ce7158e3a/psi4/src/read_options.cc#L1424) and a double in the scf code but has a copied docstring.

**Comment by dgasmith** [comment]
@loriab Its a bool, looks like a typo in the SCF code.

**Comment by loriab** [comment]
Thanks, @dgasmith. So the docstring should be something like "Do use shielding to estimate fractional occupation in SAD guess?"? I've no objection to trying a `true` default. Want a full test suite run with that?

**Comment by dgasmith** [comment]
I don't have enough compute for a full test run currently :). Maybe "Forces a even distribution of occupations across the last partially occupied orbital shell".

**Comment by dgasmith** [comment]
@loriab I think we were running full tests on this, do you have any results?

**Comment by loriab** [comment]
Running now. Forgot after Matt needed sole nupsinet.

**Comment by loriab** [comment]
Ok, four failures:

```
The following tests FAILED:
	269 - props2 (Failed)
	270 - props3 (Failed)
	324 - soscf-dft (Failed)
	349 - scf-coverage (Failed)
```

props3 and scf-coverage could be healed by slight relaxation:
```
TestComparisonError: 	Lithium anion stability: computed value (-7.4168185) does not match (-7.4168196) to 6 digits.
```

```
TestComparisonError: 	64-pole ZZZZZZ: computed value (-20544.12046) does not match (-20544.12057) to 4 digits.
```

But props2 is really off:
```
TestComparisonError:    Y Component of Dipole 0: computed value (21.592762) does not match (17.775955) to 5 digits.
```

And soscf-dft is fine energy-wise but oscillates more that the test allows on iterations in the next-to-last (PBE) subtest:
```
   @DF-RKS iter   0:  -148.97585698578987   -1.48976e+02   2.56136e-01 
   @DF-RKS iter   1:  -148.95093820938956    2.49188e-02   1.50011e-01 
   @DF-RKS iter   2:  -149.39705073850598   -4.46113e-01   1.11947e-01 DIIS
   @DF-RKS iter   3:  -150.12875309470365   -7.31702e-01   7.57889e-03 DIIS
   @DF-RKS iter   4:  -150.12714697276095    1.60612e-03   1.00558e-02 SOKS, nmicro = 4
   @DF-RKS iter   5:  -150.13120148446785   -4.05451e-03   1.42232e-05 DIIS
   @DF-RKS iter   6:  -150.12700529520501    4.19619e-03   1.02055e-02 SOKS, nmicro = 4
   @DF-RKS iter   7:  -150.13120147305844   -4.19618e-03   2.10040e-05 DIIS
   @DF-RKS iter   8:  -150.12394657944893    7.25489e-03   1.34190e-02 SOKS, nmicro = 4
   @DF-RKS iter   9:  -150.13120141103812   -7.25483e-03   4.21385e-05 DIIS
   @DF-RKS iter  10:  -150.12366619982981    7.53521e-03   1.36759e-02 SOKS, nmicro = 4
   @DF-RKS iter  11:  -150.13120140228156   -7.53520e-03   4.43841e-05 DIIS
   @DF-RKS iter  12:  -150.11089835193317    2.03031e-02   2.24444e-02 SOKS, nmicro = 4
   @DF-RKS iter  13:  -150.13120064244808   -2.03023e-02   1.38615e-04 DIIS
   @DF-RKS iter  14:  -150.10407305304250    2.71276e-02   2.59404e-02 SOKS, nmicro = 4
   @DF-RKS iter  15:  -150.13119989205700   -2.71268e-02   1.91309e-04 DIIS
   @DF-RKS iter  16:  -150.08734658173793    4.38533e-02   3.29682e-02 SOKS, nmicro = 5
   @DF-RKS iter  17:  -150.13119968635687   -4.38531e-02   1.98267e-04 DIIS
   @DF-RKS iter  18:  -150.12286951781326    8.33017e-03   1.43806e-02 SOKS, nmicro = 4
   @DF-RKS iter  19:  -150.13120137806487   -8.33186e-03   5.00267e-05 DIIS
   @DF-RKS iter  20:  -150.12924629472502    1.95508e-03   6.96605e-03 SOKS, nmicro = 4
   @DF-RKS iter  21:  -150.13120149212386   -1.95520e-03   7.21044e-06 SOKS, nmicro = 4
   @DF-RKS iter  22:  -150.13120149480929   -2.68543e-09   3.33181e-08 SOKS, nmicro = conv
  @DF-RKS Final Energy:  -150.13120149480929
```

**Comment by dgasmith** [comment]
Looks like its messing with the correct assignment of occupation states in molecules with symmetry which leads to some issues. In general this is a common problem for us and one we haven't given much thought to.

**Comment by dgasmith** [comment]
Looks like this isn't a one fix for all. @bwb314 I would add `set sad_frac_occ true` to your toolkit for fixes, but its not a 100% fix either way.
