### ISSUE TITLE
Replacing char * with std::string

### ISSUE THREAD

**Issue by tsexton** [psi4/psi4#778]
I was at the psi4 developers meeting at SETCA.  One of the tasks was to replace char * with std::string throughout the code.  I said I would do this but didn't get around to it.  Is there still interest in this being done?  If so, I will pick this up again.

Here is my plan:

replace char * with 'std::string'
replace char ** with ‘std::vector\<std::string\>’

Use .c_str() to convert the std::string when needed

Remove relevant calls to "free" (the std::string doesn't need to be freed.)

**Comment by loriab** [comment]
Yes, we're definitely still interested. You may want to go module-by-module, and we can certainly advise on which are highest priority. Upon the Boost-->Pybind11 conversion, we found some cases where `char *`s were wily and acted differently in expressions that should have had the same execution. So just proceed gingerly. And thanks for taking this on!

**Comment by dgasmith** [comment]
Just a note: I would highly suggest doing this in an iterative manner. For example, I think we talked about converting the irrep labels to `std::string` first. I would make just that piece a whole PR. This is a great thing to do as a [Agile Development Process](https://en.wikipedia.org/wiki/Agile_software_development).

**Comment by tsexton** [comment]
I put in a PR (#780) for the irrep labels.  There were a lot of sections of the code that used them.

**Comment by dgasmith** [comment]
Closing this and moving to the wish list. Thanks for all of the help on this so far! Let us know if you ever want to take this up again, we are here and happy to help if issues arise.
