### ISSUE TITLE
 auxiliary basis set assignment 

### ISSUE THREAD

**Issue by lucamontana** [psi4/psi4#784]
Dear all, 

I like to set instead of the "def2-qzvpp-ri.gbs" another auxiliary basis set for my Cu atoms with lower angular momentum like "cc-pvdz-ri.gbs ". How is this possible ?

"atoms 3-4   entry CU         line  2476 file /home/luca/Desktop/psi4_max/psi4 master/bi/stage/usr/local/psi4/share/psi4/basis/def2-qzvpp-ri.gbs"

Best,
LUCA

**Comment by loriab** [comment]
```
df_basis_mp2 <optional_name> {
assign Cu cc-pvdz-ri
}
```
should do the trick. The curly braces syntax is needed b/c you're not using a single RI basis across the molecule. Change "df_basis_mp2" to whichever basis keyword you're targeting.

**Comment by lucamontana** [comment]
Thank you Lori!
LUCA
