### ISSUE TITLE
linking error

### ISSUE THREAD

**Issue by lucamontana** [psi4/psi4#785]
Dear all, 

I am trying to compile the latest version of the PSI4 package on a cluster with OpenSuse; however I end up with the following linking error : 

Linking CXX shared library core.so
/usr/bin/ld: BFD (GNU Binutils; openSUSE 12.3) 2.23.1 internal error, aborting at ../../bfd/reloc.c line 444 in bfd_get_reloc_size

/usr/bin/ld: Please report this bug.

collect2: error: ld returned 1 exit status
make[5]: *** [src/core.so] Error 1
make[5]: *** Deleting file `src/core.so' 
make[4]: *** [src/CMakeFiles/core.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [psi4-core-prefix/src/psi4-core-stamp/psi4-core-build] Error 2
make[1]: *** [CMakeFiles/psi4-core.dir/all] Error 2
make: *** [all] Error 2
 
-----------------------------------------------------------------------------------------------------------------------------------------
Any idea how to get rid of it?

Best,
LUCA

**Comment by tsexton** [comment]
I have a computer at work with openSUSE 13.2 (Newer version compared to your 12.3)  I have recently compiled psi4 on it without this error.  Maybe it's an issue with that version of ld?  Your error message seems to indicate that ld knows this behavior is a bug.

My version of ld is newer than yours also:
$ ld --version
GNU ld (GNU Binutils; openSUSE 13.2) 2.24.0.20140403-6.1

**Comment by lucamontana** [comment]
Okay, many thanks.
LUCA
