### ISSUE TITLE
OPTKING PSIO error: optimization data write failure

### ISSUE THREAD

**Issue by dsirianni** [psi4/psi4#789]
Hi all,

The following PSIO error occurs for identical geometry optimizations on two separate machines, when OPTKING attempts to write opt data to binary file:
```
Fatal Error: PSIO Error
Error occurred in file: /theoryfs2/ds/sirianni/Gits/psi4/psi4/src/psi4/libpsio/error.cc on line: 129
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)
psi::psio_error(unsigned long, unsigned long)
psi::PSIO::write(unsigned long, char const*, char*, unsigned long, psi::psio_address, psi::psio_address*)
psi::PSIO::write_entry(unsigned long, char const*, char*, unsigned long)
psi::psio_write_entry(unsigned long, char const*, char*, unsigned long)
```
This then results in a second PSIO error upon each subsequent optimization iteration, when attempting to read the binary optimization data from file:
```
Fatal Error: PSIO Error
Error occurred in file: /theoryfs2/ds/sirianni/Gits/psi4/psi4/src/psi4/libpsio/error.cc on line: 129
The most recent 5 function calls were:

psi::psio_error(unsigned long, unsigned long)
psi::PSIO::open(unsigned long, int)
psi::psio_open(unsigned long, int)
opt::opt_io_is_present()
```
This finally results in the optimizer spinning its wheels for the remainder of the allotted iterations. The usual PSIO error-culprit, an un-touchable filesystem, was ruled out for both machines on which this behavior was observed.

Input:
```
# index A24-7-dimer label Dimer from ammmonia_methane_C3v

memory 14000 mb

molecule mol {
       units Angstrom
       no_com
       no_reorient
       0 1
    N            0.001106462041    -0.000130846927     1.849133409958
    H            0.938627974105    -0.000139345380     2.221618285244
    H           -0.467316580071    -0.811849948182     2.222477040520
    H           -0.467307391010     0.811579719379     2.222474714333
    H           -0.000457075852    -0.000011938197    -0.942103507206
    C           -0.001019750816     0.000109523659    -2.027776337389
    H            0.509840850903     0.885353515687    -2.394362733084
    H            0.509834400679    -0.885039296153    -2.394623104348
    H           -1.023308879978     0.000128616114    -2.393761958029

}

set e_convergence 11
set basis cc-pvtz
set scf guess sad
set scf dft_radial_points 150
set scf scf_type df
set scf dft_spherical_points 434
set scf maxiter 100
set guess_persist true
set geom_maxiter 300

set optking {
dynamic_level=1
full_hess_every 0
max_energy_g_convergence 1e-6
max_force_g_convergence 1.5e-5
rms_force_g_convergence 1e-5
max_disp_g_convergence 6e-4
rms_disp_g_convergence 4e-4
}

optimize('m05-2x')
``` 

Thanks in advance for any assistance, everyone!

**Comment by dgasmith** [comment]
What is Psi actually doing when it crashes?

**Comment by tsexton** [comment]
Issue #786 also has a PSIO error.

**Comment by dsirianni** [comment]
Well, @dgasmith, it's not even really crashing due to the PSIO errors...the job continues to run after failing to write the binary optimization data, and finally fails after exceeding the number of allotted optimization iterations.  But, it's the manner in which that happens which is the issue: the optimizer is failing to take steps after the first failure of PSIO, I expect because it can't read the optimization data from binary file.  Below is a brief overview of the structure within the job.

- Take some number of good optimization steps, with structure:
    1) SCF
        - Compute SCF wavefunction & gradient
    2) OPTKING
        - Read optimization data from binary file 
        - Take optimization step
        - Write optimization data to binary file
        - Sets geometry for next step
- First error step:
    1) SCF wfn & grad computed successfully
    2) OPTKING
        - Read data & take step successfully
        - PSIO error when attempting to write data to binary file
        - Sets geometry for next step
- All subsequent steps (until `geom_maxiter` reached):
    1) SCF wfn, grad computed successfully
    2) OPTKING
        - Second PSIO error occurs
        - **No optimization step taken**
        - Geometry for next step is set to the same as in first error step

So, once the first PSIO error occurs, there's no progress made by the optimizer.

**Comment by dsirianni** [comment]
Update from @psi-rking:
> When the dynamic level gets changed, the binary (file 1) file is
> supposed to be deleted.  I guess that it is not.  The function that
> removes it does check:
> `if (! psi::_default_psio_manager_->get_specific_retention(1))`
> In your .psi4rc, are you perhaps setting retention of file 1?  This
> could be happening in the psi4 driver somewhere too.
> If this is the problem, and you need to set the specific retention for
> some reason, then we will have to add another check to indicate
> deletion.

**Comment by dsirianni** [comment]
Commenting to confirm that #798 does correct this issue.  Closing as no longer relevant.
