### ISSUE TITLE
Docs : class inheritance diagrams are broken

### ISSUE THREAD

**Issue by TiborGY** [psi4/psi4#792]
The class inheritance diagrams in the documentation are currently broken: [http://psicode.org/psi4manual/1.1/psi4api.html#class-inheritance-diagram](http://psicode.org/psi4manual/1.1/psi4api.html#class-inheritance-diagram)

My best guess is that something must have went wrong with the sphinx doc generation, but beyond that I have no idea.

**Comment by loriab** [comment]
Fixed after psi4/psi4#801 after I properly installed dot/graphviz on the building computer.
