### ISSUE TITLE
Don't hardcode libxc functionals

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#793]
It appears Psi4 includes a hardcoded list of libxc functional names and ids in psi4/driver/procrouting/dft_funcs/libxc_xc_funcs.py.

This should be eliminated in favor of using libxc's own routines for parsing the functionals: ```XC(functional_get_name)(func_id)``` and ```XC(functional_get_number)(str)```

This will eliminate the need to maintain a functional list in psi4, making all newly added libxc functionals available in Psi4 as soon as the underlying libxc library is updated.

**Comment by dgasmith** [comment]
We need a hardcoded list for documentation purposes. In addition, we use those mechanics under the hood. I suppose we could allow a pass through to check if a give functional/primitives exists from a libxc call, but this is not too much a priority since its pretty easy to copy over the header when libxc is updated. Feel free to make a PR if you want this feature.

**Comment by susilehtola** [comment]
Given that pyscf also resorted to hardcoding the functional list in Python (sunqm/pyscf#48), the best option might be to move the whole thing inside libxc. Generating a Python file along the C and Fortran headers would be no trick at all; this could also encode other necessary functionalities such as the functional family etc.

I've opened up a ticket on the libxc tracker at
 https://gitlab.com/libxc/libxc/issues/28

What would be the minimal functionality you would need? It would appear from ```libxc_xc_funcs.py``` that simply replacing xc_func_list would be enough..?

**Comment by dgasmith** [comment]
Yes, I think simply producing that list would be sufficient. LibXC could also product a `char**` that we could wrap and pull out.

**Comment by susilehtola** [comment]
OK. Would something like
 void get_valid_functional_ids(int * list, int * length);
 void get_valid_functional_kws(char ** list, int * length);

do the trick, i.e. libxc would fill in the list with valid functional IDs and keywords?

**Comment by dgasmith** [comment]
Absolutely. Just give us something to query the length as well. 

-Daniel Smith

**Comment by susilehtola** [comment]
Yes the length would be filled in automatically.

**Comment by susilehtola** [comment]
Does the implementation at
https://gitlab.com/libxc/libxc/tree/funclist

fulfil your requirements?

**Comment by dgasmith** [comment]
Personal preference would be that the caller would manage memory rather than the function `mallocing` data. Not a huge possible leak, but still could be annoying. Could be nice for the C++ folks as well:

```
std::vector<int> avail_func_nums(xc_number_of_functionals());
xc_available_functional_numbers(avail_func_nums.data());
```

**Comment by susilehtola** [comment]
.. the flip side being that then you also have to query the maximum name length.

**Comment by susilehtola** [comment]
I've changed the routines so that the memory management is entirely up to the caller.

**Comment by dgasmith** [comment]
You have to know the length to use the raw pointer anyways?

Calling `malloc` from the internal C function means that I have to know to call `free` and not `delete` C++ side and I also have to copy the data into a managed object (popular). What if I want a buffer on a particular node or NUMA domain? What if I need the malloc to be aligned?

**Comment by loriab** [comment]
Right now psi is still pulling libxc from our repo (from a 3 series tarball). Any dev/unstable warnings against pulling from gitlab branch to try this out? Timeframe of next release from GL?

**Comment by susilehtola** [comment]
A lot has changed in libxc 4, but that's all on the back-end side. Libxc 3 still used hand-written functionals, whereas libxc 4 uses computer algebra generated code. I'd say there's a lot of things that work better in libxc 4. But some of the added functionals might not be thoroughly tested.

The release of libxc 4 is pending improvements to the test suite, so that functionals that work pass on a variety of compilers and architectures.

**Comment by dgasmith** [comment]
That would be really great. Let us know when `libxc4` is released and we will switch over!

**Comment by susilehtola** [comment]
I've just merged the new code in libxc master. Libxc4 is going to be released tomorrow, after which you can switch over.

**Comment by dgasmith** [comment]
Looking at this, we do not hardcode LibXC functionals in the full sense. We do present a list of functionals that are officially supported as we need to parse through them and make sure we actually support the underlying forms and dispersion corrections.

Advanced users are free to build their own functionals from any LibXC primitive or mixed functional via the more advanced custom functional interface found [here](http://psicode.org/psi4manual/master/dft.html#advanced-functional-use-and-manipulation).
