### ISSUE TITLE
Boron multideterminant wrong sign.

### ISSUE THREAD

**Issue by Konjkov** [psi4/psi4#796]
Dear PSI4 developers.

I use psi4 MOLDEN output (along with ORCA, QCHEM, etc.) as input for CASINO QMC program https://vallico.net/casinoqmc/ 

For very simple system as Be, B, C atoms well proven that if we add 2s->2p excitation to the ground state than we improve wfn quality.

PSI4, ORCA and other code gives me MOLDEN orbitals and coefficients for most important determinants. I can take it and check with CASINO QMC if energy of this multi-determinant configuration is the same as in conventional QMC codes.

For the B output from Psi4 it isn't so.
Psi4 determinant coeffs is
```
   The 20 most important determinants:

    *   1    0.972153  (    0,    0)  2AX 3AA.
    *   2    0.165709  (    4,    3)  3AA 5AX.
    *   3    0.165709  (    2,    2)  3AA 4AX.
```

but should be (as in the ORCA and other programs):
```
   The 20 most important determinants:

    *   1    0.972153  (    0,    0)  2AX 3AA.
    *   2   -0.165709  (    4,    3)  3AA 5AX.
    *   3   -0.165709  (    2,    2)  3AA 4AX.
```
And if I change sign by hand in PSI4 output i get right energy in CASINO QMC for this multi-determinant configuration, same as PAS4 Total MCSCF energy.

Can You check whether the signs of coefficients are correct.

Best, Vladimir.

PS Git: Rev {HEAD} add49b9

PPS
```
memory 2 Gb

molecule b {
  0 2
  symmetry c1
  B         0.000000000000      0.000000000000      0.000000000000
}

set {
   basis cc-pVQZ
   reference  rohf
   restricted_docc [ 1 ]
   active [ 4 ]
}

cas_e, cas_wfn = energy('casscf', return_wfn=True)
molden(cas_wfn, 'molden.dat')
```

**Comment by fevangelista** [comment]
Hi Vladimir, have you checked that both codes give CASSCF molecular orbitals with the same sign (phase)? That is likely to be the reason you get different signs for the determinants.

**Comment by Konjkov** [comment]
Hello Francesco.

I didn't check exactly the sign. I will try this with very small basis like STO-3G.
But I can take the orbitals from MOLDEN output and coefficients (with signs) and put it into CASINO program input, as I usually do this many times for another systems. Then I can recalculate energy with variational monte calro (VMC) method. I have to get the same energy but I don't in the case of Boron.
Than I changed coefficients signs by hands and gave the right VMC energy.
It makes me think that the sign was wrong.

If you suggest a way to quickly check that the sign of coefficients is correct I will use it.

Best, Vladimir.

**Comment by dgasmith** [comment]
@CDSherrill Perhaps you could comment on this?

**Comment by CDSherrill** [comment]
It's too bad thus is not working properly!

If the Molden output from Psi is being used as input to the QMC, and the
wrong CI energy is obtained, then it may be that we have a bug in the
Molden output writer.  (Are we sure the CAS orbitals are the ones being
written out, and not HF orbitals?)

The signs on the determinants printed by Psi4 code are well tested, and so
I think it is extremely unlikely they could be wrong. It is much more
likely that there is some kind of mismatch between the orbitals being used
in the CAS and the orbitals being put into the QMC code.  Possible due to a
bug in the Molden writer, or possibly due to some kind of enforced phase
convention in the QMC code that is incompatible with the phase of the
orbitals from Psi.

**Comment by Konjkov** [comment]
Hello David.

Single determinant PSI4 output works pretty well and have been tested.
There is nothing special in the code for PSI4 converter https://github.com/Konjkov/molden2qmc/blob/master/molden2qmc.py#L962

Multi-determinant extension composes from some single determinant (i.e. PSI4 CASSCF(3,4) MOLDEN output) and electron promotion data.
2-nd determinant:
up electron promote from 2 orbital to 4
down electron promote from 2 orbital to 4
3-nd determinant:
up electron promote from 2 orbital to 5
down electron promote from 2 orbital to 5
The first determinant is taken into account with the weighting factor = 0.972153
2-nd with = 0.165709
3-rd with = 0.165709
as described in PSI4 output:

    MCSCF Root 0 energy =   -24.563671749133171

    Active Space Natural occupation numbers:
         
         A   1.890162         A   1.000000         A   0.054919
         A   0.054919
 
   The 20 most important determinants:
         
     *   1    0.972153  (    0,    0)  2AX 3AA.
     *   2    0.165709  (    4,    3)  3AA 5AX.
     *   3    0.165709  (    2,    2)  3AA 4AX

symmetry is turned out.
For this multi-determinant configuration CASINO outputs (roughly)

    E     = -24.431(1) ; var  = 5.3(1) 
    Total CASINO CPU time  ::: 181.2400 seconds

if I take 2-nd and 3-rd determinants with weighting factor = -0.165709
CASINO outputs (roughly)

    E     = -24.565(1) ; var  = 5.0(1) 
    Total CASINO CPU time  ::: 256.1500 seconds

which very well coincides with the PSI4 output energy.

Best, Vladimir.

**Comment by Konjkov** [comment]
I've tried ROHF molden output from PSI$ input:

    memory 2 Gb

    molecule be {
      0 2
      symmetry c1
      B         0.000000000000      0.000000000000      0.000000000000
    }

    set {
       basis cc-pVQZ
       reference  rohf
    }

    hf_e, hf_wfn = energy('scf', return_wfn=True)
    molden(hf_wfn, 'molden.dat')

    Total Energy =                        -24.5289623832308834

Single determinant CASINO output:

    E     = -24.529(1) ; var  = 4.89(8)

3 determinants with weighting factors:
1-st  0.972153
2-nd 0.165709
3-rd  0.165709

CASINO output:

    E     = -24.459(1) ; var  = 5.1(2) 

3 determinants with weighting factors:
1-st   0.972153
2-nd -0.165709
3-rd  -0.165709

CASINO output:

    E     = -24.535(1) ; var  = 5.0(1)

**Comment by fevangelista** [comment]
Dear @Konjkov, can you post the matrices with the orbital coefficients for the above examples?

**Comment by Konjkov** [comment]
Hello  Francesco.
I don't quite understand you. The only matrix determine orbital coefficients is [MO] section data of the MOLDEN file and different determinants have only different occupation numbers of there orbitals.
I only sort MO orbitals by energy if required before feed it into CASINO.

I will upload MOLDEN outputs for CASSCF and ROHF cases approximately in 2 hours when I will have access to the server.

But you can also create these files easily from my inputs or you can talk about some other matrices.

Best, Vladimir.

**Comment by CDSherrill** [comment]
Maybe @dgasmith can clarify exactly how the orbitals are generated in cases
like this for CASSCF.  Are they CAS NO's?  Perhaps the most important
determinants are printed prior to the natural orbital procedure (in which
case there would be a mismatch between the orbitals and the determinant
printout)?  Or, alternatively, I wonder if we enforce any kind of phase
convention in our MOLDEN writer that the CASSCF code is unaware of?

David

**Comment by dgasmith** [comment]
Hmm, Fransesco recently made some changes that rotate the MCSCF orbitals to a standard frame (either semicanonical or NO’s). The CI determinants are optimized and printed in this basis however. A quick pass shows that the MOLDEN writer should be picking everything up correctly; however, this doesn’t rule out something subtle.

One check could be to disable this. A cursory looks shows the best way to accomplish this is to call RASSCF while specifying a CASSCF wavefunction.

**Comment by susilehtola** [comment]
Could there be a difference in how the programs sort the determinant strings? That can easily give a sign flip.

**Comment by Konjkov** [comment]
Hello Susilehtola.
You exactly right. first two determinant should be expressed as:
<1> = det[ψ<sub>1s</sub>(r<sub>1</sub>), ψ<sub>2s</sub>(r<sub>2</sub>), ψ<sub>2p</sub><sub>x</sub>(r<sub>3</sub>)] • det[ψ<sub>1s</sub>(r<sub>4</sub>), ψ<sub>2s</sub>(r<sub>5</sub>)]
<2> = det[ψ<sub>1s</sub>(r<sub>1</sub>), ψ<sub>2py</sub>(r<sub>2</sub>), ψ<sub>2px</sub>(r<sub>3</sub>)] • det[ψ<sub>1s</sub>(r<sub>4</sub>), ψ<sub>2py</sub>(r<sub>5</sub>)] or det[ψ<sub>1s</sub>(r<sub>1</sub>), ψ<sub>2py</sub>(r<sub>3</sub>), ψ<sub>2px</sub>(r<sub>2</sub>)] • det[ψ<sub>1s</sub>(r<sub>4</sub>), ψ<sub>2py</sub>(r<sub>5</sub>)] which accordingly to Pauli exclusion principle should change the sign.

**Comment by Konjkov** [comment]
I don't quite understand what the numbers in brackets mean
    *   1   -0.972087  (    0,    0)  2AX 3AA.
    *   2   -0.165902  (    2,    2)  3AA 4AX.
    *   3   -0.165902  (    4,    3)  3AA 5AX.
I'm also not sure that 3AA 4AX means 1-st up active space electron in 3-rd orbital, 2-nd up electron on 4-th orbital, 1-st down electron on 4-th orbital. This would explain the sign of the determinant, since in ORCA order is reversed.

**Comment by dgasmith** [comment]
@CDSherrill Can you weigh in here?

**Comment by Konjkov** [comment]
related topic in CASINO forum https://vallico.net/casino-forum/viewtopic.php?f=4&t=212

**Comment by susilehtola** [comment]
> I don't quite understand what the numbers in brackets mean
> * 1 -0.972087 ( 0, 0) 2AX 3AA.
> * 2 -0.165902 ( 2, 2) 3AA 4AX.
> * 3 -0.165902 ( 4, 3) 3AA 5AX.
> I'm also not sure that 3AA 4AX means 1-st up active space electron in 3-rd orbital, 2-nd up electron on 4-th orbital, 1-st down electron on 4-th orbital. This would explain the sign of the determinant, since in ORCA order is reversed.

3AA 4AX means that you have an alpha electron in orbital 3A, and an alpha and beta electron in orbital 4A. You could also write the three determinants as 2u00, u200, and u020 with u=spin-up, d=spin-down, 2=doubly occupied, 0=unoccupied.

I think the difference may just be in the ordering of the different spin blocks: are the creation/annihilation operators acting on the HF determinant first by orbital, then by spin, or first by spin, and then by orbital.

**Comment by JonathonMisiewicz** [comment]
This seems to be a non-issue, just a confusion about the sign convention. Issue closed.

**Comment by snasiri2016** [comment]
Dear Developers,

I am a new user of the PSI4 package and have two questions about the multideterminant expansion generated by PSI4.

My first question is about the printed letters after the orbitals in an MCSCF calculation. For example, in the following line:

1   -0.445106  (  735,  514)  6A1**X* 7A1**A* 8A1**A* 9A1**A* 1A2**A* 2B1**X* 3B1**B* 2B2**X* 3B2**X*

What do the letters "X", "A", and "B" mean?

My second question is about the multideterminant.py code. This code generates a block that contains only coefficients, and the explanation of the excitations is absent. For example:

-0.445106  1 0

While in the CASINO correlation file, there should be some lines like:

DET 1 2 PR 3 4 5 6

Could you please let me know how I can add these lines?

Thank you,
Saeed

**Comment by Konjkov** [comment]
Hello Saeed.

All questions about **multideterminant.py** should be asked [there](https://github.com/Konjkov/molden2qmc/issues) for this you need to apply psi4 version, input, output... this script works correctly for versions ORCA4.X and ORCA5.X

> 1 -0.445106 ( 735, 514) 6A1X* 7A1A* 8A1A* 9A1A* 1A2A* 2B1X* 3B1B* 2B2X* 3B2**X*

I don't know such notations for e-promotion rules, maybe that's why my script doesn't work correctly for PSI4. Maybe there is a link to documentation explaining this.
A - up electron
B - down electron
X - doubly occupied
also A, B can also mean irreducible representations. What do the asterisk mean? 

Best wishes, Vladimir.

**Comment by Konjkov** [comment]
There is a problem in getting data from the output file due to limited precision
[output.txt](https://github.com/user-attachments/files/17459080/output.txt)

these lines mean that there was not enough precision, and their presence is meaningless
    * 128    0.000000  (   23,    5)  4AA 7AB 9AA.
    * 129   -0.000000  (   13,    0)  2AB 5AA 7AA.
    * 130    0.000000  (   21,    0)  2AX 9AA.
    * 131   -0.000000  (    1,    0)  2AX 4AA.
    * 132   -0.000000  (   15,    1)  2AA 3AB 8AA
    
It would be much more correct to generate a Excitations and multideterminant-expansion coefficients section of the CASINO input file by PSI4 code itself, according [documentation](https://casinoqmc.net/casino_manual_dir/casino_manual.pdf) 
**7.4.5  Excitations and multideterminant-expansion coefficients**

**Comment by snasiri2016** [comment]
Thanks for your comment.

I am going to do as you suggested.
But I cannot include all determinants, I have to truncate the expansion.
If I am not mistaken generating the excited determinant should be explained in the correlation.data file. 
I have not been able to do by now.

**Comment by Konjkov** [comment]
@fevangelista should a separate ticket be created for the new PSI4 functionality?

**Comment by Konjkov** [comment]
> 3AA 4AX means that you have an alpha electron in orbital 3A, and an alpha and beta electron in orbital 4A. You could also write the three determinants as 2u00, u200, and u020 with u=spin-up, d=spin-down, 2=doubly occupied, 0=unoccupied.

Since the active orbitals are numbered A2 A3 A4 A5, why not the three determinants as 2u00, 0u20, and 0u02? 3A up-electron not promoted anyhow.

**Comment by JonathonMisiewicz** [comment]
Yes, proposals to create interfaces to external programs are far beyond the scope of this issue. Please make a new one.
