### ISSUE TITLE
Adding atom on top of an existing atom.

### ISSUE THREAD

**Issue by Konjkov** [psi4/psi4#804]
Hello all
I've tried to load molecular geometry from XYZ-file

    3
    0 2
     C         0.000000000000      0.000000000000      0.000000000000
     C         0.000000000000      0.000000000000      1.211315440000
     H         0.000000000000      0.000000000000      2.275843410000

charge = 0 multiplicity = 2

my input

    memory 2 Gb
    qmol = qcdb.Molecule.init_with_xyz('mol.xyz')
    lmol = geometry(qmol.create_psi4_string_from_molecule())
    set basis cc-pVQZ
    set reference uhf
    hf_e, hf_wfn = energy('scf', return_wfn=True)
    molden(hf_wfn, 'molden.dat')

I've got the following issue:

```
Traceback (most recent call last):
  File "/home/vladimir/psi4conda/bin/psi4", line 248, in <module>
    exec(content)
  File "<string>", line 21, in <module>
  File "/home/vladimir/psi4conda/lib//python3.5/site-packages/psi4/driver/qcdb/molecule.py", line 147, in init_with_xyz
    instance.add_atom(el2z[fileAtom], fileX, fileY, fileZ, fileAtom, el2mass[fileAtom], el2z[fileAtom])
  File "/home/vladimir/psi4conda/lib//python3.5/site-packages/psi4/driver/qcdb/libmintsmolecule.py", line 1173, in add_atom
    raise ValidationError("Molecule::add_atom: Adding atom on top of an existing atom.")
```
this exception raises after H atom insertions.
my version Git: Rev {HEAD} add49b9

when I rearranged my XYZ-file to the following

    3
    0 2
     H         0.000000000000      0.000000000000      2.275843410000
     C         0.000000000000      0.000000000000      0.000000000000
     C         0.000000000000      0.000000000000      1.211315440000

all works fine.

Best wishes, Vladimir.

**Comment by loriab** [comment]
Yes, this is an embarrassing but rare known issue. It's not unalike the problem mentioned in #782 where geometry updates were interpreted in a different frame from internal representation leading to surprise results. Only in this case it's a units problem. There isn't a ready solution, so it's simply in mind to be fixed at next Mol spec iteration (in progress). If you hit it in the meantime, just toggle [this line](https://github.com/psi4/psi4/blob/master/psi4/driver/qcdb/libmintsmolecule.py#L1165) with `if True:` (and re-make to copy the file); it's harmless so long as your input geometry doesn't actually have overlapping atoms. The class was designed better than this; there was a later decision that leads to this error popping up.

**Comment by loriab** [comment]
We're switching to a consider-all-molecule-at-once test to validate input geometries rather than the present each-atom-at-a-time. The `Adding atom on top of an existing atom` check is thus unneeded and just causes very rare trouble. It has been silenced (though I can't find in which PR).
