### ISSUE TITLE
Cube file units?

### ISSUE THREAD

**Issue by ibell** [psi4/psi4#815]
While I love the fact that you can output cube files and display the density and ESP in tandem in tools like paraview or VMD, I'm at a bit at a loss to understand the units of the density and ESP values that I am getting back.  From my preliminary analysis, it seems the ESP has units of MJ/mol, and the electron density is in electrons/au^3.  We should document this and not leave it up to guesswork.

I would propose that we:
a) Update the documentation for the cubeprop page with the units of the things that you can get back
b) Update the cube files that are generated with the units of the things that are in the cube file; the first two lines in the cube file spec are for metadata, and we could certainly for instance have a second line that reads like:
```
Property: Dt [electrons/au^3]
```
instead of 
```
Property: Dt
```

**Comment by dgasmith** [comment]
Sounds like a good plan, looks like the units should be in natural units since we are not applying conversion factors. @fevangelista may be a better person to comment.

1) Docs for cube prop can be found [here](https://github.com/psi4/psi4/blob/master/doc/sphinxman/source/cubeprop.rst).
b) Looks like editing these keys or lines [here](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libcubeprop/cubeprop.cc#L202) will change the name header.

**Comment by ibell** [comment]
If someone can confirm what the units are, or how they should be described,
I'm happy to update the docs and the code

**Comment by andysim** [comment]
The units should be a.u. throughout (e/a0^3 for density, as you stated above, and Eh/e for the potential).  Thanks for pointing this shortcoming out and for the offer of help.

**Comment by fevangelista** [comment]
Thanks @andysim for reporting the units, I agree all should be in a.u.

**Comment by ianhbell** [comment]
What are a0 and Eh (maybe obvious, but I come from macro molecular modeling)?

**Comment by robertodr** [comment]
Eh (Hartree energy) is the [atomic unit of energy](https://physics.nist.gov/cgi-bin/cuu/Value?thr), while a0 (Bohr radius) is the [atomic unit of length](https://physics.nist.gov/cgi-bin/cuu/Value?tbohrrada0|search_for=nonsi_in!)

**Comment by dgasmith** [comment]
Fixed in #864. @ianhbell please let us know if that works for you. Closing for now.

**Comment by ianhbell** [comment]
Yes, this seems good from reading the code, but I haven’t tried it in the real world.  Sorry I didn’t get around to fixing this myself, but your solution(s) seem much better than whatever hack I would have come up with.

Especially like the isocontour that contains XX% of the electron density PDF modification.  When will that make it into the master?

**Comment by dgasmith** [comment]
We pulled it in today. A fresh pull and rebuild should have these changes for you. 

-Daniel Smith
