### ISSUE TITLE
Support for Br in SG-1 Grid in wB97M-V calculation

### ISSUE THREAD

**Issue by amlimaye** [psi4/psi4#827]
Hi,

When I submit a wB97M-V calculation using the SG-1 grid (recommended in the wB97M-V paper: http://aip.scitation.org/doi/10.1063/1.4952647), I receive the following error:

```RuntimeError: 
Fatal Error: There is no SG-1 grid defined for the requested atomic number!
Error occurred in file: /tmp/garden-install.fcce11d8cfbe/psi4-1.1-desres05-c7/psi4/src/psi4/libfock/cubature.cc on line: 2488
The most recent 5 function calls were:

psi::MolecularGrid::buildGridFromOptions(psi::MolecularGrid::MolecularGridOptions const&)
psi::DFTGrid::buildGridFromOptions(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >)
psi::DFTGrid::DFTGrid(std::shared_ptr<psi::Molecule>, std::shared_ptr<psi::BasisSet>, psi::Options&)


*** Psi4 encountered an error. Buy a developer more coffee!
*** Resources and help at github.com/psi4/psi4.
```

Are there plans to include support for the SG-1 grid in Psi4? If not, are there any alternative grids that do work? _Removing_ the SG-1 option from the input file simply results in a segfault.

The input file is below:

```
memory 13500 Mb
molecule {
  0 1
  C 4.067369 -2.240127 -0.129252
  C 4.972458 -1.390566 3.098494
  C 2.921005 -1.630865 0.608144
  C 2.878286 -1.651992 2.002187
  C 0.763829 -0.484138 1.955055
  C 1.885141 -1.036307 -0.112440
  C 1.799700 -1.078640 2.675676
  C 0.806556 -0.463011 0.561006
  O 3.881939 -2.228505 2.721026
  Br -0.697406 0.294370 2.866925
  H 4.856028 -1.495441 -0.288527
  H 4.492277 -3.085465 0.426246
  H 3.750214 -2.627370 -1.105706
  H 5.701654 -1.973847 3.666076
  H 4.602203 -0.560418 3.705314
  H 5.446916 -0.996749 2.196547
  H 1.908587 -1.015574 -1.198747
  H 1.775186 -1.100057 3.762739
  H 0.006619 -0.004988 -0.014918
}
set dft_radial_points 99
set dft_spherical_points 590
set dft_grid_name SG1
set dft_nuclear_scheme treutler
set dft_radial_scheme EM
set basis def2-TZVPPD
ENE=energy("wB97M-V")
```

I'm running with a slightly old commit from 09/19 (92b4c55b7171ba48520f91b5344cdcfe99cedc2f). My apologies if the problem has already been fixed in a more recent commit, though it doesn't seem like it based on reading through the diffs of commits with relevant messages.

Thanks!
Aditya

**Comment by susilehtola** [comment]
SG-1 is a pruned (50,194) grid, so you can just use (50,194) for the same results.

**Comment by dgasmith** [comment]
VV10 occasionally fails due to a differences in required temporary sizes. Switching grids is unlikely to help unless you get a bit lucky in the fuzzy Voronoi cell creation. Somewhat interestingly I was hacking on this a bit yesterday and fixed the issue. I will open a PR today if I have a moment.

**Comment by dgasmith** [comment]
The input file without the `SG1` spec is fixed in #832 . As a note when you set `dft_grid_...` you are specifying the DFT grid, and not the VV10 grid which is specified through `DFT_VV10_SPHERICAL_POINTS` and `DFT_VV10_RADIAL_POINTS`. As the VV10 grid can be dramatically smaller than the general DFT grid this is quite beneficial. 

We actually run a (50, 146) grid by default *without* pruning the large radial points which gives results that are basically the same as SG-1.

**Comment by amlimaye** [comment]
Thanks for the fix!

This is more of a methods question, but the wB97M-V paper suggests using a (99, 590) grid for their "fine" grid quality. Does (50, 146) above refer to the VV10 grid points?

**Comment by susilehtola** [comment]
The wB97M-V paper gives these recommendations
• fine: (99,590)/SG-1
• medium: (75,590)/SG-1
• coarse: (75,302)/SG-0
where the first is the DFT grid and the latter is the VV10 grid. I think the same recommendations are also valid for B97M-V.

SG-1 is a pruned (50,194) grid, whereas SG-0 is a pruned (26,170) grid (for second-row - it uses 23 radial points for first-row). However, SG-0 uses MultiExp radial quadrature, so a (26,170) grid in Psi4 might not be a full match.

**Comment by amlimaye** [comment]
Awesome, that's very clear. Thank you all for the timely and descriptive answers!
