### ISSUE TITLE
Add fno variants of detci

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4#829]
Because the fno code is an efficient implementation of mp2 natural orbitals, it'd make a whole lot of sense to have "fno" variants of detci keywords, which would just trigger the detci calculation in the MP2 NO basis. The better starting guess would make CASSCF and RASSCF calculations converge a lot more quickly.

**Comment by dgasmith** [comment]
`set MCSCF_GUESS MP2` uses MP2 natural orbitals.

**Comment by susilehtola** [comment]
Oh look at that; I wonder how I've managed to miss that.

However, the documentation states "MP2 natural orbitals only available for DF-RHF reference". Does the fno code have these restrictions?

**Comment by susilehtola** [comment]
Is that a new option? It's doesn't seem to have an effect in version 1.1.
```
molecule {
-1 1
  Mn       -5.8534733333    1.3394733837   -0.4649497438
  O        -4.6678229246    2.7275455154   -0.8242237964
  H        -4.6340746874    3.3845395668   -0.1494211065
  O        -7.2789168965    2.1411811086    0.4215893334
  H        -7.8199772787    1.5357569391    0.8999611740
  O        -5.3067672331   -0.0431310925    0.6533689515
  H        -4.7858036361   -0.6983214503    0.2203485236
  O        -6.1585656429    0.5314683638   -2.1129873999
  H        -6.1687683674    1.1358176653   -2.8360759358
}

set basis aug-pcseg-0
set reference rhf
set ci_maxiter 100
set scf_type df
set mcscf_type df
set nat_orbs true

scf_e, scf_wfn = energy('scf', return_wfn = True)

# 31 occ orbs
set restricted_docc [ 26 ]
set active [10]
set mcscf_algorithm ah
set mcscf_guess mp2
cas_e, cas_wfn = energy('casscf', ref_wfn = scf_wfn, return_wfn = True)
```

**Comment by dgasmith** [comment]
If you pass in a reference wavefunction we assume that you have set the guess as you would like it and those keywords are ignored. You can use MP2 NO's by running the following:

```
psi4.core.set_global_option('ONEPDM', True)
psi4.core.set_global_option('OPDM_RELAX', False)
mp2_e, ref_wfn = psi4.gradient("MP2", return_wfn=True)
```

Odd I know and I agree that we need a generic MP2 natural orbital module, but we simply have not gotten there yet.

@bozkaya Do you have ROHF MP2 densities?

**Comment by dgasmith** [comment]
Closing this one out. ROHF is on a TODO list and we will hook it in if we get there.
