### ISSUE TITLE
FullCI H2 fails in loop

### ISSUE THREAD

**Issue by wpoely86** [psi4/psi4#83]
I've got trouble calculation H2:
```python
import numpy as np
memory 50 Gb

molecule H2 {
    0 1
    H
    H  1  R
    units au
}

set {
    SCF_TYPE PK
    diag_method rsp
    MAXITER 40
    NUM_ROOTS 5
    basis cc-pvdz
}

rlist = np.arange(1.00, 10.1, 0.1)

for r in rlist:
    H2.R = r
    energy('fci')
```
It calculates the first point and then I get:
```python
PSIO_ERROR: unit = 53, errval = 13
PSIO_ERROR: 13 (no such TOC entry)
Traceback (most recent call last):
  File "<string>", line 36, in <module>
  File "share/psi/python/driver.py", line 576, in energy
    procedures['energy'][lowername](lowername, **kwargs)
  File "share/psi/python/proc.py", line 1969, in run_detci
    psi4.detci()
RuntimeError: PSIO Error
```
This is done with 14c78eab

**Comment by loriab** [comment]
Confirmed, though I think it's not even finishing off the first R=1.0 point. The problem seems to be with managing binary files whenever NUM_ROOTS > 1. I'll refer that to @CDSherrill . On another note, your 0.1 point will fail as being too close together. If you really want that to run, I can investigate.

**Comment by loriab** [comment]
@CDSherrill Here's a numpy-free input, should you want to test. Problem is NUM_ROOTS, not loop or zmat.

```
memory 20 Gb

molecule H2 {
    0 1
    He
    He  1  R
    units au
}

set {
    SCF_TYPE PK
    diag_method rsp
    MAXITER 40
##    NUM_ROOTS 5
    basis cc-pvdz
    num_roots 2  # toggle this on/off for badness
}

rlist = [1.00, 10.1, 0.5]

for r in rlist:
    H2.R = r
    energy('fci')  # or cisd
```

**Comment by wpoely86** [comment]
@loriab You can also drop the loop and just put `H2.R=1`.  Futhermore, add `OPDM yes` and even with `num_roots 1`, it will give the same error.  So there's probably an error in saving the eigenvectors.

I don't need the 0.1 point, the np.arange command will give a list starting at 1.0 and increasing with 0.1 until 10.

**Comment by loriab** [comment]
Thanks for the ``opdm yes`` notice. Along with ``nat_orbs_write true`` that we've also seen, this forms a trio of file-handling problems in detci that are on the agenda to be addressed.

**Comment by ryanmrichard** [comment]
Still a problem with new CI code.  Full error:
```
PSIO_ERROR: Can't find TOC Entry buffer_ 0
PSIO_ERROR: unit = 53, errval = 13
PSIO_ERROR: 13 (no such TOC entry)
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "/theoryfs2/ds/richard/SrcFiles/psi4clean/lib/python/driver.py", line 647, in energy
    procedures['energy'][lowername](lowername, **kwargs)
  File "/theoryfs2/ds/richard/SrcFiles/psi4clean/lib/python/proc.py", line 2797, in run_detci
    psi4.detci()
RuntimeError: 
Fatal Error: PSIO Error
Error occurred in file: /theoryfs2/ds/richard/SrcFiles/psi4clean/src/lib/libpsio/error.cc on line: 123
The most recent 5 function calls were:

psi::PsiException::PsiException(std::string, char const*, int)
psi::psio_error(unsigned int, unsigned int)
psi::PSIO::read(unsigned int, char const*, char*, unsigned long, psi::psio_address, psi::psio_address*)
psi::psio_read(unsigned int, char const*, char*, unsigned long, psi::psio_address, psi::psio_address*)
psi::psio_read_entry(unsigned int, char const*, char*, unsigned long)
```

**Comment by dgasmith** [comment]
Yes, the CIVector was never written so when the OPDM code wanted this from disk we saw the above error.

@wpoely86 I have been making another pass at the CI code to clean up outstanding issues. Besides the issues already posted here to GitHub do you have any other requests/suggestions/problems?

**Comment by wpoely86** [comment]
@dgasmith no, my issues are all on github.
