### ISSUE TITLE
oeprop("GRID_ESP", "GRID_FIELD") fails for certain basis sets

### ISSUE THREAD

**Issue by mj-harvey** [psi4/psi4#84]
Hi,

Against a build of HEAD, using the following input:

```
set basis  $BASIS_SET$

molecule MOL {
  0 1
  C    0.0   0.00000   0.00000
	symmetry c1
}

energy('scf')
oeprop("GRID_ESP", "GRID_FIELD")
```
When $BASIS_SET$ is set to "6-31G*",  PSI4 runs to completion, correctly outputting grid_esp.dat and grid_field.dat files. However, when set to "cc-pvdz", PSI4 fails in oeprop(), with the errror:

```
Traceback (most recent call last):
  File "<string>", line 22, in <module>
  File "/usr/local/psi4/share/psi//python/p4util/util.py", line 46, in oeprop
    oe.compute()
RuntimeError: Matrix::vector_dot: Dimensions do not match!

```

**Comment by andysim** [comment]
Hmmm.  Looks like something I introduced with the changes to OEProp.  It's almost certainly an issue related to combining AO and SO dimensions somewhere.  I'll fish through the code, hopefully by the weekend, and try to find the culprit.  Thanks for the detailed feedback,

Andy.

**Comment by mj-harvey** [comment]
Thanks @andysim. Where you able to track down the fault?

**Comment by andysim** [comment]
Sorry it took me so long; I've been traveling quite a bit for work, and didn't get time to look into the problem.  I believe I found the culprit, and just pushed a fix into the repo.  Could you please test it with a basis that uses spherical harmonics (e.g. cc-pVDZ) and let me know if you get the expected results?  Sorry again for my tardiness in fixing this problem.

Andy.

**Comment by dgasmith** [comment]
@mj-harvey Works for me in basis up to a6Z and with cases where `nao != nso`.

Going to close this for now. Let us know if you see other issues.
