### ISSUE TITLE
Incorrect ghosting behavior for Iodine interaction energy calculations

### ISSUE THREAD

**Issue by amlimaye** [psi4/psi4#843]
Hi, I noticed some odd ghosting behavior when doing interaction energy calculations on molecules containing Iodine. 

When manually doing the counterpoise correction for a non-I-containing molecule, Psi4 reads the ghosted atoms properly and computes a sensible interaction energy  (see `correctly-ghosted.txt`).

However, when manually doing the counterpoise correction for an I-containing molecule, Psi4 does not ghost the atoms at all, and does the exact same calculation three times, resulting in an incorrect interaction energy (see `incorrectly-ghosted.txt`).

The (much easier) workaround here is to counterpoise correct using the bsse_type="cp" interface, but I wanted to bring this to your attention anyways.

[correctly-ghosted.txt](https://github.com/psi4/psi4/files/1458283/correctly-ghosted.txt)
[incorrectly-ghosted.txt](https://github.com/psi4/psi4/files/1458284/incorrectly-ghosted.txt)

Thanks!

**Comment by dgasmith** [comment]
Hmm, that is odd. The `bsse_type` uses the `Molecule.extract_subsets` interface and gets around this a bit. @shannonhouck Do you think you could explore this a bit?

**Comment by hokru** [comment]
This has something to do with ECPs and not iodine. If the basis contains ECPs, the ghost atom are not recognized, i.e. not printed as ghost atoms in the geometry summary at the start. Separately tested it with a water dimer and an oxygen ECP.

**Comment by dgasmith** [comment]
It looks like the code is finding the ghosts correctly?

```
       Center              X                  Y                   Z               Mass
    ------------   -----------------  -----------------  -----------------  -----------------
          XE(Gh)      0.000000000000     0.000000000000    -0.465039721145   131.904153457000
          AR          0.000000000000     0.000000000000     1.534960278855    39.962383122510
```

**Comment by dgasmith** [comment]
Looked into this again, still an issue. Must have something to do with molecule parsing as `mol.get_fragment` works fine as noted.

**Comment by loriab** [comment]
It's actually not in the molecule parsing, as the first `Mol.print_out()` is correct. So somewhere in the driver call. Investigating ...

```
molecule probe {
  @H 0.0 0.0 0.0
  @I 1.5 0.0 0.0
  0 1
  H 0.0 3.0 0.0
  F 1.5 3.0 0.0
noreorient
}
probe.update_geometry()
probe.print_out()
e_probe = energy('hf/def2-svpd')

clean()

molecule probe {
  @H 0.0 0.0 0.0
  @F 1.5 0.0 0.0
  0 1
  H 0.0 3.0 0.0
  F 1.5 3.0 0.0
noreorient
}
probe.update_geometry()
probe.print_out()
e_probe = energy('hf/def2-svpd')
```

**Comment by loriab** [comment]
https://github.com/psi4/psi4/blob/master/psi4/driver/p4util/python_helpers.py#L99

**Comment by loriab** [comment]
Yep, what we have here is a casualty of one of my less favorite topics, the type A vs. type B ghost ([details](https://github.com/psi4/psi4/issues/909#issuecomment-363473061)). By subtracting out the ECP electrons [here](https://github.com/psi4/psi4/blob/master/psi4/src/export_mints.cc#L182) and resetting `Z`, it's wiping out the only evidence of those atoms being ghosted (compare `gh=1` for extract_subsets ghosting vs. `gh=0` for `@/Gh()` ghosting). Printing is `printf("ECP: preZ=%f   TAN=%d - ncore=%d = Z=%d gh=%d\n", mol->Z(atom), mol->true_atomic_number(atom), ncore, Z, mol->atom_entry(atom)->is_ghosted());`

```
# @/Gh() ghosted
ECP: preZ=0.000000   TAN=1 - ncore=0 = Z=1 gh=0
ECP: preZ=0.000000   TAN=53 - ncore=28 = Z=25 gh=0
ECP: preZ=1.000000   TAN=1 - ncore=0 = Z=1 gh=0
ECP: preZ=53.000000   TAN=53 - ncore=28 = Z=25 gh=0
# extract_subsets ghosted
ECP: preZ=0.000000   TAN=1 - ncore=0 = Z=1 gh=1
ECP: preZ=0.000000   TAN=53 - ncore=28 = Z=25 gh=1
ECP: preZ=1.000000   TAN=1 - ncore=0 = Z=1 gh=0
ECP: preZ=53.000000   TAN=53 - ncore=28 = Z=25 gh=0
>>> grep 'Final E' i843_c.out 
  @DF-RHF Final Energy:  -594.38702051330188
  @DF-RHF Final Energy:  -297.22774750033528
```

```
memory 1800 Mb
set guess core

molecule probe1 {
  @H 0.0 0.0 0.0
  @I 1.5 0.0 0.0
  H 0.0 3.0 0.0
  I 1.5 3.0 0.0
symmetry c1
noreorient
}
probe1.update_geometry()
probe1.print_out()
e_probe = energy('hf/def2-svpd')

clean()

molecule probe3 {
  H 0.0 0.0 0.0
  I 1.5 0.0 0.0
  --
  H 0.0 3.0 0.0
  I 1.5 3.0 0.0
symmetry c1
noreorient
}
probe3.update_geometry()
probe3gh = probe3.extract_subsets(2, 1)
probe3gh.update_geometry()
probe3gh.print_out()
e_probe = energy('hf/def2-svpd')
```
