### ISSUE TITLE
Stray .cmake files are installed

### ISSUE THREAD

**Issue by yurivict** [psi4/psi4#855]
The build installs these files:
```
Error: Orphaned: /usr/ports/science/psi4/work/.build/stage/usr/local/share/cmake/TargetHDF5/TargetHDF5Config.cmake
Error: Orphaned: /usr/ports/science/psi4/work/.build/stage/usr/local/share/cmake/TargetHDF5/TargetHDF5ConfigVersion.cmake
Error: Orphaned: /usr/ports/science/psi4/work/.build/stage/usr/local/share/cmake/TargetHDF5/TargetHDF5Targets.cmake
Error: Orphaned: /usr/ports/science/psi4/work/.build/stage/usr/local/share/cmake/TargetLAPACK/TargetLAPACKConfig.cmake
Error: Orphaned: /usr/ports/science/psi4/work/.build/stage/usr/local/share/cmake/TargetLAPACK/TargetLAPACKTargets.cmake
```

Each one is already installed into the proper location, ex. ```
/usr/local/share/cmake/TargetHDF5/TargetHDF5Config.cmake```

For some reason, it installs duplicates copies into locations derived from the build directory path (?).

@loriab Maybe you know how to fix it?

**Comment by loriab** [comment]
How did `TargetHDF5Config.cmake`, etc. even get into `/usr/local/` except through a Psi4 install? Or possibly libefp or CheMPS2 install? Those are just CMake target wrappings around HDF5 and LAPACK detections. If you're not wanting Psi to install those (they're mainly for info sharing w/i the Psi cmake superbuild), then libefp and chemps2 shouldn't be installing them either.

Just in case it's unclear, every package gets internally installed to `<builddir>/stage/${CMAKE_PREFIX_PATH}`, which is a full-fledged psi installation. The result of user `make install` is to just bodily copy the `stage/` dir into the filesystem.

**Comment by yurivict** [comment]
Normally, they are installed into /usr/local (under stage directory). But these files go into /usr/ports under the same stage directory. It must have ran ```pwd``` or something like that during build/install.

**Comment by loriab** [comment]
I'm not following, I'm afraid. On a build with only pb11 built internally and configured and launched from odd directories to try to provoke a `pwd` issue, these are the only Target files I get under `stage/`, and they seem to be in place and not duplicated.

```
objdir1: (insist) find stage/ -name "*Target*"
stage/usr/local/psi4/share/cmake/TargetLAPACK
stage/usr/local/psi4/share/cmake/TargetLAPACK/TargetLAPACKConfig.cmake
stage/usr/local/psi4/share/cmake/TargetLAPACK/TargetLAPACKTargets.cmake
stage/usr/local/psi4/share/cmake/TargetHDF5
stage/usr/local/psi4/share/cmake/TargetHDF5/TargetHDF5Config.cmake
stage/usr/local/psi4/share/cmake/TargetHDF5/TargetHDF5ConfigVersion.cmake
stage/usr/local/psi4/share/cmake/TargetHDF5/TargetHDF5Targets.cmake
stage/usr/local/psi4/share/cmake/pybind11/pybind11Targets.cmake
stage/usr/local/psi4/share/cmake/psi4/psi4Targets.cmake
stage/usr/local/psi4/share/cmake/psi4/psi4Targets-release.cmake
```

**Comment by yurivict** [comment]
I have libxc and libint bundled, ambit external, the rest is disabled. I get these duplicates under stage/.
I just delete them, but they need to be fixed.

**Comment by loriab** [comment]
I'm not sure how to reproduce this. Please post again if still causing trouble.
