### ISSUE TITLE
Unable to compute torsion value

### ISSUE THREAD

**Issue by ChayaSt** [psi4/psi4#858]
I was running a constrained geometry optimization but the optimizer failed with this error:
```
Back-transformation to cartesian coordinates...
	The INTCO_EXCEPTion handler:
	TORS::compute_val: unable to compute torsion value
	Dynamic level is 0.
	exc.g_really_quit() is 0.

  **** Optimization has failed! (in 3 steps) ****
```

Here's the [input file](https://github.com/ChayaSt/torsionfit_examples/blob/torsion_drive/torsion_drive/biphenyl/phepyr/4_10_11_6/15/phepyr_4_10_11_6_15.dat) and the [output file](https://github.com/ChayaSt/torsionfit_examples/blob/torsion_drive/torsion_drive/biphenyl/phepyr/4_10_11_6/15/phepyr_4_10_11_6_15.out)

I ran it again with `dynamic_level = 1` but this time I got the following error:
```Fatal Error: PSIO Error
Error occurred in file: /scratch/psilocaluser/conda-builds/psi4_1495011512596/work/psi4/src/psi4/libpsio/error.cc on line: 129
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)
psi::psio_error(unsigned int, unsigned int)
psi::PSIO::write(unsigned int, char const*, char*, unsigned long, psi::psio_address, psi::psio_address*)
psi::PSIO::write_entry(unsigned int, char const*, char*, unsigned long)
                                                                                                                      7447,46       99%
```

**Comment by loriab** [comment]
We do hit these errors sometimes. Some special cases have been fixed this year. What version of the code are you running, `psi4 --version`?

It's failing on the backtransformation in the second opt iter. Dihedrals are near 180 to start but no angles are. If up-to-date, any suggestions, @psi-rking ?

**Comment by ChayaSt** [comment]
I'm using version 1.1.

**Comment by psi-rking** [comment]
At the bottom of the output, after 3 steps, many of the torsions are very close to 180.  Is the structure exactly planar?  I'm not surprised if you are not able to converge this tightly.  You could try Cartesian coordinates to avoid all these discontinuities (not just in the value of the torsion, but in its derivative too).

	 D(7,11,6,18)     =        -3.129372	    -179.299795
	 D(8,6,11,10)     =        -3.133590	    -179.541496
	 D(8,12,9,21)     =         3.130680	     179.374777
	 D(9,7,11,10)     =         3.130802	     179.381713
	 D(9,12,8,20)     =         3.137161	     179.746078
	 D(10,4,2,14)     =        -3.130400	    -179.358722

**Comment by ChayaSt** [comment]
Yes, this is a planer structure. Should I set `opt_coordinates = cartesian`? Will that worked with a `fixed_dihedral`?

**Comment by psi-rking** [comment]
Hmmm.  Good question.  There is no good reason that we can't support that,
but I don't know if anyone has ever tried it.

**Comment by ChayaSt** [comment]
I tried running it again with `opt_coordinates = cartesian` with a restrained dihedral and `dynamic_level = 1`. However, it crashed again, this time when it raises dynamic level to 3 it crashed when it tries to write the optimization data to binary file. [Here's](https://github.com/ChayaSt/torsionfit_examples/blob/torsion_drive/torsion_drive/biphenyl/phepyr/4_10_11_6/15/phepyr_4_10_11_6_15.out#L12821-L12831) the traceback:

```
	Writing optimization data to binary file.
	
Fatal Error: PSIO Error
Error occurred in file: /scratch/psilocaluser/conda-builds/psi4_1495011512596/work/psi4/src/psi4/libpsio/error.cc on line: 129
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)
psi::psio_error(unsigned int, unsigned int)
psi::PSIO::write(unsigned int, char const*, char*, unsigned long, psi::psio_address, psi::psio_address*)
psi::PSIO::write_entry(unsigned int, char const*, char*, unsigned long)
psi::psio_write_entry(unsigned int, char const*, char*, unsigned long)
```

Also, it still seems to be using internal coordinates (unless I'm not understanding the output file). 
Here is the new [input](https://github.com/ChayaSt/torsionfit_examples/blob/torsion_drive/torsion_drive/biphenyl/phepyr/4_10_11_6/15/phepyr_4_10_11_6_15.dat) and [output](https://github.com/ChayaSt/torsionfit_examples/blob/torsion_drive/torsion_drive/biphenyl/phepyr/4_10_11_6/15/phepyr_4_10_11_6_15.out)

**Comment by psi-rking** [comment]
I took a closer look at the system.  You are beginning with a geometrical
torsion value of 15 degrees and want to keep it there, apparently.  If you
can build a starting geometry that satisfies the desired constraint, then
you've got better odds of success using "frozen" coordinates.   I tried a
double-zeta HF optimization with frozen_dihedral = "4 10 11 6" with
dynamic_level =1, and the optimization converged within 10 iterations.

**Comment by ChayaSt** [comment]
I tried freezing the cartesian coordinates of the dihedral atoms and it seems to work. The optimization converged within 10 iterations. I also used `consecutive_backsteps = 2` 

```
frozen_string = """
4 xyz
10 xyz
11 xyz
6 xyz
"""
set optking { opt_coordinates = cartesian
              frozen_cartesian = $frozen_string
              consecutive_backsteps = 2
              geom_maxiter = 250
              print_trajectory_xyz_file = True }

optimize('MP2/aug-cc-PVTZ')
```
The starting structure has a torsion value of 15 generated with OpenEye, but it will be a good idea to first optimize using a lower level of theory. I'll try that too.

**Comment by ChayaSt** [comment]
There's a problem I'm noticing though. Both of the calculation were started from the same starting configuration. However, the last geometry in the non converging file has a lower energy than the converged structure which used `frozen cartesian` instead of `frozen_dihedral`. I ran another calculation with a `frozen_dihedral` at 345 degrees (should be very close in energy to 15 degrees) which did converge and that geometry's energy is similar to the last converging geometry in the non converging file.

**Comment by jchodera** [comment]
@psi-rking : Can you elaborate on what the fundamental issue here is? Is it that the internal-to-cartesian coordinate conversion is numerically unstable? Or that there is some other weird saddle point that the minimization converges to instead? If you could point us to the code that needs to be made more robust, we can take a stab at it, but if there's fundamentally no way to converge these kinds of calculations, that would be helpful to know.

Also, isn't this second error unrelated?
```
Error occurred in file: /scratch/psilocaluser/conda-builds/psi4_1495011512596/work/psi4/src/psi4/libpsio/error.cc on line: 129
The most recent 5 function calls were:

psi::PsiException::PsiException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int)
psi::psio_error(unsigned int, unsigned int)
psi::PSIO::write(unsigned int, char const*, char*, unsigned long, psi::psio_address, psi::psio_address*)
psi::PSIO::write_entry(unsigned int, char const*, char*, unsigned long)
```
This seems to be an error in writing rather than an error in the constrained optimization, isn't it?

**Comment by ChayaSt** [comment]
> This seems to be an error in writing rather than an error in the constrained optimization, isn't it?

This error shows up when dynamic level is raised to 3 after the first convergence check when it tries to write optimization data to binary file.

**Comment by psi-rking** [comment]
Agreed, the write error is a bug.  The error is due to the number of
optimization coordinates changing.  When that happens, then the old binary
file should be wiped out, and I guess it is not being removed.  It is
possible this bug has been fixed in the latest version as we have looked at
this problem before, but I'm not sure.

The 'dynamic_level' idea is still under development, and hasn't been much
tested.
If you look in /psi4/psi4/src/psi4/optking/set_params.cc, you can see what
the dynamic level is doing.  It is changing parameters towards typically
more robust levels.  You can do the same thing by changing input keywords.
For example, the behavior of dynamic_level=3 shown there can be produced by
setting the analogous keywords.

      Opt_params.coordinates = OPT_PARAMS::BOTH;

      Opt_params.consecutive_backsteps_allowed = 1;

      Opt_params.step_type = OPT_PARAMS::RFO;

      Opt_params.intrafragment_step_limit = 0.1;

      Opt_params.intrafragment_step_limit_min = 0.1;

      Opt_params.intrafragment_step_limit_max = 0.1;

All this to say that you can skip the dynamic_level usage (or simply start
with dynamic_level = 3 [don't know if anyone has ever done that!] and I
expect the i/o error will go away.

On the stability of the back-transformation, optking accounts for Delta(q)
for a torsion value going from -178 to +178 degrees, etc..  However, the
formula for the derivative (B-matrix element) is undefined and also
discontinuous at 180.  A real pain.  I hope to try to fix this someday, but
when I do, it'll probably be in the newer python optimizer I'm developing.

**Comment by ChayaSt** [comment]
When setting `dynamic_level = 3` with the same input script initially posted here (where frozen dihedral was used) the geometry converged after 12 iterations with dynamic level 3 and 3 iterations at dynamic level 4.

**Comment by dgasmith** [comment]
After discussion with @ChayaSt this is handled via other means and is a deprecated issue.
