### ISSUE TITLE
Analytical gradient with wB97X

### ISSUE THREAD

**Issue by raimis** [psi4/psi4#867]
Compute numerical and analytical gradients with **wB97X** functional:
```python
import psi4

print(psi4.__version__)

psi4.geometry('H -.5 0 0\nH .5 0 0')
psi4.gradient('wb97x/3-21g', dertype=0)
psi4.gradient('wb97x/3-21g', dertype=1)
```

The numerical gradient works, but analytical one crashes:
```
1.2a1.dev681
gradient() will perform gradient computation by finite difference of analytic energies.

... skipped ...

  ## F-D gradient (Symmetry 0) ##
  Irrep: 1 Size: 2 x 3

                 1                   2                   3

    1    -0.08957282148820     0.00000000000000     0.00000000000000
    2     0.08957282148820     0.00000000000000     0.00000000000000


Traceback (most recent call last):
  File "test.py", line 7, in <module>
    psi4.gradient('wb97x/3-21g', dertype=1)
  File "/home/raimis/opt/miniconda3/envs/ani_test/lib/python3.6/site-packages/psi4/driver/driver.py", line 549, in gradient
    dertype = min([_find_derivative_type('gradient', method, user_dertype) for method in cbs_methods])
  File "/home/raimis/opt/miniconda3/envs/ani_test/lib/python3.6/site-packages/psi4/driver/driver.py", line 549, in <listcomp>
    dertype = min([_find_derivative_type('gradient', method, user_dertype) for method in cbs_methods])
  File "/home/raimis/opt/miniconda3/envs/ani_test/lib/python3.6/site-packages/psi4/driver/driver.py", line 103, in _find_derivative_type
    % (method_name, str(dertype), alternatives))
psi4.driver.p4util.exceptions.ValidationError: Derivative method 'name' wb97x and derivative level 'dertype' 1 are not available. Did you mean? b97 wb97 wb97x wb97x-v wb97x-d
```

Also, the error message is self-contradicting:
```
psi4.driver.p4util.exceptions.ValidationError: Derivative method 'name' wb97x and derivative level 'dertype' 1 are not available. Did you mean? b97 wb97 wb97x wb97x-v wb97x-d
```

According to https://gitlab.com/libxc/libxc/wikis/Functionals-list-3.0.0, **libXC** supports **wB97X** and I don't see any notes that the analytical gradient is not implemented. So I guess, the problem is somewhere in **Psi4**.

**Comment by hokru** [comment]
there are no `scf_type df` gradients for RSH functionals. There should be for direct SCF through, albeit that is not recognized in the driver.

**Comment by hokru** [comment]
You can run it like this:
```
set scf_type direct
energy('scf',df_functional='wb97x')

```
 But first I would carefully compare if the gradient is actually OK.

**Comment by raimis** [comment]
Hi @hokru 

Thanks for a quick response!

Using your suggestion, the density-fitted and direct gradients seems to be working:
```python
import psi4

print(psi4.__version__)

psi4.geometry('H -.5 0 0\nH .5 0 0')

psi4.set_options({'scf_type': 'df'})
psi4.gradient('scf/3-21g', df_functional='wb97x', dertype=1)

psi4.set_options({'scf_type': 'direct'})
psi4.gradient('scf/3-21g', df_functional='wb97x', dertype=1)
```
```
1.2a1.dev681
... skipped ...

  ==> DFJKGrad: Density-Fitted SCF Gradients <==

    Gradient:                    1
    J tasked:                  Yes
    K tasked:                  Yes
    wK tasked:                  No
    OpenMP threads:              1
    Integrals threads:           1
    Memory (MB):               375
    Schwarz Cutoff:          0E+00
    Fitting Condition:       1E-12

   => Auxiliary Basis Set <=

  Basis Set: (3-21G AUX)
    Blend: DEF2-SVP-JKFIT
    Number of shells: 12
    Number of basis function: 40
    Number of Cartesian functions: 40
    Spherical Harmonics?: false
    Max angular momentum: 2


  -Total Gradient:
     Atom            X                  Y                   Z
    ------   -----------------  -----------------  -----------------
       1       -0.097845194473    -0.000000000000     0.000000000000
       2        0.097845194473     0.000000000000     0.000000000000

... skipped ...

  ==> DirectJKGrad: Integral-Direct SCF Gradients <==

    Gradient:                    1
    J tasked:                  Yes
    K tasked:                  Yes
    wK tasked:                  No
    Integrals threads:           1
    Schwarz Cutoff:          0E+00


  -Total Gradient:
     Atom            X                  Y                   Z
    ------   -----------------  -----------------  -----------------
       1       -0.097852807518    -0.000000000000     0.000000000000
       2        0.097852807518     0.000000000000     0.000000000000

... skipped ...
```

So, assuming, the numerical gradient matches, it is suitable for production, isn't?

**Comment by hokru** [comment]
I had a typo! You did maybe only HF.

```
import psi4


psi4.geometry('H -.5 0 0\nH .5 0 0')

set global {
basis def2-SVP
scf_type direct
}

num=gradient('scf',dft_functional='wb97x',dertype=0)
ana=gradient('scf',dft_functional='wb97x',dertype=1)
compare_matrices(ana, num, 5, "LR grad")

```
That seems to pass with 5 decimals at least.
I would test a larger molecule, though.

**Comment by dgasmith** [comment]
The reason its bouncing is we are not entirely sure the range-seperatated gradients are correct. This admittedly could use a better error message.

On `psi4.gradient('scf/3-21g', df_functional='wb97x', dertype=1)` I think this shows a need to scan for valid `kwargs`. This could be difficult to do however.

**Comment by raimis** [comment]
@hokru Thanks! I'll try to test with bigger molecules.

**Comment by dgasmith** [comment]
So to reiterate, you are circumventing a safety feature of Psi4 this way. The analytical gradients are very likely wrong.

**Comment by raimis** [comment]
@hokru and @dgasmith 

I tested the analytic and numeric gradients with 100 molecules using wB97X-D and B3LYP (for reference).

![anal_vs_grad_wb97x-d](https://user-images.githubusercontent.com/2469715/33882176-8d09a24e-df37-11e7-9aee-3a6a4530d4a9.png)

Sample: 4512
MaxAE 0.002127
MSE -0.000000
MAE 0.000039
RMSE 0.000089

![anal_vs_grad_b3lyp](https://user-images.githubusercontent.com/2469715/33882181-8f7b6972-df37-11e7-8377-358eb436c824.png)

Sample: 4512
MaxAE 0.000631
MSE -0.000000
MAE 0.000016
RMSE 0.000031

There is no systematic error in both cases, but wB97X-D results are more skewed. Do you think, it is just numerics or indication of a more serious problem?

**Comment by dgasmith** [comment]
AFAIK, these were turned off because we believed there was a bug in them. I do find this a bit odd as wK should be identical to K.  @loriab or @andysim may remember exactly what was happening then.

**Comment by andysim** [comment]
Thank you very much for looking into this, @raimis - especially the detailed benchmarks.  If my memories from way back (circa 2010) are correct, @robparrish and I were trying to write a prototype  DF gradient code and hit a very strange error.  The finite difference tests we did for hybrids all looked good, but for range-separated functionals we were getting quite large noise.  The direct range-separated code worked fine, confirming that the derivative integrals were correct, and pointing the fact that we somehow messed up the chain rule in our haste.  Since then Rob did a complete rewrite of the entire SCF machinery and made it infinitely better so, inspired by your detailed comments, I decided to revisit.  This input

```
memory 6Gb

molecule C4NH4 {
  -1 1
  C         0.00000000     0.00000000     2.13868804
  N         0.00000000     0.00000000     4.42197911
  C         0.00000000     0.00000000    -0.46134192
  C        -1.47758582     0.00000000    -2.82593059
  C         1.47758582     0.00000000    -2.82593059
  H        -2.41269553    -1.74021190    -3.52915989
  H        -2.41269553     1.74021190    -3.52915989
  H         2.41269553     1.74021190    -3.52915989
  H         2.41269553    -1.74021190    -3.52915989
  units bohr
}

set {
    basis 6-31G
    d_convergence 11
    points 5
}

anl = gradient('scf', df_functional='wB97X-D', dertype=1)
num = gradient('scf', df_functional='wB97X-D', dertype=0)

anl.print_out()
num.print_out()
```

Yields the following analytic/numerical grads for B3LYP:
```
  ## Total Gradient (Symmetry 0) ##
  Irrep: 1 Size: 9 x 3

                 1                   2                   3

    1     0.00000000000000    -0.00000000000000     0.01448961501491
    2     0.00000000000000     0.00000000000000     0.00650495770571
    3     0.00000000000000    -0.00000000000000    -0.01465457276700
    4    -0.00257733094550    -0.00000000000000    -0.00299790291405
    5     0.00257733094550     0.00000000000000    -0.00299790291405
    6    -0.00015263631139    -0.00478910772840    -0.00008555938077
    7    -0.00015263631139     0.00478910772840    -0.00008555938077
    8     0.00015263631139     0.00478910772840    -0.00008555938077
    9     0.00015263631139    -0.00478910772840    -0.00008555938077



  ## F-D gradient (Symmetry 0) ##
  Irrep: 1 Size: 9 x 3

                 1                   2                   3

    1     0.00000000000000     0.00000000000000     0.01448679231786
    2     0.00000000000000     0.00000000000000     0.00650780527423
    3     0.00000000000000     0.00000000000000    -0.01467048755060
    4    -0.00257410227128     0.00000000000000    -0.00298989706945
    5     0.00257410227128     0.00000000000000    -0.00298989706945
    6    -0.00015309842746    -0.00478900518843    -0.00008607897565
    7    -0.00015309842746     0.00478900518843    -0.00008607897565
    8     0.00015309842746     0.00478900518843    -0.00008607897565
    9     0.00015309842746    -0.00478900518843    -0.00008607897565
```

and thse for wB97X-D:
```
  ## Total Gradient (Symmetry 0) ##
  Irrep: 1 Size: 9 x 3

                 1                   2                   3

    1     0.00000000000000     0.00000000000000    -0.02530663408790
    2     0.00000000000000    -0.00000000000000     0.06073552407916
    3     0.00000000000000    -0.00000000000000    -0.01910268412068
    4     0.00053727899697     0.00000000000000     0.00185002606365
    5    -0.00053727899697    -0.00000000000000     0.00185002606365
    6    -0.00554076664310    -0.01384288220048    -0.00500656449972
    7    -0.00554076664310     0.01384288220048    -0.00500656449972
    8     0.00554076664310     0.01384288220048    -0.00500656449972
    9     0.00554076664310    -0.01384288220048    -0.00500656449972



  ## F-D gradient (Symmetry 0) ##
  Irrep: 1 Size: 9 x 3

                 1                   2                   3

    1     0.00000000000000     0.00000000000000    -0.02530648968490
    2     0.00000000000000     0.00000000000000     0.06073503270434
    3     0.00000000000000     0.00000000000000    -0.01910251844802
    4     0.00053728999275     0.00000000000000     0.00185009324839
    5    -0.00053728999275     0.00000000000000     0.00185009324839
    6    -0.00554074931312    -0.01384287705163    -0.00500655276705
    7    -0.00554074931312     0.01384287705163    -0.00500655276705
    8     0.00554074931312     0.01384287705163    -0.00500655276705
    9     0.00554074931312    -0.01384287705163    -0.00500655276705
```

I'd actually expect slightly better agreement out of a 5 point finite difference stencil, but I'm willing to say that the gradient bug was fixed and we just never removed the safety check.  I know I'm asking you to go way back here, @robparrish , but is this consistent with your memory of this code development?

**Comment by CDSherrill** [comment]
@wardence has seen what look like small errors in Hartree-Fock analytic
gradients in high-symmetry molecules that make me wonder if we have some
small noise coming from our general SCF gradient machinery.  She is hoping
to post an issue on that as soon as she gets a little free time.  This
might be a cause of the occasional small differences between analytic and
finite difference gradients observed by @raimis.  @raimis, were your tests
run with a 3 point finite difference stencil, or 5 points?  5 points should
be more numerically stable (probably good to also crank up d_convergence
like @andysim did).

The check done by @andysim looks pretty clean to me and suggest that, at
least for this test case, the wB97X-D gradients are fine.

**Comment by andysim** [comment]
I think that a little noise in the gradients is inevitable with so many moving parts; that's why we have calls like [this](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/scfgrad/scf_grad.cc#L274-L275) for all (I think) gradients throughout the code.  It sounds like we just need to consider non-Abelian symmetry in this routine to fix the issue you're describing

**Comment by CDSherrill** [comment]
Yes, the symmetrize call is nice and should help cleanup any inevitable
small numerical noise.  Would be great if it could be extended to
non-Abelian point groups!  But the noise @wardence is seeing looks a bit
more serious than just roundoff error.  (Sorry to tease an issue before it
gets posted.)

**Comment by raimis** [comment]
@CDSherrill, I did the tests with the 3-point finite differences and the default convergence.

@andysim, your input has a misspelled keyword `df_functional` in stead of `dft_functional`. The same mistake I had, which runs just HF, as @hokru pointed out.

**Comment by hokru** [comment]
Firstly, wow, nice doing this benchmark.

@andysim wrote:
> The direct range-separated code worked fine, confirming that the derivative integrals were correct

You are talking about the complete direct RSF gradient code? because it has also been disabled in the driver. The manual only ever explicitly told that the DF gradient code is not working, i believe. I actually asked about this once in the forum: http://forum.psicode.org/t/lrc-dft-gradients-time-plan/140/4 
Basically my test back then caused me to suggest the route (direct and not DF gradients) @raimis is trying out.

**Comment by andysim** [comment]
Oops, that's embarrassing!  I was skimming this thread too quickly, apparently, and failed to check my output before posting.  If I run the direct code, I get reasonable wB97X-D results:

```
  ## Total Gradient (Symmetry 0) ##
  Irrep: 1 Size: 9 x 3

                 1                   2                   3

    1    -0.00000000000000     0.00000000000000     0.00727404539260
    2     0.00000000000000     0.00000000000000     0.01566508504775
    3    -0.00000000000000    -0.00000000000000    -0.01592565050467
    4    -0.00087629381335    -0.00000000000000    -0.00080744525748
    5     0.00087629381335     0.00000000000000    -0.00080744525748
    6    -0.00150497205043    -0.00584776113735    -0.00140352222961
    7    -0.00150497205043     0.00584776113735    -0.00140352222961
    8     0.00150497205043     0.00584776113735    -0.00140352222961
    9     0.00150497205043    -0.00584776113735    -0.00140352222961



  ## F-D gradient (Symmetry 0) ##
  Irrep: 1 Size: 9 x 3

                 1                   2                   3

    1     0.00000000000000     0.00000000000000     0.00759155743061
    2     0.00000000000000     0.00000000000000     0.01575348711316
    3     0.00000000000000     0.00000000000000    -0.01604218334710
    4    -0.00080458046709     0.00000000000000    -0.00083578684600
    5     0.00080458046709     0.00000000000000    -0.00083578684600
    6    -0.00151233457098    -0.00586107718524    -0.00140782187617
    7    -0.00151233457098     0.00586107718524    -0.00140782187617
    8     0.00151233457098     0.00586107718524    -0.00140782187617
    9     0.00151233457098    -0.00586107718524    -0.00140782187617
```
By disabling [this safety check](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/scfgrad/jk_grad.cc#L185) I can make the DF version run, which is clearly wrong:
```
  ## Total Gradient (Symmetry 0) ##
  Irrep: 1 Size: 9 x 3

                 1                   2                   3

    1     0.00000000000000    -0.00000000000000    -0.34802063969605
    2     0.00000000000000    -0.00000000000000     0.51455817020357
    3     0.00000000000000     0.00000000000000     0.04263207395510
    4    -0.03687141420968    -0.00000000000000    -0.01196133113197
    5     0.03687141420968     0.00000000000000    -0.01196133113197
    6    -0.06383887601370    -0.11505211473982    -0.04636560808797
    7    -0.06383887601370     0.11505211473982    -0.04636560808797
    8     0.06383887601370     0.11505211473982    -0.04636560808797
    9     0.06383887601370    -0.11505211473982    -0.04636560808797



  ## F-D gradient (Symmetry 0) ##
  Irrep: 1 Size: 9 x 3

                 1                   2                   3

    1     0.00000000000000     0.00000000000000     0.00759612379921
    2     0.00000000000000     0.00000000000000     0.01575853518631
    3     0.00000000000000     0.00000000000000    -0.01609636966124
    4    -0.00080665975793     0.00000000000000    -0.00081633836046
    5     0.00080665975793     0.00000000000000    -0.00081633836046
    6    -0.00151005119180    -0.00585353047813    -0.00140640315084
    7    -0.00151005119180     0.00585353047813    -0.00140640315084
    8     0.00151005119180     0.00585353047813    -0.00140640315084
    9     0.00151005119180    -0.00585353047813    -0.00140640315084
```
It does look like we can re-enable the exact integral methods in the driver, but the DF bug is still present.  Thankfully DF cannot be run without code modifications, so users will never see that faulty DF gradients.  I bet it's an easy one to figure out - should be a good candidate for the next hackathon unless somebody gets to it before then.

**Comment by dgasmith** [comment]
How awful would it be if did DF SCF iterations with a direct gradient evaluation? I poured over the range-separated gradient code a few times and have not figured out the error.
