### ISSUE TITLE
psi4DepsCache cmake issue

### ISSUE THREAD

**Issue by shannonhouck** [psi4/psi4#871]
When trying to compile Psi4 with Miniconda3 using the keywords generated by `psi4-path-advisor` in the development environment, the following error is produced:
```
/home/shouck/psi4/psi4/src/psi4/dmrg/dmrgscf.cc: In function ‘void psi::dmrg::buildHamDMRG(std::shared_ptr<psi::IntegralTransform>, std::shared_ptr<psi::MOSpace>, CheMPS2::DMRGSCFmatrix*, CheMPS2::DMRGSCFmatrix*, CheMPS2::DMRGSCFindices*, CheMPS2::Hamiltonian*, std::shared_ptr<psi::PSIO>, std::shared_ptr<psi::Wavefunction>)’:
/home/shouck/psi4/psi4/src/psi4/dmrg/dmrgscf.cc:268:66: error: no matching function for call to ‘psi::Molecule::nuclear_repulsion_energy()’
     double Econstant = wfn->molecule()->nuclear_repulsion_energy();
                                                                  ^
In file included from /home/shouck/psi4/psi4/src/psi4/dmrg/dmrgscf.cc:34:0:
/home/shouck/psi4/psi4/src/psi4/libmints/molecule.h:368:12: note: candidate: double psi::Molecule::nuclear_repulsion_energy(const std::array<double, 3ul>&) const
     double nuclear_repulsion_energy(const std::array<double,3> &dipole_field) const;
            ^
/home/shouck/psi4/psi4/src/psi4/libmints/molecule.h:368:12: note:   candidate expects 1 argument, 0 provided
make[5]: *** [src/psi4/dmrg/CMakeFiles/dmrg.dir/dmrgscf.cc.o] Error 1
make[4]: *** [src/psi4/dmrg/CMakeFiles/dmrg.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [psi4-core-prefix/src/psi4-core-stamp/psi4-core-build] Error 2
make[1]: *** [CMakeFiles/psi4-core.dir/all] Error 2
make: *** [all] Error 2
```
The output generated by `psi4-path-advisor --gcc` is
```
/home/shouck/miniconda3/envs/p4dev/bin/cmake \
    -H. \
    -C/home/shouck/miniconda3/envs/p4dev/share/cmake/psi4/psi4DepsCache.cmake \
    -Bobjdir
```
@ashutoshvt and @robertodr have narrowed the issue down to the CheMPS2 module, which is set to `ON` in psi4DepsCache.cmake by default; changing it to
```
set(ENABLE_CheMPS2         OFF CACHE BOOL "")
set(CheMPS2_DIR            "/home/shouck/miniconda3/envs/p4dev/share/cmake/CheMPS2" CACHE PATH "")
```
allows Psi4 to compile without issues. I'm not sure, but it seems like maybe a function was changed and then not updated in CheMPS2. The error and log files are attached. Thank you!

[CMakeError.log](https://github.com/psi4/psi4/files/1515094/CMakeError.log)
[CMakeOutput.log](https://github.com/psi4/psi4/files/1515095/CMakeOutput.log)

**Comment by dgasmith** [comment]
We updated to a new nuclear signature so the two are getting out of sync. Not completely sure this is fixable as you are pulling addons and Psi4 from different locations. 

-Daniel Smith

**Comment by shannonhouck** [comment]
Ok, that makes sense. I got Psi4 by cloning the repo as usual, and it seems like I'm pulling CheMPS2 from the Miniconda p4dev (Psi4 development) environment. Using `conda update chemps2` doesn't show any available updates; the button on the CheMPS2 page says the most recent version is 1.8.4, but the Conda site says it's 1.8.3.

I'll try pulling from GitHub and see if that fixes anything. Thanks for the help!

**Comment by dgasmith** [comment]
Yes, if you were pulling from Conda everything would be fine. Conda is only updated periodically on the /dev channel, so its natural that psi4/psi4:master will get ahead of those built binaries. I usually recommend going sans addons while dev’ing unless you need them.

**Comment by shannonhouck** [comment]
Ok, good to know-- I'll probably just avoid using addons altogether when doing dev stuff, then. Thanks!

**Comment by loriab** [comment]
This is probably why nightly builds stopped 6 days ago when merged. And why I really must do full addons for the travis test – that would have caught this quicker. Fortunately, only the psi code will need changing. Sorry about that.
