### ISSUE TITLE
Split up n-body calls

### ISSUE THREAD

**Issue by dgasmith** [psi4/psi4#885]
Currently the `n-body` code is a single call that figures out required computations, computes those requirements, and then stitches the whole thing back together again. It would be great if these were in three separate functions so that future sow/reap tech could parallelize these across many nodes.

In `psi4/drive/nbody_driver.py` the primary function should be split at lines 291 and 312. into these three separate parts. We will then need one new function which runs through all three steps so that current functionality can be reproduced.

**Comment by dsirianni** [comment]
I think I'll stake my claim on this.  Preference on separate PR vs. incorporation into #952 ?

**Comment by amjames** [comment]
I think new PR. We probably want to start favoring smaller PRs whenever we can. Some of the massive PRs by @loriab make github choke up in my browser when I try look them over.

Smaller PRs are easier and faster to get through the review->merge cycle.

**Comment by dsirianni** [comment]
Any preference on 1.2 vs. 1.3 for #975? It's tagged as 1.2 here, but the PR seems to have been un-tagged.
