### ISSUE TITLE
Generalized Davidson solver

### ISSUE THREAD

**Issue by dgasmith** [psi4/psi4#886]
We have started a folder that contains arbitrary solvers in `psi4/driver/p4util/solvers.py`. A generalized Davidson solver which can find the first `n` roots would be greatly useful for both TDDFT, and SCF (DFT) root following. 

Requirements:
 - First n roots
 - Allow preconditions
 - Specific root following (say only positive roots)
 - Support initial guesses
 - Subspace collapse
 - Any requirements or suggestions @CDSherrill might have as well.

I believe Ruhee is on this project, but opening a stub.

**Comment by mdav2** [comment]
Hi, is anyone on this/should I get started on it? Looking for a first project and this is something I found myself wanting this afternoon - seems like a good fit!

**Comment by rdcunha** [comment]
@mdav2 @dgasmith I've been working on this for some time, and I have a decent bit of the code written. I'll open a pull request from my fork soon.

**Comment by dgasmith** [comment]
@rdcunha Cool! It would be very useful to make a PR this week so folks can understand what parts are being worked on even if it is not complete.

**Comment by dgasmith** [comment]
Closed by #1349. Thanks for everyones help here!
