### ISSUE TITLE
Serializing Wavefunctions

### ISSUE THREAD

**Issue by dgasmith** [psi4/psi4#887]
It would be very handy to have the ability to read/write entire Wavefunctions. We do this somewhat awkwardly for the SCF `read` guess functionality on [this](https://github.com/psi4/psi4/blob/master/psi4/driver/procrouting/proc.py#L1384) line. 

Some issues and solutions:
 - Serializing basis sets could be problematic. Saving the Python dictionary representation of the basis is the likely solution see [here](https://github.com/psi4/psi4/blob/master/psi4/driver/p4util/python_helpers.py#L43) to get started.
- Molecule can be serialized to/from a string (future JSON) `core.Molecule.create_molecule_from_string(mol_string)`.
- Initializing a new Wavefunction could be done with a long signature call that looks something like `Wavefunction(std::map<str::string, SharedMatrix>, std::map<str::string, SharedVector>, std::map<str::string, Dimension>, ...`. This could help reduce the number of inputs required. Curious if anyone has suggestions to simplify the population of private data.

Use cases:
 - Write our RHF wavefunction, read in for many post-SCF methods.
 - Save initial guesses for tricky to converge molecules.

**Comment by dgasmith** [comment]
As a note I need this for another project, I will probably work on it during Psi con if not completed by then.

This is a very easy PR and a great way to get started in Psi4. I can describe each step involved for those who are interested!

**Comment by zachglick** [comment]
Unless there are other volunteers, I would be happy to work on this

**Comment by dgasmith** [comment]
Excellent! I have thought up a few ways to do this, send me a DM on Slack if you want to chat or just go for it if you wish.
