### ISSUE TITLE
simint header error

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#890]
In `intrinsics_sse.h` and `simint_eri.h` i get errors like: 
` fatal error: simint/cpp_restrict.hpp: No such file or directory`

The file is located in my installation here:
`[..]/external/upstream/simint/simint_external-prefix/src/simint_external/simint/cpp_restrict.hpp`

For now I can hotfix this for myself by setting the correct path manually.
This issue suddenly appeared, it worked fine before.

**Comment by dgasmith** [comment]
@bennybp Any thoughts?

**Comment by bennybp** [comment]
Is this happening when simint is being compiled or when psi4 is being compiled with simint?

Also, what compiler?

**Comment by hokru** [comment]
When I compile psi4 with simint, using gcc v6.3. The error appears during the simint compilation part.

**Comment by loriab** [comment]
Different error, same module, so I'll add to this issue. Building simint afresh through psi4 on Mac w/`AppleClang 7.0.0.7000176` yields 

```
[  0%] Building C object simint/CMakeFiles/simint.dir/ostei/gen/ostei_s_s_s_s.c.o
In file included from /Users/loriab/linux/psihub/hrw-temp/objdir/external/upstream/simint/simint_external-prefix/src/simint_external/simint/ostei/gen/ostei_s_s_s_s.c:1:
In file included from /Users/loriab/linux/psihub/hrw-temp/objdir/external/upstream/simint/simint_external-prefix/src/simint_external/simint/boys/boys.h:3:
In file included from /Users/loriab/linux/psihub/hrw-temp/objdir/external/upstream/simint/simint_external-prefix/src/simint_external/simint/vectorization/vectorization.h:11:
/Users/loriab/linux/psihub/hrw-temp/objdir/external/upstream/simint/simint_external-prefix/src/simint_external/simint/vectorization/intrinsics_avx.h:110:26: warning: 
      implicit declaration of function '_mm256_set_m128d' is invalid in C99 [-Wimplicit-function-declaration]
            __m256d t3 = _mm256_set_m128d(  _mm256_extractf128_pd(t2, 0) + _mm256_extractf128_pd(t2, 1),
                         ^
/Users/loriab/linux/psihub/hrw-temp/objdir/external/upstream/simint/simint_external-prefix/src/simint_external/simint/vectorization/intrinsics_avx.h:110:21: error: 
      initializing '__m256d' (vector of 4 'double' values) with an expression of incompatible type 'int'
            __m256d t3 = _mm256_set_m128d(  _mm256_extractf128_pd(t2, 0) + _mm256_extractf128_pd(t2, 1),
                    ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/loriab/linux/psihub/hrw-temp/objdir/external/upstream/simint/simint_external-prefix/src/simint_external/simint/vectorization/intrinsics_avx.h:165:21: error: 
      initializing '__m256d' (vector of 4 'double' values) with an expression of incompatible type 'int'
            __m256d t3 = _mm256_set_m128d(  _mm256_extractf128_pd(t2, 0) + _mm256_extractf128_pd(t2, 1),
                    ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 2 errors generated.
```

**Comment by andysim** [comment]
Interesting, so the `implicit declaration of function '_mm256_set_m128d' is invalid in C99` shows that the included header from the `#include <immintrin.h>` up top is not working as expected, causing the compiler to assume that function is implicitly defined, and assigning it an `int` return type.  That file should include `avxintrin.h`, which defines the offending function.  Must be a namespace or `define` problem somewhere.  Very strange.

**Comment by bennybp** [comment]
@andysim is correct. @loriab  Could you check your `avxintrin.h` file and see if it has `_mm256_set_m128d`? My version of clang does (but is 9.0.0 (clang-900.0.39.2)

For the original issue: I will see if I can reproduce, but nothing is jumping out at me as being incorrect. That file should only be included when compiling the tests in simint, but the paths all look correct.

**Comment by loriab** [comment]
Of the dozen or so headers on my computer by that name, only the ones supplied by the conda clang compilers (which I'm not using) have that set. So error makes some sense. Only thing I can think of is I haven't done a simint build on this machine since the default switched from `sse` to `avx`, though, as that happened 9 months ago, shows that I've been _really_ linux or mac-psinet bound of late.

##### psi4 cmake
```
-- Setting (unspecified) option SIMINT_VECTOR: avx
```

##### simint cmake
```
--            Maximum AM: 6
--    Maximum Derivative: 0
--         CMAKE_C_FLAGS:  -march=native
--       CMAKE_CXX_FLAGS: -stdlib=libc++ -march=native
--     SIMINT_C_INCLUDES: /Users/loriab/linux/psihub/hrw-temp/objdir/external/upstream/simint/simint_external-prefix/src/simint_external;/Users/loriab/linux/psihub/hrw-temp/objdir/external/upstream/simint/simint_external-prefix/src/simint_external-build/stage
--        SIMINT_C_FLAGS: -std=c99;-Wall;-Wextra;-pedantic;-Wno-unused-parameter;-Wno-unused-variable;-mavx
--     SIMINT_LINK_FLAGS: 
```

**Comment by loriab** [comment]
Switching to `sse` on my Mac, simint builds fine through p4. But then in mints, 

```
[ 10%] Building CXX object src/psi4/libmints/CMakeFiles/mints.dir/integral.cc.o
In file included from /Users/loriab/linux/psihub/hrw-temp/psi4/src/psi4/libmints/integral.cc:55:
In file included from /Users/loriab/linux/psihub/hrw-temp/psi4/src/psi4/libmints/siminteri.h:34:
In file included from /Users/loriab/linux/miniconda3/envs/p4dev36/include/simint/simint.h:4:
In file included from /Users/loriab/linux/miniconda3/envs/p4dev36/include/simint/ostei/ostei_config.h:3:
In file included from /Users/loriab/linux/miniconda3/envs/p4dev36/include/simint/vectorization/vectorization.h:11:
/Users/loriab/linux/miniconda3/envs/p4dev36/include/simint/vectorization/intrinsics_avx.h:110:26: error: use of undeclared identifier
      '_mm256_set_m128d'
            __m256d t3 = _mm256_set_m128d(  _mm256_extractf128_pd(t2, 0) + _mm256_extractf128_pd(t2, 1),
                         ^
/Users/loriab/linux/miniconda3/envs/p4dev36/include/simint/vectorization/intrinsics_avx.h:165:26: error: use of undeclared identifier
      '_mm256_set_m128d'
            __m256d t3 = _mm256_set_m128d(  _mm256_extractf128_pd(t2, 0) + _mm256_extractf128_pd(t2, 1),
                         ^
In file included from /Users/loriab/linux/psihub/hrw-temp/psi4/src/psi4/libmints/integral.cc:55:
```

Should those be hidden for `sse`? Or is my header set just too old for words and the problem should be considered wholly on my side.

Sorry to have disrupted your issue, @hokru.

**Comment by andysim** [comment]
I don't have access to check right now, but I don't think `intrinsics_avx.h` should ever be included for SSE builds.

**Comment by bennybp** [comment]
@andysim  Yes. The 'installed' simint library should have a file `include/simint/vectorization/vector_config.h`. There is also one under the (simint) build directory under `stage`. This should define which vectorization you are using.

@loriab Maybe you didn't completely clear out the build directory before switching the vectorization type? I still think that would work, though.

**Comment by loriab** [comment]
Diagnosis: simint is sly (or, you can't defeat the header search).

Completely fresh build dir, configured from the start to build simint locally with sse (`-DCMAKE_DISABLE_FIND_PACKAGE_simint=ON -DSIMINT_VECTOR=sse`). Consequently every signal in sight (see below) is set to local build and sse. _But_, there's still a simint installed alongside libint, etc. and that simint is avxfma. And it is those simint headers that show up in `./psi4-core-prefix/src/psi4-core-build/src/psi4/libmints/CMakeFiles/mints.dir/CXX.includecache` and are presumably defining SIMINT_AVX and thus triggering the offending `intrinsics_avx.h` inclusion.

In the end, the same trouble as with multiple pybind11's – CMake can't trump native C++ header-seeking, so one has to keep any interferences out of sight. Resolved, sorry for the wild goose chase.

```
#pragma once
#define SIMINT_SSE
```

```
>>> grep -ir simint_VECTOR .
./CMakeCache.txt:SIMINT_VECTOR:STRING=sse
./external/upstream/simint/CMakeFiles/simint_external.dir/build.make:	cd /Users/loriab/linux/psihub/hrw-temp/objdir/external/upstream/simint/simint_external-prefix/src/simint_external-build && /Users/loriab/linux/miniconda3/envs/p4dev36/bin/cmake -DCMAKE_INSTALL_PREFIX=/usr/local/psi4 -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_INSTALL_INCLUDEDIR=include -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DSIMINT_STANDALONE=OFF -DENABLE_TESTS=OFF -DSIMINT_VECTOR=sse -DSIMINT_MAXAM=6 -C/Users/loriab/linux/psihub/hrw-temp/objdir/external/upstream/simint/simint_external-prefix/tmp/simint_external-cache-Release.cmake "-GUnix Makefiles" /Users/loriab/linux/psihub/hrw-temp/objdir/external/upstream/simint/simint_external-prefix/src/simint_external
./external/upstream/simint/simint_external-prefix/src/simint_external-build/CMakeCache.txt:SIMINT_VECTOR:STRING=sse
./external/upstream/simint/simint_external-prefix/src/simint_external-build/simintConfig.cmake:set(simint_VECTOR sse)
./external/upstream/simint/simint_external-prefix/tmp/simint_external-cfgcmd.txt:cmd='/Users/loriab/linux/miniconda3/envs/p4dev36/bin/cmake;-DCMAKE_INSTALL_PREFIX=/usr/local/psi4;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_C_COMPILER=/usr/bin/clang;-DCMAKE_CXX_COMPILER=/usr/bin/clang++;-DCMAKE_INSTALL_LIBDIR=lib;-DCMAKE_INSTALL_INCLUDEDIR=include;-DBUILD_SHARED_LIBS=OFF;-DCMAKE_POSITION_INDEPENDENT_CODE=ON;-DSIMINT_STANDALONE=OFF;-DENABLE_TESTS=OFF;-DSIMINT_VECTOR=sse;-DSIMINT_MAXAM=6;-C/Users/loriab/linux/psihub/hrw-temp/objdir/external/upstream/simint/simint_external-prefix/tmp/simint_external-cache-$<CONFIG>.cmake;-GUnix Makefiles;/Users/loriab/linux/psihub/hrw-temp/objdir/external/upstream/simint/simint_external-prefix/src/simint_external'
./stage/usr/local/psi4/share/cmake/simint/simintConfig.cmake:set(simint_VECTOR sse)
```

**Comment by hokru** [comment]
CMake is still back magic too me, but i just tried again from scratch and actually the error occurs when making psi4-core. The Simint library is installed before and cmake finds it in the correct path.

```
[ 10%] Building CXX object src/psi4/libmints/CMakeFiles/mints.dir/gshell.cc.o
[ 10%] Building CXX object src/psi4/libmints/CMakeFiles/mints.dir/integral.cc.o
In file included from /home/kruse/Progs/psi4.custom/objdir2/stage/home/kruse/Progs/psi4.deleteme/include/simint/vectorization/intrinsics_avx.h:7:0,
                 from /home/kruse/Progs/psi4.custom/objdir2/stage/home/kruse/Progs/psi4.deleteme/include/simint/vectorization/vectorization.h:11,
                 from /home/kruse/Progs/psi4.custom/objdir2/stage/home/kruse/Progs/psi4.deleteme/include/simint/ostei/ostei_config.h:3,
                 from /home/kruse/Progs/psi4.custom/objdir2/stage/home/kruse/Progs/psi4.deleteme/include/simint/simint.h:4,
                 from /home/kruse/Progs/psi4.custom/psi4/src/psi4/libmints/siminteri.h:34,
                 from /home/kruse/Progs/psi4.custom/psi4/src/psi4/libmints/integral.cc:55:
/home/kruse/Progs/psi4.custom/objdir2/stage/home/kruse/Progs/psi4.deleteme/include/simint/vectorization/intrinsics_sse.h:7:35: fatal error: simint/cpp_restrict.hpp: No such file or directory
 #include "simint/cpp_restrict.hpp"
                                   ^
compilation terminated.
```

**Comment by loriab** [comment]
@hokru, just in case our problems have the same root, do you want to look at `./psi4-core-prefix/src/psi4-core-build/src/psi4/libmints/CMakeFiles/mints.dir/CXX.includecache` within your build directory? Check that the simint headers full paths are within `builddir/stage/.../simint/... .h`, not to elsewhere on your system.

**Comment by hokru** [comment]
This CXX.includecache looks ok. I have lots of these:

```
simint/vectorization/intrinsics_sse.h
BUILDDIR/stage/PREFIX/include/simint/vectorization/simint/vectorization/intrinsics_sse.h
simint/cpp_restrict.hpp
BUILDDIR/stage/PREFIX/include/simint/vectorization/simint/cpp_restrict.hpp
```

The problem seems that `cpp_restrict.cpp `is not located in `BUILDDIR/stage/.../simint` as the above lines want, but only in `BUILDDIR/external/../simint/`

**Comment by loriab** [comment]
Hmm, I see the same – `.h` are installing but `.hpp` are not. @bennybp, [this line](https://github.com/simint-chem/simint-generator/blob/master/skel/simint/CMakeLists.txt#L92) doesn't seem to be functioning. The simint conda package has the cpp_restrict.hpp file installed, though, so once upon a time it worked.

```
>>> (objdir) find . -name "cpp_restrict.hpp"
./external/upstream/simint/simint_external-prefix/src/simint_external/simint/cpp_restrict.hpp
>>> (objdir) ll ./external/upstream/simint/simint_external-prefix/src/simint_external/simint
total 64
-rw-r--r--   1 loriab  staff  2451 Mar 22  2017 CMakeLists.txt
drwxr-xr-x   8 loriab  staff   272 Mar 22  2017 boys
-rw-r--r--   1 loriab  staff   332 Jan 24  2017 constants.h
-rw-r--r--   1 loriab  staff   165 Mar 22  2017 cpp_restrict.hpp
drwxr-xr-x  14 loriab  staff   476 Mar 28  2017 ostei
drwxr-xr-x   8 loriab  staff   272 Mar 22  2017 shell
-rw-r--r--   1 loriab  staff   138 Feb  2  2017 simint.h
-rw-r--r--   1 loriab  staff   831 Feb  2  2017 simint_eri.c
-rw-r--r--   1 loriab  staff  1927 Mar 22  2017 simint_eri.h
-rw-r--r--   1 loriab  staff   253 Jan 24  2017 simint_init.c
-rw-r--r--   1 loriab  staff  1148 Mar 22  2017 simint_init.h
drwxr-xr-x   8 loriab  staff   272 Mar 22  2017 vectorization
>>> objdir: ll stage/usr/local/psi4/include/simint/
total 32
drwxr-xr-x  7 loriab  staff   238 Jan 11 01:05 boys
-rw-r--r--  1 loriab  staff   332 Jan 24  2017 constants.h
drwxr-xr-x  8 loriab  staff   272 Jan 11 01:05 ostei
drwxr-xr-x  5 loriab  staff   170 Jan 11 01:05 shell
-rw-r--r--  1 loriab  staff   138 Feb  2  2017 simint.h
-rw-r--r--  1 loriab  staff  1927 Mar 22  2017 simint_eri.h
-rw-r--r--  1 loriab  staff  1148 Mar 22  2017 simint_init.h
drwxr-xr-x  8 loriab  staff   272 Jan 11 01:05 vectorization
```

**Comment by bennybp** [comment]
Ok starting to see the problem, although I don't know how it happened. v0.7 that is posted doesn't have this commit, which fixed it just prior to release: https://github.com/simint-chem/simint-generator/commit/7ea0109da8fe756903eed48b79f772ec2646b69a#diff-5a855f00d19271887654b21b58214a87

I have a feeling this was due to a change in the way I build my website...

@loriab  you wouldn't happen to have a simint-v.0.7 tarball from your conda builds, do you?

**Comment by hokru** [comment]
Hmm, i just noticed that there is no: `/stage/../vectorization/simint/` as written in CXX.includedir, only `/stage/../vectorization/`. Maybe a path mixup somewhere?

**Comment by loriab** [comment]
@bennybp sorry, no tarball

**Comment by bennybp** [comment]
I've reuploaded a tarball that should have the fix. Hopefully it should work now.

You may need to delete any cached versions of `simint-v0.7.tar.bz2` that you have in your build directory (or just delete your build directory and start from scratch).

**Comment by loriab** [comment]
works for me (after uninstalling the interfering avxfma simint that, besides my ancient headers, was the root of my problem). I think I would have hit @hokru's problem if I had persisted. Thanks, @bennybp.

```
>>> find . -name "cpp_restrict.hpp"
./external/upstream/simint/simint_external-prefix/src/simint_external/simint/cpp_restrict.hpp
./stage/usr/local/psi4/include/simint/cpp_restrict.hpp
```

**Comment by hokru** [comment]
Also works fine for me now. Thanks everyone!
