### ISSUE TITLE
Make html manual optionally buildable without psi theme

### ISSUE THREAD

**Issue by mbanck** [psi4/psi4#892]
I understand that the sphinx psi-theme likely makes things pretty and is required for the on-line manual on psicode.org, but it seems overblown to require that (external) theme package just to build the documentation locally (unless it provides more than just themeing, that is).

So I propose to just build the HTML manual using the default sphinx theme if the psi theme cannot be found.

**Comment by loriab** [comment]
I sympathize, but enough would break that a non-psi-theme-psi-docs is probably best built by hand. psi_theme has a couple sphinx extensions, and psi_theme is a light tweak on cloud_theme which also has extensions psi uses. And all the api autodoc-ing uses extensions from astropy. So if you change the theme and comment out enough from [here](https://github.com/psi4/psi4/blob/master/doc/sphinxman/source/conf.py.in#L67-L86), you can get a docs build with a built-in theme (I've done it), but it's definitely incomplete.

There came to be so many external requirements that I thought it was better practice to add psi_theme to the list and just make sure they were all easily installable (https://github.com/psi4/psi4/blob/master/doc/sphinxman/CMakeLists.txt#L18-L21). How intent are you on evading psi_theme?

**Comment by mbanck** [comment]
I don't mind, but it's an additional external dependency I have to package in order to ship the manual along with the Debian packages. And those packages need to get manually approved, so it takes a while.

I think I'll just drop the manual for now, upload 1.1 to Debian and then see about the psi theme in order to reactivate the manual. I do think it's a useful local resource to have, though.
