### ISSUE TITLE
cam-b3lyp problems with ghost atoms

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#900]
Running a cam-b3lyp calculation with ghost atoms leads to severe scf problems.

```
molecule wat {
@O     -0.031788188689    -0.057762343755    -2.500000000000
@H     -0.415040188689     0.819260656245    -2.500000000000
@H      0.919541811311     0.097469656245    -2.500000000000
O         -0.031788188689    -0.057762343755     2.500000000000
H         -0.415040188689     0.819260656245     2.500000000000
H          0.919541811311     0.097469656245     2.500000000000
}

set {
 basis def2-SVP
}
energy('cam-b3lyp')
```

Gives:

```
 ==> Iterations <==

                           Total Energy        Delta E     RMS |[F,P]|

   @DF-RKS iter   0:   -76.28416922601539   -7.62842e+01   3.25937e-02 
   @DF-RKS iter   1:    42.90914490853778    1.19193e+02   1.57477e-01 
   @DF-RKS iter   2:   -67.59424772229025   -1.10503e+02   6.97022e-02 DIIS
   @DF-RKS iter   3:    -5.92023271767882    6.16740e+01   1.67018e-01 DIIS
   @DF-RKS iter   4:   -25.53109522421165   -1.96109e+01   1.22988e-01 DIIS
   @DF-RKS iter   5:    -6.43807826871483    1.90930e+01   1.58323e-01 DIIS
   @DF-RKS iter   6:    29.17875295082399    3.56168e+01   1.24341e-01 DIIS
   @DF-RKS iter   7:    29.14675833982615   -3.19946e-02   1.24329e-01 DIIS
   @DF-RKS iter   8:    29.14518341499436   -1.57492e-03   1.24344e-01 DIIS
   @DF-RKS iter   9:    29.15167484147237    6.49143e-03   1.24371e-01 DIIS
   @DF-RKS iter  10:   -25.72021965887588   -5.48719e+01   1.20627e-01 DIIS
   @DF-RKS iter  11:   -25.72793758296909   -7.71792e-03   1.20619e-01 DIIS
   @DF-RKS iter  12:   -26.38471390876281   -6.56776e-01   1.23180e-01 DIIS
   @DF-RKS iter  13:    -6.54455688045927    1.98402e+01   1.57065e-01 DIIS

```

Other LRC functionals like `lrc-wpbe` seem to work fine. 

The first energy is in the correct ballpark, so I guess something is wrong with the potential. But how would ghost atoms come into play? And why seemingly just for CAM-style?

-----

edit:
seemingly working "LC" versions:
LRC-wPBE
CAMY-B3LYP 
LCY-BLYP

**Comment by dgasmith** [comment]
Does this work if the ghosts are farther away? LRC and CAM are very similar, just that we have global exchange at long-range with CAM. This could be typical for CAM or a bug with us.

**Comment by loriab** [comment]
Confirmed to also be broken on `1.2a1.dev508` which is pre-DFHelper and pre-gau2grid.

Psi's `molinstance.Z(atomindex)` returns nuclear charge (so `0.0` for ghosts), not atomic number (as one might think from the function name), so I can see room for programming error there. But I'm not seeing anywhere that CAM is singled out from other functional, so I share your confusion.

**Comment by hokru** [comment]
The farther the waters are apart the more positive the energy gets. Energy also stays essentially constant then.

```
   @DF-RKS iter   4:   -76.32981119020519   -1.12735e-04   7.24826e-05 DIIS
   @DF-RKS iter   5:   119.53415655216450    1.95864e+02   4.45340e-01 DIIS
   @DF-RKS iter   6:   119.53415655216457    7.10543e-14   4.45340e-01 DIIS
   @DF-RKS iter   7:   119.53415655216453   -4.26326e-14   4.45340e-01 DIIS

```

They are 5 A apart in the original example, quite far already. Putting them at 3 A leads to SCF convergence.

**Comment by susilehtola** [comment]
If you're using libxc's camb3lyp, the energy should be something like -76.32981537.

**Comment by PeterKraus** [comment]
I see the same behaviour for the CH4-HF complex, in a counterpoise-corrected single-point calculation with def2-tzvpd. See attached.

[cam-b3lyp-HF-CH4.txt](https://github.com/psi4/psi4/files/1683053/cam-b3lyp-HF-CH4.txt)

**Comment by dgasmith** [comment]
I feel like something is going wrong in the Fock matrix from what is shown. I am going to be MIA for a few weeks. Can anyone else look into this?

**Comment by PeterKraus** [comment]
I've tracked this down to "GGA_X_ITYH", which is the range-separated GGA part - this exchange functional just doesn't converge for the above system, even when I run something like 100% X_ITYH + 100% C_VWN without range separation. @susilehtola, is there any reason the 3.0.0 version could be broken?

**Comment by loriab** [comment]
I'm going to put together a psi-hosted libxc 4.0 + patch for psi to build from, in case that's helpful.

Congrats for tracking that down.
