### ISSUE TITLE
SAPT(DFT) : Units error in output

### ISSUE THREAD

**Issue by ajmisquitta** [psi4/psi4#910]
The summary output of the SAPT(DFT) module correctly converts to mH and kcal/mol, but does not convert to kJ/mol. 

The fix seems to be simple: In the file lib/psi4/driver/procrouting/sapt/sapt_util.py
change the third conversion constant to constants.hartree2kJmol.

**Comment by dgasmith** [comment]
Whoops, can you change this one?

**Comment by ajmisquitta** [comment]
Hi Daniel, I've made the change in my copy and could commit it. It's just that I was not sure of the policy you guys have for commits. Should this be made to the master?

**Comment by dgasmith** [comment]
[Here](https://gist.github.com/Chaser324/ce0505fbed06b947d962) is a pretty quick guide on the standard PR cycle.

Effectively, you need to make a new "feature" branch with the change, push that change to your GitHub fork, and then make a PR to our psi4/psi4:master. I can go into more detail if needed.
