### ISSUE TITLE
BasisSetNotFound

### ISSUE THREAD

**Issue by dragannin** [psi4/psi4#917]
Haw can I update my basis set list?

BasisSetNotFound: BasisSet::construct: Unable to find a basis set for atom 2 for key BASIS among:
  Shell Entries: [u'AU']
  Basis Sets: [(u'DEF2-QZVP', u'DEF2-QZVP', None)]
  File Path: /lustre/home/drninko19/RESTORED/naftalen/SAPT, /lustre/home/drninko19/RESTORED/naftalen/SAPT, /lustre/home/drninko19/psi4conda/share/psi4/basis
  Input Blocks:

**Comment by loriab** [comment]
Looks to be present [here](https://github.com/psi4/psi4/blob/master/psi4/share/psi4/basis/def2-qzvp.gbs#L3915).

**Comment by loriab** [comment]
Replace the file in your installed `share/psi4/basis` with the one I linked.

**Comment by dgasmith** [comment]
Please reopen if this still a issue.
