### ISSUE TITLE
Issues with ECP's from EMSL

### ISSUE THREAD

**Issue by PeterKraus** [psi4/psi4#926]
Further to our discussion at Slack and e-mail, I made some tests on molecules with ECP's. Please see the attached G09 and psi4 input and log files.

To obtain the psi4 results, the g- and h- shell coefficient of 0.000 in the Xe/Hg ECP has been replaced with 1D-10. A simple trapping of `tsum==0` in `erd_normalize_shell()` in `libmintsgshell.py` doesn't work properly - the term has to be sanity-checked in the loop before on lines 241-252. 

For Hg, the `libmintsbasissetparser.py` had to be extended at line 202 to include the H-shell (thanks, Jesse).

![image](https://user-images.githubusercontent.com/5336995/36932575-1957f002-1ecb-11e8-84dc-b365f16b84b3.png)

As can be seen from the table above, the absolute energies of the dimers are fine when compared to G09. The `nocp` interaction energy is also OK, however when CP-correction is involved, the results are not good - I imagine the ECP doesn't get properly ghosted.

Finally, the psi4 calculations crash as `libmintsbasisset.py` is not able to find the basis sets for some reason - perhaps the basis set file is not passed into the routine properly? This also occurs when the basis set is defined in the job file using `basis { ... }`.

[ECP-test.zip](https://github.com/psi4/psi4/files/1777311/ECP-test.zip)

**Comment by PeterKraus** [comment]
Possible fixes for the angular momentum and contraction coefficients are here:

https://github.com/psi4/psi4/compare/master...PeterKraus:ecp_fix

**Comment by dgasmith** [comment]
For the failure at the end, check out `driver/driver_nbody.py:471`. Which looks like `wfn = core.Wavefunction.build(molecule, 'sto-3g')`. This should be replaced with `wfn = core.Wavefunction.build(molecule)` so that the global basis set is picked up.

You may want to try a fix more like `[x if x > 1.e-10 else x + 1.e10 for x in values]` to be a bit more canonical.
