### ISSUE TITLE
a bug in energy() function

### ISSUE THREAD

**Issue by timn2008** [psi4/psi4#927]
Hi!

there is a bug in energy() function: both
energy('scf') 
and
energy('scf', dft_functional='b3lyp')
produce exactly the same results in psi4conda. This fact is inconsistent with http://www.psicode.org/psi4manual/master/dft.html where it is said that the latter syntax is absolutely valid.
See attached archieves for complete input and output files.
[1cc1.z437604.hippodrome.zip](https://github.com/psi4/psi4/files/1777480/1cc1.z437604.hippodrome.zip)
[1cc1.z437605.hippodrome.zip](https://github.com/psi4/psi4/files/1777481/1cc1.z437605.hippodrome.zip)

**Comment by loriab** [comment]
Thanks for the report!

I suspect you've been caught out by our rapidly changing DFT code. If you're using psi4conda, that's the last published release, so 1.1, which uses our home-grown DFT functionals before we switched out to Libxc (and added nifty things like `energy(..., dft_functional='b3lyp')`). You can check to confirm with `psi4 --version`.

The 1.1 manual is at http://www.psicode.org/psi4manual/1.1/dft.html#advanced-functional-use-and-manipulation

See [here](http://psicode.org/psi4manual/master/conda.html#how-to-install-a-psi4-binary-into-an-ana-miniconda-distribution) for updating (still with conda) to the pre-1.2 development branch, for which your two commands should behave differently.

**Comment by timn2008** [comment]
well, I've done
conda update psi4 -c psi4/label/dev
which got 
    gau2grid:   0.1-0              psi4/label/dev
    psi4:       1.1+add49b9-py36_0 psi4           --> 1.2a1.dev781+837e345-py36_0 psi4/label/dev
    psi4-lt-mp: 1.1-py36_0         psi4           --> 1.2a1.dev5-py36_0           psi4/label/dev
But now psi4 doesn't work from my Anaconda Python3:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/psi4/__init__.py", line 54, in <module>
    from . import core
ImportError: /opt/anaconda3/lib/python3.6/site-packages/psi4/core.so: undefined symbol: __svml_sin4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cc4.py", line 1, in <module>
    import psi4
  File "/opt/anaconda3/lib/python3.6/site-packages/psi4/__init__.py", line 59, in <module>
    raise ImportError("{0}".format(err))
ImportError: /opt/anaconda3/lib/python3.6/site-packages/psi4/core.so: undefined symbol: __svml_sin4

**Comment by loriab** [comment]
You’re def in the newly created env? 

Away from computer but do “conda list”. Then try “conda install <pkg> -c psi4/label/dev -c psi4” for every pkg that is psi4 channel in origin. That is, things like libxc, chemps2 etc. also make sure you have defaults numpy to provide mkl (which is what your error is about).

**Comment by timn2008** [comment]
It now seems to work fine, thanks!

**Comment by dgasmith** [comment]
Glad it works! Please reopen if you have further issues.
