### ISSUE TITLE
different results when running psi4 as binary and as Python module

### ISSUE THREAD

**Issue by timn2008** [psi4/psi4#932]
Hi!

An issue: different results are printed when running the attached files: 
a) python tst.py
It prints [  2.00000335e+00   2.00000331e+00   ..... -6.65828772e-04  -2.38015245e-03]
for the custom output which I request
(notice that tst.py is attached as tst.py.txt)
[tst.py.txt](https://github.com/psi4/psi4/files/1790987/tst.py.txt)

b) /opt/anaconda3/bin/psi4 file.dat
which prints
[  1.99922250e+00   1.99922249e+00   .......  -6.83682794e-04  -2.43598746e-03] 
(notice that file.dat is attached as file.dat.txt)
[file.dat.txt](https://github.com/psi4/psi4/files/1790991/file.dat.txt)

There is a clear difference in first two values, although tst.py is almost **identical** to file.dat !

PS. Psi4 was installed via Anaconda. Now I'm using a 64-bit Anaconda Python 3.6.3 with the following modules:
[root@*** ***]# conda list | grep "psi"
chemps2                   1.8.4                         0    psi4/label/dev
dftd3                     3.2.0                         7    psi4
dkh                       1.2                           1    psi4/label/dev
erd                       3.0.6                         1    psi4/label/dev
gau2grid                  0.1                           0    psi4/label/dev
gcc-5                     5.2.0                         1    psi4
gcc-5-mp                  5.2.0                         0    psi4
gcp                       2.0.1                         0    psi4
gdma                      2.2.6                         3    psi4/label/dev
libefp                    1.5b1                         0    psi4/label/dev
libint                    1.2.1                         1    psi4/label/dev
libxc                     3.0.0                         6    psi4/label/dev
pcmsolver                 1.1.10                   py36_1    psi4/label/dev
psi4                      1.2a1.dev781+837e345          py36_0    psi4/label/dev
psi4-lt-mp                1.2a1.dev5               py36_0    psi4/label/dev
simint                    0.7                           0    psi4

PPS. I've previously followed advices to solve the https://github.com/psi4/psi4/issues/927#issuecomment-370240121 issue which I encountered earlier. Could I have not updated anything ?

**Comment by loriab** [comment]
one's frozen core and other isn't

**Comment by andysim** [comment]
The input `tst.py.txt` freezes the core orbitals, while the other appears not to.

**Comment by timn2008** [comment]
But isn't core orbitals frozen by default?

**Comment by timn2008** [comment]
Well, you're right! Commenting out 'freeze_core': 'true' solves the issue. SO, no bug really

**Comment by andysim** [comment]
The [default](http://www.psicode.org/psi4manual/master/autodir_options_c/module__globals.html#freeze-core) is to correlate all electrons, primarily because the CC gradient codes do not support frozen cores yet.

**Comment by timn2008** [comment]
Oh, btw, is there a way to increase the number of digits which the program uses to write orbital occupancies into molden files ?

**Comment by andysim** [comment]
It's currently [hardwired](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libmints/writer.cc#L238-L241) at 4 digits after the decimal, which we though would suffice for most purposes.  Feel free to change that format string and issue a pull request if there's a pressing need for more.

**Comment by loriab** [comment]
I think this one's cleared up. Please reopen if necessary.
