### ISSUE TITLE
`properties` call fails with the method/basis syntax.

### ISSUE THREAD

**Issue by dgasmith** [psi4/psi4#934]
The following input:

```
import psi4

mol = psi4.geometry("""
He 0 0 0
""")

wfn = psi4.properties('scf/sto-3g')
```

fails with the following exception:
```
Traceback (most recent call last):
  File "/Users/daniel/Gits/psi4/psi4/run_psi4.py", line 259, in <module>
    exec(content)
  File "<string>", line 23, in <module>
  File "/Users/daniel/Gits/psi4/psi4/driver/driver.py", line 826, in properties
    optstash = driver_util._set_convergence_criterion('properties', lowername, 6, 10, 6, 10, 8)
  File "/Users/daniel/Gits/psi4/psi4/driver/driver_util.py", line 78, in _set_convergence_criterion
    _method_exists(ptype, method_name)
  File "/Users/daniel/Gits/psi4/psi4/driver/driver_util.py", line 50, in _method_exists
    raise ValidationError('%s method "%s" is not available.%s' % (Cptype, method_name, alternatives))

ValidationError: Properties method "scf/sto-3g" is not available.
```

How `frequency` uses the code [here](https://github.com/psi4/psi4/blob/master/psi4/driver/driver.py#L1674) to overcome the issue.

The `properties` call in Psi4 is located [here](https://github.com/psi4/psi4/blob/master/psi4/driver/driver.py#L754) and could use a similar fix (or a nice little function to prevent duplication with `frequency`).

**Comment by loriab** [comment]
Btw, is there concurrence on killing of `property()` in favor of `properties()`? I like the former better, but using a python syntax word makes me nervous.

**Comment by dgasmith** [comment]
I incorrectly wrote that down, `property` was killed off in favor of `properties`. I do like the former better as well, but it messes with Python.

**Comment by loriab** [comment]
`energy('B3lyp/6-311++G**')` is another one the regex needs to be smarter for.

**Comment by loriab** [comment]
`+\s*D:` probably

**Comment by dgasmith** [comment]
FYI for the new developers, the relevant line is here:
https://github.com/psi4/psi4/blob/master/psi4/driver/driver_cbs.py#L1516
