### ISSUE TITLE
samples/sapt3/input.dat error

### ISSUE THREAD

**Issue by prpbarreto** [psi4/psi4#936]
Dear all,

I am new at psi4, and I want to run sapt using the mid-bonds. I pick up the sapt3 example to test it, but I got the following error 

  Memory set to 953.674 MiB by Python driver.
  SAPT does not make use of molecular symmetry, further calculations in C1 point group.

Traceback (most recent call last):
  File "/opt/psi4/bin/psi4", line 248, in <module>
    exec(content)
  File "<string>", line 43, in <module>
  File "/opt/psi4/lib//python3.6/site-packages/psi4/driver/driver.py", line 460, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/opt/psi4/lib//python3.6/site-packages/psi4/driver/procrouting/proc.py", line 3151, in run_sapt
    raise ValidationError('SAPT requires active molecule to have 2 fragments, not %s.' % (nfrag))

ValidationError: SAPT requires active molecule to have 2 fragments, not 3.

Can somebody tell me what I am doing wrong?

Thanks

**Comment by PeterKraus** [comment]
Hello,
it works fine for me with a relatively recent psi4 (Git: Rev {master} a3d8d93). It also works with the latest dev. conda package (837e345). Which psi4 version are you using? If it's anything older, try [updating](http://www.psicode.org/psi4manual/master/conda.html#how-to-update-a-psi4-binary).
Peter

Log: [{master} a3d8d93](https://github.com/psi4/psi4/files/1811137/master.txt)

**Comment by prpbarreto** [comment]
O install it last week, so I should be using de last version. I download the script version py3.6.

**Comment by PeterKraus** [comment]
It might well be you've downloaded the stable version (psi4 version 1.1) and the mid-bond functionality might have been introduced afterwards (so it's available only in the dev releases). What does `psi4 --version` return?

**Comment by dgasmith** [comment]
Just a note to confirm, that error looks like a mismatch between an old version of Psi4 and new version of the test. Midbonds were added fairly recently.

**Comment by prpbarreto** [comment]
pis4--version returns:

/psi4/lib/python3.6/site-packages/v2rdm_casscf/v2rdm_casscf.so loaded.1.1

**Comment by prpbarreto** [comment]
how can I get eh new version, as the site give the version 1.1?

**Comment by loriab** [comment]
The updating link @PeterKraus sent you and https://github.com/psi4/psi4/issues/927 should help.

**Comment by hokru** [comment]
If conda is used you will likely need to run this:
`update psi4 libefp libint erd simint pcmsolver chemps2 gdma dkh libxc -c psi4/label/dev` or else
you will get this error: http://forum.psicode.org/t/psi4-error-after-upgrade/662/2

(I happend to run into this today morning)

**Comment by prpbarreto** [comment]
Now nothings works anymore. I update psi4 using conda update psi4 libefp libint erd simint pcmsolver chemps2 gdma dkh libxc -c psi4/label/dev it finish ok, but when I try to run psi4 I got the following error:

  File "/opt/psi4/bin/psi4", line 158, in <module>
    import psi4
  File "/opt/psi4/lib//python3.6/site-packages/psi4/__init__.py", line 81, in <module>
    from .driver import endorsed_plugins
  File "/opt/psi4/lib//python3.6/site-packages/psi4/driver/endorsed_plugins.py", line 32, in <module>
    import v2rdm_casscf
  File "/opt/psi4/lib//python3.6/site-packages/v2rdm_casscf/__init__.py", line 39, in <module>
    psi4.core.plugin_load(sofile)
RuntimeError: 
Fatal Error: load_plugin: Cannot open library: /opt/psi4/lib/python3.6/site-packages/v2rdm_casscf/v2rdm_casscf.so: undefined symbol: _ZNK3psi12Wavefunction26tpdm_gradient_contributionEv
Error occurred in file: /scratch/psilocaluser/conda-builds/psi4_1514132855674/work/psi4/src/psi4/libplugin/load_plugin.cc on line: 51
The most recent 5 function calls were:

psi::plugin_load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)
py_psi_plugin_load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
pybind11::cpp_function::dispatcher(_object*, _object*, _object*)

forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
libpcm.so.1        00002AC3069B82CD  Unknown               Unknown  Unknown
libpthread.so.0    00002AC301BBD1F0  Unknown               Unknown  Unknown
ld-linux-x86-64.s  00002AC30148A0D1  Unknown               Unknown  Unknown
ld-linux-x86-64.s  00002AC3014847A6  Unknown               Unknown  Unknown
libdl.so.2         00002AC301DCB5EC  Unknown               Unknown  Unknown
libdl.so.2         00002AC301DCB10F  Unknown               Unknown  Unknown
core.so            00002AC303C6DC02  Unknown               Unknown  Unknown
core.so            00002AC303DC58E2  Unknown               Unknown  Unknown
core.so            00002AC303DE4A13  Unknown               Unknown  Unknown
core.so            00002AC303955DEC  Unknown               Unknown  Unknown
libpython3.6m.so.  00002AC30175D1C9  Unknown               Unknown  Unknown
libpython3.6m.so.  00002AC301705E96  Unknown               Unknown  Unknown
libpython3.6m.so.  00002AC3018614B5  Unknown               Unknown  Unknown
libpython3.6m.so.  00002AC301810E03  Unknown               Unknown  Unknown
libpython3.6m.so.  00002AC30182F8FA  Unknown               Unknown  Unknown
python             0000000000400C1D  Unknown               Unknown  Unknown
libc.so.6          00002AC3026F9A15  Unknown               Unknown  Unknown
python             00000000004009E9  Unknown               Unknown  Unknown

**Comment by loriab** [comment]
just remove v2rdm `conda uninstall v2rdm_casscf`

**Comment by prpbarreto** [comment]
now works.

thanks
