### ISSUE TITLE
understanding the sapt results with psi4

### ISSUE THREAD

**Issue by prpbarreto** [psi4/psi4#938]
Dear all, 

I started to use psi4 last week, to run the sapt calculation, but maybe I am doing something wrong because the results are not what I expected. I run the system H2O-H2 using the following input:

#! SAPT0 aug-cc-pVQZ computation of the h2o-h2 interaction energy,

molecule {
     0 1
   O	-0.00497112320277    0.00000000000   -0.00324242498004   
   H	-0.00635802533704    0.00000000000    1.80786893363963    
   H	1.74732087529567    0.00000000000   -0.46100056491475   
     --
     0 1
   H	-5.31435149256189    0.00000000000   -3.57188290957646   
   H	-4.14192596170216    0.00000000000   -2.81859073952601   
     units angstrom
}

set {
    basis         aug-cc-pvqz
    guess         sad
    scf_type      df
    puream        true
    print         1
    basis_guess   true
}

energy('sapt2+3(ccd)')

Eelst = psi4.get_variable("SAPT ELST ENERGY")
Eexch = psi4.get_variable("SAPT EXCH ENERGY")
Eind  = psi4.get_variable("SAPT IND ENERGY")
Edisp = psi4.get_variable("SAPT DISP ENERGY")
ET = psi4.get_variable("SAPT0 TOTAL ENERGY")

And I got the following results:

  Total HF                         -0.23285527 [mEh]      -0.14611889 [kcal/mol]      -0.61136150 [kJ/mol]
  Total SAPT0                      -0.31237291 [mEh]      -0.19601697 [kcal/mol]      -0.82013509 [kJ/mol]
  Total SAPT2                      -0.22375789 [mEh]      -0.14041020 [kcal/mol]      -0.58747633 [kJ/mol]
  Total SAPT2+                     -0.21063053 [mEh]      -0.13217266 [kcal/mol]      -0.55301046 [kJ/mol]
  Total SAPT2+(3)                  -0.18566214 [mEh]      -0.11650476 [kcal/mol]      -0.48745596 [kJ/mol]
  Total SAPT2+3                    -0.18495027 [mEh]      -0.11605805 [kcal/mol]      -0.48558693 [kJ/mol]
  Total SAPT2+(CCD)                -0.19261506 [mEh]      -0.12086778 [kcal/mol]      -0.50571084 [kJ/mol]
  Total SAPT2+(3)(CCD)             -0.16764667 [mEh]      -0.10519988 [kcal/mol]      -0.44015633 [kJ/mol]
  Total SAPT2+3(CCD)               -0.16693480 [mEh]      -0.10475317 [kcal/mol]      -0.43828731 [kJ/mol]

  Special recipe for scaled SAPT0 (see Manual):
    Electrostatics sSAPT0          -0.21426853 [mEh]      -0.13445554 [kcal/mol]      -0.56256203 [kJ/mol]
    Exchange sSAPT0                 0.00071398 [mEh]       0.00044803 [kcal/mol]       0.00187454 [kJ/mol]
    Induction sSAPT0               -0.01930071 [mEh]      -0.01211138 [kcal/mol]      -0.05067402 [kJ/mol]
    Dispersion sSAPT0              -0.07951765 [mEh]      -0.04989808 [kcal/mol]      -0.20877358 [kJ/mol]
  Total sSAPT0                     -0.31237291 [mEh]      -0.19601697 [kcal/mol]      -0.82013509 [kJ/mol]

But the energy should the higher, then I include the mid-bond to try to solve this problema 

   @He      -2.068477419249695        0.0  -1.410916582253025 

and the results are, almost, the same:

  Total HF                         -0.24001137 [mEh]      -0.15060942 [kcal/mol]      -0.63014986 [kJ/mol]
  Total SAPT0                      -0.31952707 [mEh]      -0.20050627 [kcal/mol]      -0.83891833 [kJ/mol]
  Total SAPT2                      -0.23090246 [mEh]      -0.14489348 [kcal/mol]      -0.60623440 [kJ/mol]
  Total SAPT2+                     -0.21777522 [mEh]      -0.13665602 [kcal/mol]      -0.57176884 [kJ/mol]
  Total SAPT2+(3)                  -0.19281865 [mEh]      -0.12099553 [kcal/mol]      -0.50624536 [kJ/mol]
  Total SAPT2+3                    -0.19210713 [mEh]      -0.12054905 [kcal/mol]      -0.50437726 [kJ/mol]
  Total SAPT2+(CCD)                -0.19975973 [mEh]      -0.12535113 [kcal/mol]      -0.52446918 [kJ/mol]
  Total SAPT2+(3)(CCD)             -0.17480316 [mEh]      -0.10969064 [kcal/mol]      -0.45894570 [kJ/mol]
  Total SAPT2+3(CCD)               -0.17409164 [mEh]      -0.10924416 [kcal/mol]      -0.45707760 [kJ/mol]

  Special recipe for scaled SAPT0 (see Manual):
    Electrostatics sSAPT0          -0.21424647 [mEh]      -0.13444170 [kcal/mol]      -0.56250411 [kJ/mol]
    Exchange sSAPT0                 0.00070499 [mEh]       0.00044239 [kcal/mol]       0.00185095 [kJ/mol]
    Induction sSAPT0               -0.02646989 [mEh]      -0.01661011 [kcal/mol]      -0.06949671 [kJ/mol]
    Dispersion sSAPT0              -0.07951570 [mEh]      -0.04989686 [kcal/mol]      -0.20876847 [kJ/mol]
  Total sSAPT0                     -0.31952707 [mEh]      -0.20050627 [kcal/mol]      -0.83891833 [kJ/mol]
 
This results should be [in cm^-1]:

Eelst -248.3272 -246.5658 -247.1986
Eexch 299.6085 288.2112 284.0616
E[disp] -207.7366 -208.4609 -208.5377
Eind -68.5323 -70.0473 -70.0178
SAPT(2)+E(30)
SAPT(3)[c] -201.3719 -210.6001 -214.9008
SAPT(3)+δ3EHFint -218.9833 -230.1329 -234.5033
CCSD(T)[d] -170.0199 -209.7644 -216.5667
CCSD(T)[e] -206.6663 -214.6229 -218.4051

according to reference: Proceedings - 12th International Conference on Computational Science and Its Applications, ICCSA 2012 2012, Article number 6257612, Pages 67-76, 12th International Conference on Computational Science and Its Applications, ICCSA 2012; Salvador, Bahia; Brazil; 18 June 2012 through 21 June 2012; Category numberE4710; Code 92715 (http://ieeexplore.ieee.org/document/6257612/?reload=true)

Somebody has any idea about what I am doing wrong.

Thanks in advance.

**Comment by hokru** [comment]
your geometry is in bohr!

**Comment by prpbarreto** [comment]
Thanks, I can't believe I did such basic error. Now it works.
