### ISSUE TITLE
Hessian by Finite Difference of Energies Reports Wrong Number of Displacements

### ISSUE THREAD

**Issue by JonathonMisiewicz** [psi4/psi4#941]
When getting a hessian by finite difference of energies, the output file will report "Number of geometries (including reference) is" one _less_ than the actual number of geometries. The culprit is [this line](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/findif/fd_geoms_freq_0.cc#L164), which forgets to include the reference in the count. Contrast [this line of finite difference by gradients code](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/findif/fd_geoms_freq_1.cc#L134), which reports the number of displacements correctly.

This will be fixed with Issue #884, as a commit to-be-made to PR #834.

**Comment by dgasmith** [comment]
@JonathonMisiewicz Did #834 fix this?

**Comment by JonathonMisiewicz** [comment]
@dgasmith No. Fixing this is a one-liner, so I could get this fixed for 1.2 if you'd like.

This was originally going to be fixed as part of my larger findif work, but I underestimated the time that two other urgent projects would take, so findif has been delayed.

**Comment by dgasmith** [comment]
If it is a quick fix, I would like to get this into 1.2.
