### ISSUE TITLE
migrate coupled-cluster test cases to independence

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#943]
Presently, there are rather few `compare_values()` statements in the `tests/cc*/input.dat` test cases. This is because there's a very thorough [perl script](https://github.com/psi4/psi4/blob/master/tests/psitest.pl) that parses the output file and parses the alongside `reference.dat` file and compares everything in sight to a sensible number of decimal places. Works great (except when we accidentally break its arrangements and then everything trivially passes for months at a time until someone notices) in Make or CMake testing framework for checking CC. _Doesn't_ work great to check that psivar coverage is good for the cc* modules or independently of the ctest testing macros or in an installed (as opposed to source) testing env w/o reference.dat files or without perl.

I think the in-file compare_values() testing is an idea that has proven its worth. I suggest that:
1.  the key reference values from each `reference.dat` be collected into the various `cc*/input.dat` tests,
2. more psivars be defined as needed in the `psi4/src/psi4/cc*` modules, 
3. a `compare_coupledcluster()` be written to take in a wfn and a structure of reference values and apply all the checks that the perl script currently does through compare_values(), compare_arrays(), etc.

(3) is negotiable; it's just my current idea on how to move toward compare_values() without losing coverage. Primary aims are to make coupled-cluster tests suitable for installed testing (`assert compare_values(...)` works great in pytest) and increase coupled-cluster psivar usage (@amjames already did one follow-up pass) for the QCSchema project. Further note that in the near future, psivars need to be on Wfn, *not* `P::e`. Might be worth multiple ppl working to spread the pain.

This hasn't been run by @lothian, so he may have other ideas.

**Comment by amjames** [comment]
- Step 1. Modify the perl script to write the reference values out instead of checking them could even write them directly into input.dat with a variable name.
- Step 2. Hunt down the corresponding psivars and add the `compare_value` statements.
- Step 3. The ones that don't work in 2 point at missing psivars which need to be added

1.) should be somewhat easy but some perl knowledge required. 2) not too difficult either. 3) will take the most time,  finding the code in `psi4/src/psi4/cc*` that needs to be modified will take the most time. 

I am not completely sure I get what you want to do with your point (3) do you want to just lump `compare_values` together in a function that takes a `wfn` and  `ref_vals` dict and does all the `compare_values` needed rather than putting lots of them in the input files?

**Comment by loriab** [comment]
@amjames Yes, having a coupled-cluster-check-all fn that takes `wfn` and `ref_vals` was just an idea to preserve the comprehensiveness of the perl script. If I was writing this from scratch I'd probably put lots of `compare_values` in the input files for independence. But with 50 cc test cases I fear ppl will lose steam if they checked everything the perl script checks line by line.

**Comment by amjames** [comment]
Yea, I see what you mean. The perl script is very comprehensive and it detects the type of calculation being run, changing the values that will be checked as needed. I am able to offer navigational/general help on this is someone volunteers B.TW. so if anyone is interested post here/slack me/ping me/send a smoke signal.

**Comment by loriab** [comment]
Recording all the reference values should cover the type-of-calc-being-run logic, as that won't be changing for a given infile. So it should be down to if-present-in-`ref_vals`-then-compare being sufficient. And thanks, @amjames, getting some cc* module psivars onto wfn, as opposed to `P::e` can be tricky, as I learned from cctriples.

**Comment by amjames** [comment]
Yes, IIRC we need to make sure that `CCEnergyWavefunction`'s vars is updated *not* `ref_wfn`'s ? but just in energy modules, lambda/density/eom/response do not have proper wfns so they need to update whatever wfn they were passed [*Warning: It might not have the same name in all of those modules*]

**Comment by loriab** [comment]
Second that warning. Here's a start. https://github.com/loriab/psi4/commit/97cff30585980e995ae66ee62180b08482083283

**Comment by JonathonMisiewicz** [comment]
I'll be taking this one myself, for the sake of `ccdensity` sanitizing.

Alas, I already have a mug.
