### ISSUE TITLE
File Not Found Error for scratch json_out file 

### ISSUE THREAD

**Issue by ChayaSt** [psi4/psi4#944]
I'm running psi4 via JSON inputs using `psi4.json_wrapper.run_json(json_data)`. The script I'm running is [here](https://github.com/ChayaSt/torsionfit_examples/blob/wbo/kinase_inhibitors/bond_order/run_psi4.py). 
I'm using psi4 version `1.2a1.dev781`. 
When I try to run this on the cluster I get the following error:
```
Traceback (most recent call last):
  File "run_psi4.py", line 14, in <module>
    psi4.json_wrapper.run_json(json_data)
  File "/home/chayas/miniconda3/envs/p4dev/lib/python3.6/site-packages/psi4/driver/json_wrapper.py", line 234, in run_json
    with open(outfile, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '817ec146-d766-49a6-828c-8758bd88af3d.json_out'
```
I added `print(os.getcwd()), print(outfile)` after [this line](https://github.com/psi4/psi4/blob/master/psi4/driver/json_wrapper.py#L233) in `json_wrapper.py` and it printed out:
```
current directory: /tmp/psi.50867..dftd3.a3e40a77
outfile: 9eab12bc-82e2-47aa-b29f-eb58db83bf22.json_out
```
When I set `json_data["scratch_location"]: "absolute/path/to/current/directory"` where the current directory is the directory I launch psi4 from, I get the following print out:

```
current directory: /lila/home/chayas/src/ChayaSt/torsionfit_examples/kinase_inhibitors/bond_order/Axitinib/psi.52714..dftd3.cb5f92ab
outfile: 45d87c61-c859-4e40-9a96-419f3b0888ad.json_out
```
The tmp directory `psi.57214..dftd3.cb5f92ab` gets written to the directory I specified and some scratch files get written there too. But `45d87c61-c859-4e40-9a96-419f3b0888ad.json_out` is written to `/lila/home/chayas/src/ChayaSt/torsionfit_examples/kinase_inhibitors/bond_order/Axitinib/`, not to the tmp directory no matter if I specify where the scratch files should be written. 

@dgasmith suggested I add `outfile = core.IOManager.shared_object().get_default_path() +str(uuid.uuid4()) + ".json_out"` to [here](https://github.com/psi4/psi4/blob/master/psi4/driver/json_wrapper.py#L188). When I do this, `json_wrapper` does find the scratch file.

**Comment by dgasmith** [comment]
Yea, this is kind of an interesting issue. Best to change this so that the scratch output is written to the scratch path as well. The above fix works, just make sure to use `os.path.join` over the `+` operator I think.

**Comment by dgasmith** [comment]
I forget the exact PR, but this was fixed in one of the JSON updates.
