### ISSUE TITLE
No external LAPACK library found

### ISSUE THREAD

**Issue by xiexr151e** [psi4/psi4#954]
I would like to use the program from source (rather than the conda distribution), but attempting to build CMake gives me the following error:
```
CMake Error at cmake/math/MathLibsFunctions.cmake:216 (message):
  -- No external LAPACK library found (have you set the MATH_ROOT environment variable?)
```

However, when performing `locate lapack`, I get this:
```
/usr/include/clapack.h
/usr/lib64/liblapack.so.3
/usr/lib64/liblapack.so.3.4
/usr/lib64/liblapack.so.3.4.2
/usr/lib64/liblapacke.so.3
/usr/lib64/liblapacke.so.3.4
/usr/lib64/liblapacke.so.3.4.2
/usr/lib64/python2.7/site-packages/numpy/linalg/lapack_lite.so
/usr/share/doc/lapack-3.4.2
/usr/share/doc/atlas-devel-3.10.1/doc/lapackqref.pdf
/usr/share/doc/lapack-3.4.2/LICENSE
/usr/share/doc/lapack-3.4.2/README
/usr/share/doc/lapack-3.4.2/lapackqref.ps
```
I am not sure if the required library is here. Doing `MATH_ROOT=\usr\ cmake3 -H. -Bobjdir` did not help either.
Is there any possible idea how the error could have occurred? I have also tried to instal MKL from conda.

**Comment by robertodr** [comment]
Silly of me to ask, but it seems you've used back-slashes rather than forward-slashes. Have you tried `MATH_ROOT=/usr/lib64`?

**Comment by xiexr151e** [comment]
My mistake. Those were supposed to be forward-slashes.
In any case, that does not work either.

**Comment by loriab** [comment]
Have you modeled on the examples [here](http://psicode.org/psi4manual/master/build_planning.html#how-to-configure-blas-lapack-for-building-psi4)? 

You can work from conda mkl nowadays with `conda install mkl-devel`. cmake commands are https://github.com/psi4/psi4meta/blob/master/conda-recipes/psi4-dev-src/psi4DepsMKLCache.cmake#L15-L16

**Comment by susilehtola** [comment]
@xiexr151e you're obviouosly missing the development packages, as you only have the runtime libraries on your system. (The development library name ends with ".so") Which distribution are you using?

**Comment by xiexr151e** [comment]
For MKL, I did not install the development package yet.
As for psi4, I was using the conda distribution, but I am trying to build from source.

**Comment by loriab** [comment]
The conda packages are in a state of transition just now wrt gcc, so I can't give you bullet-proof directions for this procedure without a lot of back-and-forth, but there is a procedure to build psi4 from source using all dependencies from conda, including MKL. It's outlined here (http://psicode.org/psi4manual/master/conda.html#how-to-use-conda-to-compile-psi4-faster-and-easier).

**Comment by susilehtola** [comment]
@xiexr151e  you should install the BLAS/LAPACK development package using your linux distribution's package manager. (Note that you should install an optimized implementation such as ATLAS or OpenBLAS instead of the reference BLAS/LAPACK implementation.)

**Comment by xiexr151e** [comment]
I have installed mkl-devel, but now I have a new issue:

```
CMake Error at tests/fsapt-terms/CMakeLists.txt:4 (file):
  file COPY cannot find
  "/server-home1/.../psi4/tests/fsapt-terms/../../psi4/share/psi4/fsapt/fsapt.py".


CMake Error at tests/fsapt-allterms/CMakeLists.txt:6 (file):
  file COPY cannot find
  "/server-home1/.../psi4/tests/fsapt-allterms/../../psi4/share/psi4/fsapt/fsapt.py".
```

Is there a cmake comment I should look at in the psi4 documentation?

**Comment by loriab** [comment]
Does the file exist?

Did you end up updating the psi source in the course of your trying to solve the other issue?

Did you delete any partial `<objdir>/` between trial `cmake` commands?

**Comment by xiexr151e** [comment]
I re-cloned the git repository, and it seems to have solved the problem.

**Comment by xiexr151e** [comment]
I ran into another issue during the `make install` step.
I kept getting the `ImportError: No module named mpmath`.

I have attempted to install `mpmath` through conda, and the issue still persists.

**Comment by amjames** [comment]
mpmath is a required for one of the dependencies which was probably added sometime between your first cloning and your re-clone. 

A couple of things:  
 - Was the installation of mpmath successful? 
 - Did you install into the base env or a different one? 
 - Is that one active? 
 - You can see if mpmath is available in the env that is active while you are trying to build by looking at the output from `conda list`

**Comment by loriab** [comment]
How did you get gau2grid (psi4 dependency) compiled without `mpmath`? There are ways around it, but simplest precaution is to make sure the python psi4 cmake is detecting (look in `<objdir>/CMakeCache.txt`; influence through `cmake -DPYTHON_EXECUTABLE=/full/path/to/bin/python`) and any conda-supplied psi dependencies are in the *same* conda environment and that that's active throughout cmake configure, `make`, `make install`, and runtime.

**Comment by xiexr151e** [comment]
The environment that I am working on had `mpmath`, and installing `mpmath` is successful. When running `conda list`, `mpmath` shows up.

How would I be able to make sure cmake is properly detecting? I have created a new environment for this installation, and only used this environment during the duration of the build.

**Comment by loriab** [comment]
If you update your code (`git pull origin master` if you direct cloned or `git pull upstream master` if you forked, then cloned, then added a remote; look at `git remote -v` to see which is pointing to psi4/psi4), no `mpmath` should now be needed. Remove your `<objdir>/` and reissue `cmake` and recompile.
