### ISSUE TITLE
Psi4 1.2 Release Candidate and Release Dates

### ISSUE THREAD

**Issue by dgasmith** [psi4/psi4#960]
A snapshot that will be used as the first 1.2 release candidate will happen on May 1st. On May 1st the master branch will undergo a new feature freeze and will only accept bug fixes. The target release date of Psi4 1.2 is May 18th if no major bugs are found in the intervening period.

- The Psi4 Dev Team

**Comment by dgasmith** [comment]
Reminder: Feature freeze is in 4 days (May 1st)! At this point this means that currently open PR's are the only ones that can likely get in. If you have a new feature wanting to get into the Psi4 1.2 release, please contact us today.

**Comment by loriab** [comment]
## Known Bugs for RC1

* [ ] Functionals wrong, [description](https://github.com/psi4/psi4/pull/961#issuecomment-385090273). Only seen for one computer, so just watch and report.
* [ ] FCIDUMP for UHF refs failing, [description](https://github.com/psi4/psi4/issues/980). Shows up [in test case](https://github.com/psi4/psi4/blob/master/tests/fcidump/input.dat#L15-L23), currently suppressed.
* [ ] New `MemJK` gives wrong answers when auxiliary basis is Cartesian, [for description, search "cart" here](https://github.com/psi4/psi4/pull/961)
* [ ] ERD and SIMINT show all sorts of broken-like behavior upon interface. Only compilation I've gotten to work is a pure-GNU one, none with Intel. So some Intel vectorization operation is the suspect (though why is it still failing with debug ...).

**Comment by dgasmith** [comment]
`MEM_JK` and `DISK_JK` need dock lines. Mentioned [here](http://forum.psicode.org/t/manual-update-dfocc-requires-scf-type-disk-df/904/2).

**Comment by loriab** [comment]
1.2rc2 was tagged last week. Please try it out and report problems here on GitHub. Linux installers and packages available from http://vergil.chemistry.gatech.edu/nu-psicode/install-v1.2rc2.html .

**Comment by dgasmith** [comment]
Psi4 has been released, closing this.
