### ISSUE TITLE
Strange M05-2X Gradient Behavior

### ISSUE THREAD

**Issue by dsirianni** [psi4/psi4#962]
## Description
During the course of one of my projects, where I was attempting to perform very tight optimizations of nonbonded clusters with DFT, I encountered some very strange noise in the DF-M05-2X analytic gradients with Psi4.  The noise actually prevented us from successfully converging several optimizations to `g_convergence interfrag_tight`.

I've attached [this file](https://github.com/psi4/psi4/files/1908011/summary.txt) which contains a variety of gradients, computed using a new-ish version of Psi4 (1.2a1), pre-inversion Psi4 (PSI 4.0.0-beta5) and Q-Chem 4.4, but I'll summarize the results here.

Modern Psi4 (1.2a1):
- Density fitting errors in M05-2X yield gradient noise of around 10^{-6} in analytic gradients vs. direct
- Increasing the grid density from the standard (72, 302) to (150, 434) can result in differences as large as 10^{-3} for DF-M05-2X vs. 5pt FD
- Neither direct- nor DF-M05-2X match either 3- or 5-point numerical gradients, which match each other to < 10^{-7}
- DF-B97/cc-pVDZ analytic vs. 5-point FD grad match to ~10^{-5}, and DF-RHF/cc-pVDZ, direct-RHF/cc-pVDZ, & FD(5pt)-RHF/cc-pVDZ all match to < 10^{-7}

Psi4 Beta5:
- Analytic DF-M05-2X gradients vs 5pt FD exhibit differences as large as 10^{-4}
- Similarly small density fitting error vs direct as in modern Psi4
- DF-RHF analytic grads match 5pt FD nearly perfectly, density fitting differences of < 10^{-5}

vs. Q-Chem 4.4 (apples-to-apples comparisons):
- Psi4 1.2a1 analytic direct-M05-2X w/ dense grids, analytic direct-RHF both agree w/ Q-Chem to 10^{-5}
- Psi4 Beta5 analytic direct-M05-2X w/ dense grids matches to ~10^{-5}, with direct-RHF matching to 10^{-7}

I'm unsure if this is an issue in the FINDIF code which may be fortuitously resolved by #884 or more of the same strange behavior noted by @CDSherrill in #867, but we thought it strange enough to want to bring it to the greater community's attention.

**Comment by dgasmith** [comment]
This is not particularly surprising as the M0x functionals use rather high polynomials in the density which exacerbate their grid dependency and general stability. 

To be extra sure can you run a few other meta-GGA's that are not of the M0x series to check their stability. That could potentially be telling, especially if this is with regard to our meta-GGA gradient code or LibXC's kernels.

**Comment by dsirianni** [comment]
Testing the gradients of dlDF/cc-pVDZ, I see similar differences between analytic and numerical gradients with modern Psi4 (1.2a1.dev829):

- Density fitting error <= 10^{-6}
- Differences b/t analytic & numerical as large as ~10^{-4}
- Nearly no difference between analytic gradients computed w/ standard and dense grids; numerical gradients differ by nearly 10^{-4} between dense and standard grids

For anyone interested, I've uploaded a file containing the raw gradients [here](https://github.com/psi4/psi4/files/1919924/dlDF_summary.txt) for perusal.  These observations would seemingly point towards libXC kernel instabilities for meta-GGAs, instead of a more targeted problem with our M05-2X gradients in particular, exactly in line with @dgasmith's prediction.

**Comment by dgasmith** [comment]
Two comments:
 - `dlDF` is based off M05, you might want to try TPSS or SCAN.
 - I am not really sure this clears our derivative code from problems. All meta functionals use the same integration code and could still be a problem.

**Comment by hokru** [comment]
careful with SCAN though.I don't know how Q-chem implemented this functional, but the Turbomole implementation requires quite a hefty increase in radial grid points to get gradients usable for optimizations. Angular grid is unproblematic.

**Comment by susilehtola** [comment]
SCAN is crazy grid dependent. You might need up to 500 radial points to get single points with microhartree accuracy.

**Comment by CDSherrill** [comment]
I have noticed some other general gradient weirdness that might or might
not be related.  I'll try to post that as another issue as soon as I get a
chance.

**Comment by dgasmith** [comment]
Playing around with absolute errors between finite difference and analytical for a UKS water cation (mean/max):
```
# Cation Water
B3LYP   - 0.000005 / 0.000019
TPSS    - 0.000259 / 0.001291
TPSS    - 0.000264 / 0.001321 #  (150, 434) 
M05     - 0.001182 / 0.006572
```

Big kick from GGA -> MGGA as commented. Now what if we run UKS and RKS gradients on a neutral molecule:
```
# Neutral Water
RKS TPSS   - 0.000007 / 0.000024
UKS TPSS   - 0.000007 / 0.000024
RKS M05    - 0.000020 / 0.000091
UKS M05    - 0.000012 / 0.000091
```

So now we know pretty much that the XC input and output is correct, the integration of the XC data to gradient is correct, and that the normal XC data to AO gradient integration is correct. With this knowledge we are left with a single piece of code that could be [wrong](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libfock/v.cc#L2477-L2496).

We therefore spot the error (a good exercise before looking at the answer) and we now get the following:

```
# Cation Water - fixed
RKS TPSS   - 0.000007 / 0.000024
UKS TPSS   - 0.000007 / 0.000028
RKS M05    - 0.000020 / 0.000091
UKS M05    - 0.000012 / 0.000050
```

This makes me happy.
