### ISSUE TITLE
missing symbol for JK object in plugins

### ISSUE THREAD

**Issue by edeprince3** [psi4/psi4#971]
I recently updated my copy of psi4, and I'm now having plugin issues.  I added "PSI_API" where appropriate, and my plugins compile, but I get missing symbol errors for the JK object constructor:

Attention! This SCF may be density-fitted.
dyld: lazy symbol binding failed: Symbol not found: __ZN3psi4PKJKC1ENSt3__110shared_ptrINS_8BasisSetEEERNS_7OptionsE
  Referenced from: /Users/deprince/edeprince3/deprince-group/plugins/does_jk_work/does_jk_work.so
  Expected in: flat namespace

dyld: Symbol not found: __ZN3psi4PKJKC1ENSt3__110shared_ptrINS_8BasisSetEEERNS_7OptionsE
  Referenced from: /Users/deprince/edeprince3/deprince-group/plugins/does_jk_work/does_jk_work.so
  Expected in: flat namespace

Abort trap: 6

This error is for a clean plugin that only calls the constructor for PKJK:

extern "C" PSI_API
SharedWavefunction does_jk_work(SharedWavefunction ref_wfn, Options& options)
{
    int print = options.get_int("PRINT");

    /* Your code goes here */

    std::shared_ptr<PKJK> jk (new PKJK(ref_wfn->basisset(),options));

    // Typically you would build a new wavefunction and populate it with data
    return ref_wfn;
}

**Comment by edeprince3** [comment]
My original issue was for a mac, but I see the same error on linux with intel18 compilers:

deprince_root@ed7:~/does_jk_work$ psi4
Attention! This SCF may be density-fitted.
/usr/bin/python3: symbol lookup error: /edfs/users/deprince/does_jk_work/does_jk_work.so: undefined symbol: _ZN3psi4PKJKC1ESt10shared_ptrINS_8BasisSetEERNS_7OptionsE

I don't understand what is going on.  For previously functioning plugins, symbols are missing for only certain classes.  I've noticed this for PK/DFJK and VBase so far.

**Comment by loriab** [comment]
Run c++filt on that symbol and also grep it in nm psi4.so to see if it’s hidden (lc) or visible (uc). There’s lots of useful stuff not exported yet, but perhaps something more going on.

**Comment by edeprince3** [comment]
c++filt __ZN3psi4PKJKC1ENSt3__110shared_ptrINS_8BasisSetEEERNS_7OptionsE
psi::PKJK::PKJK(std::__1::shared_ptr<psi::BasisSet>, psi::Options&)

I'm not sure what this tells me.  Regarding the symbol in core.so, it is there:

(11:48 ~/software/psi4/install/lib/psi4/) nm core.so  | grep __ZN3psi4PKJKC1ENSt3__110shared_ptrINS_8BasisSetEEERNS_7OptionsE
0000000000f0a730 t __ZN3psi4PKJKC1ENSt3__110shared_ptrINS_8BasisSetEEERNS_7OptionsE

**Comment by edeprince3** [comment]
Is there any chance this issue is related to the comments about -fvisibility in #814 ?

**Comment by loriab** [comment]
Yes, definitely related to #814. Sorry, you were talking about `PSI_API` so comfortably, I thought you were already adept at expanding psi's exported symbols. The `t` in the `nm core.so | grep` means that one's still hidden. Youv'e tried turning https://github.com/psi4/psi4/blob/0da1e693534f1dc08b00a4ab860f5c6309b649d8/psi4/src/psi4/libfock/jk.h#L571 into `class PSI_API PKJK` adding header `pragma.h` if necessary?

**Comment by edeprince3** [comment]
@loriab , you are the best.  I changed the class into class PSI_API PKJK, and all is well.  So, should I make a PR for every case I encounter where my plugins can't see the symbols?

**Comment by loriab** [comment]
My fault for not realizing you had only seen one half of the `PSI_API` additions. Yes, please add any you need psi-side and PR 'em all. [Here's](https://github.com/psi4/psi4/pull/955/files) more examples.
