### ISSUE TITLE
Psi4 1.3 Planning Document

### ISSUE THREAD

**Issue by loriab** [psi4/psi4#972]
A place to stash "next-release" items that come up that don't fit elsewhere. Who knows what the next release will be called — "1.3" shall be used as placeholder.

This is for opinions as well as consensus, so don't read this and consider anything BDFL-PEP-Approved. Similarly, if you're posting for more than yourself, try to convey a notion of the breadth of agreement.

Also, separate issues by post so up/downvotes have a chance to mean something.

**Comment by loriab** [comment]
* Regarding the pybind11-2.1-motivated explicit declaration of exported symbols via `PSI_API`, most of the core-dev team agrees with "We used to have to declare our ABI as our API, I kind of feel like this is a chance to declare a C++ API we feel happy about."

**Comment by loriab** [comment]
Most everyone I've talked to (core-dev, BDFL, limited users) is ok with 1.3 being Python 3.6+

**Comment by loriab** [comment]
Let's make 1.2 the last release w/o IR intensities.

**Comment by dgasmith** [comment]
- Switch SCF iterations to Python.
- Add stability analysis for all SCF Wavefunctions via a generic Python Davidson solver.
- Add a smart SCF iterator that can make decisions on the fly of what type of step to take.

**Comment by loriab** [comment]
optking --> pyoptking

**Comment by loriab** [comment]
There's some build-time --> run-time transitions that wouldn't be too hard.
- [ ] libefp --> pylibefp (in #953)
- [ ] gdma --> py-wrapped gdma exe
- [ ] chemps2 --> pychemps2

**Comment by loriab** [comment]
- [ ] Finally use upstream Libxc (in #1101)

**Comment by loriab** [comment]
### Tentative Roadmap
- [ ] **1.3a1** when Windows ready
- alphas as needed by downstream users who needs tags
- [ ] **feature freeze** & **1.3rc1** 1 Oct 2018
- rc's as needed until code settles
- [ ] **1.3** 1 Nov 2018
- [ ] **PsiCon2018** 9–10 Nov 2018 @ GT

**Comment by loriab** [comment]
To my surprise, consensus at the psi conf call was to release 1.3 sooner rather than later. This is part of an effort to make releases not a 2 month production but a more frequent and non-intensive and non-manic-sprint-to-get-your-feature-in-this-year occurrence.

**To that end, we're planning on Feature Freeze on Monday, 10 December 2018. Considerable apologies for the short notice.**

* Naturally, bug fixes allowed after FF
* We're not averse to 1.3.1, etc.
* v1.4 anticipated May–July 2019

**Comment by dgasmith** [comment]
Release v1.3 has been feature complete for a bit now and rc1/2 are now out. See #1406 for patch notes.
