### ISSUE TITLE
SCF stability analysis with FOLLOW needs some love

### ISSUE THREAD

**Issue by TiborGY** [psi4/psi4#973]
SCF stability analysis with FOLLOW is currently only implemented for UHF. RHF and ROHF have stability analysis, but do not have the capability to follow the instability. This is not documented at all, as far as I can tell, and what is even worse is that if the user requests a FOLLOW with RHF, it "fails" silently.
That is, the SCF and the stability analysis is run, and even if there is an instability Psi4 just carries on.

So I propose two short term solutions:
1. Update the docs to make it clear that FOLLOW is currently an UHF only feature.
2. Implement checks against the user requesting FOLLOW with RHF or ROHF. I think exiting with error is the reasonable action when the user requests an unavailable feature.

Of course the long term solution would be to implement follow for R(O)HF, but that is probably more of a wishlist item, than anything else.

I found these issues a while ago and planned to fix them myself, but never got around to actually do so, and will not have the time to work on them before the 1.2 release.

**Comment by dgasmith** [comment]
For the long-term we have the required Hessian-vector products. We need #886 would allow us to optimize them, planned for 1.3 when Python-SCF iterations go live.

Please do make a PR for 1) and 2) as they are quite needed before 1.2 is released.

**Comment by jgonthier** [comment]
If I remember correctly, the other problem with RHF/ROHF stability analysis is that they do a very costly explicit inversion of the Hessian instead of using Hessian-vector products.

**Comment by amjames** [comment]
Since there has been no action on this I'm going to take care of 1/2 above so that it makes the 1.2 release.
