### ISSUE TITLE
FCIDUMP for UHF references

### ISSUE THREAD

**Issue by robertodr** [psi4/psi4#980]
As noted by @loriab, the UHF FCIDUMP files seem erratic when it comes to the number of nonzero two-electron integrals printed out. I am tracking down the problem.
The current FCIDUMP functionality is a rewrite of the plugin @jsspencer wrote for Psi4 1.1 [available here](https://github.com/hande-qmc/fcidump) I have a reference UHF/cc-pVDZ output file and integral dump for Ne and I notice that the current incarnation of the functionality prints 300 MO TEIs _less_ than the original plugin. Looking at the output files I see the following output from `MintsHelper`:
   - **Reference**
      ```
      Computing two-electron integrals...done
      Computed 861 non-zero two-electron integrals.
        Stored in file 33.
      ```
     [ne.in.log](https://github.com/psi4/psi4/files/1947119/ne.in.log)
     [NE.CC-PVDZ.UHF.PLUGINDUMP.ref.log](https://github.com/psi4/psi4/files/1947108/NE.CC-PVDZ.UHF.PLUGINDUMP.ref.log)
     [ne.ref.log](https://github.com/psi4/psi4/files/1948145/ne.ref.log)
   - **Current implementation**
     ```
     Computing two-electron integrals...done
     Computed 794 non-zero two-electron integrals.
       Stored in file 33.
     ``` 
     [input.py.log](https://github.com/psi4/psi4/files/1947121/input.py.log)
     [Ne.cc-pVDZ.UHF.INTDUMP.log](https://github.com/psi4/psi4/files/1947113/Ne.cc-pVDZ.UHF.INTDUMP.log)
     [Ne.cc-pVDZ.UHF.dat.log](https://github.com/psi4/psi4/files/1947114/Ne.cc-pVDZ.UHF.dat.log)

I cannot see how the two calculations differ. Does anybody have a clue @jturney @dgasmith?

**EDIT** I've cut the reference output to only include the problematic calculation: Ne, cc-pVDZ, UHF reference, with symmetry.

**Comment by dgasmith** [comment]
For fun, I computed the SCF energy from these DUMP files and both sum to the same SCF energy. It looks more like a representation issue than an actual bug. Its probably worth running these through a downstream program and seeing the result.

**Comment by loriab** [comment]
If it was purely representation, then test case shouldn't have failed. Or check on test was too tight.

**Comment by dgasmith** [comment]
The test case checks individual integral values. In this particular case there are a infinite number of representations that give equivalent results as the test is a single atom. This has stung us a few times before in things like `cube` and similar where we purposefully build C1 molecules in frozen cartesian space to prevent this issue.

**Comment by loriab** [comment]
Indeed, considering the nature of the test, [my comment](https://github.com/psi4/psi4/issues/980#issuecomment-385264045) was wrongheaded.
