### ISSUE TITLE
occupation per irrep print-out for c1 sym

### ISSUE THREAD

**Issue by hokru** [psi4/psi4#991]
In the given format I would expect that `A` equals `Total`.
Though this is essentially just cosmetics.

```
  ==> Pre-Iterations <==

   -------------------------------------------------------
    Irrep   Nso     Nmo     Nalpha   Nbeta   Ndocc  Nsocc
   -------------------------------------------------------
     A        300     300       0       0       0       0
   -------------------------------------------------------
    Total     300     300     180     180     180       0
   -------------------------------------------------------

```

**Comment by dgasmith** [comment]
In the general case occupations are not yet known as SCF has not started, it would be a bit of a workaround assign them here as they are only known for C1. Wouldn't this be slightly inconsistent between C1/non-C1? I believe if you assign occupations by hand they are printed at this stage.

**Comment by hokru** [comment]
OK, maybe I dont fully understand the purpose of this print out then.

**Comment by dgasmith** [comment]
Perhaps we could make this more clear? I think if you had an issue understanding what this was supposed to mean others will have as well.

**Comment by hokru** [comment]
I never **really** looked at what it meant and where it occurred and assumed these are the starting occupations, ie. including the MO guess, but the guess is done in the next step.

Printing the actual occupations after all types of guesses are done seemed like the natural thing.
